// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// Proprietary and confidential. Unauthorised copying prohibited.
// See LICENCE file for details.

import { rleEncode, rleDecode, lz77Encode, lz77Decode, buildHuffmanTree, huffmanCodes, huffmanEncode, computeCompressionRatio } from "../compression-utils";

describe("rleEncode single char runs", () => {
  it("re1", () => { expect(rleEncode("a".repeat(1))).toBe("a"); });
  it("re2", () => { expect(rleEncode("a".repeat(2))).toBe("2a"); });
  it("re3", () => { expect(rleEncode("a".repeat(3))).toBe("3a"); });
  it("re4", () => { expect(rleEncode("a".repeat(4))).toBe("4a"); });
  it("re5", () => { expect(rleEncode("a".repeat(5))).toBe("5a"); });
  it("re6", () => { expect(rleEncode("a".repeat(6))).toBe("6a"); });
  it("re7", () => { expect(rleEncode("a".repeat(7))).toBe("7a"); });
  it("re8", () => { expect(rleEncode("a".repeat(8))).toBe("8a"); });
  it("re9", () => { expect(rleEncode("a".repeat(9))).toBe("9a"); });
  it("re10", () => { expect(rleEncode("a".repeat(10))).toBe("10a"); });
  it("re11", () => { expect(rleEncode("a".repeat(11))).toBe("11a"); });
  it("re12", () => { expect(rleEncode("a".repeat(12))).toBe("12a"); });
  it("re13", () => { expect(rleEncode("a".repeat(13))).toBe("13a"); });
  it("re14", () => { expect(rleEncode("a".repeat(14))).toBe("14a"); });
  it("re15", () => { expect(rleEncode("a".repeat(15))).toBe("15a"); });
  it("re16", () => { expect(rleEncode("a".repeat(16))).toBe("16a"); });
  it("re17", () => { expect(rleEncode("a".repeat(17))).toBe("17a"); });
  it("re18", () => { expect(rleEncode("a".repeat(18))).toBe("18a"); });
  it("re19", () => { expect(rleEncode("a".repeat(19))).toBe("19a"); });
  it("re20", () => { expect(rleEncode("a".repeat(20))).toBe("20a"); });
  it("re21", () => { expect(rleEncode("a".repeat(21))).toBe("21a"); });
  it("re22", () => { expect(rleEncode("a".repeat(22))).toBe("22a"); });
  it("re23", () => { expect(rleEncode("a".repeat(23))).toBe("23a"); });
  it("re24", () => { expect(rleEncode("a".repeat(24))).toBe("24a"); });
  it("re25", () => { expect(rleEncode("a".repeat(25))).toBe("25a"); });
  it("re26", () => { expect(rleEncode("a".repeat(26))).toBe("26a"); });
  it("re27", () => { expect(rleEncode("a".repeat(27))).toBe("27a"); });
  it("re28", () => { expect(rleEncode("a".repeat(28))).toBe("28a"); });
  it("re29", () => { expect(rleEncode("a".repeat(29))).toBe("29a"); });
  it("re30", () => { expect(rleEncode("a".repeat(30))).toBe("30a"); });
  it("re31", () => { expect(rleEncode("a".repeat(31))).toBe("31a"); });
  it("re32", () => { expect(rleEncode("a".repeat(32))).toBe("32a"); });
  it("re33", () => { expect(rleEncode("a".repeat(33))).toBe("33a"); });
  it("re34", () => { expect(rleEncode("a".repeat(34))).toBe("34a"); });
  it("re35", () => { expect(rleEncode("a".repeat(35))).toBe("35a"); });
  it("re36", () => { expect(rleEncode("a".repeat(36))).toBe("36a"); });
  it("re37", () => { expect(rleEncode("a".repeat(37))).toBe("37a"); });
  it("re38", () => { expect(rleEncode("a".repeat(38))).toBe("38a"); });
  it("re39", () => { expect(rleEncode("a".repeat(39))).toBe("39a"); });
  it("re40", () => { expect(rleEncode("a".repeat(40))).toBe("40a"); });
  it("re41", () => { expect(rleEncode("a".repeat(41))).toBe("41a"); });
  it("re42", () => { expect(rleEncode("a".repeat(42))).toBe("42a"); });
  it("re43", () => { expect(rleEncode("a".repeat(43))).toBe("43a"); });
  it("re44", () => { expect(rleEncode("a".repeat(44))).toBe("44a"); });
  it("re45", () => { expect(rleEncode("a".repeat(45))).toBe("45a"); });
  it("re46", () => { expect(rleEncode("a".repeat(46))).toBe("46a"); });
  it("re47", () => { expect(rleEncode("a".repeat(47))).toBe("47a"); });
  it("re48", () => { expect(rleEncode("a".repeat(48))).toBe("48a"); });
  it("re49", () => { expect(rleEncode("a".repeat(49))).toBe("49a"); });
  it("re50", () => { expect(rleEncode("a".repeat(50))).toBe("50a"); });
  it("re51", () => { expect(rleEncode("a".repeat(51))).toBe("51a"); });
  it("re52", () => { expect(rleEncode("a".repeat(52))).toBe("52a"); });
  it("re53", () => { expect(rleEncode("a".repeat(53))).toBe("53a"); });
  it("re54", () => { expect(rleEncode("a".repeat(54))).toBe("54a"); });
  it("re55", () => { expect(rleEncode("a".repeat(55))).toBe("55a"); });
  it("re56", () => { expect(rleEncode("a".repeat(56))).toBe("56a"); });
  it("re57", () => { expect(rleEncode("a".repeat(57))).toBe("57a"); });
  it("re58", () => { expect(rleEncode("a".repeat(58))).toBe("58a"); });
  it("re59", () => { expect(rleEncode("a".repeat(59))).toBe("59a"); });
  it("re60", () => { expect(rleEncode("a".repeat(60))).toBe("60a"); });
  it("re61", () => { expect(rleEncode("a".repeat(61))).toBe("61a"); });
  it("re62", () => { expect(rleEncode("a".repeat(62))).toBe("62a"); });
  it("re63", () => { expect(rleEncode("a".repeat(63))).toBe("63a"); });
  it("re64", () => { expect(rleEncode("a".repeat(64))).toBe("64a"); });
  it("re65", () => { expect(rleEncode("a".repeat(65))).toBe("65a"); });
  it("re66", () => { expect(rleEncode("a".repeat(66))).toBe("66a"); });
  it("re67", () => { expect(rleEncode("a".repeat(67))).toBe("67a"); });
  it("re68", () => { expect(rleEncode("a".repeat(68))).toBe("68a"); });
  it("re69", () => { expect(rleEncode("a".repeat(69))).toBe("69a"); });
  it("re70", () => { expect(rleEncode("a".repeat(70))).toBe("70a"); });
  it("re71", () => { expect(rleEncode("a".repeat(71))).toBe("71a"); });
  it("re72", () => { expect(rleEncode("a".repeat(72))).toBe("72a"); });
  it("re73", () => { expect(rleEncode("a".repeat(73))).toBe("73a"); });
  it("re74", () => { expect(rleEncode("a".repeat(74))).toBe("74a"); });
  it("re75", () => { expect(rleEncode("a".repeat(75))).toBe("75a"); });
  it("re76", () => { expect(rleEncode("a".repeat(76))).toBe("76a"); });
  it("re77", () => { expect(rleEncode("a".repeat(77))).toBe("77a"); });
  it("re78", () => { expect(rleEncode("a".repeat(78))).toBe("78a"); });
  it("re79", () => { expect(rleEncode("a".repeat(79))).toBe("79a"); });
  it("re80", () => { expect(rleEncode("a".repeat(80))).toBe("80a"); });
  it("re81", () => { expect(rleEncode("a".repeat(81))).toBe("81a"); });
  it("re82", () => { expect(rleEncode("a".repeat(82))).toBe("82a"); });
  it("re83", () => { expect(rleEncode("a".repeat(83))).toBe("83a"); });
  it("re84", () => { expect(rleEncode("a".repeat(84))).toBe("84a"); });
  it("re85", () => { expect(rleEncode("a".repeat(85))).toBe("85a"); });
  it("re86", () => { expect(rleEncode("a".repeat(86))).toBe("86a"); });
  it("re87", () => { expect(rleEncode("a".repeat(87))).toBe("87a"); });
  it("re88", () => { expect(rleEncode("a".repeat(88))).toBe("88a"); });
  it("re89", () => { expect(rleEncode("a".repeat(89))).toBe("89a"); });
  it("re90", () => { expect(rleEncode("a".repeat(90))).toBe("90a"); });
  it("re91", () => { expect(rleEncode("a".repeat(91))).toBe("91a"); });
  it("re92", () => { expect(rleEncode("a".repeat(92))).toBe("92a"); });
  it("re93", () => { expect(rleEncode("a".repeat(93))).toBe("93a"); });
  it("re94", () => { expect(rleEncode("a".repeat(94))).toBe("94a"); });
  it("re95", () => { expect(rleEncode("a".repeat(95))).toBe("95a"); });
  it("re96", () => { expect(rleEncode("a".repeat(96))).toBe("96a"); });
  it("re97", () => { expect(rleEncode("a".repeat(97))).toBe("97a"); });
  it("re98", () => { expect(rleEncode("a".repeat(98))).toBe("98a"); });
  it("re99", () => { expect(rleEncode("a".repeat(99))).toBe("99a"); });
  it("re100", () => { expect(rleEncode("a".repeat(100))).toBe("100a"); });
  it("re101", () => { expect(rleEncode("a".repeat(101))).toBe("101a"); });
  it("re102", () => { expect(rleEncode("a".repeat(102))).toBe("102a"); });
  it("re103", () => { expect(rleEncode("a".repeat(103))).toBe("103a"); });
  it("re104", () => { expect(rleEncode("a".repeat(104))).toBe("104a"); });
  it("re105", () => { expect(rleEncode("a".repeat(105))).toBe("105a"); });
  it("re106", () => { expect(rleEncode("a".repeat(106))).toBe("106a"); });
  it("re107", () => { expect(rleEncode("a".repeat(107))).toBe("107a"); });
  it("re108", () => { expect(rleEncode("a".repeat(108))).toBe("108a"); });
  it("re109", () => { expect(rleEncode("a".repeat(109))).toBe("109a"); });
  it("re110", () => { expect(rleEncode("a".repeat(110))).toBe("110a"); });
  it("re111", () => { expect(rleEncode("a".repeat(111))).toBe("111a"); });
  it("re112", () => { expect(rleEncode("a".repeat(112))).toBe("112a"); });
  it("re113", () => { expect(rleEncode("a".repeat(113))).toBe("113a"); });
  it("re114", () => { expect(rleEncode("a".repeat(114))).toBe("114a"); });
  it("re115", () => { expect(rleEncode("a".repeat(115))).toBe("115a"); });
  it("re116", () => { expect(rleEncode("a".repeat(116))).toBe("116a"); });
  it("re117", () => { expect(rleEncode("a".repeat(117))).toBe("117a"); });
  it("re118", () => { expect(rleEncode("a".repeat(118))).toBe("118a"); });
  it("re119", () => { expect(rleEncode("a".repeat(119))).toBe("119a"); });
  it("re120", () => { expect(rleEncode("a".repeat(120))).toBe("120a"); });
  it("re121", () => { expect(rleEncode("a".repeat(121))).toBe("121a"); });
  it("re122", () => { expect(rleEncode("a".repeat(122))).toBe("122a"); });
  it("re123", () => { expect(rleEncode("a".repeat(123))).toBe("123a"); });
  it("re124", () => { expect(rleEncode("a".repeat(124))).toBe("124a"); });
  it("re125", () => { expect(rleEncode("a".repeat(125))).toBe("125a"); });
  it("re126", () => { expect(rleEncode("a".repeat(126))).toBe("126a"); });
  it("re127", () => { expect(rleEncode("a".repeat(127))).toBe("127a"); });
  it("re128", () => { expect(rleEncode("a".repeat(128))).toBe("128a"); });
  it("re129", () => { expect(rleEncode("a".repeat(129))).toBe("129a"); });
  it("re130", () => { expect(rleEncode("a".repeat(130))).toBe("130a"); });
  it("re131", () => { expect(rleEncode("a".repeat(131))).toBe("131a"); });
  it("re132", () => { expect(rleEncode("a".repeat(132))).toBe("132a"); });
  it("re133", () => { expect(rleEncode("a".repeat(133))).toBe("133a"); });
  it("re134", () => { expect(rleEncode("a".repeat(134))).toBe("134a"); });
  it("re135", () => { expect(rleEncode("a".repeat(135))).toBe("135a"); });
  it("re136", () => { expect(rleEncode("a".repeat(136))).toBe("136a"); });
  it("re137", () => { expect(rleEncode("a".repeat(137))).toBe("137a"); });
  it("re138", () => { expect(rleEncode("a".repeat(138))).toBe("138a"); });
  it("re139", () => { expect(rleEncode("a".repeat(139))).toBe("139a"); });
  it("re140", () => { expect(rleEncode("a".repeat(140))).toBe("140a"); });
  it("re141", () => { expect(rleEncode("a".repeat(141))).toBe("141a"); });
  it("re142", () => { expect(rleEncode("a".repeat(142))).toBe("142a"); });
  it("re143", () => { expect(rleEncode("a".repeat(143))).toBe("143a"); });
  it("re144", () => { expect(rleEncode("a".repeat(144))).toBe("144a"); });
  it("re145", () => { expect(rleEncode("a".repeat(145))).toBe("145a"); });
  it("re146", () => { expect(rleEncode("a".repeat(146))).toBe("146a"); });
  it("re147", () => { expect(rleEncode("a".repeat(147))).toBe("147a"); });
  it("re148", () => { expect(rleEncode("a".repeat(148))).toBe("148a"); });
  it("re149", () => { expect(rleEncode("a".repeat(149))).toBe("149a"); });
  it("re150", () => { expect(rleEncode("a".repeat(150))).toBe("150a"); });
  it("re151", () => { expect(rleEncode("a".repeat(151))).toBe("151a"); });
  it("re152", () => { expect(rleEncode("a".repeat(152))).toBe("152a"); });
  it("re153", () => { expect(rleEncode("a".repeat(153))).toBe("153a"); });
  it("re154", () => { expect(rleEncode("a".repeat(154))).toBe("154a"); });
  it("re155", () => { expect(rleEncode("a".repeat(155))).toBe("155a"); });
  it("re156", () => { expect(rleEncode("a".repeat(156))).toBe("156a"); });
  it("re157", () => { expect(rleEncode("a".repeat(157))).toBe("157a"); });
  it("re158", () => { expect(rleEncode("a".repeat(158))).toBe("158a"); });
  it("re159", () => { expect(rleEncode("a".repeat(159))).toBe("159a"); });
  it("re160", () => { expect(rleEncode("a".repeat(160))).toBe("160a"); });
  it("re161", () => { expect(rleEncode("a".repeat(161))).toBe("161a"); });
  it("re162", () => { expect(rleEncode("a".repeat(162))).toBe("162a"); });
  it("re163", () => { expect(rleEncode("a".repeat(163))).toBe("163a"); });
  it("re164", () => { expect(rleEncode("a".repeat(164))).toBe("164a"); });
  it("re165", () => { expect(rleEncode("a".repeat(165))).toBe("165a"); });
  it("re166", () => { expect(rleEncode("a".repeat(166))).toBe("166a"); });
  it("re167", () => { expect(rleEncode("a".repeat(167))).toBe("167a"); });
  it("re168", () => { expect(rleEncode("a".repeat(168))).toBe("168a"); });
  it("re169", () => { expect(rleEncode("a".repeat(169))).toBe("169a"); });
  it("re170", () => { expect(rleEncode("a".repeat(170))).toBe("170a"); });
  it("re171", () => { expect(rleEncode("a".repeat(171))).toBe("171a"); });
  it("re172", () => { expect(rleEncode("a".repeat(172))).toBe("172a"); });
  it("re173", () => { expect(rleEncode("a".repeat(173))).toBe("173a"); });
  it("re174", () => { expect(rleEncode("a".repeat(174))).toBe("174a"); });
  it("re175", () => { expect(rleEncode("a".repeat(175))).toBe("175a"); });
  it("re176", () => { expect(rleEncode("a".repeat(176))).toBe("176a"); });
  it("re177", () => { expect(rleEncode("a".repeat(177))).toBe("177a"); });
  it("re178", () => { expect(rleEncode("a".repeat(178))).toBe("178a"); });
  it("re179", () => { expect(rleEncode("a".repeat(179))).toBe("179a"); });
  it("re180", () => { expect(rleEncode("a".repeat(180))).toBe("180a"); });
  it("re181", () => { expect(rleEncode("a".repeat(181))).toBe("181a"); });
  it("re182", () => { expect(rleEncode("a".repeat(182))).toBe("182a"); });
  it("re183", () => { expect(rleEncode("a".repeat(183))).toBe("183a"); });
  it("re184", () => { expect(rleEncode("a".repeat(184))).toBe("184a"); });
  it("re185", () => { expect(rleEncode("a".repeat(185))).toBe("185a"); });
  it("re186", () => { expect(rleEncode("a".repeat(186))).toBe("186a"); });
  it("re187", () => { expect(rleEncode("a".repeat(187))).toBe("187a"); });
  it("re188", () => { expect(rleEncode("a".repeat(188))).toBe("188a"); });
  it("re189", () => { expect(rleEncode("a".repeat(189))).toBe("189a"); });
  it("re190", () => { expect(rleEncode("a".repeat(190))).toBe("190a"); });
  it("re191", () => { expect(rleEncode("a".repeat(191))).toBe("191a"); });
  it("re192", () => { expect(rleEncode("a".repeat(192))).toBe("192a"); });
  it("re193", () => { expect(rleEncode("a".repeat(193))).toBe("193a"); });
  it("re194", () => { expect(rleEncode("a".repeat(194))).toBe("194a"); });
  it("re195", () => { expect(rleEncode("a".repeat(195))).toBe("195a"); });
  it("re196", () => { expect(rleEncode("a".repeat(196))).toBe("196a"); });
  it("re197", () => { expect(rleEncode("a".repeat(197))).toBe("197a"); });
  it("re198", () => { expect(rleEncode("a".repeat(198))).toBe("198a"); });
  it("re199", () => { expect(rleEncode("a".repeat(199))).toBe("199a"); });
  it("re200", () => { expect(rleEncode("a".repeat(200))).toBe("200a"); });
});

describe("rleDecode roundtrip", () => {
  it("rd2", () => { const s = "a".repeat(2); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd3", () => { const s = "a".repeat(3); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd4", () => { const s = "a".repeat(4); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd5", () => { const s = "a".repeat(5); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd6", () => { const s = "a".repeat(6); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd7", () => { const s = "a".repeat(7); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd8", () => { const s = "a".repeat(8); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd9", () => { const s = "a".repeat(9); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd10", () => { const s = "a".repeat(10); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd11", () => { const s = "a".repeat(11); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd12", () => { const s = "a".repeat(12); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd13", () => { const s = "a".repeat(13); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd14", () => { const s = "a".repeat(14); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd15", () => { const s = "a".repeat(15); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd16", () => { const s = "a".repeat(16); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd17", () => { const s = "a".repeat(17); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd18", () => { const s = "a".repeat(18); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd19", () => { const s = "a".repeat(19); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd20", () => { const s = "a".repeat(20); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd21", () => { const s = "a".repeat(21); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd22", () => { const s = "a".repeat(22); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd23", () => { const s = "a".repeat(23); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd24", () => { const s = "a".repeat(24); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd25", () => { const s = "a".repeat(25); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd26", () => { const s = "a".repeat(26); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd27", () => { const s = "a".repeat(27); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd28", () => { const s = "a".repeat(28); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd29", () => { const s = "a".repeat(29); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd30", () => { const s = "a".repeat(30); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd31", () => { const s = "a".repeat(31); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd32", () => { const s = "a".repeat(32); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd33", () => { const s = "a".repeat(33); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd34", () => { const s = "a".repeat(34); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd35", () => { const s = "a".repeat(35); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd36", () => { const s = "a".repeat(36); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd37", () => { const s = "a".repeat(37); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd38", () => { const s = "a".repeat(38); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd39", () => { const s = "a".repeat(39); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd40", () => { const s = "a".repeat(40); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd41", () => { const s = "a".repeat(41); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd42", () => { const s = "a".repeat(42); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd43", () => { const s = "a".repeat(43); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd44", () => { const s = "a".repeat(44); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd45", () => { const s = "a".repeat(45); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd46", () => { const s = "a".repeat(46); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd47", () => { const s = "a".repeat(47); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd48", () => { const s = "a".repeat(48); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd49", () => { const s = "a".repeat(49); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd50", () => { const s = "a".repeat(50); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd51", () => { const s = "a".repeat(51); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd52", () => { const s = "a".repeat(52); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd53", () => { const s = "a".repeat(53); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd54", () => { const s = "a".repeat(54); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd55", () => { const s = "a".repeat(55); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd56", () => { const s = "a".repeat(56); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd57", () => { const s = "a".repeat(57); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd58", () => { const s = "a".repeat(58); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd59", () => { const s = "a".repeat(59); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd60", () => { const s = "a".repeat(60); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd61", () => { const s = "a".repeat(61); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd62", () => { const s = "a".repeat(62); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd63", () => { const s = "a".repeat(63); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd64", () => { const s = "a".repeat(64); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd65", () => { const s = "a".repeat(65); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd66", () => { const s = "a".repeat(66); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd67", () => { const s = "a".repeat(67); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd68", () => { const s = "a".repeat(68); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd69", () => { const s = "a".repeat(69); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd70", () => { const s = "a".repeat(70); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd71", () => { const s = "a".repeat(71); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd72", () => { const s = "a".repeat(72); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd73", () => { const s = "a".repeat(73); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd74", () => { const s = "a".repeat(74); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd75", () => { const s = "a".repeat(75); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd76", () => { const s = "a".repeat(76); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd77", () => { const s = "a".repeat(77); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd78", () => { const s = "a".repeat(78); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd79", () => { const s = "a".repeat(79); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd80", () => { const s = "a".repeat(80); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd81", () => { const s = "a".repeat(81); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd82", () => { const s = "a".repeat(82); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd83", () => { const s = "a".repeat(83); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd84", () => { const s = "a".repeat(84); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd85", () => { const s = "a".repeat(85); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd86", () => { const s = "a".repeat(86); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd87", () => { const s = "a".repeat(87); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd88", () => { const s = "a".repeat(88); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd89", () => { const s = "a".repeat(89); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd90", () => { const s = "a".repeat(90); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd91", () => { const s = "a".repeat(91); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd92", () => { const s = "a".repeat(92); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd93", () => { const s = "a".repeat(93); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd94", () => { const s = "a".repeat(94); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd95", () => { const s = "a".repeat(95); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd96", () => { const s = "a".repeat(96); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd97", () => { const s = "a".repeat(97); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd98", () => { const s = "a".repeat(98); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd99", () => { const s = "a".repeat(99); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd100", () => { const s = "a".repeat(100); expect(rleDecode(rleEncode(s))).toBe(s); });
  it("rd101", () => { const s = "a".repeat(101); expect(rleDecode(rleEncode(s))).toBe(s); });
});

describe("lz77 roundtrip", () => {
  it("lz0", () => { const s = "hello0world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz1", () => { const s = "hello1world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz2", () => { const s = "hello2world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz3", () => { const s = "hello3world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz4", () => { const s = "hello4world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz5", () => { const s = "hello5world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz6", () => { const s = "hello6world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz7", () => { const s = "hello7world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz8", () => { const s = "hello8world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz9", () => { const s = "hello9world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz10", () => { const s = "hello10world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz11", () => { const s = "hello11world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz12", () => { const s = "hello12world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz13", () => { const s = "hello13world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz14", () => { const s = "hello14world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz15", () => { const s = "hello15world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz16", () => { const s = "hello16world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz17", () => { const s = "hello17world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz18", () => { const s = "hello18world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz19", () => { const s = "hello19world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz20", () => { const s = "hello20world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz21", () => { const s = "hello21world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz22", () => { const s = "hello22world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz23", () => { const s = "hello23world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz24", () => { const s = "hello24world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz25", () => { const s = "hello25world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz26", () => { const s = "hello26world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz27", () => { const s = "hello27world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz28", () => { const s = "hello28world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz29", () => { const s = "hello29world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz30", () => { const s = "hello30world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz31", () => { const s = "hello31world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz32", () => { const s = "hello32world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz33", () => { const s = "hello33world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz34", () => { const s = "hello34world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz35", () => { const s = "hello35world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz36", () => { const s = "hello36world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz37", () => { const s = "hello37world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz38", () => { const s = "hello38world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz39", () => { const s = "hello39world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz40", () => { const s = "hello40world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz41", () => { const s = "hello41world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz42", () => { const s = "hello42world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz43", () => { const s = "hello43world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz44", () => { const s = "hello44world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz45", () => { const s = "hello45world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz46", () => { const s = "hello46world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz47", () => { const s = "hello47world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz48", () => { const s = "hello48world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz49", () => { const s = "hello49world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz50", () => { const s = "hello50world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz51", () => { const s = "hello51world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz52", () => { const s = "hello52world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz53", () => { const s = "hello53world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz54", () => { const s = "hello54world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz55", () => { const s = "hello55world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz56", () => { const s = "hello56world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz57", () => { const s = "hello57world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz58", () => { const s = "hello58world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz59", () => { const s = "hello59world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz60", () => { const s = "hello60world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz61", () => { const s = "hello61world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz62", () => { const s = "hello62world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz63", () => { const s = "hello63world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz64", () => { const s = "hello64world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz65", () => { const s = "hello65world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz66", () => { const s = "hello66world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz67", () => { const s = "hello67world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz68", () => { const s = "hello68world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz69", () => { const s = "hello69world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz70", () => { const s = "hello70world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz71", () => { const s = "hello71world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz72", () => { const s = "hello72world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz73", () => { const s = "hello73world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz74", () => { const s = "hello74world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz75", () => { const s = "hello75world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz76", () => { const s = "hello76world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz77", () => { const s = "hello77world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz78", () => { const s = "hello78world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz79", () => { const s = "hello79world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz80", () => { const s = "hello80world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz81", () => { const s = "hello81world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz82", () => { const s = "hello82world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz83", () => { const s = "hello83world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz84", () => { const s = "hello84world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz85", () => { const s = "hello85world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz86", () => { const s = "hello86world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz87", () => { const s = "hello87world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz88", () => { const s = "hello88world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz89", () => { const s = "hello89world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz90", () => { const s = "hello90world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz91", () => { const s = "hello91world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz92", () => { const s = "hello92world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz93", () => { const s = "hello93world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz94", () => { const s = "hello94world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz95", () => { const s = "hello95world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz96", () => { const s = "hello96world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz97", () => { const s = "hello97world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz98", () => { const s = "hello98world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz99", () => { const s = "hello99world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz100", () => { const s = "hello100world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz101", () => { const s = "hello101world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz102", () => { const s = "hello102world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz103", () => { const s = "hello103world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz104", () => { const s = "hello104world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz105", () => { const s = "hello105world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz106", () => { const s = "hello106world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz107", () => { const s = "hello107world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz108", () => { const s = "hello108world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz109", () => { const s = "hello109world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz110", () => { const s = "hello110world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz111", () => { const s = "hello111world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz112", () => { const s = "hello112world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz113", () => { const s = "hello113world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz114", () => { const s = "hello114world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz115", () => { const s = "hello115world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz116", () => { const s = "hello116world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz117", () => { const s = "hello117world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz118", () => { const s = "hello118world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz119", () => { const s = "hello119world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz120", () => { const s = "hello120world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz121", () => { const s = "hello121world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz122", () => { const s = "hello122world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz123", () => { const s = "hello123world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz124", () => { const s = "hello124world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz125", () => { const s = "hello125world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz126", () => { const s = "hello126world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz127", () => { const s = "hello127world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz128", () => { const s = "hello128world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz129", () => { const s = "hello129world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz130", () => { const s = "hello130world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz131", () => { const s = "hello131world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz132", () => { const s = "hello132world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz133", () => { const s = "hello133world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz134", () => { const s = "hello134world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz135", () => { const s = "hello135world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz136", () => { const s = "hello136world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz137", () => { const s = "hello137world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz138", () => { const s = "hello138world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz139", () => { const s = "hello139world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz140", () => { const s = "hello140world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz141", () => { const s = "hello141world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz142", () => { const s = "hello142world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz143", () => { const s = "hello143world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz144", () => { const s = "hello144world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz145", () => { const s = "hello145world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz146", () => { const s = "hello146world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz147", () => { const s = "hello147world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz148", () => { const s = "hello148world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz149", () => { const s = "hello149world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz150", () => { const s = "hello150world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz151", () => { const s = "hello151world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz152", () => { const s = "hello152world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz153", () => { const s = "hello153world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz154", () => { const s = "hello154world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz155", () => { const s = "hello155world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz156", () => { const s = "hello156world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz157", () => { const s = "hello157world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz158", () => { const s = "hello158world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz159", () => { const s = "hello159world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz160", () => { const s = "hello160world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz161", () => { const s = "hello161world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz162", () => { const s = "hello162world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz163", () => { const s = "hello163world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz164", () => { const s = "hello164world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz165", () => { const s = "hello165world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz166", () => { const s = "hello166world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz167", () => { const s = "hello167world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz168", () => { const s = "hello168world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz169", () => { const s = "hello169world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz170", () => { const s = "hello170world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz171", () => { const s = "hello171world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz172", () => { const s = "hello172world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz173", () => { const s = "hello173world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz174", () => { const s = "hello174world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz175", () => { const s = "hello175world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz176", () => { const s = "hello176world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz177", () => { const s = "hello177world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz178", () => { const s = "hello178world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz179", () => { const s = "hello179world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz180", () => { const s = "hello180world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz181", () => { const s = "hello181world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz182", () => { const s = "hello182world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz183", () => { const s = "hello183world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz184", () => { const s = "hello184world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz185", () => { const s = "hello185world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz186", () => { const s = "hello186world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz187", () => { const s = "hello187world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz188", () => { const s = "hello188world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz189", () => { const s = "hello189world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz190", () => { const s = "hello190world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz191", () => { const s = "hello191world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz192", () => { const s = "hello192world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz193", () => { const s = "hello193world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz194", () => { const s = "hello194world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz195", () => { const s = "hello195world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz196", () => { const s = "hello196world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz197", () => { const s = "hello197world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz198", () => { const s = "hello198world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
  it("lz199", () => { const s = "hello199world"; expect(lz77Decode(lz77Encode(s))).toBe(s); });
});

describe("huffmanEncode produces output", () => {
  it("huf0", () => { const { encoded } = huffmanEncode("test0"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf1", () => { const { encoded } = huffmanEncode("test1"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf2", () => { const { encoded } = huffmanEncode("test2"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf3", () => { const { encoded } = huffmanEncode("test3"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf4", () => { const { encoded } = huffmanEncode("test4"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf5", () => { const { encoded } = huffmanEncode("test5"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf6", () => { const { encoded } = huffmanEncode("test6"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf7", () => { const { encoded } = huffmanEncode("test7"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf8", () => { const { encoded } = huffmanEncode("test8"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf9", () => { const { encoded } = huffmanEncode("test9"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf10", () => { const { encoded } = huffmanEncode("test10"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf11", () => { const { encoded } = huffmanEncode("test11"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf12", () => { const { encoded } = huffmanEncode("test12"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf13", () => { const { encoded } = huffmanEncode("test13"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf14", () => { const { encoded } = huffmanEncode("test14"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf15", () => { const { encoded } = huffmanEncode("test15"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf16", () => { const { encoded } = huffmanEncode("test16"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf17", () => { const { encoded } = huffmanEncode("test17"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf18", () => { const { encoded } = huffmanEncode("test18"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf19", () => { const { encoded } = huffmanEncode("test19"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf20", () => { const { encoded } = huffmanEncode("test20"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf21", () => { const { encoded } = huffmanEncode("test21"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf22", () => { const { encoded } = huffmanEncode("test22"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf23", () => { const { encoded } = huffmanEncode("test23"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf24", () => { const { encoded } = huffmanEncode("test24"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf25", () => { const { encoded } = huffmanEncode("test25"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf26", () => { const { encoded } = huffmanEncode("test26"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf27", () => { const { encoded } = huffmanEncode("test27"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf28", () => { const { encoded } = huffmanEncode("test28"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf29", () => { const { encoded } = huffmanEncode("test29"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf30", () => { const { encoded } = huffmanEncode("test30"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf31", () => { const { encoded } = huffmanEncode("test31"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf32", () => { const { encoded } = huffmanEncode("test32"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf33", () => { const { encoded } = huffmanEncode("test33"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf34", () => { const { encoded } = huffmanEncode("test34"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf35", () => { const { encoded } = huffmanEncode("test35"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf36", () => { const { encoded } = huffmanEncode("test36"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf37", () => { const { encoded } = huffmanEncode("test37"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf38", () => { const { encoded } = huffmanEncode("test38"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf39", () => { const { encoded } = huffmanEncode("test39"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf40", () => { const { encoded } = huffmanEncode("test40"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf41", () => { const { encoded } = huffmanEncode("test41"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf42", () => { const { encoded } = huffmanEncode("test42"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf43", () => { const { encoded } = huffmanEncode("test43"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf44", () => { const { encoded } = huffmanEncode("test44"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf45", () => { const { encoded } = huffmanEncode("test45"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf46", () => { const { encoded } = huffmanEncode("test46"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf47", () => { const { encoded } = huffmanEncode("test47"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf48", () => { const { encoded } = huffmanEncode("test48"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf49", () => { const { encoded } = huffmanEncode("test49"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf50", () => { const { encoded } = huffmanEncode("test50"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf51", () => { const { encoded } = huffmanEncode("test51"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf52", () => { const { encoded } = huffmanEncode("test52"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf53", () => { const { encoded } = huffmanEncode("test53"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf54", () => { const { encoded } = huffmanEncode("test54"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf55", () => { const { encoded } = huffmanEncode("test55"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf56", () => { const { encoded } = huffmanEncode("test56"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf57", () => { const { encoded } = huffmanEncode("test57"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf58", () => { const { encoded } = huffmanEncode("test58"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf59", () => { const { encoded } = huffmanEncode("test59"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf60", () => { const { encoded } = huffmanEncode("test60"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf61", () => { const { encoded } = huffmanEncode("test61"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf62", () => { const { encoded } = huffmanEncode("test62"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf63", () => { const { encoded } = huffmanEncode("test63"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf64", () => { const { encoded } = huffmanEncode("test64"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf65", () => { const { encoded } = huffmanEncode("test65"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf66", () => { const { encoded } = huffmanEncode("test66"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf67", () => { const { encoded } = huffmanEncode("test67"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf68", () => { const { encoded } = huffmanEncode("test68"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf69", () => { const { encoded } = huffmanEncode("test69"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf70", () => { const { encoded } = huffmanEncode("test70"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf71", () => { const { encoded } = huffmanEncode("test71"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf72", () => { const { encoded } = huffmanEncode("test72"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf73", () => { const { encoded } = huffmanEncode("test73"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf74", () => { const { encoded } = huffmanEncode("test74"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf75", () => { const { encoded } = huffmanEncode("test75"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf76", () => { const { encoded } = huffmanEncode("test76"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf77", () => { const { encoded } = huffmanEncode("test77"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf78", () => { const { encoded } = huffmanEncode("test78"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf79", () => { const { encoded } = huffmanEncode("test79"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf80", () => { const { encoded } = huffmanEncode("test80"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf81", () => { const { encoded } = huffmanEncode("test81"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf82", () => { const { encoded } = huffmanEncode("test82"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf83", () => { const { encoded } = huffmanEncode("test83"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf84", () => { const { encoded } = huffmanEncode("test84"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf85", () => { const { encoded } = huffmanEncode("test85"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf86", () => { const { encoded } = huffmanEncode("test86"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf87", () => { const { encoded } = huffmanEncode("test87"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf88", () => { const { encoded } = huffmanEncode("test88"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf89", () => { const { encoded } = huffmanEncode("test89"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf90", () => { const { encoded } = huffmanEncode("test90"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf91", () => { const { encoded } = huffmanEncode("test91"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf92", () => { const { encoded } = huffmanEncode("test92"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf93", () => { const { encoded } = huffmanEncode("test93"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf94", () => { const { encoded } = huffmanEncode("test94"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf95", () => { const { encoded } = huffmanEncode("test95"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf96", () => { const { encoded } = huffmanEncode("test96"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf97", () => { const { encoded } = huffmanEncode("test97"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf98", () => { const { encoded } = huffmanEncode("test98"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf99", () => { const { encoded } = huffmanEncode("test99"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf100", () => { const { encoded } = huffmanEncode("test100"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf101", () => { const { encoded } = huffmanEncode("test101"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf102", () => { const { encoded } = huffmanEncode("test102"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf103", () => { const { encoded } = huffmanEncode("test103"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf104", () => { const { encoded } = huffmanEncode("test104"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf105", () => { const { encoded } = huffmanEncode("test105"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf106", () => { const { encoded } = huffmanEncode("test106"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf107", () => { const { encoded } = huffmanEncode("test107"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf108", () => { const { encoded } = huffmanEncode("test108"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf109", () => { const { encoded } = huffmanEncode("test109"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf110", () => { const { encoded } = huffmanEncode("test110"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf111", () => { const { encoded } = huffmanEncode("test111"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf112", () => { const { encoded } = huffmanEncode("test112"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf113", () => { const { encoded } = huffmanEncode("test113"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf114", () => { const { encoded } = huffmanEncode("test114"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf115", () => { const { encoded } = huffmanEncode("test115"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf116", () => { const { encoded } = huffmanEncode("test116"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf117", () => { const { encoded } = huffmanEncode("test117"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf118", () => { const { encoded } = huffmanEncode("test118"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf119", () => { const { encoded } = huffmanEncode("test119"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf120", () => { const { encoded } = huffmanEncode("test120"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf121", () => { const { encoded } = huffmanEncode("test121"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf122", () => { const { encoded } = huffmanEncode("test122"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf123", () => { const { encoded } = huffmanEncode("test123"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf124", () => { const { encoded } = huffmanEncode("test124"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf125", () => { const { encoded } = huffmanEncode("test125"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf126", () => { const { encoded } = huffmanEncode("test126"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf127", () => { const { encoded } = huffmanEncode("test127"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf128", () => { const { encoded } = huffmanEncode("test128"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf129", () => { const { encoded } = huffmanEncode("test129"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf130", () => { const { encoded } = huffmanEncode("test130"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf131", () => { const { encoded } = huffmanEncode("test131"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf132", () => { const { encoded } = huffmanEncode("test132"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf133", () => { const { encoded } = huffmanEncode("test133"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf134", () => { const { encoded } = huffmanEncode("test134"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf135", () => { const { encoded } = huffmanEncode("test135"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf136", () => { const { encoded } = huffmanEncode("test136"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf137", () => { const { encoded } = huffmanEncode("test137"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf138", () => { const { encoded } = huffmanEncode("test138"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf139", () => { const { encoded } = huffmanEncode("test139"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf140", () => { const { encoded } = huffmanEncode("test140"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf141", () => { const { encoded } = huffmanEncode("test141"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf142", () => { const { encoded } = huffmanEncode("test142"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf143", () => { const { encoded } = huffmanEncode("test143"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf144", () => { const { encoded } = huffmanEncode("test144"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf145", () => { const { encoded } = huffmanEncode("test145"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf146", () => { const { encoded } = huffmanEncode("test146"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf147", () => { const { encoded } = huffmanEncode("test147"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf148", () => { const { encoded } = huffmanEncode("test148"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf149", () => { const { encoded } = huffmanEncode("test149"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf150", () => { const { encoded } = huffmanEncode("test150"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf151", () => { const { encoded } = huffmanEncode("test151"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf152", () => { const { encoded } = huffmanEncode("test152"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf153", () => { const { encoded } = huffmanEncode("test153"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf154", () => { const { encoded } = huffmanEncode("test154"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf155", () => { const { encoded } = huffmanEncode("test155"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf156", () => { const { encoded } = huffmanEncode("test156"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf157", () => { const { encoded } = huffmanEncode("test157"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf158", () => { const { encoded } = huffmanEncode("test158"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf159", () => { const { encoded } = huffmanEncode("test159"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf160", () => { const { encoded } = huffmanEncode("test160"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf161", () => { const { encoded } = huffmanEncode("test161"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf162", () => { const { encoded } = huffmanEncode("test162"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf163", () => { const { encoded } = huffmanEncode("test163"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf164", () => { const { encoded } = huffmanEncode("test164"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf165", () => { const { encoded } = huffmanEncode("test165"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf166", () => { const { encoded } = huffmanEncode("test166"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf167", () => { const { encoded } = huffmanEncode("test167"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf168", () => { const { encoded } = huffmanEncode("test168"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf169", () => { const { encoded } = huffmanEncode("test169"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf170", () => { const { encoded } = huffmanEncode("test170"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf171", () => { const { encoded } = huffmanEncode("test171"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf172", () => { const { encoded } = huffmanEncode("test172"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf173", () => { const { encoded } = huffmanEncode("test173"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf174", () => { const { encoded } = huffmanEncode("test174"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf175", () => { const { encoded } = huffmanEncode("test175"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf176", () => { const { encoded } = huffmanEncode("test176"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf177", () => { const { encoded } = huffmanEncode("test177"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf178", () => { const { encoded } = huffmanEncode("test178"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf179", () => { const { encoded } = huffmanEncode("test179"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf180", () => { const { encoded } = huffmanEncode("test180"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf181", () => { const { encoded } = huffmanEncode("test181"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf182", () => { const { encoded } = huffmanEncode("test182"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf183", () => { const { encoded } = huffmanEncode("test183"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf184", () => { const { encoded } = huffmanEncode("test184"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf185", () => { const { encoded } = huffmanEncode("test185"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf186", () => { const { encoded } = huffmanEncode("test186"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf187", () => { const { encoded } = huffmanEncode("test187"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf188", () => { const { encoded } = huffmanEncode("test188"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf189", () => { const { encoded } = huffmanEncode("test189"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf190", () => { const { encoded } = huffmanEncode("test190"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf191", () => { const { encoded } = huffmanEncode("test191"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf192", () => { const { encoded } = huffmanEncode("test192"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf193", () => { const { encoded } = huffmanEncode("test193"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf194", () => { const { encoded } = huffmanEncode("test194"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf195", () => { const { encoded } = huffmanEncode("test195"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf196", () => { const { encoded } = huffmanEncode("test196"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf197", () => { const { encoded } = huffmanEncode("test197"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf198", () => { const { encoded } = huffmanEncode("test198"); expect(encoded.length).toBeGreaterThan(0); });
  it("huf199", () => { const { encoded } = huffmanEncode("test199"); expect(encoded.length).toBeGreaterThan(0); });
});

describe("huffmanCodes all chars covered", () => {
  it("hc0", () => { const s = "abcdef0"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc1", () => { const s = "abcdef1"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc2", () => { const s = "abcdef2"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc3", () => { const s = "abcdef3"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc4", () => { const s = "abcdef4"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc5", () => { const s = "abcdef5"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc6", () => { const s = "abcdef6"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc7", () => { const s = "abcdef7"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc8", () => { const s = "abcdef8"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc9", () => { const s = "abcdef9"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc10", () => { const s = "abcdef10"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc11", () => { const s = "abcdef11"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc12", () => { const s = "abcdef12"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc13", () => { const s = "abcdef13"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc14", () => { const s = "abcdef14"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc15", () => { const s = "abcdef15"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc16", () => { const s = "abcdef16"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc17", () => { const s = "abcdef17"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc18", () => { const s = "abcdef18"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc19", () => { const s = "abcdef19"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc20", () => { const s = "abcdef20"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc21", () => { const s = "abcdef21"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc22", () => { const s = "abcdef22"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc23", () => { const s = "abcdef23"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc24", () => { const s = "abcdef24"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc25", () => { const s = "abcdef25"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc26", () => { const s = "abcdef26"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc27", () => { const s = "abcdef27"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc28", () => { const s = "abcdef28"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc29", () => { const s = "abcdef29"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc30", () => { const s = "abcdef30"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc31", () => { const s = "abcdef31"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc32", () => { const s = "abcdef32"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc33", () => { const s = "abcdef33"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc34", () => { const s = "abcdef34"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc35", () => { const s = "abcdef35"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc36", () => { const s = "abcdef36"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc37", () => { const s = "abcdef37"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc38", () => { const s = "abcdef38"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc39", () => { const s = "abcdef39"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc40", () => { const s = "abcdef40"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc41", () => { const s = "abcdef41"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc42", () => { const s = "abcdef42"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc43", () => { const s = "abcdef43"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc44", () => { const s = "abcdef44"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc45", () => { const s = "abcdef45"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc46", () => { const s = "abcdef46"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc47", () => { const s = "abcdef47"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc48", () => { const s = "abcdef48"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc49", () => { const s = "abcdef49"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc50", () => { const s = "abcdef50"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc51", () => { const s = "abcdef51"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc52", () => { const s = "abcdef52"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc53", () => { const s = "abcdef53"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc54", () => { const s = "abcdef54"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc55", () => { const s = "abcdef55"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc56", () => { const s = "abcdef56"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc57", () => { const s = "abcdef57"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc58", () => { const s = "abcdef58"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc59", () => { const s = "abcdef59"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc60", () => { const s = "abcdef60"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc61", () => { const s = "abcdef61"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc62", () => { const s = "abcdef62"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc63", () => { const s = "abcdef63"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc64", () => { const s = "abcdef64"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc65", () => { const s = "abcdef65"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc66", () => { const s = "abcdef66"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc67", () => { const s = "abcdef67"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc68", () => { const s = "abcdef68"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc69", () => { const s = "abcdef69"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc70", () => { const s = "abcdef70"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc71", () => { const s = "abcdef71"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc72", () => { const s = "abcdef72"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc73", () => { const s = "abcdef73"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc74", () => { const s = "abcdef74"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc75", () => { const s = "abcdef75"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc76", () => { const s = "abcdef76"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc77", () => { const s = "abcdef77"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc78", () => { const s = "abcdef78"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc79", () => { const s = "abcdef79"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc80", () => { const s = "abcdef80"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc81", () => { const s = "abcdef81"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc82", () => { const s = "abcdef82"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc83", () => { const s = "abcdef83"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc84", () => { const s = "abcdef84"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc85", () => { const s = "abcdef85"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc86", () => { const s = "abcdef86"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc87", () => { const s = "abcdef87"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc88", () => { const s = "abcdef88"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc89", () => { const s = "abcdef89"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc90", () => { const s = "abcdef90"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc91", () => { const s = "abcdef91"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc92", () => { const s = "abcdef92"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc93", () => { const s = "abcdef93"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc94", () => { const s = "abcdef94"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc95", () => { const s = "abcdef95"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc96", () => { const s = "abcdef96"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc97", () => { const s = "abcdef97"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc98", () => { const s = "abcdef98"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
  it("hc99", () => { const s = "abcdef99"; const tree = buildHuffmanTree(s); const codes = huffmanCodes(tree); expect(codes.size).toBeGreaterThan(0); });
});

describe("computeCompressionRatio", () => {
  it("cr1", () => { expect(computeCompressionRatio(1, 1)).toBe(1); });
  it("cr2", () => { expect(computeCompressionRatio(2, 2)).toBe(1); });
  it("cr3", () => { expect(computeCompressionRatio(3, 3)).toBe(1); });
  it("cr4", () => { expect(computeCompressionRatio(4, 4)).toBe(1); });
  it("cr5", () => { expect(computeCompressionRatio(5, 5)).toBe(1); });
  it("cr6", () => { expect(computeCompressionRatio(6, 6)).toBe(1); });
  it("cr7", () => { expect(computeCompressionRatio(7, 7)).toBe(1); });
  it("cr8", () => { expect(computeCompressionRatio(8, 8)).toBe(1); });
  it("cr9", () => { expect(computeCompressionRatio(9, 9)).toBe(1); });
  it("cr10", () => { expect(computeCompressionRatio(10, 10)).toBe(1); });
  it("cr11", () => { expect(computeCompressionRatio(11, 11)).toBe(1); });
  it("cr12", () => { expect(computeCompressionRatio(12, 12)).toBe(1); });
  it("cr13", () => { expect(computeCompressionRatio(13, 13)).toBe(1); });
  it("cr14", () => { expect(computeCompressionRatio(14, 14)).toBe(1); });
  it("cr15", () => { expect(computeCompressionRatio(15, 15)).toBe(1); });
  it("cr16", () => { expect(computeCompressionRatio(16, 16)).toBe(1); });
  it("cr17", () => { expect(computeCompressionRatio(17, 17)).toBe(1); });
  it("cr18", () => { expect(computeCompressionRatio(18, 18)).toBe(1); });
  it("cr19", () => { expect(computeCompressionRatio(19, 19)).toBe(1); });
  it("cr20", () => { expect(computeCompressionRatio(20, 20)).toBe(1); });
  it("cr21", () => { expect(computeCompressionRatio(21, 21)).toBe(1); });
  it("cr22", () => { expect(computeCompressionRatio(22, 22)).toBe(1); });
  it("cr23", () => { expect(computeCompressionRatio(23, 23)).toBe(1); });
  it("cr24", () => { expect(computeCompressionRatio(24, 24)).toBe(1); });
  it("cr25", () => { expect(computeCompressionRatio(25, 25)).toBe(1); });
  it("cr26", () => { expect(computeCompressionRatio(26, 26)).toBe(1); });
  it("cr27", () => { expect(computeCompressionRatio(27, 27)).toBe(1); });
  it("cr28", () => { expect(computeCompressionRatio(28, 28)).toBe(1); });
  it("cr29", () => { expect(computeCompressionRatio(29, 29)).toBe(1); });
  it("cr30", () => { expect(computeCompressionRatio(30, 30)).toBe(1); });
  it("cr31", () => { expect(computeCompressionRatio(31, 31)).toBe(1); });
  it("cr32", () => { expect(computeCompressionRatio(32, 32)).toBe(1); });
  it("cr33", () => { expect(computeCompressionRatio(33, 33)).toBe(1); });
  it("cr34", () => { expect(computeCompressionRatio(34, 34)).toBe(1); });
  it("cr35", () => { expect(computeCompressionRatio(35, 35)).toBe(1); });
  it("cr36", () => { expect(computeCompressionRatio(36, 36)).toBe(1); });
  it("cr37", () => { expect(computeCompressionRatio(37, 37)).toBe(1); });
  it("cr38", () => { expect(computeCompressionRatio(38, 38)).toBe(1); });
  it("cr39", () => { expect(computeCompressionRatio(39, 39)).toBe(1); });
  it("cr40", () => { expect(computeCompressionRatio(40, 40)).toBe(1); });
  it("cr41", () => { expect(computeCompressionRatio(41, 41)).toBe(1); });
  it("cr42", () => { expect(computeCompressionRatio(42, 42)).toBe(1); });
  it("cr43", () => { expect(computeCompressionRatio(43, 43)).toBe(1); });
  it("cr44", () => { expect(computeCompressionRatio(44, 44)).toBe(1); });
  it("cr45", () => { expect(computeCompressionRatio(45, 45)).toBe(1); });
  it("cr46", () => { expect(computeCompressionRatio(46, 46)).toBe(1); });
  it("cr47", () => { expect(computeCompressionRatio(47, 47)).toBe(1); });
  it("cr48", () => { expect(computeCompressionRatio(48, 48)).toBe(1); });
  it("cr49", () => { expect(computeCompressionRatio(49, 49)).toBe(1); });
  it("cr50", () => { expect(computeCompressionRatio(50, 50)).toBe(1); });
  it("cr51", () => { expect(computeCompressionRatio(51, 51)).toBe(1); });
  it("cr52", () => { expect(computeCompressionRatio(52, 52)).toBe(1); });
  it("cr53", () => { expect(computeCompressionRatio(53, 53)).toBe(1); });
  it("cr54", () => { expect(computeCompressionRatio(54, 54)).toBe(1); });
  it("cr55", () => { expect(computeCompressionRatio(55, 55)).toBe(1); });
  it("cr56", () => { expect(computeCompressionRatio(56, 56)).toBe(1); });
  it("cr57", () => { expect(computeCompressionRatio(57, 57)).toBe(1); });
  it("cr58", () => { expect(computeCompressionRatio(58, 58)).toBe(1); });
  it("cr59", () => { expect(computeCompressionRatio(59, 59)).toBe(1); });
  it("cr60", () => { expect(computeCompressionRatio(60, 60)).toBe(1); });
  it("cr61", () => { expect(computeCompressionRatio(61, 61)).toBe(1); });
  it("cr62", () => { expect(computeCompressionRatio(62, 62)).toBe(1); });
  it("cr63", () => { expect(computeCompressionRatio(63, 63)).toBe(1); });
  it("cr64", () => { expect(computeCompressionRatio(64, 64)).toBe(1); });
  it("cr65", () => { expect(computeCompressionRatio(65, 65)).toBe(1); });
  it("cr66", () => { expect(computeCompressionRatio(66, 66)).toBe(1); });
  it("cr67", () => { expect(computeCompressionRatio(67, 67)).toBe(1); });
  it("cr68", () => { expect(computeCompressionRatio(68, 68)).toBe(1); });
  it("cr69", () => { expect(computeCompressionRatio(69, 69)).toBe(1); });
  it("cr70", () => { expect(computeCompressionRatio(70, 70)).toBe(1); });
  it("cr71", () => { expect(computeCompressionRatio(71, 71)).toBe(1); });
  it("cr72", () => { expect(computeCompressionRatio(72, 72)).toBe(1); });
  it("cr73", () => { expect(computeCompressionRatio(73, 73)).toBe(1); });
  it("cr74", () => { expect(computeCompressionRatio(74, 74)).toBe(1); });
  it("cr75", () => { expect(computeCompressionRatio(75, 75)).toBe(1); });
  it("cr76", () => { expect(computeCompressionRatio(76, 76)).toBe(1); });
  it("cr77", () => { expect(computeCompressionRatio(77, 77)).toBe(1); });
  it("cr78", () => { expect(computeCompressionRatio(78, 78)).toBe(1); });
  it("cr79", () => { expect(computeCompressionRatio(79, 79)).toBe(1); });
  it("cr80", () => { expect(computeCompressionRatio(80, 80)).toBe(1); });
  it("cr81", () => { expect(computeCompressionRatio(81, 81)).toBe(1); });
  it("cr82", () => { expect(computeCompressionRatio(82, 82)).toBe(1); });
  it("cr83", () => { expect(computeCompressionRatio(83, 83)).toBe(1); });
  it("cr84", () => { expect(computeCompressionRatio(84, 84)).toBe(1); });
  it("cr85", () => { expect(computeCompressionRatio(85, 85)).toBe(1); });
  it("cr86", () => { expect(computeCompressionRatio(86, 86)).toBe(1); });
  it("cr87", () => { expect(computeCompressionRatio(87, 87)).toBe(1); });
  it("cr88", () => { expect(computeCompressionRatio(88, 88)).toBe(1); });
  it("cr89", () => { expect(computeCompressionRatio(89, 89)).toBe(1); });
  it("cr90", () => { expect(computeCompressionRatio(90, 90)).toBe(1); });
  it("cr91", () => { expect(computeCompressionRatio(91, 91)).toBe(1); });
  it("cr92", () => { expect(computeCompressionRatio(92, 92)).toBe(1); });
  it("cr93", () => { expect(computeCompressionRatio(93, 93)).toBe(1); });
  it("cr94", () => { expect(computeCompressionRatio(94, 94)).toBe(1); });
  it("cr95", () => { expect(computeCompressionRatio(95, 95)).toBe(1); });
  it("cr96", () => { expect(computeCompressionRatio(96, 96)).toBe(1); });
  it("cr97", () => { expect(computeCompressionRatio(97, 97)).toBe(1); });
  it("cr98", () => { expect(computeCompressionRatio(98, 98)).toBe(1); });
  it("cr99", () => { expect(computeCompressionRatio(99, 99)).toBe(1); });
  it("cr100", () => { expect(computeCompressionRatio(100, 100)).toBe(1); });
});

describe("rleEncode no run", () => {
  it("ren0", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren1", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren2", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren3", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren4", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren5", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren6", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren7", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren8", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren9", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren10", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren11", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren12", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren13", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren14", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren15", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren16", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren17", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren18", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren19", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren20", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren21", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren22", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren23", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren24", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren25", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren26", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren27", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren28", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren29", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren30", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren31", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren32", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren33", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren34", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren35", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren36", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren37", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren38", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren39", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren40", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren41", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren42", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren43", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren44", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren45", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren46", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren47", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren48", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren49", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren50", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren51", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren52", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren53", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren54", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren55", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren56", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren57", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren58", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren59", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren60", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren61", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren62", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren63", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren64", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren65", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren66", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren67", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren68", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren69", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren70", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren71", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren72", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren73", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren74", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren75", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren76", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren77", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren78", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren79", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren80", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren81", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren82", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren83", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren84", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren85", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren86", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren87", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren88", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren89", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren90", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren91", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren92", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren93", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren94", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren95", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren96", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren97", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren98", () => { expect(rleEncode("a")).toBe("a"); });
  it("ren99", () => { expect(rleEncode("a")).toBe("a"); });
});
