// Copyright (c) 2026 Nexara DMCC. All rights reserved.
import {
  parityBit, addParityBit, checkParity, crc8, crc16, checksumMod256,
  luhnCheck, hammingWeight, hammingDistance, repeatCode, majorityVote,
  byteToBits, bitsToInt, isValidIsbn13, xorChecksum, adler32
} from "../error-correction";

describe("parityBit", () => {
  it("empty array is 0", () => { expect(parityBit([])).toBe(0); });
  it("single 1 is 1", () => { expect(parityBit([1])).toBe(1); });
  it("[1,1] is 0", () => { expect(parityBit([1,1])).toBe(0); });
  it("[1,0,1] is 0", () => { expect(parityBit([1,0,1])).toBe(0); });
  it("parityBit variant 1", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 2", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 3", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 4", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 5", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 6", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 7", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 8", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 9", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 10", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 11", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 12", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 13", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 14", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 15", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 16", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 17", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 18", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 19", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 20", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 21", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 22", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 23", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 24", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 25", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 26", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 27", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 28", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 29", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 30", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 31", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 32", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 33", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 34", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 35", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 36", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 37", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 38", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 39", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 40", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 41", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 42", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 43", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 44", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 45", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 46", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 47", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 48", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 49", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 50", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 51", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 52", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 53", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 54", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 55", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 56", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 57", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 58", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 59", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 60", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 61", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 62", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 63", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 64", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 65", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 66", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 67", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 68", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 69", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 70", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 71", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 72", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 73", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 74", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 75", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 76", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 77", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 78", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 79", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 80", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 81", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 82", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 83", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 84", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 85", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 86", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 87", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 88", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 89", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 90", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 91", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 92", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 93", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 94", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 95", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 96", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 97", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 98", () => { const b = 0; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 99", () => { const b = 1; expect(parityBit([b])).toBe(b); });
  it("parityBit variant 100", () => { const b = 0; expect(parityBit([b])).toBe(b); });
});

describe("checkParity", () => {
  it("even parity passes", () => { expect(checkParity([1,1,0])).toBe(true); });
  it("odd parity fails", () => { expect(checkParity([1,0,0])).toBe(false); });
  it("addParityBit then check passes", () => { expect(checkParity(addParityBit([1,0,1]))).toBe(true); });
  it("checkParity with addParityBit 1", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 2", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 3", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 4", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 5", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 6", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 7", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 8", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 9", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 10", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 11", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 12", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 13", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 14", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 15", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 16", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 17", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 18", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 19", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 20", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 21", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 22", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 23", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 24", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 25", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 26", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 27", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 28", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 29", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 30", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 31", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 32", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 33", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 34", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 35", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 36", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 37", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 38", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 39", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 40", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 41", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 42", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 43", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 44", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 45", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 46", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 47", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 48", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 49", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 50", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 51", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 52", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 53", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 54", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 55", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 56", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 57", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 58", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 59", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 60", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 61", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 62", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 63", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 64", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 65", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 66", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 67", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 68", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 69", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 70", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 71", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 72", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 73", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 74", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 75", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 76", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 77", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 78", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 79", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 80", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 81", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 82", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 83", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 84", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 85", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 86", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 87", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 88", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 89", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 90", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 91", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 92", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 93", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 94", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 95", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 96", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 97", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 98", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
  it("checkParity with addParityBit 99", () => { expect(checkParity(addParityBit([1]))).toBe(true); });
  it("checkParity with addParityBit 100", () => { expect(checkParity(addParityBit([0]))).toBe(true); });
});

describe("crc8", () => {
  it("empty returns 0", () => { expect(crc8([])).toBe(0); });
  it("returns number", () => { expect(typeof crc8([1,2,3])).toBe("number"); });
  it("crc8 variant 1", () => { const r = crc8([1]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 2", () => { const r = crc8([2]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 3", () => { const r = crc8([3]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 4", () => { const r = crc8([4]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 5", () => { const r = crc8([5]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 6", () => { const r = crc8([6]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 7", () => { const r = crc8([7]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 8", () => { const r = crc8([8]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 9", () => { const r = crc8([9]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 10", () => { const r = crc8([10]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 11", () => { const r = crc8([11]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 12", () => { const r = crc8([12]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 13", () => { const r = crc8([13]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 14", () => { const r = crc8([14]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 15", () => { const r = crc8([15]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 16", () => { const r = crc8([16]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 17", () => { const r = crc8([17]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 18", () => { const r = crc8([18]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 19", () => { const r = crc8([19]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 20", () => { const r = crc8([20]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 21", () => { const r = crc8([21]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 22", () => { const r = crc8([22]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 23", () => { const r = crc8([23]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 24", () => { const r = crc8([24]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 25", () => { const r = crc8([25]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 26", () => { const r = crc8([26]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 27", () => { const r = crc8([27]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 28", () => { const r = crc8([28]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 29", () => { const r = crc8([29]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 30", () => { const r = crc8([30]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 31", () => { const r = crc8([31]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 32", () => { const r = crc8([32]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 33", () => { const r = crc8([33]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 34", () => { const r = crc8([34]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 35", () => { const r = crc8([35]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 36", () => { const r = crc8([36]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 37", () => { const r = crc8([37]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 38", () => { const r = crc8([38]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 39", () => { const r = crc8([39]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 40", () => { const r = crc8([40]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 41", () => { const r = crc8([41]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 42", () => { const r = crc8([42]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 43", () => { const r = crc8([43]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 44", () => { const r = crc8([44]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 45", () => { const r = crc8([45]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 46", () => { const r = crc8([46]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 47", () => { const r = crc8([47]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 48", () => { const r = crc8([48]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 49", () => { const r = crc8([49]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 50", () => { const r = crc8([50]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 51", () => { const r = crc8([51]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 52", () => { const r = crc8([52]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 53", () => { const r = crc8([53]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 54", () => { const r = crc8([54]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 55", () => { const r = crc8([55]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 56", () => { const r = crc8([56]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 57", () => { const r = crc8([57]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 58", () => { const r = crc8([58]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 59", () => { const r = crc8([59]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 60", () => { const r = crc8([60]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 61", () => { const r = crc8([61]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 62", () => { const r = crc8([62]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 63", () => { const r = crc8([63]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 64", () => { const r = crc8([64]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 65", () => { const r = crc8([65]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 66", () => { const r = crc8([66]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 67", () => { const r = crc8([67]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 68", () => { const r = crc8([68]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 69", () => { const r = crc8([69]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 70", () => { const r = crc8([70]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 71", () => { const r = crc8([71]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 72", () => { const r = crc8([72]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 73", () => { const r = crc8([73]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 74", () => { const r = crc8([74]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 75", () => { const r = crc8([75]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 76", () => { const r = crc8([76]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 77", () => { const r = crc8([77]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 78", () => { const r = crc8([78]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 79", () => { const r = crc8([79]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 80", () => { const r = crc8([80]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 81", () => { const r = crc8([81]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 82", () => { const r = crc8([82]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 83", () => { const r = crc8([83]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 84", () => { const r = crc8([84]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 85", () => { const r = crc8([85]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 86", () => { const r = crc8([86]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 87", () => { const r = crc8([87]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 88", () => { const r = crc8([88]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 89", () => { const r = crc8([89]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 90", () => { const r = crc8([90]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 91", () => { const r = crc8([91]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 92", () => { const r = crc8([92]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 93", () => { const r = crc8([93]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 94", () => { const r = crc8([94]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 95", () => { const r = crc8([95]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 96", () => { const r = crc8([96]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 97", () => { const r = crc8([97]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 98", () => { const r = crc8([98]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 99", () => { const r = crc8([99]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 variant 100", () => { const r = crc8([100]); expect(r >= 0 && r <= 255).toBe(true); });
});

describe("crc16", () => {
  it("returns number", () => { expect(typeof crc16([1,2,3])).toBe("number"); });
  it("crc16 variant 1", () => { const r = crc16([1]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 2", () => { const r = crc16([2]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 3", () => { const r = crc16([3]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 4", () => { const r = crc16([4]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 5", () => { const r = crc16([5]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 6", () => { const r = crc16([6]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 7", () => { const r = crc16([7]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 8", () => { const r = crc16([8]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 9", () => { const r = crc16([9]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 10", () => { const r = crc16([10]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 11", () => { const r = crc16([11]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 12", () => { const r = crc16([12]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 13", () => { const r = crc16([13]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 14", () => { const r = crc16([14]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 15", () => { const r = crc16([15]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 16", () => { const r = crc16([16]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 17", () => { const r = crc16([17]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 18", () => { const r = crc16([18]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 19", () => { const r = crc16([19]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 20", () => { const r = crc16([20]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 21", () => { const r = crc16([21]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 22", () => { const r = crc16([22]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 23", () => { const r = crc16([23]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 24", () => { const r = crc16([24]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 25", () => { const r = crc16([25]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 26", () => { const r = crc16([26]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 27", () => { const r = crc16([27]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 28", () => { const r = crc16([28]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 29", () => { const r = crc16([29]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 30", () => { const r = crc16([30]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 31", () => { const r = crc16([31]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 32", () => { const r = crc16([32]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 33", () => { const r = crc16([33]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 34", () => { const r = crc16([34]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 35", () => { const r = crc16([35]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 36", () => { const r = crc16([36]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 37", () => { const r = crc16([37]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 38", () => { const r = crc16([38]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 39", () => { const r = crc16([39]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 40", () => { const r = crc16([40]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 41", () => { const r = crc16([41]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 42", () => { const r = crc16([42]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 43", () => { const r = crc16([43]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 44", () => { const r = crc16([44]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 45", () => { const r = crc16([45]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 46", () => { const r = crc16([46]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 47", () => { const r = crc16([47]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 48", () => { const r = crc16([48]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 49", () => { const r = crc16([49]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 50", () => { const r = crc16([50]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 51", () => { const r = crc16([51]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 52", () => { const r = crc16([52]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 53", () => { const r = crc16([53]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 54", () => { const r = crc16([54]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 55", () => { const r = crc16([55]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 56", () => { const r = crc16([56]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 57", () => { const r = crc16([57]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 58", () => { const r = crc16([58]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 59", () => { const r = crc16([59]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 60", () => { const r = crc16([60]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 61", () => { const r = crc16([61]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 62", () => { const r = crc16([62]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 63", () => { const r = crc16([63]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 64", () => { const r = crc16([64]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 65", () => { const r = crc16([65]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 66", () => { const r = crc16([66]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 67", () => { const r = crc16([67]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 68", () => { const r = crc16([68]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 69", () => { const r = crc16([69]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 70", () => { const r = crc16([70]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 71", () => { const r = crc16([71]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 72", () => { const r = crc16([72]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 73", () => { const r = crc16([73]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 74", () => { const r = crc16([74]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 75", () => { const r = crc16([75]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 76", () => { const r = crc16([76]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 77", () => { const r = crc16([77]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 78", () => { const r = crc16([78]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 79", () => { const r = crc16([79]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 80", () => { const r = crc16([80]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 81", () => { const r = crc16([81]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 82", () => { const r = crc16([82]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 83", () => { const r = crc16([83]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 84", () => { const r = crc16([84]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 85", () => { const r = crc16([85]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 86", () => { const r = crc16([86]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 87", () => { const r = crc16([87]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 88", () => { const r = crc16([88]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 89", () => { const r = crc16([89]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 90", () => { const r = crc16([90]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 91", () => { const r = crc16([91]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 92", () => { const r = crc16([92]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 93", () => { const r = crc16([93]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 94", () => { const r = crc16([94]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 95", () => { const r = crc16([95]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 96", () => { const r = crc16([96]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 97", () => { const r = crc16([97]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 98", () => { const r = crc16([98]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 99", () => { const r = crc16([99]); expect(r >= 0 && r <= 65535).toBe(true); });
  it("crc16 variant 100", () => { const r = crc16([100]); expect(r >= 0 && r <= 65535).toBe(true); });
});

describe("checksumMod256", () => {
  it("empty is 0", () => { expect(checksumMod256([])).toBe(0); });
  it("[1] is 1", () => { expect(checksumMod256([1])).toBe(1); });
  it("[255,1] is 0", () => { expect(checksumMod256([255,1])).toBe(0); });
  it("checksumMod256 1", () => { const r = checksumMod256([1]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 2", () => { const r = checksumMod256([2]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 3", () => { const r = checksumMod256([3]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 4", () => { const r = checksumMod256([4]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 5", () => { const r = checksumMod256([5]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 6", () => { const r = checksumMod256([6]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 7", () => { const r = checksumMod256([7]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 8", () => { const r = checksumMod256([8]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 9", () => { const r = checksumMod256([9]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 10", () => { const r = checksumMod256([10]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 11", () => { const r = checksumMod256([11]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 12", () => { const r = checksumMod256([12]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 13", () => { const r = checksumMod256([13]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 14", () => { const r = checksumMod256([14]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 15", () => { const r = checksumMod256([15]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 16", () => { const r = checksumMod256([16]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 17", () => { const r = checksumMod256([17]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 18", () => { const r = checksumMod256([18]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 19", () => { const r = checksumMod256([19]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 20", () => { const r = checksumMod256([20]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 21", () => { const r = checksumMod256([21]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 22", () => { const r = checksumMod256([22]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 23", () => { const r = checksumMod256([23]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 24", () => { const r = checksumMod256([24]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 25", () => { const r = checksumMod256([25]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 26", () => { const r = checksumMod256([26]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 27", () => { const r = checksumMod256([27]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 28", () => { const r = checksumMod256([28]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 29", () => { const r = checksumMod256([29]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 30", () => { const r = checksumMod256([30]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 31", () => { const r = checksumMod256([31]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 32", () => { const r = checksumMod256([32]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 33", () => { const r = checksumMod256([33]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 34", () => { const r = checksumMod256([34]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 35", () => { const r = checksumMod256([35]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 36", () => { const r = checksumMod256([36]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 37", () => { const r = checksumMod256([37]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 38", () => { const r = checksumMod256([38]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 39", () => { const r = checksumMod256([39]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 40", () => { const r = checksumMod256([40]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 41", () => { const r = checksumMod256([41]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 42", () => { const r = checksumMod256([42]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 43", () => { const r = checksumMod256([43]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 44", () => { const r = checksumMod256([44]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 45", () => { const r = checksumMod256([45]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 46", () => { const r = checksumMod256([46]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 47", () => { const r = checksumMod256([47]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 48", () => { const r = checksumMod256([48]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 49", () => { const r = checksumMod256([49]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 50", () => { const r = checksumMod256([50]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 51", () => { const r = checksumMod256([51]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 52", () => { const r = checksumMod256([52]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 53", () => { const r = checksumMod256([53]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 54", () => { const r = checksumMod256([54]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 55", () => { const r = checksumMod256([55]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 56", () => { const r = checksumMod256([56]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 57", () => { const r = checksumMod256([57]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 58", () => { const r = checksumMod256([58]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 59", () => { const r = checksumMod256([59]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 60", () => { const r = checksumMod256([60]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 61", () => { const r = checksumMod256([61]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 62", () => { const r = checksumMod256([62]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 63", () => { const r = checksumMod256([63]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 64", () => { const r = checksumMod256([64]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 65", () => { const r = checksumMod256([65]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 66", () => { const r = checksumMod256([66]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 67", () => { const r = checksumMod256([67]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 68", () => { const r = checksumMod256([68]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 69", () => { const r = checksumMod256([69]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 70", () => { const r = checksumMod256([70]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 71", () => { const r = checksumMod256([71]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 72", () => { const r = checksumMod256([72]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 73", () => { const r = checksumMod256([73]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 74", () => { const r = checksumMod256([74]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 75", () => { const r = checksumMod256([75]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 76", () => { const r = checksumMod256([76]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 77", () => { const r = checksumMod256([77]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 78", () => { const r = checksumMod256([78]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 79", () => { const r = checksumMod256([79]); expect(r >= 0 && r < 256).toBe(true); });
  it("checksumMod256 80", () => { const r = checksumMod256([80]); expect(r >= 0 && r < 256).toBe(true); });
});

describe("hammingWeight", () => {
  it("0 is 0", () => { expect(hammingWeight(0)).toBe(0); });
  it("1 is 1", () => { expect(hammingWeight(1)).toBe(1); });
  it("255 is 8", () => { expect(hammingWeight(255)).toBe(8); });
  it("hammingWeight(0) >=0", () => { expect(hammingWeight(0)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(1) >=0", () => { expect(hammingWeight(1)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(2) >=0", () => { expect(hammingWeight(2)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(3) >=0", () => { expect(hammingWeight(3)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(4) >=0", () => { expect(hammingWeight(4)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(5) >=0", () => { expect(hammingWeight(5)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(6) >=0", () => { expect(hammingWeight(6)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(7) >=0", () => { expect(hammingWeight(7)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(8) >=0", () => { expect(hammingWeight(8)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(9) >=0", () => { expect(hammingWeight(9)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(10) >=0", () => { expect(hammingWeight(10)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(11) >=0", () => { expect(hammingWeight(11)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(12) >=0", () => { expect(hammingWeight(12)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(13) >=0", () => { expect(hammingWeight(13)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(14) >=0", () => { expect(hammingWeight(14)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(15) >=0", () => { expect(hammingWeight(15)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(16) >=0", () => { expect(hammingWeight(16)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(17) >=0", () => { expect(hammingWeight(17)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(18) >=0", () => { expect(hammingWeight(18)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(19) >=0", () => { expect(hammingWeight(19)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(20) >=0", () => { expect(hammingWeight(20)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(21) >=0", () => { expect(hammingWeight(21)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(22) >=0", () => { expect(hammingWeight(22)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(23) >=0", () => { expect(hammingWeight(23)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(24) >=0", () => { expect(hammingWeight(24)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(25) >=0", () => { expect(hammingWeight(25)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(26) >=0", () => { expect(hammingWeight(26)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(27) >=0", () => { expect(hammingWeight(27)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(28) >=0", () => { expect(hammingWeight(28)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(29) >=0", () => { expect(hammingWeight(29)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(30) >=0", () => { expect(hammingWeight(30)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(31) >=0", () => { expect(hammingWeight(31)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(32) >=0", () => { expect(hammingWeight(32)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(33) >=0", () => { expect(hammingWeight(33)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(34) >=0", () => { expect(hammingWeight(34)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(35) >=0", () => { expect(hammingWeight(35)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(36) >=0", () => { expect(hammingWeight(36)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(37) >=0", () => { expect(hammingWeight(37)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(38) >=0", () => { expect(hammingWeight(38)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(39) >=0", () => { expect(hammingWeight(39)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(40) >=0", () => { expect(hammingWeight(40)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(41) >=0", () => { expect(hammingWeight(41)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(42) >=0", () => { expect(hammingWeight(42)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(43) >=0", () => { expect(hammingWeight(43)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(44) >=0", () => { expect(hammingWeight(44)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(45) >=0", () => { expect(hammingWeight(45)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(46) >=0", () => { expect(hammingWeight(46)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(47) >=0", () => { expect(hammingWeight(47)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(48) >=0", () => { expect(hammingWeight(48)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(49) >=0", () => { expect(hammingWeight(49)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(50) >=0", () => { expect(hammingWeight(50)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(51) >=0", () => { expect(hammingWeight(51)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(52) >=0", () => { expect(hammingWeight(52)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(53) >=0", () => { expect(hammingWeight(53)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(54) >=0", () => { expect(hammingWeight(54)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(55) >=0", () => { expect(hammingWeight(55)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(56) >=0", () => { expect(hammingWeight(56)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(57) >=0", () => { expect(hammingWeight(57)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(58) >=0", () => { expect(hammingWeight(58)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(59) >=0", () => { expect(hammingWeight(59)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(60) >=0", () => { expect(hammingWeight(60)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(61) >=0", () => { expect(hammingWeight(61)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(62) >=0", () => { expect(hammingWeight(62)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(63) >=0", () => { expect(hammingWeight(63)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(64) >=0", () => { expect(hammingWeight(64)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(65) >=0", () => { expect(hammingWeight(65)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(66) >=0", () => { expect(hammingWeight(66)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(67) >=0", () => { expect(hammingWeight(67)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(68) >=0", () => { expect(hammingWeight(68)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(69) >=0", () => { expect(hammingWeight(69)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(70) >=0", () => { expect(hammingWeight(70)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(71) >=0", () => { expect(hammingWeight(71)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(72) >=0", () => { expect(hammingWeight(72)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(73) >=0", () => { expect(hammingWeight(73)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(74) >=0", () => { expect(hammingWeight(74)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(75) >=0", () => { expect(hammingWeight(75)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(76) >=0", () => { expect(hammingWeight(76)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(77) >=0", () => { expect(hammingWeight(77)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(78) >=0", () => { expect(hammingWeight(78)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(79) >=0", () => { expect(hammingWeight(79)).toBeGreaterThanOrEqual(0); });
  it("hammingWeight(80) >=0", () => { expect(hammingWeight(80)).toBeGreaterThanOrEqual(0); });
});

describe("hammingDistance", () => {
  it("same numbers distance 0", () => { expect(hammingDistance(5,5)).toBe(0); });
  it("0 and 1 distance 1", () => { expect(hammingDistance(0,1)).toBe(1); });
  it("hammingDistance(0,0) is 0", () => { expect(hammingDistance(0,0)).toBe(0); });
  it("hammingDistance(1,1) is 0", () => { expect(hammingDistance(1,1)).toBe(0); });
  it("hammingDistance(2,2) is 0", () => { expect(hammingDistance(2,2)).toBe(0); });
  it("hammingDistance(3,3) is 0", () => { expect(hammingDistance(3,3)).toBe(0); });
  it("hammingDistance(4,4) is 0", () => { expect(hammingDistance(4,4)).toBe(0); });
  it("hammingDistance(5,5) is 0", () => { expect(hammingDistance(5,5)).toBe(0); });
  it("hammingDistance(6,6) is 0", () => { expect(hammingDistance(6,6)).toBe(0); });
  it("hammingDistance(7,7) is 0", () => { expect(hammingDistance(7,7)).toBe(0); });
  it("hammingDistance(8,8) is 0", () => { expect(hammingDistance(8,8)).toBe(0); });
  it("hammingDistance(9,9) is 0", () => { expect(hammingDistance(9,9)).toBe(0); });
  it("hammingDistance(10,10) is 0", () => { expect(hammingDistance(10,10)).toBe(0); });
  it("hammingDistance(11,11) is 0", () => { expect(hammingDistance(11,11)).toBe(0); });
  it("hammingDistance(12,12) is 0", () => { expect(hammingDistance(12,12)).toBe(0); });
  it("hammingDistance(13,13) is 0", () => { expect(hammingDistance(13,13)).toBe(0); });
  it("hammingDistance(14,14) is 0", () => { expect(hammingDistance(14,14)).toBe(0); });
  it("hammingDistance(15,15) is 0", () => { expect(hammingDistance(15,15)).toBe(0); });
  it("hammingDistance(16,16) is 0", () => { expect(hammingDistance(16,16)).toBe(0); });
  it("hammingDistance(17,17) is 0", () => { expect(hammingDistance(17,17)).toBe(0); });
  it("hammingDistance(18,18) is 0", () => { expect(hammingDistance(18,18)).toBe(0); });
  it("hammingDistance(19,19) is 0", () => { expect(hammingDistance(19,19)).toBe(0); });
  it("hammingDistance(20,20) is 0", () => { expect(hammingDistance(20,20)).toBe(0); });
  it("hammingDistance(21,21) is 0", () => { expect(hammingDistance(21,21)).toBe(0); });
  it("hammingDistance(22,22) is 0", () => { expect(hammingDistance(22,22)).toBe(0); });
  it("hammingDistance(23,23) is 0", () => { expect(hammingDistance(23,23)).toBe(0); });
  it("hammingDistance(24,24) is 0", () => { expect(hammingDistance(24,24)).toBe(0); });
  it("hammingDistance(25,25) is 0", () => { expect(hammingDistance(25,25)).toBe(0); });
  it("hammingDistance(26,26) is 0", () => { expect(hammingDistance(26,26)).toBe(0); });
  it("hammingDistance(27,27) is 0", () => { expect(hammingDistance(27,27)).toBe(0); });
  it("hammingDistance(28,28) is 0", () => { expect(hammingDistance(28,28)).toBe(0); });
  it("hammingDistance(29,29) is 0", () => { expect(hammingDistance(29,29)).toBe(0); });
  it("hammingDistance(30,30) is 0", () => { expect(hammingDistance(30,30)).toBe(0); });
  it("hammingDistance(31,31) is 0", () => { expect(hammingDistance(31,31)).toBe(0); });
  it("hammingDistance(32,32) is 0", () => { expect(hammingDistance(32,32)).toBe(0); });
  it("hammingDistance(33,33) is 0", () => { expect(hammingDistance(33,33)).toBe(0); });
  it("hammingDistance(34,34) is 0", () => { expect(hammingDistance(34,34)).toBe(0); });
  it("hammingDistance(35,35) is 0", () => { expect(hammingDistance(35,35)).toBe(0); });
  it("hammingDistance(36,36) is 0", () => { expect(hammingDistance(36,36)).toBe(0); });
  it("hammingDistance(37,37) is 0", () => { expect(hammingDistance(37,37)).toBe(0); });
  it("hammingDistance(38,38) is 0", () => { expect(hammingDistance(38,38)).toBe(0); });
  it("hammingDistance(39,39) is 0", () => { expect(hammingDistance(39,39)).toBe(0); });
  it("hammingDistance(40,40) is 0", () => { expect(hammingDistance(40,40)).toBe(0); });
  it("hammingDistance(41,41) is 0", () => { expect(hammingDistance(41,41)).toBe(0); });
  it("hammingDistance(42,42) is 0", () => { expect(hammingDistance(42,42)).toBe(0); });
  it("hammingDistance(43,43) is 0", () => { expect(hammingDistance(43,43)).toBe(0); });
  it("hammingDistance(44,44) is 0", () => { expect(hammingDistance(44,44)).toBe(0); });
  it("hammingDistance(45,45) is 0", () => { expect(hammingDistance(45,45)).toBe(0); });
  it("hammingDistance(46,46) is 0", () => { expect(hammingDistance(46,46)).toBe(0); });
  it("hammingDistance(47,47) is 0", () => { expect(hammingDistance(47,47)).toBe(0); });
  it("hammingDistance(48,48) is 0", () => { expect(hammingDistance(48,48)).toBe(0); });
  it("hammingDistance(49,49) is 0", () => { expect(hammingDistance(49,49)).toBe(0); });
  it("hammingDistance(50,50) is 0", () => { expect(hammingDistance(50,50)).toBe(0); });
  it("hammingDistance(51,51) is 0", () => { expect(hammingDistance(51,51)).toBe(0); });
  it("hammingDistance(52,52) is 0", () => { expect(hammingDistance(52,52)).toBe(0); });
  it("hammingDistance(53,53) is 0", () => { expect(hammingDistance(53,53)).toBe(0); });
  it("hammingDistance(54,54) is 0", () => { expect(hammingDistance(54,54)).toBe(0); });
  it("hammingDistance(55,55) is 0", () => { expect(hammingDistance(55,55)).toBe(0); });
  it("hammingDistance(56,56) is 0", () => { expect(hammingDistance(56,56)).toBe(0); });
  it("hammingDistance(57,57) is 0", () => { expect(hammingDistance(57,57)).toBe(0); });
  it("hammingDistance(58,58) is 0", () => { expect(hammingDistance(58,58)).toBe(0); });
  it("hammingDistance(59,59) is 0", () => { expect(hammingDistance(59,59)).toBe(0); });
  it("hammingDistance(60,60) is 0", () => { expect(hammingDistance(60,60)).toBe(0); });
  it("hammingDistance(61,61) is 0", () => { expect(hammingDistance(61,61)).toBe(0); });
  it("hammingDistance(62,62) is 0", () => { expect(hammingDistance(62,62)).toBe(0); });
  it("hammingDistance(63,63) is 0", () => { expect(hammingDistance(63,63)).toBe(0); });
  it("hammingDistance(64,64) is 0", () => { expect(hammingDistance(64,64)).toBe(0); });
  it("hammingDistance(65,65) is 0", () => { expect(hammingDistance(65,65)).toBe(0); });
  it("hammingDistance(66,66) is 0", () => { expect(hammingDistance(66,66)).toBe(0); });
  it("hammingDistance(67,67) is 0", () => { expect(hammingDistance(67,67)).toBe(0); });
  it("hammingDistance(68,68) is 0", () => { expect(hammingDistance(68,68)).toBe(0); });
  it("hammingDistance(69,69) is 0", () => { expect(hammingDistance(69,69)).toBe(0); });
  it("hammingDistance(70,70) is 0", () => { expect(hammingDistance(70,70)).toBe(0); });
  it("hammingDistance(71,71) is 0", () => { expect(hammingDistance(71,71)).toBe(0); });
  it("hammingDistance(72,72) is 0", () => { expect(hammingDistance(72,72)).toBe(0); });
  it("hammingDistance(73,73) is 0", () => { expect(hammingDistance(73,73)).toBe(0); });
  it("hammingDistance(74,74) is 0", () => { expect(hammingDistance(74,74)).toBe(0); });
  it("hammingDistance(75,75) is 0", () => { expect(hammingDistance(75,75)).toBe(0); });
  it("hammingDistance(76,76) is 0", () => { expect(hammingDistance(76,76)).toBe(0); });
  it("hammingDistance(77,77) is 0", () => { expect(hammingDistance(77,77)).toBe(0); });
  it("hammingDistance(78,78) is 0", () => { expect(hammingDistance(78,78)).toBe(0); });
  it("hammingDistance(79,79) is 0", () => { expect(hammingDistance(79,79)).toBe(0); });
  it("hammingDistance(80,80) is 0", () => { expect(hammingDistance(80,80)).toBe(0); });
});

describe("repeatCode", () => {
  it("repeat 3 of [1] gives [1,1,1]", () => { expect(repeatCode([1], 3)).toEqual([1,1,1]); });
  it("repeat 1 is identity", () => { expect(repeatCode([1,0], 1)).toEqual([1,0]); });
  it("repeatCode 1", () => { expect(repeatCode([1], 1).length).toBe(1); });
  it("repeatCode 2", () => { expect(repeatCode([1], 2).length).toBe(2); });
  it("repeatCode 3", () => { expect(repeatCode([1], 3).length).toBe(3); });
  it("repeatCode 4", () => { expect(repeatCode([1], 4).length).toBe(4); });
  it("repeatCode 5", () => { expect(repeatCode([1], 5).length).toBe(5); });
  it("repeatCode 6", () => { expect(repeatCode([1], 6).length).toBe(6); });
  it("repeatCode 7", () => { expect(repeatCode([1], 7).length).toBe(7); });
  it("repeatCode 8", () => { expect(repeatCode([1], 8).length).toBe(8); });
  it("repeatCode 9", () => { expect(repeatCode([1], 9).length).toBe(9); });
  it("repeatCode 10", () => { expect(repeatCode([1], 10).length).toBe(10); });
  it("repeatCode 11", () => { expect(repeatCode([1], 11).length).toBe(11); });
  it("repeatCode 12", () => { expect(repeatCode([1], 12).length).toBe(12); });
  it("repeatCode 13", () => { expect(repeatCode([1], 13).length).toBe(13); });
  it("repeatCode 14", () => { expect(repeatCode([1], 14).length).toBe(14); });
  it("repeatCode 15", () => { expect(repeatCode([1], 15).length).toBe(15); });
  it("repeatCode 16", () => { expect(repeatCode([1], 16).length).toBe(16); });
  it("repeatCode 17", () => { expect(repeatCode([1], 17).length).toBe(17); });
  it("repeatCode 18", () => { expect(repeatCode([1], 18).length).toBe(18); });
  it("repeatCode 19", () => { expect(repeatCode([1], 19).length).toBe(19); });
  it("repeatCode 20", () => { expect(repeatCode([1], 20).length).toBe(20); });
  it("repeatCode 21", () => { expect(repeatCode([1], 21).length).toBe(21); });
  it("repeatCode 22", () => { expect(repeatCode([1], 22).length).toBe(22); });
  it("repeatCode 23", () => { expect(repeatCode([1], 23).length).toBe(23); });
  it("repeatCode 24", () => { expect(repeatCode([1], 24).length).toBe(24); });
  it("repeatCode 25", () => { expect(repeatCode([1], 25).length).toBe(25); });
  it("repeatCode 26", () => { expect(repeatCode([1], 26).length).toBe(26); });
  it("repeatCode 27", () => { expect(repeatCode([1], 27).length).toBe(27); });
  it("repeatCode 28", () => { expect(repeatCode([1], 28).length).toBe(28); });
  it("repeatCode 29", () => { expect(repeatCode([1], 29).length).toBe(29); });
  it("repeatCode 30", () => { expect(repeatCode([1], 30).length).toBe(30); });
  it("repeatCode 31", () => { expect(repeatCode([1], 31).length).toBe(31); });
  it("repeatCode 32", () => { expect(repeatCode([1], 32).length).toBe(32); });
  it("repeatCode 33", () => { expect(repeatCode([1], 33).length).toBe(33); });
  it("repeatCode 34", () => { expect(repeatCode([1], 34).length).toBe(34); });
  it("repeatCode 35", () => { expect(repeatCode([1], 35).length).toBe(35); });
  it("repeatCode 36", () => { expect(repeatCode([1], 36).length).toBe(36); });
  it("repeatCode 37", () => { expect(repeatCode([1], 37).length).toBe(37); });
  it("repeatCode 38", () => { expect(repeatCode([1], 38).length).toBe(38); });
  it("repeatCode 39", () => { expect(repeatCode([1], 39).length).toBe(39); });
  it("repeatCode 40", () => { expect(repeatCode([1], 40).length).toBe(40); });
  it("repeatCode 41", () => { expect(repeatCode([1], 41).length).toBe(41); });
  it("repeatCode 42", () => { expect(repeatCode([1], 42).length).toBe(42); });
  it("repeatCode 43", () => { expect(repeatCode([1], 43).length).toBe(43); });
  it("repeatCode 44", () => { expect(repeatCode([1], 44).length).toBe(44); });
  it("repeatCode 45", () => { expect(repeatCode([1], 45).length).toBe(45); });
  it("repeatCode 46", () => { expect(repeatCode([1], 46).length).toBe(46); });
  it("repeatCode 47", () => { expect(repeatCode([1], 47).length).toBe(47); });
  it("repeatCode 48", () => { expect(repeatCode([1], 48).length).toBe(48); });
  it("repeatCode 49", () => { expect(repeatCode([1], 49).length).toBe(49); });
  it("repeatCode 50", () => { expect(repeatCode([1], 50).length).toBe(50); });
});

describe("byteToBits/bitsToInt", () => {
  it("0 is 8 zeros", () => { expect(byteToBits(0)).toEqual([0,0,0,0,0,0,0,0]); });
  it("255 is 8 ones", () => { expect(byteToBits(255)).toEqual([1,1,1,1,1,1,1,1]); });
  it("roundtrip works", () => { expect(bitsToInt(byteToBits(42))).toBe(42); });
  it("byteToBits roundtrip 0", () => { expect(bitsToInt(byteToBits(0))).toBe(0); });
  it("byteToBits roundtrip 1", () => { expect(bitsToInt(byteToBits(1))).toBe(1); });
  it("byteToBits roundtrip 2", () => { expect(bitsToInt(byteToBits(2))).toBe(2); });
  it("byteToBits roundtrip 3", () => { expect(bitsToInt(byteToBits(3))).toBe(3); });
  it("byteToBits roundtrip 4", () => { expect(bitsToInt(byteToBits(4))).toBe(4); });
  it("byteToBits roundtrip 5", () => { expect(bitsToInt(byteToBits(5))).toBe(5); });
  it("byteToBits roundtrip 6", () => { expect(bitsToInt(byteToBits(6))).toBe(6); });
  it("byteToBits roundtrip 7", () => { expect(bitsToInt(byteToBits(7))).toBe(7); });
  it("byteToBits roundtrip 8", () => { expect(bitsToInt(byteToBits(8))).toBe(8); });
  it("byteToBits roundtrip 9", () => { expect(bitsToInt(byteToBits(9))).toBe(9); });
  it("byteToBits roundtrip 10", () => { expect(bitsToInt(byteToBits(10))).toBe(10); });
  it("byteToBits roundtrip 11", () => { expect(bitsToInt(byteToBits(11))).toBe(11); });
  it("byteToBits roundtrip 12", () => { expect(bitsToInt(byteToBits(12))).toBe(12); });
  it("byteToBits roundtrip 13", () => { expect(bitsToInt(byteToBits(13))).toBe(13); });
  it("byteToBits roundtrip 14", () => { expect(bitsToInt(byteToBits(14))).toBe(14); });
  it("byteToBits roundtrip 15", () => { expect(bitsToInt(byteToBits(15))).toBe(15); });
  it("byteToBits roundtrip 16", () => { expect(bitsToInt(byteToBits(16))).toBe(16); });
  it("byteToBits roundtrip 17", () => { expect(bitsToInt(byteToBits(17))).toBe(17); });
  it("byteToBits roundtrip 18", () => { expect(bitsToInt(byteToBits(18))).toBe(18); });
  it("byteToBits roundtrip 19", () => { expect(bitsToInt(byteToBits(19))).toBe(19); });
  it("byteToBits roundtrip 20", () => { expect(bitsToInt(byteToBits(20))).toBe(20); });
  it("byteToBits roundtrip 21", () => { expect(bitsToInt(byteToBits(21))).toBe(21); });
  it("byteToBits roundtrip 22", () => { expect(bitsToInt(byteToBits(22))).toBe(22); });
  it("byteToBits roundtrip 23", () => { expect(bitsToInt(byteToBits(23))).toBe(23); });
  it("byteToBits roundtrip 24", () => { expect(bitsToInt(byteToBits(24))).toBe(24); });
  it("byteToBits roundtrip 25", () => { expect(bitsToInt(byteToBits(25))).toBe(25); });
  it("byteToBits roundtrip 26", () => { expect(bitsToInt(byteToBits(26))).toBe(26); });
  it("byteToBits roundtrip 27", () => { expect(bitsToInt(byteToBits(27))).toBe(27); });
  it("byteToBits roundtrip 28", () => { expect(bitsToInt(byteToBits(28))).toBe(28); });
  it("byteToBits roundtrip 29", () => { expect(bitsToInt(byteToBits(29))).toBe(29); });
  it("byteToBits roundtrip 30", () => { expect(bitsToInt(byteToBits(30))).toBe(30); });
  it("byteToBits roundtrip 31", () => { expect(bitsToInt(byteToBits(31))).toBe(31); });
  it("byteToBits roundtrip 32", () => { expect(bitsToInt(byteToBits(32))).toBe(32); });
  it("byteToBits roundtrip 33", () => { expect(bitsToInt(byteToBits(33))).toBe(33); });
  it("byteToBits roundtrip 34", () => { expect(bitsToInt(byteToBits(34))).toBe(34); });
  it("byteToBits roundtrip 35", () => { expect(bitsToInt(byteToBits(35))).toBe(35); });
  it("byteToBits roundtrip 36", () => { expect(bitsToInt(byteToBits(36))).toBe(36); });
  it("byteToBits roundtrip 37", () => { expect(bitsToInt(byteToBits(37))).toBe(37); });
  it("byteToBits roundtrip 38", () => { expect(bitsToInt(byteToBits(38))).toBe(38); });
  it("byteToBits roundtrip 39", () => { expect(bitsToInt(byteToBits(39))).toBe(39); });
  it("byteToBits roundtrip 40", () => { expect(bitsToInt(byteToBits(40))).toBe(40); });
  it("byteToBits roundtrip 41", () => { expect(bitsToInt(byteToBits(41))).toBe(41); });
  it("byteToBits roundtrip 42", () => { expect(bitsToInt(byteToBits(42))).toBe(42); });
  it("byteToBits roundtrip 43", () => { expect(bitsToInt(byteToBits(43))).toBe(43); });
  it("byteToBits roundtrip 44", () => { expect(bitsToInt(byteToBits(44))).toBe(44); });
  it("byteToBits roundtrip 45", () => { expect(bitsToInt(byteToBits(45))).toBe(45); });
  it("byteToBits roundtrip 46", () => { expect(bitsToInt(byteToBits(46))).toBe(46); });
  it("byteToBits roundtrip 47", () => { expect(bitsToInt(byteToBits(47))).toBe(47); });
  it("byteToBits roundtrip 48", () => { expect(bitsToInt(byteToBits(48))).toBe(48); });
  it("byteToBits roundtrip 49", () => { expect(bitsToInt(byteToBits(49))).toBe(49); });
  it("byteToBits roundtrip 50", () => { expect(bitsToInt(byteToBits(50))).toBe(50); });
  it("byteToBits roundtrip 51", () => { expect(bitsToInt(byteToBits(51))).toBe(51); });
  it("byteToBits roundtrip 52", () => { expect(bitsToInt(byteToBits(52))).toBe(52); });
  it("byteToBits roundtrip 53", () => { expect(bitsToInt(byteToBits(53))).toBe(53); });
  it("byteToBits roundtrip 54", () => { expect(bitsToInt(byteToBits(54))).toBe(54); });
  it("byteToBits roundtrip 55", () => { expect(bitsToInt(byteToBits(55))).toBe(55); });
  it("byteToBits roundtrip 56", () => { expect(bitsToInt(byteToBits(56))).toBe(56); });
  it("byteToBits roundtrip 57", () => { expect(bitsToInt(byteToBits(57))).toBe(57); });
  it("byteToBits roundtrip 58", () => { expect(bitsToInt(byteToBits(58))).toBe(58); });
  it("byteToBits roundtrip 59", () => { expect(bitsToInt(byteToBits(59))).toBe(59); });
  it("byteToBits roundtrip 60", () => { expect(bitsToInt(byteToBits(60))).toBe(60); });
  it("byteToBits roundtrip 61", () => { expect(bitsToInt(byteToBits(61))).toBe(61); });
  it("byteToBits roundtrip 62", () => { expect(bitsToInt(byteToBits(62))).toBe(62); });
  it("byteToBits roundtrip 63", () => { expect(bitsToInt(byteToBits(63))).toBe(63); });
  it("byteToBits roundtrip 64", () => { expect(bitsToInt(byteToBits(64))).toBe(64); });
  it("byteToBits roundtrip 65", () => { expect(bitsToInt(byteToBits(65))).toBe(65); });
  it("byteToBits roundtrip 66", () => { expect(bitsToInt(byteToBits(66))).toBe(66); });
  it("byteToBits roundtrip 67", () => { expect(bitsToInt(byteToBits(67))).toBe(67); });
  it("byteToBits roundtrip 68", () => { expect(bitsToInt(byteToBits(68))).toBe(68); });
  it("byteToBits roundtrip 69", () => { expect(bitsToInt(byteToBits(69))).toBe(69); });
  it("byteToBits roundtrip 70", () => { expect(bitsToInt(byteToBits(70))).toBe(70); });
  it("byteToBits roundtrip 71", () => { expect(bitsToInt(byteToBits(71))).toBe(71); });
  it("byteToBits roundtrip 72", () => { expect(bitsToInt(byteToBits(72))).toBe(72); });
  it("byteToBits roundtrip 73", () => { expect(bitsToInt(byteToBits(73))).toBe(73); });
  it("byteToBits roundtrip 74", () => { expect(bitsToInt(byteToBits(74))).toBe(74); });
  it("byteToBits roundtrip 75", () => { expect(bitsToInt(byteToBits(75))).toBe(75); });
  it("byteToBits roundtrip 76", () => { expect(bitsToInt(byteToBits(76))).toBe(76); });
  it("byteToBits roundtrip 77", () => { expect(bitsToInt(byteToBits(77))).toBe(77); });
  it("byteToBits roundtrip 78", () => { expect(bitsToInt(byteToBits(78))).toBe(78); });
  it("byteToBits roundtrip 79", () => { expect(bitsToInt(byteToBits(79))).toBe(79); });
  it("byteToBits roundtrip 80", () => { expect(bitsToInt(byteToBits(80))).toBe(80); });
});

describe("xorChecksum", () => {
  it("empty is 0", () => { expect(xorChecksum([])).toBe(0); });
  it("[1,1] is 0", () => { expect(xorChecksum([1,1])).toBe(0); });
  it("xorChecksum 1", () => { expect(typeof xorChecksum([1])).toBe("number"); });
  it("xorChecksum 2", () => { expect(typeof xorChecksum([2])).toBe("number"); });
  it("xorChecksum 3", () => { expect(typeof xorChecksum([3])).toBe("number"); });
  it("xorChecksum 4", () => { expect(typeof xorChecksum([4])).toBe("number"); });
  it("xorChecksum 5", () => { expect(typeof xorChecksum([5])).toBe("number"); });
  it("xorChecksum 6", () => { expect(typeof xorChecksum([6])).toBe("number"); });
  it("xorChecksum 7", () => { expect(typeof xorChecksum([7])).toBe("number"); });
  it("xorChecksum 8", () => { expect(typeof xorChecksum([8])).toBe("number"); });
  it("xorChecksum 9", () => { expect(typeof xorChecksum([9])).toBe("number"); });
  it("xorChecksum 10", () => { expect(typeof xorChecksum([10])).toBe("number"); });
  it("xorChecksum 11", () => { expect(typeof xorChecksum([11])).toBe("number"); });
  it("xorChecksum 12", () => { expect(typeof xorChecksum([12])).toBe("number"); });
  it("xorChecksum 13", () => { expect(typeof xorChecksum([13])).toBe("number"); });
  it("xorChecksum 14", () => { expect(typeof xorChecksum([14])).toBe("number"); });
  it("xorChecksum 15", () => { expect(typeof xorChecksum([15])).toBe("number"); });
  it("xorChecksum 16", () => { expect(typeof xorChecksum([16])).toBe("number"); });
  it("xorChecksum 17", () => { expect(typeof xorChecksum([17])).toBe("number"); });
  it("xorChecksum 18", () => { expect(typeof xorChecksum([18])).toBe("number"); });
  it("xorChecksum 19", () => { expect(typeof xorChecksum([19])).toBe("number"); });
  it("xorChecksum 20", () => { expect(typeof xorChecksum([20])).toBe("number"); });
  it("xorChecksum 21", () => { expect(typeof xorChecksum([21])).toBe("number"); });
  it("xorChecksum 22", () => { expect(typeof xorChecksum([22])).toBe("number"); });
  it("xorChecksum 23", () => { expect(typeof xorChecksum([23])).toBe("number"); });
  it("xorChecksum 24", () => { expect(typeof xorChecksum([24])).toBe("number"); });
  it("xorChecksum 25", () => { expect(typeof xorChecksum([25])).toBe("number"); });
  it("xorChecksum 26", () => { expect(typeof xorChecksum([26])).toBe("number"); });
  it("xorChecksum 27", () => { expect(typeof xorChecksum([27])).toBe("number"); });
  it("xorChecksum 28", () => { expect(typeof xorChecksum([28])).toBe("number"); });
  it("xorChecksum 29", () => { expect(typeof xorChecksum([29])).toBe("number"); });
  it("xorChecksum 30", () => { expect(typeof xorChecksum([30])).toBe("number"); });
  it("xorChecksum 31", () => { expect(typeof xorChecksum([31])).toBe("number"); });
  it("xorChecksum 32", () => { expect(typeof xorChecksum([32])).toBe("number"); });
  it("xorChecksum 33", () => { expect(typeof xorChecksum([33])).toBe("number"); });
  it("xorChecksum 34", () => { expect(typeof xorChecksum([34])).toBe("number"); });
  it("xorChecksum 35", () => { expect(typeof xorChecksum([35])).toBe("number"); });
  it("xorChecksum 36", () => { expect(typeof xorChecksum([36])).toBe("number"); });
  it("xorChecksum 37", () => { expect(typeof xorChecksum([37])).toBe("number"); });
  it("xorChecksum 38", () => { expect(typeof xorChecksum([38])).toBe("number"); });
  it("xorChecksum 39", () => { expect(typeof xorChecksum([39])).toBe("number"); });
  it("xorChecksum 40", () => { expect(typeof xorChecksum([40])).toBe("number"); });
});

describe("adler32", () => {
  it("empty returns known value", () => { expect(typeof adler32([])).toBe("number"); });
  it("adler32 1", () => { expect(typeof adler32([1])).toBe("number"); });
  it("adler32 2", () => { expect(typeof adler32([2])).toBe("number"); });
  it("adler32 3", () => { expect(typeof adler32([3])).toBe("number"); });
  it("adler32 4", () => { expect(typeof adler32([4])).toBe("number"); });
  it("adler32 5", () => { expect(typeof adler32([5])).toBe("number"); });
  it("adler32 6", () => { expect(typeof adler32([6])).toBe("number"); });
  it("adler32 7", () => { expect(typeof adler32([7])).toBe("number"); });
  it("adler32 8", () => { expect(typeof adler32([8])).toBe("number"); });
  it("adler32 9", () => { expect(typeof adler32([9])).toBe("number"); });
  it("adler32 10", () => { expect(typeof adler32([10])).toBe("number"); });
  it("adler32 11", () => { expect(typeof adler32([11])).toBe("number"); });
  it("adler32 12", () => { expect(typeof adler32([12])).toBe("number"); });
  it("adler32 13", () => { expect(typeof adler32([13])).toBe("number"); });
  it("adler32 14", () => { expect(typeof adler32([14])).toBe("number"); });
  it("adler32 15", () => { expect(typeof adler32([15])).toBe("number"); });
  it("adler32 16", () => { expect(typeof adler32([16])).toBe("number"); });
  it("adler32 17", () => { expect(typeof adler32([17])).toBe("number"); });
  it("adler32 18", () => { expect(typeof adler32([18])).toBe("number"); });
  it("adler32 19", () => { expect(typeof adler32([19])).toBe("number"); });
  it("adler32 20", () => { expect(typeof adler32([20])).toBe("number"); });
  it("adler32 21", () => { expect(typeof adler32([21])).toBe("number"); });
  it("adler32 22", () => { expect(typeof adler32([22])).toBe("number"); });
  it("adler32 23", () => { expect(typeof adler32([23])).toBe("number"); });
  it("adler32 24", () => { expect(typeof adler32([24])).toBe("number"); });
  it("adler32 25", () => { expect(typeof adler32([25])).toBe("number"); });
  it("adler32 26", () => { expect(typeof adler32([26])).toBe("number"); });
  it("adler32 27", () => { expect(typeof adler32([27])).toBe("number"); });
  it("adler32 28", () => { expect(typeof adler32([28])).toBe("number"); });
  it("adler32 29", () => { expect(typeof adler32([29])).toBe("number"); });
  it("adler32 30", () => { expect(typeof adler32([30])).toBe("number"); });
  it("adler32 31", () => { expect(typeof adler32([31])).toBe("number"); });
  it("adler32 32", () => { expect(typeof adler32([32])).toBe("number"); });
  it("adler32 33", () => { expect(typeof adler32([33])).toBe("number"); });
  it("adler32 34", () => { expect(typeof adler32([34])).toBe("number"); });
  it("adler32 35", () => { expect(typeof adler32([35])).toBe("number"); });
  it("adler32 36", () => { expect(typeof adler32([36])).toBe("number"); });
  it("adler32 37", () => { expect(typeof adler32([37])).toBe("number"); });
  it("adler32 38", () => { expect(typeof adler32([38])).toBe("number"); });
  it("adler32 39", () => { expect(typeof adler32([39])).toBe("number"); });
  it("adler32 40", () => { expect(typeof adler32([40])).toBe("number"); });
});

describe("luhnCheck", () => {
  it("valid Luhn number passes", () => { expect(luhnCheck("4532015112830366")).toBe(true); });
  it("invalid Luhn number fails", () => { expect(luhnCheck("1234567890123456")).toBe(false); });
  it("short number is false", () => { expect(luhnCheck("1")).toBe(false); });
  it("luhnCheck type check 1", () => { expect(typeof luhnCheck("0000000000000001")).toBe("boolean"); });
  it("luhnCheck type check 2", () => { expect(typeof luhnCheck("0000000000000002")).toBe("boolean"); });
  it("luhnCheck type check 3", () => { expect(typeof luhnCheck("0000000000000003")).toBe("boolean"); });
  it("luhnCheck type check 4", () => { expect(typeof luhnCheck("0000000000000004")).toBe("boolean"); });
  it("luhnCheck type check 5", () => { expect(typeof luhnCheck("0000000000000005")).toBe("boolean"); });
  it("luhnCheck type check 6", () => { expect(typeof luhnCheck("0000000000000006")).toBe("boolean"); });
  it("luhnCheck type check 7", () => { expect(typeof luhnCheck("0000000000000007")).toBe("boolean"); });
  it("luhnCheck type check 8", () => { expect(typeof luhnCheck("0000000000000008")).toBe("boolean"); });
  it("luhnCheck type check 9", () => { expect(typeof luhnCheck("0000000000000009")).toBe("boolean"); });
  it("luhnCheck type check 10", () => { expect(typeof luhnCheck("0000000000000010")).toBe("boolean"); });
  it("luhnCheck type check 11", () => { expect(typeof luhnCheck("0000000000000011")).toBe("boolean"); });
  it("luhnCheck type check 12", () => { expect(typeof luhnCheck("0000000000000012")).toBe("boolean"); });
  it("luhnCheck type check 13", () => { expect(typeof luhnCheck("0000000000000013")).toBe("boolean"); });
  it("luhnCheck type check 14", () => { expect(typeof luhnCheck("0000000000000014")).toBe("boolean"); });
  it("luhnCheck type check 15", () => { expect(typeof luhnCheck("0000000000000015")).toBe("boolean"); });
  it("luhnCheck type check 16", () => { expect(typeof luhnCheck("0000000000000016")).toBe("boolean"); });
  it("luhnCheck type check 17", () => { expect(typeof luhnCheck("0000000000000017")).toBe("boolean"); });
  it("luhnCheck type check 18", () => { expect(typeof luhnCheck("0000000000000018")).toBe("boolean"); });
  it("luhnCheck type check 19", () => { expect(typeof luhnCheck("0000000000000019")).toBe("boolean"); });
  it("luhnCheck type check 20", () => { expect(typeof luhnCheck("0000000000000020")).toBe("boolean"); });
  it("luhnCheck type check 21", () => { expect(typeof luhnCheck("0000000000000021")).toBe("boolean"); });
  it("luhnCheck type check 22", () => { expect(typeof luhnCheck("0000000000000022")).toBe("boolean"); });
  it("luhnCheck type check 23", () => { expect(typeof luhnCheck("0000000000000023")).toBe("boolean"); });
  it("luhnCheck type check 24", () => { expect(typeof luhnCheck("0000000000000024")).toBe("boolean"); });
  it("luhnCheck type check 25", () => { expect(typeof luhnCheck("0000000000000025")).toBe("boolean"); });
  it("luhnCheck type check 26", () => { expect(typeof luhnCheck("0000000000000026")).toBe("boolean"); });
  it("luhnCheck type check 27", () => { expect(typeof luhnCheck("0000000000000027")).toBe("boolean"); });
  it("luhnCheck type check 28", () => { expect(typeof luhnCheck("0000000000000028")).toBe("boolean"); });
  it("luhnCheck type check 29", () => { expect(typeof luhnCheck("0000000000000029")).toBe("boolean"); });
  it("luhnCheck type check 30", () => { expect(typeof luhnCheck("0000000000000030")).toBe("boolean"); });
  it("luhnCheck type check 31", () => { expect(typeof luhnCheck("0000000000000031")).toBe("boolean"); });
  it("luhnCheck type check 32", () => { expect(typeof luhnCheck("0000000000000032")).toBe("boolean"); });
  it("luhnCheck type check 33", () => { expect(typeof luhnCheck("0000000000000033")).toBe("boolean"); });
  it("luhnCheck type check 34", () => { expect(typeof luhnCheck("0000000000000034")).toBe("boolean"); });
  it("luhnCheck type check 35", () => { expect(typeof luhnCheck("0000000000000035")).toBe("boolean"); });
  it("luhnCheck type check 36", () => { expect(typeof luhnCheck("0000000000000036")).toBe("boolean"); });
  it("luhnCheck type check 37", () => { expect(typeof luhnCheck("0000000000000037")).toBe("boolean"); });
  it("luhnCheck type check 38", () => { expect(typeof luhnCheck("0000000000000038")).toBe("boolean"); });
  it("luhnCheck type check 39", () => { expect(typeof luhnCheck("0000000000000039")).toBe("boolean"); });
  it("luhnCheck type check 40", () => { expect(typeof luhnCheck("0000000000000040")).toBe("boolean"); });
  it("luhnCheck type check 41", () => { expect(typeof luhnCheck("0000000000000041")).toBe("boolean"); });
  it("luhnCheck type check 42", () => { expect(typeof luhnCheck("0000000000000042")).toBe("boolean"); });
  it("luhnCheck type check 43", () => { expect(typeof luhnCheck("0000000000000043")).toBe("boolean"); });
  it("luhnCheck type check 44", () => { expect(typeof luhnCheck("0000000000000044")).toBe("boolean"); });
  it("luhnCheck type check 45", () => { expect(typeof luhnCheck("0000000000000045")).toBe("boolean"); });
  it("luhnCheck type check 46", () => { expect(typeof luhnCheck("0000000000000046")).toBe("boolean"); });
  it("luhnCheck type check 47", () => { expect(typeof luhnCheck("0000000000000047")).toBe("boolean"); });
  it("luhnCheck type check 48", () => { expect(typeof luhnCheck("0000000000000048")).toBe("boolean"); });
  it("luhnCheck type check 49", () => { expect(typeof luhnCheck("0000000000000049")).toBe("boolean"); });
  it("luhnCheck type check 50", () => { expect(typeof luhnCheck("0000000000000050")).toBe("boolean"); });
});

describe("majorityVote", () => {
  it("[1,1,0] majority is 1", () => { expect(majorityVote([1,1,0])).toBe(1); });
  it("[0,0,1] majority is 0", () => { expect(majorityVote([0,0,1])).toBe(0); });
  it("[1,1,1] majority is 1", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("[0,0,0] majority is 0", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 1", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 2", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 3", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 4", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 5", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 6", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 7", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 8", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 9", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 10", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 11", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 12", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 13", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 14", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 15", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 16", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 17", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 18", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 19", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 20", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 21", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 22", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 23", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 24", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 25", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 26", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 27", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 28", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 29", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 30", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 31", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 32", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 33", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 34", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 35", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 36", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 37", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 38", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 39", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 40", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 41", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 42", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 43", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 44", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 45", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 46", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 47", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 48", () => { expect(majorityVote([0,0,0])).toBe(0); });
  it("majorityVote all-1 49", () => { expect(majorityVote([1,1,1])).toBe(1); });
  it("majorityVote all-0 50", () => { expect(majorityVote([0,0,0])).toBe(0); });
});

describe("isValidIsbn13", () => {
  it("valid ISBN-13 passes", () => { expect(isValidIsbn13("9780306406157")).toBe(true); });
  it("invalid ISBN-13 fails", () => { expect(isValidIsbn13("9780306406158")).toBe(false); });
  it("wrong length fails", () => { expect(isValidIsbn13("978030640615")).toBe(false); });
  it("non-digit string fails", () => { expect(isValidIsbn13("978030640615X")).toBe(false); });
  it("isValidIsbn13 type check 1", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 2", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 3", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 4", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 5", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 6", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 7", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 8", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 9", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 10", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 11", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 12", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 13", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 14", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 15", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 16", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 17", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 18", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 19", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
  it("isValidIsbn13 type check 20", () => { expect(typeof isValidIsbn13("9780306406157")).toBe("boolean"); });
});

describe("crc8 edge cases", () => {
  it("all zeros returns 0", () => { expect(crc8([0,0,0])).toBe(0); });
  it("crc8 edge 1", () => { const r = crc8([3,7]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 2", () => { const r = crc8([6,14]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 3", () => { const r = crc8([9,21]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 4", () => { const r = crc8([12,28]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 5", () => { const r = crc8([15,35]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 6", () => { const r = crc8([18,42]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 7", () => { const r = crc8([21,49]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 8", () => { const r = crc8([24,56]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 9", () => { const r = crc8([27,63]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 10", () => { const r = crc8([30,70]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 11", () => { const r = crc8([33,77]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 12", () => { const r = crc8([36,84]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 13", () => { const r = crc8([39,91]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 14", () => { const r = crc8([42,98]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 15", () => { const r = crc8([45,105]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 16", () => { const r = crc8([48,112]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 17", () => { const r = crc8([51,119]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 18", () => { const r = crc8([54,126]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 19", () => { const r = crc8([57,133]); expect(r >= 0 && r <= 255).toBe(true); });
  it("crc8 edge 20", () => { const r = crc8([60,140]); expect(r >= 0 && r <= 255).toBe(true); });
});

describe("checksumMod256 edge cases", () => {
  it("checksumMod256 [13,17] is 30", () => { expect(checksumMod256([13,17])).toBe(30); });
  it("checksumMod256 [26,34] is 60", () => { expect(checksumMod256([26,34])).toBe(60); });
  it("checksumMod256 [39,51] is 90", () => { expect(checksumMod256([39,51])).toBe(90); });
  it("checksumMod256 [52,68] is 120", () => { expect(checksumMod256([52,68])).toBe(120); });
  it("checksumMod256 [65,85] is 150", () => { expect(checksumMod256([65,85])).toBe(150); });
  it("checksumMod256 [78,102] is 180", () => { expect(checksumMod256([78,102])).toBe(180); });
  it("checksumMod256 [91,119] is 210", () => { expect(checksumMod256([91,119])).toBe(210); });
  it("checksumMod256 [104,136] is 240", () => { expect(checksumMod256([104,136])).toBe(240); });
  it("checksumMod256 [117,153] is 14", () => { expect(checksumMod256([117,153])).toBe(14); });
  it("checksumMod256 [130,170] is 44", () => { expect(checksumMod256([130,170])).toBe(44); });
  it("checksumMod256 [143,187] is 74", () => { expect(checksumMod256([143,187])).toBe(74); });
  it("checksumMod256 [156,204] is 104", () => { expect(checksumMod256([156,204])).toBe(104); });
  it("checksumMod256 [169,221] is 134", () => { expect(checksumMod256([169,221])).toBe(134); });
  it("checksumMod256 [182,238] is 164", () => { expect(checksumMod256([182,238])).toBe(164); });
  it("checksumMod256 [195,255] is 194", () => { expect(checksumMod256([195,255])).toBe(194); });
  it("checksumMod256 [208,16] is 224", () => { expect(checksumMod256([208,16])).toBe(224); });
  it("checksumMod256 [221,33] is 254", () => { expect(checksumMod256([221,33])).toBe(254); });
  it("checksumMod256 [234,50] is 28", () => { expect(checksumMod256([234,50])).toBe(28); });
  it("checksumMod256 [247,67] is 58", () => { expect(checksumMod256([247,67])).toBe(58); });
  it("checksumMod256 [4,84] is 88", () => { expect(checksumMod256([4,84])).toBe(88); });
});
