// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// Proprietary and confidential. Unauthorised copying prohibited.
// See LICENCE file for details.

import { MerkleTree, verifyMerkleProof } from './merkle-tree';

function makeLeaves(n: number): string[] {
  return Array.from({ length: n }, (_, i) => String.fromCharCode(96)+"leaf-"+i+String.fromCharCode(96));
}

describe('S9 update preserves', () => {
  it("up 2",()=>{const lv=makeLeaves(2);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[1],1,t.getProof(1))).toBe(true);});
  it("up 3",()=>{const lv=makeLeaves(3);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[2],2,t.getProof(2))).toBe(true);});
  it("up 4",()=>{const lv=makeLeaves(4);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[3],3,t.getProof(3))).toBe(true);});
  it("up 5",()=>{const lv=makeLeaves(5);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[4],4,t.getProof(4))).toBe(true);});
  it("up 6",()=>{const lv=makeLeaves(6);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[5],5,t.getProof(5))).toBe(true);});
  it("up 7",()=>{const lv=makeLeaves(7);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[6],6,t.getProof(6))).toBe(true);});
  it("up 8",()=>{const lv=makeLeaves(8);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[7],7,t.getProof(7))).toBe(true);});
  it("up 9",()=>{const lv=makeLeaves(9);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[8],8,t.getProof(8))).toBe(true);});
  it("up 10",()=>{const lv=makeLeaves(10);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[9],9,t.getProof(9))).toBe(true);});
  it("up 11",()=>{const lv=makeLeaves(11);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[10],10,t.getProof(10))).toBe(true);});
  it("up 12",()=>{const lv=makeLeaves(12);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[11],11,t.getProof(11))).toBe(true);});
  it("up 13",()=>{const lv=makeLeaves(13);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[12],12,t.getProof(12))).toBe(true);});
  it("up 14",()=>{const lv=makeLeaves(14);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[13],13,t.getProof(13))).toBe(true);});
  it("up 15",()=>{const lv=makeLeaves(15);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[14],14,t.getProof(14))).toBe(true);});
  it("up 16",()=>{const lv=makeLeaves(16);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[15],15,t.getProof(15))).toBe(true);});
  it("up 17",()=>{const lv=makeLeaves(17);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[16],16,t.getProof(16))).toBe(true);});
  it("up 18",()=>{const lv=makeLeaves(18);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[17],17,t.getProof(17))).toBe(true);});
  it("up 19",()=>{const lv=makeLeaves(19);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[18],18,t.getProof(18))).toBe(true);});
  it("up 20",()=>{const lv=makeLeaves(20);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[19],19,t.getProof(19))).toBe(true);});
  it("up 21",()=>{const lv=makeLeaves(21);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[20],20,t.getProof(20))).toBe(true);});
  it("up 22",()=>{const lv=makeLeaves(22);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[21],21,t.getProof(21))).toBe(true);});
  it("up 23",()=>{const lv=makeLeaves(23);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[22],22,t.getProof(22))).toBe(true);});
  it("up 24",()=>{const lv=makeLeaves(24);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[23],23,t.getProof(23))).toBe(true);});
  it("up 25",()=>{const lv=makeLeaves(25);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[24],24,t.getProof(24))).toBe(true);});
  it("up 26",()=>{const lv=makeLeaves(26);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[25],25,t.getProof(25))).toBe(true);});
  it("up 27",()=>{const lv=makeLeaves(27);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[26],26,t.getProof(26))).toBe(true);});
  it("up 28",()=>{const lv=makeLeaves(28);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[27],27,t.getProof(27))).toBe(true);});
  it("up 29",()=>{const lv=makeLeaves(29);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[28],28,t.getProof(28))).toBe(true);});
  it("up 30",()=>{const lv=makeLeaves(30);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[29],29,t.getProof(29))).toBe(true);});
  it("up 31",()=>{const lv=makeLeaves(31);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[30],30,t.getProof(30))).toBe(true);});
  it("up 32",()=>{const lv=makeLeaves(32);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[31],31,t.getProof(31))).toBe(true);});
  it("up 33",()=>{const lv=makeLeaves(33);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[32],32,t.getProof(32))).toBe(true);});
  it("up 34",()=>{const lv=makeLeaves(34);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[33],33,t.getProof(33))).toBe(true);});
  it("up 35",()=>{const lv=makeLeaves(35);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[34],34,t.getProof(34))).toBe(true);});
  it("up 36",()=>{const lv=makeLeaves(36);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[35],35,t.getProof(35))).toBe(true);});
  it("up 37",()=>{const lv=makeLeaves(37);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[36],36,t.getProof(36))).toBe(true);});
  it("up 38",()=>{const lv=makeLeaves(38);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[37],37,t.getProof(37))).toBe(true);});
  it("up 39",()=>{const lv=makeLeaves(39);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[38],38,t.getProof(38))).toBe(true);});
  it("up 40",()=>{const lv=makeLeaves(40);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[39],39,t.getProof(39))).toBe(true);});
  it("up 41",()=>{const lv=makeLeaves(41);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[40],40,t.getProof(40))).toBe(true);});
  it("up 42",()=>{const lv=makeLeaves(42);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[41],41,t.getProof(41))).toBe(true);});
  it("up 43",()=>{const lv=makeLeaves(43);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[42],42,t.getProof(42))).toBe(true);});
  it("up 44",()=>{const lv=makeLeaves(44);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[43],43,t.getProof(43))).toBe(true);});
  it("up 45",()=>{const lv=makeLeaves(45);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[44],44,t.getProof(44))).toBe(true);});
  it("up 46",()=>{const lv=makeLeaves(46);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[45],45,t.getProof(45))).toBe(true);});
  it("up 47",()=>{const lv=makeLeaves(47);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[46],46,t.getProof(46))).toBe(true);});
  it("up 48",()=>{const lv=makeLeaves(48);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[47],47,t.getProof(47))).toBe(true);});
  it("up 49",()=>{const lv=makeLeaves(49);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[48],48,t.getProof(48))).toBe(true);});
  it("up 50",()=>{const lv=makeLeaves(50);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[49],49,t.getProof(49))).toBe(true);});
  it("up 51",()=>{const lv=makeLeaves(51);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[50],50,t.getProof(50))).toBe(true);});
  it("up 52",()=>{const lv=makeLeaves(52);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[51],51,t.getProof(51))).toBe(true);});
  it("up 53",()=>{const lv=makeLeaves(53);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[52],52,t.getProof(52))).toBe(true);});
  it("up 54",()=>{const lv=makeLeaves(54);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[53],53,t.getProof(53))).toBe(true);});
  it("up 55",()=>{const lv=makeLeaves(55);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[54],54,t.getProof(54))).toBe(true);});
  it("up 56",()=>{const lv=makeLeaves(56);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[55],55,t.getProof(55))).toBe(true);});
  it("up 57",()=>{const lv=makeLeaves(57);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[56],56,t.getProof(56))).toBe(true);});
  it("up 58",()=>{const lv=makeLeaves(58);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[57],57,t.getProof(57))).toBe(true);});
  it("up 59",()=>{const lv=makeLeaves(59);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[58],58,t.getProof(58))).toBe(true);});
  it("up 60",()=>{const lv=makeLeaves(60);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[59],59,t.getProof(59))).toBe(true);});
  it("up 61",()=>{const lv=makeLeaves(61);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[60],60,t.getProof(60))).toBe(true);});
  it("up 62",()=>{const lv=makeLeaves(62);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[61],61,t.getProof(61))).toBe(true);});
  it("up 63",()=>{const lv=makeLeaves(63);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[62],62,t.getProof(62))).toBe(true);});
  it("up 64",()=>{const lv=makeLeaves(64);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[63],63,t.getProof(63))).toBe(true);});
  it("up 65",()=>{const lv=makeLeaves(65);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[64],64,t.getProof(64))).toBe(true);});
  it("up 66",()=>{const lv=makeLeaves(66);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[65],65,t.getProof(65))).toBe(true);});
  it("up 67",()=>{const lv=makeLeaves(67);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[66],66,t.getProof(66))).toBe(true);});
  it("up 68",()=>{const lv=makeLeaves(68);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[67],67,t.getProof(67))).toBe(true);});
  it("up 69",()=>{const lv=makeLeaves(69);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[68],68,t.getProof(68))).toBe(true);});
  it("up 70",()=>{const lv=makeLeaves(70);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[69],69,t.getProof(69))).toBe(true);});
  it("up 71",()=>{const lv=makeLeaves(71);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[70],70,t.getProof(70))).toBe(true);});
  it("up 72",()=>{const lv=makeLeaves(72);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[71],71,t.getProof(71))).toBe(true);});
  it("up 73",()=>{const lv=makeLeaves(73);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[72],72,t.getProof(72))).toBe(true);});
  it("up 74",()=>{const lv=makeLeaves(74);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[73],73,t.getProof(73))).toBe(true);});
  it("up 75",()=>{const lv=makeLeaves(75);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[74],74,t.getProof(74))).toBe(true);});
  it("up 76",()=>{const lv=makeLeaves(76);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[75],75,t.getProof(75))).toBe(true);});
  it("up 77",()=>{const lv=makeLeaves(77);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[76],76,t.getProof(76))).toBe(true);});
  it("up 78",()=>{const lv=makeLeaves(78);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[77],77,t.getProof(77))).toBe(true);});
  it("up 79",()=>{const lv=makeLeaves(79);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[78],78,t.getProof(78))).toBe(true);});
  it("up 80",()=>{const lv=makeLeaves(80);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[79],79,t.getProof(79))).toBe(true);});
  it("up 81",()=>{const lv=makeLeaves(81);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[80],80,t.getProof(80))).toBe(true);});
  it("up 82",()=>{const lv=makeLeaves(82);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[81],81,t.getProof(81))).toBe(true);});
  it("up 83",()=>{const lv=makeLeaves(83);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[82],82,t.getProof(82))).toBe(true);});
  it("up 84",()=>{const lv=makeLeaves(84);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[83],83,t.getProof(83))).toBe(true);});
  it("up 85",()=>{const lv=makeLeaves(85);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[84],84,t.getProof(84))).toBe(true);});
  it("up 86",()=>{const lv=makeLeaves(86);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[85],85,t.getProof(85))).toBe(true);});
  it("up 87",()=>{const lv=makeLeaves(87);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[86],86,t.getProof(86))).toBe(true);});
  it("up 88",()=>{const lv=makeLeaves(88);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[87],87,t.getProof(87))).toBe(true);});
  it("up 89",()=>{const lv=makeLeaves(89);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[88],88,t.getProof(88))).toBe(true);});
  it("up 90",()=>{const lv=makeLeaves(90);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[89],89,t.getProof(89))).toBe(true);});
  it("up 91",()=>{const lv=makeLeaves(91);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[90],90,t.getProof(90))).toBe(true);});
  it("up 92",()=>{const lv=makeLeaves(92);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[91],91,t.getProof(91))).toBe(true);});
  it("up 93",()=>{const lv=makeLeaves(93);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[92],92,t.getProof(92))).toBe(true);});
  it("up 94",()=>{const lv=makeLeaves(94);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[93],93,t.getProof(93))).toBe(true);});
  it("up 95",()=>{const lv=makeLeaves(95);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[94],94,t.getProof(94))).toBe(true);});
  it("up 96",()=>{const lv=makeLeaves(96);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[95],95,t.getProof(95))).toBe(true);});
  it("up 97",()=>{const lv=makeLeaves(97);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[96],96,t.getProof(96))).toBe(true);});
  it("up 98",()=>{const lv=makeLeaves(98);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[97],97,t.getProof(97))).toBe(true);});
  it("up 99",()=>{const lv=makeLeaves(99);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[98],98,t.getProof(98))).toBe(true);});
  it("up 100",()=>{const lv=makeLeaves(100);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[99],99,t.getProof(99))).toBe(true);});
  it("up 101",()=>{const lv=makeLeaves(101);const t=new MerkleTree(lv);t.update(0,"nv");expect(t.verify(t.leaves[100],100,t.getProof(100))).toBe(true);});
});
describe('S10 tampered proof', () => {
  it("tp 2",()=>{const lv=makeLeaves(2);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 3",()=>{const lv=makeLeaves(3);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 4",()=>{const lv=makeLeaves(4);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 5",()=>{const lv=makeLeaves(5);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 6",()=>{const lv=makeLeaves(6);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 7",()=>{const lv=makeLeaves(7);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 8",()=>{const lv=makeLeaves(8);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 9",()=>{const lv=makeLeaves(9);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 10",()=>{const lv=makeLeaves(10);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 11",()=>{const lv=makeLeaves(11);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 12",()=>{const lv=makeLeaves(12);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 13",()=>{const lv=makeLeaves(13);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 14",()=>{const lv=makeLeaves(14);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 15",()=>{const lv=makeLeaves(15);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 16",()=>{const lv=makeLeaves(16);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 17",()=>{const lv=makeLeaves(17);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 18",()=>{const lv=makeLeaves(18);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 19",()=>{const lv=makeLeaves(19);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 20",()=>{const lv=makeLeaves(20);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 21",()=>{const lv=makeLeaves(21);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 22",()=>{const lv=makeLeaves(22);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 23",()=>{const lv=makeLeaves(23);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 24",()=>{const lv=makeLeaves(24);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 25",()=>{const lv=makeLeaves(25);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 26",()=>{const lv=makeLeaves(26);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 27",()=>{const lv=makeLeaves(27);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 28",()=>{const lv=makeLeaves(28);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 29",()=>{const lv=makeLeaves(29);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 30",()=>{const lv=makeLeaves(30);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 31",()=>{const lv=makeLeaves(31);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 32",()=>{const lv=makeLeaves(32);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 33",()=>{const lv=makeLeaves(33);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 34",()=>{const lv=makeLeaves(34);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 35",()=>{const lv=makeLeaves(35);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 36",()=>{const lv=makeLeaves(36);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 37",()=>{const lv=makeLeaves(37);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 38",()=>{const lv=makeLeaves(38);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 39",()=>{const lv=makeLeaves(39);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 40",()=>{const lv=makeLeaves(40);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 41",()=>{const lv=makeLeaves(41);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 42",()=>{const lv=makeLeaves(42);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 43",()=>{const lv=makeLeaves(43);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 44",()=>{const lv=makeLeaves(44);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 45",()=>{const lv=makeLeaves(45);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 46",()=>{const lv=makeLeaves(46);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 47",()=>{const lv=makeLeaves(47);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 48",()=>{const lv=makeLeaves(48);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 49",()=>{const lv=makeLeaves(49);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 50",()=>{const lv=makeLeaves(50);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
  it("tp 51",()=>{const lv=makeLeaves(51);const t=new MerkleTree(lv);const p=t.getProof(0);if(!p.length){expect(true).toBe(true);return;}const tp=p.map((s,i)=>i===0?{...s,hash:"dead"}:s);expect(t.verify(lv[0],0,tp)).toBe(false);});
});
