// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// Proprietary and confidential. Unauthorised copying prohibited.
// See LICENCE file for details.
import { MerkleTree, verifyMerkleProof } from './merkle-tree';
function makeLeaves(n: number): string[] {
  return Array.from({ length: n }, (_, i) => String.fromCharCode(96)+"leaf-"+i+String.fromCharCode(96));
}
describe('S1 construction', () => {
  it("ctor 1",()=>{const t=new MerkleTree(makeLeaves(1));expect(t.leafCount).toBe(1);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 2",()=>{const t=new MerkleTree(makeLeaves(2));expect(t.leafCount).toBe(2);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 3",()=>{const t=new MerkleTree(makeLeaves(3));expect(t.leafCount).toBe(3);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 4",()=>{const t=new MerkleTree(makeLeaves(4));expect(t.leafCount).toBe(4);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 5",()=>{const t=new MerkleTree(makeLeaves(5));expect(t.leafCount).toBe(5);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 6",()=>{const t=new MerkleTree(makeLeaves(6));expect(t.leafCount).toBe(6);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 7",()=>{const t=new MerkleTree(makeLeaves(7));expect(t.leafCount).toBe(7);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 8",()=>{const t=new MerkleTree(makeLeaves(8));expect(t.leafCount).toBe(8);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 9",()=>{const t=new MerkleTree(makeLeaves(9));expect(t.leafCount).toBe(9);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 10",()=>{const t=new MerkleTree(makeLeaves(10));expect(t.leafCount).toBe(10);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 11",()=>{const t=new MerkleTree(makeLeaves(11));expect(t.leafCount).toBe(11);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 12",()=>{const t=new MerkleTree(makeLeaves(12));expect(t.leafCount).toBe(12);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 13",()=>{const t=new MerkleTree(makeLeaves(13));expect(t.leafCount).toBe(13);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 14",()=>{const t=new MerkleTree(makeLeaves(14));expect(t.leafCount).toBe(14);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 15",()=>{const t=new MerkleTree(makeLeaves(15));expect(t.leafCount).toBe(15);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 16",()=>{const t=new MerkleTree(makeLeaves(16));expect(t.leafCount).toBe(16);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 17",()=>{const t=new MerkleTree(makeLeaves(17));expect(t.leafCount).toBe(17);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 18",()=>{const t=new MerkleTree(makeLeaves(18));expect(t.leafCount).toBe(18);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 19",()=>{const t=new MerkleTree(makeLeaves(19));expect(t.leafCount).toBe(19);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 20",()=>{const t=new MerkleTree(makeLeaves(20));expect(t.leafCount).toBe(20);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 21",()=>{const t=new MerkleTree(makeLeaves(21));expect(t.leafCount).toBe(21);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 22",()=>{const t=new MerkleTree(makeLeaves(22));expect(t.leafCount).toBe(22);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 23",()=>{const t=new MerkleTree(makeLeaves(23));expect(t.leafCount).toBe(23);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 24",()=>{const t=new MerkleTree(makeLeaves(24));expect(t.leafCount).toBe(24);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 25",()=>{const t=new MerkleTree(makeLeaves(25));expect(t.leafCount).toBe(25);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 26",()=>{const t=new MerkleTree(makeLeaves(26));expect(t.leafCount).toBe(26);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 27",()=>{const t=new MerkleTree(makeLeaves(27));expect(t.leafCount).toBe(27);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 28",()=>{const t=new MerkleTree(makeLeaves(28));expect(t.leafCount).toBe(28);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 29",()=>{const t=new MerkleTree(makeLeaves(29));expect(t.leafCount).toBe(29);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 30",()=>{const t=new MerkleTree(makeLeaves(30));expect(t.leafCount).toBe(30);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 31",()=>{const t=new MerkleTree(makeLeaves(31));expect(t.leafCount).toBe(31);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 32",()=>{const t=new MerkleTree(makeLeaves(32));expect(t.leafCount).toBe(32);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 33",()=>{const t=new MerkleTree(makeLeaves(33));expect(t.leafCount).toBe(33);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 34",()=>{const t=new MerkleTree(makeLeaves(34));expect(t.leafCount).toBe(34);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 35",()=>{const t=new MerkleTree(makeLeaves(35));expect(t.leafCount).toBe(35);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 36",()=>{const t=new MerkleTree(makeLeaves(36));expect(t.leafCount).toBe(36);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 37",()=>{const t=new MerkleTree(makeLeaves(37));expect(t.leafCount).toBe(37);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 38",()=>{const t=new MerkleTree(makeLeaves(38));expect(t.leafCount).toBe(38);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 39",()=>{const t=new MerkleTree(makeLeaves(39));expect(t.leafCount).toBe(39);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 40",()=>{const t=new MerkleTree(makeLeaves(40));expect(t.leafCount).toBe(40);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 41",()=>{const t=new MerkleTree(makeLeaves(41));expect(t.leafCount).toBe(41);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 42",()=>{const t=new MerkleTree(makeLeaves(42));expect(t.leafCount).toBe(42);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 43",()=>{const t=new MerkleTree(makeLeaves(43));expect(t.leafCount).toBe(43);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 44",()=>{const t=new MerkleTree(makeLeaves(44));expect(t.leafCount).toBe(44);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 45",()=>{const t=new MerkleTree(makeLeaves(45));expect(t.leafCount).toBe(45);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 46",()=>{const t=new MerkleTree(makeLeaves(46));expect(t.leafCount).toBe(46);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 47",()=>{const t=new MerkleTree(makeLeaves(47));expect(t.leafCount).toBe(47);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 48",()=>{const t=new MerkleTree(makeLeaves(48));expect(t.leafCount).toBe(48);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 49",()=>{const t=new MerkleTree(makeLeaves(49));expect(t.leafCount).toBe(49);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 50",()=>{const t=new MerkleTree(makeLeaves(50));expect(t.leafCount).toBe(50);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 51",()=>{const t=new MerkleTree(makeLeaves(51));expect(t.leafCount).toBe(51);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 52",()=>{const t=new MerkleTree(makeLeaves(52));expect(t.leafCount).toBe(52);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 53",()=>{const t=new MerkleTree(makeLeaves(53));expect(t.leafCount).toBe(53);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 54",()=>{const t=new MerkleTree(makeLeaves(54));expect(t.leafCount).toBe(54);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 55",()=>{const t=new MerkleTree(makeLeaves(55));expect(t.leafCount).toBe(55);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 56",()=>{const t=new MerkleTree(makeLeaves(56));expect(t.leafCount).toBe(56);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 57",()=>{const t=new MerkleTree(makeLeaves(57));expect(t.leafCount).toBe(57);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 58",()=>{const t=new MerkleTree(makeLeaves(58));expect(t.leafCount).toBe(58);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 59",()=>{const t=new MerkleTree(makeLeaves(59));expect(t.leafCount).toBe(59);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 60",()=>{const t=new MerkleTree(makeLeaves(60));expect(t.leafCount).toBe(60);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 61",()=>{const t=new MerkleTree(makeLeaves(61));expect(t.leafCount).toBe(61);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 62",()=>{const t=new MerkleTree(makeLeaves(62));expect(t.leafCount).toBe(62);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 63",()=>{const t=new MerkleTree(makeLeaves(63));expect(t.leafCount).toBe(63);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 64",()=>{const t=new MerkleTree(makeLeaves(64));expect(t.leafCount).toBe(64);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 65",()=>{const t=new MerkleTree(makeLeaves(65));expect(t.leafCount).toBe(65);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 66",()=>{const t=new MerkleTree(makeLeaves(66));expect(t.leafCount).toBe(66);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 67",()=>{const t=new MerkleTree(makeLeaves(67));expect(t.leafCount).toBe(67);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 68",()=>{const t=new MerkleTree(makeLeaves(68));expect(t.leafCount).toBe(68);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 69",()=>{const t=new MerkleTree(makeLeaves(69));expect(t.leafCount).toBe(69);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 70",()=>{const t=new MerkleTree(makeLeaves(70));expect(t.leafCount).toBe(70);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 71",()=>{const t=new MerkleTree(makeLeaves(71));expect(t.leafCount).toBe(71);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 72",()=>{const t=new MerkleTree(makeLeaves(72));expect(t.leafCount).toBe(72);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 73",()=>{const t=new MerkleTree(makeLeaves(73));expect(t.leafCount).toBe(73);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 74",()=>{const t=new MerkleTree(makeLeaves(74));expect(t.leafCount).toBe(74);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 75",()=>{const t=new MerkleTree(makeLeaves(75));expect(t.leafCount).toBe(75);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 76",()=>{const t=new MerkleTree(makeLeaves(76));expect(t.leafCount).toBe(76);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 77",()=>{const t=new MerkleTree(makeLeaves(77));expect(t.leafCount).toBe(77);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 78",()=>{const t=new MerkleTree(makeLeaves(78));expect(t.leafCount).toBe(78);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 79",()=>{const t=new MerkleTree(makeLeaves(79));expect(t.leafCount).toBe(79);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 80",()=>{const t=new MerkleTree(makeLeaves(80));expect(t.leafCount).toBe(80);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 81",()=>{const t=new MerkleTree(makeLeaves(81));expect(t.leafCount).toBe(81);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 82",()=>{const t=new MerkleTree(makeLeaves(82));expect(t.leafCount).toBe(82);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 83",()=>{const t=new MerkleTree(makeLeaves(83));expect(t.leafCount).toBe(83);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 84",()=>{const t=new MerkleTree(makeLeaves(84));expect(t.leafCount).toBe(84);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 85",()=>{const t=new MerkleTree(makeLeaves(85));expect(t.leafCount).toBe(85);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 86",()=>{const t=new MerkleTree(makeLeaves(86));expect(t.leafCount).toBe(86);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 87",()=>{const t=new MerkleTree(makeLeaves(87));expect(t.leafCount).toBe(87);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 88",()=>{const t=new MerkleTree(makeLeaves(88));expect(t.leafCount).toBe(88);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 89",()=>{const t=new MerkleTree(makeLeaves(89));expect(t.leafCount).toBe(89);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 90",()=>{const t=new MerkleTree(makeLeaves(90));expect(t.leafCount).toBe(90);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 91",()=>{const t=new MerkleTree(makeLeaves(91));expect(t.leafCount).toBe(91);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 92",()=>{const t=new MerkleTree(makeLeaves(92));expect(t.leafCount).toBe(92);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 93",()=>{const t=new MerkleTree(makeLeaves(93));expect(t.leafCount).toBe(93);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 94",()=>{const t=new MerkleTree(makeLeaves(94));expect(t.leafCount).toBe(94);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 95",()=>{const t=new MerkleTree(makeLeaves(95));expect(t.leafCount).toBe(95);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 96",()=>{const t=new MerkleTree(makeLeaves(96));expect(t.leafCount).toBe(96);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 97",()=>{const t=new MerkleTree(makeLeaves(97));expect(t.leafCount).toBe(97);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 98",()=>{const t=new MerkleTree(makeLeaves(98));expect(t.leafCount).toBe(98);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 99",()=>{const t=new MerkleTree(makeLeaves(99));expect(t.leafCount).toBe(99);expect(t.root.length).toBeGreaterThan(0);});
  it("ctor 100",()=>{const t=new MerkleTree(makeLeaves(100));expect(t.leafCount).toBe(100);expect(t.root.length).toBeGreaterThan(0);});
});
describe('S2 root changes', () => {
  it("rc 1",()=>{const t=new MerkleTree(makeLeaves(1));const b=t.root;t.update(0,"C");expect(t.root).not.toBe(b);});
  it("rc 2",()=>{const t=new MerkleTree(makeLeaves(2));const b=t.root;t.update(1,"C");expect(t.root).not.toBe(b);});
  it("rc 3",()=>{const t=new MerkleTree(makeLeaves(3));const b=t.root;t.update(2,"C");expect(t.root).not.toBe(b);});
  it("rc 4",()=>{const t=new MerkleTree(makeLeaves(4));const b=t.root;t.update(3,"C");expect(t.root).not.toBe(b);});
  it("rc 5",()=>{const t=new MerkleTree(makeLeaves(5));const b=t.root;t.update(4,"C");expect(t.root).not.toBe(b);});
  it("rc 6",()=>{const t=new MerkleTree(makeLeaves(6));const b=t.root;t.update(5,"C");expect(t.root).not.toBe(b);});
  it("rc 7",()=>{const t=new MerkleTree(makeLeaves(7));const b=t.root;t.update(6,"C");expect(t.root).not.toBe(b);});
  it("rc 8",()=>{const t=new MerkleTree(makeLeaves(8));const b=t.root;t.update(7,"C");expect(t.root).not.toBe(b);});
  it("rc 9",()=>{const t=new MerkleTree(makeLeaves(9));const b=t.root;t.update(8,"C");expect(t.root).not.toBe(b);});
  it("rc 10",()=>{const t=new MerkleTree(makeLeaves(10));const b=t.root;t.update(9,"C");expect(t.root).not.toBe(b);});
  it("rc 11",()=>{const t=new MerkleTree(makeLeaves(11));const b=t.root;t.update(10,"C");expect(t.root).not.toBe(b);});
  it("rc 12",()=>{const t=new MerkleTree(makeLeaves(12));const b=t.root;t.update(11,"C");expect(t.root).not.toBe(b);});
  it("rc 13",()=>{const t=new MerkleTree(makeLeaves(13));const b=t.root;t.update(12,"C");expect(t.root).not.toBe(b);});
  it("rc 14",()=>{const t=new MerkleTree(makeLeaves(14));const b=t.root;t.update(13,"C");expect(t.root).not.toBe(b);});
  it("rc 15",()=>{const t=new MerkleTree(makeLeaves(15));const b=t.root;t.update(14,"C");expect(t.root).not.toBe(b);});
  it("rc 16",()=>{const t=new MerkleTree(makeLeaves(16));const b=t.root;t.update(15,"C");expect(t.root).not.toBe(b);});
  it("rc 17",()=>{const t=new MerkleTree(makeLeaves(17));const b=t.root;t.update(16,"C");expect(t.root).not.toBe(b);});
  it("rc 18",()=>{const t=new MerkleTree(makeLeaves(18));const b=t.root;t.update(17,"C");expect(t.root).not.toBe(b);});
  it("rc 19",()=>{const t=new MerkleTree(makeLeaves(19));const b=t.root;t.update(18,"C");expect(t.root).not.toBe(b);});
  it("rc 20",()=>{const t=new MerkleTree(makeLeaves(20));const b=t.root;t.update(19,"C");expect(t.root).not.toBe(b);});
  it("rc 21",()=>{const t=new MerkleTree(makeLeaves(21));const b=t.root;t.update(20,"C");expect(t.root).not.toBe(b);});
  it("rc 22",()=>{const t=new MerkleTree(makeLeaves(22));const b=t.root;t.update(21,"C");expect(t.root).not.toBe(b);});
  it("rc 23",()=>{const t=new MerkleTree(makeLeaves(23));const b=t.root;t.update(22,"C");expect(t.root).not.toBe(b);});
  it("rc 24",()=>{const t=new MerkleTree(makeLeaves(24));const b=t.root;t.update(23,"C");expect(t.root).not.toBe(b);});
  it("rc 25",()=>{const t=new MerkleTree(makeLeaves(25));const b=t.root;t.update(24,"C");expect(t.root).not.toBe(b);});
  it("rc 26",()=>{const t=new MerkleTree(makeLeaves(26));const b=t.root;t.update(25,"C");expect(t.root).not.toBe(b);});
  it("rc 27",()=>{const t=new MerkleTree(makeLeaves(27));const b=t.root;t.update(26,"C");expect(t.root).not.toBe(b);});
  it("rc 28",()=>{const t=new MerkleTree(makeLeaves(28));const b=t.root;t.update(27,"C");expect(t.root).not.toBe(b);});
  it("rc 29",()=>{const t=new MerkleTree(makeLeaves(29));const b=t.root;t.update(28,"C");expect(t.root).not.toBe(b);});
  it("rc 30",()=>{const t=new MerkleTree(makeLeaves(30));const b=t.root;t.update(29,"C");expect(t.root).not.toBe(b);});
  it("rc 31",()=>{const t=new MerkleTree(makeLeaves(31));const b=t.root;t.update(30,"C");expect(t.root).not.toBe(b);});
  it("rc 32",()=>{const t=new MerkleTree(makeLeaves(32));const b=t.root;t.update(31,"C");expect(t.root).not.toBe(b);});
  it("rc 33",()=>{const t=new MerkleTree(makeLeaves(33));const b=t.root;t.update(32,"C");expect(t.root).not.toBe(b);});
  it("rc 34",()=>{const t=new MerkleTree(makeLeaves(34));const b=t.root;t.update(33,"C");expect(t.root).not.toBe(b);});
  it("rc 35",()=>{const t=new MerkleTree(makeLeaves(35));const b=t.root;t.update(34,"C");expect(t.root).not.toBe(b);});
  it("rc 36",()=>{const t=new MerkleTree(makeLeaves(36));const b=t.root;t.update(35,"C");expect(t.root).not.toBe(b);});
  it("rc 37",()=>{const t=new MerkleTree(makeLeaves(37));const b=t.root;t.update(36,"C");expect(t.root).not.toBe(b);});
  it("rc 38",()=>{const t=new MerkleTree(makeLeaves(38));const b=t.root;t.update(37,"C");expect(t.root).not.toBe(b);});
  it("rc 39",()=>{const t=new MerkleTree(makeLeaves(39));const b=t.root;t.update(38,"C");expect(t.root).not.toBe(b);});
  it("rc 40",()=>{const t=new MerkleTree(makeLeaves(40));const b=t.root;t.update(39,"C");expect(t.root).not.toBe(b);});
  it("rc 41",()=>{const t=new MerkleTree(makeLeaves(41));const b=t.root;t.update(40,"C");expect(t.root).not.toBe(b);});
  it("rc 42",()=>{const t=new MerkleTree(makeLeaves(42));const b=t.root;t.update(41,"C");expect(t.root).not.toBe(b);});
  it("rc 43",()=>{const t=new MerkleTree(makeLeaves(43));const b=t.root;t.update(42,"C");expect(t.root).not.toBe(b);});
  it("rc 44",()=>{const t=new MerkleTree(makeLeaves(44));const b=t.root;t.update(43,"C");expect(t.root).not.toBe(b);});
  it("rc 45",()=>{const t=new MerkleTree(makeLeaves(45));const b=t.root;t.update(44,"C");expect(t.root).not.toBe(b);});
  it("rc 46",()=>{const t=new MerkleTree(makeLeaves(46));const b=t.root;t.update(45,"C");expect(t.root).not.toBe(b);});
  it("rc 47",()=>{const t=new MerkleTree(makeLeaves(47));const b=t.root;t.update(46,"C");expect(t.root).not.toBe(b);});
  it("rc 48",()=>{const t=new MerkleTree(makeLeaves(48));const b=t.root;t.update(47,"C");expect(t.root).not.toBe(b);});
  it("rc 49",()=>{const t=new MerkleTree(makeLeaves(49));const b=t.root;t.update(48,"C");expect(t.root).not.toBe(b);});
  it("rc 50",()=>{const t=new MerkleTree(makeLeaves(50));const b=t.root;t.update(49,"C");expect(t.root).not.toBe(b);});
  it("rc 51",()=>{const t=new MerkleTree(makeLeaves(51));const b=t.root;t.update(50,"C");expect(t.root).not.toBe(b);});
  it("rc 52",()=>{const t=new MerkleTree(makeLeaves(52));const b=t.root;t.update(51,"C");expect(t.root).not.toBe(b);});
  it("rc 53",()=>{const t=new MerkleTree(makeLeaves(53));const b=t.root;t.update(52,"C");expect(t.root).not.toBe(b);});
  it("rc 54",()=>{const t=new MerkleTree(makeLeaves(54));const b=t.root;t.update(53,"C");expect(t.root).not.toBe(b);});
  it("rc 55",()=>{const t=new MerkleTree(makeLeaves(55));const b=t.root;t.update(54,"C");expect(t.root).not.toBe(b);});
  it("rc 56",()=>{const t=new MerkleTree(makeLeaves(56));const b=t.root;t.update(55,"C");expect(t.root).not.toBe(b);});
  it("rc 57",()=>{const t=new MerkleTree(makeLeaves(57));const b=t.root;t.update(56,"C");expect(t.root).not.toBe(b);});
  it("rc 58",()=>{const t=new MerkleTree(makeLeaves(58));const b=t.root;t.update(57,"C");expect(t.root).not.toBe(b);});
  it("rc 59",()=>{const t=new MerkleTree(makeLeaves(59));const b=t.root;t.update(58,"C");expect(t.root).not.toBe(b);});
  it("rc 60",()=>{const t=new MerkleTree(makeLeaves(60));const b=t.root;t.update(59,"C");expect(t.root).not.toBe(b);});
  it("rc 61",()=>{const t=new MerkleTree(makeLeaves(61));const b=t.root;t.update(60,"C");expect(t.root).not.toBe(b);});
  it("rc 62",()=>{const t=new MerkleTree(makeLeaves(62));const b=t.root;t.update(61,"C");expect(t.root).not.toBe(b);});
  it("rc 63",()=>{const t=new MerkleTree(makeLeaves(63));const b=t.root;t.update(62,"C");expect(t.root).not.toBe(b);});
  it("rc 64",()=>{const t=new MerkleTree(makeLeaves(64));const b=t.root;t.update(63,"C");expect(t.root).not.toBe(b);});
  it("rc 65",()=>{const t=new MerkleTree(makeLeaves(65));const b=t.root;t.update(64,"C");expect(t.root).not.toBe(b);});
  it("rc 66",()=>{const t=new MerkleTree(makeLeaves(66));const b=t.root;t.update(65,"C");expect(t.root).not.toBe(b);});
  it("rc 67",()=>{const t=new MerkleTree(makeLeaves(67));const b=t.root;t.update(66,"C");expect(t.root).not.toBe(b);});
  it("rc 68",()=>{const t=new MerkleTree(makeLeaves(68));const b=t.root;t.update(67,"C");expect(t.root).not.toBe(b);});
  it("rc 69",()=>{const t=new MerkleTree(makeLeaves(69));const b=t.root;t.update(68,"C");expect(t.root).not.toBe(b);});
  it("rc 70",()=>{const t=new MerkleTree(makeLeaves(70));const b=t.root;t.update(69,"C");expect(t.root).not.toBe(b);});
  it("rc 71",()=>{const t=new MerkleTree(makeLeaves(71));const b=t.root;t.update(70,"C");expect(t.root).not.toBe(b);});
  it("rc 72",()=>{const t=new MerkleTree(makeLeaves(72));const b=t.root;t.update(71,"C");expect(t.root).not.toBe(b);});
  it("rc 73",()=>{const t=new MerkleTree(makeLeaves(73));const b=t.root;t.update(72,"C");expect(t.root).not.toBe(b);});
  it("rc 74",()=>{const t=new MerkleTree(makeLeaves(74));const b=t.root;t.update(73,"C");expect(t.root).not.toBe(b);});
  it("rc 75",()=>{const t=new MerkleTree(makeLeaves(75));const b=t.root;t.update(74,"C");expect(t.root).not.toBe(b);});
  it("rc 76",()=>{const t=new MerkleTree(makeLeaves(76));const b=t.root;t.update(75,"C");expect(t.root).not.toBe(b);});
  it("rc 77",()=>{const t=new MerkleTree(makeLeaves(77));const b=t.root;t.update(76,"C");expect(t.root).not.toBe(b);});
  it("rc 78",()=>{const t=new MerkleTree(makeLeaves(78));const b=t.root;t.update(77,"C");expect(t.root).not.toBe(b);});
  it("rc 79",()=>{const t=new MerkleTree(makeLeaves(79));const b=t.root;t.update(78,"C");expect(t.root).not.toBe(b);});
  it("rc 80",()=>{const t=new MerkleTree(makeLeaves(80));const b=t.root;t.update(79,"C");expect(t.root).not.toBe(b);});
  it("rc 81",()=>{const t=new MerkleTree(makeLeaves(81));const b=t.root;t.update(80,"C");expect(t.root).not.toBe(b);});
  it("rc 82",()=>{const t=new MerkleTree(makeLeaves(82));const b=t.root;t.update(81,"C");expect(t.root).not.toBe(b);});
  it("rc 83",()=>{const t=new MerkleTree(makeLeaves(83));const b=t.root;t.update(82,"C");expect(t.root).not.toBe(b);});
  it("rc 84",()=>{const t=new MerkleTree(makeLeaves(84));const b=t.root;t.update(83,"C");expect(t.root).not.toBe(b);});
  it("rc 85",()=>{const t=new MerkleTree(makeLeaves(85));const b=t.root;t.update(84,"C");expect(t.root).not.toBe(b);});
  it("rc 86",()=>{const t=new MerkleTree(makeLeaves(86));const b=t.root;t.update(85,"C");expect(t.root).not.toBe(b);});
  it("rc 87",()=>{const t=new MerkleTree(makeLeaves(87));const b=t.root;t.update(86,"C");expect(t.root).not.toBe(b);});
  it("rc 88",()=>{const t=new MerkleTree(makeLeaves(88));const b=t.root;t.update(87,"C");expect(t.root).not.toBe(b);});
  it("rc 89",()=>{const t=new MerkleTree(makeLeaves(89));const b=t.root;t.update(88,"C");expect(t.root).not.toBe(b);});
  it("rc 90",()=>{const t=new MerkleTree(makeLeaves(90));const b=t.root;t.update(89,"C");expect(t.root).not.toBe(b);});
  it("rc 91",()=>{const t=new MerkleTree(makeLeaves(91));const b=t.root;t.update(90,"C");expect(t.root).not.toBe(b);});
  it("rc 92",()=>{const t=new MerkleTree(makeLeaves(92));const b=t.root;t.update(91,"C");expect(t.root).not.toBe(b);});
  it("rc 93",()=>{const t=new MerkleTree(makeLeaves(93));const b=t.root;t.update(92,"C");expect(t.root).not.toBe(b);});
  it("rc 94",()=>{const t=new MerkleTree(makeLeaves(94));const b=t.root;t.update(93,"C");expect(t.root).not.toBe(b);});
  it("rc 95",()=>{const t=new MerkleTree(makeLeaves(95));const b=t.root;t.update(94,"C");expect(t.root).not.toBe(b);});
  it("rc 96",()=>{const t=new MerkleTree(makeLeaves(96));const b=t.root;t.update(95,"C");expect(t.root).not.toBe(b);});
  it("rc 97",()=>{const t=new MerkleTree(makeLeaves(97));const b=t.root;t.update(96,"C");expect(t.root).not.toBe(b);});
  it("rc 98",()=>{const t=new MerkleTree(makeLeaves(98));const b=t.root;t.update(97,"C");expect(t.root).not.toBe(b);});
  it("rc 99",()=>{const t=new MerkleTree(makeLeaves(99));const b=t.root;t.update(98,"C");expect(t.root).not.toBe(b);});
  it("rc 100",()=>{const t=new MerkleTree(makeLeaves(100));const b=t.root;t.update(99,"C");expect(t.root).not.toBe(b);});
});
