// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// Proprietary and confidential. Unauthorised copying prohibited.
// See LICENCE file for details.

import { MerkleTree, verifyMerkleProof } from './merkle-tree';

function makeLeaves(n: number): string[] {
  return Array.from({ length: n }, (_, i) => String.fromCharCode(96)+"leaf-"+i+String.fromCharCode(96));
}

describe('S3 proof idx0', () => {
  it("proof0 1",()=>{const lv=makeLeaves(1);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 2",()=>{const lv=makeLeaves(2);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 3",()=>{const lv=makeLeaves(3);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 4",()=>{const lv=makeLeaves(4);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 5",()=>{const lv=makeLeaves(5);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 6",()=>{const lv=makeLeaves(6);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 7",()=>{const lv=makeLeaves(7);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 8",()=>{const lv=makeLeaves(8);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 9",()=>{const lv=makeLeaves(9);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 10",()=>{const lv=makeLeaves(10);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 11",()=>{const lv=makeLeaves(11);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 12",()=>{const lv=makeLeaves(12);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 13",()=>{const lv=makeLeaves(13);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 14",()=>{const lv=makeLeaves(14);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 15",()=>{const lv=makeLeaves(15);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 16",()=>{const lv=makeLeaves(16);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 17",()=>{const lv=makeLeaves(17);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 18",()=>{const lv=makeLeaves(18);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 19",()=>{const lv=makeLeaves(19);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 20",()=>{const lv=makeLeaves(20);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 21",()=>{const lv=makeLeaves(21);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 22",()=>{const lv=makeLeaves(22);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 23",()=>{const lv=makeLeaves(23);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 24",()=>{const lv=makeLeaves(24);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 25",()=>{const lv=makeLeaves(25);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 26",()=>{const lv=makeLeaves(26);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 27",()=>{const lv=makeLeaves(27);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 28",()=>{const lv=makeLeaves(28);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 29",()=>{const lv=makeLeaves(29);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 30",()=>{const lv=makeLeaves(30);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 31",()=>{const lv=makeLeaves(31);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 32",()=>{const lv=makeLeaves(32);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 33",()=>{const lv=makeLeaves(33);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 34",()=>{const lv=makeLeaves(34);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 35",()=>{const lv=makeLeaves(35);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 36",()=>{const lv=makeLeaves(36);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 37",()=>{const lv=makeLeaves(37);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 38",()=>{const lv=makeLeaves(38);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 39",()=>{const lv=makeLeaves(39);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 40",()=>{const lv=makeLeaves(40);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 41",()=>{const lv=makeLeaves(41);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 42",()=>{const lv=makeLeaves(42);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 43",()=>{const lv=makeLeaves(43);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 44",()=>{const lv=makeLeaves(44);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 45",()=>{const lv=makeLeaves(45);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 46",()=>{const lv=makeLeaves(46);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 47",()=>{const lv=makeLeaves(47);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 48",()=>{const lv=makeLeaves(48);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 49",()=>{const lv=makeLeaves(49);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 50",()=>{const lv=makeLeaves(50);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 51",()=>{const lv=makeLeaves(51);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 52",()=>{const lv=makeLeaves(52);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 53",()=>{const lv=makeLeaves(53);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 54",()=>{const lv=makeLeaves(54);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 55",()=>{const lv=makeLeaves(55);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 56",()=>{const lv=makeLeaves(56);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 57",()=>{const lv=makeLeaves(57);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 58",()=>{const lv=makeLeaves(58);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 59",()=>{const lv=makeLeaves(59);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 60",()=>{const lv=makeLeaves(60);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 61",()=>{const lv=makeLeaves(61);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 62",()=>{const lv=makeLeaves(62);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 63",()=>{const lv=makeLeaves(63);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 64",()=>{const lv=makeLeaves(64);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 65",()=>{const lv=makeLeaves(65);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 66",()=>{const lv=makeLeaves(66);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 67",()=>{const lv=makeLeaves(67);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 68",()=>{const lv=makeLeaves(68);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 69",()=>{const lv=makeLeaves(69);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 70",()=>{const lv=makeLeaves(70);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 71",()=>{const lv=makeLeaves(71);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 72",()=>{const lv=makeLeaves(72);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 73",()=>{const lv=makeLeaves(73);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 74",()=>{const lv=makeLeaves(74);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 75",()=>{const lv=makeLeaves(75);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 76",()=>{const lv=makeLeaves(76);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 77",()=>{const lv=makeLeaves(77);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 78",()=>{const lv=makeLeaves(78);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 79",()=>{const lv=makeLeaves(79);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 80",()=>{const lv=makeLeaves(80);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 81",()=>{const lv=makeLeaves(81);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 82",()=>{const lv=makeLeaves(82);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 83",()=>{const lv=makeLeaves(83);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 84",()=>{const lv=makeLeaves(84);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 85",()=>{const lv=makeLeaves(85);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 86",()=>{const lv=makeLeaves(86);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 87",()=>{const lv=makeLeaves(87);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 88",()=>{const lv=makeLeaves(88);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 89",()=>{const lv=makeLeaves(89);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 90",()=>{const lv=makeLeaves(90);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 91",()=>{const lv=makeLeaves(91);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 92",()=>{const lv=makeLeaves(92);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 93",()=>{const lv=makeLeaves(93);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 94",()=>{const lv=makeLeaves(94);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 95",()=>{const lv=makeLeaves(95);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 96",()=>{const lv=makeLeaves(96);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 97",()=>{const lv=makeLeaves(97);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 98",()=>{const lv=makeLeaves(98);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 99",()=>{const lv=makeLeaves(99);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
  it("proof0 100",()=>{const lv=makeLeaves(100);const t=new MerkleTree(lv);expect(t.verify(lv[0],0,t.getProof(0))).toBe(true);});
});
describe('S4 tampered leaf', () => {
  it("tamp 1",()=>{const t=new MerkleTree(makeLeaves(1));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 2",()=>{const t=new MerkleTree(makeLeaves(2));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 3",()=>{const t=new MerkleTree(makeLeaves(3));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 4",()=>{const t=new MerkleTree(makeLeaves(4));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 5",()=>{const t=new MerkleTree(makeLeaves(5));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 6",()=>{const t=new MerkleTree(makeLeaves(6));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 7",()=>{const t=new MerkleTree(makeLeaves(7));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 8",()=>{const t=new MerkleTree(makeLeaves(8));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 9",()=>{const t=new MerkleTree(makeLeaves(9));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 10",()=>{const t=new MerkleTree(makeLeaves(10));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 11",()=>{const t=new MerkleTree(makeLeaves(11));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 12",()=>{const t=new MerkleTree(makeLeaves(12));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 13",()=>{const t=new MerkleTree(makeLeaves(13));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 14",()=>{const t=new MerkleTree(makeLeaves(14));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 15",()=>{const t=new MerkleTree(makeLeaves(15));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 16",()=>{const t=new MerkleTree(makeLeaves(16));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 17",()=>{const t=new MerkleTree(makeLeaves(17));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 18",()=>{const t=new MerkleTree(makeLeaves(18));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 19",()=>{const t=new MerkleTree(makeLeaves(19));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 20",()=>{const t=new MerkleTree(makeLeaves(20));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 21",()=>{const t=new MerkleTree(makeLeaves(21));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 22",()=>{const t=new MerkleTree(makeLeaves(22));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 23",()=>{const t=new MerkleTree(makeLeaves(23));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 24",()=>{const t=new MerkleTree(makeLeaves(24));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 25",()=>{const t=new MerkleTree(makeLeaves(25));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 26",()=>{const t=new MerkleTree(makeLeaves(26));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 27",()=>{const t=new MerkleTree(makeLeaves(27));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 28",()=>{const t=new MerkleTree(makeLeaves(28));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 29",()=>{const t=new MerkleTree(makeLeaves(29));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 30",()=>{const t=new MerkleTree(makeLeaves(30));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 31",()=>{const t=new MerkleTree(makeLeaves(31));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 32",()=>{const t=new MerkleTree(makeLeaves(32));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 33",()=>{const t=new MerkleTree(makeLeaves(33));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 34",()=>{const t=new MerkleTree(makeLeaves(34));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 35",()=>{const t=new MerkleTree(makeLeaves(35));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 36",()=>{const t=new MerkleTree(makeLeaves(36));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 37",()=>{const t=new MerkleTree(makeLeaves(37));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 38",()=>{const t=new MerkleTree(makeLeaves(38));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 39",()=>{const t=new MerkleTree(makeLeaves(39));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 40",()=>{const t=new MerkleTree(makeLeaves(40));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 41",()=>{const t=new MerkleTree(makeLeaves(41));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 42",()=>{const t=new MerkleTree(makeLeaves(42));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 43",()=>{const t=new MerkleTree(makeLeaves(43));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 44",()=>{const t=new MerkleTree(makeLeaves(44));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 45",()=>{const t=new MerkleTree(makeLeaves(45));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 46",()=>{const t=new MerkleTree(makeLeaves(46));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 47",()=>{const t=new MerkleTree(makeLeaves(47));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 48",()=>{const t=new MerkleTree(makeLeaves(48));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 49",()=>{const t=new MerkleTree(makeLeaves(49));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 50",()=>{const t=new MerkleTree(makeLeaves(50));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 51",()=>{const t=new MerkleTree(makeLeaves(51));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 52",()=>{const t=new MerkleTree(makeLeaves(52));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 53",()=>{const t=new MerkleTree(makeLeaves(53));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 54",()=>{const t=new MerkleTree(makeLeaves(54));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 55",()=>{const t=new MerkleTree(makeLeaves(55));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 56",()=>{const t=new MerkleTree(makeLeaves(56));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 57",()=>{const t=new MerkleTree(makeLeaves(57));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 58",()=>{const t=new MerkleTree(makeLeaves(58));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 59",()=>{const t=new MerkleTree(makeLeaves(59));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 60",()=>{const t=new MerkleTree(makeLeaves(60));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 61",()=>{const t=new MerkleTree(makeLeaves(61));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 62",()=>{const t=new MerkleTree(makeLeaves(62));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 63",()=>{const t=new MerkleTree(makeLeaves(63));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 64",()=>{const t=new MerkleTree(makeLeaves(64));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 65",()=>{const t=new MerkleTree(makeLeaves(65));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 66",()=>{const t=new MerkleTree(makeLeaves(66));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 67",()=>{const t=new MerkleTree(makeLeaves(67));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 68",()=>{const t=new MerkleTree(makeLeaves(68));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 69",()=>{const t=new MerkleTree(makeLeaves(69));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 70",()=>{const t=new MerkleTree(makeLeaves(70));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 71",()=>{const t=new MerkleTree(makeLeaves(71));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 72",()=>{const t=new MerkleTree(makeLeaves(72));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 73",()=>{const t=new MerkleTree(makeLeaves(73));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 74",()=>{const t=new MerkleTree(makeLeaves(74));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 75",()=>{const t=new MerkleTree(makeLeaves(75));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 76",()=>{const t=new MerkleTree(makeLeaves(76));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 77",()=>{const t=new MerkleTree(makeLeaves(77));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 78",()=>{const t=new MerkleTree(makeLeaves(78));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 79",()=>{const t=new MerkleTree(makeLeaves(79));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 80",()=>{const t=new MerkleTree(makeLeaves(80));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 81",()=>{const t=new MerkleTree(makeLeaves(81));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 82",()=>{const t=new MerkleTree(makeLeaves(82));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 83",()=>{const t=new MerkleTree(makeLeaves(83));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 84",()=>{const t=new MerkleTree(makeLeaves(84));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 85",()=>{const t=new MerkleTree(makeLeaves(85));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 86",()=>{const t=new MerkleTree(makeLeaves(86));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 87",()=>{const t=new MerkleTree(makeLeaves(87));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 88",()=>{const t=new MerkleTree(makeLeaves(88));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 89",()=>{const t=new MerkleTree(makeLeaves(89));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 90",()=>{const t=new MerkleTree(makeLeaves(90));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 91",()=>{const t=new MerkleTree(makeLeaves(91));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 92",()=>{const t=new MerkleTree(makeLeaves(92));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 93",()=>{const t=new MerkleTree(makeLeaves(93));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 94",()=>{const t=new MerkleTree(makeLeaves(94));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 95",()=>{const t=new MerkleTree(makeLeaves(95));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 96",()=>{const t=new MerkleTree(makeLeaves(96));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 97",()=>{const t=new MerkleTree(makeLeaves(97));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 98",()=>{const t=new MerkleTree(makeLeaves(98));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 99",()=>{const t=new MerkleTree(makeLeaves(99));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
  it("tamp 100",()=>{const t=new MerkleTree(makeLeaves(100));expect(t.verify("X",0,t.getProof(0))).toBe(false);});
});
