apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ims

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - infrastructure.yaml
  - api-gateway.yaml
  - microservices.yaml
  - ingress.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: ims
  app.kubernetes.io/part-of: integrated-management-system
  app.kubernetes.io/managed-by: kustomize
