'use client';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@ims/ui';
import { Plus, Search, Crosshair } from 'lucide-react';
import { api } from '@/lib/api';
interface Item { id: string; [key: string]: any; }
export default function CCPsPage() {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [searchTerm, setSearchTerm] = useState('');
  useEffect(() => { (async () => { try { const res = await api.get('/ccps'); setItems(res.data.data || []); } catch (e) { console.error('Error:', e); } finally { setLoading(false); } })(); }, []);
  const filtered = items.filter(i => JSON.stringify(i).toLowerCase().includes(searchTerm.toLowerCase()));
  if (loading) return <div className="p-8"><div className="animate-pulse space-y-4"><div className="h-8 bg-gray-200 rounded w-1/4" /><div className="h-64 bg-gray-200 rounded" /></div></div>;
  return (<div className="p-8"><div className="max-w-7xl mx-auto"><div className="flex justify-between items-center mb-6"><div><h1 className="text-3xl font-bold text-gray-900">Critical Control Points</h1><p className="text-gray-500 mt-1">Manage HACCP critical control points</p></div><button className="bg-orange-600 text-white px-4 py-2 rounded-lg hover:bg-orange-700 flex items-center gap-2"><Plus className="h-5 w-5" /> Add CCP</button></div><div className="mb-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" /><input type="text" placeholder="Search CCPs..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} className="pl-10 pr-4 py-2 border rounded-lg w-full" /></div></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><Crosshair className="h-5 w-5 text-orange-600" />CCPs ({filtered.length})</CardTitle></CardHeader><CardContent>{filtered.length > 0 ? (<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="text-left py-3 px-4 font-medium text-gray-500">Name</th><th className="text-left py-3 px-4 font-medium text-gray-500">Type</th><th className="text-left py-3 px-4 font-medium text-gray-500">Critical Limit</th><th className="text-left py-3 px-4 font-medium text-gray-500">Status</th></tr></thead><tbody>{filtered.map(item => (<tr key={item.id} className="border-b hover:bg-gray-50"><td className="py-3 px-4 text-gray-900 font-medium">{item.name || item.title || '-'}</td><td className="py-3 px-4 text-gray-600">{item.type || item.hazardType || '-'}</td><td className="py-3 px-4 text-gray-600">{item.criticalLimit || '-'}</td><td className="py-3 px-4"><span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${item.status === 'ACTIVE' || item.status === 'IN_CONTROL' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>{item.status?.replace(/_/g, ' ') || '-'}</span></td></tr>)}</tbody></table></div>) : (<div className="text-center py-12 text-gray-500"><Crosshair className="h-12 w-12 mx-auto mb-4 opacity-50" /><p>No CCPs found</p></div>)}</CardContent></Card></div></div>);
}
