import { EmissionFactor } from './types';

/**
 * UK DEFRA 2024 Greenhouse Gas Conversion Factors.
 * Source: UK Government GHG Conversion Factors for Company Reporting.
 * All factors in kgCO2e per unit specified.
 */
export const DEFRA_FACTORS: EmissionFactor[] = [
  // Scope 1 - Direct emissions (fuels)
  {
    type: 'natural_gas',
    factor: 2.02,
    unit: 'm3',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'diesel',
    factor: 2.68,
    unit: 'litre',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'petrol',
    factor: 2.31,
    unit: 'litre',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'lpg',
    factor: 1.56,
    unit: 'litre',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'coal',
    factor: 2.88,
    unit: 'kg',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'heating_oil',
    factor: 2.54,
    unit: 'litre',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'biodiesel',
    factor: 0.17,
    unit: 'litre',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'bioethanol',
    factor: 0.14,
    unit: 'litre',
    co2eUnit: 'kgCO2e',
    scope: 'scope1',
    source: 'DEFRA',
    year: 2024,
  },

  // Scope 2 - Indirect emissions (electricity)
  {
    type: 'grid_electricity',
    factor: 0.207,
    unit: 'kWh',
    co2eUnit: 'kgCO2e',
    scope: 'scope2',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'renewable_electricity',
    factor: 0.0,
    unit: 'kWh',
    co2eUnit: 'kgCO2e',
    scope: 'scope2',
    source: 'DEFRA',
    year: 2024,
  },

  // Scope 3 - Other indirect
  {
    type: 'water_supply',
    factor: 0.149,
    unit: 'm3',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'water_treatment',
    factor: 0.272,
    unit: 'm3',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'waste_landfill',
    factor: 467.05,
    unit: 'tonne',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'waste_recycled',
    factor: 21.35,
    unit: 'tonne',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'business_travel_car',
    factor: 0.171,
    unit: 'km',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'business_travel_rail',
    factor: 0.035,
    unit: 'km',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'business_travel_air_domestic',
    factor: 0.246,
    unit: 'km',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'business_travel_air_short',
    factor: 0.156,
    unit: 'km',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
  {
    type: 'business_travel_air_long',
    factor: 0.195,
    unit: 'km',
    co2eUnit: 'kgCO2e',
    scope: 'scope3',
    source: 'DEFRA',
    year: 2024,
  },
];
