// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { StandardAssessment } from './types';

export const iso42001Assessment: StandardAssessment = {
  standardId: 'iso-42001-2023',
  standardName: 'ISO 42001:2023',
  version: '2023',
  clauses: [
    {
      id: '4.1',
      title: 'Understanding the organisation and its context',
      description: 'Determine external and internal issues relevant to the organisation\'s purpose that affect its ability to achieve intended outcomes of the AI management system.',
      evidenceExamples: ['AI context analysis', 'AI regulatory landscape review', 'Organisational AI strategy documents'],
      mandatory: true,
    },
    {
      id: '4.2',
      title: 'Understanding needs and expectations of interested parties',
      description: 'Identify interested parties relevant to the AIMS and their relevant requirements including ethical expectations and regulatory obligations for AI.',
      evidenceExamples: ['AI stakeholder register', 'User rights documentation', 'Regulatory obligation register for AI'],
      mandatory: true,
    },
    {
      id: '4.3',
      title: 'Determining scope of the AIMS',
      description: 'Determine boundaries and applicability of the AI management system considering internal/external issues and interested party requirements.',
      evidenceExamples: ['AIMS scope statement', 'AI system inventory in scope', 'Scope exclusions justification'],
      mandatory: true,
    },
    {
      id: '4.4',
      title: 'AI management system',
      description: 'Establish, implement, maintain, and continually improve an AIMS including required processes and their interactions in accordance with this standard.',
      evidenceExamples: ['AIMS policy and framework', 'AI governance structure', 'Process documentation'],
      mandatory: true,
    },
    {
      id: '5.1',
      title: 'Leadership and commitment',
      description: 'Top management shall demonstrate leadership and commitment to the AIMS, integrating it with business strategy and ensuring necessary resources are provided.',
      evidenceExamples: ['Executive AI policy sign-off', 'AI governance committee charter', 'Leadership AI accountability evidence'],
      mandatory: true,
    },
    {
      id: '5.2',
      title: 'AI policy',
      description: 'Top management shall establish an AI policy appropriate to the organisation\'s context, committing to responsible AI development and use.',
      evidenceExamples: ['AI policy document', 'Responsible AI principles', 'Policy communication evidence'],
      mandatory: true,
    },
    {
      id: '5.3',
      title: 'Roles, responsibilities and authorities',
      description: 'Assign and communicate roles and responsibilities for AI management including AI system owners, ethics reviewers, and data governance roles.',
      evidenceExamples: ['RACI for AI systems', 'AI owner/custodian assignments', 'AI ethics officer role definition'],
      mandatory: true,
    },
    {
      id: '6.1',
      title: 'Actions to address risks and opportunities',
      description: 'Determine risks and opportunities relating to AI systems including bias, safety, privacy, security, and societal impact. Plan and implement actions.',
      evidenceExamples: ['AI risk register', 'AI impact assessment', 'Bias and fairness risk analysis'],
      mandatory: true,
    },
    {
      id: '6.1.2',
      title: 'AI risk assessment',
      description: 'Perform AI-specific risk assessments considering technical risks (model failure, drift, adversarial attacks) and non-technical risks (bias, transparency, accountability).',
      evidenceExamples: ['AI risk assessment reports', 'Model risk assessments', 'Algorithmic impact assessments'],
      mandatory: true,
    },
    {
      id: '6.1.3',
      title: 'AI risk treatment',
      description: 'Select and implement appropriate treatment options for identified AI risks. Document residual risk and obtain acceptance.',
      evidenceExamples: ['AI risk treatment plan', 'Control implementation evidence', 'Residual risk acceptance records'],
      mandatory: true,
    },
    {
      id: '6.2',
      title: 'AI objectives and planning',
      description: 'Establish AI objectives aligned with policy, covering responsible AI goals such as fairness, transparency, privacy, and safety.',
      evidenceExamples: ['AI objectives register', 'KPIs for responsible AI', 'AI objectives review records'],
      mandatory: true,
    },
    {
      id: '7.1',
      title: 'Resources',
      description: 'Determine and provide resources for establishing, implementing, maintaining, and continually improving the AIMS including technical infrastructure and human expertise.',
      evidenceExamples: ['AI team structure and headcount', 'AI infrastructure inventory', 'AI budget allocation'],
      mandatory: true,
    },
    {
      id: '7.2',
      title: 'Competence',
      description: 'Ensure persons doing work that affects AI system performance are competent in AI ethics, governance, technical AI concepts, and applicable regulations.',
      evidenceExamples: ['AI competency framework', 'AI training programme records', 'AI literacy assessment results'],
      mandatory: true,
    },
    {
      id: '7.3',
      title: 'Awareness',
      description: 'Ensure personnel are aware of AI policy, responsible AI principles, their contribution to AIMS effectiveness, and the implications of AI failures.',
      evidenceExamples: ['AI awareness training records', 'Responsible AI communications', 'AI ethics onboarding materials'],
      mandatory: true,
    },
    {
      id: '7.4',
      title: 'Communication',
      description: 'Determine internal and external communications relevant to the AIMS. Include transparency communication to users and stakeholders about AI system capabilities and limitations.',
      evidenceExamples: ['AI transparency disclosures', 'User communication on AI use', 'Internal AI governance communications'],
      mandatory: true,
    },
    {
      id: '7.5',
      title: 'Documented information',
      description: 'Maintain documented information required by the standard and determined as necessary for AIMS effectiveness, including AI system documentation and model cards.',
      evidenceExamples: ['AI system registry', 'Model cards/data sheets', 'AI decision documentation', 'AIMS procedures'],
      mandatory: true,
    },
    {
      id: '8.1',
      title: 'Operational planning and control',
      description: 'Plan, implement, control, and maintain processes for responsible AI development and deployment including design controls and operational guardrails.',
      evidenceExamples: ['AI development lifecycle procedures', 'AI deployment checklists', 'Operational monitoring procedures'],
      mandatory: true,
    },
    {
      id: '8.2',
      title: 'AI system impact assessment',
      description: 'Conduct impact assessments for AI systems considering effects on individuals, groups, and society including potential for discrimination or harm.',
      evidenceExamples: ['Algorithmic impact assessments', 'AI fairness assessment reports', 'Human rights impact analysis'],
      mandatory: true,
    },
    {
      id: '8.3',
      title: 'AI system life cycle',
      description: 'Manage the complete AI system life cycle from data collection and model development through deployment, monitoring, and decommissioning.',
      evidenceExamples: ['AI system lifecycle documentation', 'Data lineage records', 'Model versioning and retirement procedures'],
      mandatory: true,
    },
    {
      id: '8.4',
      title: 'Data for AI systems',
      description: 'Manage data used in AI systems to ensure quality, representativeness, and appropriate handling. Address data bias, provenance, and privacy.',
      evidenceExamples: ['Data quality assessment', 'Data governance procedures', 'Training data documentation', 'Data bias analysis'],
      mandatory: true,
    },
    {
      id: '8.5',
      title: 'AI system design',
      description: 'Apply responsible AI design principles including explainability, fairness, robustness, safety, and privacy by design in AI system development.',
      evidenceExamples: ['AI design principles documentation', 'Explainability/XAI records', 'Safety by design evidence', 'Privacy by design documentation'],
      mandatory: true,
    },
    {
      id: '8.6',
      title: 'AI system verification and validation',
      description: 'Verify and validate AI systems against requirements including performance, fairness, safety, and security before and after deployment.',
      evidenceExamples: ['AI testing and validation reports', 'Fairness evaluation results', 'Model performance benchmarks', 'Red team/adversarial testing records'],
      mandatory: true,
    },
    {
      id: '8.7',
      title: 'AI system operation',
      description: 'Operate AI systems with appropriate monitoring, human oversight mechanisms, and incident response procedures.',
      evidenceExamples: ['AI operational monitoring dashboard', 'Human oversight procedures', 'Model drift detection records', 'AI incident response plan'],
      mandatory: true,
    },
    {
      id: '9.1',
      title: 'Monitoring, measurement, analysis and evaluation',
      description: 'Monitor and measure AIMS performance including AI system outcomes, responsible AI KPIs, and alignment with policy and objectives.',
      evidenceExamples: ['AI performance metrics', 'Responsible AI KPI tracking', 'AIMS effectiveness evaluation'],
      mandatory: true,
    },
    {
      id: '9.2',
      title: 'Internal audit',
      description: 'Conduct internal audits at planned intervals to confirm the AIMS conforms to the organisation\'s requirements and ISO 42001.',
      evidenceExamples: ['AI audit programme', 'AI audit reports', 'Auditor competency records'],
      mandatory: true,
    },
    {
      id: '9.3',
      title: 'Management review',
      description: 'Top management shall review the AIMS at planned intervals to ensure its continuing suitability, adequacy, effectiveness, and alignment with strategic direction.',
      evidenceExamples: ['AI governance committee minutes', 'AIMS management review records', 'AI strategy alignment review'],
      mandatory: true,
    },
    {
      id: '10.1',
      title: 'Nonconformity and corrective action',
      description: 'React to AI-related nonconformities including model failures, bias incidents, and governance gaps. Implement corrective actions addressing root causes.',
      evidenceExamples: ['AI incident/nonconformity log', 'Root cause analysis for AI failures', 'Corrective action tracking'],
      mandatory: true,
    },
    {
      id: '10.2',
      title: 'Continual improvement',
      description: 'Continually improve the suitability, adequacy, and effectiveness of the AIMS, tracking emerging AI risks and regulatory developments.',
      evidenceExamples: ['AIMS improvement register', 'AI maturity roadmap', 'Emerging AI risk horizon scanning'],
      mandatory: true,
    },
  ],
};
