// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { StandardAssessment } from './types';

export const iso13485Assessment: StandardAssessment = {
  standardId: 'iso-13485-2016',
  standardName: 'ISO 13485:2016',
  version: '2016',
  clauses: [
    {
      id: '4.1',
      title: 'QMS — general requirements',
      description: 'Establish, document, implement, maintain, and improve QMS for medical devices per ISO 13485:2016.',
      evidenceExamples: ['QMS manual', 'Process map', 'Risk management file', 'Regulatory strategy document'],
      mandatory: true,
    },
    {
      id: '4.2',
      title: 'Documentation requirements',
      description: 'Maintain QMS documentation including quality manual, procedures, work instructions, and records.',
      evidenceExamples: ['Document hierarchy', 'Document register', 'Quality manual', 'Records retention policy'],
      mandatory: true,
    },
    {
      id: '4.2.3',
      title: 'Medical device file',
      description: 'Maintain medical device file (technical file) for each device type.',
      evidenceExamples: ['Device technical file', 'Design history file', 'Device master record', 'Risk management file per ISO 14971'],
      mandatory: true,
    },
    {
      id: '5.1',
      title: 'Management commitment',
      description: 'Top management demonstrate commitment to QMS and applicable regulatory requirements.',
      evidenceExamples: ['Quality policy signed by CEO', 'Management review minutes', 'Resource allocation records'],
      mandatory: true,
    },
    {
      id: '5.2',
      title: 'Customer focus',
      description: 'Determine and meet customer requirements and applicable regulatory requirements.',
      evidenceExamples: ['Customer requirements register', 'Regulatory compliance matrix', 'Customer satisfaction data'],
      mandatory: true,
    },
    {
      id: '5.3',
      title: 'Quality policy',
      description: 'Quality policy appropriate to medical device manufacturer with regulatory compliance commitment.',
      evidenceExamples: ['Current signed quality policy', 'Annual policy review records', 'Communication evidence'],
      mandatory: true,
    },
    {
      id: '5.4',
      title: 'Planning',
      description: 'Quality objectives and planning to maintain integrity when changes occur.',
      evidenceExamples: ['Quality objectives register', 'Change control plan', 'Risk-based planning records'],
      mandatory: true,
    },
    {
      id: '5.5',
      title: 'Responsibility, authority and communication',
      description: 'Defined responsibilities including Regulatory Affairs and Management Representative.',
      evidenceExamples: ['Organisation chart', 'Job descriptions', 'Management Representative appointment', 'Regulatory contact list'],
      mandatory: true,
    },
    {
      id: '5.6',
      title: 'Management review',
      description: 'Periodic management review covering regulatory requirements, complaints, audits, and post-market surveillance.',
      evidenceExamples: ['Management review minutes', 'Post-market surveillance summary', 'Complaint trend analysis'],
      mandatory: true,
    },
    {
      id: '6.1',
      title: 'Resource management',
      description: 'Determine and provide resources to implement and maintain QMS including clean room/controlled environments.',
      evidenceExamples: ['Resource plan', 'Facility qualification records', 'Environmental monitoring records'],
      mandatory: true,
    },
    {
      id: '6.2',
      title: 'Human resources',
      description: 'Competent personnel with appropriate education, training, skills, and experience for device manufacture.',
      evidenceExamples: ['Training matrix', 'Competence records', 'GMP training records', 'Role-specific qualifications'],
      mandatory: true,
    },
    {
      id: '6.3',
      title: 'Infrastructure',
      description: 'Maintain infrastructure necessary for product conformity including clean rooms and equipment.',
      evidenceExamples: ['Facility maintenance records', 'Clean room qualification', 'Equipment qualification (IQ/OQ/PQ)'],
      mandatory: true,
    },
    {
      id: '6.4',
      title: 'Work environment',
      description: 'Control work environment including contamination control and health/cleanliness requirements for personnel.',
      evidenceExamples: ['Environmental monitoring plan', 'Contamination control procedure', 'Gowning procedures', 'Environmental monitoring records'],
      mandatory: true,
    },
    {
      id: '7.1',
      title: 'Planning of product realisation',
      description: 'Plan product realisation including risk management activities per ISO 14971.',
      evidenceExamples: ['Project quality plan', 'Risk management plan (ISO 14971)', 'Design and development plan'],
      mandatory: true,
    },
    {
      id: '7.2',
      title: 'Customer-related processes',
      description: 'Determine, review, and communicate requirements including intended use and applicable regulations.',
      evidenceExamples: ['Intended use statement', 'Contract review records', 'Regulatory requirement flowdown'],
      mandatory: true,
    },
    {
      id: '7.3',
      title: 'Design and development',
      description: 'Design and development with planning, inputs, outputs, reviews, verification, and validation.',
      evidenceExamples: ['Design history file', 'Design review records', 'Verification protocols/reports', 'Clinical evaluation', 'Usability engineering file'],
      mandatory: true,
    },
    {
      id: '7.4',
      title: 'Purchasing',
      description: 'Control purchased products/services including critical component qualification and supplier management.',
      evidenceExamples: ['Approved Supplier List', 'Supplier qualification records', 'Component qualification records', 'Incoming inspection records'],
      mandatory: true,
    },
    {
      id: '7.5',
      title: 'Production and service provision',
      description: 'Controlled manufacturing with documented procedures, validated processes, and clean environment.',
      evidenceExamples: ['Batch records', 'Device history record (DHR)', 'Validated process records', 'Sterility testing records'],
      mandatory: true,
    },
    {
      id: '7.5.6',
      title: 'Validation of processes for production',
      description: 'Validate processes where output cannot be verified by subsequent monitoring — sterilisation, clean room, etc.',
      evidenceExamples: ['Process validation protocols', 'PQ/OQ/IQ records', 'Sterilisation validation', 'Software validation records'],
      mandatory: true,
    },
    {
      id: '7.5.8',
      title: 'Identification and traceability',
      description: 'Full UDI-compliant traceability of all devices from component to patient if applicable.',
      evidenceExamples: ['UDI assignment records', 'Lot/serial number traceability records', 'Distribution records', 'Device history records'],
      mandatory: true,
    },
    {
      id: '7.6',
      title: 'Control of monitoring and measuring devices',
      description: 'Calibrated measurement equipment with traceability to international standards.',
      evidenceExamples: ['Calibration schedule', 'Calibration certificates', 'Out-of-tolerance investigation records'],
      mandatory: true,
    },
    {
      id: '8.1',
      title: 'Measurement, analysis and improvement — general',
      description: 'Plan and implement monitoring, measurement, and improvement processes including statistical methods.',
      evidenceExamples: ['Quality performance metrics', 'Statistical methods documentation', 'CAPA effectiveness data'],
      mandatory: true,
    },
    {
      id: '8.2',
      title: 'Monitoring and measurement',
      description: 'Monitor and measure customer satisfaction, QMS, processes, and product conformity.',
      evidenceExamples: ['Post-market surveillance data', 'Complaint analysis', 'Process capability data', 'Final inspection records'],
      mandatory: true,
    },
    {
      id: '8.2.1',
      title: 'Feedback — complaint handling',
      description: 'Documented procedure for receiving, documenting, and evaluating customer feedback and complaints.',
      evidenceExamples: ['Complaint handling procedure', 'Complaint register', 'MDR/vigilance reports', 'Regulatory reporting records'],
      mandatory: true,
    },
    {
      id: '8.2.3',
      title: 'Reporting to regulatory authorities',
      description: 'Report to regulatory authorities as required: MDRs (FDA), vigilance reports (EU MDR), etc.',
      evidenceExamples: ['Reportability analysis procedure', 'MDR/vigilance report log', 'Submission acknowledgement records'],
      mandatory: true,
    },
    {
      id: '8.3',
      title: 'Control of nonconforming product',
      description: 'Identify, control, and segregate nonconforming products; document disposition decisions.',
      evidenceExamples: ['Nonconformance procedure', 'NCR log', 'Concession/waiver records', 'MRB records'],
      mandatory: true,
    },
    {
      id: '8.4',
      title: 'Analysis of data',
      description: 'Collect and analyse data demonstrating suitability and effectiveness of QMS; identify improvements.',
      evidenceExamples: ['Quality KPI reports', 'Trend analysis records', 'Management review data pack', 'Supplier performance data'],
      mandatory: true,
    },
    {
      id: '8.5',
      title: 'Improvement',
      description: 'Corrective actions (with root cause analysis), preventive actions, and documented CAPA system.',
      evidenceExamples: ['CAPA procedure', 'CAPA log', 'Root cause analysis records', 'Effectiveness checks', 'Preventive action log'],
      mandatory: true,
    },
  ],
};
