// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { StandardAssessment } from './types';

export const iso9001Assessment: StandardAssessment = {
  standardId: 'iso-9001-2015',
  standardName: 'ISO 9001:2015',
  version: '2015',
  clauses: [
    {
      id: '4.1',
      title: 'Understanding the organisation and its context',
      description: 'The organisation shall determine external and internal issues relevant to its purpose and its strategic direction.',
      evidenceExamples: ['SWOT analysis', 'PESTLE analysis', 'Strategic planning documents', 'Management review minutes'],
      mandatory: true,
    },
    {
      id: '4.2',
      title: 'Understanding the needs of interested parties',
      description: 'The organisation shall determine the relevant interested parties and their relevant requirements.',
      evidenceExamples: ['Stakeholder register', 'Customer requirements register', 'Legal register'],
      mandatory: true,
    },
    {
      id: '4.3',
      title: 'Determining the scope of the QMS',
      description: 'The organisation shall determine the boundaries and applicability of the QMS.',
      evidenceExamples: ['QMS scope statement', 'Exclusions justification', 'Certificate of registration'],
      mandatory: true,
    },
    {
      id: '4.4',
      title: 'Quality management system and its processes',
      description: 'The organisation shall establish, implement, maintain and continually improve a QMS, including the processes needed.',
      evidenceExamples: ['Process map', 'Process interactions diagram', 'Process owners list'],
      mandatory: true,
    },
    {
      id: '5.1',
      title: 'Leadership and commitment',
      description: 'Top management shall demonstrate leadership and commitment with respect to the QMS.',
      evidenceExamples: ['Management review records', 'Quality policy signed by CEO', 'Resource allocation evidence'],
      mandatory: true,
    },
    {
      id: '5.2',
      title: 'Quality policy',
      description: 'Top management shall establish, implement and maintain a quality policy.',
      evidenceExamples: ['Signed quality policy document', 'Communication evidence', 'Accessibility records'],
      mandatory: true,
    },
    {
      id: '5.3',
      title: 'Organisational roles, responsibilities and authorities',
      description: 'Top management shall ensure that responsibilities and authorities are assigned and communicated.',
      evidenceExamples: ['Organisation chart', 'Job descriptions', 'RACI matrix', 'Management rep appointment letter'],
      mandatory: true,
    },
    {
      id: '6.1',
      title: 'Actions to address risks and opportunities',
      description: 'The organisation shall determine the risks and opportunities that need to be addressed.',
      evidenceExamples: ['Risk register', 'Risk assessment methodology', 'Risk treatment plan'],
      mandatory: true,
    },
    {
      id: '6.2',
      title: 'Quality objectives and planning to achieve them',
      description: 'The organisation shall establish quality objectives at relevant functions and levels.',
      evidenceExamples: ['Objectives register', 'KPI dashboard', 'Action plans', 'Management review minutes'],
      mandatory: true,
    },
    {
      id: '6.3',
      title: 'Planning of changes',
      description: 'When the organisation determines the need for changes to the QMS, such changes shall be carried out in a planned manner.',
      evidenceExamples: ['Change control procedure', 'Change request forms', 'Change log'],
      mandatory: true,
    },
    {
      id: '7.1',
      title: 'Resources',
      description: 'The organisation shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the QMS.',
      evidenceExamples: ['Resource allocation plans', 'Infrastructure register', 'Calibration records', 'IT inventory'],
      mandatory: true,
    },
    {
      id: '7.2',
      title: 'Competence',
      description: 'The organisation shall determine the necessary competence of person(s) doing work under its control.',
      evidenceExamples: ['Competence matrix', 'Training records', 'Certificates of competence', 'CVs'],
      mandatory: true,
    },
    {
      id: '7.3',
      title: 'Awareness',
      description: "Persons doing work under the organisation's control shall be aware of the quality policy and their contribution.",
      evidenceExamples: ['Induction records', 'Toolbox talk records', 'Communication logs', 'Staff survey results'],
      mandatory: true,
    },
    {
      id: '7.4',
      title: 'Communication',
      description: 'The organisation shall determine the internal and external communications relevant to the QMS.',
      evidenceExamples: ['Communication plan', 'Meeting minutes', 'Intranet postings', 'Customer communications'],
      mandatory: true,
    },
    {
      id: '7.5',
      title: 'Documented information',
      description: 'The QMS shall include documented information required by ISO 9001:2015 and determined as necessary by the organisation.',
      evidenceExamples: ['Document register', 'Document control procedure', 'Records retention schedule'],
      mandatory: true,
    },
    {
      id: '8.1',
      title: 'Operational planning and control',
      description: 'The organisation shall plan, implement, control, maintain and retain documented information.',
      evidenceExamples: ['Production plans', 'Quality plans', 'Inspection records', 'Process instructions'],
      mandatory: true,
    },
    {
      id: '8.2',
      title: 'Requirements for products and services',
      description: 'The organisation shall implement a process for communicating with customers.',
      evidenceExamples: ['Customer contracts', 'Order acknowledgements', 'Customer requirements register', 'Post-delivery feedback'],
      mandatory: true,
    },
    {
      id: '8.3',
      title: 'Design and development of products and services',
      description: 'The organisation shall establish, implement and maintain a design and development process.',
      evidenceExamples: ['Design plan', 'Design review records', 'Design verification records', 'Design validation records'],
      mandatory: false,
    },
    {
      id: '8.4',
      title: 'Control of externally provided processes, products and services',
      description: 'The organisation shall ensure that externally provided processes, products and services conform to requirements.',
      evidenceExamples: ['Approved supplier list', 'Supplier evaluation records', 'Purchase orders', 'Incoming inspection records'],
      mandatory: true,
    },
    {
      id: '8.5',
      title: 'Production and service provision',
      description: 'The organisation shall implement production and service provision under controlled conditions.',
      evidenceExamples: ['Work instructions', 'Production records', 'Batch records', 'Traceability records'],
      mandatory: true,
    },
    {
      id: '8.6',
      title: 'Release of products and services',
      description: 'The organisation shall implement planned arrangements to verify that the product and service requirements have been met.',
      evidenceExamples: ['Inspection records', 'Test certificates', 'Final acceptance records', 'Dispatch notes'],
      mandatory: true,
    },
    {
      id: '8.7',
      title: 'Control of nonconforming outputs',
      description: 'The organisation shall ensure that outputs that do not conform to their requirements are identified and controlled.',
      evidenceExamples: ['NCR register', 'Quarantine records', 'Concession records', 'Scrap/rework records'],
      mandatory: true,
    },
    {
      id: '9.1',
      title: 'Monitoring, measurement, analysis and evaluation',
      description: 'The organisation shall determine what needs to be monitored and measured.',
      evidenceExamples: ['KPI reports', 'Customer satisfaction surveys', 'Internal audit schedule', 'Data analysis records'],
      mandatory: true,
    },
    {
      id: '9.2',
      title: 'Internal audit',
      description: 'The organisation shall conduct internal audits at planned intervals.',
      evidenceExamples: ['Audit programme', 'Audit reports', 'Audit findings log', 'Corrective action records'],
      mandatory: true,
    },
    {
      id: '9.3',
      title: 'Management review',
      description: "Top management shall review the organisation's QMS at planned intervals.",
      evidenceExamples: ['Management review agenda', 'Management review minutes', 'Action plan from review'],
      mandatory: true,
    },
    {
      id: '10.1',
      title: 'Improvement — General',
      description: 'The organisation shall determine and select opportunities for improvement.',
      evidenceExamples: ['Improvement register', 'Lessons learned log', 'Innovation pipeline'],
      mandatory: true,
    },
    {
      id: '10.2',
      title: 'Nonconformity and corrective action',
      description: 'When a nonconformity occurs, the organisation shall react to the nonconformity.',
      evidenceExamples: ['CAPA register', 'Root cause analysis records', 'Corrective action verification records'],
      mandatory: true,
    },
    {
      id: '10.3',
      title: 'Continual improvement',
      description: 'The organisation shall continually improve the suitability, adequacy and effectiveness of the QMS.',
      evidenceExamples: ['Improvement plan', 'Trend analysis', 'Benchmarking records', 'Management review outputs'],
      mandatory: true,
    },
  ],
};
