// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { StandardAssessment } from './types';

export const iso22000Assessment: StandardAssessment = {
  standardId: 'iso-22000-2018',
  standardName: 'ISO 22000:2018',
  version: '2018',
  clauses: [
    {
      id: '4.1',
      title: 'Understanding the organisation and its context',
      description: 'Determine issues relevant to food safety and the FSMS.',
      evidenceExamples: ['Food safety context analysis', 'SWOT analysis for food safety', 'Product and market scope document'],
      mandatory: true,
    },
    {
      id: '4.2',
      title: 'Understanding needs and expectations of interested parties',
      description: 'Identify interested parties (customers, regulators, certifying bodies) and their food safety requirements.',
      evidenceExamples: ['Interested party register', 'Regulatory register', 'Customer specification register', 'Third-party audit requirements'],
      mandatory: true,
    },
    {
      id: '4.3',
      title: 'Scope of the FSMS',
      description: 'Define scope including products, product categories, and applicable food chain steps.',
      evidenceExamples: ['FSMS scope statement', 'Product scope list', 'Certificate of registration', 'Flow diagram with scope boundary'],
      mandatory: true,
    },
    {
      id: '4.4',
      title: 'FSMS and its processes',
      description: 'Establish, implement, maintain, update, and continually improve FSMS.',
      evidenceExamples: ['FSMS procedure set', 'Process interaction map', 'FSMS implementation records'],
      mandatory: true,
    },
    {
      id: '5.1',
      title: 'Leadership and commitment',
      description: 'Top management demonstrate commitment to food safety culture and FSMS effectiveness.',
      evidenceExamples: ['Signed food safety policy', 'Management review records', 'Resource commitment evidence', 'Food safety culture plan'],
      mandatory: true,
    },
    {
      id: '5.2',
      title: 'Food safety policy',
      description: 'Documented food safety policy communicating commitment to statutory/regulatory compliance and continual improvement.',
      evidenceExamples: ['Current signed food safety policy', 'Communication evidence', 'Policy review records'],
      mandatory: true,
    },
    {
      id: '5.3',
      title: 'Roles, responsibilities and authorities',
      description: 'Designate Food Safety Team Leader and communicate food safety roles.',
      evidenceExamples: ['Food Safety Team Leader appointment', 'Organisation chart', 'Job descriptions with food safety duties'],
      mandatory: true,
    },
    {
      id: '6.1',
      title: 'Actions to address risks and opportunities',
      description: 'Address risks and opportunities at the FSMS level (distinct from hazard analysis).',
      evidenceExamples: ['FSMS risk register', 'Opportunity register', 'Action plans', 'Effectiveness evaluation records'],
      mandatory: true,
    },
    {
      id: '6.2',
      title: 'Objectives of the FSMS and planning',
      description: 'Establish measurable food safety objectives with plans to achieve them.',
      evidenceExamples: ['Food safety objectives register', 'Objective action plans', 'Progress monitoring records'],
      mandatory: true,
    },
    {
      id: '7.1',
      title: 'Resources',
      description: 'Provide infrastructure and work environment for FSMS including food safety appropriate facilities.',
      evidenceExamples: ['Facility maintenance records', 'Infrastructure qualification', 'Environmental monitoring records'],
      mandatory: true,
    },
    {
      id: '7.2',
      title: 'Competence',
      description: 'Ensure FSMS-related competence including food safety training and hygiene.',
      evidenceExamples: ['Food safety training matrix', 'Hygiene training records', 'Allergen training records', 'Competence assessments'],
      mandatory: true,
    },
    {
      id: '7.3',
      title: 'Awareness',
      description: 'Personnel aware of food safety policy, their contribution, and the consequences of non-conformance.',
      evidenceExamples: ['Awareness training records', 'Toolbox talks', 'Food safety posters/signage', 'Induction records'],
      mandatory: true,
    },
    {
      id: '7.4',
      title: 'Communication',
      description: 'Internal and external communication on food safety matters including supply chain communication.',
      evidenceExamples: ['Communication plan', 'Customer communication records', 'Regulatory communication log', 'Supplier communication records'],
      mandatory: true,
    },
    {
      id: '7.5',
      title: 'Documented information',
      description: 'Create, update, and control documented information including HACCP plan and PRPs.',
      evidenceExamples: ['Document register', 'HACCP plan', 'PRP documentation', 'Records retention schedule'],
      mandatory: true,
    },
    {
      id: '8.1',
      title: 'Operational planning and control',
      description: 'Plan, implement, control, maintain, and update processes for food safety product realisation.',
      evidenceExamples: ['Production plan', 'Food safety plan', 'Process control records', 'Specification compliance records'],
      mandatory: true,
    },
    {
      id: '8.2',
      title: 'Prerequisite programmes (PRPs)',
      description: 'Establish, implement, maintain, and update PRPs appropriate to the food chain position.',
      evidenceExamples: ['PRP procedure set', 'Cleaning/sanitation schedule and records', 'Pest control records', 'Supplier approval records', 'Allergen management plan'],
      mandatory: true,
    },
    {
      id: '8.3',
      title: 'Traceability system',
      description: 'One-step-back / one-step-forward traceability for all batches across the food chain.',
      evidenceExamples: ['Traceability procedure', 'Mock recall exercise records', 'Lot traceability records', 'Recall test results'],
      mandatory: true,
    },
    {
      id: '8.4',
      title: 'Emergency preparedness and response',
      description: 'Manage potential emergency situations affecting food safety (contamination events, recall, etc.).',
      evidenceExamples: ['Emergency response plan', 'Recall procedure', 'Crisis management plan', 'Emergency contact list'],
      mandatory: true,
    },
    {
      id: '8.5',
      title: 'Hazard analysis — preliminary steps',
      description: 'Assemble food safety team, describe product characteristics, intended use, flow diagrams, and process steps.',
      evidenceExamples: ['Food safety team record', 'Product descriptions', 'Intended use statements', 'Process flow diagrams', 'Confirmed on-site flow diagrams'],
      mandatory: true,
    },
    {
      id: '8.5.2',
      title: 'Hazard analysis',
      description: 'Identify, evaluate, and select control measures for all food safety hazards (biological, chemical, physical, radiological).',
      evidenceExamples: ['Hazard register', 'Hazard assessment records', 'Control measure selection rationale', 'Allergen hazard assessment'],
      mandatory: true,
    },
    {
      id: '8.5.4',
      title: 'Hazard control plan — HACCP/oPRP',
      description: 'Document HACCP plan with CCPs (critical limits, monitoring, corrective actions) and oPRP plans.',
      evidenceExamples: ['HACCP plan', 'CCP monitoring records', 'Critical limit deviation records', 'oPRP monitoring records'],
      mandatory: true,
    },
    {
      id: '8.6',
      title: 'Updating preliminary information and HACCP/oPRP',
      description: 'Update preliminary information, flow diagrams, hazard analysis, and control measures after changes.',
      evidenceExamples: ['HACCP plan review records', 'Flow diagram update log', 'Change impact assessment records'],
      mandatory: true,
    },
    {
      id: '8.7',
      title: 'Control of monitoring and measuring',
      description: 'Ensure measuring equipment is fit for purpose and calibrated.',
      evidenceExamples: ['Calibration schedule', 'Calibration certificates', 'Out-of-calibration investigation records'],
      mandatory: true,
    },
    {
      id: '8.8',
      title: 'Verification related to PRPs and HACCP plan',
      description: 'Plan and implement verification activities confirming PRPs, HACCP, and oPRPs are effective.',
      evidenceExamples: ['Verification schedule', 'Internal audit records', 'Microbiological testing records', 'Verification activity log'],
      mandatory: true,
    },
    {
      id: '8.9',
      title: 'Control of nonconformities',
      description: 'Handle potentially unsafe product, product withdrawals/recalls, corrections, and corrective actions.',
      evidenceExamples: ['Nonconforming product procedure', 'Product hold/release records', 'Withdrawal/recall records', 'Corrective action log'],
      mandatory: true,
    },
    {
      id: '9.1',
      title: 'Monitoring, measurement, analysis and evaluation',
      description: 'Determine what needs to be monitored, when, and how; analyse and evaluate results.',
      evidenceExamples: ['KPI dashboard', 'Customer complaint analysis', 'Audit findings analysis', 'Supplier performance data'],
      mandatory: true,
    },
    {
      id: '9.2',
      title: 'Internal audit',
      description: 'Planned internal audit programme covering all FSMS clauses and food safety activities.',
      evidenceExamples: ['Audit schedule', 'Audit reports', 'Auditor qualification records', 'Finding closure evidence'],
      mandatory: true,
    },
    {
      id: '9.3',
      title: 'Management review',
      description: 'Management review including food safety performance, objective progress, and update of FSMS.',
      evidenceExamples: ['Management review minutes', 'Food safety KPI summary', 'Regulatory update review', 'Action tracker'],
      mandatory: true,
    },
    {
      id: '10.1',
      title: 'Nonconformity and corrective action',
      description: 'Systematic corrective action process with root cause analysis and effectiveness verification.',
      evidenceExamples: ['Corrective action procedure', 'CAPA log', 'Root cause analysis records', 'Effectiveness verification records'],
      mandatory: true,
    },
    {
      id: '10.2',
      title: 'Continual improvement',
      description: 'Continually improve suitability, adequacy, and effectiveness of the FSMS.',
      evidenceExamples: ['Improvement project register', 'Year-over-year KPI trends', 'Management review improvement items', 'Food safety culture assessment'],
      mandatory: true,
    },
    {
      id: '10.3',
      title: 'Update of the FSMS',
      description: 'Ensure FSMS is continuously updated with information from external communication, regulatory changes, etc.',
      evidenceExamples: ['FSMS update log', 'Regulatory change review records', 'Customer requirement update records', 'Annual FSMS review minutes'],
      mandatory: true,
    },
  ],
};
