// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { StandardAssessment } from './types';

export const iso22301Assessment: StandardAssessment = {
  standardId: 'iso-22301-2019',
  standardName: 'ISO 22301:2019',
  version: '2019',
  clauses: [
    {
      id: '4.1',
      title: 'Understanding the organisation and its context',
      description: 'Determine external and internal issues relevant to purpose and ability to achieve intended outcomes of the BCMS.',
      evidenceExamples: ['Business context analysis', 'PESTLE analysis', 'Strategic risk register'],
      mandatory: true,
    },
    {
      id: '4.2',
      title: 'Understanding needs and expectations of interested parties',
      description: 'Determine relevant interested parties and their requirements relevant to business continuity.',
      evidenceExamples: ['Stakeholder register', 'Customer continuity requirements', 'Regulatory continuity obligations'],
      mandatory: true,
    },
    {
      id: '4.3',
      title: 'Determining scope of the BCMS',
      description: 'Determine boundaries and applicability of the BCMS. Consider external/internal issues and interested party requirements.',
      evidenceExamples: ['BCMS scope document', 'Scope exclusions justification', 'Critical function inventory'],
      mandatory: true,
    },
    {
      id: '4.4',
      title: 'Business continuity management system',
      description: 'Establish, implement, maintain, and continually improve a BCMS including required processes and their interactions.',
      evidenceExamples: ['BCMS policy and framework', 'Process interaction map', 'Management system documentation'],
      mandatory: true,
    },
    {
      id: '5.1',
      title: 'Leadership and commitment',
      description: 'Top management shall demonstrate leadership and commitment to the BCMS by ensuring integration with business direction, providing resources, and communicating importance.',
      evidenceExamples: ['Executive sponsorship records', 'Board approval of BCP policy', 'Leadership communication on BC'],
      mandatory: true,
    },
    {
      id: '5.2',
      title: 'Policy',
      description: 'Top management shall establish a BC policy appropriate to the organisation that includes a commitment to satisfy applicable requirements and continual improvement.',
      evidenceExamples: ['Business continuity policy', 'Policy communication evidence', 'Annual policy review records'],
      mandatory: true,
    },
    {
      id: '5.3',
      title: 'Organisational roles, responsibilities and authorities',
      description: 'Ensure roles, responsibilities, and authorities for relevant functions are assigned, communicated, and understood.',
      evidenceExamples: ['BC team organisation chart', 'Role assignment matrix', 'BC coordinator job description'],
      mandatory: true,
    },
    {
      id: '6.1',
      title: 'Actions to address risks and opportunities',
      description: 'Determine risks and opportunities, plan actions to address them, and integrate these into the BCMS processes.',
      evidenceExamples: ['BC risk register', 'Risk treatment plan', 'Opportunity identification records'],
      mandatory: true,
    },
    {
      id: '6.2',
      title: 'Business continuity objectives and planning',
      description: 'Establish BC objectives at relevant functions and levels, consistent with policy. Plan how to achieve them.',
      evidenceExamples: ['BC objectives document', 'Recovery time objectives (RTO)', 'Recovery point objectives (RPO)'],
      mandatory: true,
    },
    {
      id: '7.1',
      title: 'Resources',
      description: 'Determine and provide resources needed for establishment, implementation, maintenance, and continual improvement of the BCMS.',
      evidenceExamples: ['BC budget allocation', 'Resource inventory for recovery', 'Alternate site provisions'],
      mandatory: true,
    },
    {
      id: '7.2',
      title: 'Competence',
      description: 'Determine required competence for persons doing work under the BCMS. Ensure they are competent based on education, training, or experience.',
      evidenceExamples: ['BC competency framework', 'Training records', 'Competency assessment results'],
      mandatory: true,
    },
    {
      id: '7.3',
      title: 'Awareness',
      description: 'Ensure persons doing work under the BCMS are aware of the BC policy, their contribution, and implications of not conforming.',
      evidenceExamples: ['BC awareness training records', 'Staff communications', 'Awareness assessment results'],
      mandatory: true,
    },
    {
      id: '7.4',
      title: 'Communication',
      description: 'Determine internal and external communications relevant to the BCMS including what, when, with whom, and how to communicate during a disruption.',
      evidenceExamples: ['Crisis communication plan', 'Internal BC communication procedures', 'Stakeholder notification matrix'],
      mandatory: true,
    },
    {
      id: '7.5',
      title: 'Documented information',
      description: 'Include documented information required by the standard and determined as necessary for the effectiveness of the BCMS.',
      evidenceExamples: ['BC documentation inventory', 'Document control procedures', 'Offsite document storage'],
      mandatory: true,
    },
    {
      id: '8.1',
      title: 'Operational planning and control',
      description: 'Plan, implement, control, and maintain processes needed to meet requirements and implement actions determined in planning.',
      evidenceExamples: ['BC operational procedures', 'Process control documentation', 'Supplier BC requirements'],
      mandatory: true,
    },
    {
      id: '8.2',
      title: 'Business impact analysis',
      description: 'Establish and maintain a formal process to identify and prioritise activities, determine impact of disruption, and establish RTOs and RPOs.',
      evidenceExamples: ['Business impact analysis (BIA) report', 'RTO/RPO for critical functions', 'BIA review records'],
      mandatory: true,
    },
    {
      id: '8.3',
      title: 'Risk assessment',
      description: 'Establish and maintain a risk assessment process identifying threats to critical activities and their likelihood and impact.',
      evidenceExamples: ['BC risk assessment', 'Threat/hazard analysis', 'Risk scenario planning records'],
      mandatory: true,
    },
    {
      id: '8.4.1',
      title: 'Business continuity strategy — General',
      description: 'Determine appropriate BC strategies and solutions based on BIA and risk assessment outputs to protect prioritised activities.',
      evidenceExamples: ['BC strategy document', 'Strategy options analysis', 'Solution selection rationale'],
      mandatory: true,
    },
    {
      id: '8.4.2',
      title: 'Resource requirements',
      description: 'Identify resource requirements for BC strategies including people, information, technology, facilities, supplies and finance.',
      evidenceExamples: ['Resource requirements register', 'Minimum operating requirements', 'Critical resource inventory'],
      mandatory: true,
    },
    {
      id: '8.4.3',
      title: 'Protection and mitigation',
      description: 'Identify and implement appropriate preventive and mitigation measures for risks identified in the risk assessment.',
      evidenceExamples: ['Mitigation controls register', 'Preventive measures evidence', 'Infrastructure resilience improvements'],
      mandatory: true,
    },
    {
      id: '8.5',
      title: 'Business continuity plans and procedures',
      description: 'Establish and maintain documented BC plans and procedures sufficient to manage disruptions and meet continuity requirements.',
      evidenceExamples: ['Business continuity plans (BCPs)', 'Incident response procedures', 'Escalation procedures', 'Recovery checklists'],
      mandatory: true,
    },
    {
      id: '8.6',
      title: 'Exercise programme',
      description: 'Establish and maintain an exercise programme that validates BC plans and procedures, reviews organisational capability, and identifies improvements.',
      evidenceExamples: ['Annual exercise programme', 'Tabletop exercise records', 'Full simulation exercise reports', 'Post-exercise improvement actions'],
      mandatory: true,
    },
    {
      id: '8.7',
      title: 'Evaluation of business continuity documentation and capability',
      description: 'Evaluate and update BC documentation and test capabilities regularly, particularly after exercises, incidents, or significant changes.',
      evidenceExamples: ['BCP review log', 'Post-incident lessons learned', 'Documentation update records'],
      mandatory: true,
    },
    {
      id: '9.1',
      title: 'Monitoring, measurement, analysis and evaluation',
      description: 'Evaluate BCMS performance, including what needs to be monitored, methods, timing, and when results shall be analysed.',
      evidenceExamples: ['BC performance metrics', 'KPI dashboard', 'Monitoring and measurement procedures'],
      mandatory: true,
    },
    {
      id: '9.2',
      title: 'Internal audit',
      description: 'Conduct internal audits at planned intervals to provide information on whether the BCMS conforms to requirements and is effectively implemented.',
      evidenceExamples: ['Internal audit programme', 'Audit reports', 'Auditor competency records', 'Corrective action tracking'],
      mandatory: true,
    },
    {
      id: '9.3',
      title: 'Management review',
      description: 'Top management shall review the BCMS at planned intervals to ensure its continuing suitability, adequacy, and effectiveness.',
      evidenceExamples: ['Management review agenda', 'Management review minutes', 'Action log from review'],
      mandatory: true,
    },
    {
      id: '10.1',
      title: 'Nonconformity and corrective action',
      description: 'React to nonconformities, take actions to control and correct them, deal with consequences, and implement corrective actions.',
      evidenceExamples: ['Nonconformity log', 'Root cause analysis records', 'Corrective action completion evidence'],
      mandatory: true,
    },
    {
      id: '10.2',
      title: 'Continual improvement',
      description: 'Continually improve the suitability, adequacy, and effectiveness of the BCMS.',
      evidenceExamples: ['Improvement opportunities register', 'Year-on-year maturity assessment', 'BCMS evolution roadmap'],
      mandatory: true,
    },
  ],
};
