// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { StandardAssessment } from './types';

export const iso50001Assessment: StandardAssessment = {
  standardId: 'iso-50001-2018',
  standardName: 'ISO 50001:2018',
  version: '2018',
  clauses: [
    {
      id: '4.1',
      title: 'Understanding the organisation and its context',
      description: 'Identify internal/external issues that affect energy performance and EnMS establishment.',
      evidenceExamples: ['Energy context analysis', 'SWOT/PESTLE for energy', 'Energy stakeholder register'],
      mandatory: true,
    },
    {
      id: '4.2',
      title: 'Understanding needs and expectations of interested parties',
      description: 'Identify interested parties and their energy-related requirements.',
      evidenceExamples: ['Interested party register', 'Regulatory requirement log', 'Customer energy requirements'],
      mandatory: true,
    },
    {
      id: '4.3',
      title: 'Scope and boundaries of the EnMS',
      description: 'Define EnMS scope including activities, facilities, systems, processes, and decisions within boundaries.',
      evidenceExamples: ['EnMS scope statement', 'Site boundary diagram', 'Metering boundary document'],
      mandatory: true,
    },
    {
      id: '4.4',
      title: 'EnMS — general',
      description: 'Establish, implement, maintain, and improve EnMS including processes for continual energy performance improvement.',
      evidenceExamples: ['EnMS procedure set', 'Process interaction diagram', 'EnMS implementation plan'],
      mandatory: true,
    },
    {
      id: '5.1',
      title: 'Leadership and commitment',
      description: 'Top management demonstrate commitment to energy performance improvement and EnMS.',
      evidenceExamples: ['Signed energy policy', 'Management review records', 'Energy budget allocation', 'CEO energy statement'],
      mandatory: true,
    },
    {
      id: '5.2',
      title: 'Energy policy',
      description: 'Documented energy policy committing to improved energy performance, compliance, and information availability.',
      evidenceExamples: ['Current signed energy policy', 'Policy communication evidence', 'Policy review records'],
      mandatory: true,
    },
    {
      id: '5.3',
      title: 'Roles, responsibilities and authorities',
      description: 'Assign management representative (Energy Management Team lead) and communicate roles.',
      evidenceExamples: ['Energy Management Representative appointment', 'Energy team terms of reference', 'RACI matrix'],
      mandatory: true,
    },
    {
      id: '6.1',
      title: 'Actions to address risks and opportunities',
      description: 'Identify energy-related risks/opportunities; plan actions and evaluate effectiveness.',
      evidenceExamples: ['Energy risk register', 'Opportunity assessment records', 'Action plans', 'Effectiveness evaluation'],
      mandatory: true,
    },
    {
      id: '6.2',
      title: 'Energy review',
      description: 'Systematic energy review identifying energy sources, uses, consumption, SEUs, and improvement opportunities.',
      evidenceExamples: ['Energy review report', 'Energy consumption data', 'SEU identification records', 'Energy analysis (12 months min)'],
      mandatory: true,
    },
    {
      id: '6.3',
      title: 'Energy performance indicators (EnPIs)',
      description: 'Establish EnPIs appropriate to monitoring and measuring energy performance improvement.',
      evidenceExamples: ['EnPI register', 'EnPI calculation methodology', 'Baseline documentation', 'Normalisation factors'],
      mandatory: true,
    },
    {
      id: '6.4',
      title: 'Energy baselines (EnBs)',
      description: 'Establish quantitative energy baselines using data from energy review over defined reference period.',
      evidenceExamples: ['Energy baseline report', 'Baseline data (12 months+)', 'Baseline normalisation model', 'Baseline adjustment records'],
      mandatory: true,
    },
    {
      id: '6.5',
      title: 'Planning for energy data collection',
      description: 'Identify energy data to be collected, measurement methods, calibration, and collection frequency.',
      evidenceExamples: ['Metering plan', 'Data collection plan', 'Meter calibration records', 'Meter register'],
      mandatory: true,
    },
    {
      id: '6.6',
      title: 'Significant energy uses (SEUs)',
      description: 'Identify SEUs, determine current energy performance, identify relevant variables, and associated personnel.',
      evidenceExamples: ['SEU register', 'SEU performance data', 'Relevant variable analysis', 'Static factor documentation'],
      mandatory: true,
    },
    {
      id: '6.7',
      title: 'Energy objectives and energy targets',
      description: 'Establish documented energy objectives and energy targets aligned with policy and improvement potential.',
      evidenceExamples: ['Energy objectives register', 'Energy targets with deadlines', 'Action plans for each target', 'Progress monitoring records'],
      mandatory: true,
    },
    {
      id: '7.1',
      title: 'Resources',
      description: 'Provide resources (financial, human, technical) needed to establish, implement, and improve EnMS.',
      evidenceExamples: ['Energy budget', 'Energy team resource allocation', 'Tool/metering equipment inventory'],
      mandatory: true,
    },
    {
      id: '7.2',
      title: 'Competence',
      description: 'Ensure personnel affecting energy performance are competent through education, training, or experience.',
      evidenceExamples: ['Energy training matrix', 'Training records', 'Competence assessments', 'Energy auditor qualifications'],
      mandatory: true,
    },
    {
      id: '7.3',
      title: 'Awareness',
      description: 'Personnel aware of energy policy, their contribution to energy performance, and benefits of improved performance.',
      evidenceExamples: ['Energy awareness training records', 'Energy communication campaigns', 'Toolbox talks', 'Display boards'],
      mandatory: true,
    },
    {
      id: '7.4',
      title: 'Communication',
      description: 'Internal and external communication on EnMS and energy performance including what, when, and to whom.',
      evidenceExamples: ['Communication plan', 'Energy performance reports', 'Website/ESG disclosures', 'Board reports'],
      mandatory: true,
    },
    {
      id: '7.5',
      title: 'Documented information',
      description: 'Create, update, and control documented information required by ISO 50001:2018.',
      evidenceExamples: ['Document register', 'Records retention schedule', 'Document control procedure', 'EnMS documentation hierarchy'],
      mandatory: true,
    },
    {
      id: '8.1',
      title: 'Operational planning and control',
      description: 'Plan, implement, control, and maintain operations to meet energy performance criteria for SEUs.',
      evidenceExamples: ['Operating procedures for SEUs', 'Operational criteria for SEUs', 'Maintenance records for SEUs'],
      mandatory: true,
    },
    {
      id: '8.2',
      title: 'Design',
      description: 'Consider energy performance improvement opportunities in design of new/renovated facilities and equipment.',
      evidenceExamples: ['Design energy review checklist', 'Equipment energy specification', 'Building energy model', 'Energy design review records'],
      mandatory: true,
    },
    {
      id: '8.3',
      title: 'Procurement',
      description: 'Procurement criteria for energy performance and lifecycle cost of energy-significant products and services.',
      evidenceExamples: ['Procurement energy criteria', 'Supplier energy questionnaire', 'Equipment energy datasheet evaluation'],
      mandatory: true,
    },
    {
      id: '9.1',
      title: 'Monitoring, measurement, analysis and evaluation',
      description: 'Monitor, measure, analyse, and evaluate energy performance and EnMS effectiveness.',
      evidenceExamples: ['Energy monitoring plan', 'Monthly energy reports', 'EnPI trend charts', 'Deviation investigation records'],
      mandatory: true,
    },
    {
      id: '9.1.1',
      title: 'Energy performance — monitoring and measurement',
      description: 'Conduct regular energy performance measurement against baselines and EnPIs with investigation of significant deviations.',
      evidenceExamples: ['Energy dashboard', 'Monthly metered data', 'Deviation threshold definition', 'Investigation reports'],
      mandatory: true,
    },
    {
      id: '9.2',
      title: 'Internal audit',
      description: 'Planned internal audit programme to verify EnMS conformance and energy performance improvement.',
      evidenceExamples: ['Audit schedule', 'Audit reports', 'Auditor qualification records', 'Finding closure evidence'],
      mandatory: true,
    },
    {
      id: '9.3',
      title: 'Management review',
      description: 'Periodic management review including energy performance data, objective progress, and improvement opportunities.',
      evidenceExamples: ['Management review agenda/minutes', 'Energy performance trend data', 'Objective completion status', 'Action tracker'],
      mandatory: true,
    },
    {
      id: '10.1',
      title: 'Nonconformity and corrective action',
      description: 'React to nonconformities, conduct root cause analysis, and take corrective action.',
      evidenceExamples: ['Corrective action register', 'Root cause analysis records', 'Effectiveness verification', 'EnMS update records'],
      mandatory: true,
    },
    {
      id: '10.2',
      title: 'Continual improvement',
      description: 'Continually improve energy performance and suitability/adequacy/effectiveness of EnMS.',
      evidenceExamples: ['Annual energy performance improvement report', 'Year-over-year EnPI trends', 'Improvement project register'],
      mandatory: true,
    },
  ],
};
