// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import { match, when, isString, isNumber, isBoolean, isNull, isUndefined, isArray, isObject, matchType, glob, wildcardMatch, deepMatch, extractGroups } from "../index";

describe('match exact values', () => {
  it('match exact 0', () => { expect(match(0).with(0, () => 0).run()).toBe(0); });
  it('match exact 1', () => { expect(match(1).with(1, () => 1).run()).toBe(1); });
  it('match exact 2', () => { expect(match(2).with(2, () => 2).run()).toBe(2); });
  it('match exact 3', () => { expect(match(3).with(3, () => 3).run()).toBe(3); });
  it('match exact 4', () => { expect(match(4).with(4, () => 4).run()).toBe(4); });
  it('match exact 5', () => { expect(match(5).with(5, () => 5).run()).toBe(5); });
  it('match exact 6', () => { expect(match(6).with(6, () => 6).run()).toBe(6); });
  it('match exact 7', () => { expect(match(7).with(7, () => 7).run()).toBe(7); });
  it('match exact 8', () => { expect(match(8).with(8, () => 8).run()).toBe(8); });
  it('match exact 9', () => { expect(match(9).with(9, () => 9).run()).toBe(9); });
  it('match exact 10', () => { expect(match(10).with(10, () => 10).run()).toBe(10); });
  it('match exact 11', () => { expect(match(11).with(11, () => 11).run()).toBe(11); });
  it('match exact 12', () => { expect(match(12).with(12, () => 12).run()).toBe(12); });
  it('match exact 13', () => { expect(match(13).with(13, () => 13).run()).toBe(13); });
  it('match exact 14', () => { expect(match(14).with(14, () => 14).run()).toBe(14); });
  it('match exact 15', () => { expect(match(15).with(15, () => 15).run()).toBe(15); });
  it('match exact 16', () => { expect(match(16).with(16, () => 16).run()).toBe(16); });
  it('match exact 17', () => { expect(match(17).with(17, () => 17).run()).toBe(17); });
  it('match exact 18', () => { expect(match(18).with(18, () => 18).run()).toBe(18); });
  it('match exact 19', () => { expect(match(19).with(19, () => 19).run()).toBe(19); });
  it('match exact 20', () => { expect(match(20).with(20, () => 20).run()).toBe(20); });
  it('match exact 21', () => { expect(match(21).with(21, () => 21).run()).toBe(21); });
  it('match exact 22', () => { expect(match(22).with(22, () => 22).run()).toBe(22); });
  it('match exact 23', () => { expect(match(23).with(23, () => 23).run()).toBe(23); });
  it('match exact 24', () => { expect(match(24).with(24, () => 24).run()).toBe(24); });
  it('match exact 25', () => { expect(match(25).with(25, () => 25).run()).toBe(25); });
  it('match exact 26', () => { expect(match(26).with(26, () => 26).run()).toBe(26); });
  it('match exact 27', () => { expect(match(27).with(27, () => 27).run()).toBe(27); });
  it('match exact 28', () => { expect(match(28).with(28, () => 28).run()).toBe(28); });
  it('match exact 29', () => { expect(match(29).with(29, () => 29).run()).toBe(29); });
  it('match exact 30', () => { expect(match(30).with(30, () => 30).run()).toBe(30); });
  it('match exact 31', () => { expect(match(31).with(31, () => 31).run()).toBe(31); });
  it('match exact 32', () => { expect(match(32).with(32, () => 32).run()).toBe(32); });
  it('match exact 33', () => { expect(match(33).with(33, () => 33).run()).toBe(33); });
  it('match exact 34', () => { expect(match(34).with(34, () => 34).run()).toBe(34); });
  it('match exact 35', () => { expect(match(35).with(35, () => 35).run()).toBe(35); });
  it('match exact 36', () => { expect(match(36).with(36, () => 36).run()).toBe(36); });
  it('match exact 37', () => { expect(match(37).with(37, () => 37).run()).toBe(37); });
  it('match exact 38', () => { expect(match(38).with(38, () => 38).run()).toBe(38); });
  it('match exact 39', () => { expect(match(39).with(39, () => 39).run()).toBe(39); });
  it('match exact 40', () => { expect(match(40).with(40, () => 40).run()).toBe(40); });
  it('match exact 41', () => { expect(match(41).with(41, () => 41).run()).toBe(41); });
  it('match exact 42', () => { expect(match(42).with(42, () => 42).run()).toBe(42); });
  it('match exact 43', () => { expect(match(43).with(43, () => 43).run()).toBe(43); });
  it('match exact 44', () => { expect(match(44).with(44, () => 44).run()).toBe(44); });
  it('match exact 45', () => { expect(match(45).with(45, () => 45).run()).toBe(45); });
  it('match exact 46', () => { expect(match(46).with(46, () => 46).run()).toBe(46); });
  it('match exact 47', () => { expect(match(47).with(47, () => 47).run()).toBe(47); });
  it('match exact 48', () => { expect(match(48).with(48, () => 48).run()).toBe(48); });
  it('match exact 49', () => { expect(match(49).with(49, () => 49).run()).toBe(49); });
  it('match exact 50', () => { expect(match(50).with(50, () => 50).run()).toBe(50); });
  it('match exact 51', () => { expect(match(51).with(51, () => 51).run()).toBe(51); });
  it('match exact 52', () => { expect(match(52).with(52, () => 52).run()).toBe(52); });
  it('match exact 53', () => { expect(match(53).with(53, () => 53).run()).toBe(53); });
  it('match exact 54', () => { expect(match(54).with(54, () => 54).run()).toBe(54); });
  it('match exact 55', () => { expect(match(55).with(55, () => 55).run()).toBe(55); });
  it('match exact 56', () => { expect(match(56).with(56, () => 56).run()).toBe(56); });
  it('match exact 57', () => { expect(match(57).with(57, () => 57).run()).toBe(57); });
  it('match exact 58', () => { expect(match(58).with(58, () => 58).run()).toBe(58); });
  it('match exact 59', () => { expect(match(59).with(59, () => 59).run()).toBe(59); });
  it('match exact 60', () => { expect(match(60).with(60, () => 60).run()).toBe(60); });
  it('match exact 61', () => { expect(match(61).with(61, () => 61).run()).toBe(61); });
  it('match exact 62', () => { expect(match(62).with(62, () => 62).run()).toBe(62); });
  it('match exact 63', () => { expect(match(63).with(63, () => 63).run()).toBe(63); });
  it('match exact 64', () => { expect(match(64).with(64, () => 64).run()).toBe(64); });
  it('match exact 65', () => { expect(match(65).with(65, () => 65).run()).toBe(65); });
  it('match exact 66', () => { expect(match(66).with(66, () => 66).run()).toBe(66); });
  it('match exact 67', () => { expect(match(67).with(67, () => 67).run()).toBe(67); });
  it('match exact 68', () => { expect(match(68).with(68, () => 68).run()).toBe(68); });
  it('match exact 69', () => { expect(match(69).with(69, () => 69).run()).toBe(69); });
  it('match exact 70', () => { expect(match(70).with(70, () => 70).run()).toBe(70); });
  it('match exact 71', () => { expect(match(71).with(71, () => 71).run()).toBe(71); });
  it('match exact 72', () => { expect(match(72).with(72, () => 72).run()).toBe(72); });
  it('match exact 73', () => { expect(match(73).with(73, () => 73).run()).toBe(73); });
  it('match exact 74', () => { expect(match(74).with(74, () => 74).run()).toBe(74); });
  it('match exact 75', () => { expect(match(75).with(75, () => 75).run()).toBe(75); });
  it('match exact 76', () => { expect(match(76).with(76, () => 76).run()).toBe(76); });
  it('match exact 77', () => { expect(match(77).with(77, () => 77).run()).toBe(77); });
  it('match exact 78', () => { expect(match(78).with(78, () => 78).run()).toBe(78); });
  it('match exact 79', () => { expect(match(79).with(79, () => 79).run()).toBe(79); });
  it('match exact 80', () => { expect(match(80).with(80, () => 80).run()).toBe(80); });
  it('match exact 81', () => { expect(match(81).with(81, () => 81).run()).toBe(81); });
  it('match exact 82', () => { expect(match(82).with(82, () => 82).run()).toBe(82); });
  it('match exact 83', () => { expect(match(83).with(83, () => 83).run()).toBe(83); });
  it('match exact 84', () => { expect(match(84).with(84, () => 84).run()).toBe(84); });
  it('match exact 85', () => { expect(match(85).with(85, () => 85).run()).toBe(85); });
  it('match exact 86', () => { expect(match(86).with(86, () => 86).run()).toBe(86); });
  it('match exact 87', () => { expect(match(87).with(87, () => 87).run()).toBe(87); });
  it('match exact 88', () => { expect(match(88).with(88, () => 88).run()).toBe(88); });
  it('match exact 89', () => { expect(match(89).with(89, () => 89).run()).toBe(89); });
  it('match exact 90', () => { expect(match(90).with(90, () => 90).run()).toBe(90); });
  it('match exact 91', () => { expect(match(91).with(91, () => 91).run()).toBe(91); });
  it('match exact 92', () => { expect(match(92).with(92, () => 92).run()).toBe(92); });
  it('match exact 93', () => { expect(match(93).with(93, () => 93).run()).toBe(93); });
  it('match exact 94', () => { expect(match(94).with(94, () => 94).run()).toBe(94); });
  it('match exact 95', () => { expect(match(95).with(95, () => 95).run()).toBe(95); });
  it('match exact 96', () => { expect(match(96).with(96, () => 96).run()).toBe(96); });
  it('match exact 97', () => { expect(match(97).with(97, () => 97).run()).toBe(97); });
  it('match exact 98', () => { expect(match(98).with(98, () => 98).run()).toBe(98); });
  it('match exact 99', () => { expect(match(99).with(99, () => 99).run()).toBe(99); });
});

describe('match with when', () => {
  it('when predicate 0', () => { expect(match(0).with(when((v) => v === 0), () => 'yes').run()).toBe('yes'); });
  it('when predicate 1', () => { expect(match(1).with(when((v) => v === 1), () => 'yes').run()).toBe('yes'); });
  it('when predicate 2', () => { expect(match(2).with(when((v) => v === 2), () => 'yes').run()).toBe('yes'); });
  it('when predicate 3', () => { expect(match(3).with(when((v) => v === 3), () => 'yes').run()).toBe('yes'); });
  it('when predicate 4', () => { expect(match(4).with(when((v) => v === 4), () => 'yes').run()).toBe('yes'); });
  it('when predicate 5', () => { expect(match(5).with(when((v) => v === 5), () => 'yes').run()).toBe('yes'); });
  it('when predicate 6', () => { expect(match(6).with(when((v) => v === 6), () => 'yes').run()).toBe('yes'); });
  it('when predicate 7', () => { expect(match(7).with(when((v) => v === 7), () => 'yes').run()).toBe('yes'); });
  it('when predicate 8', () => { expect(match(8).with(when((v) => v === 8), () => 'yes').run()).toBe('yes'); });
  it('when predicate 9', () => { expect(match(9).with(when((v) => v === 9), () => 'yes').run()).toBe('yes'); });
  it('when predicate 10', () => { expect(match(10).with(when((v) => v === 10), () => 'yes').run()).toBe('yes'); });
  it('when predicate 11', () => { expect(match(11).with(when((v) => v === 11), () => 'yes').run()).toBe('yes'); });
  it('when predicate 12', () => { expect(match(12).with(when((v) => v === 12), () => 'yes').run()).toBe('yes'); });
  it('when predicate 13', () => { expect(match(13).with(when((v) => v === 13), () => 'yes').run()).toBe('yes'); });
  it('when predicate 14', () => { expect(match(14).with(when((v) => v === 14), () => 'yes').run()).toBe('yes'); });
  it('when predicate 15', () => { expect(match(15).with(when((v) => v === 15), () => 'yes').run()).toBe('yes'); });
  it('when predicate 16', () => { expect(match(16).with(when((v) => v === 16), () => 'yes').run()).toBe('yes'); });
  it('when predicate 17', () => { expect(match(17).with(when((v) => v === 17), () => 'yes').run()).toBe('yes'); });
  it('when predicate 18', () => { expect(match(18).with(when((v) => v === 18), () => 'yes').run()).toBe('yes'); });
  it('when predicate 19', () => { expect(match(19).with(when((v) => v === 19), () => 'yes').run()).toBe('yes'); });
  it('when predicate 20', () => { expect(match(20).with(when((v) => v === 20), () => 'yes').run()).toBe('yes'); });
  it('when predicate 21', () => { expect(match(21).with(when((v) => v === 21), () => 'yes').run()).toBe('yes'); });
  it('when predicate 22', () => { expect(match(22).with(when((v) => v === 22), () => 'yes').run()).toBe('yes'); });
  it('when predicate 23', () => { expect(match(23).with(when((v) => v === 23), () => 'yes').run()).toBe('yes'); });
  it('when predicate 24', () => { expect(match(24).with(when((v) => v === 24), () => 'yes').run()).toBe('yes'); });
  it('when predicate 25', () => { expect(match(25).with(when((v) => v === 25), () => 'yes').run()).toBe('yes'); });
  it('when predicate 26', () => { expect(match(26).with(when((v) => v === 26), () => 'yes').run()).toBe('yes'); });
  it('when predicate 27', () => { expect(match(27).with(when((v) => v === 27), () => 'yes').run()).toBe('yes'); });
  it('when predicate 28', () => { expect(match(28).with(when((v) => v === 28), () => 'yes').run()).toBe('yes'); });
  it('when predicate 29', () => { expect(match(29).with(when((v) => v === 29), () => 'yes').run()).toBe('yes'); });
  it('when predicate 30', () => { expect(match(30).with(when((v) => v === 30), () => 'yes').run()).toBe('yes'); });
  it('when predicate 31', () => { expect(match(31).with(when((v) => v === 31), () => 'yes').run()).toBe('yes'); });
  it('when predicate 32', () => { expect(match(32).with(when((v) => v === 32), () => 'yes').run()).toBe('yes'); });
  it('when predicate 33', () => { expect(match(33).with(when((v) => v === 33), () => 'yes').run()).toBe('yes'); });
  it('when predicate 34', () => { expect(match(34).with(when((v) => v === 34), () => 'yes').run()).toBe('yes'); });
  it('when predicate 35', () => { expect(match(35).with(when((v) => v === 35), () => 'yes').run()).toBe('yes'); });
  it('when predicate 36', () => { expect(match(36).with(when((v) => v === 36), () => 'yes').run()).toBe('yes'); });
  it('when predicate 37', () => { expect(match(37).with(when((v) => v === 37), () => 'yes').run()).toBe('yes'); });
  it('when predicate 38', () => { expect(match(38).with(when((v) => v === 38), () => 'yes').run()).toBe('yes'); });
  it('when predicate 39', () => { expect(match(39).with(when((v) => v === 39), () => 'yes').run()).toBe('yes'); });
  it('when predicate 40', () => { expect(match(40).with(when((v) => v === 40), () => 'yes').run()).toBe('yes'); });
  it('when predicate 41', () => { expect(match(41).with(when((v) => v === 41), () => 'yes').run()).toBe('yes'); });
  it('when predicate 42', () => { expect(match(42).with(when((v) => v === 42), () => 'yes').run()).toBe('yes'); });
  it('when predicate 43', () => { expect(match(43).with(when((v) => v === 43), () => 'yes').run()).toBe('yes'); });
  it('when predicate 44', () => { expect(match(44).with(when((v) => v === 44), () => 'yes').run()).toBe('yes'); });
  it('when predicate 45', () => { expect(match(45).with(when((v) => v === 45), () => 'yes').run()).toBe('yes'); });
  it('when predicate 46', () => { expect(match(46).with(when((v) => v === 46), () => 'yes').run()).toBe('yes'); });
  it('when predicate 47', () => { expect(match(47).with(when((v) => v === 47), () => 'yes').run()).toBe('yes'); });
  it('when predicate 48', () => { expect(match(48).with(when((v) => v === 48), () => 'yes').run()).toBe('yes'); });
  it('when predicate 49', () => { expect(match(49).with(when((v) => v === 49), () => 'yes').run()).toBe('yes'); });
  it('when predicate 50', () => { expect(match(50).with(when((v) => v === 50), () => 'yes').run()).toBe('yes'); });
  it('when predicate 51', () => { expect(match(51).with(when((v) => v === 51), () => 'yes').run()).toBe('yes'); });
  it('when predicate 52', () => { expect(match(52).with(when((v) => v === 52), () => 'yes').run()).toBe('yes'); });
  it('when predicate 53', () => { expect(match(53).with(when((v) => v === 53), () => 'yes').run()).toBe('yes'); });
  it('when predicate 54', () => { expect(match(54).with(when((v) => v === 54), () => 'yes').run()).toBe('yes'); });
  it('when predicate 55', () => { expect(match(55).with(when((v) => v === 55), () => 'yes').run()).toBe('yes'); });
  it('when predicate 56', () => { expect(match(56).with(when((v) => v === 56), () => 'yes').run()).toBe('yes'); });
  it('when predicate 57', () => { expect(match(57).with(when((v) => v === 57), () => 'yes').run()).toBe('yes'); });
  it('when predicate 58', () => { expect(match(58).with(when((v) => v === 58), () => 'yes').run()).toBe('yes'); });
  it('when predicate 59', () => { expect(match(59).with(when((v) => v === 59), () => 'yes').run()).toBe('yes'); });
  it('when predicate 60', () => { expect(match(60).with(when((v) => v === 60), () => 'yes').run()).toBe('yes'); });
  it('when predicate 61', () => { expect(match(61).with(when((v) => v === 61), () => 'yes').run()).toBe('yes'); });
  it('when predicate 62', () => { expect(match(62).with(when((v) => v === 62), () => 'yes').run()).toBe('yes'); });
  it('when predicate 63', () => { expect(match(63).with(when((v) => v === 63), () => 'yes').run()).toBe('yes'); });
  it('when predicate 64', () => { expect(match(64).with(when((v) => v === 64), () => 'yes').run()).toBe('yes'); });
  it('when predicate 65', () => { expect(match(65).with(when((v) => v === 65), () => 'yes').run()).toBe('yes'); });
  it('when predicate 66', () => { expect(match(66).with(when((v) => v === 66), () => 'yes').run()).toBe('yes'); });
  it('when predicate 67', () => { expect(match(67).with(when((v) => v === 67), () => 'yes').run()).toBe('yes'); });
  it('when predicate 68', () => { expect(match(68).with(when((v) => v === 68), () => 'yes').run()).toBe('yes'); });
  it('when predicate 69', () => { expect(match(69).with(when((v) => v === 69), () => 'yes').run()).toBe('yes'); });
  it('when predicate 70', () => { expect(match(70).with(when((v) => v === 70), () => 'yes').run()).toBe('yes'); });
  it('when predicate 71', () => { expect(match(71).with(when((v) => v === 71), () => 'yes').run()).toBe('yes'); });
  it('when predicate 72', () => { expect(match(72).with(when((v) => v === 72), () => 'yes').run()).toBe('yes'); });
  it('when predicate 73', () => { expect(match(73).with(when((v) => v === 73), () => 'yes').run()).toBe('yes'); });
  it('when predicate 74', () => { expect(match(74).with(when((v) => v === 74), () => 'yes').run()).toBe('yes'); });
  it('when predicate 75', () => { expect(match(75).with(when((v) => v === 75), () => 'yes').run()).toBe('yes'); });
  it('when predicate 76', () => { expect(match(76).with(when((v) => v === 76), () => 'yes').run()).toBe('yes'); });
  it('when predicate 77', () => { expect(match(77).with(when((v) => v === 77), () => 'yes').run()).toBe('yes'); });
  it('when predicate 78', () => { expect(match(78).with(when((v) => v === 78), () => 'yes').run()).toBe('yes'); });
  it('when predicate 79', () => { expect(match(79).with(when((v) => v === 79), () => 'yes').run()).toBe('yes'); });
  it('when predicate 80', () => { expect(match(80).with(when((v) => v === 80), () => 'yes').run()).toBe('yes'); });
  it('when predicate 81', () => { expect(match(81).with(when((v) => v === 81), () => 'yes').run()).toBe('yes'); });
  it('when predicate 82', () => { expect(match(82).with(when((v) => v === 82), () => 'yes').run()).toBe('yes'); });
  it('when predicate 83', () => { expect(match(83).with(when((v) => v === 83), () => 'yes').run()).toBe('yes'); });
  it('when predicate 84', () => { expect(match(84).with(when((v) => v === 84), () => 'yes').run()).toBe('yes'); });
  it('when predicate 85', () => { expect(match(85).with(when((v) => v === 85), () => 'yes').run()).toBe('yes'); });
  it('when predicate 86', () => { expect(match(86).with(when((v) => v === 86), () => 'yes').run()).toBe('yes'); });
  it('when predicate 87', () => { expect(match(87).with(when((v) => v === 87), () => 'yes').run()).toBe('yes'); });
  it('when predicate 88', () => { expect(match(88).with(when((v) => v === 88), () => 'yes').run()).toBe('yes'); });
  it('when predicate 89', () => { expect(match(89).with(when((v) => v === 89), () => 'yes').run()).toBe('yes'); });
  it('when predicate 90', () => { expect(match(90).with(when((v) => v === 90), () => 'yes').run()).toBe('yes'); });
  it('when predicate 91', () => { expect(match(91).with(when((v) => v === 91), () => 'yes').run()).toBe('yes'); });
  it('when predicate 92', () => { expect(match(92).with(when((v) => v === 92), () => 'yes').run()).toBe('yes'); });
  it('when predicate 93', () => { expect(match(93).with(when((v) => v === 93), () => 'yes').run()).toBe('yes'); });
  it('when predicate 94', () => { expect(match(94).with(when((v) => v === 94), () => 'yes').run()).toBe('yes'); });
  it('when predicate 95', () => { expect(match(95).with(when((v) => v === 95), () => 'yes').run()).toBe('yes'); });
  it('when predicate 96', () => { expect(match(96).with(when((v) => v === 96), () => 'yes').run()).toBe('yes'); });
  it('when predicate 97', () => { expect(match(97).with(when((v) => v === 97), () => 'yes').run()).toBe('yes'); });
  it('when predicate 98', () => { expect(match(98).with(when((v) => v === 98), () => 'yes').run()).toBe('yes'); });
  it('when predicate 99', () => { expect(match(99).with(when((v) => v === 99), () => 'yes').run()).toBe('yes'); });
});

describe('match otherwise', () => {
  it('otherwise 0', () => { expect(match(0).with(1000, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 1', () => { expect(match(1).with(1001, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 2', () => { expect(match(2).with(1002, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 3', () => { expect(match(3).with(1003, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 4', () => { expect(match(4).with(1004, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 5', () => { expect(match(5).with(1005, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 6', () => { expect(match(6).with(1006, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 7', () => { expect(match(7).with(1007, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 8', () => { expect(match(8).with(1008, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 9', () => { expect(match(9).with(1009, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 10', () => { expect(match(10).with(1010, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 11', () => { expect(match(11).with(1011, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 12', () => { expect(match(12).with(1012, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 13', () => { expect(match(13).with(1013, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 14', () => { expect(match(14).with(1014, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 15', () => { expect(match(15).with(1015, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 16', () => { expect(match(16).with(1016, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 17', () => { expect(match(17).with(1017, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 18', () => { expect(match(18).with(1018, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 19', () => { expect(match(19).with(1019, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 20', () => { expect(match(20).with(1020, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 21', () => { expect(match(21).with(1021, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 22', () => { expect(match(22).with(1022, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 23', () => { expect(match(23).with(1023, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 24', () => { expect(match(24).with(1024, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 25', () => { expect(match(25).with(1025, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 26', () => { expect(match(26).with(1026, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 27', () => { expect(match(27).with(1027, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 28', () => { expect(match(28).with(1028, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 29', () => { expect(match(29).with(1029, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 30', () => { expect(match(30).with(1030, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 31', () => { expect(match(31).with(1031, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 32', () => { expect(match(32).with(1032, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 33', () => { expect(match(33).with(1033, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 34', () => { expect(match(34).with(1034, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 35', () => { expect(match(35).with(1035, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 36', () => { expect(match(36).with(1036, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 37', () => { expect(match(37).with(1037, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 38', () => { expect(match(38).with(1038, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 39', () => { expect(match(39).with(1039, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 40', () => { expect(match(40).with(1040, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 41', () => { expect(match(41).with(1041, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 42', () => { expect(match(42).with(1042, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 43', () => { expect(match(43).with(1043, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 44', () => { expect(match(44).with(1044, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 45', () => { expect(match(45).with(1045, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 46', () => { expect(match(46).with(1046, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 47', () => { expect(match(47).with(1047, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 48', () => { expect(match(48).with(1048, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 49', () => { expect(match(49).with(1049, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 50', () => { expect(match(50).with(1050, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 51', () => { expect(match(51).with(1051, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 52', () => { expect(match(52).with(1052, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 53', () => { expect(match(53).with(1053, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 54', () => { expect(match(54).with(1054, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 55', () => { expect(match(55).with(1055, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 56', () => { expect(match(56).with(1056, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 57', () => { expect(match(57).with(1057, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 58', () => { expect(match(58).with(1058, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 59', () => { expect(match(59).with(1059, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 60', () => { expect(match(60).with(1060, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 61', () => { expect(match(61).with(1061, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 62', () => { expect(match(62).with(1062, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 63', () => { expect(match(63).with(1063, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 64', () => { expect(match(64).with(1064, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 65', () => { expect(match(65).with(1065, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 66', () => { expect(match(66).with(1066, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 67', () => { expect(match(67).with(1067, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 68', () => { expect(match(68).with(1068, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 69', () => { expect(match(69).with(1069, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 70', () => { expect(match(70).with(1070, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 71', () => { expect(match(71).with(1071, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 72', () => { expect(match(72).with(1072, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 73', () => { expect(match(73).with(1073, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 74', () => { expect(match(74).with(1074, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 75', () => { expect(match(75).with(1075, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 76', () => { expect(match(76).with(1076, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 77', () => { expect(match(77).with(1077, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 78', () => { expect(match(78).with(1078, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 79', () => { expect(match(79).with(1079, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 80', () => { expect(match(80).with(1080, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 81', () => { expect(match(81).with(1081, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 82', () => { expect(match(82).with(1082, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 83', () => { expect(match(83).with(1083, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 84', () => { expect(match(84).with(1084, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 85', () => { expect(match(85).with(1085, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 86', () => { expect(match(86).with(1086, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 87', () => { expect(match(87).with(1087, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 88', () => { expect(match(88).with(1088, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 89', () => { expect(match(89).with(1089, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 90', () => { expect(match(90).with(1090, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 91', () => { expect(match(91).with(1091, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 92', () => { expect(match(92).with(1092, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 93', () => { expect(match(93).with(1093, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 94', () => { expect(match(94).with(1094, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 95', () => { expect(match(95).with(1095, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 96', () => { expect(match(96).with(1096, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 97', () => { expect(match(97).with(1097, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 98', () => { expect(match(98).with(1098, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
  it('otherwise 99', () => { expect(match(99).with(1099, () => 'wrong').otherwise(() => 'default').run()).toBe('default'); });
});

describe('type guards', () => {
  it('isString str0', () => expect(isString('hello0')).toBe(true));
  it('isNumber num0', () => expect(isNumber(0)).toBe(true));
  it('isBoolean bool0', () => expect(isBoolean(true)).toBe(true));
  it('isString str1', () => expect(isString('hello1')).toBe(true));
  it('isNumber num1', () => expect(isNumber(1)).toBe(true));
  it('isBoolean bool1', () => expect(isBoolean(false)).toBe(true));
  it('isString str2', () => expect(isString('hello2')).toBe(true));
  it('isNumber num2', () => expect(isNumber(2)).toBe(true));
  it('isBoolean bool2', () => expect(isBoolean(true)).toBe(true));
  it('isString str3', () => expect(isString('hello3')).toBe(true));
  it('isNumber num3', () => expect(isNumber(3)).toBe(true));
  it('isBoolean bool3', () => expect(isBoolean(false)).toBe(true));
  it('isString str4', () => expect(isString('hello4')).toBe(true));
  it('isNumber num4', () => expect(isNumber(4)).toBe(true));
  it('isBoolean bool4', () => expect(isBoolean(true)).toBe(true));
  it('isString str5', () => expect(isString('hello5')).toBe(true));
  it('isNumber num5', () => expect(isNumber(5)).toBe(true));
  it('isBoolean bool5', () => expect(isBoolean(false)).toBe(true));
  it('isString str6', () => expect(isString('hello6')).toBe(true));
  it('isNumber num6', () => expect(isNumber(6)).toBe(true));
  it('isBoolean bool6', () => expect(isBoolean(true)).toBe(true));
  it('isString str7', () => expect(isString('hello7')).toBe(true));
  it('isNumber num7', () => expect(isNumber(7)).toBe(true));
  it('isBoolean bool7', () => expect(isBoolean(false)).toBe(true));
  it('isString str8', () => expect(isString('hello8')).toBe(true));
  it('isNumber num8', () => expect(isNumber(8)).toBe(true));
  it('isBoolean bool8', () => expect(isBoolean(true)).toBe(true));
  it('isString str9', () => expect(isString('hello9')).toBe(true));
  it('isNumber num9', () => expect(isNumber(9)).toBe(true));
  it('isBoolean bool9', () => expect(isBoolean(false)).toBe(true));
  it('isString str10', () => expect(isString('hello10')).toBe(true));
  it('isNumber num10', () => expect(isNumber(10)).toBe(true));
  it('isBoolean bool10', () => expect(isBoolean(true)).toBe(true));
  it('isString str11', () => expect(isString('hello11')).toBe(true));
  it('isNumber num11', () => expect(isNumber(11)).toBe(true));
  it('isBoolean bool11', () => expect(isBoolean(false)).toBe(true));
  it('isString str12', () => expect(isString('hello12')).toBe(true));
  it('isNumber num12', () => expect(isNumber(12)).toBe(true));
  it('isBoolean bool12', () => expect(isBoolean(true)).toBe(true));
  it('isString str13', () => expect(isString('hello13')).toBe(true));
  it('isNumber num13', () => expect(isNumber(13)).toBe(true));
  it('isBoolean bool13', () => expect(isBoolean(false)).toBe(true));
  it('isString str14', () => expect(isString('hello14')).toBe(true));
  it('isNumber num14', () => expect(isNumber(14)).toBe(true));
  it('isBoolean bool14', () => expect(isBoolean(true)).toBe(true));
  it('isString str15', () => expect(isString('hello15')).toBe(true));
  it('isNumber num15', () => expect(isNumber(15)).toBe(true));
  it('isBoolean bool15', () => expect(isBoolean(false)).toBe(true));
  it('isString str16', () => expect(isString('hello16')).toBe(true));
  it('isNumber num16', () => expect(isNumber(16)).toBe(true));
  it('isBoolean bool16', () => expect(isBoolean(true)).toBe(true));
  it('isString str17', () => expect(isString('hello17')).toBe(true));
  it('isNumber num17', () => expect(isNumber(17)).toBe(true));
  it('isBoolean bool17', () => expect(isBoolean(false)).toBe(true));
  it('isString str18', () => expect(isString('hello18')).toBe(true));
  it('isNumber num18', () => expect(isNumber(18)).toBe(true));
  it('isBoolean bool18', () => expect(isBoolean(true)).toBe(true));
  it('isString str19', () => expect(isString('hello19')).toBe(true));
  it('isNumber num19', () => expect(isNumber(19)).toBe(true));
  it('isBoolean bool19', () => expect(isBoolean(false)).toBe(true));
  it('isString str20', () => expect(isString('hello20')).toBe(true));
  it('isNumber num20', () => expect(isNumber(20)).toBe(true));
  it('isBoolean bool20', () => expect(isBoolean(true)).toBe(true));
  it('isString str21', () => expect(isString('hello21')).toBe(true));
  it('isNumber num21', () => expect(isNumber(21)).toBe(true));
  it('isBoolean bool21', () => expect(isBoolean(false)).toBe(true));
  it('isString str22', () => expect(isString('hello22')).toBe(true));
  it('isNumber num22', () => expect(isNumber(22)).toBe(true));
  it('isBoolean bool22', () => expect(isBoolean(true)).toBe(true));
  it('isString str23', () => expect(isString('hello23')).toBe(true));
  it('isNumber num23', () => expect(isNumber(23)).toBe(true));
  it('isBoolean bool23', () => expect(isBoolean(false)).toBe(true));
  it('isString str24', () => expect(isString('hello24')).toBe(true));
  it('isNumber num24', () => expect(isNumber(24)).toBe(true));
  it('isBoolean bool24', () => expect(isBoolean(true)).toBe(true));
  it('isString str25', () => expect(isString('hello25')).toBe(true));
  it('isNumber num25', () => expect(isNumber(25)).toBe(true));
  it('isBoolean bool25', () => expect(isBoolean(false)).toBe(true));
  it('isString str26', () => expect(isString('hello26')).toBe(true));
  it('isNumber num26', () => expect(isNumber(26)).toBe(true));
  it('isBoolean bool26', () => expect(isBoolean(true)).toBe(true));
  it('isString str27', () => expect(isString('hello27')).toBe(true));
  it('isNumber num27', () => expect(isNumber(27)).toBe(true));
  it('isBoolean bool27', () => expect(isBoolean(false)).toBe(true));
  it('isString str28', () => expect(isString('hello28')).toBe(true));
  it('isNumber num28', () => expect(isNumber(28)).toBe(true));
  it('isBoolean bool28', () => expect(isBoolean(true)).toBe(true));
  it('isString str29', () => expect(isString('hello29')).toBe(true));
  it('isNumber num29', () => expect(isNumber(29)).toBe(true));
  it('isBoolean bool29', () => expect(isBoolean(false)).toBe(true));
  it('isString str30', () => expect(isString('hello30')).toBe(true));
  it('isNumber num30', () => expect(isNumber(30)).toBe(true));
  it('isBoolean bool30', () => expect(isBoolean(true)).toBe(true));
  it('isString str31', () => expect(isString('hello31')).toBe(true));
  it('isNumber num31', () => expect(isNumber(31)).toBe(true));
  it('isBoolean bool31', () => expect(isBoolean(false)).toBe(true));
  it('isString str32', () => expect(isString('hello32')).toBe(true));
  it('isNumber num32', () => expect(isNumber(32)).toBe(true));
  it('isBoolean bool32', () => expect(isBoolean(true)).toBe(true));
  it('isString str33', () => expect(isString('hello33')).toBe(true));
  it('isNumber num33', () => expect(isNumber(33)).toBe(true));
  it('isBoolean bool33', () => expect(isBoolean(false)).toBe(true));
  it('isString false', () => expect(isString(42)).toBe(false));
  it('isNumber false', () => expect(isNumber('a')).toBe(false));
});

describe('matchType', () => {
  it('mt string0', () => expect(matchType('val0')).toBe('string'));
  it('mt number0', () => expect(matchType(0)).toBe('number'));
  it('mt boolean0', () => expect(matchType(true)).toBe('boolean'));
  it('mt array0', () => expect(matchType([0])).toBe('array'));
  it('mt object0', () => expect(matchType({a:0})).toBe('object'));
  it('mt string1', () => expect(matchType('val1')).toBe('string'));
  it('mt number1', () => expect(matchType(1)).toBe('number'));
  it('mt boolean1', () => expect(matchType(false)).toBe('boolean'));
  it('mt array1', () => expect(matchType([1])).toBe('array'));
  it('mt object1', () => expect(matchType({a:1})).toBe('object'));
  it('mt string2', () => expect(matchType('val2')).toBe('string'));
  it('mt number2', () => expect(matchType(2)).toBe('number'));
  it('mt boolean2', () => expect(matchType(true)).toBe('boolean'));
  it('mt array2', () => expect(matchType([2])).toBe('array'));
  it('mt object2', () => expect(matchType({a:2})).toBe('object'));
  it('mt string3', () => expect(matchType('val3')).toBe('string'));
  it('mt number3', () => expect(matchType(3)).toBe('number'));
  it('mt boolean3', () => expect(matchType(false)).toBe('boolean'));
  it('mt array3', () => expect(matchType([3])).toBe('array'));
  it('mt object3', () => expect(matchType({a:3})).toBe('object'));
  it('mt string4', () => expect(matchType('val4')).toBe('string'));
  it('mt number4', () => expect(matchType(4)).toBe('number'));
  it('mt boolean4', () => expect(matchType(true)).toBe('boolean'));
  it('mt array4', () => expect(matchType([4])).toBe('array'));
  it('mt object4', () => expect(matchType({a:4})).toBe('object'));
  it('mt string5', () => expect(matchType('val5')).toBe('string'));
  it('mt number5', () => expect(matchType(5)).toBe('number'));
  it('mt boolean5', () => expect(matchType(false)).toBe('boolean'));
  it('mt array5', () => expect(matchType([5])).toBe('array'));
  it('mt object5', () => expect(matchType({a:5})).toBe('object'));
  it('mt string6', () => expect(matchType('val6')).toBe('string'));
  it('mt number6', () => expect(matchType(6)).toBe('number'));
  it('mt boolean6', () => expect(matchType(true)).toBe('boolean'));
  it('mt array6', () => expect(matchType([6])).toBe('array'));
  it('mt object6', () => expect(matchType({a:6})).toBe('object'));
  it('mt string7', () => expect(matchType('val7')).toBe('string'));
  it('mt number7', () => expect(matchType(7)).toBe('number'));
  it('mt boolean7', () => expect(matchType(false)).toBe('boolean'));
  it('mt array7', () => expect(matchType([7])).toBe('array'));
  it('mt object7', () => expect(matchType({a:7})).toBe('object'));
  it('mt string8', () => expect(matchType('val8')).toBe('string'));
  it('mt number8', () => expect(matchType(8)).toBe('number'));
  it('mt boolean8', () => expect(matchType(true)).toBe('boolean'));
  it('mt array8', () => expect(matchType([8])).toBe('array'));
  it('mt object8', () => expect(matchType({a:8})).toBe('object'));
  it('mt string9', () => expect(matchType('val9')).toBe('string'));
  it('mt number9', () => expect(matchType(9)).toBe('number'));
  it('mt boolean9', () => expect(matchType(false)).toBe('boolean'));
  it('mt array9', () => expect(matchType([9])).toBe('array'));
  it('mt object9', () => expect(matchType({a:9})).toBe('object'));
  it('mt string10', () => expect(matchType('val10')).toBe('string'));
  it('mt number10', () => expect(matchType(10)).toBe('number'));
  it('mt boolean10', () => expect(matchType(true)).toBe('boolean'));
  it('mt array10', () => expect(matchType([10])).toBe('array'));
  it('mt object10', () => expect(matchType({a:10})).toBe('object'));
  it('mt string11', () => expect(matchType('val11')).toBe('string'));
  it('mt number11', () => expect(matchType(11)).toBe('number'));
  it('mt boolean11', () => expect(matchType(false)).toBe('boolean'));
  it('mt array11', () => expect(matchType([11])).toBe('array'));
  it('mt object11', () => expect(matchType({a:11})).toBe('object'));
  it('mt string12', () => expect(matchType('val12')).toBe('string'));
  it('mt number12', () => expect(matchType(12)).toBe('number'));
  it('mt boolean12', () => expect(matchType(true)).toBe('boolean'));
  it('mt array12', () => expect(matchType([12])).toBe('array'));
  it('mt object12', () => expect(matchType({a:12})).toBe('object'));
  it('mt string13', () => expect(matchType('val13')).toBe('string'));
  it('mt number13', () => expect(matchType(13)).toBe('number'));
  it('mt boolean13', () => expect(matchType(false)).toBe('boolean'));
  it('mt array13', () => expect(matchType([13])).toBe('array'));
  it('mt object13', () => expect(matchType({a:13})).toBe('object'));
  it('mt string14', () => expect(matchType('val14')).toBe('string'));
  it('mt number14', () => expect(matchType(14)).toBe('number'));
  it('mt boolean14', () => expect(matchType(true)).toBe('boolean'));
  it('mt array14', () => expect(matchType([14])).toBe('array'));
  it('mt object14', () => expect(matchType({a:14})).toBe('object'));
  it('mt string15', () => expect(matchType('val15')).toBe('string'));
  it('mt number15', () => expect(matchType(15)).toBe('number'));
  it('mt boolean15', () => expect(matchType(false)).toBe('boolean'));
  it('mt array15', () => expect(matchType([15])).toBe('array'));
  it('mt object15', () => expect(matchType({a:15})).toBe('object'));
  it('mt string16', () => expect(matchType('val16')).toBe('string'));
  it('mt number16', () => expect(matchType(16)).toBe('number'));
  it('mt boolean16', () => expect(matchType(true)).toBe('boolean'));
  it('mt array16', () => expect(matchType([16])).toBe('array'));
  it('mt object16', () => expect(matchType({a:16})).toBe('object'));
  it('mt string17', () => expect(matchType('val17')).toBe('string'));
  it('mt number17', () => expect(matchType(17)).toBe('number'));
  it('mt boolean17', () => expect(matchType(false)).toBe('boolean'));
  it('mt array17', () => expect(matchType([17])).toBe('array'));
  it('mt object17', () => expect(matchType({a:17})).toBe('object'));
  it('mt string18', () => expect(matchType('val18')).toBe('string'));
  it('mt number18', () => expect(matchType(18)).toBe('number'));
  it('mt boolean18', () => expect(matchType(true)).toBe('boolean'));
  it('mt array18', () => expect(matchType([18])).toBe('array'));
  it('mt object18', () => expect(matchType({a:18})).toBe('object'));
  it('mt string19', () => expect(matchType('val19')).toBe('string'));
  it('mt number19', () => expect(matchType(19)).toBe('number'));
  it('mt boolean19', () => expect(matchType(false)).toBe('boolean'));
  it('mt array19', () => expect(matchType([19])).toBe('array'));
  it('mt object19', () => expect(matchType({a:19})).toBe('object'));
  it('mt null', () => expect(matchType(null)).toBe('null'));
  it('mt undef', () => expect(matchType(undefined)).toBe('undefined'));
  it('mt fn', () => expect(matchType(() => 1)).toBe('function'));
});

describe('glob', () => {
  it('glob star0', () => expect(glob('prefix*', 'prefix0')).toBe(true));
  it('glob star1', () => expect(glob('prefix*', 'prefix1')).toBe(true));
  it('glob star2', () => expect(glob('prefix*', 'prefix2')).toBe(true));
  it('glob star3', () => expect(glob('prefix*', 'prefix3')).toBe(true));
  it('glob star4', () => expect(glob('prefix*', 'prefix4')).toBe(true));
  it('glob star5', () => expect(glob('prefix*', 'prefix5')).toBe(true));
  it('glob star6', () => expect(glob('prefix*', 'prefix6')).toBe(true));
  it('glob star7', () => expect(glob('prefix*', 'prefix7')).toBe(true));
  it('glob star8', () => expect(glob('prefix*', 'prefix8')).toBe(true));
  it('glob star9', () => expect(glob('prefix*', 'prefix9')).toBe(true));
  it('glob star10', () => expect(glob('prefix*', 'prefix10')).toBe(true));
  it('glob star11', () => expect(glob('prefix*', 'prefix11')).toBe(true));
  it('glob star12', () => expect(glob('prefix*', 'prefix12')).toBe(true));
  it('glob star13', () => expect(glob('prefix*', 'prefix13')).toBe(true));
  it('glob star14', () => expect(glob('prefix*', 'prefix14')).toBe(true));
  it('glob star15', () => expect(glob('prefix*', 'prefix15')).toBe(true));
  it('glob star16', () => expect(glob('prefix*', 'prefix16')).toBe(true));
  it('glob star17', () => expect(glob('prefix*', 'prefix17')).toBe(true));
  it('glob star18', () => expect(glob('prefix*', 'prefix18')).toBe(true));
  it('glob star19', () => expect(glob('prefix*', 'prefix19')).toBe(true));
  it('glob star20', () => expect(glob('prefix*', 'prefix20')).toBe(true));
  it('glob star21', () => expect(glob('prefix*', 'prefix21')).toBe(true));
  it('glob star22', () => expect(glob('prefix*', 'prefix22')).toBe(true));
  it('glob star23', () => expect(glob('prefix*', 'prefix23')).toBe(true));
  it('glob star24', () => expect(glob('prefix*', 'prefix24')).toBe(true));
  it('glob star25', () => expect(glob('prefix*', 'prefix25')).toBe(true));
  it('glob star26', () => expect(glob('prefix*', 'prefix26')).toBe(true));
  it('glob star27', () => expect(glob('prefix*', 'prefix27')).toBe(true));
  it('glob star28', () => expect(glob('prefix*', 'prefix28')).toBe(true));
  it('glob star29', () => expect(glob('prefix*', 'prefix29')).toBe(true));
  it('glob star30', () => expect(glob('prefix*', 'prefix30')).toBe(true));
  it('glob star31', () => expect(glob('prefix*', 'prefix31')).toBe(true));
  it('glob star32', () => expect(glob('prefix*', 'prefix32')).toBe(true));
  it('glob star33', () => expect(glob('prefix*', 'prefix33')).toBe(true));
  it('glob star34', () => expect(glob('prefix*', 'prefix34')).toBe(true));
  it('glob star35', () => expect(glob('prefix*', 'prefix35')).toBe(true));
  it('glob star36', () => expect(glob('prefix*', 'prefix36')).toBe(true));
  it('glob star37', () => expect(glob('prefix*', 'prefix37')).toBe(true));
  it('glob star38', () => expect(glob('prefix*', 'prefix38')).toBe(true));
  it('glob star39', () => expect(glob('prefix*', 'prefix39')).toBe(true));
  it('glob star40', () => expect(glob('prefix*', 'prefix40')).toBe(true));
  it('glob star41', () => expect(glob('prefix*', 'prefix41')).toBe(true));
  it('glob star42', () => expect(glob('prefix*', 'prefix42')).toBe(true));
  it('glob star43', () => expect(glob('prefix*', 'prefix43')).toBe(true));
  it('glob star44', () => expect(glob('prefix*', 'prefix44')).toBe(true));
  it('glob star45', () => expect(glob('prefix*', 'prefix45')).toBe(true));
  it('glob star46', () => expect(glob('prefix*', 'prefix46')).toBe(true));
  it('glob star47', () => expect(glob('prefix*', 'prefix47')).toBe(true));
  it('glob star48', () => expect(glob('prefix*', 'prefix48')).toBe(true));
  it('glob star49', () => expect(glob('prefix*', 'prefix49')).toBe(true));
  it('glob q0', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q1', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q2', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q3', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q4', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q5', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q6', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q7', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q8', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q9', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q10', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q11', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q12', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q13', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q14', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q15', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q16', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q17', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q18', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q19', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q20', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q21', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q22', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q23', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q24', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q25', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q26', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q27', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q28', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q29', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q30', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q31', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q32', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q33', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q34', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q35', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q36', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q37', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q38', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q39', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q40', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q41', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q42', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q43', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q44', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q45', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q46', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q47', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q48', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob q49', () => expect(glob('?????', 'hello')).toBe(true));
  it('glob nm0', () => expect(glob('exact0', 'wrong')).toBe(false));
  it('glob nm1', () => expect(glob('exact1', 'wrong')).toBe(false));
  it('glob nm2', () => expect(glob('exact2', 'wrong')).toBe(false));
  it('glob nm3', () => expect(glob('exact3', 'wrong')).toBe(false));
  it('glob nm4', () => expect(glob('exact4', 'wrong')).toBe(false));
  it('glob nm5', () => expect(glob('exact5', 'wrong')).toBe(false));
  it('glob nm6', () => expect(glob('exact6', 'wrong')).toBe(false));
  it('glob nm7', () => expect(glob('exact7', 'wrong')).toBe(false));
  it('glob nm8', () => expect(glob('exact8', 'wrong')).toBe(false));
  it('glob nm9', () => expect(glob('exact9', 'wrong')).toBe(false));
  it('glob nm10', () => expect(glob('exact10', 'wrong')).toBe(false));
  it('glob nm11', () => expect(glob('exact11', 'wrong')).toBe(false));
  it('glob nm12', () => expect(glob('exact12', 'wrong')).toBe(false));
  it('glob nm13', () => expect(glob('exact13', 'wrong')).toBe(false));
  it('glob nm14', () => expect(glob('exact14', 'wrong')).toBe(false));
  it('glob nm15', () => expect(glob('exact15', 'wrong')).toBe(false));
  it('glob nm16', () => expect(glob('exact16', 'wrong')).toBe(false));
  it('glob nm17', () => expect(glob('exact17', 'wrong')).toBe(false));
  it('glob nm18', () => expect(glob('exact18', 'wrong')).toBe(false));
  it('glob nm19', () => expect(glob('exact19', 'wrong')).toBe(false));
  it('glob nm20', () => expect(glob('exact20', 'wrong')).toBe(false));
  it('glob nm21', () => expect(glob('exact21', 'wrong')).toBe(false));
  it('glob nm22', () => expect(glob('exact22', 'wrong')).toBe(false));
  it('glob nm23', () => expect(glob('exact23', 'wrong')).toBe(false));
  it('glob nm24', () => expect(glob('exact24', 'wrong')).toBe(false));
  it('glob nm25', () => expect(glob('exact25', 'wrong')).toBe(false));
  it('glob nm26', () => expect(glob('exact26', 'wrong')).toBe(false));
  it('glob nm27', () => expect(glob('exact27', 'wrong')).toBe(false));
  it('glob nm28', () => expect(glob('exact28', 'wrong')).toBe(false));
  it('glob nm29', () => expect(glob('exact29', 'wrong')).toBe(false));
  it('glob nm30', () => expect(glob('exact30', 'wrong')).toBe(false));
  it('glob nm31', () => expect(glob('exact31', 'wrong')).toBe(false));
  it('glob nm32', () => expect(glob('exact32', 'wrong')).toBe(false));
  it('glob nm33', () => expect(glob('exact33', 'wrong')).toBe(false));
  it('glob nm34', () => expect(glob('exact34', 'wrong')).toBe(false));
  it('glob nm35', () => expect(glob('exact35', 'wrong')).toBe(false));
  it('glob nm36', () => expect(glob('exact36', 'wrong')).toBe(false));
  it('glob nm37', () => expect(glob('exact37', 'wrong')).toBe(false));
  it('glob nm38', () => expect(glob('exact38', 'wrong')).toBe(false));
  it('glob nm39', () => expect(glob('exact39', 'wrong')).toBe(false));
  it('glob nm40', () => expect(glob('exact40', 'wrong')).toBe(false));
  it('glob nm41', () => expect(glob('exact41', 'wrong')).toBe(false));
  it('glob nm42', () => expect(glob('exact42', 'wrong')).toBe(false));
  it('glob nm43', () => expect(glob('exact43', 'wrong')).toBe(false));
  it('glob nm44', () => expect(glob('exact44', 'wrong')).toBe(false));
  it('glob nm45', () => expect(glob('exact45', 'wrong')).toBe(false));
  it('glob nm46', () => expect(glob('exact46', 'wrong')).toBe(false));
  it('glob nm47', () => expect(glob('exact47', 'wrong')).toBe(false));
  it('glob nm48', () => expect(glob('exact48', 'wrong')).toBe(false));
  it('glob nm49', () => expect(glob('exact49', 'wrong')).toBe(false));
});

describe('deepMatch', () => {
  it('dm match0', () => expect(deepMatch({a:0,b:'x'},{a:0})).toBe(true));
  it('dm match1', () => expect(deepMatch({a:1,b:'x'},{a:1})).toBe(true));
  it('dm match2', () => expect(deepMatch({a:2,b:'x'},{a:2})).toBe(true));
  it('dm match3', () => expect(deepMatch({a:3,b:'x'},{a:3})).toBe(true));
  it('dm match4', () => expect(deepMatch({a:4,b:'x'},{a:4})).toBe(true));
  it('dm match5', () => expect(deepMatch({a:5,b:'x'},{a:5})).toBe(true));
  it('dm match6', () => expect(deepMatch({a:6,b:'x'},{a:6})).toBe(true));
  it('dm match7', () => expect(deepMatch({a:7,b:'x'},{a:7})).toBe(true));
  it('dm match8', () => expect(deepMatch({a:8,b:'x'},{a:8})).toBe(true));
  it('dm match9', () => expect(deepMatch({a:9,b:'x'},{a:9})).toBe(true));
  it('dm match10', () => expect(deepMatch({a:10,b:'x'},{a:10})).toBe(true));
  it('dm match11', () => expect(deepMatch({a:11,b:'x'},{a:11})).toBe(true));
  it('dm match12', () => expect(deepMatch({a:12,b:'x'},{a:12})).toBe(true));
  it('dm match13', () => expect(deepMatch({a:13,b:'x'},{a:13})).toBe(true));
  it('dm match14', () => expect(deepMatch({a:14,b:'x'},{a:14})).toBe(true));
  it('dm match15', () => expect(deepMatch({a:15,b:'x'},{a:15})).toBe(true));
  it('dm match16', () => expect(deepMatch({a:16,b:'x'},{a:16})).toBe(true));
  it('dm match17', () => expect(deepMatch({a:17,b:'x'},{a:17})).toBe(true));
  it('dm match18', () => expect(deepMatch({a:18,b:'x'},{a:18})).toBe(true));
  it('dm match19', () => expect(deepMatch({a:19,b:'x'},{a:19})).toBe(true));
  it('dm match20', () => expect(deepMatch({a:20,b:'x'},{a:20})).toBe(true));
  it('dm match21', () => expect(deepMatch({a:21,b:'x'},{a:21})).toBe(true));
  it('dm match22', () => expect(deepMatch({a:22,b:'x'},{a:22})).toBe(true));
  it('dm match23', () => expect(deepMatch({a:23,b:'x'},{a:23})).toBe(true));
  it('dm match24', () => expect(deepMatch({a:24,b:'x'},{a:24})).toBe(true));
  it('dm match25', () => expect(deepMatch({a:25,b:'x'},{a:25})).toBe(true));
  it('dm match26', () => expect(deepMatch({a:26,b:'x'},{a:26})).toBe(true));
  it('dm match27', () => expect(deepMatch({a:27,b:'x'},{a:27})).toBe(true));
  it('dm match28', () => expect(deepMatch({a:28,b:'x'},{a:28})).toBe(true));
  it('dm match29', () => expect(deepMatch({a:29,b:'x'},{a:29})).toBe(true));
  it('dm match30', () => expect(deepMatch({a:30,b:'x'},{a:30})).toBe(true));
  it('dm match31', () => expect(deepMatch({a:31,b:'x'},{a:31})).toBe(true));
  it('dm match32', () => expect(deepMatch({a:32,b:'x'},{a:32})).toBe(true));
  it('dm match33', () => expect(deepMatch({a:33,b:'x'},{a:33})).toBe(true));
  it('dm match34', () => expect(deepMatch({a:34,b:'x'},{a:34})).toBe(true));
  it('dm match35', () => expect(deepMatch({a:35,b:'x'},{a:35})).toBe(true));
  it('dm match36', () => expect(deepMatch({a:36,b:'x'},{a:36})).toBe(true));
  it('dm match37', () => expect(deepMatch({a:37,b:'x'},{a:37})).toBe(true));
  it('dm match38', () => expect(deepMatch({a:38,b:'x'},{a:38})).toBe(true));
  it('dm match39', () => expect(deepMatch({a:39,b:'x'},{a:39})).toBe(true));
  it('dm match40', () => expect(deepMatch({a:40,b:'x'},{a:40})).toBe(true));
  it('dm match41', () => expect(deepMatch({a:41,b:'x'},{a:41})).toBe(true));
  it('dm match42', () => expect(deepMatch({a:42,b:'x'},{a:42})).toBe(true));
  it('dm match43', () => expect(deepMatch({a:43,b:'x'},{a:43})).toBe(true));
  it('dm match44', () => expect(deepMatch({a:44,b:'x'},{a:44})).toBe(true));
  it('dm match45', () => expect(deepMatch({a:45,b:'x'},{a:45})).toBe(true));
  it('dm match46', () => expect(deepMatch({a:46,b:'x'},{a:46})).toBe(true));
  it('dm match47', () => expect(deepMatch({a:47,b:'x'},{a:47})).toBe(true));
  it('dm match48', () => expect(deepMatch({a:48,b:'x'},{a:48})).toBe(true));
  it('dm match49', () => expect(deepMatch({a:49,b:'x'},{a:49})).toBe(true));
  it('dm match50', () => expect(deepMatch({a:50,b:'x'},{a:50})).toBe(true));
  it('dm match51', () => expect(deepMatch({a:51,b:'x'},{a:51})).toBe(true));
  it('dm match52', () => expect(deepMatch({a:52,b:'x'},{a:52})).toBe(true));
  it('dm match53', () => expect(deepMatch({a:53,b:'x'},{a:53})).toBe(true));
  it('dm match54', () => expect(deepMatch({a:54,b:'x'},{a:54})).toBe(true));
  it('dm match55', () => expect(deepMatch({a:55,b:'x'},{a:55})).toBe(true));
  it('dm match56', () => expect(deepMatch({a:56,b:'x'},{a:56})).toBe(true));
  it('dm match57', () => expect(deepMatch({a:57,b:'x'},{a:57})).toBe(true));
  it('dm match58', () => expect(deepMatch({a:58,b:'x'},{a:58})).toBe(true));
  it('dm match59', () => expect(deepMatch({a:59,b:'x'},{a:59})).toBe(true));
  it('dm match60', () => expect(deepMatch({a:60,b:'x'},{a:60})).toBe(true));
  it('dm match61', () => expect(deepMatch({a:61,b:'x'},{a:61})).toBe(true));
  it('dm match62', () => expect(deepMatch({a:62,b:'x'},{a:62})).toBe(true));
  it('dm match63', () => expect(deepMatch({a:63,b:'x'},{a:63})).toBe(true));
  it('dm match64', () => expect(deepMatch({a:64,b:'x'},{a:64})).toBe(true));
  it('dm match65', () => expect(deepMatch({a:65,b:'x'},{a:65})).toBe(true));
  it('dm match66', () => expect(deepMatch({a:66,b:'x'},{a:66})).toBe(true));
  it('dm match67', () => expect(deepMatch({a:67,b:'x'},{a:67})).toBe(true));
  it('dm match68', () => expect(deepMatch({a:68,b:'x'},{a:68})).toBe(true));
  it('dm match69', () => expect(deepMatch({a:69,b:'x'},{a:69})).toBe(true));
  it('dm match70', () => expect(deepMatch({a:70,b:'x'},{a:70})).toBe(true));
  it('dm match71', () => expect(deepMatch({a:71,b:'x'},{a:71})).toBe(true));
  it('dm match72', () => expect(deepMatch({a:72,b:'x'},{a:72})).toBe(true));
  it('dm match73', () => expect(deepMatch({a:73,b:'x'},{a:73})).toBe(true));
  it('dm match74', () => expect(deepMatch({a:74,b:'x'},{a:74})).toBe(true));
  it('dm nomatch0', () => expect(deepMatch({a:0},{a:1})).toBe(false));
  it('dm nomatch1', () => expect(deepMatch({a:1},{a:2})).toBe(false));
  it('dm nomatch2', () => expect(deepMatch({a:2},{a:3})).toBe(false));
  it('dm nomatch3', () => expect(deepMatch({a:3},{a:4})).toBe(false));
  it('dm nomatch4', () => expect(deepMatch({a:4},{a:5})).toBe(false));
  it('dm nomatch5', () => expect(deepMatch({a:5},{a:6})).toBe(false));
  it('dm nomatch6', () => expect(deepMatch({a:6},{a:7})).toBe(false));
  it('dm nomatch7', () => expect(deepMatch({a:7},{a:8})).toBe(false));
  it('dm nomatch8', () => expect(deepMatch({a:8},{a:9})).toBe(false));
  it('dm nomatch9', () => expect(deepMatch({a:9},{a:10})).toBe(false));
  it('dm nomatch10', () => expect(deepMatch({a:10},{a:11})).toBe(false));
  it('dm nomatch11', () => expect(deepMatch({a:11},{a:12})).toBe(false));
  it('dm nomatch12', () => expect(deepMatch({a:12},{a:13})).toBe(false));
  it('dm nomatch13', () => expect(deepMatch({a:13},{a:14})).toBe(false));
  it('dm nomatch14', () => expect(deepMatch({a:14},{a:15})).toBe(false));
  it('dm nomatch15', () => expect(deepMatch({a:15},{a:16})).toBe(false));
  it('dm nomatch16', () => expect(deepMatch({a:16},{a:17})).toBe(false));
  it('dm nomatch17', () => expect(deepMatch({a:17},{a:18})).toBe(false));
  it('dm nomatch18', () => expect(deepMatch({a:18},{a:19})).toBe(false));
  it('dm nomatch19', () => expect(deepMatch({a:19},{a:20})).toBe(false));
  it('dm nomatch20', () => expect(deepMatch({a:20},{a:21})).toBe(false));
  it('dm nomatch21', () => expect(deepMatch({a:21},{a:22})).toBe(false));
  it('dm nomatch22', () => expect(deepMatch({a:22},{a:23})).toBe(false));
  it('dm nomatch23', () => expect(deepMatch({a:23},{a:24})).toBe(false));
  it('dm nomatch24', () => expect(deepMatch({a:24},{a:25})).toBe(false));
  it('dm nomatch25', () => expect(deepMatch({a:25},{a:26})).toBe(false));
  it('dm nomatch26', () => expect(deepMatch({a:26},{a:27})).toBe(false));
  it('dm nomatch27', () => expect(deepMatch({a:27},{a:28})).toBe(false));
  it('dm nomatch28', () => expect(deepMatch({a:28},{a:29})).toBe(false));
  it('dm nomatch29', () => expect(deepMatch({a:29},{a:30})).toBe(false));
  it('dm nomatch30', () => expect(deepMatch({a:30},{a:31})).toBe(false));
  it('dm nomatch31', () => expect(deepMatch({a:31},{a:32})).toBe(false));
  it('dm nomatch32', () => expect(deepMatch({a:32},{a:33})).toBe(false));
  it('dm nomatch33', () => expect(deepMatch({a:33},{a:34})).toBe(false));
  it('dm nomatch34', () => expect(deepMatch({a:34},{a:35})).toBe(false));
  it('dm nomatch35', () => expect(deepMatch({a:35},{a:36})).toBe(false));
  it('dm nomatch36', () => expect(deepMatch({a:36},{a:37})).toBe(false));
  it('dm nomatch37', () => expect(deepMatch({a:37},{a:38})).toBe(false));
  it('dm nomatch38', () => expect(deepMatch({a:38},{a:39})).toBe(false));
  it('dm nomatch39', () => expect(deepMatch({a:39},{a:40})).toBe(false));
  it('dm nomatch40', () => expect(deepMatch({a:40},{a:41})).toBe(false));
  it('dm nomatch41', () => expect(deepMatch({a:41},{a:42})).toBe(false));
  it('dm nomatch42', () => expect(deepMatch({a:42},{a:43})).toBe(false));
  it('dm nomatch43', () => expect(deepMatch({a:43},{a:44})).toBe(false));
  it('dm nomatch44', () => expect(deepMatch({a:44},{a:45})).toBe(false));
  it('dm nomatch45', () => expect(deepMatch({a:45},{a:46})).toBe(false));
  it('dm nomatch46', () => expect(deepMatch({a:46},{a:47})).toBe(false));
  it('dm nomatch47', () => expect(deepMatch({a:47},{a:48})).toBe(false));
  it('dm nomatch48', () => expect(deepMatch({a:48},{a:49})).toBe(false));
  it('dm nomatch49', () => expect(deepMatch({a:49},{a:50})).toBe(false));
  it('dm nomatch50', () => expect(deepMatch({a:50},{a:51})).toBe(false));
  it('dm nomatch51', () => expect(deepMatch({a:51},{a:52})).toBe(false));
  it('dm nomatch52', () => expect(deepMatch({a:52},{a:53})).toBe(false));
  it('dm nomatch53', () => expect(deepMatch({a:53},{a:54})).toBe(false));
  it('dm nomatch54', () => expect(deepMatch({a:54},{a:55})).toBe(false));
  it('dm nomatch55', () => expect(deepMatch({a:55},{a:56})).toBe(false));
  it('dm nomatch56', () => expect(deepMatch({a:56},{a:57})).toBe(false));
  it('dm nomatch57', () => expect(deepMatch({a:57},{a:58})).toBe(false));
  it('dm nomatch58', () => expect(deepMatch({a:58},{a:59})).toBe(false));
  it('dm nomatch59', () => expect(deepMatch({a:59},{a:60})).toBe(false));
  it('dm nomatch60', () => expect(deepMatch({a:60},{a:61})).toBe(false));
  it('dm nomatch61', () => expect(deepMatch({a:61},{a:62})).toBe(false));
  it('dm nomatch62', () => expect(deepMatch({a:62},{a:63})).toBe(false));
  it('dm nomatch63', () => expect(deepMatch({a:63},{a:64})).toBe(false));
  it('dm nomatch64', () => expect(deepMatch({a:64},{a:65})).toBe(false));
  it('dm nomatch65', () => expect(deepMatch({a:65},{a:66})).toBe(false));
  it('dm nomatch66', () => expect(deepMatch({a:66},{a:67})).toBe(false));
  it('dm nomatch67', () => expect(deepMatch({a:67},{a:68})).toBe(false));
  it('dm nomatch68', () => expect(deepMatch({a:68},{a:69})).toBe(false));
  it('dm nomatch69', () => expect(deepMatch({a:69},{a:70})).toBe(false));
  it('dm nomatch70', () => expect(deepMatch({a:70},{a:71})).toBe(false));
  it('dm nomatch71', () => expect(deepMatch({a:71},{a:72})).toBe(false));
  it('dm nomatch72', () => expect(deepMatch({a:72},{a:73})).toBe(false));
  it('dm nomatch73', () => expect(deepMatch({a:73},{a:74})).toBe(false));
  it('dm nomatch74', () => expect(deepMatch({a:74},{a:75})).toBe(false));
});

describe('wildcardMatch', () => {
  it('wm match0', () => expect(wildcardMatch('pre*', 'pre0')).toBe(true));
  it('wm match1', () => expect(wildcardMatch('pre*', 'pre1')).toBe(true));
  it('wm match2', () => expect(wildcardMatch('pre*', 'pre2')).toBe(true));
  it('wm match3', () => expect(wildcardMatch('pre*', 'pre3')).toBe(true));
  it('wm match4', () => expect(wildcardMatch('pre*', 'pre4')).toBe(true));
  it('wm match5', () => expect(wildcardMatch('pre*', 'pre5')).toBe(true));
  it('wm match6', () => expect(wildcardMatch('pre*', 'pre6')).toBe(true));
  it('wm match7', () => expect(wildcardMatch('pre*', 'pre7')).toBe(true));
  it('wm match8', () => expect(wildcardMatch('pre*', 'pre8')).toBe(true));
  it('wm match9', () => expect(wildcardMatch('pre*', 'pre9')).toBe(true));
  it('wm match10', () => expect(wildcardMatch('pre*', 'pre10')).toBe(true));
  it('wm match11', () => expect(wildcardMatch('pre*', 'pre11')).toBe(true));
  it('wm match12', () => expect(wildcardMatch('pre*', 'pre12')).toBe(true));
  it('wm match13', () => expect(wildcardMatch('pre*', 'pre13')).toBe(true));
  it('wm match14', () => expect(wildcardMatch('pre*', 'pre14')).toBe(true));
  it('wm match15', () => expect(wildcardMatch('pre*', 'pre15')).toBe(true));
  it('wm match16', () => expect(wildcardMatch('pre*', 'pre16')).toBe(true));
  it('wm match17', () => expect(wildcardMatch('pre*', 'pre17')).toBe(true));
  it('wm match18', () => expect(wildcardMatch('pre*', 'pre18')).toBe(true));
  it('wm match19', () => expect(wildcardMatch('pre*', 'pre19')).toBe(true));
  it('wm match20', () => expect(wildcardMatch('pre*', 'pre20')).toBe(true));
  it('wm match21', () => expect(wildcardMatch('pre*', 'pre21')).toBe(true));
  it('wm match22', () => expect(wildcardMatch('pre*', 'pre22')).toBe(true));
  it('wm match23', () => expect(wildcardMatch('pre*', 'pre23')).toBe(true));
  it('wm match24', () => expect(wildcardMatch('pre*', 'pre24')).toBe(true));
  it('wm match25', () => expect(wildcardMatch('pre*', 'pre25')).toBe(true));
  it('wm match26', () => expect(wildcardMatch('pre*', 'pre26')).toBe(true));
  it('wm match27', () => expect(wildcardMatch('pre*', 'pre27')).toBe(true));
  it('wm match28', () => expect(wildcardMatch('pre*', 'pre28')).toBe(true));
  it('wm match29', () => expect(wildcardMatch('pre*', 'pre29')).toBe(true));
  it('wm match30', () => expect(wildcardMatch('pre*', 'pre30')).toBe(true));
  it('wm match31', () => expect(wildcardMatch('pre*', 'pre31')).toBe(true));
  it('wm match32', () => expect(wildcardMatch('pre*', 'pre32')).toBe(true));
  it('wm match33', () => expect(wildcardMatch('pre*', 'pre33')).toBe(true));
  it('wm match34', () => expect(wildcardMatch('pre*', 'pre34')).toBe(true));
  it('wm match35', () => expect(wildcardMatch('pre*', 'pre35')).toBe(true));
  it('wm match36', () => expect(wildcardMatch('pre*', 'pre36')).toBe(true));
  it('wm match37', () => expect(wildcardMatch('pre*', 'pre37')).toBe(true));
  it('wm match38', () => expect(wildcardMatch('pre*', 'pre38')).toBe(true));
  it('wm match39', () => expect(wildcardMatch('pre*', 'pre39')).toBe(true));
  it('wm match40', () => expect(wildcardMatch('pre*', 'pre40')).toBe(true));
  it('wm match41', () => expect(wildcardMatch('pre*', 'pre41')).toBe(true));
  it('wm match42', () => expect(wildcardMatch('pre*', 'pre42')).toBe(true));
  it('wm match43', () => expect(wildcardMatch('pre*', 'pre43')).toBe(true));
  it('wm match44', () => expect(wildcardMatch('pre*', 'pre44')).toBe(true));
  it('wm match45', () => expect(wildcardMatch('pre*', 'pre45')).toBe(true));
  it('wm match46', () => expect(wildcardMatch('pre*', 'pre46')).toBe(true));
  it('wm match47', () => expect(wildcardMatch('pre*', 'pre47')).toBe(true));
  it('wm match48', () => expect(wildcardMatch('pre*', 'pre48')).toBe(true));
  it('wm match49', () => expect(wildcardMatch('pre*', 'pre49')).toBe(true));
  it('wm nomatch0', () => expect(wildcardMatch('nope0', 'different')).toBe(false));
  it('wm nomatch1', () => expect(wildcardMatch('nope1', 'different')).toBe(false));
  it('wm nomatch2', () => expect(wildcardMatch('nope2', 'different')).toBe(false));
  it('wm nomatch3', () => expect(wildcardMatch('nope3', 'different')).toBe(false));
  it('wm nomatch4', () => expect(wildcardMatch('nope4', 'different')).toBe(false));
  it('wm nomatch5', () => expect(wildcardMatch('nope5', 'different')).toBe(false));
  it('wm nomatch6', () => expect(wildcardMatch('nope6', 'different')).toBe(false));
  it('wm nomatch7', () => expect(wildcardMatch('nope7', 'different')).toBe(false));
  it('wm nomatch8', () => expect(wildcardMatch('nope8', 'different')).toBe(false));
  it('wm nomatch9', () => expect(wildcardMatch('nope9', 'different')).toBe(false));
  it('wm nomatch10', () => expect(wildcardMatch('nope10', 'different')).toBe(false));
  it('wm nomatch11', () => expect(wildcardMatch('nope11', 'different')).toBe(false));
  it('wm nomatch12', () => expect(wildcardMatch('nope12', 'different')).toBe(false));
  it('wm nomatch13', () => expect(wildcardMatch('nope13', 'different')).toBe(false));
  it('wm nomatch14', () => expect(wildcardMatch('nope14', 'different')).toBe(false));
  it('wm nomatch15', () => expect(wildcardMatch('nope15', 'different')).toBe(false));
  it('wm nomatch16', () => expect(wildcardMatch('nope16', 'different')).toBe(false));
  it('wm nomatch17', () => expect(wildcardMatch('nope17', 'different')).toBe(false));
  it('wm nomatch18', () => expect(wildcardMatch('nope18', 'different')).toBe(false));
  it('wm nomatch19', () => expect(wildcardMatch('nope19', 'different')).toBe(false));
  it('wm nomatch20', () => expect(wildcardMatch('nope20', 'different')).toBe(false));
  it('wm nomatch21', () => expect(wildcardMatch('nope21', 'different')).toBe(false));
  it('wm nomatch22', () => expect(wildcardMatch('nope22', 'different')).toBe(false));
  it('wm nomatch23', () => expect(wildcardMatch('nope23', 'different')).toBe(false));
  it('wm nomatch24', () => expect(wildcardMatch('nope24', 'different')).toBe(false));
  it('wm nomatch25', () => expect(wildcardMatch('nope25', 'different')).toBe(false));
  it('wm nomatch26', () => expect(wildcardMatch('nope26', 'different')).toBe(false));
  it('wm nomatch27', () => expect(wildcardMatch('nope27', 'different')).toBe(false));
  it('wm nomatch28', () => expect(wildcardMatch('nope28', 'different')).toBe(false));
  it('wm nomatch29', () => expect(wildcardMatch('nope29', 'different')).toBe(false));
  it('wm nomatch30', () => expect(wildcardMatch('nope30', 'different')).toBe(false));
  it('wm nomatch31', () => expect(wildcardMatch('nope31', 'different')).toBe(false));
  it('wm nomatch32', () => expect(wildcardMatch('nope32', 'different')).toBe(false));
  it('wm nomatch33', () => expect(wildcardMatch('nope33', 'different')).toBe(false));
  it('wm nomatch34', () => expect(wildcardMatch('nope34', 'different')).toBe(false));
  it('wm nomatch35', () => expect(wildcardMatch('nope35', 'different')).toBe(false));
  it('wm nomatch36', () => expect(wildcardMatch('nope36', 'different')).toBe(false));
  it('wm nomatch37', () => expect(wildcardMatch('nope37', 'different')).toBe(false));
  it('wm nomatch38', () => expect(wildcardMatch('nope38', 'different')).toBe(false));
  it('wm nomatch39', () => expect(wildcardMatch('nope39', 'different')).toBe(false));
  it('wm nomatch40', () => expect(wildcardMatch('nope40', 'different')).toBe(false));
  it('wm nomatch41', () => expect(wildcardMatch('nope41', 'different')).toBe(false));
  it('wm nomatch42', () => expect(wildcardMatch('nope42', 'different')).toBe(false));
  it('wm nomatch43', () => expect(wildcardMatch('nope43', 'different')).toBe(false));
  it('wm nomatch44', () => expect(wildcardMatch('nope44', 'different')).toBe(false));
  it('wm nomatch45', () => expect(wildcardMatch('nope45', 'different')).toBe(false));
  it('wm nomatch46', () => expect(wildcardMatch('nope46', 'different')).toBe(false));
  it('wm nomatch47', () => expect(wildcardMatch('nope47', 'different')).toBe(false));
  it('wm nomatch48', () => expect(wildcardMatch('nope48', 'different')).toBe(false));
  it('wm nomatch49', () => expect(wildcardMatch('nope49', 'different')).toBe(false));
});

describe('extractGroups', () => {
  it('eg match0', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match1', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match2', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match3', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match4', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match5', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match6', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match7', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match8', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match9', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match10', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match11', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match12', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match13', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match14', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match15', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match16', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match17', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match18', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match19', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match20', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match21', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match22', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match23', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match24', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match25', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match26', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match27', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match28', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match29', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match30', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match31', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match32', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match33', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match34', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match35', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match36', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match37', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match38', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match39', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match40', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match41', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match42', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match43', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match44', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match45', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match46', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match47', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match48', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg match49', () => { const r = extractGroups(/(?<name>hello)/,'hello world'); expect(r).not.toBeNull(); });
  it('eg null0', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null1', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null2', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null3', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null4', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null5', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null6', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null7', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null8', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null9', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null10', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null11', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null12', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null13', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null14', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null15', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null16', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null17', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null18', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null19', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null20', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null21', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null22', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null23', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null24', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null25', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null26', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null27', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null28', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null29', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null30', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null31', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null32', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null33', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null34', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null35', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null36', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null37', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null38', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null39', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null40', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null41', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null42', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null43', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null44', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null45', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null46', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null47', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null48', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
  it('eg null49', () => { const r = extractGroups(/(?<name>hello)/,'goodbye'); expect(r).toBeNull(); });
});

describe('null undef array object guards', () => {
  it('isNull null0', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef0', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr0', () => expect(isArray([0,1])).toBe(true));
  it('isObject obj0', () => expect(isObject({k:0})).toBe(true));
  it('isNull null1', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef1', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr1', () => expect(isArray([1,2])).toBe(true));
  it('isObject obj1', () => expect(isObject({k:1})).toBe(true));
  it('isNull null2', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef2', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr2', () => expect(isArray([2,3])).toBe(true));
  it('isObject obj2', () => expect(isObject({k:2})).toBe(true));
  it('isNull null3', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef3', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr3', () => expect(isArray([3,4])).toBe(true));
  it('isObject obj3', () => expect(isObject({k:3})).toBe(true));
  it('isNull null4', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef4', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr4', () => expect(isArray([4,5])).toBe(true));
  it('isObject obj4', () => expect(isObject({k:4})).toBe(true));
  it('isNull null5', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef5', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr5', () => expect(isArray([5,6])).toBe(true));
  it('isObject obj5', () => expect(isObject({k:5})).toBe(true));
  it('isNull null6', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef6', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr6', () => expect(isArray([6,7])).toBe(true));
  it('isObject obj6', () => expect(isObject({k:6})).toBe(true));
  it('isNull null7', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef7', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr7', () => expect(isArray([7,8])).toBe(true));
  it('isObject obj7', () => expect(isObject({k:7})).toBe(true));
  it('isNull null8', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef8', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr8', () => expect(isArray([8,9])).toBe(true));
  it('isObject obj8', () => expect(isObject({k:8})).toBe(true));
  it('isNull null9', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef9', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr9', () => expect(isArray([9,10])).toBe(true));
  it('isObject obj9', () => expect(isObject({k:9})).toBe(true));
  it('isNull null10', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef10', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr10', () => expect(isArray([10,11])).toBe(true));
  it('isObject obj10', () => expect(isObject({k:10})).toBe(true));
  it('isNull null11', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef11', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr11', () => expect(isArray([11,12])).toBe(true));
  it('isObject obj11', () => expect(isObject({k:11})).toBe(true));
  it('isNull null12', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef12', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr12', () => expect(isArray([12,13])).toBe(true));
  it('isObject obj12', () => expect(isObject({k:12})).toBe(true));
  it('isNull null13', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef13', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr13', () => expect(isArray([13,14])).toBe(true));
  it('isObject obj13', () => expect(isObject({k:13})).toBe(true));
  it('isNull null14', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef14', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr14', () => expect(isArray([14,15])).toBe(true));
  it('isObject obj14', () => expect(isObject({k:14})).toBe(true));
  it('isNull null15', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef15', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr15', () => expect(isArray([15,16])).toBe(true));
  it('isObject obj15', () => expect(isObject({k:15})).toBe(true));
  it('isNull null16', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef16', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr16', () => expect(isArray([16,17])).toBe(true));
  it('isObject obj16', () => expect(isObject({k:16})).toBe(true));
  it('isNull null17', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef17', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr17', () => expect(isArray([17,18])).toBe(true));
  it('isObject obj17', () => expect(isObject({k:17})).toBe(true));
  it('isNull null18', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef18', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr18', () => expect(isArray([18,19])).toBe(true));
  it('isObject obj18', () => expect(isObject({k:18})).toBe(true));
  it('isNull null19', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef19', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr19', () => expect(isArray([19,20])).toBe(true));
  it('isObject obj19', () => expect(isObject({k:19})).toBe(true));
  it('isNull null20', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef20', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr20', () => expect(isArray([20,21])).toBe(true));
  it('isObject obj20', () => expect(isObject({k:20})).toBe(true));
  it('isNull null21', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef21', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr21', () => expect(isArray([21,22])).toBe(true));
  it('isObject obj21', () => expect(isObject({k:21})).toBe(true));
  it('isNull null22', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef22', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr22', () => expect(isArray([22,23])).toBe(true));
  it('isObject obj22', () => expect(isObject({k:22})).toBe(true));
  it('isNull null23', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef23', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr23', () => expect(isArray([23,24])).toBe(true));
  it('isObject obj23', () => expect(isObject({k:23})).toBe(true));
  it('isNull null24', () => expect(isNull(null)).toBe(true));
  it('isUndefined undef24', () => expect(isUndefined(undefined)).toBe(true));
  it('isArray arr24', () => expect(isArray([24,25])).toBe(true));
  it('isObject obj24', () => expect(isObject({k:24})).toBe(true));
});

