import dotenv from 'dotenv';
dotenv.config();
const requiredEnvVars = ['JWT_SECRET'];
for (const envVar of requiredEnvVars) { if (!process.env[envVar]) { createLogger('startup').error(`FATAL: Missing required env var: ${envVar}`); process.exit(1); } }
import express, { Express, Request, Response, NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { createLogger, metricsMiddleware, metricsHandler, correlationIdMiddleware, createHealthCheck } from '@ims/monitoring';
import { attachPermissions } from '@ims/rbac';
import { sanitizeMiddleware, sanitizeQueryMiddleware } from '@ims/validation';
import { prisma } from './prisma';
const logger = createLogger('api-audits');
import auditsRouter from './routes/audits';
import findingsRouter from './routes/findings';
import checklistsRouter from './routes/checklists';
import programmesRouter from './routes/programmes';
import dashboardRouter from './routes/dashboard';
import preAuditRouter from './routes/pre-audit';
const app: Express = express();
const PORT = process.env.PORT || 4037;
app.use(helmet()); app.use(cors({ origin: true, credentials: true })); app.use(correlationIdMiddleware()); app.use(metricsMiddleware('api-audits')); app.use(express.json({ limit: '1mb' })); app.use(express.urlencoded({ extended: true })); app.use(sanitizeMiddleware()); app.use(sanitizeQueryMiddleware()); app.use(attachPermissions());
app.get('/health', createHealthCheck('api-audits', prisma, '1.0.0'));
app.get('/ready', async (_req, res) => { try { await prisma.$queryRaw`SELECT 1`; res.json({ status: 'ready' }); } catch { res.status(503).json({ status: 'not ready' }); } });
app.get('/metrics', metricsHandler);
app.use('/api/audits', auditsRouter);
app.use('/api/findings', findingsRouter);
app.use('/api/checklists', checklistsRouter);
app.use('/api/programmes', programmesRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/pre-audit', preAuditRouter);
app.use((_req: Request, res: Response) => { res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Endpoint not found' } }); });
app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => { logger.error('Unhandled error', { error: err.message, stack: err.stack }); res.status(500).json({ success: false, error: { code: 'INTERNAL_ERROR', message: 'Internal server error' } }); });
const server = app.listen(PORT, () => { logger.info(`Audits API running on port ${PORT}`); });
const gracefulShutdown = async (signal: string) => { logger.info(`${signal} received`); server.close(async () => { await prisma.$disconnect(); process.exit(0); }); setTimeout(() => { process.exit(1); }, 10000); };
process.on('SIGTERM', () => gracefulShutdown('SIGTERM')); process.on('SIGINT', () => gracefulShutdown('SIGINT'));
process.on('unhandledRejection', (reason) => { logger.error('Unhandled rejection', { reason: String(reason) }); });
process.on('uncaughtException', (error) => { logger.error('Uncaught exception', { error: error.message }); process.exit(1); });
export default app;
