// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { RegionConfig } from '../types/region-config.types';

export const au: RegionConfig = {
  countryCode: 'AU',
  countryName: 'Australia',
  region: 'ANZ',
  tier: 1,
  currency: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', decimals: 2, symbolPosition: 'before', thousandsSeparator: ',', decimalSeparator: '.' },
  dateFormat: 'DD/MM/YYYY',
  numberFormat: { thousandsSeparator: ',', decimalSeparator: '.', grouping: 3 },
  timezone: ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Brisbane', 'Australia/Perth', 'Australia/Adelaide'],
  languages: [
    { code: 'en-AU', name: 'English', isOfficial: false, isPrimary: true, script: 'Latn' },
  ],
  finance: {
    corporateTaxRate: 0.30,
    gstVatRate: 0.10,
    gstVatName: 'GST',
    gstVatRegistrationThreshold: 75000,
    witholdingTaxRates: { dividends: 0.30, interest: 0.10, royalties: 0.30, services: 0.15 },
    payrollTax: { employeeRate: 0, employerRate: 0.105, name: 'Superannuation', ceiling: undefined },
    transferPricingRules: true,
    thinCapitalisationRules: true,
    taxTreatyNetwork: ['SG', 'NZ', 'JP', 'CN', 'KR', 'IN', 'MY', 'TH', 'PH', 'ID', 'VN', 'GB', 'US', 'DE', 'FR', 'CA'],
    fiscalYearEnd: 'Jun 30',
    filingDeadlines: { corporateTax: 'Oct 31 (or Feb 28 via tax agent)', gstVat: 'Monthly/Quarterly/Annually', employeeTax: 'Oct 31' },
  },
  legislation: {
    primaryLaws: [
      {
        shortCode: 'FWA-AU', title: 'Fair Work Act 2009', jurisdiction: 'Australia', category: 'EMPLOYMENT',
        summary: 'National workplace relations framework covering employment conditions, unfair dismissal, and enterprise bargaining.',
        keyRequirements: ['National Employment Standards (NES)', 'Modern awards', 'Enterprise agreements', 'Unfair dismissal protections', 'General protections'],
        effectiveDate: '2009-07-01', lastAmended: '2023-06-01',
        officialUrl: 'https://www.legislation.gov.au/Details/C2023C00047',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'PA88-AU', title: 'Privacy Act 1988', jurisdiction: 'Australia', category: 'DATA_PRIVACY',
        summary: 'Governs the handling of personal information by Australian Government agencies and organisations with over A$3M turnover.',
        keyRequirements: ['13 Australian Privacy Principles (APPs)', 'Privacy policy', 'Data breach notification', 'Cross-border disclosure controls'],
        effectiveDate: '1988-12-14', lastAmended: '2023-12-01',
        officialUrl: 'https://www.legislation.gov.au/Details/C2023C00340',
        relatedISOStandards: ['ISO 27001:2022'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'WHSA-AU', title: 'Work Health and Safety Act 2011', jurisdiction: 'Australia', category: 'HSE',
        summary: 'Model WHS legislation adopted across most Australian jurisdictions. Imposes duties on persons conducting a business or undertaking (PCBUs).',
        keyRequirements: ['Primary duty of care', 'Worker consultation', 'Incident notification', 'Health and safety representatives', 'WHS management system'],
        effectiveDate: '2011-01-01', lastAmended: '2021-06-01',
        officialUrl: 'https://www.legislation.gov.au/Details/C2022C00062',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'CA01-AU', title: 'Corporations Act 2001', jurisdiction: 'Australia', category: 'CORPORATE',
        summary: 'Principal legislation governing companies in Australia, including incorporation, directors duties, financial reporting.',
        keyRequirements: ["Directors' duties", 'Financial reporting', 'Shareholder rights', 'Continuous disclosure (listed)', 'ASIC registration'],
        effectiveDate: '2001-07-15', lastAmended: '2023-01-01',
        officialUrl: 'https://www.legislation.gov.au/Details/C2023C00129',
        relatedISOStandards: ['ISO 37001:2016'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'MSA-AU', title: 'Modern Slavery Act 2018', jurisdiction: 'Australia', category: 'EMPLOYMENT',
        summary: 'Requires entities with annual consolidated revenue of A$100M+ to report on modern slavery risks in their operations and supply chains.',
        keyRequirements: ['Annual modern slavery statement', 'Supply chain due diligence', 'Board approval of statement', 'Public register submission'],
        effectiveDate: '2019-01-01', lastAmended: '2023-01-01',
        officialUrl: 'https://www.legislation.gov.au/Details/C2018A00153',
        relatedISOStandards: ['ISO 37001:2016'], isMandatory: true, applicableTo: ['all'],
      },
    ],
    regulatoryBodies: [
      { name: 'Fair Work Commission', acronym: 'FWC', website: 'https://www.fwc.gov.au', jurisdiction: ['EMPLOYMENT'] },
      { name: 'Office of the Australian Information Commissioner', acronym: 'OAIC', website: 'https://www.oaic.gov.au', jurisdiction: ['DATA_PRIVACY'] },
      { name: 'Safe Work Australia', acronym: 'SWA', website: 'https://www.safeworkaustralia.gov.au', jurisdiction: ['HSE'] },
      { name: 'Australian Securities and Investments Commission', acronym: 'ASIC', website: 'https://www.asic.gov.au', jurisdiction: ['CORPORATE', 'FINANCIAL'] },
      { name: 'Australian Competition and Consumer Commission', acronym: 'ACCC', website: 'https://www.accc.gov.au', jurisdiction: ['CONSUMER'] },
    ],
    reportingRequirements: ['ASIC annual company statement', 'ATO tax returns', 'Modern slavery statement (>A$100M)', 'APRA reporting (financial sector)', 'ASX continuous disclosure (listed)'],
    auditRequirements: 'Mandatory for public companies and large proprietary companies (>A$50M revenue or >100 employees)',
  },
  isoContext: {
    adoptedStandards: [
      { standard: 'ISO 9001:2015', localStandard: 'AS/NZS ISO 9001:2016', adoptionStatus: 'ADOPTED', certificationBodies: ['SAI Global', 'Bureau Veritas', 'SGS', 'BSI'], notes: 'Widely used across government and defence procurement' },
      { standard: 'ISO 14001:2015', localStandard: 'AS/NZS ISO 14001:2016', adoptionStatus: 'ADOPTED', certificationBodies: ['SAI Global', 'Bureau Veritas', 'SGS'], notes: 'Growing adoption driven by ESG reporting requirements' },
      { standard: 'ISO 45001:2018', localStandard: 'AS/NZS ISO 45001:2019', adoptionStatus: 'ADOPTED', certificationBodies: ['SAI Global', 'Bureau Veritas', 'BSI'], mandatoryForSectors: ['construction', 'manufacturing'], notes: 'Aligned with model WHS legislation' },
      { standard: 'ISO 27001:2022', adoptionStatus: 'ADOPTED', certificationBodies: ['SAI Global', 'BSI', 'Bureau Veritas'], mandatoryForSectors: ['financial'], notes: 'Aligned with APRA CPS 234 information security standard' },
      { standard: 'ISO 37001:2016', adoptionStatus: 'ADOPTED', certificationBodies: ['BSI', 'Bureau Veritas', 'SGS'], notes: 'Increasingly adopted by ASX-listed companies' },
    ],
    certificationBodies: ['SAI Global', 'Bureau Veritas', 'SGS', 'BSI Group', 'DNV GL', 'Lloyd\'s Register', 'Intertek'],
    accreditationBody: 'Joint Accreditation System of Australia and New Zealand (JAS-ANZ)',
    notes: 'Australia uses AS/NZS joint standards with New Zealand. JAS-ANZ accredits certification bodies across both countries.',
  },
  compliance: {
    mandatoryReporting: ['ASIC annual return', 'ATO tax lodgements', 'Modern slavery statement (>A$100M revenue)', 'APRA reporting (banks/insurers)', 'WorkSafe incident notifications'],
    esgRequirements: 'ASX Corporate Governance Principles require listed companies to disclose ESG risks. TCFD aligned climate disclosures becoming mandatory for large entities.',
    sustainabilityFrameworks: ['GRI Standards', 'TCFD', 'SASB', 'SDGs', 'ASX CGC Principles'],
    dataProtectionAuthority: 'Office of the Australian Information Commissioner (OAIC)',
    dataRetentionYears: 7,
    crossBorderDataTransfer: 'Requires comparable protection under APP 8; notifiable data breach scheme applies',
    whistleblowerProtection: true,
    modernSlaveryAct: true,
    dueDiligenceRequirements: 'Modern Slavery Act 2018 requires supply chain due diligence reporting for entities >A$100M revenue',
  },
  business: {
    companyTypes: ['Proprietary Limited (Pty Ltd)', 'Public Company (Ltd)', 'Sole Trader', 'Partnership', 'Trust', 'Branch Office'],
    minShareCapital: 1,
    incorporationTime: '1-2 business days',
    businessRegistrationBody: 'Australian Securities and Investments Commission (ASIC)',
    easeOfDoingBusinessRank: 14,
    freeTradeZones: ['Darwin Business Park FTZ', 'Port of Darwin FTZ'],
    importDutyFramework: 'Generally 0-5% tariff. ASEAN-Australia-NZ FTA provides preferential rates. GST applies to imports >A$1,000.',
    exportControls: ['Defence Export Controls', 'Autonomous Sanctions Act 2011', 'Charter of the United Nations Act 1945'],
    ipProtectionRating: 'Very High — WIPO rankings consistently high',
    corruptionPerceptionsIndex: 75,
  },
};
