// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { RegionConfig } from '../types/region-config.types';

export const jp: RegionConfig = {
  countryCode: 'JP',
  countryName: 'Japan',
  region: 'EAST_ASIA',
  tier: 2,
  currency: { code: 'JPY', symbol: '¥', name: 'Japanese Yen', decimals: 0, symbolPosition: 'before', thousandsSeparator: ',', decimalSeparator: '.' },
  dateFormat: 'YYYY/MM/DD',
  numberFormat: { thousandsSeparator: ',', decimalSeparator: '.', grouping: 3 },
  timezone: ['Asia/Tokyo'],
  languages: [
    { code: 'ja', name: 'Japanese', isOfficial: true, isPrimary: true, script: 'Jpan' },
  ],
  finance: {
    corporateTaxRate: 0.232,
    gstVatRate: 0.10,
    gstVatName: 'Consumption Tax',
    gstVatRegistrationThreshold: 10000000,
    witholdingTaxRates: { dividends: 0.20, interest: 0.20, royalties: 0.20, services: 0.20 },
    payrollTax: { employeeRate: 0.149, employerRate: 0.157, name: 'Shakai Hoken (Social Insurance)', ceiling: undefined },
    transferPricingRules: true,
    thinCapitalisationRules: true,
    taxTreatyNetwork: ['SG', 'AU', 'NZ', 'CN', 'KR', 'IN', 'MY', 'TH', 'PH', 'ID', 'VN', 'GB', 'US', 'DE', 'FR', 'CA'],
    fiscalYearEnd: 'Mar 31',
    filingDeadlines: { corporateTax: '2 months after fiscal year end', gstVat: '2 months after fiscal year end', employeeTax: 'Jan 31' },
  },
  legislation: {
    primaryLaws: [
      {
        shortCode: 'LSA-JP', title: 'Labour Standards Act (労働基準法)', jurisdiction: 'Japan', category: 'EMPLOYMENT',
        summary: 'Primary labour law setting minimum working conditions including working hours, wages, and leave.',
        keyRequirements: ['Written employment contracts', '8-hour workday / 40-hour week', 'Overtime caps', 'Annual paid leave (minimum 10 days)', '36 Agreement for overtime'],
        effectiveDate: '1947-04-07', lastAmended: '2023-04-01',
        officialUrl: 'https://www.mhlw.go.jp',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'APPI-JP', title: 'Act on Protection of Personal Information (個人情報保護法)', jurisdiction: 'Japan', category: 'DATA_PRIVACY',
        summary: 'Comprehensive personal information protection law applicable to all business operators handling personal data.',
        keyRequirements: ['Lawful use of personal information', 'Third-party provision restrictions', 'Data breach notification (3 days to PPC)', 'Data subject rights', 'Overseas transfer restrictions'],
        effectiveDate: '2005-04-01', lastAmended: '2022-04-01',
        officialUrl: 'https://www.ppc.go.jp',
        relatedISOStandards: ['ISO 27001:2022'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'ISHA-JP', title: 'Industrial Safety and Health Act (労働安全衛生法)', jurisdiction: 'Japan', category: 'HSE',
        summary: 'Establishes framework for occupational safety and health management.',
        keyRequirements: ['Safety manager appointment', 'Risk assessment', 'Occupational physician (>50 employees)', 'Regular health checkups', 'Incident reporting to Labour Standards Inspection Office'],
        effectiveDate: '1972-06-08', lastAmended: '2023-01-01',
        officialUrl: 'https://www.mhlw.go.jp',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'AEL-JP', title: 'Act on Promotion of Global Warming Countermeasures (地球温暖化対策推進法)', jurisdiction: 'Japan', category: 'ENVIRONMENT',
        summary: 'Requires GHG emission reporting and promotes countermeasures.',
        keyRequirements: ['Annual GHG emission reporting (>3,000 tonnes CO2e)', 'Energy consumption reporting', 'Emission reduction targets'],
        effectiveDate: '1998-10-09', lastAmended: '2022-04-01',
        officialUrl: 'https://www.env.go.jp',
        relatedISOStandards: ['ISO 14001:2015', 'ISO 50001:2018'], isMandatory: true, applicableTo: ['manufacturing', 'retail'],
      },
      {
        shortCode: 'UFC-JP', title: 'Unfair Competition Prevention Act (不正競争防止法)', jurisdiction: 'Japan', category: 'TRADE',
        summary: 'Prevents unfair competition including trade secret misappropriation and misleading representations.',
        keyRequirements: ['Trade secret protection', 'Prohibition of misleading representations', 'Domain name protection'],
        effectiveDate: '1993-05-19', lastAmended: '2023-06-01',
        officialUrl: 'https://www.meti.go.jp',
        relatedISOStandards: [], isMandatory: true, applicableTo: ['all'],
      },
    ],
    regulatoryBodies: [
      { name: 'Ministry of Health, Labour and Welfare', acronym: 'MHLW', website: 'https://www.mhlw.go.jp', jurisdiction: ['EMPLOYMENT', 'HSE'] },
      { name: 'Personal Information Protection Commission', acronym: 'PPC', website: 'https://www.ppc.go.jp', jurisdiction: ['DATA_PRIVACY'] },
      { name: 'Ministry of the Environment', acronym: 'MOE', website: 'https://www.env.go.jp', jurisdiction: ['ENVIRONMENT'] },
      { name: 'Financial Services Agency', acronym: 'FSA', website: 'https://www.fsa.go.jp', jurisdiction: ['FINANCIAL', 'CORPORATE'] },
    ],
    reportingRequirements: ['Annual corporate filing with Legal Affairs Bureau', 'NTA tax returns', 'Tokyo Stock Exchange (TSE) disclosures (listed)', 'FSA financial sector reports', 'MOE GHG emission reports'],
    auditRequirements: 'Mandatory for large companies (>1,000 employees or >JPY 5B paid-in capital or assets >JPY 20B)',
  },
  isoContext: {
    adoptedStandards: [
      { standard: 'ISO 9001:2015', localStandard: 'JIS Q 9001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['JACO', 'JQA', 'Bureau Veritas', 'SGS', 'TÜV Rheinland'], notes: 'Japan has the world\'s largest number of ISO 9001 certificates' },
      { standard: 'ISO 14001:2015', localStandard: 'JIS Q 14001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['JACO', 'JQA', 'Bureau Veritas', 'SGS'], notes: 'Japan has the world\'s second largest number of ISO 14001 certificates' },
      { standard: 'ISO 45001:2018', localStandard: 'JIS Q 45001:2018', adoptionStatus: 'ADOPTED', certificationBodies: ['JACO', 'JQA', 'Bureau Veritas', 'BSI'], notes: 'Aligned with Industrial Safety and Health Act' },
      { standard: 'ISO 27001:2022', localStandard: 'JIS Q 27001:2023', adoptionStatus: 'ADOPTED', certificationBodies: ['ISMS-AC', 'JACO', 'Bureau Veritas', 'BSI'], mandatoryForSectors: ['financial'], notes: 'ISMS-AC is the dedicated ISMS accreditation body in Japan' },
      { standard: 'ISO 50001:2018', localStandard: 'JIS Q 50001:2019', adoptionStatus: 'ADOPTED', certificationBodies: ['JACO', 'Bureau Veritas', 'TÜV Rheinland'], notes: 'Growing adoption driven by Act on Rational Use of Energy' },
    ],
    certificationBodies: ['JACO (Japan Accredited Bodies)', 'JQA (Japan Quality Assurance Organization)', 'Bureau Veritas Japan', 'SGS Japan', 'TÜV Rheinland Japan', 'BSI Japan'],
    accreditationBody: 'Japan Accreditation Board (JAB)',
    notes: 'Japan has one of the highest ISO certification concentrations globally. JAB is the national accreditation body. JIS (Japan Industrial Standards) adopt ISO standards.',
  },
  compliance: {
    mandatoryReporting: ['Legal Affairs Bureau annual filing', 'NTA corporate tax return', 'TSE continuous disclosure (listed)', 'FSA financial reports', 'MOE/METI GHG reports (>3,000t CO2e)'],
    esgRequirements: 'TSE Prime Market listed companies must comply with Japan Stewardship Code and Corporate Governance Code. TCFD-aligned climate disclosure mandatory for TSE Prime.',
    sustainabilityFrameworks: ['GRI Standards', 'TCFD', 'IIRC', 'Japan\'s Corporate Governance Code', 'SDGs'],
    dataProtectionAuthority: 'Personal Information Protection Commission (PPC)',
    dataRetentionYears: 7,
    crossBorderDataTransfer: 'Permitted to countries with equivalent level of protection; PPC maintains approved country list',
    whistleblowerProtection: true,
    modernSlaveryAct: false,
    dueDiligenceRequirements: 'Japan Guidelines on Responsible Business Conduct based on OECD/UNGPs; not yet mandatory but strong government push',
  },
  business: {
    companyTypes: ['Kabushiki-Kaisha (KK)', 'Godo-Kaisha (GK)', 'Goshi-Kaisha', 'Gomei-Kaisha', 'Branch Office', 'Representative Office'],
    minShareCapital: 1,
    incorporationTime: '7-14 business days',
    businessRegistrationBody: 'Legal Affairs Bureau (Ministry of Justice)',
    easeOfDoingBusinessRank: 29,
    freeTradeZones: ['National Strategic Special Zones (NSSZ)', 'Abenomics Special Economic Zones'],
    importDutyFramework: 'Varied tariff rates. EPA/FTA preferential rates with many partners. TPP-11/CPTPP provides preferential rates.',
    exportControls: ['Foreign Exchange and Foreign Trade Act (FEFTA)', 'Export Trade Control Order'],
    ipProtectionRating: 'Very High — JPO provides strong protection; Japan consistently ranked in top 5 globally',
    corruptionPerceptionsIndex: 73,
  },
};
