// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { RegionConfig } from '../types/region-config.types';

export const kr: RegionConfig = {
  countryCode: 'KR',
  countryName: 'South Korea',
  region: 'EAST_ASIA',
  tier: 2,
  currency: { code: 'KRW', symbol: '₩', name: 'South Korean Won', decimals: 0, symbolPosition: 'before', thousandsSeparator: ',', decimalSeparator: '.' },
  dateFormat: 'YYYY.MM.DD',
  numberFormat: { thousandsSeparator: ',', decimalSeparator: '.', grouping: 3 },
  timezone: ['Asia/Seoul'],
  languages: [
    { code: 'ko', name: 'Korean', isOfficial: true, isPrimary: true, script: 'Hang' },
  ],
  finance: {
    corporateTaxRate: 0.22,
    corporateTaxBands: [
      { min: 0, max: 200000000, rate: 0.09, label: 'Up to KRW 200M' },
      { min: 200000000, max: 20000000000, rate: 0.19, label: 'KRW 200M to 20B' },
      { min: 20000000000, max: 300000000000, rate: 0.21, label: 'KRW 20B to 300B' },
      { min: 300000000000, rate: 0.24, label: 'Over KRW 300B' },
    ],
    gstVatRate: 0.10,
    gstVatName: 'VAT',
    gstVatRegistrationThreshold: 0,
    witholdingTaxRates: { dividends: 0.22, interest: 0.22, royalties: 0.22, services: 0.22 },
    payrollTax: { employeeRate: 0.0905, employerRate: 0.0965, name: '4대보험 (4 Major Insurances)', ceiling: undefined },
    transferPricingRules: true,
    thinCapitalisationRules: true,
    taxTreatyNetwork: ['SG', 'AU', 'NZ', 'JP', 'CN', 'IN', 'MY', 'TH', 'PH', 'ID', 'VN', 'GB', 'US', 'DE', 'FR', 'CA'],
    fiscalYearEnd: 'Dec 31',
    filingDeadlines: { corporateTax: 'Mar 31 (3 months after year end)', gstVat: 'Jan 25 / Jul 25 (semi-annual)', employeeTax: 'Mar 10' },
  },
  legislation: {
    primaryLaws: [
      {
        shortCode: 'LSA-KR', title: 'Labor Standards Act (근로기준법)', jurisdiction: 'South Korea', category: 'EMPLOYMENT',
        summary: 'Primary labour legislation covering working conditions, wages, hours, and dismissal.',
        keyRequirements: ['Employment contracts', '52-hour work week limit', 'Minimum wage compliance', 'Annual paid leave (15 days minimum)', 'Severance pay (1 month per year)'],
        effectiveDate: '1953-05-10', lastAmended: '2021-05-18',
        officialUrl: 'https://www.moel.go.kr',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'PIPA-KR', title: 'Personal Information Protection Act (개인정보보호법)', jurisdiction: 'South Korea', category: 'DATA_PRIVACY',
        summary: 'Comprehensive personal information protection law, one of the strictest in Asia.',
        keyRequirements: ['Lawful basis for collection', 'Sensitive information extra protection', 'Breach notification within 72 hours', 'Privacy impact assessment', 'CPO appointment', 'Destruction of data after purpose fulfilled'],
        effectiveDate: '2011-09-30', lastAmended: '2023-09-15',
        officialUrl: 'https://www.pipc.go.kr',
        relatedISOStandards: ['ISO 27001:2022'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'OSHA-KR', title: 'Occupational Safety and Health Act (산업안전보건법)', jurisdiction: 'South Korea', category: 'HSE',
        summary: 'Comprehensive OSH legislation revised in 2020 with expanded corporate liability.',
        keyRequirements: ['Safety and health management system', 'Risk assessment', 'Safety officer appointment', 'Incident reporting to MOEL', 'CEO liability for serious accidents'],
        effectiveDate: '1981-12-31', lastAmended: '2023-01-26',
        officialUrl: 'https://www.moel.go.kr',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'EPA-KR', title: 'Environmental Policy Basic Act (환경정책기본법)', jurisdiction: 'South Korea', category: 'ENVIRONMENT',
        summary: 'Framework legislation for comprehensive environmental policy and management.',
        keyRequirements: ['Environmental impact assessment', 'Pollutant monitoring', 'GHG target management', 'Environmental liability'],
        effectiveDate: '1990-08-01', lastAmended: '2023-01-01',
        officialUrl: 'https://www.me.go.kr',
        relatedISOStandards: ['ISO 14001:2015'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'ACCA-KR', title: 'Anti-Corruption and Civil Rights Commission Act (부패방지 및 국민권익위원회의 설치와 운영에 관한 법률)', jurisdiction: 'South Korea', category: 'ANTI_CORRUPTION',
        summary: 'Establishes anti-corruption framework and ACRC oversight.',
        keyRequirements: ['Anti-corruption education', 'Integrity pact', 'Conflict of interest disclosure', 'Whistleblower protection'],
        effectiveDate: '2008-02-29', lastAmended: '2022-01-01',
        officialUrl: 'https://www.acrc.go.kr',
        relatedISOStandards: ['ISO 37001:2016'], isMandatory: false, applicableTo: ['all'],
      },
    ],
    regulatoryBodies: [
      { name: 'Ministry of Employment and Labor', acronym: 'MOEL', website: 'https://www.moel.go.kr', jurisdiction: ['EMPLOYMENT', 'HSE'] },
      { name: 'Personal Information Protection Commission', acronym: 'PIPC', website: 'https://www.pipc.go.kr', jurisdiction: ['DATA_PRIVACY'] },
      { name: 'Ministry of Environment', acronym: 'MOE-KR', website: 'https://www.me.go.kr', jurisdiction: ['ENVIRONMENT'] },
      { name: 'Financial Services Commission', acronym: 'FSC', website: 'https://www.fsc.go.kr', jurisdiction: ['FINANCIAL', 'CORPORATE'] },
    ],
    reportingRequirements: ['DART annual report (listed)', 'NTS tax returns', 'MOE GHG target management reports', 'FSC financial sector reports', 'MOEL accident reports'],
    auditRequirements: 'Mandatory for large corporations (>KRW 10B assets) and listed companies',
  },
  isoContext: {
    adoptedStandards: [
      { standard: 'ISO 9001:2015', localStandard: 'KS Q ISO 9001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['KSA', 'Bureau Veritas', 'SGS', 'TÜV Rheinland'], notes: 'Strong adoption in automotive and electronics sectors' },
      { standard: 'ISO 14001:2015', localStandard: 'KS Q ISO 14001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['KSA', 'Bureau Veritas', 'SGS'], notes: 'Required for large emitters under GHG ETS' },
      { standard: 'ISO 45001:2018', localStandard: 'KS Q ISO 45001:2019', adoptionStatus: 'ADOPTED', certificationBodies: ['KSA', 'Bureau Veritas', 'BSI'], notes: 'Strongly recommended post-Serious Accident Punishment Act' },
      { standard: 'ISO 27001:2022', localStandard: 'KS X ISO/IEC 27001:2022', adoptionStatus: 'ADOPTED', certificationBodies: ['KISA', 'BSI', 'Bureau Veritas'], mandatoryForSectors: ['financial'], notes: 'Aligned with PIPA requirements' },
    ],
    certificationBodies: ['KSA (Korean Standards Association)', 'Bureau Veritas Korea', 'SGS Korea', 'TÜV Rheinland Korea', 'BSI Korea', 'KISA'],
    accreditationBody: 'Korea Accreditation Board (KAB)',
    notes: 'Korea uses KS (Korean Standards) which adopt ISO standards. KAB is the national accreditation body. Strong government push for ISO adoption.',
  },
  compliance: {
    mandatoryReporting: ['DART annual business report', 'NTS corporate tax return', 'MOE GHG emissions (ETS participants)', 'FSC financial sector filings', 'MOEL accident reporting'],
    esgRequirements: 'KRX-listed companies required to publish ESG information. K-ESG Guidelines issued by Ministry of Economy and Finance. Carbon ETS mandatory for large emitters.',
    sustainabilityFrameworks: ['GRI Standards', 'K-ESG Guidelines', 'TCFD', 'Korean Green New Deal'],
    dataProtectionAuthority: 'Personal Information Protection Commission (PIPC)',
    dataRetentionYears: 5,
    crossBorderDataTransfer: 'Restricted; PIPC approval required for overseas transfers; adequacy decisions for select countries',
    whistleblowerProtection: true,
    modernSlaveryAct: false,
    dueDiligenceRequirements: 'No mandatory human rights due diligence; National Action Plan on Business and Human Rights (2018) encourages voluntary compliance',
  },
  business: {
    companyTypes: ['주식회사 (Jusik-hoesa / Corporation)', '유한회사 (Yuhan-hoesa / LLC)', '합자회사 (Partnership)', 'Branch Office', 'Liaison Office'],
    minShareCapital: 100000000,
    incorporationTime: '3-5 business days',
    businessRegistrationBody: 'Court Registry Office (등기소) / Small Business Support Center',
    easeOfDoingBusinessRank: 5,
    freeTradeZones: ['Incheon Free Economic Zone', 'Busan-Jinhae Free Economic Zone', 'Gwangyang Bay Area FEZ', 'Yellow Sea FEZ'],
    importDutyFramework: 'Varied tariff rates. KORUS FTA, ASEAN FTA, EU-Korea FTA provide preferential rates.',
    exportControls: ['Foreign Trade Act', 'Strategic Materials Export Controls'],
    ipProtectionRating: 'Very High — KIPO provides strong protection',
    corruptionPerceptionsIndex: 63,
  },
};
