// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { RegionConfig } from '../types/region-config.types';

export const nz: RegionConfig = {
  countryCode: 'NZ',
  countryName: 'New Zealand',
  region: 'ANZ',
  tier: 1,
  currency: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', decimals: 2, symbolPosition: 'before', thousandsSeparator: ',', decimalSeparator: '.' },
  dateFormat: 'DD/MM/YYYY',
  numberFormat: { thousandsSeparator: ',', decimalSeparator: '.', grouping: 3 },
  timezone: ['Pacific/Auckland', 'Pacific/Chatham'],
  languages: [
    { code: 'en-NZ', name: 'English', isOfficial: true, isPrimary: true, script: 'Latn' },
    { code: 'mi', name: 'Māori', isOfficial: true, isPrimary: false, script: 'Latn' },
    { code: 'nzsl', name: 'New Zealand Sign Language', isOfficial: true, isPrimary: false },
  ],
  finance: {
    corporateTaxRate: 0.28,
    gstVatRate: 0.15,
    gstVatName: 'GST',
    gstVatRegistrationThreshold: 60000,
    witholdingTaxRates: { dividends: 0.15, interest: 0.15, royalties: 0.15, services: 0.15 },
    payrollTax: { employeeRate: 0.03, employerRate: 0.03, name: 'KiwiSaver', ceiling: undefined },
    transferPricingRules: true,
    thinCapitalisationRules: true,
    taxTreatyNetwork: ['AU', 'SG', 'JP', 'CN', 'IN', 'MY', 'UK', 'US', 'CA', 'DE', 'FR'],
    fiscalYearEnd: 'Mar 31',
    filingDeadlines: { corporateTax: 'Jul 7 (or Apr 30 via tax agent)', gstVat: 'Monthly/Bi-monthly/6-monthly', employeeTax: 'Jul 7' },
  },
  legislation: {
    primaryLaws: [
      {
        shortCode: 'ERA-NZ', title: 'Employment Relations Act 2000', jurisdiction: 'New Zealand', category: 'EMPLOYMENT',
        summary: 'Provides statutory framework for employment relationships, collective bargaining, and personal grievances.',
        keyRequirements: ['Good faith obligations', 'Individual employment agreements', 'Collective bargaining', 'Personal grievance process'],
        effectiveDate: '2000-10-02', lastAmended: '2022-12-01',
        officialUrl: 'https://www.legislation.govt.nz/act/public/2000/0024/latest/whole.html',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'PA20-NZ', title: 'Privacy Act 2020', jurisdiction: 'New Zealand', category: 'DATA_PRIVACY',
        summary: 'Governs the collection, use, and disclosure of personal information in New Zealand.',
        keyRequirements: ['13 information privacy principles', 'Privacy impact assessments', 'Mandatory breach notification', 'Privacy Officer appointment'],
        effectiveDate: '2020-12-01', lastAmended: '2020-12-01',
        officialUrl: 'https://www.legislation.govt.nz/act/public/2020/0031/latest/whole.html',
        relatedISOStandards: ['ISO 27001:2022'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'HSWA-NZ', title: 'Health and Safety at Work Act 2015', jurisdiction: 'New Zealand', category: 'HSE',
        summary: 'Primary health and safety legislation modelled on Australian model WHS laws. Imposes duties on persons conducting a business or undertaking.',
        keyRequirements: ['Primary duty of care', 'Worker participation', 'Notifiable events', 'Health and safety representatives', 'Management of risks'],
        effectiveDate: '2016-04-04', lastAmended: '2021-06-01',
        officialUrl: 'https://www.legislation.govt.nz/act/public/2015/0070/latest/whole.html',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'RMA-NZ', title: 'Resource Management Act 1991', jurisdiction: 'New Zealand', category: 'ENVIRONMENT',
        summary: 'Controls the use of natural and physical resources to promote sustainable management.',
        keyRequirements: ['Resource consent requirements', 'Environmental impact assessment', 'Emissions monitoring', 'Māori consultation'],
        effectiveDate: '1991-10-01', lastAmended: '2023-01-01',
        officialUrl: 'https://www.legislation.govt.nz/act/public/1991/0069/latest/whole.html',
        relatedISOStandards: ['ISO 14001:2015'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'CA93-NZ', title: 'Companies Act 1993', jurisdiction: 'New Zealand', category: 'CORPORATE',
        summary: 'Governs the incorporation, operation, and winding up of companies in New Zealand.',
        keyRequirements: ['Director duties', 'Financial reporting', 'Shareholder rights', 'Companies Office registration'],
        effectiveDate: '1993-07-01', lastAmended: '2023-01-01',
        officialUrl: 'https://www.legislation.govt.nz/act/public/1993/0105/latest/whole.html',
        relatedISOStandards: [], isMandatory: true, applicableTo: ['all'],
      },
    ],
    regulatoryBodies: [
      { name: 'WorkSafe New Zealand', acronym: 'WorkSafe', website: 'https://www.worksafe.govt.nz', jurisdiction: ['HSE'] },
      { name: 'Office of the Privacy Commissioner', acronym: 'OPC', website: 'https://www.privacy.org.nz', jurisdiction: ['DATA_PRIVACY'] },
      { name: 'Ministry of Business, Innovation and Employment', acronym: 'MBIE', website: 'https://www.mbie.govt.nz', jurisdiction: ['EMPLOYMENT', 'CORPORATE'] },
      { name: 'Environmental Protection Authority', acronym: 'EPA', website: 'https://www.epa.govt.nz', jurisdiction: ['ENVIRONMENT'] },
    ],
    reportingRequirements: ['Companies Office annual return', 'IRD tax filings', 'WorkSafe notifiable events', 'Privacy Commissioner breach notifications'],
    auditRequirements: 'Mandatory for large companies (>NZ$30M total assets or >NZ$15M revenue or >100 employees)',
  },
  isoContext: {
    adoptedStandards: [
      { standard: 'ISO 9001:2015', localStandard: 'AS/NZS ISO 9001:2016', adoptionStatus: 'ADOPTED', certificationBodies: ['SAI Global', 'Bureau Veritas', 'SGS', 'BSI'], notes: 'Joint standard with Australia' },
      { standard: 'ISO 14001:2015', localStandard: 'AS/NZS ISO 14001:2016', adoptionStatus: 'ADOPTED', certificationBodies: ['SAI Global', 'Bureau Veritas', 'SGS'], notes: 'Commonly adopted in primary industries' },
      { standard: 'ISO 45001:2018', localStandard: 'AS/NZS ISO 45001:2019', adoptionStatus: 'ADOPTED', certificationBodies: ['SAI Global', 'Bureau Veritas', 'BSI'], notes: 'Aligned with HSWA 2015' },
      { standard: 'ISO 27001:2022', adoptionStatus: 'ADOPTED', certificationBodies: ['BSI', 'Bureau Veritas'], notes: 'Growing adoption in financial and government sectors' },
    ],
    certificationBodies: ['SAI Global', 'Bureau Veritas', 'SGS', 'BSI Group', 'Lloyd\'s Register', 'Intertek'],
    accreditationBody: 'Joint Accreditation System of Australia and New Zealand (JAS-ANZ)',
    notes: 'New Zealand uses joint AS/NZS standards with Australia. JAS-ANZ covers both countries.',
  },
  compliance: {
    mandatoryReporting: ['Companies Office annual return', 'IRD tax filings', 'WorkSafe notifiable events', 'Reserve Bank reporting (financial sector)'],
    esgRequirements: 'NZX-listed companies required to publish climate-related disclosures aligned to TCFD from 2023. Climate-related Disclosures Act 2021 applies to large entities.',
    sustainabilityFrameworks: ['GRI Standards', 'TCFD', 'SDGs', 'He Ara Waiora wellbeing framework'],
    dataProtectionAuthority: 'Office of the Privacy Commissioner (OPC)',
    dataRetentionYears: 7,
    crossBorderDataTransfer: 'Permitted to countries with comparable privacy laws; principle 12 governs transfers',
    whistleblowerProtection: true,
    modernSlaveryAct: false,
    dueDiligenceRequirements: 'No mandatory modern slavery legislation; voluntary guidance from MBIE',
  },
  business: {
    companyTypes: ['Limited Liability Company (Ltd)', 'Unlimited Company', 'Sole Trader', 'Partnership', 'Limited Partnership', 'Overseas Company'],
    minShareCapital: 1,
    incorporationTime: '1 business day',
    businessRegistrationBody: 'Companies Office (Ministry of Business, Innovation and Employment)',
    easeOfDoingBusinessRank: 1,
    freeTradeZones: [],
    importDutyFramework: 'Low tariff regime; 0% on most goods from FTA partners. GST applies to all imports.',
    exportControls: ['Strategic Goods Act 2003', 'United Nations sanctions'],
    ipProtectionRating: 'High — strong IP framework',
    corruptionPerceptionsIndex: 87,
  },
};
