// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { RegionConfig } from '../types/region-config.types';

export const ph: RegionConfig = {
  countryCode: 'PH',
  countryName: 'Philippines',
  region: 'ASEAN',
  tier: 1,
  currency: { code: 'PHP', symbol: '₱', name: 'Philippine Peso', decimals: 2, symbolPosition: 'before', thousandsSeparator: ',', decimalSeparator: '.' },
  dateFormat: 'MM/DD/YYYY',
  numberFormat: { thousandsSeparator: ',', decimalSeparator: '.', grouping: 3 },
  timezone: ['Asia/Manila'],
  languages: [
    { code: 'fil', name: 'Filipino (Tagalog)', isOfficial: true, isPrimary: true, script: 'Latn' },
    { code: 'en-PH', name: 'English', isOfficial: true, isPrimary: false, script: 'Latn' },
  ],
  finance: {
    corporateTaxRate: 0.25,
    gstVatRate: 0.12,
    gstVatName: 'VAT',
    gstVatRegistrationThreshold: 3000000,
    witholdingTaxRates: { dividends: 0.25, interest: 0.20, royalties: 0.20, services: 0.02 },
    payrollTax: { employeeRate: 0.045, employerRate: 0.085, name: 'SSS/PhilHealth/Pag-IBIG', ceiling: undefined },
    transferPricingRules: true,
    thinCapitalisationRules: false,
    taxTreatyNetwork: ['SG', 'AU', 'NZ', 'JP', 'CN', 'KR', 'IN', 'MY', 'TH', 'ID', 'VN', 'GB', 'US', 'DE'],
    fiscalYearEnd: 'Dec 31',
    filingDeadlines: { corporateTax: 'Apr 15 (annual); 60 days after quarter', gstVat: 'Monthly (20th)', employeeTax: 'Apr 15' },
  },
  legislation: {
    primaryLaws: [
      {
        shortCode: 'LC-PH', title: 'Labor Code of the Philippines (P.D. 442)', jurisdiction: 'Philippines', category: 'EMPLOYMENT',
        summary: 'Comprehensive labour legislation governing employment, wages, working conditions, and labour relations.',
        keyRequirements: ['Employment contracts', 'Minimum wage', '8-hour workday', '13th month pay', 'Separation pay', 'Maternity leave'],
        effectiveDate: '1974-05-01', lastAmended: '2023-01-01',
        officialUrl: 'https://www.dole.gov.ph',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'DPA12-PH', title: 'Data Privacy Act of 2012 (R.A. 10173)', jurisdiction: 'Philippines', category: 'DATA_PRIVACY',
        summary: 'Protects individual personal information in government and private sector information and communications systems.',
        keyRequirements: ['Data Privacy Principles', 'Privacy notice', 'Data Protection Officer (DPO)', 'Breach notification (72 hours)', 'NPC registration'],
        effectiveDate: '2012-08-15', lastAmended: '2016-09-09',
        officialUrl: 'https://www.privacy.gov.ph',
        relatedISOStandards: ['ISO 27001:2022'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'OSH-PH', title: 'Occupational Safety and Health Standards (R.A. 11058)', jurisdiction: 'Philippines', category: 'HSE',
        summary: 'Strengthened OSH law ensuring safe and healthy working conditions.',
        keyRequirements: ['Safety officer (1 per 200 employees)', 'Safety committee', 'OSH program', 'Incident reporting to DOLE', 'Annual medical examinations'],
        effectiveDate: '2018-08-17', lastAmended: '2019-01-01',
        officialUrl: 'https://oshc.dole.gov.ph',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'CA-PH', title: 'Clean Air Act of 1999 (R.A. 8749)', jurisdiction: 'Philippines', category: 'ENVIRONMENT',
        summary: 'Promotes clean air through pollution control and reduction.',
        keyRequirements: ['Emission standards compliance', 'Air quality monitoring', 'Pollution control officer', 'EIA for major projects'],
        effectiveDate: '1999-06-23', lastAmended: '2022-01-01',
        officialUrl: 'https://www.denr.gov.ph',
        relatedISOStandards: ['ISO 14001:2015'], isMandatory: true, applicableTo: ['manufacturing', 'construction'] ,
      },
      {
        shortCode: 'AMLA-PH', title: 'Anti-Money Laundering Act (R.A. 9160 as amended)', jurisdiction: 'Philippines', category: 'FINANCIAL',
        summary: 'Prevents money laundering and financing of terrorism in the Philippine financial system.',
        keyRequirements: ['Customer due diligence', 'Suspicious transaction reporting', 'Record keeping', 'Compliance program', 'AMLC registration'],
        effectiveDate: '2001-10-17', lastAmended: '2021-01-01',
        officialUrl: 'https://www.amlc.gov.ph',
        relatedISOStandards: [], isMandatory: true, applicableTo: ['financial'],
      },
    ],
    regulatoryBodies: [
      { name: 'Department of Labor and Employment', acronym: 'DOLE', website: 'https://www.dole.gov.ph', jurisdiction: ['EMPLOYMENT', 'HSE'] },
      { name: 'National Privacy Commission', acronym: 'NPC', website: 'https://www.privacy.gov.ph', jurisdiction: ['DATA_PRIVACY'] },
      { name: 'Department of Environment and Natural Resources', acronym: 'DENR', website: 'https://www.denr.gov.ph', jurisdiction: ['ENVIRONMENT'] },
      { name: 'Securities and Exchange Commission', acronym: 'SEC-PH', website: 'https://www.sec.gov.ph', jurisdiction: ['CORPORATE', 'FINANCIAL'] },
    ],
    reportingRequirements: ['SEC annual report', 'BIR tax returns', 'PSE disclosure (listed)', 'BSP reporting (banks)', 'SSS/PhilHealth/Pag-IBIG contributions'],
    auditRequirements: 'Mandatory for stock corporations and companies above SEC thresholds (>P600K paid-up capital)',
  },
  isoContext: {
    adoptedStandards: [
      { standard: 'ISO 9001:2015', localStandard: 'PNS/ISO 9001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['Bureau Veritas', 'SGS', 'TÜV Rheinland', 'Intertek'], notes: 'Required for government procurement; strong in manufacturing and BPO' },
      { standard: 'ISO 14001:2015', localStandard: 'PNS/ISO 14001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['Bureau Veritas', 'SGS', 'TÜV Rheinland'], notes: 'Growing adoption especially in mining and manufacturing' },
      { standard: 'ISO 45001:2018', localStandard: 'PNS/ISO 45001:2019', adoptionStatus: 'ADOPTED', certificationBodies: ['Bureau Veritas', 'SGS', 'SOCOTEC'], notes: 'Aligned with R.A. 11058 OSH law' },
      { standard: 'ISO 27001:2022', adoptionStatus: 'ADOPTED', certificationBodies: ['BSI', 'Bureau Veritas', 'SGS'], notes: 'Growing adoption in BPO, fintech, and government' },
    ],
    certificationBodies: ['Bureau Veritas Philippines', 'SGS Philippines', 'TÜV Rheinland Philippines', 'BSI', 'Intertek Philippines'],
    accreditationBody: 'Philippine Accreditation Bureau (PAB)',
    notes: 'Philippines uses PNS (Philippine National Standards) which adopt ISO standards. PAB is the accreditation body under DTI.',
  },
  compliance: {
    mandatoryReporting: ['SEC General Information Sheet', 'BIR annual income tax return', 'PSE quarterly and annual reports (listed)', 'BSP prudential reports (banks)', 'CHED/TESDA for education entities'],
    esgRequirements: 'PSE requires large listed companies to submit sustainability reports. SEC Memorandum Circular 4 series 2019 on sustainability reporting.',
    sustainabilityFrameworks: ['GRI Standards', 'PSE Sustainability Reporting Guidelines', 'TCFD', 'SDGs'],
    dataProtectionAuthority: 'National Privacy Commission (NPC)',
    dataRetentionYears: 5,
    crossBorderDataTransfer: 'Permitted with adequate safeguards; NPC must be notified for certain transfers',
    whistleblowerProtection: true,
    modernSlaveryAct: false,
    dueDiligenceRequirements: 'No mandatory human rights due diligence; PSE sustainability reporting encourages supply chain ESG',
  },
  business: {
    companyTypes: ['Domestic Corporation', 'OPC (One Person Corporation)', 'Sole Proprietorship', 'Partnership', 'Branch Office', 'Representative Office', 'Regional HQ (RHQ)'],
    minShareCapital: 5000,
    incorporationTime: '1-3 business days (online via SEC)',
    businessRegistrationBody: 'Securities and Exchange Commission (SEC) / DTI (sole proprietorships)',
    easeOfDoingBusinessRank: 95,
    freeTradeZones: ['Clark Freeport Zone', 'Subic Bay Freeport Zone', 'Cagayan Special Economic Zone', 'PEZA Economic Zones'],
    importDutyFramework: 'Varied tariff rates. ASEAN ATIGA applies. PEZA companies enjoy duty-free imports for production inputs.',
    exportControls: ['Strategic Goods laws', 'Bureau of Customs export regulations'],
    ipProtectionRating: 'Moderate — improving under IPOPHL oversight',
    corruptionPerceptionsIndex: 33,
  },
};
