// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.

import type { RegionConfig } from '../types/region-config.types';

export const sg: RegionConfig = {
  countryCode: 'SG',
  countryName: 'Singapore',
  region: 'ASEAN',
  tier: 1,
  currency: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', decimals: 2, symbolPosition: 'before', thousandsSeparator: ',', decimalSeparator: '.' },
  dateFormat: 'DD/MM/YYYY',
  numberFormat: { thousandsSeparator: ',', decimalSeparator: '.', grouping: 3 },
  timezone: ['Asia/Singapore'],
  languages: [
    { code: 'en-SG', name: 'English', isOfficial: true, isPrimary: true, script: 'Latn' },
    { code: 'zh-SG', name: 'Mandarin Chinese', isOfficial: true, isPrimary: false, script: 'Hans' },
    { code: 'ms-SG', name: 'Malay', isOfficial: true, isPrimary: false, script: 'Latn' },
    { code: 'ta-SG', name: 'Tamil', isOfficial: true, isPrimary: false, script: 'Taml' },
  ],
  finance: {
    corporateTaxRate: 0.17,
    gstVatRate: 0.09,
    gstVatName: 'GST',
    gstVatRegistrationThreshold: 1000000,
    witholdingTaxRates: { dividends: 0, interest: 0.15, royalties: 0.10, services: 0.17 },
    payrollTax: { employeeRate: 0.20, employerRate: 0.17, name: 'CPF', ceiling: 6800 },
    transferPricingRules: true,
    thinCapitalisationRules: false,
    taxTreatyNetwork: ['AU', 'NZ', 'JP', 'CN', 'KR', 'IN', 'MY', 'TH', 'PH', 'ID', 'VN', 'GB', 'US', 'DE', 'FR'],
    fiscalYearEnd: 'Dec 31',
    filingDeadlines: { corporateTax: 'Nov 30 (ECI by Apr 30)', gstVat: 'Monthly/Quarterly', employeeTax: 'Mar 1' },
  },
  legislation: {
    primaryLaws: [
      {
        shortCode: 'EA-SG', title: 'Employment Act (Cap. 91A)', jurisdiction: 'Singapore', category: 'EMPLOYMENT',
        summary: 'Core employment legislation covering contracts, wages, leave and termination.',
        keyRequirements: ['Written employment contracts', 'Statutory leave entitlements', 'Overtime pay provisions', 'Notice periods'],
        effectiveDate: '1968-01-01', lastAmended: '2023-01-01',
        officialUrl: 'https://sso.agc.gov.sg/Act/EA1968',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'PDPA-SG', title: 'Personal Data Protection Act 2012', jurisdiction: 'Singapore', category: 'DATA_PRIVACY',
        summary: 'Governs collection, use, and disclosure of personal data in Singapore.',
        keyRequirements: ['Consent obligation', 'Purpose limitation', 'Data breach notification within 3 days', 'Retention limitation', 'PDPC registration'],
        effectiveDate: '2014-07-02', lastAmended: '2021-02-01',
        officialUrl: 'https://sso.agc.gov.sg/Act/PDPA2012',
        relatedISOStandards: ['ISO 27001:2022'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'WSHA-SG', title: 'Workplace Safety and Health Act (Cap. 354A)', jurisdiction: 'Singapore', category: 'HSE',
        summary: 'Regulates workplace safety and health obligations for employers and employees.',
        keyRequirements: ['Risk assessment', 'Safety management system', 'Incident reporting to MOM', 'WSH officer appointment'],
        effectiveDate: '2006-03-01', lastAmended: '2020-01-01',
        officialUrl: 'https://sso.agc.gov.sg/Act/WSHA2006',
        relatedISOStandards: ['ISO 45001:2018'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'EPMA-SG', title: 'Environmental Protection and Management Act', jurisdiction: 'Singapore', category: 'ENVIRONMENT',
        summary: 'Controls pollution and environmental hazards in Singapore.',
        keyRequirements: ['Pollution control', 'Hazardous substances management', 'Environmental impact assessment'],
        effectiveDate: '1999-01-01', lastAmended: '2022-01-01',
        officialUrl: 'https://sso.agc.gov.sg/Act/EPMA1999',
        relatedISOStandards: ['ISO 14001:2015'], isMandatory: true, applicableTo: ['all'],
      },
      {
        shortCode: 'PCA-SG', title: 'Prevention of Corruption Act (Cap. 241)', jurisdiction: 'Singapore', category: 'ANTI_CORRUPTION',
        summary: 'Prevents and punishes corruption in public and private sectors.',
        keyRequirements: ['Zero tolerance anti-corruption policy', 'Gifts policy', 'Training obligations'],
        officialUrl: 'https://sso.agc.gov.sg/Act/PCA1960',
        relatedISOStandards: ['ISO 37001:2016'], isMandatory: true, applicableTo: ['all'],
      },
    ],
    regulatoryBodies: [
      { name: 'Ministry of Manpower', acronym: 'MOM', website: 'https://www.mom.gov.sg', jurisdiction: ['EMPLOYMENT', 'HSE'] },
      { name: 'Personal Data Protection Commission', acronym: 'PDPC', website: 'https://www.pdpc.gov.sg', jurisdiction: ['DATA_PRIVACY'] },
      { name: 'National Environment Agency', acronym: 'NEA', website: 'https://www.nea.gov.sg', jurisdiction: ['ENVIRONMENT'] },
      { name: 'Corrupt Practices Investigation Bureau', acronym: 'CPIB', website: 'https://www.cpib.gov.sg', jurisdiction: ['ANTI_CORRUPTION'] },
    ],
    reportingRequirements: ['Annual return to ACRA', 'Audited financial statements (>S$10M revenue)', 'GST returns', 'PDPC breach notifications', 'MOM work injury notifications'],
    auditRequirements: 'Mandatory for companies with >S$10M annual turnover or >50 employees or assets >S$10M',
  },
  isoContext: {
    adoptedStandards: [
      { standard: 'ISO 9001:2015', localStandard: 'SS ISO 9001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['TÜV SÜD', 'Bureau Veritas', 'SGS', "Lloyd's Register"], notes: 'Widely adopted; common for government procurement' },
      { standard: 'ISO 14001:2015', localStandard: 'SS ISO 14001:2015', adoptionStatus: 'ADOPTED', certificationBodies: ['TÜV SÜD', 'Bureau Veritas', 'SGS'], mandatoryForSectors: ['construction', 'manufacturing'], notes: 'Required for certain BCA Green Mark projects' },
      { standard: 'ISO 45001:2018', localStandard: 'SS ISO 45001:2018', adoptionStatus: 'ADOPTED', certificationBodies: ['TÜV SÜD', 'Bureau Veritas', 'BSI'], mandatoryForSectors: ['construction', 'manufacturing'], notes: 'Aligned with WSH Act requirements' },
      { standard: 'ISO 27001:2022', adoptionStatus: 'ADOPTED', certificationBodies: ['TÜV SÜD', 'BSI', 'Bureau Veritas'], mandatoryForSectors: ['financial'], notes: 'MAS Technology Risk Management Guidelines aligned' },
      { standard: 'ISO 37001:2016', adoptionStatus: 'ADOPTED', certificationBodies: ['BSI', 'Bureau Veritas'], notes: 'Aligned with Prevention of Corruption Act' },
    ],
    certificationBodies: ['TÜV SÜD PSB', 'Bureau Veritas', 'SGS', "Lloyd's Register", 'BSI Group', 'DNV GL'],
    accreditationBody: 'Singapore Accreditation Council (SAC)',
    notes: 'Singapore has one of the highest ISO certification rates in ASEAN. SAC is the national accreditation body under ESG.',
  },
  compliance: {
    mandatoryReporting: ['SGXNET sustainability reports (listed co.)', 'ACRA annual filing', 'MAS regulatory reporting', 'PDPC data breach notifications'],
    esgRequirements: 'SGX-listed companies must report on sustainability. MAS Green Finance Action Plan guides financial sector.',
    sustainabilityFrameworks: ['GRI Standards', 'TCFD', 'SASB', 'Singapore Green Plan 2030'],
    dataProtectionAuthority: 'Personal Data Protection Commission (PDPC)',
    dataRetentionYears: 5,
    crossBorderDataTransfer: 'Permitted with adequate protection under PDPA Schedule 1 or approved certification',
    whistleblowerProtection: true,
    modernSlaveryAct: false,
    dueDiligenceRequirements: 'MAS Financial Services Integrity/Compliance guidelines; no mandatory human rights due diligence law yet',
  },
  business: {
    companyTypes: ['Private Limited (Pte Ltd)', 'Public Company Limited (Ltd)', 'Sole Proprietorship', 'Partnership', 'LLP', 'Branch Office', 'Representative Office'],
    minShareCapital: 1,
    incorporationTime: '1-3 business days',
    businessRegistrationBody: 'Accounting and Corporate Regulatory Authority (ACRA)',
    easeOfDoingBusinessRank: 2,
    freeTradeZones: ['Jurong Port FTZ', 'Sembawang Wharves FTZ', 'Changi Airport FTZ', 'Keppel Distripark FTZ'],
    importDutyFramework: 'Generally 0% tariff on most goods. GST applies. ASEAN harmonised tariff schedule.',
    exportControls: ['Strategic Goods (Control) Act', 'Customs (Prohibited Exports) Regulations'],
    ipProtectionRating: 'Very High — WIPO Global Innovation Index Top 5',
    corruptionPerceptionsIndex: 83,
  },
};
