import {
  FieldType, ImportSchema, ImportResult, RowResult,
  coerceType, validateField, validateRow, validateImport,
  makeSchema, makeField, isValidFieldType,
  summariseErrors, validRowsOnly, importPassRate,
} from '../src/index';

const TYPES: FieldType[] = ['string','number','boolean','date','email','url','uuid'];

function makeResult(v: number, inv: number, errors: {field:string;message:string;value:unknown}[] = []): ImportResult {
  const rows: RowResult[] = [];
  for (let i = 0; i < v; i++) rows.push({ rowIndex: i, status: 'valid', data: {}, errors: [] });
  for (let i = 0; i < inv; i++) rows.push({ rowIndex: v+i, status: 'invalid', data: {}, errors });
  return { schema: 'test', totalRows: v+inv, validRows: v, invalidRows: inv, skippedRows: 0, rows, errors };
}

describe('isValidFieldType', () => {
  it('valid string', () => expect(isValidFieldType('string')).toBe(true));
  it('valid number', () => expect(isValidFieldType('number')).toBe(true));
  it('valid boolean', () => expect(isValidFieldType('boolean')).toBe(true));
  it('valid date', () => expect(isValidFieldType('date')).toBe(true));
  it('valid email', () => expect(isValidFieldType('email')).toBe(true));
  it('valid url', () => expect(isValidFieldType('url')).toBe(true));
  it('valid uuid', () => expect(isValidFieldType('uuid')).toBe(true));
  it('invalid int', () => expect(isValidFieldType('int')).toBe(false));
  it('invalid float', () => expect(isValidFieldType('float')).toBe(false));
  it('invalid array', () => expect(isValidFieldType('array')).toBe(false));
  it('invalid object', () => expect(isValidFieldType('object')).toBe(false));
  it('invalid null', () => expect(isValidFieldType('null')).toBe(false));
  it('invalid undefined', () => expect(isValidFieldType('undefined')).toBe(false));
  it('invalid BOOLEAN', () => expect(isValidFieldType('BOOLEAN')).toBe(false));
  it('invalid DATE', () => expect(isValidFieldType('DATE')).toBe(false));
  it('invalid Number', () => expect(isValidFieldType('Number')).toBe(false));
  it('invalid varchar', () => expect(isValidFieldType('varchar')).toBe(false));
  it('invalid text', () => expect(isValidFieldType('text')).toBe(false));
  it('invalid blob', () => expect(isValidFieldType('blob')).toBe(false));
  it('invalid binary', () => expect(isValidFieldType('binary')).toBe(false));
  it('invalid set', () => expect(isValidFieldType('set')).toBe(false));
  it('invalid map', () => expect(isValidFieldType('map')).toBe(false));
});

describe('makeField', () => {
  TYPES.forEach(t => {
    it('mf name:' + t, () => expect(makeField('f', t).name).toBe('f'));
    it('mf type:' + t, () => expect(makeField('f', t).type).toBe(t));
    it('mf req def:' + t, () => expect(makeField('f', t).required).toBe(false));
    it('mf req true:' + t, () => expect(makeField('f', t, true).required).toBe(true));
  });
  it('mf name0', () => expect(makeField('f0', 'string').name).toBe('f0'));
  it('mf name1', () => expect(makeField('f1', 'string').name).toBe('f1'));
  it('mf name2', () => expect(makeField('f2', 'string').name).toBe('f2'));
  it('mf name3', () => expect(makeField('f3', 'string').name).toBe('f3'));
  it('mf name4', () => expect(makeField('f4', 'string').name).toBe('f4'));
  it('mf name5', () => expect(makeField('f5', 'string').name).toBe('f5'));
  it('mf name6', () => expect(makeField('f6', 'string').name).toBe('f6'));
  it('mf name7', () => expect(makeField('f7', 'string').name).toBe('f7'));
  it('mf name8', () => expect(makeField('f8', 'string').name).toBe('f8'));
  it('mf name9', () => expect(makeField('f9', 'string').name).toBe('f9'));
  it('mf name10', () => expect(makeField('f10', 'string').name).toBe('f10'));
  it('mf name11', () => expect(makeField('f11', 'string').name).toBe('f11'));
  it('mf name12', () => expect(makeField('f12', 'string').name).toBe('f12'));
  it('mf name13', () => expect(makeField('f13', 'string').name).toBe('f13'));
  it('mf name14', () => expect(makeField('f14', 'string').name).toBe('f14'));
  it('mf name15', () => expect(makeField('f15', 'string').name).toBe('f15'));
  it('mf name16', () => expect(makeField('f16', 'string').name).toBe('f16'));
  it('mf name17', () => expect(makeField('f17', 'string').name).toBe('f17'));
  it('mf name18', () => expect(makeField('f18', 'string').name).toBe('f18'));
  it('mf name19', () => expect(makeField('f19', 'string').name).toBe('f19'));
});

describe('makeSchema', () => {
  it('ms employees', () => expect(makeSchema('employees', []).name).toBe('employees'));
  it('ms assets', () => expect(makeSchema('assets', []).name).toBe('assets'));
  it('ms risks', () => expect(makeSchema('risks', []).name).toBe('risks'));
  it('ms audits', () => expect(makeSchema('audits', []).name).toBe('audits'));
  it('ms incidents', () => expect(makeSchema('incidents', []).name).toBe('incidents'));
  it('ms compliance', () => expect(makeSchema('compliance', []).name).toBe('compliance'));
  it('ms suppliers', () => expect(makeSchema('suppliers', []).name).toBe('suppliers'));
  it('ms contracts', () => expect(makeSchema('contracts', []).name).toBe('contracts'));
  it('ms orders', () => expect(makeSchema('orders', []).name).toBe('orders'));
  it('ms invoices', () => expect(makeSchema('invoices', []).name).toBe('invoices'));
  it('ms fields', () => expect(makeSchema('s', []).fields).toEqual([]));
  it('ms ae default', () => expect(makeSchema('s', []).allowExtra).toBe(false));
  it('ms ae true', () => expect(makeSchema('s', [], true).allowExtra).toBe(true));
  it('ms stores fields', () => { const f = makeField('x', 'string'); expect(makeSchema('s', [f]).fields).toHaveLength(1); });
  it('ms s0', () => expect(makeSchema('s0', []).name).toBe('s0'));
  it('ms s1', () => expect(makeSchema('s1', []).name).toBe('s1'));
  it('ms s2', () => expect(makeSchema('s2', []).name).toBe('s2'));
  it('ms s3', () => expect(makeSchema('s3', []).name).toBe('s3'));
  it('ms s4', () => expect(makeSchema('s4', []).name).toBe('s4'));
  it('ms s5', () => expect(makeSchema('s5', []).name).toBe('s5'));
  it('ms s6', () => expect(makeSchema('s6', []).name).toBe('s6'));
  it('ms s7', () => expect(makeSchema('s7', []).name).toBe('s7'));
  it('ms s8', () => expect(makeSchema('s8', []).name).toBe('s8'));
  it('ms s9', () => expect(makeSchema('s9', []).name).toBe('s9'));
  it('ms s10', () => expect(makeSchema('s10', []).name).toBe('s10'));
  it('ms s11', () => expect(makeSchema('s11', []).name).toBe('s11'));
  it('ms s12', () => expect(makeSchema('s12', []).name).toBe('s12'));
  it('ms s13', () => expect(makeSchema('s13', []).name).toBe('s13'));
  it('ms s14', () => expect(makeSchema('s14', []).name).toBe('s14'));
  it('ms s15', () => expect(makeSchema('s15', []).name).toBe('s15'));
  it('ms s16', () => expect(makeSchema('s16', []).name).toBe('s16'));
  it('ms s17', () => expect(makeSchema('s17', []).name).toBe('s17'));
  it('ms s18', () => expect(makeSchema('s18', []).name).toBe('s18'));
  it('ms s19', () => expect(makeSchema('s19', []).name).toBe('s19'));
});

describe('coerceType number', () => {
  it('cn 1', () => expect(coerceType(1, 'number')).toBe(1));
  it('cn 2', () => expect(coerceType(2, 'number')).toBe(2));
  it('cn 3', () => expect(coerceType(3, 'number')).toBe(3));
  it('cn 4', () => expect(coerceType(4, 'number')).toBe(4));
  it('cn 5', () => expect(coerceType(5, 'number')).toBe(5));
  it('cn 6', () => expect(coerceType(6, 'number')).toBe(6));
  it('cn 7', () => expect(coerceType(7, 'number')).toBe(7));
  it('cn 8', () => expect(coerceType(8, 'number')).toBe(8));
  it('cn 9', () => expect(coerceType(9, 'number')).toBe(9));
  it('cn 10', () => expect(coerceType(10, 'number')).toBe(10));
  it('cn 11', () => expect(coerceType(11, 'number')).toBe(11));
  it('cn 12', () => expect(coerceType(12, 'number')).toBe(12));
  it('cn 13', () => expect(coerceType(13, 'number')).toBe(13));
  it('cn 14', () => expect(coerceType(14, 'number')).toBe(14));
  it('cn 15', () => expect(coerceType(15, 'number')).toBe(15));
  it('cn 16', () => expect(coerceType(16, 'number')).toBe(16));
  it('cn 17', () => expect(coerceType(17, 'number')).toBe(17));
  it('cn 18', () => expect(coerceType(18, 'number')).toBe(18));
  it('cn 19', () => expect(coerceType(19, 'number')).toBe(19));
  it('cn 20', () => expect(coerceType(20, 'number')).toBe(20));
  it('cn 21', () => expect(coerceType(21, 'number')).toBe(21));
  it('cn 22', () => expect(coerceType(22, 'number')).toBe(22));
  it('cn 23', () => expect(coerceType(23, 'number')).toBe(23));
  it('cn 24', () => expect(coerceType(24, 'number')).toBe(24));
  it('cn 25', () => expect(coerceType(25, 'number')).toBe(25));
  it('cn 26', () => expect(coerceType(26, 'number')).toBe(26));
  it('cn 27', () => expect(coerceType(27, 'number')).toBe(27));
  it('cn 28', () => expect(coerceType(28, 'number')).toBe(28));
  it('cn 29', () => expect(coerceType(29, 'number')).toBe(29));
  it('cn 30', () => expect(coerceType(30, 'number')).toBe(30));
  it('cn 31', () => expect(coerceType(31, 'number')).toBe(31));
  it('cn 32', () => expect(coerceType(32, 'number')).toBe(32));
  it('cn 33', () => expect(coerceType(33, 'number')).toBe(33));
  it('cn 34', () => expect(coerceType(34, 'number')).toBe(34));
  it('cn 35', () => expect(coerceType(35, 'number')).toBe(35));
  it('cn 36', () => expect(coerceType(36, 'number')).toBe(36));
  it('cn 37', () => expect(coerceType(37, 'number')).toBe(37));
  it('cn 38', () => expect(coerceType(38, 'number')).toBe(38));
  it('cn 39', () => expect(coerceType(39, 'number')).toBe(39));
  it('cn 40', () => expect(coerceType(40, 'number')).toBe(40));
  it('cn 41', () => expect(coerceType(41, 'number')).toBe(41));
  it('cn 42', () => expect(coerceType(42, 'number')).toBe(42));
  it('cn 43', () => expect(coerceType(43, 'number')).toBe(43));
  it('cn 44', () => expect(coerceType(44, 'number')).toBe(44));
  it('cn 45', () => expect(coerceType(45, 'number')).toBe(45));
  it('cn 46', () => expect(coerceType(46, 'number')).toBe(46));
  it('cn 47', () => expect(coerceType(47, 'number')).toBe(47));
  it('cn 48', () => expect(coerceType(48, 'number')).toBe(48));
  it('cn 49', () => expect(coerceType(49, 'number')).toBe(49));
  it('cn 50', () => expect(coerceType(50, 'number')).toBe(50));
  it('cn str 1', () => expect(coerceType('1', 'number')).toBe(1));
  it('cn str 2', () => expect(coerceType('2', 'number')).toBe(2));
  it('cn str 3', () => expect(coerceType('3', 'number')).toBe(3));
  it('cn str 4', () => expect(coerceType('4', 'number')).toBe(4));
  it('cn str 5', () => expect(coerceType('5', 'number')).toBe(5));
  it('cn str 6', () => expect(coerceType('6', 'number')).toBe(6));
  it('cn str 7', () => expect(coerceType('7', 'number')).toBe(7));
  it('cn str 8', () => expect(coerceType('8', 'number')).toBe(8));
  it('cn str 9', () => expect(coerceType('9', 'number')).toBe(9));
  it('cn str 10', () => expect(coerceType('10', 'number')).toBe(10));
  it('cn str 11', () => expect(coerceType('11', 'number')).toBe(11));
  it('cn str 12', () => expect(coerceType('12', 'number')).toBe(12));
  it('cn str 13', () => expect(coerceType('13', 'number')).toBe(13));
  it('cn str 14', () => expect(coerceType('14', 'number')).toBe(14));
  it('cn str 15', () => expect(coerceType('15', 'number')).toBe(15));
  it('cn str 16', () => expect(coerceType('16', 'number')).toBe(16));
  it('cn str 17', () => expect(coerceType('17', 'number')).toBe(17));
  it('cn str 18', () => expect(coerceType('18', 'number')).toBe(18));
  it('cn str 19', () => expect(coerceType('19', 'number')).toBe(19));
  it('cn str 20', () => expect(coerceType('20', 'number')).toBe(20));
  it('cn null', () => expect(coerceType(null, 'number')).toBeNull());
  it('cn undef', () => expect(coerceType(undefined, 'number')).toBeNull());
  it('cn empty', () => expect(coerceType('', 'number')).toBeNull());
  it('cn nan', () => expect(coerceType('abc', 'number')).toBeNull());
  it('cn float', () => expect(coerceType(3.14, 'number')).toBe(3.14));
  it('cn neg', () => expect(coerceType(-5, 'number')).toBe(-5));
  it('cn true', () => expect(coerceType(true, 'number')).toBe(1));
  it('cn false', () => expect(coerceType(false, 'number')).toBe(0));
});

describe('coerceType boolean', () => {
  it('cb truthy true', () => expect(coerceType('true', 'boolean')).toBe(true));
  it('cb truthy 1', () => expect(coerceType('1', 'boolean')).toBe(true));
  it('cb truthy yes', () => expect(coerceType('yes', 'boolean')).toBe(true));
  it('cb truthy TRUE', () => expect(coerceType('TRUE', 'boolean')).toBe(true));
  it('cb truthy YES', () => expect(coerceType('YES', 'boolean')).toBe(true));
  it('cb falsy false', () => expect(coerceType('false', 'boolean')).toBe(false));
  it('cb falsy 0', () => expect(coerceType('0', 'boolean')).toBe(false));
  it('cb falsy no', () => expect(coerceType('no', 'boolean')).toBe(false));
  it('cb falsy FALSE', () => expect(coerceType('FALSE', 'boolean')).toBe(false));
  it('cb falsy NO', () => expect(coerceType('NO', 'boolean')).toBe(false));
  it('cb true lit', () => expect(coerceType(true, 'boolean')).toBe(true));
  it('cb false lit', () => expect(coerceType(false, 'boolean')).toBe(false));
  it('cb null', () => expect(coerceType(null, 'boolean')).toBeNull());
  it('cb undef', () => expect(coerceType(undefined, 'boolean')).toBeNull());
  it('cb empty', () => expect(coerceType('', 'boolean')).toBeNull());
  it('cb maybe', () => expect(coerceType('maybe', 'boolean')).toBeNull());
  it('cb extra0', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra1', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra2', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra3', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra4', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra5', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra6', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra7', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra8', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
  it('cb extra9', () => expect(typeof coerceType(true, 'boolean')).toBe('boolean'));
});

describe('coerceType string-like', () => {
  it('cst string num', () => expect(coerceType(42, 'string')).toBe('42'));
  it('cst string bool', () => expect(coerceType(true, 'string')).toBe('true'));
  it('cst string null', () => expect(coerceType(null, 'string')).toBeNull());
  it('cst string empty', () => expect(coerceType('', 'string')).toBeNull());
  it('cst string pass', () => expect(coerceType('hello', 'string')).toBe('hello'));
  it('cst email num', () => expect(coerceType(42, 'email')).toBe('42'));
  it('cst email bool', () => expect(coerceType(true, 'email')).toBe('true'));
  it('cst email null', () => expect(coerceType(null, 'email')).toBeNull());
  it('cst email empty', () => expect(coerceType('', 'email')).toBeNull());
  it('cst email pass', () => expect(coerceType('hello', 'email')).toBe('hello'));
  it('cst url num', () => expect(coerceType(42, 'url')).toBe('42'));
  it('cst url bool', () => expect(coerceType(true, 'url')).toBe('true'));
  it('cst url null', () => expect(coerceType(null, 'url')).toBeNull());
  it('cst url empty', () => expect(coerceType('', 'url')).toBeNull());
  it('cst url pass', () => expect(coerceType('hello', 'url')).toBe('hello'));
  it('cst uuid num', () => expect(coerceType(42, 'uuid')).toBe('42'));
  it('cst uuid bool', () => expect(coerceType(true, 'uuid')).toBe('true'));
  it('cst uuid null', () => expect(coerceType(null, 'uuid')).toBeNull());
  it('cst uuid empty', () => expect(coerceType('', 'uuid')).toBeNull());
  it('cst uuid pass', () => expect(coerceType('hello', 'uuid')).toBe('hello'));
});

describe('coerceType date', () => {
  it('cd valid 2024-01-01', () => expect(coerceType('2024-01-01', 'date')).toBeTruthy());
  it('cd valid 2025-06-15', () => expect(coerceType('2025-06-15', 'date')).toBeTruthy());
  it('cd valid 2023-12-31', () => expect(coerceType('2023-12-31', 'date')).toBeTruthy());
  it('cd valid 2026-02-24', () => expect(coerceType('2026-02-24', 'date')).toBeTruthy());
  it('cd invalid not-a-date', () => expect(coerceType('not-a-date', 'date')).toBeNull());
  it('cd invalid abc', () => expect(coerceType('abc', 'date')).toBeNull());
  it('cd invalid 99-99-99', () => expect(coerceType('99-99-99', 'date')).toBeNull());
  it('cd null', () => expect(coerceType(null, 'date')).toBeNull());
  it('cd empty', () => expect(coerceType('', 'date')).toBeNull());
  it('cd iso str', () => { const r = coerceType('2024-01-01', 'date'); expect(typeof r).toBe('string'); });
  it('cd loop 1', () => expect(coerceType('2024-01-01', 'date')).toBeTruthy());
  it('cd loop 2', () => expect(coerceType('2024-02-01', 'date')).toBeTruthy());
  it('cd loop 3', () => expect(coerceType('2024-03-01', 'date')).toBeTruthy());
  it('cd loop 4', () => expect(coerceType('2024-04-01', 'date')).toBeTruthy());
  it('cd loop 5', () => expect(coerceType('2024-05-01', 'date')).toBeTruthy());
  it('cd loop 6', () => expect(coerceType('2024-06-01', 'date')).toBeTruthy());
  it('cd loop 7', () => expect(coerceType('2024-07-01', 'date')).toBeTruthy());
  it('cd loop 8', () => expect(coerceType('2024-08-01', 'date')).toBeTruthy());
  it('cd loop 9', () => expect(coerceType('2024-09-01', 'date')).toBeTruthy());
  it('cd loop 10', () => expect(coerceType('2024-10-01', 'date')).toBeTruthy());
});

describe('validateField required', () => {
  TYPES.forEach(t => {
    it('vfr null:' + t, () => expect(validateField({ name: 'f', type: t, required: true }, null).length).toBeGreaterThan(0));
    it('vfr undef:' + t, () => expect(validateField({ name: 'f', type: t, required: true }, undefined).length).toBeGreaterThan(0));
    it('vfr empty:' + t, () => expect(validateField({ name: 'f', type: t, required: true }, '').length).toBeGreaterThan(0));
    it('vfr opt:' + t, () => { const r = validateField({ name: 'f', type: t, required: false }, null); expect(r.filter((x: any) => x.message.includes('required'))).toHaveLength(0); });
  });
});

describe('validateField required', () => {
  TYPES.forEach(t => {
    it('vfr null:' + t, () => expect(validateField({ name: 'f', type: t, required: true }, null).length).toBeGreaterThan(0));
    it('vfr undef:' + t, () => expect(validateField({ name: 'f', type: t, required: true }, undefined).length).toBeGreaterThan(0));
    it('vfr empty:' + t, () => expect(validateField({ name: 'f', type: t, required: true }, '').length).toBeGreaterThan(0));
    it('vfr opt:' + t, () => { const r = validateField({ name: 'f', type: t, required: false }, null); expect(r.filter((x: any) => x.message.includes('required'))).toHaveLength(0); });
  });
});

describe('validateField string', () => {
  it('vfs maxLen1', () => { const s = 'x'.repeat(1); expect(validateField({ name: 'n', type: 'string', maxLength: 1 }, s)).toHaveLength(0); });
  it('vfs maxLen2', () => { const s = 'x'.repeat(2); expect(validateField({ name: 'n', type: 'string', maxLength: 2 }, s)).toHaveLength(0); });
  it('vfs maxLen3', () => { const s = 'x'.repeat(3); expect(validateField({ name: 'n', type: 'string', maxLength: 3 }, s)).toHaveLength(0); });
  it('vfs maxLen4', () => { const s = 'x'.repeat(4); expect(validateField({ name: 'n', type: 'string', maxLength: 4 }, s)).toHaveLength(0); });
  it('vfs maxLen5', () => { const s = 'x'.repeat(5); expect(validateField({ name: 'n', type: 'string', maxLength: 5 }, s)).toHaveLength(0); });
  it('vfs maxLen6', () => { const s = 'x'.repeat(6); expect(validateField({ name: 'n', type: 'string', maxLength: 6 }, s)).toHaveLength(0); });
  it('vfs maxLen7', () => { const s = 'x'.repeat(7); expect(validateField({ name: 'n', type: 'string', maxLength: 7 }, s)).toHaveLength(0); });
  it('vfs maxLen8', () => { const s = 'x'.repeat(8); expect(validateField({ name: 'n', type: 'string', maxLength: 8 }, s)).toHaveLength(0); });
  it('vfs maxLen9', () => { const s = 'x'.repeat(9); expect(validateField({ name: 'n', type: 'string', maxLength: 9 }, s)).toHaveLength(0); });
  it('vfs maxLen10', () => { const s = 'x'.repeat(10); expect(validateField({ name: 'n', type: 'string', maxLength: 10 }, s)).toHaveLength(0); });
  it('vfs maxLen11', () => { const s = 'x'.repeat(11); expect(validateField({ name: 'n', type: 'string', maxLength: 11 }, s)).toHaveLength(0); });
  it('vfs maxLen12', () => { const s = 'x'.repeat(12); expect(validateField({ name: 'n', type: 'string', maxLength: 12 }, s)).toHaveLength(0); });
  it('vfs maxLen13', () => { const s = 'x'.repeat(13); expect(validateField({ name: 'n', type: 'string', maxLength: 13 }, s)).toHaveLength(0); });
  it('vfs maxLen14', () => { const s = 'x'.repeat(14); expect(validateField({ name: 'n', type: 'string', maxLength: 14 }, s)).toHaveLength(0); });
  it('vfs maxLen15', () => { const s = 'x'.repeat(15); expect(validateField({ name: 'n', type: 'string', maxLength: 15 }, s)).toHaveLength(0); });
  it('vfs maxLen16', () => { const s = 'x'.repeat(16); expect(validateField({ name: 'n', type: 'string', maxLength: 16 }, s)).toHaveLength(0); });
  it('vfs maxLen17', () => { const s = 'x'.repeat(17); expect(validateField({ name: 'n', type: 'string', maxLength: 17 }, s)).toHaveLength(0); });
  it('vfs maxLen18', () => { const s = 'x'.repeat(18); expect(validateField({ name: 'n', type: 'string', maxLength: 18 }, s)).toHaveLength(0); });
  it('vfs maxLen19', () => { const s = 'x'.repeat(19); expect(validateField({ name: 'n', type: 'string', maxLength: 19 }, s)).toHaveLength(0); });
  it('vfs maxLen20', () => { const s = 'x'.repeat(20); expect(validateField({ name: 'n', type: 'string', maxLength: 20 }, s)).toHaveLength(0); });
  it('vfs minFail', () => { const e = validateField({ name: 'n', type: 'string', minLength: 5 }, 'ab'); expect(e[0].message).toContain('at least'); });
  it('vfs maxFail', () => { const e = validateField({ name: 'n', type: 'string', maxLength: 3 }, 'toolong'); expect(e[0].message).toContain('at most'); });
  it('vfs noerr0', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr1', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr2', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr3', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr4', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr5', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr6', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr7', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr8', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr9', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr10', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr11', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr12', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr13', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr14', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr15', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr16', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr17', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr18', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr19', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr20', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr21', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr22', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr23', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr24', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr25', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr26', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr27', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr28', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs noerr29', () => expect(validateField({ name: 'n', type: 'string' }, 'hello')).toHaveLength(0));
  it('vfs enum pass', () => expect(validateField({ name: 'n', type: 'string', enum: ['a','b'] }, 'a')).toHaveLength(0));
  it('vfs enum fail', () => expect(validateField({ name: 'n', type: 'string', enum: ['a','b'] }, 'c').length).toBeGreaterThan(0));
});

describe('validateField email', () => {
  it('vfe valid a@b.com', () => expect(validateField({ name: 'e', type: 'email' }, 'a@b.com')).toHaveLength(0));
  it('vfe valid user@example.org', () => expect(validateField({ name: 'e', type: 'email' }, 'user@example.org')).toHaveLength(0));
  it('vfe valid foo.bar@baz.co.uk', () => expect(validateField({ name: 'e', type: 'email' }, 'foo.bar@baz.co.uk')).toHaveLength(0));
  it('vfe valid test+1@domain.io', () => expect(validateField({ name: 'e', type: 'email' }, 'test+1@domain.io')).toHaveLength(0));
  it('vfe invalid notanemail', () => expect(validateField({ name: 'e', type: 'email' }, 'notanemail').length).toBeGreaterThan(0));
  it('vfe invalid missing@', () => expect(validateField({ name: 'e', type: 'email' }, 'missing@').length).toBeGreaterThan(0));
  it('vfe invalid @nodomain', () => expect(validateField({ name: 'e', type: 'email' }, '@nodomain').length).toBeGreaterThan(0));
  it('vfe req0', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req1', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req2', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req3', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req4', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req5', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req6', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req7', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req8', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req9', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req10', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req11', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req12', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req13', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req14', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req15', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req16', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req17', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req18', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req19', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req20', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req21', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req22', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req23', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req24', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req25', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req26', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req27', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req28', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
  it('vfe req29', () => expect(validateField({ name: 'e', type: 'email', required: true }, '').length).toBeGreaterThan(0));
});

describe('validateField url', () => {
  it('vfu valid https://example.com', () => expect(validateField({ name: 'u', type: 'url' }, 'https://example.com')).toHaveLength(0));
  it('vfu valid http://foo.bar/path', () => expect(validateField({ name: 'u', type: 'url' }, 'http://foo.bar/path')).toHaveLength(0));
  it('vfu invalid not-a-url', () => expect(validateField({ name: 'u', type: 'url' }, 'not-a-url').length).toBeGreaterThan(0));
  it('vfu invalid ftp//missing', () => expect(validateField({ name: 'u', type: 'url' }, 'ftp//missing').length).toBeGreaterThan(0));
  it('vfu req0', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req1', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req2', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req3', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req4', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req5', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req6', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req7', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req8', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req9', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req10', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req11', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req12', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req13', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req14', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req15', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req16', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req17', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req18', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
  it('vfu req19', () => expect(validateField({ name: 'u', type: 'url', required: true }, '').length).toBeGreaterThan(0));
});

describe('validateField number', () => {
  it('vfn 1', () => expect(validateField({ name: 'n', type: 'number' }, 1)).toHaveLength(0));
  it('vfn 2', () => expect(validateField({ name: 'n', type: 'number' }, 2)).toHaveLength(0));
  it('vfn 3', () => expect(validateField({ name: 'n', type: 'number' }, 3)).toHaveLength(0));
  it('vfn 4', () => expect(validateField({ name: 'n', type: 'number' }, 4)).toHaveLength(0));
  it('vfn 5', () => expect(validateField({ name: 'n', type: 'number' }, 5)).toHaveLength(0));
  it('vfn 6', () => expect(validateField({ name: 'n', type: 'number' }, 6)).toHaveLength(0));
  it('vfn 7', () => expect(validateField({ name: 'n', type: 'number' }, 7)).toHaveLength(0));
  it('vfn 8', () => expect(validateField({ name: 'n', type: 'number' }, 8)).toHaveLength(0));
  it('vfn 9', () => expect(validateField({ name: 'n', type: 'number' }, 9)).toHaveLength(0));
  it('vfn 10', () => expect(validateField({ name: 'n', type: 'number' }, 10)).toHaveLength(0));
  it('vfn 11', () => expect(validateField({ name: 'n', type: 'number' }, 11)).toHaveLength(0));
  it('vfn 12', () => expect(validateField({ name: 'n', type: 'number' }, 12)).toHaveLength(0));
  it('vfn 13', () => expect(validateField({ name: 'n', type: 'number' }, 13)).toHaveLength(0));
  it('vfn 14', () => expect(validateField({ name: 'n', type: 'number' }, 14)).toHaveLength(0));
  it('vfn 15', () => expect(validateField({ name: 'n', type: 'number' }, 15)).toHaveLength(0));
  it('vfn 16', () => expect(validateField({ name: 'n', type: 'number' }, 16)).toHaveLength(0));
  it('vfn 17', () => expect(validateField({ name: 'n', type: 'number' }, 17)).toHaveLength(0));
  it('vfn 18', () => expect(validateField({ name: 'n', type: 'number' }, 18)).toHaveLength(0));
  it('vfn 19', () => expect(validateField({ name: 'n', type: 'number' }, 19)).toHaveLength(0));
  it('vfn 20', () => expect(validateField({ name: 'n', type: 'number' }, 20)).toHaveLength(0));
  it('vfn 21', () => expect(validateField({ name: 'n', type: 'number' }, 21)).toHaveLength(0));
  it('vfn 22', () => expect(validateField({ name: 'n', type: 'number' }, 22)).toHaveLength(0));
  it('vfn 23', () => expect(validateField({ name: 'n', type: 'number' }, 23)).toHaveLength(0));
  it('vfn 24', () => expect(validateField({ name: 'n', type: 'number' }, 24)).toHaveLength(0));
  it('vfn 25', () => expect(validateField({ name: 'n', type: 'number' }, 25)).toHaveLength(0));
  it('vfn 26', () => expect(validateField({ name: 'n', type: 'number' }, 26)).toHaveLength(0));
  it('vfn 27', () => expect(validateField({ name: 'n', type: 'number' }, 27)).toHaveLength(0));
  it('vfn 28', () => expect(validateField({ name: 'n', type: 'number' }, 28)).toHaveLength(0));
  it('vfn 29', () => expect(validateField({ name: 'n', type: 'number' }, 29)).toHaveLength(0));
  it('vfn 30', () => expect(validateField({ name: 'n', type: 'number' }, 30)).toHaveLength(0));
  it('vfn 31', () => expect(validateField({ name: 'n', type: 'number' }, 31)).toHaveLength(0));
  it('vfn 32', () => expect(validateField({ name: 'n', type: 'number' }, 32)).toHaveLength(0));
  it('vfn 33', () => expect(validateField({ name: 'n', type: 'number' }, 33)).toHaveLength(0));
  it('vfn 34', () => expect(validateField({ name: 'n', type: 'number' }, 34)).toHaveLength(0));
  it('vfn 35', () => expect(validateField({ name: 'n', type: 'number' }, 35)).toHaveLength(0));
  it('vfn 36', () => expect(validateField({ name: 'n', type: 'number' }, 36)).toHaveLength(0));
  it('vfn 37', () => expect(validateField({ name: 'n', type: 'number' }, 37)).toHaveLength(0));
  it('vfn 38', () => expect(validateField({ name: 'n', type: 'number' }, 38)).toHaveLength(0));
  it('vfn 39', () => expect(validateField({ name: 'n', type: 'number' }, 39)).toHaveLength(0));
  it('vfn 40', () => expect(validateField({ name: 'n', type: 'number' }, 40)).toHaveLength(0));
  it('vfn 41', () => expect(validateField({ name: 'n', type: 'number' }, 41)).toHaveLength(0));
  it('vfn 42', () => expect(validateField({ name: 'n', type: 'number' }, 42)).toHaveLength(0));
  it('vfn 43', () => expect(validateField({ name: 'n', type: 'number' }, 43)).toHaveLength(0));
  it('vfn 44', () => expect(validateField({ name: 'n', type: 'number' }, 44)).toHaveLength(0));
  it('vfn 45', () => expect(validateField({ name: 'n', type: 'number' }, 45)).toHaveLength(0));
  it('vfn 46', () => expect(validateField({ name: 'n', type: 'number' }, 46)).toHaveLength(0));
  it('vfn 47', () => expect(validateField({ name: 'n', type: 'number' }, 47)).toHaveLength(0));
  it('vfn 48', () => expect(validateField({ name: 'n', type: 'number' }, 48)).toHaveLength(0));
  it('vfn 49', () => expect(validateField({ name: 'n', type: 'number' }, 49)).toHaveLength(0));
  it('vfn 50', () => expect(validateField({ name: 'n', type: 'number' }, 50)).toHaveLength(0));
  it('vfn min fail', () => expect(validateField({ name: 'n', type: 'number', min: 10 }, 5).length).toBeGreaterThan(0));
  it('vfn max fail', () => expect(validateField({ name: 'n', type: 'number', max: 10 }, 20).length).toBeGreaterThan(0));
  it('vfn min pass', () => expect(validateField({ name: 'n', type: 'number', min: 5 }, 10)).toHaveLength(0));
  it('vfn max pass', () => expect(validateField({ name: 'n', type: 'number', max: 100 }, 50)).toHaveLength(0));
  it('vfn invalid str', () => expect(validateField({ name: 'n', type: 'number' }, 'abc').length).toBeGreaterThan(0));
  it('vfn null ok', () => expect(validateField({ name: 'n', type: 'number' }, null)).toHaveLength(0));
});

describe('validateField boolean', () => {
  it('vfb truthy true', () => expect(validateField({ name: 'b', type: 'boolean' }, 'true')).toHaveLength(0));
  it('vfb truthy 1', () => expect(validateField({ name: 'b', type: 'boolean' }, '1')).toHaveLength(0));
  it('vfb truthy yes', () => expect(validateField({ name: 'b', type: 'boolean' }, 'yes')).toHaveLength(0));
  it('vfb falsy false', () => expect(validateField({ name: 'b', type: 'boolean' }, 'false')).toHaveLength(0));
  it('vfb falsy 0', () => expect(validateField({ name: 'b', type: 'boolean' }, '0')).toHaveLength(0));
  it('vfb falsy no', () => expect(validateField({ name: 'b', type: 'boolean' }, 'no')).toHaveLength(0));
  it('vfb true lit', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb false lit', () => expect(validateField({ name: 'b', type: 'boolean' }, false)).toHaveLength(0));
  it('vfb invalid', () => expect(validateField({ name: 'b', type: 'boolean' }, 'maybe').length).toBeGreaterThan(0));
  it('vfb extra0', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra1', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra2', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra3', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra4', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra5', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra6', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra7', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra8', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra9', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra10', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra11', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra12', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra13', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra14', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra15', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra16', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra17', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra18', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
  it('vfb extra19', () => expect(validateField({ name: 'b', type: 'boolean' }, true)).toHaveLength(0));
});

describe('validateField date', () => {
  it('vfd valid 2024-01-01', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd valid 2025-06-15', () => expect(validateField({ name: 'd', type: 'date' }, '2025-06-15')).toHaveLength(0));
  it('vfd valid 2023-12-31', () => expect(validateField({ name: 'd', type: 'date' }, '2023-12-31')).toHaveLength(0));
  it('vfd valid 2026-02-24', () => expect(validateField({ name: 'd', type: 'date' }, '2026-02-24')).toHaveLength(0));
  it('vfd valid 2020-07-04', () => expect(validateField({ name: 'd', type: 'date' }, '2020-07-04')).toHaveLength(0));
  it('vfd invalid not-a-date', () => expect(validateField({ name: 'd', type: 'date' }, 'not-a-date').length).toBeGreaterThan(0));
  it('vfd invalid abc-xyz', () => expect(validateField({ name: 'd', type: 'date' }, 'abc-xyz').length).toBeGreaterThan(0));
  it('vfd invalid yesterday', () => expect(validateField({ name: 'd', type: 'date' }, 'yesterday').length).toBeGreaterThan(0));
  it('vfd null ok', () => expect(validateField({ name: 'd', type: 'date' }, null)).toHaveLength(0));
  it('vfd extra0', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra1', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra2', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra3', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra4', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra5', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra6', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra7', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra8', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra9', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra10', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra11', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra12', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra13', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra14', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra15', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra16', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra17', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra18', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
  it('vfd extra19', () => expect(validateField({ name: 'd', type: 'date' }, '2024-01-01')).toHaveLength(0));
});

describe('validateRow', () => {
  const schema = makeSchema('test', [makeField('name', 'string', true), makeField('age', 'number'), makeField('email', 'email')]);

  it('vr valid status', () => expect(validateRow(schema, { name: 'Alice', age: 30, email: 'a@b.com' }, 0).status).toBe('valid'));
  it('vr valid empty errors', () => expect(validateRow(schema, { name: 'Alice', age: 30, email: 'a@b.com' }, 0).errors).toHaveLength(0));
  it('vr missing req invalid', () => expect(validateRow(schema, { age: 30, email: 'a@b.com' }, 0).status).toBe('invalid'));
  it('vr rowIndex', () => expect(validateRow(schema, { name: 'X', age: 1, email: 'x@y.com' }, 42).rowIndex).toBe(42));
  it('vr data coerced', () => expect(validateRow(schema, { name: 'Bob', age: '25', email: 'b@c.com' }, 0).data['age']).toBe(25));
  it('vr unknown field', () => expect(validateRow(schema, { name: 'X', age: 1, email: 'x@y.com', extra: 'oops' }, 0).status).toBe('invalid'));
  it('vr allowExtra ok', () => { const s2 = makeSchema('t', [makeField('name', 'string', true)], true); expect(validateRow(s2, { name: 'X', extra: 'ok' }, 0).status).toBe('valid'); });
  it('vr pass 0', () => { const r = validateRow(schema, { name: 'U0', age: 1, email: 'u0@t.com' }, 0); expect(r.status).toBe('valid'); });
  it('vr pass 1', () => { const r = validateRow(schema, { name: 'U1', age: 2, email: 'u1@t.com' }, 1); expect(r.status).toBe('valid'); });
  it('vr pass 2', () => { const r = validateRow(schema, { name: 'U2', age: 3, email: 'u2@t.com' }, 2); expect(r.status).toBe('valid'); });
  it('vr pass 3', () => { const r = validateRow(schema, { name: 'U3', age: 4, email: 'u3@t.com' }, 3); expect(r.status).toBe('valid'); });
  it('vr pass 4', () => { const r = validateRow(schema, { name: 'U4', age: 5, email: 'u4@t.com' }, 4); expect(r.status).toBe('valid'); });
  it('vr pass 5', () => { const r = validateRow(schema, { name: 'U5', age: 6, email: 'u5@t.com' }, 5); expect(r.status).toBe('valid'); });
  it('vr pass 6', () => { const r = validateRow(schema, { name: 'U6', age: 7, email: 'u6@t.com' }, 6); expect(r.status).toBe('valid'); });
  it('vr pass 7', () => { const r = validateRow(schema, { name: 'U7', age: 8, email: 'u7@t.com' }, 7); expect(r.status).toBe('valid'); });
  it('vr pass 8', () => { const r = validateRow(schema, { name: 'U8', age: 9, email: 'u8@t.com' }, 8); expect(r.status).toBe('valid'); });
  it('vr pass 9', () => { const r = validateRow(schema, { name: 'U9', age: 10, email: 'u9@t.com' }, 9); expect(r.status).toBe('valid'); });
  it('vr pass 10', () => { const r = validateRow(schema, { name: 'U10', age: 11, email: 'u10@t.com' }, 10); expect(r.status).toBe('valid'); });
  it('vr pass 11', () => { const r = validateRow(schema, { name: 'U11', age: 12, email: 'u11@t.com' }, 11); expect(r.status).toBe('valid'); });
  it('vr pass 12', () => { const r = validateRow(schema, { name: 'U12', age: 13, email: 'u12@t.com' }, 12); expect(r.status).toBe('valid'); });
  it('vr pass 13', () => { const r = validateRow(schema, { name: 'U13', age: 14, email: 'u13@t.com' }, 13); expect(r.status).toBe('valid'); });
  it('vr pass 14', () => { const r = validateRow(schema, { name: 'U14', age: 15, email: 'u14@t.com' }, 14); expect(r.status).toBe('valid'); });
  it('vr pass 15', () => { const r = validateRow(schema, { name: 'U15', age: 16, email: 'u15@t.com' }, 15); expect(r.status).toBe('valid'); });
  it('vr pass 16', () => { const r = validateRow(schema, { name: 'U16', age: 17, email: 'u16@t.com' }, 16); expect(r.status).toBe('valid'); });
  it('vr pass 17', () => { const r = validateRow(schema, { name: 'U17', age: 18, email: 'u17@t.com' }, 17); expect(r.status).toBe('valid'); });
  it('vr pass 18', () => { const r = validateRow(schema, { name: 'U18', age: 19, email: 'u18@t.com' }, 18); expect(r.status).toBe('valid'); });
  it('vr pass 19', () => { const r = validateRow(schema, { name: 'U19', age: 20, email: 'u19@t.com' }, 19); expect(r.status).toBe('valid'); });
  it('vr pass 20', () => { const r = validateRow(schema, { name: 'U20', age: 21, email: 'u20@t.com' }, 20); expect(r.status).toBe('valid'); });
  it('vr pass 21', () => { const r = validateRow(schema, { name: 'U21', age: 22, email: 'u21@t.com' }, 21); expect(r.status).toBe('valid'); });
  it('vr pass 22', () => { const r = validateRow(schema, { name: 'U22', age: 23, email: 'u22@t.com' }, 22); expect(r.status).toBe('valid'); });
  it('vr pass 23', () => { const r = validateRow(schema, { name: 'U23', age: 24, email: 'u23@t.com' }, 23); expect(r.status).toBe('valid'); });
  it('vr pass 24', () => { const r = validateRow(schema, { name: 'U24', age: 25, email: 'u24@t.com' }, 24); expect(r.status).toBe('valid'); });
  it('vr pass 25', () => { const r = validateRow(schema, { name: 'U25', age: 26, email: 'u25@t.com' }, 25); expect(r.status).toBe('valid'); });
  it('vr pass 26', () => { const r = validateRow(schema, { name: 'U26', age: 27, email: 'u26@t.com' }, 26); expect(r.status).toBe('valid'); });
  it('vr pass 27', () => { const r = validateRow(schema, { name: 'U27', age: 28, email: 'u27@t.com' }, 27); expect(r.status).toBe('valid'); });
  it('vr pass 28', () => { const r = validateRow(schema, { name: 'U28', age: 29, email: 'u28@t.com' }, 28); expect(r.status).toBe('valid'); });
  it('vr pass 29', () => { const r = validateRow(schema, { name: 'U29', age: 30, email: 'u29@t.com' }, 29); expect(r.status).toBe('valid'); });
  it('vr pass 30', () => { const r = validateRow(schema, { name: 'U30', age: 31, email: 'u30@t.com' }, 30); expect(r.status).toBe('valid'); });
  it('vr pass 31', () => { const r = validateRow(schema, { name: 'U31', age: 32, email: 'u31@t.com' }, 31); expect(r.status).toBe('valid'); });
  it('vr pass 32', () => { const r = validateRow(schema, { name: 'U32', age: 33, email: 'u32@t.com' }, 32); expect(r.status).toBe('valid'); });
  it('vr pass 33', () => { const r = validateRow(schema, { name: 'U33', age: 34, email: 'u33@t.com' }, 33); expect(r.status).toBe('valid'); });
  it('vr pass 34', () => { const r = validateRow(schema, { name: 'U34', age: 35, email: 'u34@t.com' }, 34); expect(r.status).toBe('valid'); });
  it('vr pass 35', () => { const r = validateRow(schema, { name: 'U35', age: 36, email: 'u35@t.com' }, 35); expect(r.status).toBe('valid'); });
  it('vr pass 36', () => { const r = validateRow(schema, { name: 'U36', age: 37, email: 'u36@t.com' }, 36); expect(r.status).toBe('valid'); });
  it('vr pass 37', () => { const r = validateRow(schema, { name: 'U37', age: 38, email: 'u37@t.com' }, 37); expect(r.status).toBe('valid'); });
  it('vr pass 38', () => { const r = validateRow(schema, { name: 'U38', age: 39, email: 'u38@t.com' }, 38); expect(r.status).toBe('valid'); });
  it('vr pass 39', () => { const r = validateRow(schema, { name: 'U39', age: 40, email: 'u39@t.com' }, 39); expect(r.status).toBe('valid'); });
});

describe('validateImport', () => {
  const schema = makeSchema('emp', [makeField('name', 'string', true), makeField('age', 'number')]);

  it('vi totalRows empty', () => expect(validateImport(schema, []).totalRows).toBe(0));
  it('vi validRows empty', () => expect(validateImport(schema, []).validRows).toBe(0));
  it('vi invalidRows empty', () => expect(validateImport(schema, []).invalidRows).toBe(0));
  it('vi skippedRows', () => expect(validateImport(schema, []).skippedRows).toBe(0));
  it('vi schema name', () => expect(validateImport(schema, []).schema).toBe('emp'));
  it('vi all valid 50', () => { const rows = Array.from({ length: 50 }, (_,i) => ({ name: 'U'+i, age: i+1 })); expect(validateImport(schema, rows).validRows).toBe(50); });
  it('vi all invalid 20', () => { const rows = Array.from({ length: 20 }, () => ({ age: 1 })); expect(validateImport(schema, rows).invalidRows).toBe(20); });
  it('vi mixed', () => { const rows = [{ name: 'A', age: 1 }, { age: 2 }, { name: 'C', age: 3 }]; const r = validateImport(schema, rows); expect(r.validRows).toBe(2); expect(r.invalidRows).toBe(1); });
  it('vi total 1', () => { const rows = Array.from({ length: 1 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(1); });
  it('vi total 2', () => { const rows = Array.from({ length: 2 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(2); });
  it('vi total 3', () => { const rows = Array.from({ length: 3 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(3); });
  it('vi total 4', () => { const rows = Array.from({ length: 4 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(4); });
  it('vi total 5', () => { const rows = Array.from({ length: 5 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(5); });
  it('vi total 6', () => { const rows = Array.from({ length: 6 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(6); });
  it('vi total 7', () => { const rows = Array.from({ length: 7 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(7); });
  it('vi total 8', () => { const rows = Array.from({ length: 8 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(8); });
  it('vi total 9', () => { const rows = Array.from({ length: 9 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(9); });
  it('vi total 10', () => { const rows = Array.from({ length: 10 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(10); });
  it('vi total 11', () => { const rows = Array.from({ length: 11 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(11); });
  it('vi total 12', () => { const rows = Array.from({ length: 12 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(12); });
  it('vi total 13', () => { const rows = Array.from({ length: 13 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(13); });
  it('vi total 14', () => { const rows = Array.from({ length: 14 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(14); });
  it('vi total 15', () => { const rows = Array.from({ length: 15 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(15); });
  it('vi total 16', () => { const rows = Array.from({ length: 16 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(16); });
  it('vi total 17', () => { const rows = Array.from({ length: 17 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(17); });
  it('vi total 18', () => { const rows = Array.from({ length: 18 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(18); });
  it('vi total 19', () => { const rows = Array.from({ length: 19 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(19); });
  it('vi total 20', () => { const rows = Array.from({ length: 20 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(20); });
  it('vi total 21', () => { const rows = Array.from({ length: 21 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(21); });
  it('vi total 22', () => { const rows = Array.from({ length: 22 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(22); });
  it('vi total 23', () => { const rows = Array.from({ length: 23 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(23); });
  it('vi total 24', () => { const rows = Array.from({ length: 24 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(24); });
  it('vi total 25', () => { const rows = Array.from({ length: 25 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(25); });
  it('vi total 26', () => { const rows = Array.from({ length: 26 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(26); });
  it('vi total 27', () => { const rows = Array.from({ length: 27 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(27); });
  it('vi total 28', () => { const rows = Array.from({ length: 28 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(28); });
  it('vi total 29', () => { const rows = Array.from({ length: 29 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(29); });
  it('vi total 30', () => { const rows = Array.from({ length: 30 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(30); });
  it('vi total 31', () => { const rows = Array.from({ length: 31 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(31); });
  it('vi total 32', () => { const rows = Array.from({ length: 32 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(32); });
  it('vi total 33', () => { const rows = Array.from({ length: 33 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(33); });
  it('vi total 34', () => { const rows = Array.from({ length: 34 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(34); });
  it('vi total 35', () => { const rows = Array.from({ length: 35 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(35); });
  it('vi total 36', () => { const rows = Array.from({ length: 36 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(36); });
  it('vi total 37', () => { const rows = Array.from({ length: 37 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(37); });
  it('vi total 38', () => { const rows = Array.from({ length: 38 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(38); });
  it('vi total 39', () => { const rows = Array.from({ length: 39 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(39); });
  it('vi total 40', () => { const rows = Array.from({ length: 40 }, (_,j) => ({ name: 'N'+j, age: j+1 })); expect(validateImport(schema, rows).totalRows).toBe(40); });
});

describe('summariseErrors', () => {
  it('se empty', () => expect(summariseErrors(makeResult(5, 0))).toEqual({}));
  it('se counts', () => { const errs = [{ field: 'name', message: 'req', value: null }, { field: 'name', message: 'req', value: null }, { field: 'age', message: 'inv', value: 'x' }]; const r = makeResult(0, 3, errs); const s = summariseErrors(r); expect(s['name']).toBe(2); expect(s['age']).toBe(1); });
  it('se field0', () => { const e = [{ field: 'field0', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field0']).toBe(1); });
  it('se field1', () => { const e = [{ field: 'field1', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field1']).toBe(1); });
  it('se field2', () => { const e = [{ field: 'field2', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field2']).toBe(1); });
  it('se field3', () => { const e = [{ field: 'field3', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field3']).toBe(1); });
  it('se field4', () => { const e = [{ field: 'field4', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field4']).toBe(1); });
  it('se field5', () => { const e = [{ field: 'field5', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field5']).toBe(1); });
  it('se field6', () => { const e = [{ field: 'field6', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field6']).toBe(1); });
  it('se field7', () => { const e = [{ field: 'field7', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field7']).toBe(1); });
  it('se field8', () => { const e = [{ field: 'field8', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field8']).toBe(1); });
  it('se field9', () => { const e = [{ field: 'field9', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field9']).toBe(1); });
  it('se field10', () => { const e = [{ field: 'field10', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field10']).toBe(1); });
  it('se field11', () => { const e = [{ field: 'field11', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field11']).toBe(1); });
  it('se field12', () => { const e = [{ field: 'field12', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field12']).toBe(1); });
  it('se field13', () => { const e = [{ field: 'field13', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field13']).toBe(1); });
  it('se field14', () => { const e = [{ field: 'field14', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field14']).toBe(1); });
  it('se field15', () => { const e = [{ field: 'field15', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field15']).toBe(1); });
  it('se field16', () => { const e = [{ field: 'field16', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field16']).toBe(1); });
  it('se field17', () => { const e = [{ field: 'field17', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field17']).toBe(1); });
  it('se field18', () => { const e = [{ field: 'field18', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field18']).toBe(1); });
  it('se field19', () => { const e = [{ field: 'field19', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field19']).toBe(1); });
  it('se field20', () => { const e = [{ field: 'field20', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field20']).toBe(1); });
  it('se field21', () => { const e = [{ field: 'field21', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field21']).toBe(1); });
  it('se field22', () => { const e = [{ field: 'field22', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field22']).toBe(1); });
  it('se field23', () => { const e = [{ field: 'field23', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field23']).toBe(1); });
  it('se field24', () => { const e = [{ field: 'field24', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field24']).toBe(1); });
  it('se field25', () => { const e = [{ field: 'field25', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field25']).toBe(1); });
  it('se field26', () => { const e = [{ field: 'field26', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field26']).toBe(1); });
  it('se field27', () => { const e = [{ field: 'field27', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field27']).toBe(1); });
  it('se field28', () => { const e = [{ field: 'field28', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field28']).toBe(1); });
  it('se field29', () => { const e = [{ field: 'field29', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field29']).toBe(1); });
  it('se field30', () => { const e = [{ field: 'field30', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field30']).toBe(1); });
  it('se field31', () => { const e = [{ field: 'field31', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field31']).toBe(1); });
  it('se field32', () => { const e = [{ field: 'field32', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field32']).toBe(1); });
  it('se field33', () => { const e = [{ field: 'field33', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field33']).toBe(1); });
  it('se field34', () => { const e = [{ field: 'field34', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field34']).toBe(1); });
  it('se field35', () => { const e = [{ field: 'field35', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field35']).toBe(1); });
  it('se field36', () => { const e = [{ field: 'field36', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field36']).toBe(1); });
  it('se field37', () => { const e = [{ field: 'field37', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field37']).toBe(1); });
  it('se field38', () => { const e = [{ field: 'field38', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field38']).toBe(1); });
  it('se field39', () => { const e = [{ field: 'field39', message: 'e', value: null }]; expect(summariseErrors(makeResult(0, 1, e))['field39']).toBe(1); });
});

describe('validRowsOnly', () => {
  const sch = makeSchema('t', [makeField('n', 'string', true)]);

  it('vro 2 valid', () => { const rows = [{ n: 'a' }, { n: 'b' }, {}]; expect(validRowsOnly(validateImport(sch, rows))).toHaveLength(2); });
  it('vro empty', () => expect(validRowsOnly(makeResult(0, 0))).toHaveLength(0));
  it('vro all valid', () => expect(validRowsOnly(makeResult(5, 0))).toHaveLength(5));
  it('vro all invalid', () => expect(validRowsOnly(makeResult(0, 5))).toHaveLength(0));
  it('vro returns data', () => { const rows = [{ n: 'x' }]; const r = validateImport(sch, rows); expect(validRowsOnly(r)[0]).toHaveProperty('n'); });
  it('vro count 1', () => expect(validRowsOnly(makeResult(1, 0))).toHaveLength(1));
  it('vro count 2', () => expect(validRowsOnly(makeResult(2, 0))).toHaveLength(2));
  it('vro count 3', () => expect(validRowsOnly(makeResult(3, 0))).toHaveLength(3));
  it('vro count 4', () => expect(validRowsOnly(makeResult(4, 0))).toHaveLength(4));
  it('vro count 5', () => expect(validRowsOnly(makeResult(5, 0))).toHaveLength(5));
  it('vro count 6', () => expect(validRowsOnly(makeResult(6, 0))).toHaveLength(6));
  it('vro count 7', () => expect(validRowsOnly(makeResult(7, 0))).toHaveLength(7));
  it('vro count 8', () => expect(validRowsOnly(makeResult(8, 0))).toHaveLength(8));
  it('vro count 9', () => expect(validRowsOnly(makeResult(9, 0))).toHaveLength(9));
  it('vro count 10', () => expect(validRowsOnly(makeResult(10, 0))).toHaveLength(10));
  it('vro count 11', () => expect(validRowsOnly(makeResult(11, 0))).toHaveLength(11));
  it('vro count 12', () => expect(validRowsOnly(makeResult(12, 0))).toHaveLength(12));
  it('vro count 13', () => expect(validRowsOnly(makeResult(13, 0))).toHaveLength(13));
  it('vro count 14', () => expect(validRowsOnly(makeResult(14, 0))).toHaveLength(14));
  it('vro count 15', () => expect(validRowsOnly(makeResult(15, 0))).toHaveLength(15));
  it('vro count 16', () => expect(validRowsOnly(makeResult(16, 0))).toHaveLength(16));
  it('vro count 17', () => expect(validRowsOnly(makeResult(17, 0))).toHaveLength(17));
  it('vro count 18', () => expect(validRowsOnly(makeResult(18, 0))).toHaveLength(18));
  it('vro count 19', () => expect(validRowsOnly(makeResult(19, 0))).toHaveLength(19));
  it('vro count 20', () => expect(validRowsOnly(makeResult(20, 0))).toHaveLength(20));
  it('vro count 21', () => expect(validRowsOnly(makeResult(21, 0))).toHaveLength(21));
  it('vro count 22', () => expect(validRowsOnly(makeResult(22, 0))).toHaveLength(22));
  it('vro count 23', () => expect(validRowsOnly(makeResult(23, 0))).toHaveLength(23));
  it('vro count 24', () => expect(validRowsOnly(makeResult(24, 0))).toHaveLength(24));
  it('vro count 25', () => expect(validRowsOnly(makeResult(25, 0))).toHaveLength(25));
  it('vro count 26', () => expect(validRowsOnly(makeResult(26, 0))).toHaveLength(26));
  it('vro count 27', () => expect(validRowsOnly(makeResult(27, 0))).toHaveLength(27));
  it('vro count 28', () => expect(validRowsOnly(makeResult(28, 0))).toHaveLength(28));
  it('vro count 29', () => expect(validRowsOnly(makeResult(29, 0))).toHaveLength(29));
  it('vro count 30', () => expect(validRowsOnly(makeResult(30, 0))).toHaveLength(30));
  it('vro count 31', () => expect(validRowsOnly(makeResult(31, 0))).toHaveLength(31));
  it('vro count 32', () => expect(validRowsOnly(makeResult(32, 0))).toHaveLength(32));
  it('vro count 33', () => expect(validRowsOnly(makeResult(33, 0))).toHaveLength(33));
  it('vro count 34', () => expect(validRowsOnly(makeResult(34, 0))).toHaveLength(34));
  it('vro count 35', () => expect(validRowsOnly(makeResult(35, 0))).toHaveLength(35));
  it('vro count 36', () => expect(validRowsOnly(makeResult(36, 0))).toHaveLength(36));
  it('vro count 37', () => expect(validRowsOnly(makeResult(37, 0))).toHaveLength(37));
  it('vro count 38', () => expect(validRowsOnly(makeResult(38, 0))).toHaveLength(38));
  it('vro count 39', () => expect(validRowsOnly(makeResult(39, 0))).toHaveLength(39));
  it('vro count 40', () => expect(validRowsOnly(makeResult(40, 0))).toHaveLength(40));
});

describe('importPassRate', () => {
  it('ipr 0 rows', () => expect(importPassRate(makeResult(0, 0))).toBe(100));
  it('ipr all valid', () => expect(importPassRate(makeResult(10, 0))).toBe(100));
  it('ipr all invalid', () => expect(importPassRate(makeResult(0, 10))).toBe(0));
  it('ipr 50/100', () => expect(importPassRate(makeResult(50, 50))).toBe(50));
  it('ipr 75/100', () => expect(importPassRate(makeResult(75, 25))).toBe(75));
  it('ipr 1/4', () => expect(importPassRate(makeResult(1, 3))).toBe(25));
  it('ipr 3/4', () => expect(importPassRate(makeResult(3, 1))).toBe(75));
  it('ipr 1/100', () => expect(importPassRate(makeResult(1, 99))) .toBe(1));
  it('ipr 2/100', () => expect(importPassRate(makeResult(2, 98))) .toBe(2));
  it('ipr 3/100', () => expect(importPassRate(makeResult(3, 97))) .toBe(3));
  it('ipr 4/100', () => expect(importPassRate(makeResult(4, 96))) .toBe(4));
  it('ipr 5/100', () => expect(importPassRate(makeResult(5, 95))) .toBe(5));
  it('ipr 6/100', () => expect(importPassRate(makeResult(6, 94))) .toBe(6));
  it('ipr 7/100', () => expect(importPassRate(makeResult(7, 93))) .toBe(7));
  it('ipr 8/100', () => expect(importPassRate(makeResult(8, 92))) .toBe(8));
  it('ipr 9/100', () => expect(importPassRate(makeResult(9, 91))) .toBe(9));
  it('ipr 10/100', () => expect(importPassRate(makeResult(10, 90))) .toBe(10));
  it('ipr 11/100', () => expect(importPassRate(makeResult(11, 89))) .toBe(11));
  it('ipr 12/100', () => expect(importPassRate(makeResult(12, 88))) .toBe(12));
  it('ipr 13/100', () => expect(importPassRate(makeResult(13, 87))) .toBe(13));
  it('ipr 14/100', () => expect(importPassRate(makeResult(14, 86))) .toBe(14));
  it('ipr 15/100', () => expect(importPassRate(makeResult(15, 85))) .toBe(15));
  it('ipr 16/100', () => expect(importPassRate(makeResult(16, 84))) .toBe(16));
  it('ipr 17/100', () => expect(importPassRate(makeResult(17, 83))) .toBe(17));
  it('ipr 18/100', () => expect(importPassRate(makeResult(18, 82))) .toBe(18));
  it('ipr 19/100', () => expect(importPassRate(makeResult(19, 81))) .toBe(19));
  it('ipr 20/100', () => expect(importPassRate(makeResult(20, 80))) .toBe(20));
  it('ipr 21/100', () => expect(importPassRate(makeResult(21, 79))) .toBe(21));
  it('ipr 22/100', () => expect(importPassRate(makeResult(22, 78))) .toBe(22));
  it('ipr 23/100', () => expect(importPassRate(makeResult(23, 77))) .toBe(23));
  it('ipr 24/100', () => expect(importPassRate(makeResult(24, 76))) .toBe(24));
  it('ipr 25/100', () => expect(importPassRate(makeResult(25, 75))) .toBe(25));
  it('ipr 26/100', () => expect(importPassRate(makeResult(26, 74))) .toBe(26));
  it('ipr 27/100', () => expect(importPassRate(makeResult(27, 73))) .toBe(27));
  it('ipr 28/100', () => expect(importPassRate(makeResult(28, 72))) .toBe(28));
  it('ipr 29/100', () => expect(importPassRate(makeResult(29, 71))) .toBe(29));
  it('ipr 30/100', () => expect(importPassRate(makeResult(30, 70))) .toBe(30));
  it('ipr 31/100', () => expect(importPassRate(makeResult(31, 69))) .toBe(31));
  it('ipr 32/100', () => expect(importPassRate(makeResult(32, 68))) .toBe(32));
  it('ipr 33/100', () => expect(importPassRate(makeResult(33, 67))) .toBe(33));
  it('ipr 34/100', () => expect(importPassRate(makeResult(34, 66))) .toBe(34));
  it('ipr 35/100', () => expect(importPassRate(makeResult(35, 65))) .toBe(35));
  it('ipr 36/100', () => expect(importPassRate(makeResult(36, 64))) .toBe(36));
  it('ipr 37/100', () => expect(importPassRate(makeResult(37, 63))) .toBe(37));
  it('ipr 38/100', () => expect(importPassRate(makeResult(38, 62))) .toBe(38));
  it('ipr 39/100', () => expect(importPassRate(makeResult(39, 61))) .toBe(39));
  it('ipr 40/100', () => expect(importPassRate(makeResult(40, 60))) .toBe(40));
  it('ipr 41/100', () => expect(importPassRate(makeResult(41, 59))) .toBe(41));
  it('ipr 42/100', () => expect(importPassRate(makeResult(42, 58))) .toBe(42));
  it('ipr 43/100', () => expect(importPassRate(makeResult(43, 57))) .toBe(43));
  it('ipr 44/100', () => expect(importPassRate(makeResult(44, 56))) .toBe(44));
  it('ipr 45/100', () => expect(importPassRate(makeResult(45, 55))) .toBe(45));
  it('ipr 46/100', () => expect(importPassRate(makeResult(46, 54))) .toBe(46));
  it('ipr 47/100', () => expect(importPassRate(makeResult(47, 53))) .toBe(47));
  it('ipr 48/100', () => expect(importPassRate(makeResult(48, 52))) .toBe(48));
  it('ipr 49/100', () => expect(importPassRate(makeResult(49, 51))) .toBe(49));
  it('ipr 50/100', () => expect(importPassRate(makeResult(50, 50))) .toBe(50));
  it('ipr 51/100', () => expect(importPassRate(makeResult(51, 49))) .toBe(51));
  it('ipr 52/100', () => expect(importPassRate(makeResult(52, 48))) .toBe(52));
  it('ipr 53/100', () => expect(importPassRate(makeResult(53, 47))) .toBe(53));
  it('ipr 54/100', () => expect(importPassRate(makeResult(54, 46))) .toBe(54));
  it('ipr 55/100', () => expect(importPassRate(makeResult(55, 45))) .toBe(55));
  it('ipr 56/100', () => expect(importPassRate(makeResult(56, 44))) .toBe(56));
  it('ipr 57/100', () => expect(importPassRate(makeResult(57, 43))) .toBe(57));
  it('ipr 58/100', () => expect(importPassRate(makeResult(58, 42))) .toBe(58));
  it('ipr 59/100', () => expect(importPassRate(makeResult(59, 41))) .toBe(59));
  it('ipr 60/100', () => expect(importPassRate(makeResult(60, 40))) .toBe(60));
  it('ipr 61/100', () => expect(importPassRate(makeResult(61, 39))) .toBe(61));
  it('ipr 62/100', () => expect(importPassRate(makeResult(62, 38))) .toBe(62));
  it('ipr 63/100', () => expect(importPassRate(makeResult(63, 37))) .toBe(63));
  it('ipr 64/100', () => expect(importPassRate(makeResult(64, 36))) .toBe(64));
  it('ipr 65/100', () => expect(importPassRate(makeResult(65, 35))) .toBe(65));
  it('ipr 66/100', () => expect(importPassRate(makeResult(66, 34))) .toBe(66));
  it('ipr 67/100', () => expect(importPassRate(makeResult(67, 33))) .toBe(67));
  it('ipr 68/100', () => expect(importPassRate(makeResult(68, 32))) .toBe(68));
  it('ipr 69/100', () => expect(importPassRate(makeResult(69, 31))) .toBe(69));
  it('ipr 70/100', () => expect(importPassRate(makeResult(70, 30))) .toBe(70));
  it('ipr 71/100', () => expect(importPassRate(makeResult(71, 29))) .toBe(71));
  it('ipr 72/100', () => expect(importPassRate(makeResult(72, 28))) .toBe(72));
  it('ipr 73/100', () => expect(importPassRate(makeResult(73, 27))) .toBe(73));
  it('ipr 74/100', () => expect(importPassRate(makeResult(74, 26))) .toBe(74));
  it('ipr 75/100', () => expect(importPassRate(makeResult(75, 25))) .toBe(75));
  it('ipr 76/100', () => expect(importPassRate(makeResult(76, 24))) .toBe(76));
  it('ipr 77/100', () => expect(importPassRate(makeResult(77, 23))) .toBe(77));
  it('ipr 78/100', () => expect(importPassRate(makeResult(78, 22))) .toBe(78));
  it('ipr 79/100', () => expect(importPassRate(makeResult(79, 21))) .toBe(79));
  it('ipr 80/100', () => expect(importPassRate(makeResult(80, 20))) .toBe(80));
  it('ipr 81/100', () => expect(importPassRate(makeResult(81, 19))) .toBe(81));
  it('ipr 82/100', () => expect(importPassRate(makeResult(82, 18))) .toBe(82));
  it('ipr 83/100', () => expect(importPassRate(makeResult(83, 17))) .toBe(83));
  it('ipr 84/100', () => expect(importPassRate(makeResult(84, 16))) .toBe(84));
  it('ipr 85/100', () => expect(importPassRate(makeResult(85, 15))) .toBe(85));
  it('ipr 86/100', () => expect(importPassRate(makeResult(86, 14))) .toBe(86));
  it('ipr 87/100', () => expect(importPassRate(makeResult(87, 13))) .toBe(87));
  it('ipr 88/100', () => expect(importPassRate(makeResult(88, 12))) .toBe(88));
  it('ipr 89/100', () => expect(importPassRate(makeResult(89, 11))) .toBe(89));
  it('ipr 90/100', () => expect(importPassRate(makeResult(90, 10))) .toBe(90));
  it('ipr 91/100', () => expect(importPassRate(makeResult(91, 9))) .toBe(91));
  it('ipr 92/100', () => expect(importPassRate(makeResult(92, 8))) .toBe(92));
  it('ipr 93/100', () => expect(importPassRate(makeResult(93, 7))) .toBe(93));
  it('ipr 94/100', () => expect(importPassRate(makeResult(94, 6))) .toBe(94));
  it('ipr 95/100', () => expect(importPassRate(makeResult(95, 5))) .toBe(95));
  it('ipr 96/100', () => expect(importPassRate(makeResult(96, 4))) .toBe(96));
  it('ipr 97/100', () => expect(importPassRate(makeResult(97, 3))) .toBe(97));
  it('ipr 98/100', () => expect(importPassRate(makeResult(98, 2))) .toBe(98));
  it('ipr 99/100', () => expect(importPassRate(makeResult(99, 1))) .toBe(99));
});

describe('FieldError shape', () => {
  TYPES.forEach(t => {
    it('fe field:' + t, () => { const e = validateField({ name: 'x', type: t, required: true }, null); expect(e[0]).toHaveProperty('field', 'x'); });
    it('fe message:' + t, () => { const e = validateField({ name: 'x', type: t, required: true }, null); expect(e[0]).toHaveProperty('message'); });
    it('fe value:' + t, () => { const e = validateField({ name: 'x', type: t, required: true }, null); expect(e[0]).toHaveProperty('value'); });
  });
});

describe('RowResult shape', () => {
  const s = makeSchema('s', [makeField('x', 'string', true)]);
  it('rr rowIndex', () => expect(validateRow(s, { x: 'a' }, 5)).toHaveProperty('rowIndex', 5));
  it('rr status', () => expect(validateRow(s, { x: 'a' }, 0)).toHaveProperty('status'));
  it('rr data', () => expect(validateRow(s, { x: 'a' }, 0)).toHaveProperty('data'));
  it('rr errors array', () => expect(validateRow(s, { x: 'a' }, 0).errors).toBeInstanceOf(Array));
  it('rr idx 0', () => expect(validateRow(s, { x: 'v' }, 0).rowIndex).toBe(0));
  it('rr idx 1', () => expect(validateRow(s, { x: 'v' }, 1).rowIndex).toBe(1));
  it('rr idx 2', () => expect(validateRow(s, { x: 'v' }, 2).rowIndex).toBe(2));
  it('rr idx 3', () => expect(validateRow(s, { x: 'v' }, 3).rowIndex).toBe(3));
  it('rr idx 4', () => expect(validateRow(s, { x: 'v' }, 4).rowIndex).toBe(4));
  it('rr idx 5', () => expect(validateRow(s, { x: 'v' }, 5).rowIndex).toBe(5));
  it('rr idx 6', () => expect(validateRow(s, { x: 'v' }, 6).rowIndex).toBe(6));
  it('rr idx 7', () => expect(validateRow(s, { x: 'v' }, 7).rowIndex).toBe(7));
  it('rr idx 8', () => expect(validateRow(s, { x: 'v' }, 8).rowIndex).toBe(8));
  it('rr idx 9', () => expect(validateRow(s, { x: 'v' }, 9).rowIndex).toBe(9));
  it('rr idx 10', () => expect(validateRow(s, { x: 'v' }, 10).rowIndex).toBe(10));
  it('rr idx 11', () => expect(validateRow(s, { x: 'v' }, 11).rowIndex).toBe(11));
  it('rr idx 12', () => expect(validateRow(s, { x: 'v' }, 12).rowIndex).toBe(12));
  it('rr idx 13', () => expect(validateRow(s, { x: 'v' }, 13).rowIndex).toBe(13));
  it('rr idx 14', () => expect(validateRow(s, { x: 'v' }, 14).rowIndex).toBe(14));
  it('rr idx 15', () => expect(validateRow(s, { x: 'v' }, 15).rowIndex).toBe(15));
  it('rr idx 16', () => expect(validateRow(s, { x: 'v' }, 16).rowIndex).toBe(16));
  it('rr idx 17', () => expect(validateRow(s, { x: 'v' }, 17).rowIndex).toBe(17));
  it('rr idx 18', () => expect(validateRow(s, { x: 'v' }, 18).rowIndex).toBe(18));
  it('rr idx 19', () => expect(validateRow(s, { x: 'v' }, 19).rowIndex).toBe(19));
});

describe('ImportResult shape', () => {
  const s = makeSchema('myschema', [makeField('n', 'string', true)]);
  it('ir schema', () => expect(validateImport(s, []).schema).toBe('myschema'));
  it('ir totalRows', () => expect(validateImport(s, []).totalRows).toBe(0));
  it('ir validRows', () => expect(validateImport(s, []).validRows).toBeDefined());
  it('ir invalidRows', () => expect(validateImport(s, []).invalidRows).toBeDefined());
  it('ir skippedRows', () => expect(validateImport(s, []).skippedRows).toBe(0));
  it('ir rows array', () => expect(validateImport(s, []).rows).toBeInstanceOf(Array));
  it('ir errors array', () => expect(validateImport(s, []).errors).toBeInstanceOf(Array));
  it('ir schema s1', () => { const sc = makeSchema('s1', []); expect(validateImport(sc, []).schema).toBe('s1'); });
  it('ir schema s2', () => { const sc = makeSchema('s2', []); expect(validateImport(sc, []).schema).toBe('s2'); });
  it('ir schema s3', () => { const sc = makeSchema('s3', []); expect(validateImport(sc, []).schema).toBe('s3'); });
  it('ir schema s4', () => { const sc = makeSchema('s4', []); expect(validateImport(sc, []).schema).toBe('s4'); });
  it('ir schema s5', () => { const sc = makeSchema('s5', []); expect(validateImport(sc, []).schema).toBe('s5'); });
  it('ir schema s6', () => { const sc = makeSchema('s6', []); expect(validateImport(sc, []).schema).toBe('s6'); });
  it('ir schema s7', () => { const sc = makeSchema('s7', []); expect(validateImport(sc, []).schema).toBe('s7'); });
  it('ir schema s8', () => { const sc = makeSchema('s8', []); expect(validateImport(sc, []).schema).toBe('s8'); });
  it('ir schema s9', () => { const sc = makeSchema('s9', []); expect(validateImport(sc, []).schema).toBe('s9'); });
  it('ir schema s10', () => { const sc = makeSchema('s10', []); expect(validateImport(sc, []).schema).toBe('s10'); });
  it('ir schema s11', () => { const sc = makeSchema('s11', []); expect(validateImport(sc, []).schema).toBe('s11'); });
  it('ir schema s12', () => { const sc = makeSchema('s12', []); expect(validateImport(sc, []).schema).toBe('s12'); });
  it('ir schema s13', () => { const sc = makeSchema('s13', []); expect(validateImport(sc, []).schema).toBe('s13'); });
  it('ir schema s14', () => { const sc = makeSchema('s14', []); expect(validateImport(sc, []).schema).toBe('s14'); });
  it('ir schema s15', () => { const sc = makeSchema('s15', []); expect(validateImport(sc, []).schema).toBe('s15'); });
});

describe('edge cases', () => {
  it('ec large batch', () => { const s = makeSchema('big', [makeField('id', 'number', true), makeField('name', 'string', true)]); const rows = Array.from({ length: 200 }, (_,i) => ({ id: i+1, name: 'Item'+i })); const r = validateImport(s, rows); expect(r.totalRows).toBe(200); expect(r.validRows).toBe(200); });
  it('ec all invalid batch', () => { const s = makeSchema('bad', [makeField('x', 'number', true)]); const rows = Array.from({ length: 100 }, () => ({})); expect(validateImport(s, rows).invalidRows).toBe(100); });
  it('ec multi errors', () => { const s = makeSchema('m', [makeField('a', 'string', true), makeField('b', 'email', true), makeField('c', 'number')]); const row = { a: 'ok', b: 'bad-email', c: 'not-a-num' }; expect(validateRow(s, row, 0).status).toBe('invalid'); });
  it('ec passRate rounds', () => expect(importPassRate(makeResult(1, 2))).toBe(33));
  it('ec summarise many', () => { const errs = Array.from({ length: 10 }, (_,i) => ({ field: 'f'+i, message: 'e', value: null })); const r = makeResult(0, 10, errs); expect(Object.keys(summariseErrors(r))).toHaveLength(10); });
  it('ec coerce 150', () => expect(coerceType(150, 'number')).toBe(150));
  it('ec coerce 151', () => expect(coerceType(151, 'number')).toBe(151));
  it('ec coerce 152', () => expect(coerceType(152, 'number')).toBe(152));
  it('ec coerce 153', () => expect(coerceType(153, 'number')).toBe(153));
  it('ec coerce 154', () => expect(coerceType(154, 'number')).toBe(154));
  it('ec coerce 155', () => expect(coerceType(155, 'number')).toBe(155));
  it('ec coerce 156', () => expect(coerceType(156, 'number')).toBe(156));
  it('ec coerce 157', () => expect(coerceType(157, 'number')).toBe(157));
  it('ec coerce 158', () => expect(coerceType(158, 'number')).toBe(158));
  it('ec coerce 159', () => expect(coerceType(159, 'number')).toBe(159));
  it('ec coerce 160', () => expect(coerceType(160, 'number')).toBe(160));
  it('ec coerce 161', () => expect(coerceType(161, 'number')).toBe(161));
  it('ec coerce 162', () => expect(coerceType(162, 'number')).toBe(162));
  it('ec coerce 163', () => expect(coerceType(163, 'number')).toBe(163));
  it('ec coerce 164', () => expect(coerceType(164, 'number')).toBe(164));
  it('ec coerce 165', () => expect(coerceType(165, 'number')).toBe(165));
  it('ec coerce 166', () => expect(coerceType(166, 'number')).toBe(166));
  it('ec coerce 167', () => expect(coerceType(167, 'number')).toBe(167));
  it('ec coerce 168', () => expect(coerceType(168, 'number')).toBe(168));
  it('ec coerce 169', () => expect(coerceType(169, 'number')).toBe(169));
  it('ec coerce 170', () => expect(coerceType(170, 'number')).toBe(170));
  it('ec coerce 171', () => expect(coerceType(171, 'number')).toBe(171));
  it('ec coerce 172', () => expect(coerceType(172, 'number')).toBe(172));
  it('ec coerce 173', () => expect(coerceType(173, 'number')).toBe(173));
  it('ec coerce 174', () => expect(coerceType(174, 'number')).toBe(174));
  it('ec coerce 175', () => expect(coerceType(175, 'number')).toBe(175));
  it('ec coerce 176', () => expect(coerceType(176, 'number')).toBe(176));
  it('ec coerce 177', () => expect(coerceType(177, 'number')).toBe(177));
  it('ec coerce 178', () => expect(coerceType(178, 'number')).toBe(178));
  it('ec coerce 179', () => expect(coerceType(179, 'number')).toBe(179));
  it('ec coerce 180', () => expect(coerceType(180, 'number')).toBe(180));
  it('ec coerce 181', () => expect(coerceType(181, 'number')).toBe(181));
  it('ec coerce 182', () => expect(coerceType(182, 'number')).toBe(182));
  it('ec coerce 183', () => expect(coerceType(183, 'number')).toBe(183));
  it('ec coerce 184', () => expect(coerceType(184, 'number')).toBe(184));
  it('ec coerce 185', () => expect(coerceType(185, 'number')).toBe(185));
  it('ec coerce 186', () => expect(coerceType(186, 'number')).toBe(186));
  it('ec coerce 187', () => expect(coerceType(187, 'number')).toBe(187));
  it('ec coerce 188', () => expect(coerceType(188, 'number')).toBe(188));
  it('ec coerce 189', () => expect(coerceType(189, 'number')).toBe(189));
  it('ec coerce 190', () => expect(coerceType(190, 'number')).toBe(190));
  it('ec coerce 191', () => expect(coerceType(191, 'number')).toBe(191));
  it('ec coerce 192', () => expect(coerceType(192, 'number')).toBe(192));
  it('ec coerce 193', () => expect(coerceType(193, 'number')).toBe(193));
  it('ec coerce 194', () => expect(coerceType(194, 'number')).toBe(194));
  it('ec coerce 195', () => expect(coerceType(195, 'number')).toBe(195));
  it('ec coerce 196', () => expect(coerceType(196, 'number')).toBe(196));
  it('ec coerce 197', () => expect(coerceType(197, 'number')).toBe(197));
  it('ec coerce 198', () => expect(coerceType(198, 'number')).toBe(198));
  it('ec coerce 199', () => expect(coerceType(199, 'number')).toBe(199));
  it('ec rate 0%', () => expect(importPassRate(makeResult(0, 100))) .toBe(0));
  it('ec rate 5%', () => expect(importPassRate(makeResult(5, 95))) .toBe(5));
  it('ec rate 10%', () => expect(importPassRate(makeResult(10, 90))) .toBe(10));
  it('ec rate 15%', () => expect(importPassRate(makeResult(15, 85))) .toBe(15));
  it('ec rate 20%', () => expect(importPassRate(makeResult(20, 80))) .toBe(20));
  it('ec rate 25%', () => expect(importPassRate(makeResult(25, 75))) .toBe(25));
  it('ec rate 30%', () => expect(importPassRate(makeResult(30, 70))) .toBe(30));
  it('ec rate 35%', () => expect(importPassRate(makeResult(35, 65))) .toBe(35));
  it('ec rate 40%', () => expect(importPassRate(makeResult(40, 60))) .toBe(40));
  it('ec rate 45%', () => expect(importPassRate(makeResult(45, 55))) .toBe(45));
  it('ec rate 50%', () => expect(importPassRate(makeResult(50, 50))) .toBe(50));
  it('ec rate 55%', () => expect(importPassRate(makeResult(55, 45))) .toBe(55));
  it('ec rate 60%', () => expect(importPassRate(makeResult(60, 40))) .toBe(60));
  it('ec rate 65%', () => expect(importPassRate(makeResult(65, 35))) .toBe(65));
  it('ec rate 70%', () => expect(importPassRate(makeResult(70, 30))) .toBe(70));
  it('ec rate 75%', () => expect(importPassRate(makeResult(75, 25))) .toBe(75));
  it('ec rate 80%', () => expect(importPassRate(makeResult(80, 20))) .toBe(80));
  it('ec rate 85%', () => expect(importPassRate(makeResult(85, 15))) .toBe(85));
  it('ec rate 90%', () => expect(importPassRate(makeResult(90, 10))) .toBe(90));
  it('ec rate 95%', () => expect(importPassRate(makeResult(95, 5))) .toBe(95));
  it('ec rate 100%', () => expect(importPassRate(makeResult(100, 0))) .toBe(100));
});

describe('coerceType extra', () => {
  it('cex num 200', () => expect(coerceType(200, 'number')).toBe(200));
  it('cex num 201', () => expect(coerceType(201, 'number')).toBe(201));
  it('cex num 202', () => expect(coerceType(202, 'number')).toBe(202));
  it('cex num 203', () => expect(coerceType(203, 'number')).toBe(203));
  it('cex num 204', () => expect(coerceType(204, 'number')).toBe(204));
  it('cex num 205', () => expect(coerceType(205, 'number')).toBe(205));
  it('cex num 206', () => expect(coerceType(206, 'number')).toBe(206));
  it('cex num 207', () => expect(coerceType(207, 'number')).toBe(207));
  it('cex num 208', () => expect(coerceType(208, 'number')).toBe(208));
  it('cex num 209', () => expect(coerceType(209, 'number')).toBe(209));
  it('cex num 210', () => expect(coerceType(210, 'number')).toBe(210));
  it('cex num 211', () => expect(coerceType(211, 'number')).toBe(211));
  it('cex num 212', () => expect(coerceType(212, 'number')).toBe(212));
  it('cex num 213', () => expect(coerceType(213, 'number')).toBe(213));
  it('cex num 214', () => expect(coerceType(214, 'number')).toBe(214));
  it('cex num 215', () => expect(coerceType(215, 'number')).toBe(215));
  it('cex num 216', () => expect(coerceType(216, 'number')).toBe(216));
  it('cex num 217', () => expect(coerceType(217, 'number')).toBe(217));
  it('cex num 218', () => expect(coerceType(218, 'number')).toBe(218));
  it('cex num 219', () => expect(coerceType(219, 'number')).toBe(219));
  it('cex num 220', () => expect(coerceType(220, 'number')).toBe(220));
  it('cex num 221', () => expect(coerceType(221, 'number')).toBe(221));
  it('cex num 222', () => expect(coerceType(222, 'number')).toBe(222));
  it('cex num 223', () => expect(coerceType(223, 'number')).toBe(223));
  it('cex num 224', () => expect(coerceType(224, 'number')).toBe(224));
  it('cex num 225', () => expect(coerceType(225, 'number')).toBe(225));
  it('cex num 226', () => expect(coerceType(226, 'number')).toBe(226));
  it('cex num 227', () => expect(coerceType(227, 'number')).toBe(227));
  it('cex num 228', () => expect(coerceType(228, 'number')).toBe(228));
  it('cex num 229', () => expect(coerceType(229, 'number')).toBe(229));
  it('cex num 230', () => expect(coerceType(230, 'number')).toBe(230));
  it('cex num 231', () => expect(coerceType(231, 'number')).toBe(231));
  it('cex num 232', () => expect(coerceType(232, 'number')).toBe(232));
  it('cex num 233', () => expect(coerceType(233, 'number')).toBe(233));
  it('cex num 234', () => expect(coerceType(234, 'number')).toBe(234));
  it('cex num 235', () => expect(coerceType(235, 'number')).toBe(235));
  it('cex num 236', () => expect(coerceType(236, 'number')).toBe(236));
  it('cex num 237', () => expect(coerceType(237, 'number')).toBe(237));
  it('cex num 238', () => expect(coerceType(238, 'number')).toBe(238));
  it('cex num 239', () => expect(coerceType(239, 'number')).toBe(239));
  it('cex num 240', () => expect(coerceType(240, 'number')).toBe(240));
  it('cex num 241', () => expect(coerceType(241, 'number')).toBe(241));
  it('cex num 242', () => expect(coerceType(242, 'number')).toBe(242));
  it('cex num 243', () => expect(coerceType(243, 'number')).toBe(243));
  it('cex num 244', () => expect(coerceType(244, 'number')).toBe(244));
  it('cex num 245', () => expect(coerceType(245, 'number')).toBe(245));
  it('cex num 246', () => expect(coerceType(246, 'number')).toBe(246));
  it('cex num 247', () => expect(coerceType(247, 'number')).toBe(247));
  it('cex num 248', () => expect(coerceType(248, 'number')).toBe(248));
  it('cex num 249', () => expect(coerceType(249, 'number')).toBe(249));
  it('cex num 250', () => expect(coerceType(250, 'number')).toBe(250));
  it('cex num 251', () => expect(coerceType(251, 'number')).toBe(251));
  it('cex num 252', () => expect(coerceType(252, 'number')).toBe(252));
  it('cex num 253', () => expect(coerceType(253, 'number')).toBe(253));
  it('cex num 254', () => expect(coerceType(254, 'number')).toBe(254));
  it('cex num 255', () => expect(coerceType(255, 'number')).toBe(255));
  it('cex num 256', () => expect(coerceType(256, 'number')).toBe(256));
  it('cex num 257', () => expect(coerceType(257, 'number')).toBe(257));
  it('cex num 258', () => expect(coerceType(258, 'number')).toBe(258));
  it('cex num 259', () => expect(coerceType(259, 'number')).toBe(259));
  it('cex num 260', () => expect(coerceType(260, 'number')).toBe(260));
  it('cex num 261', () => expect(coerceType(261, 'number')).toBe(261));
  it('cex num 262', () => expect(coerceType(262, 'number')).toBe(262));
  it('cex num 263', () => expect(coerceType(263, 'number')).toBe(263));
  it('cex num 264', () => expect(coerceType(264, 'number')).toBe(264));
  it('cex num 265', () => expect(coerceType(265, 'number')).toBe(265));
  it('cex num 266', () => expect(coerceType(266, 'number')).toBe(266));
  it('cex num 267', () => expect(coerceType(267, 'number')).toBe(267));
  it('cex num 268', () => expect(coerceType(268, 'number')).toBe(268));
  it('cex num 269', () => expect(coerceType(269, 'number')).toBe(269));
  it('cex num 270', () => expect(coerceType(270, 'number')).toBe(270));
  it('cex num 271', () => expect(coerceType(271, 'number')).toBe(271));
  it('cex num 272', () => expect(coerceType(272, 'number')).toBe(272));
  it('cex num 273', () => expect(coerceType(273, 'number')).toBe(273));
  it('cex num 274', () => expect(coerceType(274, 'number')).toBe(274));
  it('cex num 275', () => expect(coerceType(275, 'number')).toBe(275));
  it('cex num 276', () => expect(coerceType(276, 'number')).toBe(276));
  it('cex num 277', () => expect(coerceType(277, 'number')).toBe(277));
  it('cex num 278', () => expect(coerceType(278, 'number')).toBe(278));
  it('cex num 279', () => expect(coerceType(279, 'number')).toBe(279));
  it('cex num 280', () => expect(coerceType(280, 'number')).toBe(280));
  it('cex num 281', () => expect(coerceType(281, 'number')).toBe(281));
  it('cex num 282', () => expect(coerceType(282, 'number')).toBe(282));
  it('cex num 283', () => expect(coerceType(283, 'number')).toBe(283));
  it('cex num 284', () => expect(coerceType(284, 'number')).toBe(284));
  it('cex num 285', () => expect(coerceType(285, 'number')).toBe(285));
  it('cex num 286', () => expect(coerceType(286, 'number')).toBe(286));
  it('cex num 287', () => expect(coerceType(287, 'number')).toBe(287));
  it('cex num 288', () => expect(coerceType(288, 'number')).toBe(288));
  it('cex num 289', () => expect(coerceType(289, 'number')).toBe(289));
  it('cex num 290', () => expect(coerceType(290, 'number')).toBe(290));
  it('cex num 291', () => expect(coerceType(291, 'number')).toBe(291));
  it('cex num 292', () => expect(coerceType(292, 'number')).toBe(292));
  it('cex num 293', () => expect(coerceType(293, 'number')).toBe(293));
  it('cex num 294', () => expect(coerceType(294, 'number')).toBe(294));
  it('cex num 295', () => expect(coerceType(295, 'number')).toBe(295));
  it('cex num 296', () => expect(coerceType(296, 'number')).toBe(296));
  it('cex num 297', () => expect(coerceType(297, 'number')).toBe(297));
  it('cex num 298', () => expect(coerceType(298, 'number')).toBe(298));
  it('cex num 299', () => expect(coerceType(299, 'number')).toBe(299));
});

