import type { TemplateDefinition } from '../types';

export const aerospaceTemplates: TemplateDefinition[] = [
  // ─── TPL-AERO-001  FAI Part 1 — Part Number Accountability ───────────
  {
    code: 'TPL-AERO-001',
    name: 'First Article Inspection Part 1 — Part Number Accountability',
    description:
      'AS9102 First Article Inspection Report Form 1 — Part Number Accountability. Records part identification, drawing references, manufacturing process, organization details, and purchase order information for first article verification.',
    module: 'AEROSPACE',
    category: 'INSPECTION',
    tags: ['FAI', 'AS9102', 'first-article', 'part-accountability', 'quality'],
    isoClause: '8.5.1',
    fields: [
      {
        id: 'section_part_info',
        label: 'Part Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'part_number',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. PN-7890-001',
        helpText: 'The part number as specified on the engineering drawing.',
        width: 'third',
      },
      {
        id: 'part_name',
        label: 'Part Name / Description',
        type: 'text',
        required: true,
        placeholder: 'e.g. Turbine Blade Assembly, Stage 1',
        width: 'third',
      },
      {
        id: 'serial_number',
        label: 'Serial Number',
        type: 'text',
        required: true,
        placeholder: 'Serial number of the FAI article',
        helpText: 'If not serialized, enter lot or batch number.',
        width: 'third',
      },
      {
        id: 'section_drawing',
        label: 'Drawing & Revision',
        type: 'section',
        width: 'full',
      },
      {
        id: 'drawing_number',
        label: 'Drawing Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. DWG-7890-001',
        width: 'half',
      },
      {
        id: 'drawing_revision',
        label: 'Drawing Revision Level',
        type: 'text',
        required: true,
        placeholder: 'e.g. Rev D',
        width: 'half',
      },
      {
        id: 'additional_changes',
        label: 'Additional Changes Not Included in Revision Level',
        type: 'textarea',
        placeholder: 'List any engineering changes, deviations, or waivers not reflected in the current drawing revision.',
        helpText: 'Include ECN numbers, concession references, or customer-approved deviations.',
        width: 'full',
      },
      {
        id: 'section_manufacturing',
        label: 'Manufacturing Process',
        type: 'section',
        width: 'full',
      },
      {
        id: 'manufacturing_process_ref',
        label: 'Manufacturing Process Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. MP-2026-001 Rev A',
        helpText: 'Reference to the manufacturing process plan, routing, or work instruction.',
        width: 'half',
      },
      {
        id: 'manufacturing_process_revision',
        label: 'Process Revision',
        type: 'text',
        width: 'half',
      },
      {
        id: 'section_organization',
        label: 'Organization Details',
        type: 'section',
        width: 'full',
      },
      {
        id: 'organization_name',
        label: 'Organization Name',
        type: 'text',
        required: true,
        placeholder: 'Manufacturing facility or supplier name',
        width: 'half',
      },
      {
        id: 'supplier_code',
        label: 'Supplier / Vendor Code',
        type: 'text',
        required: true,
        placeholder: 'e.g. SUP-001 or CAGE code',
        helpText: 'Customer-assigned supplier code or CAGE/DUNS code.',
        width: 'half',
      },
      {
        id: 'po_number',
        label: 'Purchase Order Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. PO-2026-12345',
        width: 'half',
      },
      {
        id: 'fai_report_number',
        label: 'FAI Report Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. FAI-2026-001',
        width: 'half',
      },
      {
        id: 'section_detail_accountability',
        label: 'Detail Accountability',
        type: 'section',
        width: 'full',
      },
      {
        id: 'detail_accountability',
        label: 'Detail Part Accountability',
        type: 'table',
        required: true,
        helpText: 'List all detail parts, sub-assemblies, and raw materials for this assembly. For each detail, reference its own FAI or indicate if partial/full FAI is required.',
        columns: [
          {
            id: 'detail_part_number',
            label: 'Detail Part Number',
            type: 'text',
            required: true,
          },
          {
            id: 'detail_part_name',
            label: 'Part Name',
            type: 'text',
            required: true,
          },
          {
            id: 'detail_supplier',
            label: 'Supplier / CAGE',
            type: 'text',
          },
          {
            id: 'detail_fai_number',
            label: 'FAI Report No.',
            type: 'text',
            placeholder: 'Reference to the detail FAI',
          },
          {
            id: 'fai_status',
            label: 'FAI Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Complete', value: 'complete' },
              { label: 'Partial', value: 'partial' },
              { label: 'Not Required', value: 'not_required' },
              { label: 'Pending', value: 'pending' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'fai_reason',
        label: 'Reason for FAI',
        type: 'select',
        required: true,
        helpText: 'Per AS9102 — select the reason this FAI was initiated.',
        options: [
          { label: 'New Part', value: 'new_part' },
          { label: 'Design Change', value: 'design_change' },
          { label: 'Process Change', value: 'process_change' },
          { label: 'Tooling Change / Transfer', value: 'tooling_change' },
          { label: 'Change of Source / Supplier', value: 'source_change' },
          { label: 'Lapse in Production (>2 years)', value: 'lapse' },
          { label: 'Customer Request', value: 'customer_request' },
        ],
        width: 'half',
      },
      {
        id: 'fai_type',
        label: 'FAI Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Full FAI', value: 'full' },
          { label: 'Partial FAI', value: 'partial' },
          { label: 'Delta FAI', value: 'delta' },
        ],
        width: 'half',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'signature',
        required: true,
        width: 'half',
      },
      {
        id: 'date_prepared',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-AERO-002  FAI Part 2 — Product Accountability ──────────────
  {
    code: 'TPL-AERO-002',
    name: 'First Article Inspection Part 2 — Product Accountability',
    description:
      'AS9102 First Article Inspection Report Form 2 — Product Accountability. Documents raw material, special process suppliers, material certifications, process approvals, functional test procedures, and test results.',
    module: 'AEROSPACE',
    category: 'INSPECTION',
    tags: ['FAI', 'AS9102', 'material-cert', 'special-process', 'product-accountability'],
    isoClause: '8.5.1',
    fields: [
      {
        id: 'section_part_ref',
        label: 'Part Reference',
        type: 'section',
        width: 'full',
      },
      {
        id: 'part_number',
        label: 'Part Number',
        type: 'text',
        required: true,
        width: 'half',
      },
      {
        id: 'fai_report_number',
        label: 'FAI Report Number',
        type: 'text',
        required: true,
        placeholder: 'Must match Part 1 FAI number',
        width: 'half',
      },
      {
        id: 'section_raw_material',
        label: 'Raw Material',
        type: 'section',
        width: 'full',
      },
      {
        id: 'raw_material_supplier',
        label: 'Raw Material Supplier',
        type: 'text',
        required: true,
        placeholder: 'e.g. Alcoa Inc., CAGE 12345',
        width: 'half',
      },
      {
        id: 'material_specification',
        label: 'Material Specification',
        type: 'text',
        required: true,
        placeholder: 'e.g. AMS 4928 Ti-6Al-4V, ASTM A240 316L',
        helpText: 'Full material specification reference including grade/alloy.',
        width: 'half',
      },
      {
        id: 'material_cert_available',
        label: 'Material Certificate (Mill Cert) Available',
        type: 'checkbox',
        required: true,
        helpText: 'Confirm that the material test report / mill certificate is on file and meets specification requirements.',
      },
      {
        id: 'material_lot_number',
        label: 'Material Lot / Heat Number',
        type: 'text',
        placeholder: 'e.g. HEAT-2026-0456',
        width: 'half',
      },
      {
        id: 'material_cert_number',
        label: 'Certificate Number',
        type: 'text',
        placeholder: 'e.g. MC-2026-789',
        width: 'half',
      },
      {
        id: 'section_special_process',
        label: 'Special Processes',
        type: 'section',
        width: 'full',
      },
      {
        id: 'special_process_supplier',
        label: 'Special Process Supplier',
        type: 'text',
        required: true,
        placeholder: 'e.g. Bodycote PLC, Nadcap approved',
        helpText: 'Name and certification status of the special process supplier.',
        width: 'half',
      },
      {
        id: 'process_specification',
        label: 'Process Specification',
        type: 'text',
        required: true,
        placeholder: 'e.g. AMS 2759/3 (Heat Treatment), AMS-QQ-P-35 (Passivation)',
        width: 'half',
      },
      {
        id: 'process_approval_available',
        label: 'Process Approval / Nadcap Certification Available',
        type: 'checkbox',
        required: true,
        helpText: 'Confirm the special process supplier holds current approval (Nadcap, customer approval, or equivalent).',
      },
      {
        id: 'nadcap_cert_number',
        label: 'Nadcap / Approval Certificate Number',
        type: 'text',
        placeholder: 'e.g. NAD-12345-2026',
        width: 'half',
      },
      {
        id: 'approval_expiry',
        label: 'Approval Expiry Date',
        type: 'date',
        width: 'half',
      },
      {
        id: 'section_functional_tests',
        label: 'Functional Test Procedures',
        type: 'section',
        width: 'full',
      },
      {
        id: 'functional_test_procedures',
        label: 'Functional Test Procedures',
        type: 'table',
        required: true,
        helpText: 'List all functional tests, performance tests, and acceptance tests required for the first article.',
        columns: [
          {
            id: 'test_number',
            label: 'Test Procedure Number',
            type: 'text',
            required: true,
            placeholder: 'e.g. TP-2026-001',
          },
          {
            id: 'test_name',
            label: 'Test Description',
            type: 'text',
            required: true,
            placeholder: 'e.g. Proof pressure test, Fatigue test',
          },
          {
            id: 'specification_ref',
            label: 'Specification Reference',
            type: 'text',
            placeholder: 'e.g. Drawing Note 5, ASTM E466',
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
              { label: 'Not Tested', value: 'not_tested' },
              { label: 'Waived', value: 'waived' },
            ],
          },
          {
            id: 'report_number',
            label: 'Test Report Number',
            type: 'text',
          },
        ],
        width: 'full',
      },
      {
        id: 'test_results_summary',
        label: 'Test Results Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Provide overall summary of functional test results, any deviations, and disposition of any failures.',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'section_form2_signoff',
        label: 'Sign-Off',
        type: 'section',
        width: 'full',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'reviewed_by',
        label: 'QA Review',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'form2_date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'third',
      },
    ],
  },

  // ─── TPL-AERO-003  FAI Part 3 — Characteristic Accountability ───────
  {
    code: 'TPL-AERO-003',
    name: 'First Article Inspection Part 3 — Characteristic Accountability',
    description:
      'AS9102 First Article Inspection Report Form 3 — Characteristic Accountability. Records measurement results for each design characteristic, designator classification (standard/critical/major), and comparison against drawing requirements.',
    module: 'AEROSPACE',
    category: 'INSPECTION',
    tags: ['FAI', 'AS9102', 'characteristics', 'measurement', 'dimensional-inspection'],
    isoClause: '8.5.1',
    fields: [
      {
        id: 'section_part_ref',
        label: 'Part Reference',
        type: 'section',
        width: 'full',
      },
      {
        id: 'part_number',
        label: 'Part Number',
        type: 'text',
        required: true,
        width: 'third',
      },
      {
        id: 'part_name',
        label: 'Part Name',
        type: 'text',
        required: true,
        width: 'third',
      },
      {
        id: 'fai_report_number',
        label: 'FAI Report Number',
        type: 'text',
        required: true,
        width: 'third',
      },
      {
        id: 'drawing_number',
        label: 'Drawing Number / Revision',
        type: 'text',
        required: true,
        width: 'half',
      },
      {
        id: 'serial_number',
        label: 'Serial / Lot Number',
        type: 'text',
        required: true,
        width: 'half',
      },
      {
        id: 'section_characteristics',
        label: 'Characteristic Measurements',
        type: 'section',
        width: 'full',
      },
      {
        id: 'characteristics_table',
        label: 'Characteristics',
        type: 'table',
        required: true,
        helpText: 'Record every design characteristic from the drawing. Number sequentially. Identify all critical and major characteristics.',
        columns: [
          {
            id: 'char_number',
            label: 'Char #',
            type: 'number',
            required: true,
            validation: { min: 1 },
          },
          {
            id: 'reference_location',
            label: 'Reference Location',
            type: 'text',
            required: true,
            placeholder: 'e.g. Drawing Zone B3, Note 7',
            helpText: 'Drawing zone, view, detail, or note reference.',
          },
          {
            id: 'characteristic_designator',
            label: 'Designator',
            type: 'select',
            required: true,
            helpText: 'Classification per drawing callout.',
            options: [
              { label: 'Standard', value: 'standard' },
              { label: 'Critical', value: 'critical' },
              { label: 'Major', value: 'major' },
            ],
          },
          {
            id: 'requirement',
            label: 'Requirement',
            type: 'text',
            required: true,
            placeholder: 'e.g. 25.40 +/- 0.05 mm',
            helpText: 'Nominal dimension and tolerance as stated on the drawing.',
          },
          {
            id: 'results',
            label: 'Actual Result',
            type: 'text',
            required: true,
            placeholder: 'e.g. 25.42 mm',
            helpText: 'Measured value or pass/fail observation.',
          },
          {
            id: 'designed_tooling',
            label: 'Designed Tooling Used',
            type: 'checkbox',
            helpText: 'Check if a designed (not standard) tooling, fixture, or gauge was used for this measurement.',
          },
        ],
        width: 'full',
      },
      {
        id: 'section_remarks',
        label: 'Remarks & Approval',
        type: 'section',
        width: 'full',
      },
      {
        id: 'remarks',
        label: 'Remarks',
        type: 'textarea',
        placeholder: 'Any non-conformances, deviations, concessions, or additional notes.',
        helpText: 'Document any characteristics that did not meet requirements and reference the disposition (concession, rework, etc.).',
        width: 'full',
      },
      {
        id: 'nonconformances_count',
        label: 'Number of Non-Conformances',
        type: 'number',
        validation: { min: 0 },
        width: 'third',
      },
      {
        id: 'total_characteristics',
        label: 'Total Characteristics Inspected',
        type: 'number',
        required: true,
        validation: { min: 1 },
        width: 'third',
      },
      {
        id: 'fai_result',
        label: 'FAI Result',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Conditionally Approved', value: 'conditional' },
          { label: 'Rejected', value: 'rejected' },
        ],
        width: 'third',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'approved_by',
        label: 'Approved By',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'customer_approval',
        label: 'Customer Approval (if required)',
        type: 'signature',
        helpText: 'Required when customer contract specifies customer approval of FAI.',
        width: 'third',
      },
    ],
  },

  // ─── TPL-AERO-004  Engineering Change Proposal ───────────────────────
  {
    code: 'TPL-AERO-004',
    name: 'Engineering Change Proposal',
    description:
      'Formal Engineering Change Proposal (ECP) for aerospace programs. Documents the proposed change, affected assemblies, classification, impact assessment across multiple areas, effectivity point, and approval routing.',
    module: 'AEROSPACE',
    category: 'DESIGN_DEVELOPMENT',
    tags: ['engineering-change', 'ECP', 'configuration-management', 'change-control'],
    fields: [
      {
        id: 'section_ecp_header',
        label: 'ECP Identification',
        type: 'section',
        width: 'full',
      },
      {
        id: 'ecp_number',
        label: 'ECP Number',
        type: 'text',
        required: true,
        placeholder: 'ECP-2026-0001',
        width: 'third',
      },
      {
        id: 'originator',
        label: 'Originator',
        type: 'text',
        required: true,
        placeholder: 'Name and department',
        width: 'third',
      },
      {
        id: 'date',
        label: 'Date of Submission',
        type: 'date',
        required: true,
        width: 'third',
      },
      {
        id: 'programme',
        label: 'Programme / Contract',
        type: 'text',
        required: true,
        placeholder: 'e.g. A320 Wing Assembly, Contract C-2026-001',
        width: 'half',
      },
      {
        id: 'priority',
        label: 'Priority',
        type: 'select',
        required: true,
        options: [
          { label: 'Emergency — Safety of Flight', value: 'emergency' },
          { label: 'Urgent — Production Stop', value: 'urgent' },
          { label: 'Routine', value: 'routine' },
        ],
        width: 'half',
      },
      {
        id: 'section_affected',
        label: 'Affected Items',
        type: 'section',
        width: 'full',
      },
      {
        id: 'affected_part_assembly',
        label: 'Affected Part / Assembly',
        type: 'text',
        required: true,
        placeholder: 'e.g. PN-7890-001 Wing Rib Assembly',
        helpText: 'Primary part number and name affected by this change.',
        width: 'half',
      },
      {
        id: 'affected_drawings',
        label: 'Affected Drawings / Documents',
        type: 'textarea',
        placeholder: 'List all drawing numbers, specifications, and documents that require revision.',
        width: 'half',
      },
      {
        id: 'change_classification',
        label: 'Change Classification',
        type: 'select',
        required: true,
        helpText: 'Major: affects form/fit/function, interface, safety, reliability, or contractual requirements. Minor: all others.',
        options: [
          { label: 'Major (Class I)', value: 'major' },
          { label: 'Minor (Class II)', value: 'minor' },
        ],
        width: 'half',
      },
      {
        id: 'change_type',
        label: 'Change Type',
        type: 'select',
        options: [
          { label: 'Design Change', value: 'design' },
          { label: 'Material Substitution', value: 'material' },
          { label: 'Process Change', value: 'process' },
          { label: 'Supplier Change', value: 'supplier' },
          { label: 'Software Change', value: 'software' },
          { label: 'Documentation Only', value: 'documentation' },
        ],
        width: 'half',
      },
      {
        id: 'section_change_details',
        label: 'Change Details',
        type: 'section',
        width: 'full',
      },
      {
        id: 'description_of_change',
        label: 'Description of Change',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the proposed change in detail. Include before/after comparison where applicable.',
        validation: { minLength: 50, maxLength: 10000 },
        width: 'full',
      },
      {
        id: 'reason_for_change',
        label: 'Reason for Change',
        type: 'textarea',
        required: true,
        placeholder: 'Explain why the change is necessary (e.g. safety improvement, weight reduction, obsolescence, cost reduction, customer requirement).',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'section_impact',
        label: 'Impact Assessment',
        type: 'section',
        width: 'full',
      },
      {
        id: 'impact_assessment',
        label: 'Impact Assessment',
        type: 'table',
        required: true,
        helpText: 'Assess the impact of the change across all relevant areas.',
        columns: [
          {
            id: 'area',
            label: 'Area',
            type: 'select',
            required: true,
            options: [
              { label: 'Safety / Airworthiness', value: 'safety' },
              { label: 'Structural Integrity', value: 'structural' },
              { label: 'Weight & Balance', value: 'weight_balance' },
              { label: 'Reliability / Maintainability', value: 'reliability' },
              { label: 'Manufacturing / Tooling', value: 'manufacturing' },
              { label: 'Supplier / Supply Chain', value: 'supplier' },
              { label: 'Spares / Logistics', value: 'spares' },
              { label: 'Cost', value: 'cost' },
              { label: 'Schedule', value: 'schedule' },
              { label: 'Certification / Compliance', value: 'certification' },
              { label: 'Interface / Interchangeability', value: 'interface' },
              { label: 'Software', value: 'software' },
              { label: 'Training / Documentation', value: 'training' },
            ],
          },
          {
            id: 'impact',
            label: 'Impact Description',
            type: 'textarea',
            required: true,
            placeholder: 'Describe the specific impact in this area',
          },
          {
            id: 'severity',
            label: 'Severity',
            type: 'select',
            required: true,
            options: [
              { label: 'None — No Impact', value: 'none' },
              { label: 'Low — Minimal Impact', value: 'low' },
              { label: 'Medium — Moderate Impact', value: 'medium' },
              { label: 'High — Significant Impact', value: 'high' },
              { label: 'Critical — Programme Impact', value: 'critical' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'effectivity',
        label: 'Effectivity',
        type: 'textarea',
        required: true,
        placeholder: 'Define the effectivity point (e.g. Ship Set 45 and subsequent, from Lot 2026-Q3, retrofit required for all in-service units).',
        helpText: 'Specify whether the change applies to new production, in-service retrofit, or both.',
        width: 'full',
      },
      {
        id: 'section_approval_routing',
        label: 'Approval Routing',
        type: 'section',
        width: 'full',
      },
      {
        id: 'approval_routing',
        label: 'Approval Routing',
        type: 'table',
        required: true,
        helpText: 'Route to all required approvers. Major changes typically require customer and airworthiness authority approval.',
        columns: [
          {
            id: 'role',
            label: 'Approver Role / Function',
            type: 'text',
            required: true,
            placeholder: 'e.g. Design Authority, Stress Engineer, Customer Rep',
          },
          {
            id: 'name',
            label: 'Name',
            type: 'text',
          },
          {
            id: 'decision',
            label: 'Decision',
            type: 'select',
            options: [
              { label: 'Approved', value: 'approved' },
              { label: 'Approved with Comments', value: 'approved_comments' },
              { label: 'Rejected', value: 'rejected' },
              { label: 'Pending', value: 'pending' },
            ],
          },
          {
            id: 'signature',
            label: 'Signature',
            type: 'signature',
          },
          {
            id: 'approval_date',
            label: 'Date',
            type: 'date',
          },
        ],
        width: 'full',
      },
    ],
  },

  // ─── TPL-AERO-005  Maintenance Work Order ────────────────────────────
  {
    code: 'TPL-AERO-005',
    name: 'Maintenance Work Order',
    description:
      'Aircraft or aerospace equipment maintenance work order. Captures task details, ATA chapter, parts required, labor, special tools, inspection requirements, and sign-off for each work step.',
    module: 'AEROSPACE',
    category: 'PROCESS_CONTROL',
    tags: ['maintenance', 'work-order', 'MRO', 'aircraft', 'ATA'],
    fields: [
      {
        id: 'section_wo_header',
        label: 'Work Order Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'work_order_number',
        label: 'Work Order Number',
        type: 'text',
        required: true,
        placeholder: 'WO-2026-0001',
        width: 'third',
      },
      {
        id: 'date_issued',
        label: 'Date Issued',
        type: 'date',
        required: true,
        width: 'third',
      },
      {
        id: 'date_required',
        label: 'Required Completion Date',
        type: 'date',
        required: true,
        width: 'third',
      },
      {
        id: 'aircraft_equipment',
        label: 'Aircraft / Equipment',
        type: 'text',
        required: true,
        placeholder: 'e.g. Boeing 737-800, Engine CFM56-7B',
        width: 'half',
      },
      {
        id: 'registration',
        label: 'Registration / Tail Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. G-ABCD, N12345',
        width: 'half',
      },
      {
        id: 'msn',
        label: 'MSN / Serial Number',
        type: 'text',
        placeholder: 'e.g. MSN 42567',
        width: 'half',
      },
      {
        id: 'total_flight_hours',
        label: 'Total Time Since New (hours)',
        type: 'number',
        placeholder: 'e.g. 45230',
        validation: { min: 0 },
        width: 'half',
      },
      {
        id: 'section_task',
        label: 'Task Details',
        type: 'section',
        width: 'full',
      },
      {
        id: 'task_description',
        label: 'Task Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of the maintenance task to be performed.',
        validation: { minLength: 20, maxLength: 10000 },
        width: 'full',
      },
      {
        id: 'ata_chapter',
        label: 'ATA Chapter',
        type: 'text',
        required: true,
        placeholder: 'e.g. ATA 32 — Landing Gear, ATA 72 — Engine',
        helpText: 'ATA 100 / iSpec 2200 chapter reference.',
        width: 'half',
      },
      {
        id: 'task_type',
        label: 'Task Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Scheduled Maintenance', value: 'scheduled' },
          { label: 'Unscheduled Maintenance', value: 'unscheduled' },
          { label: 'Modification / SB', value: 'modification' },
          { label: 'Repair', value: 'repair' },
          { label: 'Overhaul', value: 'overhaul' },
          { label: 'Inspection (AD/SB)', value: 'inspection' },
        ],
        width: 'half',
      },
      {
        id: 'task_reference',
        label: 'Task Card / AMM Reference',
        type: 'text',
        placeholder: 'e.g. AMM 32-11-01, SB 737-32-1234',
        helpText: 'Reference to the Aircraft Maintenance Manual, Service Bulletin, or Airworthiness Directive.',
        width: 'half',
      },
      {
        id: 'zone',
        label: 'Zone / Location',
        type: 'text',
        placeholder: 'e.g. Zone 131 — LH Wing, Zone 411 — Cockpit',
        width: 'half',
      },
      {
        id: 'section_parts',
        label: 'Parts Required',
        type: 'section',
        width: 'full',
      },
      {
        id: 'parts_required',
        label: 'Parts Required',
        type: 'table',
        helpText: 'List all parts, materials, and consumables required for this work order.',
        columns: [
          {
            id: 'part_number',
            label: 'Part Number',
            type: 'text',
            required: true,
          },
          {
            id: 'description',
            label: 'Description',
            type: 'text',
            required: true,
          },
          {
            id: 'quantity',
            label: 'Qty',
            type: 'number',
            required: true,
            validation: { min: 1 },
          },
          {
            id: 'serial_batch',
            label: 'Serial / Batch No.',
            type: 'text',
          },
          {
            id: 'cert_status',
            label: 'Release Cert (EASA Form 1 / FAA 8130)',
            type: 'select',
            options: [
              { label: 'Available', value: 'available' },
              { label: 'Pending', value: 'pending' },
              { label: 'N/A (Consumable)', value: 'na' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'labor_hours_estimated',
        label: 'Estimated Labor Hours',
        type: 'number',
        required: true,
        placeholder: 'e.g. 8.5',
        validation: { min: 0.5, max: 10000 },
        width: 'half',
      },
      {
        id: 'special_tools',
        label: 'Special Tools Required',
        type: 'textarea',
        placeholder: 'List any special tools, fixtures, or ground support equipment needed.',
        width: 'half',
      },
      {
        id: 'section_inspection',
        label: 'Inspection Requirements & Sign-Off',
        type: 'section',
        width: 'full',
      },
      {
        id: 'inspection_requirements',
        label: 'Inspection Requirements',
        type: 'textarea',
        required: true,
        placeholder: 'Define inspection hold points, required inspection stamps (RII, mandatory inspection, etc.).',
        width: 'full',
      },
      {
        id: 'signoff_table',
        label: 'Work Step Sign-Off',
        type: 'table',
        required: true,
        helpText: 'Each critical step must be signed off by the performing mechanic and inspected where required.',
        columns: [
          {
            id: 'step',
            label: 'Step',
            type: 'text',
            required: true,
            placeholder: 'e.g. Step 1 — Remove component',
          },
          {
            id: 'performer',
            label: 'Performed By',
            type: 'signature',
            required: true,
          },
          {
            id: 'inspector',
            label: 'Inspected By',
            type: 'signature',
          },
          {
            id: 'date_completed',
            label: 'Date',
            type: 'date',
            required: true,
          },
        ],
        width: 'full',
      },
      {
        id: 'wo_status',
        label: 'Work Order Status',
        type: 'select',
        required: true,
        defaultValue: 'open',
        options: [
          { label: 'Open', value: 'open' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Pending Parts', value: 'pending_parts' },
          { label: 'Inspection Required', value: 'inspection_required' },
          { label: 'Completed', value: 'completed' },
          { label: 'Deferred', value: 'deferred' },
        ],
        width: 'half',
      },
      {
        id: 'release_to_service',
        label: 'Release to Service (CRS)',
        type: 'signature',
        helpText: 'Certificate of Release to Service — signed by authorized certifying staff per Part 145 / Part 43.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-AERO-006  Inspection Task Card ──────────────────────────────
  {
    code: 'TPL-AERO-006',
    name: 'Inspection Task Card',
    description:
      'Detailed inspection task card for aircraft structural, system, or component inspections. Documents inspection type, step-by-step instructions with accept/reject criteria, tools required, findings, and disposition.',
    module: 'AEROSPACE',
    category: 'INSPECTION',
    tags: ['inspection', 'task-card', 'NDT', 'structural', 'aircraft'],
    fields: [
      {
        id: 'section_task_card_header',
        label: 'Task Card Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'task_card_number',
        label: 'Task Card Number',
        type: 'text',
        required: true,
        placeholder: 'TC-2026-0001',
        width: 'third',
      },
      {
        id: 'revision',
        label: 'Revision',
        type: 'text',
        required: true,
        defaultValue: 'A',
        width: 'third',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'third',
      },
      {
        id: 'aircraft_type',
        label: 'Aircraft Type',
        type: 'text',
        required: true,
        placeholder: 'e.g. A320-214, Boeing 787-9',
        width: 'half',
      },
      {
        id: 'registration',
        label: 'Registration / MSN',
        type: 'text',
        required: true,
        width: 'half',
      },
      {
        id: 'zone',
        label: 'Zone / Area',
        type: 'text',
        required: true,
        placeholder: 'e.g. Zone 131 — Left Wing Lower Surface',
        helpText: 'ATA zone or structural location reference.',
        width: 'half',
      },
      {
        id: 'access_requirements',
        label: 'Access Requirements',
        type: 'textarea',
        required: true,
        placeholder: 'Panels to be removed, scaffolding required, jacking requirements, safety precautions.',
        helpText: 'Document all access requirements and safety precautions before inspection begins.',
        width: 'half',
      },
      {
        id: 'inspection_type',
        label: 'Inspection Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Visual (GVI / DET / SDI)', value: 'visual' },
          { label: 'NDT — Ultrasonic', value: 'ndt_ut' },
          { label: 'NDT — Eddy Current', value: 'ndt_ec' },
          { label: 'NDT — Magnetic Particle', value: 'ndt_mpi' },
          { label: 'NDT — Dye Penetrant', value: 'ndt_dpi' },
          { label: 'NDT — Radiographic', value: 'ndt_rt' },
          { label: 'Dimensional', value: 'dimensional' },
          { label: 'Functional / Operational', value: 'functional' },
          { label: 'Borescope', value: 'borescope' },
        ],
        width: 'half',
      },
      {
        id: 'ndt_qualification',
        label: 'NDT Qualification Required',
        type: 'select',
        helpText: 'For NDT inspections, specify the minimum qualification level per EN 4179 / NAS 410.',
        options: [
          { label: 'N/A — Visual Inspection', value: 'na' },
          { label: 'Level 1 (under Level 2 supervision)', value: 'level_1' },
          { label: 'Level 2', value: 'level_2' },
          { label: 'Level 3', value: 'level_3' },
        ],
        width: 'half',
      },
      {
        id: 'section_steps',
        label: 'Inspection Steps',
        type: 'section',
        width: 'full',
      },
      {
        id: 'detailed_steps',
        label: 'Detailed Inspection Steps',
        type: 'table',
        required: true,
        helpText: 'Document each inspection step with clear accept/reject criteria.',
        columns: [
          {
            id: 'step_number',
            label: 'Step',
            type: 'number',
            required: true,
            validation: { min: 1 },
          },
          {
            id: 'instruction',
            label: 'Instruction',
            type: 'textarea',
            required: true,
            placeholder: 'Describe the inspection action to perform',
          },
          {
            id: 'accept_reject_criteria',
            label: 'Accept / Reject Criteria',
            type: 'textarea',
            required: true,
            placeholder: 'e.g. No cracks, corrosion, deformation. Max allowable wear 0.5mm.',
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            options: [
              { label: 'Accept', value: 'accept' },
              { label: 'Reject', value: 'reject' },
              { label: 'Not Inspected', value: 'not_inspected' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'tools_required',
        label: 'Tools & Equipment Required',
        type: 'textarea',
        required: true,
        placeholder: 'List all tools, gauges, NDT equipment, calibration requirements.',
        width: 'full',
      },
      {
        id: 'section_findings',
        label: 'Findings & Disposition',
        type: 'section',
        width: 'full',
      },
      {
        id: 'findings',
        label: 'Findings',
        type: 'textarea',
        required: true,
        placeholder: 'Describe all findings including location, extent, and measurements. If no findings, state "No defects found".',
        helpText: 'Include photographs, sketches, or NDT records as attachments.',
        validation: { minLength: 10, maxLength: 10000 },
        width: 'full',
      },
      {
        id: 'disposition',
        label: 'Disposition',
        type: 'select',
        required: true,
        options: [
          { label: 'Serviceable — No Defects', value: 'serviceable' },
          { label: 'Unserviceable — Repair Required', value: 'unserviceable' },
          { label: 'Requires Further Inspection', value: 'requires_further_inspection' },
          { label: 'Beyond Repair — Scrap', value: 'scrap' },
          { label: 'Deferred — MEL / CDL', value: 'deferred' },
        ],
        width: 'half',
      },
      {
        id: 'follow_up_ref',
        label: 'Follow-Up Work Order / SRM Reference',
        type: 'text',
        placeholder: 'e.g. WO-2026-0045, SRM 51-70-11',
        helpText: 'Reference to follow-up work order or Structural Repair Manual chapter if repair is needed.',
        width: 'half',
      },
      {
        id: 'inspector_signature',
        label: 'Inspector',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'inspector_stamp',
        label: 'Inspector Stamp / Auth No.',
        type: 'text',
        required: true,
        placeholder: 'e.g. AUTH-12345',
        width: 'third',
      },
      {
        id: 'inspection_date',
        label: 'Inspection Date',
        type: 'date',
        required: true,
        width: 'third',
      },
    ],
  },

  // ─── TPL-AERO-007  Human Factors Assessment Report ───────────────────
  {
    code: 'TPL-AERO-007',
    name: 'Human Factors Assessment Report',
    description:
      'Human factors assessment for aviation maintenance events using the SHELL model framework. Captures environmental, individual, and organizational factors, personnel analysis, contributing factors, and corrective recommendations.',
    module: 'AEROSPACE',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['human-factors', 'SHELL-model', 'maintenance-error', 'safety', 'MRM'],
    fields: [
      {
        id: 'section_event_info',
        label: 'Event Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'event_reference',
        label: 'Event Reference Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. HF-2026-0001, linked to safety report SR-2026-xxx',
        width: 'half',
      },
      {
        id: 'event_date',
        label: 'Date of Event',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'event_description',
        label: 'Brief Event Description',
        type: 'textarea',
        required: true,
        placeholder: 'Concise description of what occurred.',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'section_personnel',
        label: 'Personnel Involved',
        type: 'section',
        width: 'full',
      },
      {
        id: 'personnel_involved',
        label: 'Personnel Involved',
        type: 'table',
        required: true,
        helpText: 'Document all personnel involved in or witnessing the event.',
        columns: [
          {
            id: 'name',
            label: 'Name / ID',
            type: 'text',
            required: true,
          },
          {
            id: 'role',
            label: 'Role / Licence',
            type: 'text',
            required: true,
            placeholder: 'e.g. B1 Licensed Engineer, Mechanic',
          },
          {
            id: 'experience_years',
            label: 'Years Experience',
            type: 'number',
            validation: { min: 0, max: 50 },
          },
          {
            id: 'shift',
            label: 'Shift',
            type: 'select',
            options: [
              { label: 'Day', value: 'day' },
              { label: 'Back (Afternoon)', value: 'back' },
              { label: 'Night', value: 'night' },
            ],
          },
          {
            id: 'hours_on_duty',
            label: 'Hours on Duty at Time of Event',
            type: 'number',
            validation: { min: 0, max: 24 },
          },
        ],
        width: 'full',
      },
      {
        id: 'task_being_performed',
        label: 'Task Being Performed',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the specific task, including AMM/SRM reference, step number, and what was expected.',
        width: 'full',
      },
      {
        id: 'section_factors',
        label: 'Contributing Factors',
        type: 'section',
        width: 'full',
      },
      {
        id: 'environmental_factors',
        label: 'Environmental Factors (Software-Hardware-Environment)',
        type: 'multiselect',
        required: true,
        helpText: 'Select all environmental factors that may have contributed to the event.',
        options: [
          { label: 'Poor Lighting', value: 'lighting' },
          { label: 'Excessive Noise', value: 'noise' },
          { label: 'Extreme Temperature (Hot/Cold)', value: 'temperature' },
          { label: 'Vibration', value: 'vibration' },
          { label: 'Confined / Restricted Workspace', value: 'workspace' },
          { label: 'Height / Working at Height', value: 'height' },
          { label: 'Weather Conditions', value: 'weather' },
          { label: 'Hazardous Substances', value: 'hazardous_substances' },
          { label: 'Tool / Equipment Condition', value: 'tool_condition' },
          { label: 'None Identified', value: 'none' },
        ],
        width: 'full',
      },
      {
        id: 'individual_factors',
        label: 'Individual Factors (Liveware)',
        type: 'multiselect',
        required: true,
        helpText: 'Select individual human factors that may have contributed.',
        options: [
          { label: 'Fatigue', value: 'fatigue' },
          { label: 'Stress (Personal/Work)', value: 'stress' },
          { label: 'Complacency', value: 'complacency' },
          { label: 'Lack of Knowledge', value: 'lack_of_knowledge' },
          { label: 'Lack of Skill / Experience', value: 'lack_of_skill' },
          { label: 'Time Pressure', value: 'pressure' },
          { label: 'Distraction / Interruption', value: 'distraction' },
          { label: 'Lack of Awareness / Situational Awareness', value: 'lack_of_awareness' },
          { label: 'Norms / Habitual Non-Compliance', value: 'norms' },
          { label: 'Communication Failure', value: 'communication' },
          { label: 'Physical Limitation', value: 'physical' },
          { label: 'None Identified', value: 'none' },
        ],
        width: 'full',
      },
      {
        id: 'organizational_factors',
        label: 'Organizational Factors (Liveware-Liveware / Liveware-Software)',
        type: 'multiselect',
        required: true,
        helpText: 'Select organizational and systemic factors.',
        options: [
          { label: 'Inadequate Procedures / Documentation', value: 'procedures' },
          { label: 'Inadequate Training', value: 'training' },
          { label: 'Inadequate Supervision', value: 'supervision' },
          { label: 'Resource Constraints (Staffing)', value: 'staffing' },
          { label: 'Resource Constraints (Tools/Equipment)', value: 'tools' },
          { label: 'Poor Task Planning / Scheduling', value: 'planning' },
          { label: 'Inadequate Communication Systems', value: 'comms_systems' },
          { label: 'Shift Handover Issues', value: 'handover' },
          { label: 'Management Pressure', value: 'management_pressure' },
          { label: 'Culture / Safety Climate', value: 'culture' },
          { label: 'None Identified', value: 'none' },
        ],
        width: 'full',
      },
      {
        id: 'section_shell',
        label: 'SHELL Model Analysis',
        type: 'section',
        width: 'full',
      },
      {
        id: 'shell_analysis',
        label: 'SHELL Model Analysis',
        type: 'textarea',
        required: true,
        placeholder:
          'Analyze the event using the SHELL model:\n\n' +
          'S (Software) — Procedures, manuals, checklists:\n\n' +
          'H (Hardware) — Tools, equipment, aircraft systems:\n\n' +
          'E (Environment) — Physical working conditions:\n\n' +
          'L-L (Liveware-Liveware) — Communication, teamwork, supervision:\n\n' +
          'L (Liveware, central) — Individual capabilities, limitations:',
        helpText: 'The SHELL model examines the interfaces between the central human element (Liveware) and Software, Hardware, Environment, and other Liveware.',
        validation: { minLength: 100, maxLength: 15000 },
        width: 'full',
      },
      {
        id: 'contributing_factors_summary',
        label: 'Contributing Factors Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Summarize the primary and secondary contributing factors. Identify the chain of events and error-producing conditions.',
        width: 'full',
      },
      {
        id: 'section_recommendations',
        label: 'Recommendations & Follow-Up',
        type: 'section',
        width: 'full',
      },
      {
        id: 'recommendations',
        label: 'Recommendations',
        type: 'table',
        required: true,
        helpText: 'Specific, actionable recommendations to prevent recurrence.',
        columns: [
          {
            id: 'rec_id',
            label: 'Rec #',
            type: 'text',
            required: true,
            placeholder: 'R-01',
          },
          {
            id: 'recommendation',
            label: 'Recommendation',
            type: 'textarea',
            required: true,
          },
          {
            id: 'type',
            label: 'Type',
            type: 'select',
            options: [
              { label: 'Procedure Change', value: 'procedure' },
              { label: 'Training', value: 'training' },
              { label: 'Equipment / Tool', value: 'equipment' },
              { label: 'Facility / Environment', value: 'facility' },
              { label: 'Organizational / Management', value: 'organizational' },
              { label: 'Communication', value: 'communication' },
            ],
          },
          {
            id: 'owner',
            label: 'Responsible Party',
            type: 'text',
            required: true,
          },
          {
            id: 'due_date',
            label: 'Due Date',
            type: 'date',
          },
        ],
        width: 'full',
      },
      {
        id: 'follow_up_actions',
        label: 'Follow-Up Actions',
        type: 'table',
        helpText: 'Track completion of recommendations and effectiveness reviews.',
        columns: [
          {
            id: 'action_ref',
            label: 'Rec Reference',
            type: 'text',
            required: true,
            placeholder: 'R-01',
          },
          {
            id: 'action_description',
            label: 'Action Taken',
            type: 'textarea',
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Completed', value: 'completed' },
              { label: 'Verified Effective', value: 'verified' },
            ],
          },
          {
            id: 'completion_date',
            label: 'Completion Date',
            type: 'date',
          },
        ],
        width: 'full',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor',
        type: 'signature',
        required: true,
        width: 'half',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-AERO-008  AS9100D Management Review ────────────────────────
  {
    code: 'TPL-AERO-008',
    name: 'AS9100D Management Review',
    description:
      'Management review meeting template per AS9100D clause 9.3. Covers aerospace-specific review inputs including on-time delivery, product safety, counterfeit part prevention, supplier performance, and risk-based thinking alongside standard QMS review elements.',
    module: 'AEROSPACE',
    category: 'MANAGEMENT_REVIEW',
    tags: ['management-review', 'AS9100D', 'clause-9.3', 'QMS', 'aerospace-quality'],
    isoClause: '9.3',
    fields: [
      {
        id: 'section_meeting',
        label: 'Meeting Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'review_period',
        label: 'Review Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. H1 2026 (Jan-Jun 2026)',
        width: 'half',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'textarea',
        required: true,
        placeholder: 'Name — Title / Function\ne.g. John Doe — Quality Director\nJane Smith — VP Operations',
        helpText: 'Top management with executive responsibility must attend (AS9100D clause 5.1).',
        width: 'full',
      },
      {
        id: 'section_inputs',
        label: 'Review Inputs (AS9100D clause 9.3.2)',
        type: 'section',
        width: 'full',
      },
      {
        id: 'audit_results',
        label: 'Audit Results',
        type: 'textarea',
        required: true,
        placeholder: 'Summary of internal audits, customer audits, certification body (CB) audits, and regulatory audits. Include major/minor findings and closure status.',
        width: 'full',
      },
      {
        id: 'customer_satisfaction',
        label: 'Customer Satisfaction & Feedback',
        type: 'textarea',
        required: true,
        placeholder: 'Customer scorecards, satisfaction surveys, formal feedback, complaints, warranty claims.',
        helpText: 'Per AS9100D 9.1.2 — monitor customer perception including on-time delivery and quality performance.',
        width: 'full',
      },
      {
        id: 'supplier_performance',
        label: 'Supplier Performance',
        type: 'textarea',
        required: true,
        placeholder: 'Supplier quality metrics, delivery performance, audit results, approved supplier list changes, SCAR status.',
        helpText: 'Per AS9100D 8.4 — external provider performance including risk-based controls.',
        width: 'full',
      },
      {
        id: 'on_time_delivery',
        label: 'On-Time Delivery Performance',
        type: 'textarea',
        required: true,
        placeholder: 'OTD metrics by programme/customer, root causes for late deliveries, improvement actions.',
        helpText: 'AS9100D specific requirement — on-time delivery is a key aerospace performance indicator.',
        width: 'full',
      },
      {
        id: 'quality_kpis',
        label: 'Quality Objectives & KPIs',
        type: 'textarea',
        required: true,
        placeholder: 'Status against quality objectives: scrap rate, rework rate, first pass yield, customer escapes, cost of quality.',
        width: 'full',
      },
      {
        id: 'risk_actions',
        label: 'Risks & Opportunities (Risk-Based Thinking)',
        type: 'textarea',
        required: true,
        placeholder: 'Status of risk register, new risks identified, effectiveness of risk mitigation actions, opportunities for improvement.',
        helpText: 'Per AS9100D 6.1 — actions to address risks and opportunities.',
        width: 'full',
      },
      {
        id: 'product_safety',
        label: 'Product Safety',
        type: 'textarea',
        required: true,
        placeholder: 'Product safety incidents, product safety reviews, airworthiness concerns, mandatory occurrence reports.',
        helpText: 'AS9100D 8.1.1 — product safety is a mandatory management review input in aerospace.',
        width: 'full',
      },
      {
        id: 'counterfeit_prevention',
        label: 'Counterfeit Part Prevention',
        type: 'textarea',
        required: true,
        placeholder: 'Counterfeit detection events, suspect parts, supplier verification activities, prevention programme effectiveness.',
        helpText: 'AS9100D 8.1.4 — counterfeit or suspect unapproved part prevention and detection.',
        width: 'full',
      },
      {
        id: 'capa_status',
        label: 'Nonconformity & Corrective Action Status',
        type: 'textarea',
        required: true,
        placeholder: 'Open NCRs, CAPA metrics, effectiveness reviews, recurring nonconformities, trends.',
        width: 'full',
      },
      {
        id: 'previous_review_actions',
        label: 'Status of Previous Management Review Actions',
        type: 'textarea',
        required: true,
        placeholder: 'Review and update each action item from the previous management review.',
        width: 'full',
      },
      {
        id: 'section_outputs',
        label: 'Review Outputs (AS9100D clause 9.3.3)',
        type: 'section',
        width: 'full',
      },
      {
        id: 'improvements',
        label: 'Improvement Decisions & Actions',
        type: 'table',
        required: true,
        helpText: 'Decisions and actions arising from the management review.',
        columns: [
          {
            id: 'action_id',
            label: 'Action ID',
            type: 'text',
            required: true,
            placeholder: 'MR-2026-ACT-001',
          },
          {
            id: 'description',
            label: 'Description',
            type: 'textarea',
            required: true,
          },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            options: [
              { label: 'Process Improvement', value: 'process' },
              { label: 'Quality Objective', value: 'objective' },
              { label: 'Resource Allocation', value: 'resource' },
              { label: 'Training', value: 'training' },
              { label: 'Supplier Management', value: 'supplier' },
              { label: 'Product Safety', value: 'safety' },
              { label: 'Corrective Action', value: 'corrective' },
              { label: 'System Change', value: 'system' },
            ],
          },
          {
            id: 'owner',
            label: 'Owner',
            type: 'text',
            required: true,
          },
          {
            id: 'due_date',
            label: 'Due Date',
            type: 'date',
            required: true,
          },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'resource_needs',
        label: 'Resource Needs',
        type: 'textarea',
        required: true,
        placeholder: 'Approved resource allocations: personnel, equipment, facility, budget, training investments.',
        helpText: 'Per AS9100D 9.3.3(b) — resource needs identified during the review.',
        width: 'full',
      },
      {
        id: 'objectives_update',
        label: 'Quality Objectives Update',
        type: 'textarea',
        placeholder: 'Any updates or revisions to quality objectives and targets for the next review period.',
        width: 'full',
      },
      {
        id: 'section_next_and_approval',
        label: 'Next Review & Approval',
        type: 'section',
        width: 'full',
      },
      {
        id: 'next_review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        helpText: 'AS9100D requires management reviews at planned intervals. Typically quarterly or semi-annually for aerospace.',
        width: 'half',
      },
      {
        id: 'chair_signature',
        label: 'Meeting Chair / Accountable Manager',
        type: 'signature',
        required: true,
        helpText: 'Signature of the management representative or accountable manager.',
        width: 'half',
      },
      {
        id: 'quality_director_signature',
        label: 'Quality Director',
        type: 'signature',
        required: true,
        width: 'half',
      },
      {
        id: 'minutes_approved_date',
        label: 'Minutes Approved Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },
];
