import type { TemplateDefinition } from '../types';

export const assetsTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-AST-001',
    name: 'Asset Register Entry',
    description:
      'Asset registration form for recording new assets including identification, classification, location, maintenance schedule, and depreciation details.',
    module: 'ASSETS',
    category: 'COMPLIANCE',
    tags: ['asset-register', 'asset-management', 'inventory', 'classification'],
    fields: [
      { id: 'section_asset', label: 'Asset Details', type: 'section' },
      { id: 'asset_tag', label: 'Asset Tag / ID', type: 'text', required: true, placeholder: 'e.g. AST-2026-0001', width: 'half', section: 'Asset Details' },
      { id: 'asset_name', label: 'Asset Name', type: 'text', required: true, width: 'half', section: 'Asset Details' },
      { id: 'category', label: 'Category', type: 'select', required: true, options: [{ label: 'Equipment', value: 'equipment' }, { label: 'Vehicle', value: 'vehicle' }, { label: 'IT Hardware', value: 'it_hardware' }, { label: 'Furniture', value: 'furniture' }, { label: 'Building', value: 'building' }, { label: 'Tool', value: 'tool' }, { label: 'Other', value: 'other' }], width: 'half', section: 'Asset Details' },
      { id: 'manufacturer', label: 'Manufacturer', type: 'text', width: 'half', section: 'Asset Details' },
      { id: 'model', label: 'Model / Part Number', type: 'text', width: 'half', section: 'Asset Details' },
      { id: 'serial_number', label: 'Serial Number', type: 'text', width: 'half', section: 'Asset Details' },
      { id: 'location', label: 'Location', type: 'text', required: true, width: 'half', section: 'Asset Details' },
      { id: 'department', label: 'Department', type: 'text', required: true, width: 'half', section: 'Asset Details' },
      { id: 'custodian', label: 'Custodian / Responsible Person', type: 'text', required: true, width: 'half', section: 'Asset Details' },
      { id: 'section_financial', label: 'Financial Details', type: 'section' },
      { id: 'purchase_date', label: 'Purchase Date', type: 'date', required: true, width: 'half', section: 'Financial Details' },
      { id: 'purchase_cost', label: 'Purchase Cost (GBP)', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Financial Details' },
      { id: 'warranty_expiry', label: 'Warranty Expiry', type: 'date', width: 'half', section: 'Financial Details' },
      { id: 'useful_life', label: 'Useful Life (years)', type: 'number', validation: { min: 1, max: 50 }, width: 'half', section: 'Financial Details' },
      { id: 'section_maintenance', label: 'Maintenance', type: 'section' },
      { id: 'maintenance_schedule', label: 'Maintenance Schedule', type: 'select', options: [{ label: 'Weekly', value: 'weekly' }, { label: 'Monthly', value: 'monthly' }, { label: 'Quarterly', value: 'quarterly' }, { label: 'Biannual', value: 'biannual' }, { label: 'Annual', value: 'annual' }, { label: 'As Required', value: 'as_required' }], width: 'half', section: 'Maintenance' },
      { id: 'criticality', label: 'Criticality', type: 'select', required: true, options: [{ label: 'Critical', value: 'critical' }, { label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }], width: 'half', section: 'Maintenance' },
      { id: 'notes', label: 'Notes', type: 'textarea', validation: { maxLength: 2000 }, width: 'full', section: 'Maintenance' },
    ],
  },
  {
    code: 'TPL-AST-002',
    name: 'Asset Condition Assessment',
    description:
      'Periodic condition assessment form for evaluating asset health, identifying defects, and recommending maintenance or replacement actions.',
    module: 'ASSETS',
    category: 'INSPECTION',
    tags: ['condition-assessment', 'asset-inspection', 'defect', 'maintenance'],
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      { id: 'asset_tag', label: 'Asset Tag / ID', type: 'text', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'asset_name', label: 'Asset Name', type: 'text', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'assessment_date', label: 'Assessment Date', type: 'date', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'assessor', label: 'Assessor', type: 'text', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'section_condition', label: 'Condition Rating', type: 'section' },
      { id: 'overall_condition', label: 'Overall Condition', type: 'select', required: true, options: [{ label: '1 — Excellent (new/like new)', value: '1' }, { label: '2 — Good (minor wear)', value: '2' }, { label: '3 — Fair (moderate wear, functional)', value: '3' }, { label: '4 — Poor (significant deterioration)', value: '4' }, { label: '5 — Critical (failure imminent)', value: '5' }], width: 'half', section: 'Condition Rating' },
      { id: 'operational_status', label: 'Operational Status', type: 'select', required: true, options: [{ label: 'Fully Operational', value: 'operational' }, { label: 'Operational with Limitations', value: 'limited' }, { label: 'Non-Operational', value: 'non_operational' }], width: 'half', section: 'Condition Rating' },
      { id: 'section_findings', label: 'Findings', type: 'section' },
      {
        id: 'defects',
        label: 'Defects / Issues Found',
        type: 'table',
        columns: [
          { id: 'component', label: 'Component / Area', type: 'text', required: true },
          { id: 'defect', label: 'Defect Description', type: 'text', required: true },
          { id: 'severity', label: 'Severity', type: 'select', required: true, options: [{ label: 'Critical', value: 'critical' }, { label: 'Major', value: 'major' }, { label: 'Minor', value: 'minor' }, { label: 'Cosmetic', value: 'cosmetic' }] },
          { id: 'action', label: 'Recommended Action', type: 'select', options: [{ label: 'Immediate Repair', value: 'immediate' }, { label: 'Scheduled Repair', value: 'scheduled' }, { label: 'Monitor', value: 'monitor' }, { label: 'Replace', value: 'replace' }] },
        ],
        section: 'Findings',
      },
      { id: 'remaining_life', label: 'Estimated Remaining Useful Life', type: 'text', placeholder: 'e.g. 3-5 years', width: 'half', section: 'Findings' },
      { id: 'recommendation', label: 'Recommendation', type: 'select', required: true, options: [{ label: 'Continue Use', value: 'continue' }, { label: 'Repair Required', value: 'repair' }, { label: 'Refurbishment Required', value: 'refurbish' }, { label: 'Replace', value: 'replace' }, { label: 'Decommission', value: 'decommission' }], width: 'half', section: 'Findings' },
      { id: 'comments', label: 'Additional Comments', type: 'textarea', validation: { maxLength: 2000 }, width: 'full', section: 'Findings' },
      { id: 'assessor_signature', label: 'Assessor Signature', type: 'signature', required: true, section: 'Findings' },
    ],
  },
  {
    code: 'TPL-AST-003',
    name: 'Asset Disposal / Decommissioning Record',
    description:
      'Record for documenting asset disposal or decommissioning, including reason, method, environmental considerations, and approval chain.',
    module: 'ASSETS',
    category: 'COMPLIANCE',
    tags: ['asset-disposal', 'decommissioning', 'write-off', 'environmental'],
    fields: [
      { id: 'section_header', label: 'Disposal Details', type: 'section' },
      { id: 'asset_tag', label: 'Asset Tag / ID', type: 'text', required: true, width: 'half', section: 'Disposal Details' },
      { id: 'asset_name', label: 'Asset Name', type: 'text', required: true, width: 'half', section: 'Disposal Details' },
      { id: 'disposal_date', label: 'Disposal Date', type: 'date', required: true, width: 'half', section: 'Disposal Details' },
      { id: 'requested_by', label: 'Requested By', type: 'text', required: true, width: 'half', section: 'Disposal Details' },
      { id: 'reason', label: 'Reason for Disposal', type: 'select', required: true, options: [{ label: 'End of Life', value: 'end_of_life' }, { label: 'Beyond Economical Repair', value: 'ber' }, { label: 'Obsolete', value: 'obsolete' }, { label: 'Surplus', value: 'surplus' }, { label: 'Damaged', value: 'damaged' }, { label: 'Replaced', value: 'replaced' }], width: 'half', section: 'Disposal Details' },
      { id: 'disposal_method', label: 'Disposal Method', type: 'select', required: true, options: [{ label: 'Sale', value: 'sale' }, { label: 'Recycling', value: 'recycling' }, { label: 'Scrap', value: 'scrap' }, { label: 'Donation', value: 'donation' }, { label: 'Trade-In', value: 'trade_in' }, { label: 'WEEE Disposal', value: 'weee' }], width: 'half', section: 'Disposal Details' },
      { id: 'section_financial', label: 'Financial', type: 'section' },
      { id: 'book_value', label: 'Current Book Value (GBP)', type: 'number', validation: { min: 0 }, width: 'half', section: 'Financial' },
      { id: 'disposal_value', label: 'Disposal Value (GBP)', type: 'number', validation: { min: 0 }, width: 'half', section: 'Financial' },
      { id: 'section_environmental', label: 'Environmental Considerations', type: 'section' },
      { id: 'hazardous_materials', label: 'Contains Hazardous Materials?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }], width: 'half', section: 'Environmental Considerations' },
      { id: 'hazardous_details', label: 'Hazardous Material Details', type: 'textarea', placeholder: 'If yes, describe hazardous materials and special handling requirements...', validation: { maxLength: 2000 }, width: 'full', section: 'Environmental Considerations' },
      { id: 'data_wiped', label: 'Data Wiped (if IT asset)?', type: 'select', options: [{ label: 'Yes — Certificate Attached', value: 'yes_cert' }, { label: 'Yes — Self-certified', value: 'yes_self' }, { label: 'N/A', value: 'na' }], width: 'half', section: 'Environmental Considerations' },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      { id: 'department_approval', label: 'Department Manager Approval', type: 'signature', required: true, section: 'Approval' },
      { id: 'finance_approval', label: 'Finance Approval', type: 'signature', required: true, section: 'Approval' },
    ],
  },
  {
    code: 'TPL-AST-004',
    name: 'Asset Calibration Record',
    description: 'Record for documenting calibration of measuring equipment and instruments, including standards used, results, and next calibration date.',
    module: 'ASSETS',
    category: 'INSPECTION',
    tags: ['calibration', 'measuring-equipment', 'traceability', 'iso-9001'],
    isoClause: '7.1.5',
    fields: [
      { id: 'section_asset', label: 'Asset Details', type: 'section' },
      { id: 'asset_tag', label: 'Asset Tag / ID', type: 'text', required: true, width: 'half', section: 'Asset Details' },
      { id: 'asset_name', label: 'Instrument Name', type: 'text', required: true, width: 'half', section: 'Asset Details' },
      { id: 'manufacturer', label: 'Manufacturer', type: 'text', width: 'half', section: 'Asset Details' },
      { id: 'serial_number', label: 'Serial Number', type: 'text', required: true, width: 'half', section: 'Asset Details' },
      { id: 'section_calibration', label: 'Calibration Details', type: 'section' },
      { id: 'calibration_date', label: 'Calibration Date', type: 'date', required: true, width: 'half', section: 'Calibration Details' },
      { id: 'next_calibration', label: 'Next Calibration Due', type: 'date', required: true, width: 'half', section: 'Calibration Details' },
      { id: 'calibrated_by', label: 'Calibrated By', type: 'text', required: true, width: 'half', section: 'Calibration Details' },
      { id: 'cal_type', label: 'Calibration Type', type: 'select', required: true, options: [{ label: 'Internal', value: 'internal' }, { label: 'External (UKAS)', value: 'external_ukas' }, { label: 'External (Non-UKAS)', value: 'external_non_ukas' }], width: 'half', section: 'Calibration Details' },
      { id: 'reference_standard', label: 'Reference Standard Used', type: 'text', required: true, width: 'full', section: 'Calibration Details' },
      { id: 'section_results', label: 'Results', type: 'section' },
      {
        id: 'readings',
        label: 'Calibration Readings',
        type: 'table',
        required: true,
        columns: [
          { id: 'test_point', label: 'Test Point', type: 'text', required: true },
          { id: 'nominal', label: 'Nominal Value', type: 'text', required: true },
          { id: 'measured', label: 'Measured Value', type: 'text', required: true },
          { id: 'tolerance', label: 'Tolerance', type: 'text', required: true },
          { id: 'pass_fail', label: 'Result', type: 'select', required: true, options: [{ label: 'Pass', value: 'pass' }, { label: 'Fail', value: 'fail' }] },
        ],
        section: 'Results',
      },
      { id: 'overall_result', label: 'Overall Result', type: 'select', required: true, options: [{ label: 'Pass — In Tolerance', value: 'pass' }, { label: 'Fail — Out of Tolerance', value: 'fail' }, { label: 'Adjusted & Re-Tested — Pass', value: 'adjusted_pass' }], width: 'half', section: 'Results' },
      { id: 'action_if_fail', label: 'Action if Fail', type: 'textarea', placeholder: 'Describe corrective action for out-of-tolerance instruments...', validation: { maxLength: 2000 }, width: 'full', section: 'Results' },
      { id: 'technician_signature', label: 'Calibration Technician', type: 'signature', required: true, section: 'Results' },
    ],
  },
];
