import type { TemplateDefinition } from '../types';

export const automotiveTemplates: TemplateDefinition[] = [
  // ─── TPL-AUTO-001  APQP Project Plan ──────────────────────────────────
  {
    code: 'TPL-AUTO-001',
    name: 'APQP Project Plan',
    description:
      'Advanced Product Quality Planning project plan covering all five APQP phases with milestones, deliverables, and team assignments per IATF 16949.',
    module: 'AUTOMOTIVE',
    category: 'PLANNING',
    tags: ['apqp', 'project-plan', 'iatf-16949', 'new-product', 'launch'],
    isoClause: '8.3',
    fields: [
      {
        id: 'apqp-header',
        label: 'Project Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'projectName',
        label: 'Project Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. New Brake Caliper Assembly - 2026 Model',
        helpText: 'Descriptive name for the APQP project.',
        width: 'half',
      },
      {
        id: 'customer',
        label: 'Customer',
        type: 'text',
        required: true,
        placeholder: 'OEM or Tier-1 customer name',
        helpText: 'Customer requesting the new product or change.',
        width: 'half',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Customer or internal part number',
        width: 'half',
      },
      {
        id: 'projectStartDate',
        label: 'Project Start Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'sopDate',
        label: 'Target SOP Date',
        type: 'date',
        required: true,
        helpText: 'Target Start of Production date.',
        width: 'half',
      },
      {
        id: 'phases-section',
        label: 'APQP Phase Milestones',
        type: 'section',
        width: 'full',
      },
      {
        id: 'phases',
        label: 'Phase Milestones & Timing',
        type: 'table',
        required: true,
        helpText: 'Define milestones for each APQP phase with planned dates and status.',
        columns: [
          {
            id: 'phase',
            label: 'Phase',
            type: 'select',
            required: true,
            options: [
              { label: 'Phase 1 - Plan & Define', value: 'phase_1' },
              { label: 'Phase 2 - Product Design & Dev', value: 'phase_2' },
              { label: 'Phase 3 - Process Design & Dev', value: 'phase_3' },
              { label: 'Phase 4 - Product & Process Validation', value: 'phase_4' },
              { label: 'Phase 5 - Feedback & Corrective Action', value: 'phase_5' },
            ],
            width: 'half',
          },
          {
            id: 'milestone',
            label: 'Milestone / Deliverable',
            type: 'text',
            required: true,
            width: 'full',
          },
          { id: 'plannedDate', label: 'Planned Date', type: 'date', required: true, width: 'half' },
          { id: 'actualDate', label: 'Actual Date', type: 'date', width: 'half' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Not Started', value: 'not_started' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Completed', value: 'completed' },
              { label: 'Delayed', value: 'delayed' },
              { label: 'At Risk', value: 'at_risk' },
            ],
            width: 'half',
          },
        ],
        width: 'full',
      },
      {
        id: 'team-section',
        label: 'Project Team',
        type: 'section',
        width: 'full',
      },
      {
        id: 'teamMembers',
        label: 'Team Members',
        type: 'table',
        required: true,
        helpText: 'Cross-functional team assigned to the APQP project.',
        columns: [
          { id: 'memberName', label: 'Name', type: 'text', required: true, width: 'half' },
          { id: 'memberRole', label: 'Role', type: 'text', required: true, width: 'half' },
          { id: 'memberDept', label: 'Department', type: 'text', width: 'half' },
          { id: 'memberContact', label: 'Contact', type: 'email', width: 'half' },
        ],
        width: 'full',
      },
      {
        id: 'timing-section',
        label: 'Timing Chart',
        type: 'section',
        width: 'full',
      },
      {
        id: 'prototypeDate',
        label: 'Prototype Completion',
        type: 'date',
        helpText: 'Target date for prototype build completion.',
        width: 'third',
      },
      {
        id: 'pilotDate',
        label: 'Pilot Run Date',
        type: 'date',
        helpText: 'Target date for pilot production run.',
        width: 'third',
      },
      {
        id: 'ppapDate',
        label: 'PPAP Submission Date',
        type: 'date',
        helpText: 'Target date for Part Submission Warrant.',
        width: 'third',
      },
      {
        id: 'deliverables-section',
        label: 'APQP Deliverables Checklist',
        type: 'section',
        width: 'full',
      },
      {
        id: 'deliverables',
        label: 'Deliverables Checklist',
        type: 'table',
        required: true,
        helpText: 'Track completion status of all APQP deliverables.',
        columns: [
          { id: 'deliverable', label: 'Deliverable', type: 'text', required: true, width: 'full' },
          { id: 'deliverablePhase', label: 'Phase', type: 'text', width: 'third' },
          { id: 'deliverableComplete', label: 'Complete', type: 'checkbox', width: 'third' },
          { id: 'deliverableNotes', label: 'Notes', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
    ],
  },

  // ─── TPL-AUTO-002  APQP Gate Review ───────────────────────────────────
  {
    code: 'TPL-AUTO-002',
    name: 'APQP Gate Review',
    description:
      'APQP phase gate review form for evaluating readiness to proceed to the next development phase. Documents deliverables status, open issues, and gate decision.',
    module: 'AUTOMOTIVE',
    category: 'DESIGN_DEVELOPMENT',
    tags: ['apqp', 'gate-review', 'phase-gate', 'iatf-16949', 'milestone'],
    isoClause: '8.3.4',
    fields: [
      {
        id: 'gate-header',
        label: 'Gate Review Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'gateNumber',
        label: 'Gate Number',
        type: 'select',
        required: true,
        helpText: 'APQP phase gate being reviewed.',
        options: [
          { label: 'Gate 1 - Program Approval', value: '1' },
          { label: 'Gate 2 - Design Approval', value: '2' },
          { label: 'Gate 3 - Process Approval', value: '3' },
          { label: 'Gate 4 - Product & Process Validation', value: '4' },
          { label: 'Gate 5 - Production Launch', value: '5' },
        ],
        width: 'half',
      },
      {
        id: 'project',
        label: 'Project Name / Part Number',
        type: 'text',
        required: true,
        placeholder: 'Project name and customer part number',
        width: 'half',
      },
      {
        id: 'reviewDate',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'deliverables-section',
        label: 'Deliverables Status',
        type: 'section',
        width: 'full',
      },
      {
        id: 'deliverables',
        label: 'Deliverables Checklist',
        type: 'table',
        required: true,
        helpText: 'Evaluate completion status of all gate deliverables.',
        columns: [
          { id: 'deliverable', label: 'Deliverable', type: 'text', required: true, width: 'full' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Complete', value: 'complete' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Not Started', value: 'not_started' },
              { label: 'Not Applicable', value: 'na' },
            ],
            width: 'half',
          },
          { id: 'evidence', label: 'Evidence / Reference', type: 'text', width: 'half' },
          { id: 'notes', label: 'Notes', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'issues-section',
        label: 'Open Issues',
        type: 'section',
        width: 'full',
      },
      {
        id: 'openIssues',
        label: 'Open Issues',
        type: 'table',
        helpText: 'List all open issues that may impact the gate decision.',
        columns: [
          { id: 'issueRef', label: 'Issue #', type: 'text', required: true, width: 'third' },
          {
            id: 'issueDescription',
            label: 'Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          {
            id: 'issueSeverity',
            label: 'Severity',
            type: 'select',
            options: [
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Critical', value: 'critical' },
            ],
            required: true,
            width: 'third',
          },
          { id: 'issueOwner', label: 'Owner', type: 'text', required: true, width: 'half' },
          { id: 'issueDueDate', label: 'Due Date', type: 'date', required: true, width: 'half' },
        ],
        width: 'full',
      },
      {
        id: 'decision-section',
        label: 'Gate Decision',
        type: 'section',
        width: 'full',
      },
      {
        id: 'gateDecision',
        label: 'Decision',
        type: 'select',
        required: true,
        helpText: 'Gate review outcome.',
        options: [
          { label: 'Pass - Proceed to Next Phase', value: 'pass' },
          { label: 'Conditional Pass - Actions Required', value: 'conditional' },
          { label: 'Fail - Rework and Re-Review', value: 'fail' },
        ],
        width: 'half',
      },
      {
        id: 'conditions',
        label: 'Conditions / Comments',
        type: 'textarea',
        placeholder: 'For conditional pass, list conditions that must be met before proceeding...',
        helpText: 'Conditions for conditional approval or reasons for failure.',
        width: 'full',
      },
      {
        id: 'approvals-section',
        label: 'Approvals',
        type: 'section',
        width: 'full',
      },
      {
        id: 'projectManagerApproval',
        label: 'Project Manager Approval',
        type: 'signature',
        required: true,
        width: 'half',
      },
      {
        id: 'qualityManagerApproval',
        label: 'Quality Manager Approval',
        type: 'signature',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-AUTO-003  Part Submission Warrant (PSW) ──────────────────────
  {
    code: 'TPL-AUTO-003',
    name: 'Part Submission Warrant (PSW)',
    description:
      'PPAP Part Submission Warrant documenting part approval status between supplier and customer. Covers submission level, declaration of compliance, and customer disposition.',
    module: 'AUTOMOTIVE',
    category: 'CERTIFICATION',
    tags: ['ppap', 'psw', 'part-submission', 'iatf-16949', 'customer-approval'],
    isoClause: '8.3.4',
    fields: [
      {
        id: 'psw-header',
        label: 'Part Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'partName',
        label: 'Part Name',
        type: 'text',
        required: true,
        placeholder: 'Descriptive part name',
        width: 'half',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Customer part number',
        width: 'half',
      },
      {
        id: 'drawingNumber',
        label: 'Drawing Number',
        type: 'text',
        required: true,
        placeholder: 'Engineering drawing number and revision',
        width: 'half',
      },
      {
        id: 'customer',
        label: 'Customer Name',
        type: 'text',
        required: true,
        placeholder: 'OEM or Tier-1 customer',
        width: 'half',
      },
      {
        id: 'customerBuyerCode',
        label: 'Customer Buyer Code',
        type: 'text',
        placeholder: 'Customer buyer / purchasing code',
        width: 'half',
      },
      {
        id: 'submission-section',
        label: 'Submission Details',
        type: 'section',
        width: 'full',
      },
      {
        id: 'submissionLevel',
        label: 'PPAP Submission Level',
        type: 'select',
        required: true,
        helpText: 'Level of evidence required per AIAG PPAP manual.',
        options: [
          { label: 'Level 1 - Warrant only', value: '1' },
          { label: 'Level 2 - Warrant with limited samples & data', value: '2' },
          { label: 'Level 3 - Warrant with full samples & data (default)', value: '3' },
          { label: 'Level 4 - Warrant with full data (per customer)', value: '4' },
          { label: 'Level 5 - Warrant with all data at supplier site', value: '5' },
        ],
        width: 'half',
      },
      {
        id: 'submissionReason',
        label: 'Reason for Submission',
        type: 'select',
        required: true,
        helpText: 'Reason for this PPAP submission.',
        options: [
          { label: 'Initial Submission', value: 'initial' },
          { label: 'Engineering Change', value: 'engineering_change' },
          { label: 'Tooling Transfer / Replacement', value: 'tooling' },
          { label: 'Correction of Discrepancy', value: 'correction' },
          { label: 'Sub-Supplier Change', value: 'sub_supplier' },
          { label: 'Change to Optional Material', value: 'material_change' },
          { label: 'Inactive > 1 Year', value: 'inactive' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
      },
      {
        id: 'declaration-section',
        label: 'Supplier Declaration',
        type: 'section',
        width: 'full',
      },
      {
        id: 'partsConform',
        label: 'Parts meet all applicable drawing specifications and requirements',
        type: 'checkbox',
        required: true,
        helpText: 'Confirm parts conform to all engineering specifications.',
        width: 'full',
      },
      {
        id: 'statisticalData',
        label: 'Statistical data conforms to applicable customer requirements',
        type: 'checkbox',
        required: true,
        width: 'full',
      },
      {
        id: 'materialsApproved',
        label: 'All materials comply with applicable requirements (IMDS/REACH/RoHS)',
        type: 'checkbox',
        required: true,
        width: 'full',
      },
      {
        id: 'samplesPrepared',
        label: 'Sample parts provided were taken from production run',
        type: 'checkbox',
        required: true,
        helpText: 'Confirm samples are from a significant production run, not prototypes.',
        width: 'full',
      },
      {
        id: 'results-section',
        label: 'Results Summary',
        type: 'section',
        width: 'full',
      },
      {
        id: 'resultsSummary',
        label: 'PPAP Elements Results',
        type: 'table',
        required: true,
        helpText: 'Summary of results for each PPAP element submitted.',
        columns: [
          { id: 'ppapElement', label: 'PPAP Element', type: 'text', required: true, width: 'full' },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Acceptable', value: 'acceptable' },
              { label: 'Not Acceptable', value: 'not_acceptable' },
              { label: 'Not Applicable', value: 'na' },
              { label: 'Not Submitted', value: 'not_submitted' },
            ],
            width: 'half',
          },
          { id: 'remarks', label: 'Remarks', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'disposition-section',
        label: 'Customer Disposition',
        type: 'section',
        width: 'full',
      },
      {
        id: 'customerDisposition',
        label: 'Customer Decision',
        type: 'select',
        required: true,
        helpText: 'Customer disposition of the PPAP submission.',
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Interim Approval', value: 'interim' },
          { label: 'Rejected', value: 'rejected' },
        ],
        width: 'half',
      },
      {
        id: 'supplierSignature',
        label: 'Supplier Authorized Signature',
        type: 'signature',
        required: true,
        helpText: 'Supplier quality representative signature.',
        width: 'half',
      },
      {
        id: 'customerSignature',
        label: 'Customer Authorized Signature',
        type: 'signature',
        helpText: 'Customer quality representative signature upon disposition.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-AUTO-004  Dimensional Results Report ─────────────────────────
  {
    code: 'TPL-AUTO-004',
    name: 'Dimensional Results Report',
    description:
      'PPAP dimensional measurement results documenting actual vs specification for all product characteristics. Used as supporting evidence for Part Submission Warrant.',
    module: 'AUTOMOTIVE',
    category: 'INSPECTION',
    tags: ['ppap', 'dimensional', 'measurement', 'inspection', 'iatf-16949'],
    isoClause: '8.6',
    fields: [
      {
        id: 'dim-header',
        label: 'Part Identification',
        type: 'section',
        width: 'full',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Customer part number',
        width: 'third',
      },
      {
        id: 'partName',
        label: 'Part Name',
        type: 'text',
        required: true,
        placeholder: 'Descriptive part name',
        width: 'third',
      },
      {
        id: 'drawingRev',
        label: 'Drawing Revision',
        type: 'text',
        required: true,
        placeholder: 'e.g. Rev C',
        helpText: 'Engineering drawing revision level.',
        width: 'third',
      },
      {
        id: 'sampleSize',
        label: 'Sample Size',
        type: 'number',
        required: true,
        placeholder: '5',
        helpText: 'Number of parts measured (typically 3-5 for PPAP).',
        validation: { min: 1, max: 100 },
        width: 'half',
      },
      {
        id: 'measurementDate',
        label: 'Measurement Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'results-section',
        label: 'Dimensional Measurement Results',
        type: 'section',
        width: 'full',
      },
      {
        id: 'measurementResults',
        label: 'Measurement Results',
        type: 'table',
        required: true,
        helpText: 'Record actual measurements against specifications for each characteristic.',
        columns: [
          {
            id: 'charNumber',
            label: 'Char #',
            type: 'text',
            required: true,
            width: 'third',
            placeholder: 'e.g. 1.1',
          },
          {
            id: 'characteristic',
            label: 'Characteristic',
            type: 'text',
            required: true,
            width: 'full',
          },
          {
            id: 'specification',
            label: 'Specification',
            type: 'text',
            required: true,
            width: 'half',
            placeholder: 'e.g. 25.0 +/- 0.1 mm',
          },
          {
            id: 'actual',
            label: 'Actual Measurement',
            type: 'text',
            required: true,
            width: 'half',
            placeholder: 'e.g. 25.02 mm',
          },
          {
            id: 'deviation',
            label: 'Deviation',
            type: 'text',
            width: 'third',
            placeholder: 'e.g. +0.02',
          },
          {
            id: 'passFail',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
            ],
            width: 'third',
          },
        ],
        width: 'full',
      },
      {
        id: 'instruments-section',
        label: 'Measurement Equipment',
        type: 'section',
        width: 'full',
      },
      {
        id: 'instrumentsUsed',
        label: 'Instruments Used',
        type: 'table',
        required: true,
        helpText: 'List all measurement instruments used with calibration status.',
        columns: [
          { id: 'instrument', label: 'Instrument', type: 'text', required: true, width: 'half' },
          {
            id: 'instrumentId',
            label: 'ID / Serial #',
            type: 'text',
            required: true,
            width: 'half',
          },
          { id: 'calDate', label: 'Calibration Date', type: 'date', width: 'half' },
          { id: 'calDue', label: 'Calibration Due', type: 'date', width: 'half' },
        ],
        width: 'full',
      },
      {
        id: 'measurementConditions',
        label: 'Measurement Conditions',
        type: 'textarea',
        placeholder: 'Temperature, humidity, fixture details, part orientation...',
        helpText: 'Environmental and setup conditions during measurement.',
        width: 'full',
      },
      {
        id: 'inspectorSignature',
        label: 'Inspector Signature',
        type: 'signature',
        required: true,
        helpText: 'Inspector who performed the measurements.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-AUTO-005  Material Test Results ──────────────────────────────
  {
    code: 'TPL-AUTO-005',
    name: 'Material Test Results',
    description:
      'Material and performance test results report for PPAP submission. Documents material certifications, test results vs specifications, and lab accreditation.',
    module: 'AUTOMOTIVE',
    category: 'INSPECTION',
    tags: ['ppap', 'material-test', 'certification', 'iatf-16949', 'lab-results'],
    isoClause: '8.6',
    fields: [
      {
        id: 'material-header',
        label: 'Material Identification',
        type: 'section',
        width: 'full',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Customer part number',
        width: 'half',
      },
      {
        id: 'materialSpec',
        label: 'Material Specification',
        type: 'text',
        required: true,
        placeholder: 'e.g. SAE J403 Grade 1020, EN 10130 DC04',
        helpText: 'Material specification per engineering drawing or customer requirement.',
        width: 'half',
      },
      {
        id: 'supplierName',
        label: 'Material Supplier',
        type: 'text',
        placeholder: 'Raw material supplier name',
        width: 'half',
      },
      {
        id: 'heatLotNumber',
        label: 'Heat / Lot Number',
        type: 'text',
        placeholder: 'Mill heat number or lot traceability code',
        helpText: 'Traceability number linking to the raw material batch.',
        width: 'half',
      },
      {
        id: 'results-section',
        label: 'Test Results',
        type: 'section',
        width: 'full',
      },
      {
        id: 'testResults',
        label: 'Test Results',
        type: 'table',
        required: true,
        helpText: 'Record all material and performance test results.',
        columns: [
          { id: 'testName', label: 'Test', type: 'text', required: true, width: 'half' },
          {
            id: 'specification',
            label: 'Specification',
            type: 'text',
            required: true,
            width: 'half',
            placeholder: 'e.g. Tensile Strength 370-500 MPa',
          },
          { id: 'actual', label: 'Actual Result', type: 'text', required: true, width: 'half' },
          {
            id: 'unit',
            label: 'Unit',
            type: 'text',
            width: 'third',
            placeholder: 'e.g. MPa, HRC, %',
          },
          {
            id: 'passFail',
            label: 'Pass / Fail',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
            ],
            width: 'third',
          },
        ],
        width: 'full',
      },
      {
        id: 'lab-section',
        label: 'Laboratory Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'labName',
        label: 'Laboratory Name',
        type: 'text',
        required: true,
        placeholder: 'Name of testing laboratory',
        helpText: 'Must be an accredited or customer-approved laboratory.',
        width: 'half',
      },
      {
        id: 'testConditions',
        label: 'Test Conditions',
        type: 'textarea',
        placeholder: 'Temperature, test speed, specimen type, test method reference...',
        helpText: 'Conditions under which tests were performed.',
        width: 'full',
      },
      {
        id: 'certifications',
        label: 'Certifications & Accreditation',
        type: 'textarea',
        placeholder: 'ISO 17025 accreditation number, NADCAP, customer-specific approvals...',
        helpText: 'Lab accreditation or certifications applicable to the test scope.',
        width: 'full',
      },
      {
        id: 'materialCertAttached',
        label: 'Material Certificate Attached',
        type: 'checkbox',
        helpText: 'Confirm that the mill certificate or material certificate is attached.',
        width: 'half',
      },
      {
        id: 'inspectorSignature',
        label: 'Inspector / Lab Technician',
        type: 'signature',
        required: true,
        helpText: 'Person responsible for testing and reporting.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-AUTO-006  Control Plan ───────────────────────────────────────
  {
    code: 'TPL-AUTO-006',
    name: 'Control Plan',
    description:
      'Process control plan defining inspection and control methods for each manufacturing step. Required PPAP element per IATF 16949 and AIAG Control Plan methodology.',
    module: 'AUTOMOTIVE',
    category: 'PROCESS_CONTROL',
    tags: ['control-plan', 'ppap', 'process-control', 'iatf-16949', 'spc'],
    isoClause: '8.5.1',
    fields: [
      {
        id: 'cp-header',
        label: 'Control Plan Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Customer part number',
        width: 'third',
      },
      {
        id: 'processName',
        label: 'Process / Description',
        type: 'text',
        required: true,
        placeholder: 'Overall process name',
        width: 'third',
      },
      {
        id: 'cpPhase',
        label: 'Control Plan Phase',
        type: 'select',
        required: true,
        helpText: 'Current phase of the control plan.',
        options: [
          { label: 'Prototype', value: 'prototype' },
          { label: 'Pre-Launch', value: 'pre_launch' },
          { label: 'Production', value: 'production' },
        ],
        width: 'third',
      },
      {
        id: 'team',
        label: 'Core Team',
        type: 'textarea',
        required: true,
        placeholder: 'List cross-functional team members...',
        helpText: 'Names and roles of the team that developed the control plan.',
        width: 'half',
      },
      {
        id: 'cpDate',
        label: 'Date (Original)',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'cpRevDate',
        label: 'Date (Revision)',
        type: 'date',
        helpText: 'Date of the latest revision.',
        width: 'half',
      },
      {
        id: 'controls-section',
        label: 'Control Items',
        type: 'section',
        width: 'full',
      },
      {
        id: 'controlItems',
        label: 'Control Plan Items',
        type: 'table',
        required: true,
        helpText:
          'Define controls for each process step including inspection methods and reaction plans.',
        columns: [
          {
            id: 'processStep',
            label: 'Process Step / Operation',
            type: 'text',
            required: true,
            width: 'full',
          },
          {
            id: 'characteristic',
            label: 'Product / Process Characteristic',
            type: 'text',
            required: true,
            width: 'full',
          },
          {
            id: 'classification',
            label: 'Class',
            type: 'select',
            options: [
              { label: 'Critical (CC)', value: 'cc' },
              { label: 'Significant (SC)', value: 'sc' },
              { label: 'Standard', value: 'standard' },
            ],
            width: 'third',
          },
          {
            id: 'specification',
            label: 'Specification / Tolerance',
            type: 'text',
            required: true,
            placeholder: 'e.g. 12.0 +/- 0.05 mm',
            width: 'half',
          },
          {
            id: 'controlMethod',
            label: 'Control Method / Tool',
            type: 'text',
            required: true,
            placeholder: 'e.g. Caliper, CMM, Visual',
            width: 'half',
          },
          {
            id: 'sampleSize',
            label: 'Sample Size',
            type: 'text',
            placeholder: 'e.g. 5 pcs',
            width: 'third',
          },
          {
            id: 'frequency',
            label: 'Frequency',
            type: 'text',
            placeholder: 'e.g. 1st/last + every 2 hrs',
            width: 'third',
          },
          {
            id: 'reactionPlan',
            label: 'Reaction Plan',
            type: 'textarea',
            placeholder: 'Action if out of spec...',
            width: 'full',
          },
        ],
        width: 'full',
      },
    ],
  },

  // ─── TPL-AUTO-007  Process Flow Diagram ───────────────────────────────
  {
    code: 'TPL-AUTO-007',
    name: 'Process Flow Diagram',
    description:
      'Process flow diagram documenting the sequential manufacturing steps, inspection points, and material flow. Required PPAP element linking to Control Plan and FMEA.',
    module: 'AUTOMOTIVE',
    category: 'PROCESS_CONTROL',
    tags: ['process-flow', 'ppap', 'manufacturing', 'iatf-16949', 'flow-diagram'],
    isoClause: '8.5.1',
    fields: [
      {
        id: 'pfd-header',
        label: 'Process Flow Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Customer part number',
        width: 'half',
      },
      {
        id: 'processName',
        label: 'Process Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Brake Caliper Assembly Process',
        width: 'half',
      },
      {
        id: 'revisionDate',
        label: 'Revision Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'preparedBy',
        label: 'Prepared By',
        type: 'text',
        required: true,
        placeholder: 'Name of process engineer',
        width: 'half',
      },
      {
        id: 'steps-section',
        label: 'Process Steps',
        type: 'section',
        width: 'full',
      },
      {
        id: 'processSteps',
        label: 'Process Steps',
        type: 'table',
        required: true,
        helpText: 'Document each process step in sequential order with classification.',
        columns: [
          {
            id: 'stepNumber',
            label: 'Step #',
            type: 'number',
            required: true,
            width: 'third',
          },
          {
            id: 'description',
            label: 'Step Description',
            type: 'text',
            required: true,
            width: 'full',
          },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Operation', value: 'operation' },
              { label: 'Transport / Move', value: 'transport' },
              { label: 'Inspection / Test', value: 'inspection' },
              { label: 'Delay / Wait', value: 'delay' },
              { label: 'Storage', value: 'storage' },
            ],
            width: 'half',
          },
          {
            id: 'keyCharacteristics',
            label: 'Key Characteristics',
            type: 'textarea',
            placeholder: 'Special or critical characteristics at this step...',
            width: 'full',
          },
          {
            id: 'controls',
            label: 'Controls / Work Instructions',
            type: 'textarea',
            placeholder: 'Reference to WI, control plan item, or inspection point...',
            width: 'full',
          },
        ],
        width: 'full',
      },
      {
        id: 'notes',
        label: 'Process Notes',
        type: 'textarea',
        placeholder: 'Additional notes about the process flow, rework loops, scrap points...',
        helpText: 'Any supplementary information about the process flow.',
        width: 'full',
      },
    ],
  },

  // ─── TPL-AUTO-008  Process Capability Study ───────────────────────────
  {
    code: 'TPL-AUTO-008',
    name: 'Process Capability Study',
    description:
      'Statistical process capability study report documenting Cp, Cpk calculations for key characteristics. Demonstrates process ability to consistently meet specifications.',
    module: 'AUTOMOTIVE',
    category: 'PROCESS_CONTROL',
    tags: ['spc', 'capability', 'cp', 'cpk', 'ppap', 'iatf-16949', 'statistics'],
    isoClause: '8.5.1',
    fields: [
      {
        id: 'capability-header',
        label: 'Study Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Customer part number',
        width: 'half',
      },
      {
        id: 'characteristic',
        label: 'Characteristic',
        type: 'text',
        required: true,
        placeholder: 'e.g. Bore Diameter, Surface Roughness',
        helpText: 'The specific product/process characteristic being studied.',
        width: 'half',
      },
      {
        id: 'specification',
        label: 'Specification',
        type: 'text',
        required: true,
        placeholder: 'e.g. 25.00 +/- 0.05 mm',
        helpText: 'Engineering specification with tolerance.',
        width: 'half',
      },
      {
        id: 'usl',
        label: 'Upper Specification Limit (USL)',
        type: 'number',
        required: true,
        helpText: 'Upper tolerance limit.',
        width: 'third',
      },
      {
        id: 'lsl',
        label: 'Lower Specification Limit (LSL)',
        type: 'number',
        required: true,
        helpText: 'Lower tolerance limit.',
        width: 'third',
      },
      {
        id: 'target',
        label: 'Target / Nominal',
        type: 'number',
        helpText: 'Nominal target value.',
        width: 'third',
      },
      {
        id: 'data-section',
        label: 'Sample Data',
        type: 'section',
        width: 'full',
      },
      {
        id: 'sampleSize',
        label: 'Total Sample Size',
        type: 'number',
        required: true,
        helpText: 'Minimum 30 samples recommended for initial capability study.',
        validation: { min: 25 },
        width: 'third',
      },
      {
        id: 'subgroupSize',
        label: 'Subgroup Size',
        type: 'number',
        helpText: 'Number of consecutive parts per subgroup (typically 3-5).',
        validation: { min: 1, max: 25 },
        width: 'third',
      },
      {
        id: 'collectionPeriod',
        label: 'Data Collection Period',
        type: 'text',
        placeholder: 'e.g. 2026-02-01 to 2026-02-10',
        helpText: 'Time period over which samples were collected.',
        width: 'third',
      },
      {
        id: 'rawData',
        label: 'Raw Measurement Data',
        type: 'textarea',
        required: true,
        placeholder: 'Enter measurements separated by commas or one per line...',
        helpText: 'Individual measurement values from the production run.',
        validation: { minLength: 10 },
        width: 'full',
      },
      {
        id: 'results-section',
        label: 'Capability Results',
        type: 'section',
        width: 'full',
      },
      {
        id: 'mean',
        label: 'Mean (X-bar)',
        type: 'number',
        helpText: 'Calculated process mean.',
        width: 'third',
      },
      {
        id: 'stdDev',
        label: 'Standard Deviation (sigma)',
        type: 'number',
        helpText: 'Calculated process standard deviation.',
        width: 'third',
      },
      {
        id: 'cp',
        label: 'Cp (Process Capability)',
        type: 'number',
        helpText: 'Cp = (USL - LSL) / (6 * sigma). Target >= 1.33.',
        width: 'third',
      },
      {
        id: 'cpk',
        label: 'Cpk (Process Capability Index)',
        type: 'number',
        helpText: 'Cpk = min[(USL - mean), (mean - LSL)] / (3 * sigma). Target >= 1.33.',
        width: 'third',
      },
      {
        id: 'interpretation',
        label: 'Interpretation',
        type: 'textarea',
        placeholder: 'Interpret the capability results: Is the process capable? Centered? Stable?',
        helpText: 'Analysis of results including normality, stability, and capability assessment.',
        width: 'full',
      },
      {
        id: 'actionsIfNotCapable',
        label: 'Actions if Not Capable',
        type: 'textarea',
        placeholder:
          'If Cpk < 1.33, describe improvement actions, 100% inspection plan, or sorting...',
        helpText:
          'Required actions if capability does not meet the minimum requirement (typically Cpk >= 1.33 for existing, >= 1.67 for new processes).',
        width: 'full',
      },
    ],
  },

  // ─── TPL-AUTO-009  Gauge R&R Study Report ─────────────────────────────
  {
    code: 'TPL-AUTO-009',
    name: 'Gauge R&R Study Report',
    description:
      'Measurement System Analysis (MSA) Gauge Repeatability and Reproducibility study report. Evaluates measurement system variation per AIAG MSA Reference Manual.',
    module: 'AUTOMOTIVE',
    category: 'INSPECTION',
    tags: ['msa', 'gauge-rr', 'measurement-system', 'ppap', 'iatf-16949'],
    isoClause: '7.1.5',
    fields: [
      {
        id: 'grr-header',
        label: 'Study Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'gaugeName',
        label: 'Gauge / Instrument Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Digital Micrometer, Bore Gauge',
        helpText: 'Type of measurement instrument being studied.',
        width: 'half',
      },
      {
        id: 'gaugeId',
        label: 'Gauge ID / Serial Number',
        type: 'text',
        required: true,
        placeholder: 'Instrument identification number',
        width: 'half',
      },
      {
        id: 'partNumber',
        label: 'Part Number',
        type: 'text',
        required: true,
        placeholder: 'Part number being measured',
        width: 'half',
      },
      {
        id: 'characteristic',
        label: 'Characteristic Measured',
        type: 'text',
        required: true,
        placeholder: 'e.g. Outer Diameter, Length, Depth',
        helpText: 'The specific dimension or characteristic being evaluated.',
        width: 'half',
      },
      {
        id: 'specification',
        label: 'Specification / Tolerance',
        type: 'text',
        required: true,
        placeholder: 'e.g. 25.00 +/- 0.05 mm',
        width: 'half',
      },
      {
        id: 'studyDate',
        label: 'Study Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'operators-section',
        label: 'Operators',
        type: 'section',
        width: 'full',
      },
      {
        id: 'operators',
        label: 'Operators',
        type: 'table',
        required: true,
        helpText: 'List all operators participating in the study (typically 3).',
        columns: [
          {
            id: 'operatorName',
            label: 'Operator Name',
            type: 'text',
            required: true,
            width: 'half',
          },
          { id: 'operatorId', label: 'Employee ID', type: 'text', width: 'half' },
          { id: 'operatorShift', label: 'Shift', type: 'text', width: 'third' },
        ],
        width: 'full',
      },
      {
        id: 'data-section',
        label: 'Measurement Data',
        type: 'section',
        width: 'full',
      },
      {
        id: 'measurementData',
        label: 'Measurement Data',
        type: 'table',
        required: true,
        helpText: 'Record all measurements: typically 3 operators x 10 parts x 3 trials.',
        columns: [
          { id: 'partId', label: 'Part #', type: 'number', required: true, width: 'third' },
          { id: 'operator', label: 'Operator', type: 'text', required: true, width: 'half' },
          { id: 'trial', label: 'Trial #', type: 'number', required: true, width: 'third' },
          {
            id: 'measurement',
            label: 'Measurement',
            type: 'number',
            required: true,
            width: 'half',
          },
        ],
        width: 'full',
      },
      {
        id: 'results-section',
        label: 'Results',
        type: 'section',
        width: 'full',
      },
      {
        id: 'repeatability',
        label: 'Repeatability (Equipment Variation) %',
        type: 'number',
        helpText: 'Variation due to the gauge itself.',
        validation: { min: 0, max: 100 },
        width: 'third',
      },
      {
        id: 'reproducibility',
        label: 'Reproducibility (Appraiser Variation) %',
        type: 'number',
        helpText: 'Variation due to different operators.',
        validation: { min: 0, max: 100 },
        width: 'third',
      },
      {
        id: 'grrPercent',
        label: '%GRR (Total Gauge R&R)',
        type: 'number',
        required: true,
        helpText: 'Total measurement system variation as a percentage of tolerance.',
        validation: { min: 0, max: 100 },
        width: 'third',
      },
      {
        id: 'ndc',
        label: 'Number of Distinct Categories (ndc)',
        type: 'number',
        helpText:
          'Number of distinct categories the measurement system can discriminate. Must be >= 5.',
        width: 'third',
      },
      {
        id: 'acceptability',
        label: 'Acceptability',
        type: 'select',
        required: true,
        helpText: 'Overall measurement system acceptability per AIAG guidelines.',
        options: [
          { label: 'Acceptable (< 10% GRR)', value: 'acceptable' },
          { label: 'Marginal (10-30% GRR)', value: 'marginal' },
          { label: 'Unacceptable (> 30% GRR)', value: 'unacceptable' },
        ],
        width: 'half',
      },
      {
        id: 'actions',
        label: 'Actions Required',
        type: 'textarea',
        placeholder: 'For marginal or unacceptable results, describe improvement actions...',
        helpText:
          'Corrective actions if the measurement system does not meet acceptability criteria.',
        width: 'full',
      },
    ],
  },

  // ─── TPL-AUTO-010  Layered Process Audit (LPA) ────────────────────────
  {
    code: 'TPL-AUTO-010',
    name: 'Layered Process Audit (LPA)',
    description:
      'Layered process audit form supporting multi-level verification of process compliance. Used by management, supervisors, and operators per CQI-8 LPA guideline and IATF 16949.',
    module: 'AUTOMOTIVE',
    category: 'AUDIT',
    tags: ['lpa', 'layered-audit', 'process-audit', 'iatf-16949', 'cqi-8'],
    isoClause: '9.2',
    fields: [
      {
        id: 'lpa-header',
        label: 'Audit Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'auditArea',
        label: 'Area / Work Station',
        type: 'text',
        required: true,
        placeholder: 'e.g. Assembly Line 3, CNC Cell B',
        helpText: 'Specific production area or work station being audited.',
        width: 'half',
      },
      {
        id: 'auditDate',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'auditor',
        label: 'Auditor Name',
        type: 'text',
        required: true,
        placeholder: 'Name of person conducting the audit',
        width: 'half',
      },
      {
        id: 'layer',
        label: 'Audit Layer',
        type: 'select',
        required: true,
        helpText: 'Organizational level performing the audit.',
        options: [
          { label: 'Layer 1 - Management / Director', value: 'management' },
          { label: 'Layer 2 - Supervisor / Team Leader', value: 'supervisor' },
          { label: 'Layer 3 - Operator / Technician', value: 'operator' },
        ],
        width: 'half',
      },
      {
        id: 'questions-section',
        label: 'Audit Questions',
        type: 'section',
        width: 'full',
      },
      {
        id: 'auditQuestions',
        label: 'LPA Questions',
        type: 'table',
        required: true,
        helpText: 'Evaluate each question by direct observation on the shop floor.',
        columns: [
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Quality', value: 'quality' },
              { label: 'Safety', value: 'safety' },
              { label: 'Workplace Organization (5S)', value: '5s' },
              { label: 'Standardized Work', value: 'standardized_work' },
              { label: 'Error Proofing', value: 'error_proofing' },
              { label: 'Material Handling', value: 'material_handling' },
              { label: 'Equipment / Tooling', value: 'equipment' },
            ],
            width: 'half',
          },
          { id: 'question', label: 'Question', type: 'text', required: true, width: 'full' },
          { id: 'conforming', label: 'Conforming?', type: 'checkbox', width: 'third' },
          { id: 'observation', label: 'Observation / Evidence', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'summary-section',
        label: 'Audit Summary',
        type: 'section',
        width: 'full',
      },
      {
        id: 'summaryScore',
        label: 'Conformance Score (%)',
        type: 'number',
        required: true,
        helpText: 'Percentage of conforming items out of total applicable questions.',
        validation: { min: 0, max: 100 },
        width: 'half',
      },
      {
        id: 'nonConformances',
        label: 'Non-Conformances',
        type: 'table',
        helpText: 'Detail each non-conformance found during the audit.',
        columns: [
          { id: 'ncRef', label: 'NC #', type: 'text', required: true, width: 'third' },
          { id: 'ncCategory', label: 'Category', type: 'text', required: true, width: 'half' },
          {
            id: 'ncDescription',
            label: 'Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          { id: 'ncContainment', label: 'Immediate Containment', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'followUpActions',
        label: 'Follow-Up Actions',
        type: 'textarea',
        placeholder: 'Required corrective actions, responsible persons, and due dates...',
        helpText: 'Actions to address non-conformances found during the LPA.',
        width: 'full',
      },
      {
        id: 'auditorSignature',
        label: 'Auditor Signature',
        type: 'signature',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-AUTO-011  IATF 16949 Management Review ──────────────────────
  {
    code: 'TPL-AUTO-011',
    name: 'IATF 16949 Management Review',
    description:
      'Management review meeting record with all required inputs and outputs per IATF 16949:2016 clause 9.3. Covers automotive-specific requirements including warranty, field returns, and customer scorecards.',
    module: 'AUTOMOTIVE',
    category: 'MANAGEMENT_REVIEW',
    tags: ['management-review', 'iatf-16949', 'quality', 'continual-improvement', 'automotive'],
    isoClause: '9.3',
    fields: [
      {
        id: 'review-header',
        label: 'Meeting Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'reviewDate',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'textarea',
        required: true,
        placeholder: 'List all attendees with their titles/roles...',
        helpText: 'Top management and key functional representatives.',
        width: 'full',
      },
      {
        id: 'input-quality-section',
        label: 'Input: Quality Performance',
        type: 'section',
        width: 'full',
      },
      {
        id: 'qualityPerformance',
        label: 'Quality Performance Metrics',
        type: 'textarea',
        required: true,
        placeholder:
          'PPM rates, scrap rates, first-pass yield, rework costs, internal reject trends...',
        helpText: 'Review of internal quality performance indicators and trends.',
        width: 'full',
      },
      {
        id: 'input-customer-section',
        label: 'Input: Customer Satisfaction',
        type: 'section',
        width: 'full',
      },
      {
        id: 'customerSatisfaction',
        label: 'Customer Satisfaction & Scorecards',
        type: 'textarea',
        required: true,
        placeholder:
          'Customer scorecards, rating trends, complaints, special status notifications...',
        helpText:
          'Review of customer satisfaction data including OEM scorecards and any special status.',
        width: 'full',
      },
      {
        id: 'input-warranty-section',
        label: 'Input: Warranty Performance',
        type: 'section',
        width: 'full',
      },
      {
        id: 'warrantyData',
        label: 'Warranty Claims & Analysis',
        type: 'textarea',
        required: true,
        placeholder: 'Warranty claim volumes, costs, Pareto analysis, 0-km vs field failures...',
        helpText:
          'Analysis of warranty claims including trends and costs. IATF 16949 specific requirement.',
        width: 'full',
      },
      {
        id: 'input-field-section',
        label: 'Input: Field Returns',
        type: 'section',
        width: 'full',
      },
      {
        id: 'fieldReturns',
        label: 'Field Return Analysis',
        type: 'textarea',
        required: true,
        placeholder: 'Field return rates, failure mode analysis, NTF (no trouble found) rates...',
        helpText: 'Analysis of field returns and customer-reported failures.',
        width: 'full',
      },
      {
        id: 'input-supplier-section',
        label: 'Input: Supplier Performance',
        type: 'section',
        width: 'full',
      },
      {
        id: 'supplierPerformance',
        label: 'Supplier Performance Review',
        type: 'textarea',
        required: true,
        placeholder: 'Supplier PPM, on-time delivery, quality issues, development status...',
        helpText: 'Review of key supplier performance metrics and any quality concerns.',
        width: 'full',
      },
      {
        id: 'input-audit-section',
        label: 'Input: Process Audit Results',
        type: 'section',
        width: 'full',
      },
      {
        id: 'processAuditResults',
        label: 'Process Audit Results',
        type: 'textarea',
        required: true,
        placeholder: 'Internal/external/customer audit results, NCRs, LPA trends...',
        helpText: 'Summary of all audit results including LPAs, product audits, and system audits.',
        width: 'full',
      },
      {
        id: 'output-section',
        label: 'Management Review Outputs',
        type: 'section',
        width: 'full',
      },
      {
        id: 'improvements',
        label: 'Improvement Actions',
        type: 'table',
        required: true,
        helpText: 'Decisions and actions for quality system improvement.',
        columns: [
          { id: 'actionNumber', label: '#', type: 'number', width: 'third' },
          { id: 'actionArea', label: 'Area', type: 'text', required: true, width: 'half' },
          {
            id: 'actionDescription',
            label: 'Action',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          { id: 'actionOwner', label: 'Owner', type: 'text', required: true, width: 'half' },
          { id: 'actionDeadline', label: 'Deadline', type: 'date', required: true, width: 'half' },
        ],
        width: 'full',
      },
      {
        id: 'resourceNeeds',
        label: 'Resource Needs',
        type: 'textarea',
        placeholder: 'Additional personnel, equipment, training, capital investment...',
        helpText: 'Resource requirements identified during the review.',
        width: 'full',
      },
      {
        id: 'objectivesUpdate',
        label: 'Quality Objectives Update',
        type: 'textarea',
        placeholder: 'Review current objectives, set new targets, update KPIs...',
        helpText: 'Updated quality objectives and targets for the next period.',
        width: 'full',
      },
      {
        id: 'nextReviewDate',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        helpText: 'Scheduled date for the next management review.',
        width: 'half',
      },
    ],
  },
];
