import type { TemplateDefinition } from '../types';

export const chemicalsTemplates: TemplateDefinition[] = [
  // ─── TPL-CHEM-001  COSHH Risk Assessment ──────────────────────────
  {
    code: 'TPL-CHEM-001',
    name: 'COSHH Risk Assessment',
    description:
      'Control of Substances Hazardous to Health assessment form aligned with COSHH Regulations 2002, UK EH40 WELs, and ISO 45001:2018 clause 6.1.2. Covers hazard identification, exposure evaluation, risk rating (5×5 matrix), hierarchy of controls, health surveillance requirements, and assessor sign-off.',
    module: 'CHEMICALS',
    category: 'RISK_ASSESSMENT',
    tags: ['COSHH', 'chemical', 'risk assessment', 'EH40', 'ISO 45001', 'hazardous substances'],
    isoClause: '6.1.2',
    fields: [
      // ── Section: Substance Details ──
      {
        id: 'section_substance',
        label: 'Substance Details',
        type: 'section',
        helpText: 'Identify the hazardous substance being assessed.',
      },
      {
        id: 'substance_name',
        label: 'Substance Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Sodium Hydroxide (NaOH)',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'cas_number',
        label: 'CAS Number',
        type: 'text',
        placeholder: 'e.g. 1310-73-2',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'supplier',
        label: 'Supplier',
        type: 'text',
        placeholder: 'e.g. Fisher Scientific',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'physical_state',
        label: 'Physical State',
        type: 'select',
        required: true,
        options: [
          { label: 'Solid', value: 'SOLID' },
          { label: 'Liquid', value: 'LIQUID' },
          { label: 'Gas', value: 'GAS' },
          { label: 'Aerosol', value: 'AEROSOL' },
          { label: 'Powder / Dust', value: 'POWDER' },
          { label: 'Paste / Gel', value: 'PASTE' },
        ],
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'is_cmr',
        label: 'CMR Substance (Carcinogen / Mutagen / Reprotoxin)',
        type: 'checkbox',
        helpText: 'Tick if substance is classified as Category 1A or 1B CMR under CLP.',
        section: 'section_substance',
      },
      {
        id: 'quantity_used',
        label: 'Typical Quantity Used per Task',
        type: 'text',
        placeholder: 'e.g. 500 ml, 2 kg',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'frequency_of_use',
        label: 'Frequency of Use',
        type: 'select',
        required: true,
        options: [
          { label: 'Daily', value: 'DAILY' },
          { label: 'Weekly', value: 'WEEKLY' },
          { label: 'Monthly', value: 'MONTHLY' },
          { label: 'Occasional / Ad-hoc', value: 'OCCASIONAL' },
        ],
        width: 'half',
        section: 'section_substance',
      },

      // ── Section: GHS / CLP Classification ──
      {
        id: 'section_ghs',
        label: 'GHS / CLP Classification',
        type: 'section',
        helpText: 'Record the GHS hazard classification from the Safety Data Sheet (Section 2).',
      },
      {
        id: 'signal_word',
        label: 'Signal Word',
        type: 'select',
        options: [
          { label: 'Danger', value: 'DANGER' },
          { label: 'Warning', value: 'WARNING' },
          { label: 'None', value: 'NONE' },
        ],
        width: 'half',
        section: 'section_ghs',
      },
      {
        id: 'pictograms',
        label: 'GHS Pictograms',
        type: 'multiselect',
        required: true,
        helpText: 'Select all GHS pictograms shown on the SDS / label.',
        options: [
          { label: 'GHS01 — Explosive', value: 'GHS01' },
          { label: 'GHS02 — Flammable', value: 'GHS02' },
          { label: 'GHS03 — Oxidising', value: 'GHS03' },
          { label: 'GHS04 — Gas Under Pressure', value: 'GHS04' },
          { label: 'GHS05 — Corrosive', value: 'GHS05' },
          { label: 'GHS06 — Toxic', value: 'GHS06' },
          { label: 'GHS07 — Irritant / Harmful', value: 'GHS07' },
          { label: 'GHS08 — Health Hazard', value: 'GHS08' },
          { label: 'GHS09 — Environmental', value: 'GHS09' },
        ],
        section: 'section_ghs',
      },
      {
        id: 'hazard_statements',
        label: 'H-Statements',
        type: 'textarea',
        placeholder: 'e.g. H314 — Causes severe skin burns and serious eye damage',
        helpText: 'List all hazard statements from SDS Section 2.',
        width: 'full',
        section: 'section_ghs',
      },
      {
        id: 'precautionary_statements',
        label: 'P-Statements',
        type: 'textarea',
        placeholder: 'e.g. P280 — Wear protective gloves / eye protection',
        helpText: 'List key precautionary statements from SDS Section 2.',
        width: 'full',
        section: 'section_ghs',
      },

      // ── Section: Exposure Assessment ──
      {
        id: 'section_exposure',
        label: 'Exposure Assessment',
        type: 'section',
        helpText: 'Evaluate potential routes and levels of exposure.',
      },
      {
        id: 'exposure_routes',
        label: 'Routes of Exposure',
        type: 'multiselect',
        required: true,
        options: [
          { label: 'Inhalation', value: 'INHALATION' },
          { label: 'Skin / Dermal Contact', value: 'DERMAL' },
          { label: 'Eye Contact', value: 'EYE' },
          { label: 'Ingestion', value: 'INGESTION' },
          { label: 'Injection / Needlestick', value: 'INJECTION' },
        ],
        section: 'section_exposure',
      },
      {
        id: 'wel_twa',
        label: 'WEL — 8hr TWA (mg/m³ or ppm)',
        type: 'text',
        placeholder: 'e.g. 2 mg/m³',
        helpText: 'UK EH40 Workplace Exposure Limit — 8hr time-weighted average.',
        width: 'half',
        section: 'section_exposure',
      },
      {
        id: 'wel_stel',
        label: 'WEL — 15min STEL (mg/m³ or ppm)',
        type: 'text',
        placeholder: 'e.g. 10 ppm',
        helpText: 'UK EH40 Workplace Exposure Limit — short-term exposure limit.',
        width: 'half',
        section: 'section_exposure',
      },
      {
        id: 'persons_at_risk',
        label: 'Persons at Risk',
        type: 'multiselect',
        required: true,
        options: [
          { label: 'Operators / Direct Users', value: 'operators' },
          { label: 'Maintenance Staff', value: 'maintenance' },
          { label: 'Cleaners', value: 'cleaners' },
          { label: 'Contractors', value: 'contractors' },
          { label: 'Visitors', value: 'visitors' },
          { label: 'Young Persons (< 18)', value: 'young_persons' },
          { label: 'New / Expectant Mothers', value: 'new_mothers' },
        ],
        section: 'section_exposure',
      },

      // ── Section: Risk Rating (Inherent) ──
      {
        id: 'section_risk_inherent',
        label: 'Inherent Risk Rating (Before Controls)',
        type: 'section',
        helpText: 'Rate the risk before any control measures are applied. Use the 5×5 matrix (1=Very Low, 5=Very High).',
      },
      {
        id: 'inherent_likelihood',
        label: 'Likelihood (1–5)',
        type: 'number',
        required: true,
        validation: { min: 1, max: 5 },
        helpText: '1=Rare, 2=Unlikely, 3=Possible, 4=Likely, 5=Almost Certain',
        width: 'half',
        section: 'section_risk_inherent',
      },
      {
        id: 'inherent_severity',
        label: 'Severity (1–5)',
        type: 'number',
        required: true,
        validation: { min: 1, max: 5 },
        helpText: '1=Negligible, 2=Minor, 3=Moderate, 4=Major, 5=Catastrophic',
        width: 'half',
        section: 'section_risk_inherent',
      },

      // ── Section: Control Measures ──
      {
        id: 'section_controls',
        label: 'Control Measures (Hierarchy of Controls)',
        type: 'section',
        helpText: 'Document controls in order of the hierarchy: Elimination → Substitution → Engineering → Administrative → PPE.',
      },
      {
        id: 'controls_table',
        label: 'Control Measures',
        type: 'table',
        required: true,
        helpText: 'Add one row per control measure. Follow the hierarchy of controls.',
        columns: [
          {
            id: 'control_level',
            label: 'Level',
            type: 'select',
            options: [
              { label: 'Elimination', value: 'ELIMINATION' },
              { label: 'Substitution', value: 'SUBSTITUTION' },
              { label: 'Engineering', value: 'ENGINEERING' },
              { label: 'Administrative', value: 'ADMINISTRATIVE' },
              { label: 'PPE', value: 'PPE' },
            ],
          },
          { id: 'control_description', label: 'Description', type: 'text', placeholder: 'e.g. Use fume cupboard for decanting' },
          {
            id: 'control_status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'In Place', value: 'IN_PLACE' },
              { label: 'Planned', value: 'PLANNED' },
              { label: 'Not Feasible', value: 'NOT_FEASIBLE' },
            ],
          },
        ],
        section: 'section_controls',
      },
      {
        id: 'ppe_required',
        label: 'PPE Required',
        type: 'multiselect',
        options: [
          { label: 'Chemical-resistant gloves (nitrile / butyl)', value: 'gloves' },
          { label: 'Safety goggles / face shield', value: 'eye_protection' },
          { label: 'Lab coat / chemical-resistant apron', value: 'body_protection' },
          { label: 'Respiratory protection (specify type)', value: 'rpe' },
          { label: 'Safety boots (chemical-resistant)', value: 'footwear' },
        ],
        section: 'section_controls',
      },
      {
        id: 'rpe_type',
        label: 'RPE Type (if required)',
        type: 'select',
        options: [
          { label: 'FFP2 Disposable Mask', value: 'FFP2' },
          { label: 'FFP3 Disposable Mask', value: 'FFP3' },
          { label: 'Half-Face Respirator + A2P3 Filters', value: 'HALF_FACE_A2P3' },
          { label: 'Full-Face Respirator', value: 'FULL_FACE' },
          { label: 'Powered Air-Purifying Respirator (PAPR)', value: 'PAPR' },
          { label: 'Self-Contained Breathing Apparatus (SCBA)', value: 'SCBA' },
          { label: 'Not Required', value: 'NONE' },
        ],
        width: 'half',
        section: 'section_controls',
      },

      // ── Section: Residual Risk Rating ──
      {
        id: 'section_risk_residual',
        label: 'Residual Risk Rating (After Controls)',
        type: 'section',
        helpText: 'Rate the risk after all control measures are in place.',
      },
      {
        id: 'residual_likelihood',
        label: 'Likelihood (1–5)',
        type: 'number',
        required: true,
        validation: { min: 1, max: 5 },
        width: 'half',
        section: 'section_risk_residual',
      },
      {
        id: 'residual_severity',
        label: 'Severity (1–5)',
        type: 'number',
        required: true,
        validation: { min: 1, max: 5 },
        width: 'half',
        section: 'section_risk_residual',
      },

      // ── Section: Health Surveillance ──
      {
        id: 'section_surveillance',
        label: 'Health Surveillance',
        type: 'section',
        helpText: 'Document any health surveillance requirements under COSHH Reg. 11.',
      },
      {
        id: 'health_surveillance_required',
        label: 'Health Surveillance Required?',
        type: 'checkbox',
        helpText: 'Required for CMR substances, isocyanates, solvents causing dermatitis, etc.',
        section: 'section_surveillance',
      },
      {
        id: 'surveillance_type',
        label: 'Type of Surveillance',
        type: 'text',
        placeholder: 'e.g. Lung function tests, biological monitoring, skin checks',
        width: 'full',
        section: 'section_surveillance',
      },
      {
        id: 'surveillance_frequency',
        label: 'Frequency',
        type: 'select',
        options: [
          { label: 'Annual', value: 'ANNUAL' },
          { label: '6-Monthly', value: '6_MONTHLY' },
          { label: 'Quarterly', value: 'QUARTERLY' },
          { label: 'Pre-employment only', value: 'PRE_EMPLOYMENT' },
          { label: 'Not Required', value: 'NONE' },
        ],
        width: 'half',
        section: 'section_surveillance',
      },

      // ── Section: Emergency Procedures ──
      {
        id: 'section_emergency',
        label: 'Emergency Procedures',
        type: 'section',
        helpText: 'Document first-aid, spill, and emergency response procedures.',
      },
      {
        id: 'first_aid_measures',
        label: 'First-Aid Measures',
        type: 'textarea',
        required: true,
        placeholder: 'Document first-aid procedures for each route of exposure...',
        helpText: 'Reference SDS Section 4.',
        width: 'full',
        section: 'section_emergency',
      },
      {
        id: 'spill_procedure',
        label: 'Spill / Release Procedure',
        type: 'textarea',
        required: true,
        placeholder: 'Document spill containment and clean-up procedures...',
        helpText: 'Reference SDS Section 6.',
        width: 'full',
        section: 'section_emergency',
      },

      // ── Section: Sign-Off ──
      {
        id: 'section_signoff',
        label: 'Assessment Sign-Off',
        type: 'section',
        helpText: 'Assessor and reviewer sign-off.',
      },
      {
        id: 'assessor_name',
        label: 'Assessor Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        helpText: 'Maximum 12 months for high-risk substances; 24 months otherwise.',
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'supervisor_name',
        label: 'Supervisor / Reviewer Name',
        type: 'text',
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'supervisor_signature',
        label: 'Supervisor Signature',
        type: 'signature',
        width: 'half',
        section: 'section_signoff',
      },
    ],
    defaultContent: {
      frequency_of_use: 'WEEKLY',
      surveillance_frequency: 'ANNUAL',
    },
  },

  // ─── TPL-CHEM-002  Chemical Register Entry ────────────────────────
  {
    code: 'TPL-CHEM-002',
    name: 'Chemical Register Entry',
    description:
      'Standard form for registering a new chemical substance in the organisation register. Captures identity (CAS, EC, REACH), classification, storage requirements, and regulatory status. Compliant with REACH, CLP Regulation, and ISO 45001.',
    module: 'CHEMICALS',
    category: 'COMPLIANCE',
    tags: ['chemical register', 'REACH', 'CLP', 'substance', 'inventory', 'ISO 45001'],
    isoClause: '8.1.2',
    fields: [
      {
        id: 'section_identity',
        label: 'Substance Identity',
        type: 'section',
        helpText: 'Record the chemical identity information.',
      },
      {
        id: 'chemical_name',
        label: 'Chemical / Product Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Isopropyl Alcohol (IPA)',
        width: 'full',
        section: 'section_identity',
      },
      {
        id: 'cas_number',
        label: 'CAS Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. 67-63-0',
        width: 'third',
        section: 'section_identity',
      },
      {
        id: 'ec_number',
        label: 'EC Number',
        type: 'text',
        placeholder: 'e.g. 200-661-7',
        width: 'third',
        section: 'section_identity',
      },
      {
        id: 'reach_registration',
        label: 'REACH Registration #',
        type: 'text',
        placeholder: 'e.g. 01-2119457558-25',
        width: 'third',
        section: 'section_identity',
      },
      {
        id: 'supplier',
        label: 'Supplier / Manufacturer',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_identity',
      },
      {
        id: 'physical_state',
        label: 'Physical State',
        type: 'select',
        required: true,
        options: [
          { label: 'Solid', value: 'SOLID' },
          { label: 'Liquid', value: 'LIQUID' },
          { label: 'Gas', value: 'GAS' },
          { label: 'Aerosol', value: 'AEROSOL' },
          { label: 'Powder / Dust', value: 'POWDER' },
          { label: 'Paste / Gel', value: 'PASTE' },
        ],
        width: 'half',
        section: 'section_identity',
      },
      // ── Classification ──
      {
        id: 'section_classification',
        label: 'GHS / CLP Classification',
        type: 'section',
      },
      {
        id: 'signal_word',
        label: 'Signal Word',
        type: 'select',
        options: [
          { label: 'Danger', value: 'DANGER' },
          { label: 'Warning', value: 'WARNING' },
          { label: 'None', value: 'NONE' },
        ],
        width: 'half',
        section: 'section_classification',
      },
      {
        id: 'pictograms',
        label: 'GHS Pictograms',
        type: 'multiselect',
        options: [
          { label: 'GHS01 — Explosive', value: 'GHS01' },
          { label: 'GHS02 — Flammable', value: 'GHS02' },
          { label: 'GHS03 — Oxidising', value: 'GHS03' },
          { label: 'GHS04 — Gas Under Pressure', value: 'GHS04' },
          { label: 'GHS05 — Corrosive', value: 'GHS05' },
          { label: 'GHS06 — Toxic', value: 'GHS06' },
          { label: 'GHS07 — Irritant / Harmful', value: 'GHS07' },
          { label: 'GHS08 — Health Hazard', value: 'GHS08' },
          { label: 'GHS09 — Environmental', value: 'GHS09' },
        ],
        section: 'section_classification',
      },
      {
        id: 'is_cmr',
        label: 'CMR Substance?',
        type: 'checkbox',
        helpText: 'Category 1A/1B Carcinogen, Mutagen, or Reprotoxin under CLP.',
        section: 'section_classification',
      },
      {
        id: 'h_statements',
        label: 'Hazard Statements',
        type: 'textarea',
        placeholder: 'e.g. H225 — Highly flammable liquid and vapour\nH319 — Causes serious eye irritation',
        width: 'full',
        section: 'section_classification',
      },
      // ── Storage ──
      {
        id: 'section_storage',
        label: 'Storage Requirements',
        type: 'section',
      },
      {
        id: 'storage_class',
        label: 'Storage Class',
        type: 'select',
        options: [
          { label: 'Flammables Cabinet', value: 'FLAMMABLES' },
          { label: 'Corrosives Cabinet', value: 'CORROSIVES' },
          { label: 'Oxidisers Cabinet', value: 'OXIDISERS' },
          { label: 'Toxic / CMR Cabinet', value: 'TOXIC' },
          { label: 'General Chemical Store', value: 'GENERAL' },
          { label: 'Refrigerated (2–8°C)', value: 'REFRIGERATED' },
          { label: 'Gas Cylinder Cage', value: 'GAS_CAGE' },
        ],
        width: 'half',
        section: 'section_storage',
      },
      {
        id: 'incompatible_with',
        label: 'Incompatible Substances',
        type: 'textarea',
        placeholder: 'e.g. Strong acids, oxidising agents',
        helpText: 'Reference SDS Section 10.5.',
        width: 'half',
        section: 'section_storage',
      },
      {
        id: 'max_quantity',
        label: 'Maximum Permitted On-Site Quantity',
        type: 'text',
        placeholder: 'e.g. 200 litres',
        width: 'half',
        section: 'section_storage',
      },
      {
        id: 'shelf_life',
        label: 'Shelf Life',
        type: 'text',
        placeholder: 'e.g. 24 months from manufacture',
        width: 'half',
        section: 'section_storage',
      },
      // ── Approval ──
      {
        id: 'section_approval',
        label: 'Approval',
        type: 'section',
      },
      {
        id: 'approved_by',
        label: 'Approved By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_approval',
      },
      {
        id: 'approval_date',
        label: 'Date Approved',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_approval',
      },
    ],
  },

  // ─── TPL-CHEM-003  Safety Data Sheet Review ───────────────────────
  {
    code: 'TPL-CHEM-003',
    name: 'Safety Data Sheet (SDS) Review',
    description:
      'Checklist and review form for verifying Safety Data Sheets against ISO 11014:2009 / REACH Annex II (16-section format). Ensures all mandatory sections are present, current, and accessible to workers.',
    module: 'CHEMICALS',
    category: 'COMPLIANCE',
    tags: ['SDS', 'MSDS', 'ISO 11014', 'REACH', 'safety data sheet', 'review'],
    isoClause: '7.5.1',
    fields: [
      {
        id: 'section_sds_info',
        label: 'SDS Information',
        type: 'section',
      },
      {
        id: 'substance_name',
        label: 'Substance / Product Name',
        type: 'text',
        required: true,
        width: 'full',
        section: 'section_sds_info',
      },
      {
        id: 'sds_revision_date',
        label: 'SDS Revision Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_sds_info',
      },
      {
        id: 'sds_version',
        label: 'SDS Version',
        type: 'text',
        placeholder: 'e.g. 4.2',
        width: 'half',
        section: 'section_sds_info',
      },
      {
        id: 'supplier',
        label: 'SDS Issued By (Supplier)',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_sds_info',
      },
      {
        id: 'sds_language',
        label: 'Language',
        type: 'select',
        options: [
          { label: 'English', value: 'EN' },
          { label: 'French', value: 'FR' },
          { label: 'German', value: 'DE' },
          { label: 'Spanish', value: 'ES' },
          { label: 'Other', value: 'OTHER' },
        ],
        width: 'half',
        section: 'section_sds_info',
      },
      // ── 16-Section Compliance Checklist ──
      {
        id: 'section_checklist',
        label: 'ISO 11014 / REACH Annex II — 16-Section Compliance Check',
        type: 'section',
        helpText: 'Verify each of the 16 mandatory SDS sections is present and adequate.',
      },
      {
        id: 'sds_checklist',
        label: 'Section Compliance',
        type: 'table',
        required: true,
        columns: [
          { id: 'sds_section', label: 'SDS Section', type: 'text' },
          {
            id: 'present',
            label: 'Present?',
            type: 'select',
            options: [
              { label: 'Yes', value: 'YES' },
              { label: 'No', value: 'NO' },
              { label: 'Partial', value: 'PARTIAL' },
            ],
          },
          { id: 'comments', label: 'Comments / Issues', type: 'text' },
        ],
        section: 'section_checklist',
      },
      // ── Review Outcome ──
      {
        id: 'section_outcome',
        label: 'Review Outcome',
        type: 'section',
      },
      {
        id: 'overall_status',
        label: 'SDS Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved — Current', value: 'APPROVED' },
          { label: 'Update Required', value: 'UPDATE_REQUIRED' },
          { label: 'Rejected — Non-Compliant', value: 'REJECTED' },
        ],
        width: 'half',
        section: 'section_outcome',
      },
      {
        id: 'next_review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        helpText: 'Maximum 5 years or when SDS is revised by supplier.',
        width: 'half',
        section: 'section_outcome',
      },
      {
        id: 'corrective_actions',
        label: 'Corrective Actions Required',
        type: 'textarea',
        placeholder: 'Document any actions needed to bring SDS into compliance...',
        width: 'full',
        section: 'section_outcome',
      },
      {
        id: 'reviewer_name',
        label: 'Reviewer',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_outcome',
      },
      {
        id: 'reviewer_signature',
        label: 'Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_outcome',
      },
    ],
    defaultContent: {
      sds_checklist: [
        { sds_section: '1. Identification', present: '', comments: '' },
        { sds_section: '2. Hazard(s) Identification', present: '', comments: '' },
        { sds_section: '3. Composition / Information on Ingredients', present: '', comments: '' },
        { sds_section: '4. First-Aid Measures', present: '', comments: '' },
        { sds_section: '5. Fire-Fighting Measures', present: '', comments: '' },
        { sds_section: '6. Accidental Release Measures', present: '', comments: '' },
        { sds_section: '7. Handling and Storage', present: '', comments: '' },
        { sds_section: '8. Exposure Controls / PPE', present: '', comments: '' },
        { sds_section: '9. Physical and Chemical Properties', present: '', comments: '' },
        { sds_section: '10. Stability and Reactivity', present: '', comments: '' },
        { sds_section: '11. Toxicological Information', present: '', comments: '' },
        { sds_section: '12. Ecological Information', present: '', comments: '' },
        { sds_section: '13. Disposal Considerations', present: '', comments: '' },
        { sds_section: '14. Transport Information', present: '', comments: '' },
        { sds_section: '15. Regulatory Information', present: '', comments: '' },
        { sds_section: '16. Other Information', present: '', comments: '' },
      ],
    },
  },

  // ─── TPL-CHEM-004  Chemical Spill Response Report ─────────────────
  {
    code: 'TPL-CHEM-004',
    name: 'Chemical Spill Response Report',
    description:
      'Incident report form for chemical spills and accidental releases. Covers immediate response actions, containment, clean-up, root cause analysis, and follow-up corrective actions. Aligned with ISO 14001 clause 8.2 and COSHH Regulations.',
    module: 'CHEMICALS',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['spill', 'chemical incident', 'emergency', 'ISO 14001', 'COSHH', 'environmental release'],
    isoClause: '8.2',
    fields: [
      {
        id: 'section_incident',
        label: 'Incident Details',
        type: 'section',
      },
      {
        id: 'incident_ref',
        label: 'Incident Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. CHEM-INC-2026-001',
        width: 'half',
        section: 'section_incident',
      },
      {
        id: 'incident_datetime',
        label: 'Date & Time of Spill',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'section_incident',
      },
      {
        id: 'substance_spilled',
        label: 'Substance(s) Spilled',
        type: 'text',
        required: true,
        placeholder: 'e.g. Hydrochloric Acid 37% (HCl)',
        width: 'full',
        section: 'section_incident',
      },
      {
        id: 'quantity_released',
        label: 'Estimated Quantity Released',
        type: 'text',
        required: true,
        placeholder: 'e.g. ~5 litres',
        width: 'half',
        section: 'section_incident',
      },
      {
        id: 'location',
        label: 'Location',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_incident',
      },
      {
        id: 'spill_type',
        label: 'Spill Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Contained — Indoor', value: 'CONTAINED_INDOOR' },
          { label: 'Contained — Bunded Area', value: 'CONTAINED_BUNDED' },
          { label: 'Uncontained — To Drain', value: 'UNCONTAINED_DRAIN' },
          { label: 'Uncontained — To Soil', value: 'UNCONTAINED_SOIL' },
          { label: 'Uncontained — To Water', value: 'UNCONTAINED_WATER' },
          { label: 'Atmospheric Release', value: 'ATMOSPHERIC' },
        ],
        width: 'half',
        section: 'section_incident',
      },
      {
        id: 'injuries',
        label: 'Injuries / Exposures',
        type: 'textarea',
        placeholder: 'Detail any injuries or exposures resulting from the spill...',
        width: 'full',
        section: 'section_incident',
      },
      // ── Response Actions ──
      {
        id: 'section_response',
        label: 'Response Actions',
        type: 'section',
        helpText: 'Document immediate and follow-up response actions taken.',
      },
      {
        id: 'response_actions',
        label: 'Actions Taken',
        type: 'table',
        required: true,
        columns: [
          { id: 'time', label: 'Time', type: 'text', placeholder: 'HH:MM' },
          { id: 'action', label: 'Action Taken', type: 'text', placeholder: 'e.g. Area evacuated, spill kit deployed' },
          { id: 'by', label: 'By Whom', type: 'text' },
        ],
        section: 'section_response',
      },
      {
        id: 'emergency_services_called',
        label: 'Emergency Services Called?',
        type: 'checkbox',
        section: 'section_response',
      },
      {
        id: 'environmental_agency_notified',
        label: 'Environment Agency Notified?',
        type: 'checkbox',
        helpText: 'Required if release reaches controlled waters or is above notification threshold.',
        section: 'section_response',
      },
      // ── Root Cause ──
      {
        id: 'section_root_cause',
        label: 'Root Cause Analysis',
        type: 'section',
      },
      {
        id: 'immediate_cause',
        label: 'Immediate Cause',
        type: 'textarea',
        required: true,
        placeholder: 'What directly caused the spill?',
        width: 'full',
        section: 'section_root_cause',
      },
      {
        id: 'root_cause',
        label: 'Root Cause(s)',
        type: 'textarea',
        required: true,
        placeholder: 'Why did the immediate cause occur? (Use 5-Whys or similar)',
        width: 'full',
        section: 'section_root_cause',
      },
      {
        id: 'corrective_actions',
        label: 'Corrective Actions',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text' },
          { id: 'responsible', label: 'Responsible', type: 'text' },
          { id: 'due_date', label: 'Due Date', type: 'date' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'OPEN' },
              { label: 'In Progress', value: 'IN_PROGRESS' },
              { label: 'Closed', value: 'CLOSED' },
            ],
          },
        ],
        section: 'section_root_cause',
      },
      // ── Sign-Off ──
      {
        id: 'section_signoff',
        label: 'Sign-Off',
        type: 'section',
      },
      {
        id: 'investigator',
        label: 'Investigator',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'investigator_signature',
        label: 'Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'investigation_date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
    ],
  },

  // ─── TPL-CHEM-005  Workplace Exposure Monitoring Record ───────────
  {
    code: 'TPL-CHEM-005',
    name: 'Workplace Exposure Monitoring Record',
    description:
      'Form for recording airborne workplace exposure monitoring results against UK EH40 Workplace Exposure Limits (WELs). Covers TWA and STEL measurements, sampling methodology, and compliance determination.',
    module: 'CHEMICALS',
    category: 'INSPECTION',
    tags: ['WEL', 'EH40', 'exposure monitoring', 'TWA', 'STEL', 'air sampling', 'occupational hygiene'],
    isoClause: '8.1',
    fields: [
      {
        id: 'section_monitoring',
        label: 'Monitoring Details',
        type: 'section',
      },
      {
        id: 'substance_monitored',
        label: 'Substance Monitored',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_monitoring',
      },
      {
        id: 'cas_number',
        label: 'CAS Number',
        type: 'text',
        width: 'half',
        section: 'section_monitoring',
      },
      {
        id: 'monitoring_date',
        label: 'Monitoring Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_monitoring',
      },
      {
        id: 'monitoring_type',
        label: 'Monitoring Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Personal (worker-worn sampler)', value: 'PERSONAL' },
          { label: 'Static / Area (fixed position)', value: 'STATIC' },
          { label: 'Biological Monitoring', value: 'BIOLOGICAL' },
        ],
        width: 'half',
        section: 'section_monitoring',
      },
      {
        id: 'location',
        label: 'Location / Work Area',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_monitoring',
      },
      {
        id: 'worker_sampled',
        label: 'Worker Name (if personal monitoring)',
        type: 'text',
        width: 'half',
        section: 'section_monitoring',
      },
      // ── Sampling Method ──
      {
        id: 'section_method',
        label: 'Sampling Methodology',
        type: 'section',
      },
      {
        id: 'sampling_method',
        label: 'Method Reference',
        type: 'text',
        placeholder: 'e.g. MDHS 14/4 (General methods for gravimetric sampling)',
        width: 'full',
        section: 'section_method',
      },
      {
        id: 'sampling_equipment',
        label: 'Equipment Used',
        type: 'text',
        placeholder: 'e.g. SKC pump + 25mm MCE filter cassette',
        width: 'half',
        section: 'section_method',
      },
      {
        id: 'flow_rate',
        label: 'Flow Rate (L/min)',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'section_method',
      },
      {
        id: 'sampling_duration',
        label: 'Sampling Duration (minutes)',
        type: 'number',
        required: true,
        validation: { min: 1, max: 480 },
        width: 'half',
        section: 'section_method',
      },
      {
        id: 'analytical_lab',
        label: 'Analytical Laboratory',
        type: 'text',
        placeholder: 'e.g. HSE Science Division, UKAS accredited',
        width: 'half',
        section: 'section_method',
      },
      // ── Results ──
      {
        id: 'section_results',
        label: 'Results',
        type: 'section',
      },
      {
        id: 'twa_result',
        label: '8hr TWA Result (mg/m³)',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'third',
        section: 'section_results',
      },
      {
        id: 'twa_wel',
        label: 'WEL TWA Limit (mg/m³)',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'third',
        section: 'section_results',
      },
      {
        id: 'twa_percentage',
        label: 'TWA as % of WEL',
        type: 'number',
        helpText: 'Auto-calculated: (Result / WEL) × 100',
        width: 'third',
        section: 'section_results',
      },
      {
        id: 'stel_result',
        label: '15min STEL Result (mg/m³)',
        type: 'number',
        validation: { min: 0 },
        width: 'third',
        section: 'section_results',
      },
      {
        id: 'stel_wel',
        label: 'WEL STEL Limit (mg/m³)',
        type: 'number',
        validation: { min: 0 },
        width: 'third',
        section: 'section_results',
      },
      {
        id: 'stel_percentage',
        label: 'STEL as % of WEL',
        type: 'number',
        width: 'third',
        section: 'section_results',
      },
      {
        id: 'compliance_status',
        label: 'Compliance Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Below WEL — Compliant', value: 'BELOW_WEL' },
          { label: 'At WEL (≥90%) — Action Required', value: 'AT_WEL' },
          { label: 'Above WEL — Non-Compliant', value: 'ABOVE_WEL' },
        ],
        width: 'half',
        section: 'section_results',
      },
      {
        id: 'actions_required',
        label: 'Actions Required',
        type: 'textarea',
        placeholder: 'Document any actions arising from the monitoring results...',
        width: 'full',
        section: 'section_results',
      },
      // ── Sign-Off ──
      {
        id: 'section_signoff',
        label: 'Sign-Off',
        type: 'section',
      },
      {
        id: 'hygienist_name',
        label: 'Occupational Hygienist',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'hygienist_signature',
        label: 'Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'next_monitoring_date',
        label: 'Next Monitoring Due',
        type: 'date',
        width: 'half',
        section: 'section_signoff',
      },
    ],
  },

  // ─── TPL-CHEM-006  Chemical Storage Inspection Checklist ──────────
  {
    code: 'TPL-CHEM-006',
    name: 'Chemical Storage Inspection Checklist',
    description:
      'Periodic inspection checklist for chemical storage areas, cabinets, and bunded areas. Covers segregation, ventilation, labelling, spill kits, and compliance with DSEAR / ATEX / COSHH storage requirements.',
    module: 'CHEMICALS',
    category: 'INSPECTION',
    tags: ['storage', 'inspection', 'segregation', 'DSEAR', 'labelling', 'chemical store'],
    isoClause: '8.1',
    fields: [
      {
        id: 'section_info',
        label: 'Inspection Details',
        type: 'section',
      },
      {
        id: 'storage_area',
        label: 'Storage Area / Location',
        type: 'text',
        required: true,
        placeholder: 'e.g. Building C — Flammables Store',
        width: 'half',
        section: 'section_info',
      },
      {
        id: 'inspection_date',
        label: 'Inspection Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_info',
      },
      {
        id: 'inspector',
        label: 'Inspector Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_info',
      },
      // ── Checklist ──
      {
        id: 'section_checklist',
        label: 'Inspection Checklist',
        type: 'section',
        helpText: 'Check each item and record findings.',
      },
      {
        id: 'checklist',
        label: 'Inspection Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'item', label: 'Check Item', type: 'text' },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            options: [
              { label: 'Pass', value: 'PASS' },
              { label: 'Fail', value: 'FAIL' },
              { label: 'N/A', value: 'NA' },
            ],
          },
          { id: 'comments', label: 'Comments', type: 'text' },
        ],
        section: 'section_checklist',
      },
      // ── Non-Conformances ──
      {
        id: 'section_ncr',
        label: 'Non-Conformances & Actions',
        type: 'section',
      },
      {
        id: 'non_conformances',
        label: 'Non-Conformances Raised',
        type: 'table',
        columns: [
          { id: 'ncr_ref', label: 'NCR Ref', type: 'text' },
          { id: 'description', label: 'Description', type: 'text' },
          { id: 'priority', label: 'Priority', type: 'select', options: [{ label: 'High', value: 'HIGH' }, { label: 'Medium', value: 'MEDIUM' }, { label: 'Low', value: 'LOW' }] },
          { id: 'assigned_to', label: 'Assigned To', type: 'text' },
          { id: 'due_date', label: 'Due Date', type: 'date' },
        ],
        section: 'section_ncr',
      },
      {
        id: 'overall_rating',
        label: 'Overall Storage Condition Rating',
        type: 'rating',
        required: true,
        helpText: '1=Poor, 5=Excellent',
        section: 'section_ncr',
      },
      {
        id: 'inspector_signature',
        label: 'Inspector Signature',
        type: 'signature',
        required: true,
        section: 'section_ncr',
      },
    ],
    defaultContent: {
      checklist: [
        { item: 'All containers properly labelled (GHS/CLP)', result: '', comments: '' },
        { item: 'Incompatible chemicals segregated correctly', result: '', comments: '' },
        { item: 'Flammables stored in approved cabinet/area', result: '', comments: '' },
        { item: 'Bunding intact and free of liquid', result: '', comments: '' },
        { item: 'Ventilation adequate (LEV / natural)', result: '', comments: '' },
        { item: 'Spill kits present and fully stocked', result: '', comments: '' },
        { item: 'Emergency shower / eyewash functional', result: '', comments: '' },
        { item: 'COSHH assessments displayed / accessible', result: '', comments: '' },
        { item: 'No expired chemicals on shelves', result: '', comments: '' },
        { item: 'Access restricted to authorised personnel', result: '', comments: '' },
        { item: 'Fire extinguisher(s) in date and accessible', result: '', comments: '' },
        { item: 'Temperature within specified range', result: '', comments: '' },
        { item: 'Gas cylinders chained/strapped upright', result: '', comments: '' },
        { item: 'Waste containers correctly labelled', result: '', comments: '' },
        { item: 'Housekeeping — area clean and tidy', result: '', comments: '' },
      ],
    },
  },

  // ─── TPL-CHEM-007  Chemical Waste Disposal Record ─────────────────
  {
    code: 'TPL-CHEM-007',
    name: 'Chemical Waste Disposal Record',
    description:
      'Record form for tracking chemical waste from generation through to final disposal. Covers waste classification, duty of care, consignment notes, and compliance with Hazardous Waste Regulations and ISO 14001 clause 8.1.',
    module: 'CHEMICALS',
    category: 'COMPLIANCE',
    tags: ['waste', 'disposal', 'hazardous waste', 'duty of care', 'ISO 14001', 'consignment'],
    isoClause: '8.1',
    fields: [
      {
        id: 'section_waste',
        label: 'Waste Details',
        type: 'section',
      },
      {
        id: 'waste_ref',
        label: 'Waste Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. CHEM-WAS-2026-001',
        width: 'half',
        section: 'section_waste',
      },
      {
        id: 'substance_name',
        label: 'Chemical / Waste Description',
        type: 'text',
        required: true,
        width: 'full',
        section: 'section_waste',
      },
      {
        id: 'ewc_code',
        label: 'EWC Code',
        type: 'text',
        required: true,
        placeholder: 'e.g. 07 01 04* (other organic solvents)',
        helpText: 'European Waste Catalogue code. Asterisk (*) denotes hazardous waste.',
        width: 'half',
        section: 'section_waste',
      },
      {
        id: 'waste_class',
        label: 'Waste Classification',
        type: 'select',
        required: true,
        options: [
          { label: 'Hazardous', value: 'HAZARDOUS' },
          { label: 'Non-Hazardous', value: 'NON_HAZARDOUS' },
          { label: 'Inert', value: 'INERT' },
        ],
        width: 'half',
        section: 'section_waste',
      },
      {
        id: 'quantity',
        label: 'Quantity',
        type: 'text',
        required: true,
        placeholder: 'e.g. 25 litres, 10 kg',
        width: 'half',
        section: 'section_waste',
      },
      {
        id: 'container_type',
        label: 'Container Type',
        type: 'select',
        options: [
          { label: 'UN-approved drum (205L)', value: 'DRUM_205L' },
          { label: 'UN-approved drum (25L)', value: 'DRUM_25L' },
          { label: 'IBC (1000L)', value: 'IBC' },
          { label: 'Winchester / Glass Bottle', value: 'GLASS' },
          { label: 'Plastic Jerry Can', value: 'JERRY_CAN' },
          { label: 'Bag / Sack', value: 'BAG' },
        ],
        width: 'half',
        section: 'section_waste',
      },
      // ── Duty of Care ──
      {
        id: 'section_duty',
        label: 'Duty of Care Chain',
        type: 'section',
        helpText: 'Record the waste duty of care information.',
      },
      {
        id: 'waste_carrier',
        label: 'Waste Carrier',
        type: 'text',
        required: true,
        placeholder: 'e.g. Veolia Environmental Services',
        width: 'half',
        section: 'section_duty',
      },
      {
        id: 'carrier_licence',
        label: 'Carrier Licence Number',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_duty',
      },
      {
        id: 'destination_facility',
        label: 'Destination Facility',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_duty',
      },
      {
        id: 'disposal_method',
        label: 'Disposal / Recovery Method',
        type: 'select',
        required: true,
        options: [
          { label: 'D10 — Incineration on land', value: 'D10' },
          { label: 'D9 — Physico-chemical treatment', value: 'D9' },
          { label: 'D1 — Landfill', value: 'D1' },
          { label: 'R1 — Energy recovery', value: 'R1' },
          { label: 'R2 — Solvent reclamation', value: 'R2' },
          { label: 'R4 — Recycling of metals', value: 'R4' },
          { label: 'R13 — Storage for recovery', value: 'R13' },
        ],
        width: 'half',
        section: 'section_duty',
      },
      {
        id: 'consignment_note',
        label: 'Consignment Note Number',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_duty',
      },
      {
        id: 'collection_date',
        label: 'Collection Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_duty',
      },
      // ── Sign-Off ──
      {
        id: 'section_signoff',
        label: 'Sign-Off',
        type: 'section',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'prepared_signature',
        label: 'Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
    ],
  },

  // ─── TPL-CHEM-008  Chemical Handling Training Record ──────────────
  {
    code: 'TPL-CHEM-008',
    name: 'Chemical Handling Training Record',
    description:
      'Training record form for chemical handling, COSHH awareness, and emergency response competency. Documents training content, practical assessment, and competency sign-off as required by COSHH Reg. 12 and ISO 45001 clause 7.2.',
    module: 'CHEMICALS',
    category: 'TRAINING',
    tags: ['training', 'COSHH', 'competency', 'chemical handling', 'ISO 45001', 'awareness'],
    isoClause: '7.2',
    fields: [
      {
        id: 'section_training',
        label: 'Training Details',
        type: 'section',
      },
      {
        id: 'training_title',
        label: 'Training Title',
        type: 'text',
        required: true,
        placeholder: 'e.g. COSHH Awareness & Chemical Handling',
        width: 'full',
        section: 'section_training',
      },
      {
        id: 'training_date',
        label: 'Training Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_training',
      },
      {
        id: 'trainer',
        label: 'Trainer / Instructor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_training',
      },
      {
        id: 'training_type',
        label: 'Training Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Initial / Induction', value: 'INITIAL' },
          { label: 'Refresher', value: 'REFRESHER' },
          { label: 'Substance-Specific', value: 'SUBSTANCE_SPECIFIC' },
          { label: 'Emergency Response', value: 'EMERGENCY' },
          { label: 'Toolbox Talk', value: 'TOOLBOX' },
        ],
        width: 'half',
        section: 'section_training',
      },
      {
        id: 'delivery_method',
        label: 'Delivery Method',
        type: 'select',
        options: [
          { label: 'Classroom', value: 'CLASSROOM' },
          { label: 'Practical / Hands-on', value: 'PRACTICAL' },
          { label: 'E-learning', value: 'ELEARNING' },
          { label: 'On-the-Job', value: 'ON_THE_JOB' },
          { label: 'Blended', value: 'BLENDED' },
        ],
        width: 'half',
        section: 'section_training',
      },
      // ── Content Covered ──
      {
        id: 'section_content',
        label: 'Training Content',
        type: 'section',
      },
      {
        id: 'topics_covered',
        label: 'Topics Covered',
        type: 'multiselect',
        required: true,
        options: [
          { label: 'COSHH Regulations overview', value: 'coshh_overview' },
          { label: 'Reading Safety Data Sheets', value: 'sds_reading' },
          { label: 'GHS pictogram identification', value: 'ghs_pictograms' },
          { label: 'PPE selection and use', value: 'ppe' },
          { label: 'Chemical storage and segregation', value: 'storage' },
          { label: 'Spill response procedures', value: 'spill_response' },
          { label: 'First aid for chemical exposure', value: 'first_aid' },
          { label: 'Waste disposal procedures', value: 'waste_disposal' },
          { label: 'WEL monitoring and health surveillance', value: 'wel_monitoring' },
          { label: 'Substance-specific handling procedures', value: 'substance_specific' },
        ],
        section: 'section_content',
      },
      {
        id: 'substances_covered',
        label: 'Specific Substances Covered',
        type: 'textarea',
        placeholder: 'List any specific chemicals covered in this training session...',
        width: 'full',
        section: 'section_content',
      },
      // ── Attendees ──
      {
        id: 'section_attendees',
        label: 'Attendees & Assessment',
        type: 'section',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'table',
        required: true,
        columns: [
          { id: 'name', label: 'Name', type: 'text' },
          { id: 'department', label: 'Department', type: 'text' },
          { id: 'assessment_score', label: 'Assessment Score (%)', type: 'number' },
          {
            id: 'competent',
            label: 'Competent?',
            type: 'select',
            options: [
              { label: 'Yes', value: 'YES' },
              { label: 'No — Retrain', value: 'NO' },
            ],
          },
          { id: 'signature', label: 'Signature', type: 'text' },
        ],
        section: 'section_attendees',
      },
      {
        id: 'pass_mark',
        label: 'Pass Mark (%)',
        type: 'number',
        validation: { min: 0, max: 100 },
        defaultValue: 80,
        width: 'half',
        section: 'section_attendees',
      },
      {
        id: 'refresher_due',
        label: 'Refresher Due Date',
        type: 'date',
        required: true,
        helpText: 'Typically 12 months for COSHH awareness, 6 months for high-risk substances.',
        width: 'half',
        section: 'section_attendees',
      },
      // ── Trainer Sign-Off ──
      {
        id: 'section_signoff',
        label: 'Trainer Sign-Off',
        type: 'section',
      },
      {
        id: 'trainer_signature',
        label: 'Trainer Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'trainer_qualifications',
        label: 'Trainer Qualifications',
        type: 'text',
        placeholder: 'e.g. NEBOSH NGC, IOSH Managing Safely',
        width: 'half',
        section: 'section_signoff',
      },
    ],
    defaultContent: {
      pass_mark: 80,
    },
  },
];
