import type { TemplateDefinition } from '../types';

export const cmmsTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-MNT-001',
    name: 'Preventive Maintenance Checklist',
    description:
      'Standardised checklist for preventive maintenance tasks on equipment and assets. Covers inspection points, measurements, and sign-off.',
    module: 'CMMS',
    category: 'INSPECTION',
    tags: ['preventive-maintenance', 'pm-checklist', 'equipment', 'inspection'],
    fields: [
      { id: 'section_header', label: 'Maintenance Details', type: 'section' },
      { id: 'equipment_name', label: 'Equipment Name', type: 'text', required: true, width: 'half', section: 'Maintenance Details' },
      { id: 'asset_id', label: 'Asset ID', type: 'text', required: true, placeholder: 'e.g. AST-001', width: 'half', section: 'Maintenance Details' },
      { id: 'technician', label: 'Technician', type: 'text', required: true, width: 'half', section: 'Maintenance Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Maintenance Details' },
      { id: 'section_checks', label: 'Inspection Checks', type: 'section' },
      {
        id: 'checks',
        label: 'Checklist Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'item', label: 'Check Item', type: 'text', required: true, placeholder: 'e.g. Oil level within range' },
          { id: 'result', label: 'Result', type: 'select', required: true, options: [{ label: 'Pass', value: 'pass' }, { label: 'Fail', value: 'fail' }, { label: 'N/A', value: 'na' }] },
          { id: 'measurement', label: 'Measurement', type: 'text', placeholder: 'Value if applicable' },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Inspection Checks',
      },
      { id: 'overall_condition', label: 'Overall Equipment Condition', type: 'select', required: true, options: [{ label: 'Good', value: 'good' }, { label: 'Fair', value: 'fair' }, { label: 'Poor', value: 'poor' }, { label: 'Critical', value: 'critical' }], width: 'half', section: 'Inspection Checks' },
      { id: 'follow_up', label: 'Follow-Up Required', type: 'textarea', placeholder: 'Describe any corrective actions or follow-up work needed...', validation: { maxLength: 2000 }, width: 'full', section: 'Inspection Checks' },
      { id: 'technician_signature', label: 'Technician Signature', type: 'signature', required: true, section: 'Inspection Checks' },
    ],
  },
  {
    code: 'TPL-MNT-002',
    name: 'Work Order Report',
    description:
      'Completed work order report documenting maintenance work performed, parts used, time spent, and equipment status after repair.',
    module: 'CMMS',
    category: 'REPORTING',
    tags: ['work-order', 'repair', 'maintenance-report', 'corrective'],
    fields: [
      { id: 'section_header', label: 'Work Order Details', type: 'section' },
      { id: 'work_order_id', label: 'Work Order ID', type: 'text', required: true, width: 'half', section: 'Work Order Details' },
      { id: 'equipment_name', label: 'Equipment Name', type: 'text', required: true, width: 'half', section: 'Work Order Details' },
      { id: 'reported_date', label: 'Date Reported', type: 'date', required: true, width: 'half', section: 'Work Order Details' },
      { id: 'completed_date', label: 'Date Completed', type: 'date', required: true, width: 'half', section: 'Work Order Details' },
      { id: 'technician', label: 'Technician', type: 'text', required: true, width: 'half', section: 'Work Order Details' },
      { id: 'priority', label: 'Priority', type: 'select', required: true, options: [{ label: 'Emergency', value: 'emergency' }, { label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }], width: 'half', section: 'Work Order Details' },
      { id: 'problem_description', label: 'Problem Description', type: 'textarea', required: true, validation: { minLength: 10, maxLength: 3000 }, width: 'full', section: 'Work Order Details' },
      { id: 'section_work', label: 'Work Performed', type: 'section' },
      { id: 'work_performed', label: 'Work Performed', type: 'textarea', required: true, validation: { minLength: 10, maxLength: 3000 }, width: 'full', section: 'Work Performed' },
      {
        id: 'parts_used',
        label: 'Parts Used',
        type: 'table',
        columns: [
          { id: 'part', label: 'Part Name', type: 'text', required: true },
          { id: 'part_number', label: 'Part Number', type: 'text' },
          { id: 'quantity', label: 'Quantity', type: 'number', required: true, validation: { min: 1 } },
          { id: 'cost', label: 'Cost', type: 'number', validation: { min: 0 } },
        ],
        section: 'Work Performed',
      },
      { id: 'hours_spent', label: 'Hours Spent', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Work Performed' },
      { id: 'equipment_status', label: 'Equipment Status After Repair', type: 'select', required: true, options: [{ label: 'Operational', value: 'operational' }, { label: 'Operational with Limitations', value: 'limited' }, { label: 'Out of Service', value: 'out_of_service' }], width: 'half', section: 'Work Performed' },
      { id: 'technician_signature', label: 'Technician Signature', type: 'signature', required: true, section: 'Work Performed' },
    ],
  },
  {
    code: 'TPL-MNT-003',
    name: 'Equipment Failure Analysis',
    description:
      'Root cause analysis report for equipment failures. Documents failure mode, contributing factors, corrective actions, and preventive measures.',
    module: 'CMMS',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['failure-analysis', 'root-cause', 'rca', 'equipment-failure'],
    fields: [
      { id: 'section_header', label: 'Failure Details', type: 'section' },
      { id: 'equipment_name', label: 'Equipment Name', type: 'text', required: true, width: 'half', section: 'Failure Details' },
      { id: 'failure_date', label: 'Failure Date', type: 'datetime', required: true, width: 'half', section: 'Failure Details' },
      { id: 'analyst', label: 'Analyst', type: 'text', required: true, width: 'half', section: 'Failure Details' },
      { id: 'failure_mode', label: 'Failure Mode', type: 'textarea', required: true, placeholder: 'How did the equipment fail?', validation: { minLength: 10, maxLength: 2000 }, width: 'full', section: 'Failure Details' },
      { id: 'section_analysis', label: 'Root Cause Analysis', type: 'section' },
      {
        id: 'contributing_factors',
        label: 'Contributing Factors',
        type: 'table',
        required: true,
        columns: [
          { id: 'factor', label: 'Factor', type: 'text', required: true },
          { id: 'category', label: 'Category', type: 'select', required: true, options: [{ label: 'Mechanical', value: 'mechanical' }, { label: 'Electrical', value: 'electrical' }, { label: 'Human Error', value: 'human' }, { label: 'Environmental', value: 'environmental' }, { label: 'Material', value: 'material' }, { label: 'Process', value: 'process' }] },
          { id: 'evidence', label: 'Evidence', type: 'text', placeholder: 'Supporting evidence' },
        ],
        section: 'Root Cause Analysis',
      },
      { id: 'root_cause', label: 'Root Cause', type: 'textarea', required: true, validation: { minLength: 10, maxLength: 2000 }, width: 'full', section: 'Root Cause Analysis' },
      { id: 'section_actions', label: 'Corrective & Preventive Actions', type: 'section' },
      {
        id: 'actions',
        label: 'Actions',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          { id: 'type', label: 'Type', type: 'select', required: true, options: [{ label: 'Corrective', value: 'corrective' }, { label: 'Preventive', value: 'preventive' }] },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Open', value: 'open' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }] },
        ],
        section: 'Corrective & Preventive Actions',
      },
    ],
  },
];
