// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.
import type { TemplateDefinition } from '../types';

export const cmmsTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-MNT-001',
    name: 'Preventive Maintenance Checklist',
    description:
      'Standardised checklist for preventive maintenance tasks on equipment and assets. Covers inspection points, measurements, and sign-off.',
    module: 'CMMS',
    category: 'INSPECTION',
    tags: ['preventive-maintenance', 'pm-checklist', 'equipment', 'inspection'],
    fields: [
      { id: 'section_header', label: 'Maintenance Details', type: 'section' },
      {
        id: 'equipment_name',
        label: 'Equipment Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Maintenance Details',
      },
      {
        id: 'asset_id',
        label: 'Asset ID',
        type: 'text',
        required: true,
        placeholder: 'e.g. AST-001',
        width: 'half',
        section: 'Maintenance Details',
      },
      {
        id: 'technician',
        label: 'Technician',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Maintenance Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Maintenance Details',
      },
      { id: 'section_checks', label: 'Inspection Checks', type: 'section' },
      {
        id: 'checks',
        label: 'Checklist Items',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'item',
            label: 'Check Item',
            type: 'text',
            required: true,
            placeholder: 'e.g. Oil level within range',
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
              { label: 'N/A', value: 'na' },
            ],
          },
          {
            id: 'measurement',
            label: 'Measurement',
            type: 'text',
            placeholder: 'Value if applicable',
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Inspection Checks',
      },
      {
        id: 'overall_condition',
        label: 'Overall Equipment Condition',
        type: 'select',
        required: true,
        options: [
          { label: 'Good', value: 'good' },
          { label: 'Fair', value: 'fair' },
          { label: 'Poor', value: 'poor' },
          { label: 'Critical', value: 'critical' },
        ],
        width: 'half',
        section: 'Inspection Checks',
      },
      {
        id: 'follow_up',
        label: 'Follow-Up Required',
        type: 'textarea',
        placeholder: 'Describe any corrective actions or follow-up work needed...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Inspection Checks',
      },
      {
        id: 'technician_signature',
        label: 'Technician Signature',
        type: 'signature',
        required: true,
        section: 'Inspection Checks',
      },
    ],
  },
  {
    code: 'TPL-MNT-002',
    name: 'Work Order Report',
    description:
      'Completed work order report documenting maintenance work performed, parts used, time spent, and equipment status after repair.',
    module: 'CMMS',
    category: 'REPORTING',
    tags: ['work-order', 'repair', 'maintenance-report', 'corrective'],
    fields: [
      { id: 'section_header', label: 'Work Order Details', type: 'section' },
      {
        id: 'work_order_id',
        label: 'Work Order ID',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Work Order Details',
      },
      {
        id: 'equipment_name',
        label: 'Equipment Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Work Order Details',
      },
      {
        id: 'reported_date',
        label: 'Date Reported',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Work Order Details',
      },
      {
        id: 'completed_date',
        label: 'Date Completed',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Work Order Details',
      },
      {
        id: 'technician',
        label: 'Technician',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Work Order Details',
      },
      {
        id: 'priority',
        label: 'Priority',
        type: 'select',
        required: true,
        options: [
          { label: 'Emergency', value: 'emergency' },
          { label: 'High', value: 'high' },
          { label: 'Medium', value: 'medium' },
          { label: 'Low', value: 'low' },
        ],
        width: 'half',
        section: 'Work Order Details',
      },
      {
        id: 'problem_description',
        label: 'Problem Description',
        type: 'textarea',
        required: true,
        validation: { minLength: 10, maxLength: 3000 },
        width: 'full',
        section: 'Work Order Details',
      },
      { id: 'section_work', label: 'Work Performed', type: 'section' },
      {
        id: 'work_performed',
        label: 'Work Performed',
        type: 'textarea',
        required: true,
        validation: { minLength: 10, maxLength: 3000 },
        width: 'full',
        section: 'Work Performed',
      },
      {
        id: 'parts_used',
        label: 'Parts Used',
        type: 'table',
        columns: [
          { id: 'part', label: 'Part Name', type: 'text', required: true },
          { id: 'part_number', label: 'Part Number', type: 'text' },
          {
            id: 'quantity',
            label: 'Quantity',
            type: 'number',
            required: true,
            validation: { min: 1 },
          },
          { id: 'cost', label: 'Cost', type: 'number', validation: { min: 0 } },
        ],
        section: 'Work Performed',
      },
      {
        id: 'hours_spent',
        label: 'Hours Spent',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Work Performed',
      },
      {
        id: 'equipment_status',
        label: 'Equipment Status After Repair',
        type: 'select',
        required: true,
        options: [
          { label: 'Operational', value: 'operational' },
          { label: 'Operational with Limitations', value: 'limited' },
          { label: 'Out of Service', value: 'out_of_service' },
        ],
        width: 'half',
        section: 'Work Performed',
      },
      {
        id: 'technician_signature',
        label: 'Technician Signature',
        type: 'signature',
        required: true,
        section: 'Work Performed',
      },
    ],
  },
  {
    code: 'TPL-MNT-003',
    name: 'Equipment Failure Analysis',
    description:
      'Root cause analysis report for equipment failures. Documents failure mode, contributing factors, corrective actions, and preventive measures.',
    module: 'CMMS',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['failure-analysis', 'root-cause', 'rca', 'equipment-failure'],
    fields: [
      { id: 'section_header', label: 'Failure Details', type: 'section' },
      {
        id: 'equipment_name',
        label: 'Equipment Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Failure Details',
      },
      {
        id: 'failure_date',
        label: 'Failure Date',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Failure Details',
      },
      {
        id: 'analyst',
        label: 'Analyst',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Failure Details',
      },
      {
        id: 'failure_mode',
        label: 'Failure Mode',
        type: 'textarea',
        required: true,
        placeholder: 'How did the equipment fail?',
        validation: { minLength: 10, maxLength: 2000 },
        width: 'full',
        section: 'Failure Details',
      },
      { id: 'section_analysis', label: 'Root Cause Analysis', type: 'section' },
      {
        id: 'contributing_factors',
        label: 'Contributing Factors',
        type: 'table',
        required: true,
        columns: [
          { id: 'factor', label: 'Factor', type: 'text', required: true },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Mechanical', value: 'mechanical' },
              { label: 'Electrical', value: 'electrical' },
              { label: 'Human Error', value: 'human' },
              { label: 'Environmental', value: 'environmental' },
              { label: 'Material', value: 'material' },
              { label: 'Process', value: 'process' },
            ],
          },
          { id: 'evidence', label: 'Evidence', type: 'text', placeholder: 'Supporting evidence' },
        ],
        section: 'Root Cause Analysis',
      },
      {
        id: 'root_cause',
        label: 'Root Cause',
        type: 'textarea',
        required: true,
        validation: { minLength: 10, maxLength: 2000 },
        width: 'full',
        section: 'Root Cause Analysis',
      },
      { id: 'section_actions', label: 'Corrective & Preventive Actions', type: 'section' },
      {
        id: 'actions',
        label: 'Actions',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          {
            id: 'type',
            label: 'Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Corrective', value: 'corrective' },
              { label: 'Preventive', value: 'preventive' },
            ],
          },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Complete', value: 'complete' },
            ],
          },
        ],
        section: 'Corrective & Preventive Actions',
      },
    ],
  },
  {
    code: 'TPL-MNT-004',
    name: 'Breakdown Maintenance Report',
    description:
      'Unplanned / breakdown maintenance report for documenting emergency repairs, root cause of failure, total downtime, production impact, and corrective actions taken to restore equipment and prevent recurrence.',
    module: 'CMMS',
    category: 'INCIDENT_INVESTIGATION',
    tags: [
      'breakdown',
      'unplanned-maintenance',
      'emergency-repair',
      'downtime',
      'corrective-maintenance',
    ],
    fields: [
      { id: 'section_header', label: 'Breakdown Details', type: 'section' },
      {
        id: 'breakdown_ref',
        label: 'Breakdown Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. BD-2026-001',
        width: 'half',
        section: 'Breakdown Details',
      },
      {
        id: 'equipment_name',
        label: 'Equipment Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Breakdown Details',
      },
      {
        id: 'asset_id',
        label: 'Asset ID',
        type: 'text',
        required: true,
        placeholder: 'e.g. AST-001',
        width: 'half',
        section: 'Breakdown Details',
      },
      {
        id: 'location',
        label: 'Location / Production Line',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Breakdown Details',
      },
      {
        id: 'reported_by',
        label: 'Reported By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Breakdown Details',
      },
      {
        id: 'failure_datetime',
        label: 'Failure Date & Time',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Breakdown Details',
      },
      {
        id: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Critical — Complete line stoppage', value: 'critical' },
          { label: 'Major — Significant capacity reduction', value: 'major' },
          { label: 'Minor — Limited impact, workaround available', value: 'minor' },
        ],
        width: 'half',
        section: 'Breakdown Details',
      },
      {
        id: 'failure_description',
        label: 'Failure Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe how the failure presented — symptoms, alarms, operator observations...',
        validation: { minLength: 10, maxLength: 3000 },
        width: 'full',
        section: 'Breakdown Details',
      },
      { id: 'section_downtime', label: 'Downtime Tracking', type: 'section' },
      {
        id: 'production_stopped',
        label: 'Production Stopped?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Full stoppage', value: 'full_stop' },
          { label: 'Partial — Reduced output', value: 'partial' },
          { label: 'No — Non-production equipment', value: 'no' },
        ],
        width: 'half',
        section: 'Downtime Tracking',
      },
      {
        id: 'downtime_start',
        label: 'Downtime Start',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Downtime Tracking',
      },
      {
        id: 'downtime_end',
        label: 'Downtime End',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Downtime Tracking',
      },
      {
        id: 'total_downtime_hours',
        label: 'Total Downtime (hours)',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Downtime Tracking',
      },
      {
        id: 'estimated_production_loss',
        label: 'Estimated Production Loss (units)',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Downtime Tracking',
        helpText: 'Estimated units of production lost during the downtime period',
      },
      {
        id: 'estimated_financial_impact',
        label: 'Estimated Financial Impact',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Downtime Tracking',
        helpText: 'Estimated cost of lost production plus repair costs',
      },
      { id: 'section_repair', label: 'Repair Details', type: 'section' },
      {
        id: 'attending_technician',
        label: 'Attending Technician(s)',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Repair Details',
      },
      {
        id: 'response_time_minutes',
        label: 'Response Time (minutes)',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Repair Details',
        helpText: 'Time from failure report to technician arriving on site',
      },
      {
        id: 'repair_description',
        label: 'Repair Work Performed',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe all repair work performed, including diagnosis steps, components replaced, adjustments made...',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
        section: 'Repair Details',
      },
      {
        id: 'parts_used',
        label: 'Parts / Materials Used',
        type: 'table',
        columns: [
          { id: 'part_name', label: 'Part / Material', type: 'text', required: true },
          { id: 'part_number', label: 'Part Number', type: 'text' },
          {
            id: 'quantity',
            label: 'Quantity',
            type: 'number',
            required: true,
            validation: { min: 1 },
          },
          {
            id: 'from_stock',
            label: 'From Stock?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes — From store', value: 'yes' },
              { label: 'No — Emergency purchase', value: 'no' },
            ],
          },
          { id: 'cost', label: 'Cost', type: 'number', validation: { min: 0 } },
        ],
        section: 'Repair Details',
      },
      {
        id: 'total_repair_hours',
        label: 'Total Repair Labour Hours',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Repair Details',
      },
      {
        id: 'external_contractor',
        label: 'External Contractor Used?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ],
        width: 'half',
        section: 'Repair Details',
      },
      {
        id: 'contractor_details',
        label: 'Contractor Details',
        type: 'text',
        placeholder: 'Contractor name and reference if applicable',
        width: 'full',
        section: 'Repair Details',
      },
      { id: 'section_root_cause', label: 'Root Cause Analysis', type: 'section' },
      {
        id: 'root_cause_category',
        label: 'Root Cause Category',
        type: 'select',
        required: true,
        options: [
          { label: 'Wear & tear / Age', value: 'wear' },
          { label: 'Lack of maintenance', value: 'maintenance_gap' },
          { label: 'Operator error', value: 'operator_error' },
          { label: 'Design deficiency', value: 'design' },
          { label: 'Material / Component defect', value: 'material_defect' },
          { label: 'Overload / Operating beyond limits', value: 'overload' },
          { label: 'Environmental conditions', value: 'environmental' },
          { label: 'Contamination / Foreign object', value: 'contamination' },
          { label: 'Unknown — Further investigation needed', value: 'unknown' },
        ],
        width: 'half',
        section: 'Root Cause Analysis',
      },
      {
        id: 'root_cause_description',
        label: 'Root Cause Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Detailed root cause analysis. Include investigation method (5-Why, Fishbone, etc.) and findings...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Root Cause Analysis',
      },
      {
        id: 'could_have_been_prevented',
        label: 'Could This Failure Have Been Prevented?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — PM programme gap', value: 'yes_pm_gap' },
          { label: 'Yes — Predictive maintenance could have detected', value: 'yes_pdm' },
          { label: 'Partially — Better monitoring would have helped', value: 'partially' },
          { label: 'No — Unpredictable failure', value: 'no' },
        ],
        width: 'full',
        section: 'Root Cause Analysis',
      },
      { id: 'section_prevention', label: 'Preventive Actions', type: 'section' },
      {
        id: 'preventive_actions',
        label: 'Preventive Actions',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          {
            id: 'action_type',
            label: 'Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Update PM schedule', value: 'pm_update' },
              { label: 'Add condition monitoring', value: 'condition_monitoring' },
              { label: 'Operator training', value: 'training' },
              { label: 'Design modification', value: 'design_mod' },
              { label: 'Spare parts stocking', value: 'spares' },
              { label: 'Procedure update', value: 'procedure' },
              { label: 'Equipment replacement', value: 'replacement' },
            ],
          },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Complete', value: 'complete' },
            ],
          },
        ],
        section: 'Preventive Actions',
      },
      { id: 'section_signoff', label: 'Sign-Off', type: 'section' },
      {
        id: 'equipment_status_after',
        label: 'Equipment Status After Repair',
        type: 'select',
        required: true,
        options: [
          { label: 'Fully Operational', value: 'operational' },
          { label: 'Operational with Limitations', value: 'limited' },
          { label: 'Temporary Repair — Planned follow-up', value: 'temporary' },
          { label: 'Out of Service', value: 'out_of_service' },
        ],
        width: 'half',
        section: 'Sign-Off',
      },
      {
        id: 'follow_up_date',
        label: 'Follow-Up Date (if temporary repair)',
        type: 'date',
        width: 'half',
        section: 'Sign-Off',
      },
      {
        id: 'technician_signature',
        label: 'Technician Signature',
        type: 'signature',
        required: true,
        section: 'Sign-Off',
      },
      {
        id: 'maintenance_manager_signature',
        label: 'Maintenance Manager Signature',
        type: 'signature',
        required: true,
        section: 'Sign-Off',
      },
    ],
  },
  {
    code: 'TPL-MNT-005',
    name: 'Asset Criticality Assessment',
    description:
      'Asset criticality ranking assessment using a structured matrix approach to evaluate equipment based on safety, production, quality, environmental, and maintenance impact factors. Used to prioritise maintenance resources and determine appropriate maintenance strategies.',
    module: 'CMMS',
    category: 'RISK_ASSESSMENT',
    tags: [
      'asset-criticality',
      'criticality-ranking',
      'maintenance-strategy',
      'reliability',
      'prioritisation',
    ],
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      {
        id: 'assessment_ref',
        label: 'Assessment Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. ACR-2026-001',
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'facility',
        label: 'Facility / Plant',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'department',
        label: 'Department / Area',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'assessor',
        label: 'Assessor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'review_due_date',
        label: 'Review Due Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
        helpText:
          'Criticality assessments should be reviewed annually or after significant changes',
      },
      { id: 'section_criteria', label: 'Scoring Criteria', type: 'section' },
      {
        id: 'scoring_explanation',
        label: 'Scoring Methodology',
        type: 'textarea',
        required: true,
        placeholder:
          'Define the scoring scales used for each criterion. Typical scale: 1=Negligible, 2=Low, 3=Moderate, 4=High, 5=Extreme. Criticality = sum of all factor scores. Describe any weighting applied...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Scoring Criteria',
        helpText: 'Document the scoring methodology so assessments are consistent and repeatable',
      },
      {
        id: 'criticality_bands',
        label: 'Criticality Bands',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'band',
            label: 'Criticality Band',
            type: 'select',
            required: true,
            options: [
              { label: 'A — Critical', value: 'A' },
              { label: 'B — Important', value: 'B' },
              { label: 'C — Standard', value: 'C' },
              { label: 'D — Low', value: 'D' },
            ],
          },
          {
            id: 'score_range',
            label: 'Score Range',
            type: 'text',
            required: true,
            placeholder: 'e.g. 25-30',
          },
          {
            id: 'maintenance_strategy',
            label: 'Recommended Strategy',
            type: 'text',
            required: true,
            placeholder: 'e.g. Predictive + PM, Run-to-failure',
          },
          {
            id: 'spare_strategy',
            label: 'Spare Parts Strategy',
            type: 'text',
            placeholder: 'e.g. Critical spares held on site',
          },
        ],
        section: 'Scoring Criteria',
      },
      { id: 'section_assets', label: 'Asset Criticality Register', type: 'section' },
      {
        id: 'asset_register',
        label: 'Asset Criticality Scores',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'asset_id',
            label: 'Asset ID',
            type: 'text',
            required: true,
            placeholder: 'e.g. AST-001',
          },
          { id: 'equipment_name', label: 'Equipment Name', type: 'text', required: true },
          {
            id: 'safety_impact',
            label: 'Safety Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'production_impact',
            label: 'Production Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'quality_impact',
            label: 'Quality Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'environmental_impact',
            label: 'Environmental Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'mttr',
            label: 'Repair Difficulty (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'failure_frequency',
            label: 'Failure Frequency (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'total_score',
            label: 'Total Score',
            type: 'number',
            required: true,
            validation: { min: 6, max: 30 },
          },
          {
            id: 'criticality_band',
            label: 'Criticality Band',
            type: 'select',
            required: true,
            options: [
              { label: 'A — Critical', value: 'A' },
              { label: 'B — Important', value: 'B' },
              { label: 'C — Standard', value: 'C' },
              { label: 'D — Low', value: 'D' },
            ],
          },
        ],
        section: 'Asset Criticality Register',
      },
      { id: 'section_strategy', label: 'Maintenance Strategy Recommendations', type: 'section' },
      {
        id: 'strategy_recommendations',
        label: 'Strategy Recommendations by Criticality',
        type: 'table',
        required: true,
        columns: [
          { id: 'asset_id', label: 'Asset ID', type: 'text', required: true },
          {
            id: 'current_strategy',
            label: 'Current Strategy',
            type: 'select',
            required: true,
            options: [
              { label: 'Run to failure', value: 'rtf' },
              { label: 'Preventive (time-based)', value: 'pm_time' },
              { label: 'Preventive (usage-based)', value: 'pm_usage' },
              { label: 'Condition-based', value: 'cbm' },
              { label: 'Predictive', value: 'pdm' },
              { label: 'Total Productive Maintenance', value: 'tpm' },
            ],
          },
          {
            id: 'recommended_strategy',
            label: 'Recommended Strategy',
            type: 'select',
            required: true,
            options: [
              { label: 'Run to failure', value: 'rtf' },
              { label: 'Preventive (time-based)', value: 'pm_time' },
              { label: 'Preventive (usage-based)', value: 'pm_usage' },
              { label: 'Condition-based', value: 'cbm' },
              { label: 'Predictive', value: 'pdm' },
              { label: 'Total Productive Maintenance', value: 'tpm' },
            ],
          },
          { id: 'justification', label: 'Justification', type: 'text', required: true },
          {
            id: 'implementation_cost',
            label: 'Implementation Cost',
            type: 'number',
            validation: { min: 0 },
          },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            required: true,
            options: [
              { label: 'Immediate', value: 'immediate' },
              { label: 'Next quarter', value: 'next_quarter' },
              { label: 'Next annual plan', value: 'annual' },
            ],
          },
        ],
        section: 'Maintenance Strategy Recommendations',
      },
      { id: 'section_summary', label: 'Summary & Approval', type: 'section' },
      {
        id: 'total_assets_assessed',
        label: 'Total Assets Assessed',
        type: 'number',
        required: true,
        validation: { min: 1 },
        width: 'half',
        section: 'Summary & Approval',
      },
      {
        id: 'critical_count',
        label: 'Band A (Critical) Count',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Summary & Approval',
      },
      {
        id: 'important_count',
        label: 'Band B (Important) Count',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Summary & Approval',
      },
      {
        id: 'summary_notes',
        label: 'Summary & Key Findings',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise the overall criticality profile of the asset base. Highlight any assets that changed criticality band, new critical assets, and recommended budget implications...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Summary & Approval',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Summary & Approval',
      },
      {
        id: 'maintenance_manager_signature',
        label: 'Maintenance Manager Signature',
        type: 'signature',
        required: true,
        section: 'Summary & Approval',
      },
      {
        id: 'operations_manager_signature',
        label: 'Operations Manager Signature',
        type: 'signature',
        required: true,
        section: 'Summary & Approval',
      },
    ],
  },
];
