import type { TemplateDefinition } from '../types';

export const complaintsTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-CMP-001',
    name: 'Customer Complaint Form',
    description:
      'Structured customer complaint intake form for recording complaint details, initial assessment, investigation, and resolution. Aligned with ISO 9001 clause 8.5.2 and ISO 10002.',
    module: 'COMPLAINTS',
    category: 'CUSTOMER',
    tags: ['customer-complaint', 'complaint-handling', 'iso-9001', 'iso-10002'],
    isoClause: '8.5.2',
    fields: [
      { id: 'section_complaint', label: 'Complaint Details', type: 'section' },
      { id: 'complaint_ref', label: 'Complaint Reference', type: 'text', required: true, placeholder: 'e.g. CMP-2026-001', width: 'half', section: 'Complaint Details' },
      { id: 'date_received', label: 'Date Received', type: 'date', required: true, width: 'half', section: 'Complaint Details' },
      { id: 'customer_name', label: 'Customer Name', type: 'text', required: true, width: 'half', section: 'Complaint Details' },
      { id: 'customer_contact', label: 'Customer Contact', type: 'text', required: true, width: 'half', section: 'Complaint Details' },
      { id: 'received_by', label: 'Received By', type: 'text', required: true, width: 'half', section: 'Complaint Details' },
      { id: 'received_via', label: 'Received Via', type: 'select', required: true, options: [{ label: 'Email', value: 'email' }, { label: 'Phone', value: 'phone' }, { label: 'In Person', value: 'in_person' }, { label: 'Website', value: 'website' }, { label: 'Letter', value: 'letter' }, { label: 'Social Media', value: 'social_media' }], width: 'half', section: 'Complaint Details' },
      { id: 'category', label: 'Complaint Category', type: 'select', required: true, options: [{ label: 'Product Quality', value: 'product_quality' }, { label: 'Service Quality', value: 'service_quality' }, { label: 'Delivery', value: 'delivery' }, { label: 'Billing', value: 'billing' }, { label: 'Safety', value: 'safety' }, { label: 'Documentation', value: 'documentation' }, { label: 'Other', value: 'other' }], width: 'half', section: 'Complaint Details' },
      { id: 'severity', label: 'Severity', type: 'select', required: true, options: [{ label: 'Critical — Safety/Regulatory', value: 'critical' }, { label: 'Major', value: 'major' }, { label: 'Minor', value: 'minor' }], width: 'half', section: 'Complaint Details' },
      { id: 'description', label: 'Complaint Description', type: 'textarea', required: true, placeholder: 'Describe the complaint in detail including products/services involved...', validation: { minLength: 30, maxLength: 5000 }, width: 'full', section: 'Complaint Details' },
      { id: 'section_investigation', label: 'Investigation', type: 'section' },
      { id: 'investigator', label: 'Investigator', type: 'text', required: true, width: 'half', section: 'Investigation' },
      { id: 'investigation_date', label: 'Investigation Date', type: 'date', required: true, width: 'half', section: 'Investigation' },
      { id: 'root_cause', label: 'Root Cause', type: 'textarea', required: true, placeholder: 'Identify the root cause of the complaint...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Investigation' },
      { id: 'section_resolution', label: 'Resolution', type: 'section' },
      { id: 'immediate_action', label: 'Immediate Action Taken', type: 'textarea', required: true, placeholder: 'Containment and immediate correction...', validation: { maxLength: 2000 }, width: 'full', section: 'Resolution' },
      { id: 'corrective_action', label: 'Corrective Action', type: 'textarea', required: true, placeholder: 'Permanent corrective action to prevent recurrence...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Resolution' },
      { id: 'customer_notified', label: 'Customer Notified?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'Not Yet', value: 'not_yet' }], width: 'half', section: 'Resolution' },
      { id: 'closed_date', label: 'Date Closed', type: 'date', width: 'half', section: 'Resolution' },
      { id: 'customer_satisfaction', label: 'Customer Satisfied with Resolution?', type: 'select', options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }, { label: 'Pending', value: 'pending' }], width: 'half', section: 'Resolution' },
      { id: 'investigator_signature', label: 'Investigator Signature', type: 'signature', required: true, section: 'Resolution' },
    ],
  },
  {
    code: 'TPL-CMP-002',
    name: 'Complaint Trend Analysis Report',
    description:
      'Periodic report for analysing complaint trends, identifying systemic issues, and tracking improvement effectiveness.',
    module: 'COMPLAINTS',
    category: 'REPORTING',
    tags: ['complaint-trends', 'analysis', 'kpi', 'continual-improvement'],
    isoClause: '9.1.3',
    fields: [
      { id: 'section_header', label: 'Report Details', type: 'section' },
      { id: 'report_period', label: 'Report Period', type: 'text', required: true, placeholder: 'e.g. Q1 2026', width: 'half', section: 'Report Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'Report Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Report Details' },
      { id: 'section_summary', label: 'Summary Statistics', type: 'section' },
      { id: 'total_complaints', label: 'Total Complaints', type: 'number', required: true, validation: { min: 0 }, width: 'third', section: 'Summary Statistics' },
      { id: 'closed_complaints', label: 'Closed', type: 'number', required: true, validation: { min: 0 }, width: 'third', section: 'Summary Statistics' },
      { id: 'open_complaints', label: 'Open', type: 'number', required: true, validation: { min: 0 }, width: 'third', section: 'Summary Statistics' },
      { id: 'avg_resolution_days', label: 'Avg. Resolution Time (days)', type: 'number', validation: { min: 0 }, width: 'third', section: 'Summary Statistics' },
      { id: 'customer_satisfaction_rate', label: 'Customer Satisfaction Rate %', type: 'number', validation: { min: 0, max: 100 }, width: 'third', section: 'Summary Statistics' },
      { id: 'repeat_complaint_rate', label: 'Repeat Complaint Rate %', type: 'number', validation: { min: 0, max: 100 }, width: 'third', section: 'Summary Statistics' },
      { id: 'section_trends', label: 'Trend Analysis', type: 'section' },
      {
        id: 'by_category',
        label: 'Complaints by Category',
        type: 'table',
        columns: [
          { id: 'category', label: 'Category', type: 'text', required: true },
          { id: 'count', label: 'Count', type: 'number', required: true },
          { id: 'pct', label: '% of Total', type: 'number' },
          { id: 'trend', label: 'Trend', type: 'select', options: [{ label: 'Increasing', value: 'increasing' }, { label: 'Stable', value: 'stable' }, { label: 'Decreasing', value: 'decreasing' }] },
        ],
        section: 'Trend Analysis',
      },
      { id: 'top_issues', label: 'Top Issues / Root Causes', type: 'textarea', required: true, validation: { maxLength: 3000 }, width: 'full', section: 'Trend Analysis' },
      { id: 'section_actions', label: 'Actions', type: 'section' },
      { id: 'improvements', label: 'Recommended Improvements', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Actions' },
      { id: 'manager_signature', label: 'Manager Signature', type: 'signature', required: true, section: 'Actions' },
    ],
  },
  {
    code: 'TPL-CMP-003',
    name: 'Stakeholder Complaint Register',
    description:
      'Register for tracking all complaints from stakeholders (employees, regulators, community, suppliers) beyond customer complaints.',
    module: 'COMPLAINTS',
    category: 'COMPLIANCE',
    tags: ['stakeholder-complaints', 'register', 'non-customer', 'tracking'],
    isoClause: '4.2',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      { id: 'maintained_by', label: 'Maintained By', type: 'text', required: true, width: 'half', section: 'Register Details' },
      { id: 'last_updated', label: 'Last Updated', type: 'date', required: true, width: 'half', section: 'Register Details' },
      { id: 'section_register', label: 'Complaints', type: 'section' },
      {
        id: 'complaints',
        label: 'Complaint Entries',
        type: 'table',
        required: true,
        columns: [
          { id: 'ref', label: 'Ref', type: 'text', required: true },
          { id: 'date', label: 'Date', type: 'date', required: true },
          { id: 'stakeholder_type', label: 'Stakeholder Type', type: 'select', required: true, options: [{ label: 'Employee', value: 'employee' }, { label: 'Regulator', value: 'regulator' }, { label: 'Community', value: 'community' }, { label: 'Supplier', value: 'supplier' }, { label: 'Partner', value: 'partner' }, { label: 'Other', value: 'other' }] },
          { id: 'complainant', label: 'Complainant', type: 'text' },
          { id: 'category', label: 'Category', type: 'text', required: true },
          { id: 'description', label: 'Description', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'status', label: 'Status', type: 'select', options: [{ label: 'Open', value: 'open' }, { label: 'Investigating', value: 'investigating' }, { label: 'Resolved', value: 'resolved' }, { label: 'Closed', value: 'closed' }] },
          { id: 'resolution', label: 'Resolution', type: 'text' },
          { id: 'closed_date', label: 'Closed Date', type: 'date' },
        ],
        section: 'Complaints',
      },
    ],
  },
  {
    code: 'TPL-CMP-004',
    name: 'Complaint Investigation & CAPA Form',
    description: 'Combined investigation and corrective action form for complaints requiring root cause analysis and formal resolution per ISO 10002.',
    module: 'COMPLAINTS',
    category: 'CAPA',
    tags: ['complaint-investigation', 'capa', 'root-cause', 'iso-10002'],
    isoClause: '10.2',
    fields: [
      { id: 'section_complaint', label: 'Complaint Reference', type: 'section' },
      { id: 'complaint_ref', label: 'Complaint Ref', type: 'text', required: true, width: 'half', section: 'Complaint Reference' },
      { id: 'investigation_date', label: 'Investigation Date', type: 'date', required: true, width: 'half', section: 'Complaint Reference' },
      { id: 'investigator', label: 'Investigator', type: 'text', required: true, width: 'half', section: 'Complaint Reference' },
      { id: 'section_rca', label: 'Root Cause Analysis', type: 'section' },
      { id: 'rca_method', label: 'Method', type: 'select', required: true, options: [{ label: '5 Whys', value: '5whys' }, { label: 'Fishbone', value: 'fishbone' }, { label: 'Pareto', value: 'pareto' }, { label: 'Other', value: 'other' }], width: 'half', section: 'Root Cause Analysis' },
      { id: 'root_cause', label: 'Root Cause', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Root Cause Analysis' },
      { id: 'section_action', label: 'Corrective Action', type: 'section' },
      { id: 'containment', label: 'Containment Action', type: 'textarea', required: true, validation: { maxLength: 2000 }, width: 'full', section: 'Corrective Action' },
      { id: 'corrective_action', label: 'Corrective Action Plan', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Corrective Action' },
      { id: 'owner', label: 'Action Owner', type: 'text', required: true, width: 'half', section: 'Corrective Action' },
      { id: 'due_date', label: 'Due Date', type: 'date', required: true, width: 'half', section: 'Corrective Action' },
      { id: 'verification_date', label: 'Verification Date', type: 'date', width: 'half', section: 'Corrective Action' },
      { id: 'effective', label: 'Effective?', type: 'select', options: [{ label: 'Yes', value: 'yes' }, { label: 'No — Reopen', value: 'no' }], width: 'half', section: 'Corrective Action' },
      { id: 'investigator_signature', label: 'Investigator Signature', type: 'signature', required: true, section: 'Corrective Action' },
    ],
  },
];
