import type { TemplateDefinition } from '../types';

export const contractsTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-CON-001',
    name: 'Contract Review Checklist',
    description:
      'Pre-signature contract review checklist for assessing terms, risks, compliance requirements, and approval chain. Aligned with ISO 9001 clause 8.2.3.',
    module: 'CONTRACTS',
    category: 'COMPLIANCE',
    tags: ['contract-review', 'checklist', 'pre-signature', 'iso-9001'],
    isoClause: '8.2.3',
    fields: [
      { id: 'section_contract', label: 'Contract Details', type: 'section' },
      {
        id: 'contract_ref',
        label: 'Contract Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. CTR-2026-001',
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'contract_title',
        label: 'Contract Title',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'counterparty',
        label: 'Counterparty',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'contract_type',
        label: 'Contract Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Customer Contract', value: 'customer' },
          { label: 'Supplier Contract', value: 'supplier' },
          { label: 'Partnership Agreement', value: 'partnership' },
          { label: 'Service Agreement', value: 'service' },
          { label: 'NDA', value: 'nda' },
          { label: 'Employment', value: 'employment' },
          { label: 'Lease', value: 'lease' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'value',
        label: 'Contract Value (GBP)',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'start_date',
        label: 'Start Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'end_date',
        label: 'End Date',
        type: 'date',
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'reviewer',
        label: 'Reviewer',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      { id: 'section_checklist', label: 'Review Checklist', type: 'section' },
      {
        id: 'scope_clear',
        label: 'Scope clearly defined?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Action Required', value: 'no' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      {
        id: 'deliverables_defined',
        label: 'Deliverables clearly specified?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Action Required', value: 'no' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      {
        id: 'payment_terms',
        label: 'Payment terms acceptable?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Negotiate', value: 'no' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      {
        id: 'liability_caps',
        label: 'Liability caps adequate?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Negotiate', value: 'no' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      {
        id: 'termination_clause',
        label: 'Termination clause acceptable?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Negotiate', value: 'no' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      {
        id: 'ip_rights',
        label: 'IP rights addressed?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Action Required', value: 'no' },
          { label: 'N/A', value: 'na' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      {
        id: 'data_protection',
        label: 'Data protection / GDPR compliant?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Action Required', value: 'no' },
          { label: 'N/A', value: 'na' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      {
        id: 'insurance_adequate',
        label: 'Insurance requirements met?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Action Required', value: 'no' },
        ],
        width: 'half',
        section: 'Review Checklist',
      },
      { id: 'section_risks', label: 'Risk Assessment', type: 'section' },
      {
        id: 'risk_level',
        label: 'Overall Risk Level',
        type: 'select',
        required: true,
        options: [
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
        ],
        width: 'half',
        section: 'Risk Assessment',
      },
      {
        id: 'risks_identified',
        label: 'Risks Identified',
        type: 'textarea',
        placeholder: 'Describe key risks and mitigations...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Risk Assessment',
      },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      {
        id: 'recommendation',
        label: 'Recommendation',
        type: 'select',
        required: true,
        options: [
          { label: 'Approve for Signature', value: 'approve' },
          { label: 'Approve with Amendments', value: 'amend' },
          { label: 'Do Not Approve', value: 'reject' },
        ],
        width: 'half',
        section: 'Approval',
      },
      {
        id: 'comments',
        label: 'Comments',
        type: 'textarea',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Approval',
      },
      {
        id: 'reviewer_signature',
        label: 'Reviewer Signature',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
      {
        id: 'legal_signature',
        label: 'Legal Approval (if required)',
        type: 'signature',
        section: 'Approval',
      },
    ],
  },
  {
    code: 'TPL-CON-002',
    name: 'Contract Register',
    description:
      'Master contract register for tracking all active contracts, renewal dates, values, and responsible parties.',
    module: 'CONTRACTS',
    category: 'COMPLIANCE',
    tags: ['contract-register', 'master-list', 'tracking', 'renewals'],
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      {
        id: 'maintained_by',
        label: 'Maintained By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Register Details',
      },
      {
        id: 'last_updated',
        label: 'Last Updated',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Register Details',
      },
      { id: 'section_contracts', label: 'Contract List', type: 'section' },
      {
        id: 'contracts',
        label: 'Contracts',
        type: 'table',
        required: true,
        columns: [
          { id: 'ref', label: 'Ref', type: 'text', required: true },
          { id: 'title', label: 'Title', type: 'text', required: true },
          { id: 'counterparty', label: 'Counterparty', type: 'text', required: true },
          {
            id: 'type',
            label: 'Type',
            type: 'select',
            options: [
              { label: 'Customer', value: 'customer' },
              { label: 'Supplier', value: 'supplier' },
              { label: 'Service', value: 'service' },
              { label: 'Lease', value: 'lease' },
              { label: 'NDA', value: 'nda' },
              { label: 'Other', value: 'other' },
            ],
          },
          { id: 'value', label: 'Value (GBP)', type: 'number' },
          { id: 'start', label: 'Start Date', type: 'date', required: true },
          { id: 'expiry', label: 'Expiry Date', type: 'date' },
          {
            id: 'auto_renew',
            label: 'Auto-Renew?',
            type: 'select',
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Active', value: 'active' },
              { label: 'Expiring Soon', value: 'expiring' },
              { label: 'Expired', value: 'expired' },
              { label: 'Terminated', value: 'terminated' },
              { label: 'Under Negotiation', value: 'negotiation' },
            ],
          },
        ],
        section: 'Contract List',
      },
    ],
  },
  {
    code: 'TPL-CON-003',
    name: 'Contract Amendment Record',
    description:
      'Record for documenting contract amendments, including change description, impact assessment, and mutual agreement.',
    module: 'CONTRACTS',
    category: 'PROCESS_CONTROL',
    tags: ['contract-amendment', 'variation', 'change-order', 'modification'],
    isoClause: '8.2.4',
    fields: [
      { id: 'section_header', label: 'Amendment Details', type: 'section' },
      {
        id: 'amendment_ref',
        label: 'Amendment Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. CTR-2026-001-AMD-01',
        width: 'half',
        section: 'Amendment Details',
      },
      {
        id: 'contract_ref',
        label: 'Original Contract Ref',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Amendment Details',
      },
      {
        id: 'contract_title',
        label: 'Contract Title',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Amendment Details',
      },
      {
        id: 'counterparty',
        label: 'Counterparty',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Amendment Details',
      },
      {
        id: 'requested_by',
        label: 'Requested By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Amendment Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Amendment Details',
      },
      { id: 'section_changes', label: 'Changes', type: 'section' },
      {
        id: 'change_description',
        label: 'Description of Amendment',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the changes being made to the contract...',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
        section: 'Changes',
      },
      {
        id: 'reason',
        label: 'Reason for Amendment',
        type: 'textarea',
        required: true,
        validation: { minLength: 10, maxLength: 2000 },
        width: 'full',
        section: 'Changes',
      },
      {
        id: 'cost_impact',
        label: 'Cost Impact (GBP)',
        type: 'number',
        width: 'half',
        section: 'Changes',
      },
      {
        id: 'timeline_impact',
        label: 'Timeline Impact',
        type: 'text',
        placeholder: 'e.g. +2 weeks delivery',
        width: 'half',
        section: 'Changes',
      },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      {
        id: 'internal_approval',
        label: 'Internal Approval',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
      {
        id: 'counterparty_agreed',
        label: 'Counterparty Agreement',
        type: 'select',
        required: true,
        options: [
          { label: 'Agreed', value: 'agreed' },
          { label: 'Under Negotiation', value: 'negotiation' },
          { label: 'Rejected', value: 'rejected' },
        ],
        width: 'half',
        section: 'Approval',
      },
      {
        id: 'effective_date',
        label: 'Amendment Effective Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Approval',
      },
    ],
  },
  {
    code: 'TPL-CON-004',
    name: 'Contract Closeout Checklist',
    description:
      'Checklist for formally closing out completed or terminated contracts, verifying all obligations have been met and documenting lessons learned.',
    module: 'CONTRACTS',
    category: 'COMPLIANCE',
    tags: ['contract-closeout', 'completion', 'obligations', 'lessons-learned'],
    isoClause: '8.2.3',
    fields: [
      { id: 'section_contract', label: 'Contract Details', type: 'section' },
      {
        id: 'contract_ref',
        label: 'Contract Reference',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'contract_title',
        label: 'Contract Title',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'counterparty',
        label: 'Counterparty',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'closeout_date',
        label: 'Closeout Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Contract Details',
      },
      {
        id: 'closeout_reason',
        label: 'Reason',
        type: 'select',
        required: true,
        options: [
          { label: 'Completed', value: 'completed' },
          { label: 'Expired', value: 'expired' },
          { label: 'Terminated', value: 'terminated' },
          { label: 'Replaced', value: 'replaced' },
        ],
        width: 'half',
        section: 'Contract Details',
      },
      { id: 'section_checklist', label: 'Closeout Checklist', type: 'section' },
      {
        id: 'items',
        label: 'Verification Items',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'item',
            label: 'Item',
            type: 'select',
            required: true,
            options: [
              { label: 'All deliverables received', value: 'deliverables' },
              { label: 'All payments settled', value: 'payments' },
              { label: 'Warranties documented', value: 'warranties' },
              { label: 'IP / data returned', value: 'ip_data' },
              { label: 'Confidentiality obligations noted', value: 'confidentiality' },
              { label: 'Insurance certificates filed', value: 'insurance' },
              { label: 'Performance reviewed', value: 'performance' },
              { label: 'Disputes resolved', value: 'disputes' },
            ],
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Complete', value: 'complete' },
              { label: 'Outstanding', value: 'outstanding' },
              { label: 'N/A', value: 'na' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Closeout Checklist',
      },
      {
        id: 'lessons_learned',
        label: 'Lessons Learned',
        type: 'textarea',
        placeholder: 'Key takeaways from this contract...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Closeout Checklist',
      },
      {
        id: 'manager_signature',
        label: 'Manager Signature',
        type: 'signature',
        required: true,
        section: 'Closeout Checklist',
      },
    ],
  },
];
