import type { TemplateDefinition } from '../types';

export const crmTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-CRM-001',
    name: 'Customer Onboarding Checklist',
    description:
      'Step-by-step checklist for onboarding new customers. Covers account setup, introductions, training, and first-value milestones.',
    module: 'CRM',
    category: 'CUSTOMER',
    tags: ['onboarding', 'customer', 'checklist', 'new-account'],
    fields: [
      { id: 'section_customer', label: 'Customer Details', type: 'section' },
      { id: 'customer_name', label: 'Customer Name', type: 'text', required: true, width: 'half', section: 'Customer Details' },
      { id: 'account_manager', label: 'Account Manager', type: 'text', required: true, width: 'half', section: 'Customer Details' },
      { id: 'start_date', label: 'Onboarding Start Date', type: 'date', required: true, width: 'half', section: 'Customer Details' },
      { id: 'section_steps', label: 'Onboarding Steps', type: 'section' },
      {
        id: 'steps',
        label: 'Onboarding Steps',
        type: 'table',
        required: true,
        columns: [
          { id: 'step', label: 'Step', type: 'text', required: true, placeholder: 'e.g. Send welcome pack' },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Pending', value: 'pending' }, { label: 'Complete', value: 'complete' }, { label: 'Skipped', value: 'skipped' }] },
        ],
        section: 'Onboarding Steps',
      },
      { id: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional onboarding notes...', validation: { maxLength: 2000 }, width: 'full', section: 'Onboarding Steps' },
    ],
  },
  {
    code: 'TPL-CRM-002',
    name: 'Account Review Report',
    description:
      'Quarterly or annual account review template covering relationship health, revenue, satisfaction, and growth opportunities.',
    module: 'CRM',
    category: 'REPORTING',
    tags: ['account-review', 'customer-health', 'revenue', 'quarterly-review'],
    fields: [
      { id: 'section_header', label: 'Review Details', type: 'section' },
      { id: 'customer_name', label: 'Customer Name', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'review_period', label: 'Review Period', type: 'text', required: true, placeholder: 'e.g. Q1 2026', width: 'half', section: 'Review Details' },
      { id: 'account_manager', label: 'Account Manager', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'health_score', label: 'Account Health', type: 'select', required: true, options: [{ label: 'Healthy', value: 'healthy' }, { label: 'At Risk', value: 'at_risk' }, { label: 'Critical', value: 'critical' }], width: 'half', section: 'Review Details' },
      { id: 'section_metrics', label: 'Key Metrics', type: 'section' },
      { id: 'annual_revenue', label: 'Annual Revenue', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Key Metrics' },
      { id: 'nps_score', label: 'NPS Score', type: 'number', validation: { min: -100, max: 100 }, width: 'half', section: 'Key Metrics' },
      { id: 'section_opportunities', label: 'Opportunities & Actions', type: 'section' },
      {
        id: 'opportunities',
        label: 'Growth Opportunities',
        type: 'table',
        columns: [
          { id: 'opportunity', label: 'Opportunity', type: 'text', required: true },
          { id: 'value', label: 'Estimated Value', type: 'number', validation: { min: 0 } },
          { id: 'action', label: 'Next Action', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
        ],
        section: 'Opportunities & Actions',
      },
      { id: 'summary', label: 'Summary & Recommendations', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Opportunities & Actions' },
    ],
  },
  {
    code: 'TPL-CRM-003',
    name: 'Sales Pipeline Review',
    description:
      'Sales pipeline review template for tracking deals by stage, probability, and expected close date. Supports weekly pipeline meetings.',
    module: 'CRM',
    category: 'REPORTING',
    tags: ['pipeline', 'sales', 'deals', 'forecast', 'pipeline-review'],
    fields: [
      { id: 'section_header', label: 'Pipeline Review', type: 'section' },
      { id: 'review_date', label: 'Review Date', type: 'date', required: true, width: 'half', section: 'Pipeline Review' },
      { id: 'sales_rep', label: 'Sales Representative', type: 'text', required: true, width: 'half', section: 'Pipeline Review' },
      { id: 'section_deals', label: 'Active Deals', type: 'section' },
      {
        id: 'deals',
        label: 'Deals',
        type: 'table',
        required: true,
        columns: [
          { id: 'deal_name', label: 'Deal Name', type: 'text', required: true },
          { id: 'company', label: 'Company', type: 'text', required: true },
          { id: 'value', label: 'Deal Value', type: 'number', required: true, validation: { min: 0 } },
          { id: 'stage', label: 'Stage', type: 'select', required: true, options: [{ label: 'Prospecting', value: 'prospecting' }, { label: 'Qualification', value: 'qualification' }, { label: 'Proposal', value: 'proposal' }, { label: 'Negotiation', value: 'negotiation' }, { label: 'Closed Won', value: 'closed_won' }, { label: 'Closed Lost', value: 'closed_lost' }] },
          { id: 'probability', label: 'Probability %', type: 'number', validation: { min: 0, max: 100 } },
          { id: 'close_date', label: 'Expected Close', type: 'date', required: true },
          { id: 'next_step', label: 'Next Step', type: 'text', placeholder: 'Next action to progress' },
        ],
        section: 'Active Deals',
      },
      { id: 'total_pipeline', label: 'Total Pipeline Value', type: 'number', validation: { min: 0 }, width: 'half', section: 'Active Deals' },
      { id: 'weighted_pipeline', label: 'Weighted Pipeline Value', type: 'number', validation: { min: 0 }, width: 'half', section: 'Active Deals' },
    ],
  },
  {
    code: 'TPL-CRM-004',
    name: 'Account Plan Template',
    description:
      'Strategic account plan for key accounts covering account objectives, relationship mapping, opportunity pipeline, competitive landscape, and action items. Supports structured account management and revenue growth planning.',
    module: 'CRM',
    category: 'CUSTOMER',
    tags: ['account-plan', 'strategic-account', 'relationship-map', 'key-account', 'growth'],
    fields: [
      { id: 'section_account', label: 'Account Overview', type: 'section' },
      { id: 'account_name', label: 'Account Name', type: 'text', required: true, width: 'half', section: 'Account Overview' },
      { id: 'account_manager', label: 'Account Manager', type: 'text', required: true, width: 'half', section: 'Account Overview' },
      { id: 'plan_period', label: 'Plan Period', type: 'text', required: true, placeholder: 'e.g. FY 2026-2027', width: 'half', section: 'Account Overview' },
      { id: 'plan_date', label: 'Plan Date', type: 'date', required: true, width: 'half', section: 'Account Overview' },
      { id: 'account_tier', label: 'Account Tier', type: 'select', required: true, options: [{ label: 'Tier 1 — Strategic', value: 'tier1' }, { label: 'Tier 2 — Growth', value: 'tier2' }, { label: 'Tier 3 — Maintain', value: 'tier3' }], width: 'half', section: 'Account Overview' },
      { id: 'industry', label: 'Industry', type: 'text', required: true, width: 'half', section: 'Account Overview' },
      { id: 'annual_revenue', label: 'Current Annual Revenue', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Account Overview' },
      { id: 'revenue_target', label: 'Target Annual Revenue', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Account Overview' },
      { id: 'account_summary', label: 'Account Summary', type: 'textarea', required: true, placeholder: 'Provide a summary of the account including history, current status, and strategic importance...', validation: { minLength: 30, maxLength: 3000 }, width: 'full', section: 'Account Overview' },
      { id: 'section_objectives', label: 'Strategic Objectives', type: 'section', helpText: 'Define the key objectives for this account over the plan period.' },
      {
        id: 'objectives',
        label: 'Objectives',
        type: 'table',
        required: true,
        columns: [
          { id: 'objective', label: 'Objective', type: 'text', required: true, placeholder: 'e.g. Expand to 3 additional departments' },
          { id: 'category', label: 'Category', type: 'select', required: true, options: [{ label: 'Revenue Growth', value: 'revenue' }, { label: 'Product Adoption', value: 'adoption' }, { label: 'Relationship Deepening', value: 'relationship' }, { label: 'Retention / Renewal', value: 'retention' }, { label: 'Strategic Partnership', value: 'partnership' }, { label: 'Customer Satisfaction', value: 'satisfaction' }] },
          { id: 'metric', label: 'Success Metric', type: 'text', required: true, placeholder: 'e.g. 3 new department contracts signed' },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Not Started', value: 'not_started' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Achieved', value: 'achieved' }, { label: 'At Risk', value: 'at_risk' }, { label: 'Missed', value: 'missed' }] },
        ],
        section: 'Strategic Objectives',
      },
      { id: 'section_relationships', label: 'Relationship Map', type: 'section', helpText: 'Map key stakeholders, their roles, influence, and our relationship strength.' },
      {
        id: 'stakeholders',
        label: 'Key Stakeholders',
        type: 'table',
        required: true,
        columns: [
          { id: 'name', label: 'Name', type: 'text', required: true },
          { id: 'title', label: 'Title / Role', type: 'text', required: true },
          { id: 'department', label: 'Department', type: 'text', required: true },
          { id: 'influence', label: 'Influence Level', type: 'select', required: true, options: [{ label: 'Decision Maker', value: 'decision_maker' }, { label: 'Key Influencer', value: 'influencer' }, { label: 'Champion', value: 'champion' }, { label: 'Gatekeeper', value: 'gatekeeper' }, { label: 'End User', value: 'end_user' }, { label: 'Blocker', value: 'blocker' }] },
          { id: 'relationship_strength', label: 'Relationship Strength', type: 'select', required: true, options: [{ label: 'Strong — Executive Sponsor', value: 'strong' }, { label: 'Good — Regular Contact', value: 'good' }, { label: 'Developing — Occasional Contact', value: 'developing' }, { label: 'Weak — Limited Contact', value: 'weak' }, { label: 'None — No Contact', value: 'none' }] },
          { id: 'engagement_plan', label: 'Engagement Plan', type: 'text', placeholder: 'e.g. Monthly QBR, Executive dinner Q2' },
        ],
        section: 'Relationship Map',
      },
      { id: 'section_pipeline', label: 'Opportunity Pipeline', type: 'section', helpText: 'Track identified upsell, cross-sell, and expansion opportunities.' },
      {
        id: 'opportunities',
        label: 'Opportunities',
        type: 'table',
        columns: [
          { id: 'opportunity', label: 'Opportunity', type: 'text', required: true, placeholder: 'e.g. ISO 45001 module expansion' },
          { id: 'product_service', label: 'Product / Service', type: 'text', required: true },
          { id: 'estimated_value', label: 'Estimated Value', type: 'number', required: true, validation: { min: 0 } },
          { id: 'probability', label: 'Probability %', type: 'number', required: true, validation: { min: 0, max: 100 } },
          { id: 'stage', label: 'Stage', type: 'select', required: true, options: [{ label: 'Identified', value: 'identified' }, { label: 'Qualified', value: 'qualified' }, { label: 'Proposal Sent', value: 'proposal' }, { label: 'Negotiation', value: 'negotiation' }, { label: 'Closed Won', value: 'won' }, { label: 'Closed Lost', value: 'lost' }] },
          { id: 'expected_close', label: 'Expected Close', type: 'date', required: true },
          { id: 'next_step', label: 'Next Step', type: 'text', required: true },
        ],
        section: 'Opportunity Pipeline',
      },
      { id: 'section_competitive', label: 'Competitive Landscape', type: 'section' },
      {
        id: 'competitors',
        label: 'Competitors in Account',
        type: 'table',
        columns: [
          { id: 'competitor', label: 'Competitor', type: 'text', required: true },
          { id: 'products_used', label: 'Products / Services Used', type: 'text', required: true },
          { id: 'strength', label: 'Their Strength', type: 'text', placeholder: 'e.g. Lower price, legacy integration' },
          { id: 'our_advantage', label: 'Our Advantage', type: 'text', placeholder: 'e.g. Integrated platform, better support' },
          { id: 'threat_level', label: 'Threat Level', type: 'select', required: true, options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
          { id: 'displacement_strategy', label: 'Displacement Strategy', type: 'text', placeholder: 'How we plan to win against this competitor' },
        ],
        section: 'Competitive Landscape',
      },
      { id: 'section_actions', label: 'Action Plan', type: 'section' },
      {
        id: 'action_items',
        label: 'Key Actions',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          { id: 'priority', label: 'Priority', type: 'select', required: true, options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Open', value: 'open' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }, { label: 'Overdue', value: 'overdue' }] },
        ],
        section: 'Action Plan',
      },
      { id: 'risks_and_challenges', label: 'Risks & Challenges', type: 'textarea', placeholder: 'Identify key risks to achieving the account plan objectives and mitigation strategies...', validation: { maxLength: 2000 }, width: 'full', section: 'Action Plan' },
      { id: 'executive_summary', label: 'Executive Summary', type: 'textarea', required: true, placeholder: 'High-level summary of the account plan for leadership review...', validation: { minLength: 30, maxLength: 3000 }, width: 'full', section: 'Action Plan' },
      { id: 'account_manager_signature', label: 'Account Manager Signature', type: 'signature', required: true, section: 'Action Plan' },
      { id: 'sales_director_signature', label: 'Sales Director Signature', type: 'signature', required: true, section: 'Action Plan' },
    ],
  },
  {
    code: 'TPL-CRM-005',
    name: 'Customer Onboarding Checklist (Detailed)',
    description:
      'Comprehensive customer onboarding checklist with structured phases, milestone tracking, stakeholder handoff documentation, technical setup verification, and go-live readiness assessment. Ensures consistent onboarding experience and time-to-value.',
    module: 'CRM',
    category: 'CUSTOMER',
    tags: ['onboarding', 'customer-success', 'go-live', 'milestones', 'handoff', 'implementation'],
    fields: [
      { id: 'section_customer', label: 'Customer & Project Details', type: 'section' },
      { id: 'customer_name', label: 'Customer Name', type: 'text', required: true, width: 'half', section: 'Customer & Project Details' },
      { id: 'primary_contact', label: 'Customer Primary Contact', type: 'text', required: true, width: 'half', section: 'Customer & Project Details' },
      { id: 'contact_email', label: 'Contact Email', type: 'email', required: true, width: 'half', section: 'Customer & Project Details' },
      { id: 'contact_phone', label: 'Contact Phone', type: 'tel', width: 'half', section: 'Customer & Project Details' },
      { id: 'contract_start_date', label: 'Contract Start Date', type: 'date', required: true, width: 'half', section: 'Customer & Project Details' },
      { id: 'target_go_live', label: 'Target Go-Live Date', type: 'date', required: true, width: 'half', section: 'Customer & Project Details' },
      { id: 'products_purchased', label: 'Products / Modules Purchased', type: 'textarea', required: true, placeholder: 'List all products, modules, and licence details...', validation: { maxLength: 1000 }, width: 'full', section: 'Customer & Project Details' },
      { id: 'onboarding_manager', label: 'Onboarding Manager', type: 'text', required: true, width: 'half', section: 'Customer & Project Details' },
      { id: 'csm_assigned', label: 'Customer Success Manager', type: 'text', required: true, width: 'half', section: 'Customer & Project Details' },
      { id: 'section_handoff', label: 'Sales-to-CS Handoff', type: 'section', helpText: 'Document the handoff from the sales team to customer success / onboarding.' },
      { id: 'sales_rep', label: 'Sales Representative', type: 'text', required: true, width: 'half', section: 'Sales-to-CS Handoff' },
      { id: 'handoff_date', label: 'Handoff Date', type: 'date', required: true, width: 'half', section: 'Sales-to-CS Handoff' },
      { id: 'deal_summary', label: 'Deal Summary & Customer Expectations', type: 'textarea', required: true, placeholder: 'Summarise the deal, customer expectations, key commitments, and any special terms...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Sales-to-CS Handoff' },
      { id: 'success_criteria', label: 'Customer-Defined Success Criteria', type: 'textarea', required: true, placeholder: 'What does the customer define as a successful implementation? List specific measurable outcomes...', validation: { minLength: 20, maxLength: 2000 }, width: 'full', section: 'Sales-to-CS Handoff' },
      { id: 'known_risks', label: 'Known Risks or Concerns', type: 'textarea', placeholder: 'Any risks, concerns, or potential blockers identified during the sales process...', validation: { maxLength: 1000 }, width: 'full', section: 'Sales-to-CS Handoff' },
      { id: 'section_phase1', label: 'Phase 1: Kickoff & Planning (Week 1)', type: 'section' },
      {
        id: 'phase1_tasks',
        label: 'Kickoff Tasks',
        type: 'table',
        required: true,
        columns: [
          { id: 'task', label: 'Task', type: 'select', required: true, options: [{ label: 'Internal kickoff meeting held', value: 'internal_kickoff' }, { label: 'Customer kickoff meeting scheduled', value: 'customer_kickoff_scheduled' }, { label: 'Customer kickoff meeting completed', value: 'customer_kickoff_done' }, { label: 'Welcome email sent', value: 'welcome_email' }, { label: 'Project plan shared with customer', value: 'project_plan' }, { label: 'Stakeholder roles confirmed', value: 'stakeholders_confirmed' }, { label: 'Communication cadence agreed', value: 'comms_cadence' }, { label: 'Access credentials provisioned', value: 'credentials' }] },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Pending', value: 'pending' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }, { label: 'Blocked', value: 'blocked' }, { label: 'Skipped', value: 'skipped' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Phase 1: Kickoff & Planning (Week 1)',
      },
      { id: 'section_phase2', label: 'Phase 2: Configuration & Setup (Weeks 2-3)', type: 'section' },
      {
        id: 'phase2_tasks',
        label: 'Setup Tasks',
        type: 'table',
        required: true,
        columns: [
          { id: 'task', label: 'Task', type: 'select', required: true, options: [{ label: 'Tenant / environment provisioned', value: 'tenant_provisioned' }, { label: 'SSO / authentication configured', value: 'sso_configured' }, { label: 'User accounts created', value: 'users_created' }, { label: 'Roles & permissions configured', value: 'roles_configured' }, { label: 'Data migration plan agreed', value: 'migration_plan' }, { label: 'Data migration completed', value: 'migration_done' }, { label: 'Integrations configured', value: 'integrations' }, { label: 'Custom branding applied', value: 'branding' }, { label: 'Workflows configured', value: 'workflows' }, { label: 'Document templates uploaded', value: 'templates' }] },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Pending', value: 'pending' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }, { label: 'Blocked', value: 'blocked' }, { label: 'Skipped', value: 'skipped' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Phase 2: Configuration & Setup (Weeks 2-3)',
      },
      { id: 'section_phase3', label: 'Phase 3: Training & UAT (Week 4)', type: 'section' },
      {
        id: 'phase3_tasks',
        label: 'Training & Testing Tasks',
        type: 'table',
        required: true,
        columns: [
          { id: 'task', label: 'Task', type: 'select', required: true, options: [{ label: 'Admin training delivered', value: 'admin_training' }, { label: 'End-user training delivered', value: 'user_training' }, { label: 'Training materials provided', value: 'training_materials' }, { label: 'UAT plan agreed', value: 'uat_plan' }, { label: 'UAT completed', value: 'uat_done' }, { label: 'UAT issues resolved', value: 'uat_issues' }, { label: 'Customer sign-off on UAT', value: 'uat_signoff' }] },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Pending', value: 'pending' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }, { label: 'Blocked', value: 'blocked' }, { label: 'Skipped', value: 'skipped' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Phase 3: Training & UAT (Week 4)',
      },
      { id: 'section_golive', label: 'Phase 4: Go-Live Readiness', type: 'section', helpText: 'Final verification before the customer goes live.' },
      { id: 'golive_checklist_complete', label: 'All Configuration Verified?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No — Outstanding Items', value: 'no' }], width: 'half', section: 'Phase 4: Go-Live Readiness' },
      { id: 'data_verified', label: 'Migrated Data Verified?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }, { label: 'N/A — No Migration', value: 'na' }], width: 'half', section: 'Phase 4: Go-Live Readiness' },
      { id: 'support_handover', label: 'Support Handover Complete?', type: 'select', required: true, options: [{ label: 'Yes — Escalation Path Communicated', value: 'yes' }, { label: 'No', value: 'no' }], width: 'half', section: 'Phase 4: Go-Live Readiness' },
      { id: 'customer_approval', label: 'Customer Go-Live Approval?', type: 'select', required: true, options: [{ label: 'Yes — Approved', value: 'yes' }, { label: 'No — Deferred', value: 'no' }], width: 'half', section: 'Phase 4: Go-Live Readiness' },
      { id: 'actual_go_live_date', label: 'Actual Go-Live Date', type: 'date', width: 'half', section: 'Phase 4: Go-Live Readiness' },
      { id: 'section_milestones', label: 'Post Go-Live Milestones', type: 'section', helpText: 'Track first-value milestones and early adoption indicators.' },
      {
        id: 'milestones',
        label: 'Post Go-Live Milestones',
        type: 'table',
        columns: [
          { id: 'milestone', label: 'Milestone', type: 'text', required: true, placeholder: 'e.g. First audit completed, 50 users active' },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          { id: 'actual_date', label: 'Actual Date', type: 'date' },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Pending', value: 'pending' }, { label: 'Achieved', value: 'achieved' }, { label: 'At Risk', value: 'at_risk' }, { label: 'Missed', value: 'missed' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Post Go-Live Milestones',
      },
      { id: 'section_summary', label: 'Onboarding Summary', type: 'section' },
      { id: 'overall_status', label: 'Overall Onboarding Status', type: 'select', required: true, options: [{ label: 'On Track', value: 'on_track' }, { label: 'At Risk', value: 'at_risk' }, { label: 'Delayed', value: 'delayed' }, { label: 'Complete', value: 'complete' }], width: 'half', section: 'Onboarding Summary' },
      { id: 'customer_satisfaction', label: 'Customer Satisfaction (Post-Onboarding)', type: 'rating', validation: { min: 1, max: 5 }, width: 'half', section: 'Onboarding Summary' },
      { id: 'onboarding_notes', label: 'Onboarding Notes & Lessons Learned', type: 'textarea', required: true, placeholder: 'Summarise the onboarding experience, any issues encountered, and recommendations for similar future engagements...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Onboarding Summary' },
      { id: 'onboarding_manager_signature', label: 'Onboarding Manager Signature', type: 'signature', required: true, section: 'Onboarding Summary' },
      { id: 'customer_signature', label: 'Customer Sign-Off Signature', type: 'signature', required: true, section: 'Onboarding Summary' },
    ],
  },
];
