import type { TemplateDefinition } from '../types';

export const documentsTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-DOC-001',
    name: 'Document Review & Approval Form',
    description:
      'Document review and approval form for managing the review cycle of controlled documents, capturing reviewer feedback and approval decisions. Aligned with ISO 9001 clause 7.5.',
    module: 'DOCUMENTS',
    category: 'COMPLIANCE',
    tags: ['document-review', 'approval', 'controlled-document', 'iso-9001'],
    isoClause: '7.5.2',
    fields: [
      { id: 'section_doc', label: 'Document Details', type: 'section' },
      { id: 'doc_ref', label: 'Document Reference', type: 'text', required: true, placeholder: 'e.g. QMS-PRO-001', width: 'half', section: 'Document Details' },
      { id: 'doc_title', label: 'Document Title', type: 'text', required: true, width: 'half', section: 'Document Details' },
      { id: 'doc_type', label: 'Document Type', type: 'select', required: true, options: [{ label: 'Policy', value: 'policy' }, { label: 'Procedure', value: 'procedure' }, { label: 'Work Instruction', value: 'work_instruction' }, { label: 'Form', value: 'form' }, { label: 'Standard', value: 'standard' }, { label: 'Specification', value: 'specification' }, { label: 'Manual', value: 'manual' }], width: 'half', section: 'Document Details' },
      { id: 'version', label: 'Version', type: 'text', required: true, placeholder: 'e.g. 2.0', width: 'half', section: 'Document Details' },
      { id: 'author', label: 'Author', type: 'text', required: true, width: 'half', section: 'Document Details' },
      { id: 'review_type', label: 'Review Type', type: 'select', required: true, options: [{ label: 'New Document', value: 'new' }, { label: 'Periodic Review', value: 'periodic' }, { label: 'Revision', value: 'revision' }, { label: 'Change Request', value: 'change' }], width: 'half', section: 'Document Details' },
      { id: 'change_summary', label: 'Summary of Changes', type: 'textarea', placeholder: 'Describe changes since previous version...', validation: { maxLength: 3000 }, width: 'full', section: 'Document Details' },
      { id: 'section_review', label: 'Review', type: 'section' },
      {
        id: 'reviewers',
        label: 'Reviewers',
        type: 'table',
        required: true,
        columns: [
          { id: 'reviewer_name', label: 'Reviewer', type: 'text', required: true },
          { id: 'role', label: 'Role', type: 'text', required: true },
          { id: 'review_date', label: 'Review Date', type: 'date', required: true },
          { id: 'decision', label: 'Decision', type: 'select', required: true, options: [{ label: 'Approved', value: 'approved' }, { label: 'Approved with Changes', value: 'approved_changes' }, { label: 'Rejected', value: 'rejected' }] },
          { id: 'comments', label: 'Comments', type: 'text' },
        ],
        section: 'Review',
      },
      { id: 'section_approval', label: 'Final Approval', type: 'section' },
      { id: 'effective_date', label: 'Effective Date', type: 'date', required: true, width: 'half', section: 'Final Approval' },
      { id: 'next_review', label: 'Next Review Date', type: 'date', required: true, width: 'half', section: 'Final Approval' },
      { id: 'approver_signature', label: 'Approver Signature', type: 'signature', required: true, section: 'Final Approval' },
    ],
  },
  {
    code: 'TPL-DOC-002',
    name: 'Document Change Request',
    description:
      'Form for requesting changes to controlled documents, capturing justification, impact assessment, and approval workflow.',
    module: 'DOCUMENTS',
    category: 'PROCESS_CONTROL',
    tags: ['change-request', 'document-control', 'change-management'],
    isoClause: '7.5.2',
    fields: [
      { id: 'section_request', label: 'Change Request', type: 'section' },
      { id: 'dcr_ref', label: 'DCR Reference', type: 'text', required: true, placeholder: 'e.g. DCR-2026-001', width: 'half', section: 'Change Request' },
      { id: 'date', label: 'Request Date', type: 'date', required: true, width: 'half', section: 'Change Request' },
      { id: 'requester', label: 'Requester', type: 'text', required: true, width: 'half', section: 'Change Request' },
      { id: 'department', label: 'Department', type: 'text', required: true, width: 'half', section: 'Change Request' },
      { id: 'doc_ref', label: 'Document Reference', type: 'text', required: true, width: 'half', section: 'Change Request' },
      { id: 'doc_title', label: 'Document Title', type: 'text', required: true, width: 'half', section: 'Change Request' },
      { id: 'change_type', label: 'Change Type', type: 'select', required: true, options: [{ label: 'Editorial', value: 'editorial' }, { label: 'Technical', value: 'technical' }, { label: 'Regulatory', value: 'regulatory' }, { label: 'Process Improvement', value: 'improvement' }], width: 'half', section: 'Change Request' },
      { id: 'priority', label: 'Priority', type: 'select', required: true, options: [{ label: 'Urgent', value: 'urgent' }, { label: 'High', value: 'high' }, { label: 'Normal', value: 'normal' }, { label: 'Low', value: 'low' }], width: 'half', section: 'Change Request' },
      { id: 'description', label: 'Description of Change', type: 'textarea', required: true, placeholder: 'Describe the proposed changes in detail...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Change Request' },
      { id: 'justification', label: 'Justification', type: 'textarea', required: true, placeholder: 'Why is this change necessary?', validation: { minLength: 20, maxLength: 2000 }, width: 'full', section: 'Change Request' },
      { id: 'section_impact', label: 'Impact Assessment', type: 'section' },
      { id: 'affected_processes', label: 'Affected Processes', type: 'textarea', placeholder: 'List processes, departments, or systems affected...', validation: { maxLength: 2000 }, width: 'full', section: 'Impact Assessment' },
      { id: 'training_required', label: 'Training Required?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }], width: 'half', section: 'Impact Assessment' },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      { id: 'decision', label: 'Decision', type: 'select', required: true, options: [{ label: 'Approved', value: 'approved' }, { label: 'Rejected', value: 'rejected' }, { label: 'Deferred', value: 'deferred' }], width: 'half', section: 'Approval' },
      { id: 'approver_comments', label: 'Approver Comments', type: 'textarea', validation: { maxLength: 2000 }, width: 'full', section: 'Approval' },
      { id: 'approver_signature', label: 'Approver Signature', type: 'signature', required: true, section: 'Approval' },
    ],
  },
  {
    code: 'TPL-DOC-003',
    name: 'Master Document List',
    description:
      'Master list of all controlled documents in the management system, tracking document status, ownership, review dates, and distribution.',
    module: 'DOCUMENTS',
    category: 'COMPLIANCE',
    tags: ['master-list', 'document-register', 'controlled-documents'],
    isoClause: '7.5.3',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      { id: 'organisation', label: 'Organisation', type: 'text', required: true, width: 'half', section: 'Register Details' },
      { id: 'last_updated', label: 'Last Updated', type: 'date', required: true, width: 'half', section: 'Register Details' },
      { id: 'maintained_by', label: 'Maintained By', type: 'text', required: true, width: 'half', section: 'Register Details' },
      { id: 'section_documents', label: 'Document List', type: 'section' },
      {
        id: 'documents',
        label: 'Controlled Documents',
        type: 'table',
        required: true,
        columns: [
          { id: 'doc_ref', label: 'Doc Ref', type: 'text', required: true },
          { id: 'title', label: 'Title', type: 'text', required: true },
          { id: 'type', label: 'Type', type: 'select', options: [{ label: 'Policy', value: 'policy' }, { label: 'Procedure', value: 'procedure' }, { label: 'WI', value: 'wi' }, { label: 'Form', value: 'form' }, { label: 'Manual', value: 'manual' }, { label: 'Specification', value: 'spec' }] },
          { id: 'version', label: 'Version', type: 'text', required: true },
          { id: 'status', label: 'Status', type: 'select', options: [{ label: 'Active', value: 'active' }, { label: 'Under Review', value: 'review' }, { label: 'Obsolete', value: 'obsolete' }, { label: 'Draft', value: 'draft' }] },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'effective_date', label: 'Effective Date', type: 'date' },
          { id: 'review_date', label: 'Next Review', type: 'date' },
          { id: 'location', label: 'Storage Location', type: 'text' },
        ],
        section: 'Document List',
      },
    ],
  },
  {
    code: 'TPL-DOC-004',
    name: 'Document Distribution Record',
    description: 'Record for tracking the distribution of controlled documents to ensure all relevant parties receive the correct version.',
    module: 'DOCUMENTS',
    category: 'COMPLIANCE',
    tags: ['distribution', 'controlled-document', 'version-control', 'recipients'],
    isoClause: '7.5.3',
    fields: [
      { id: 'section_doc', label: 'Document Details', type: 'section' },
      { id: 'doc_ref', label: 'Document Reference', type: 'text', required: true, width: 'half', section: 'Document Details' },
      { id: 'doc_title', label: 'Document Title', type: 'text', required: true, width: 'half', section: 'Document Details' },
      { id: 'version', label: 'Version', type: 'text', required: true, width: 'half', section: 'Document Details' },
      { id: 'effective_date', label: 'Effective Date', type: 'date', required: true, width: 'half', section: 'Document Details' },
      { id: 'distributed_by', label: 'Distributed By', type: 'text', required: true, width: 'half', section: 'Document Details' },
      { id: 'section_recipients', label: 'Recipients', type: 'section' },
      {
        id: 'recipients',
        label: 'Distribution List',
        type: 'table',
        required: true,
        columns: [
          { id: 'name', label: 'Recipient Name', type: 'text', required: true },
          { id: 'department', label: 'Department', type: 'text', required: true },
          { id: 'copy_type', label: 'Copy Type', type: 'select', options: [{ label: 'Controlled', value: 'controlled' }, { label: 'Uncontrolled', value: 'uncontrolled' }, { label: 'Electronic', value: 'electronic' }] },
          { id: 'date_received', label: 'Date Received', type: 'date' },
          { id: 'acknowledged', label: 'Acknowledged?', type: 'select', options: [{ label: 'Yes', value: 'yes' }, { label: 'Pending', value: 'pending' }] },
        ],
        section: 'Recipients',
      },
      { id: 'previous_version_recalled', label: 'Previous Version Recalled?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'N/A (New Document)', value: 'na' }, { label: 'No', value: 'no' }], width: 'half', section: 'Recipients' },
    ],
  },
];
