import type { TemplateDefinition } from '../types';

export const energyTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-ENR-001',
    name: 'Energy Audit Report',
    description:
      'Comprehensive energy audit report covering energy consumption analysis, efficiency opportunities, and recommended improvements. Aligned with ISO 50001.',
    module: 'ENERGY',
    category: 'AUDIT',
    tags: ['energy-audit', 'iso-50001', 'efficiency', 'consumption'],
    isoClause: '6.3',
    fields: [
      { id: 'section_header', label: 'Audit Details', type: 'section' },
      { id: 'facility', label: 'Facility', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'auditor', label: 'Auditor', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'audit_date', label: 'Audit Date', type: 'date', required: true, width: 'half', section: 'Audit Details' },
      { id: 'period_covered', label: 'Period Covered', type: 'text', required: true, placeholder: 'e.g. Jan–Dec 2025', width: 'half', section: 'Audit Details' },
      { id: 'section_consumption', label: 'Energy Consumption', type: 'section' },
      {
        id: 'consumption',
        label: 'Consumption by Source',
        type: 'table',
        required: true,
        columns: [
          { id: 'source', label: 'Energy Source', type: 'select', required: true, options: [{ label: 'Electricity', value: 'electricity' }, { label: 'Natural Gas', value: 'natural_gas' }, { label: 'Diesel', value: 'diesel' }, { label: 'Solar', value: 'solar' }, { label: 'Other', value: 'other' }] },
          { id: 'consumption_kwh', label: 'Consumption (kWh)', type: 'number', required: true, validation: { min: 0 } },
          { id: 'cost', label: 'Cost', type: 'number', required: true, validation: { min: 0 } },
          { id: 'percentage', label: '% of Total', type: 'number', validation: { min: 0, max: 100 } },
        ],
        section: 'Energy Consumption',
      },
      { id: 'total_consumption', label: 'Total Consumption (kWh)', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Energy Consumption' },
      { id: 'section_opportunities', label: 'Improvement Opportunities', type: 'section' },
      {
        id: 'opportunities',
        label: 'Opportunities',
        type: 'table',
        required: true,
        columns: [
          { id: 'opportunity', label: 'Opportunity', type: 'text', required: true },
          { id: 'estimated_savings_kwh', label: 'Est. Savings (kWh/yr)', type: 'number', validation: { min: 0 } },
          { id: 'estimated_cost_saving', label: 'Est. Cost Saving/yr', type: 'number', validation: { min: 0 } },
          { id: 'investment', label: 'Investment Required', type: 'number', validation: { min: 0 } },
          { id: 'payback', label: 'Payback (months)', type: 'number', validation: { min: 0 } },
          { id: 'priority', label: 'Priority', type: 'select', required: true, options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
        ],
        section: 'Improvement Opportunities',
      },
      { id: 'summary', label: 'Audit Summary', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Improvement Opportunities' },
    ],
  },
  {
    code: 'TPL-ENR-002',
    name: 'Energy Savings Action Plan',
    description:
      'Action plan for implementing energy efficiency improvements with timeline, responsibilities, and expected savings.',
    module: 'ENERGY',
    category: 'PLANNING',
    tags: ['energy-savings', 'action-plan', 'efficiency', 'improvement'],
    fields: [
      { id: 'section_header', label: 'Plan Details', type: 'section' },
      { id: 'plan_title', label: 'Plan Title', type: 'text', required: true, width: 'full', section: 'Plan Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'Plan Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Plan Details' },
      { id: 'target_reduction', label: 'Target Reduction (%)', type: 'number', required: true, validation: { min: 0, max: 100 }, width: 'half', section: 'Plan Details' },
      { id: 'section_actions', label: 'Actions', type: 'section' },
      {
        id: 'actions',
        label: 'Action Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'start_date', label: 'Start Date', type: 'date', required: true },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          { id: 'expected_saving', label: 'Expected Saving (kWh/yr)', type: 'number', validation: { min: 0 } },
          { id: 'budget', label: 'Budget', type: 'number', validation: { min: 0 } },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Not Started', value: 'not_started' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }, { label: 'On Hold', value: 'on_hold' }] },
        ],
        section: 'Actions',
      },
    ],
  },
  {
    code: 'TPL-ENR-003',
    name: 'ISO 50001 Management Review',
    description:
      'Management review template for the energy management system per ISO 50001. Covers energy performance, objectives, audit results, and improvement opportunities.',
    module: 'ENERGY',
    category: 'MANAGEMENT_REVIEW',
    tags: ['management-review', 'iso-50001', 'energy-performance', 'enms'],
    isoClause: '9.3',
    fields: [
      { id: 'section_header', label: 'Review Details', type: 'section' },
      { id: 'review_date', label: 'Review Date', type: 'date', required: true, width: 'half', section: 'Review Details' },
      { id: 'chair', label: 'Chaired By', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'attendees', label: 'Attendees', type: 'textarea', required: true, placeholder: 'List all attendees...', validation: { maxLength: 1000 }, width: 'full', section: 'Review Details' },
      { id: 'section_inputs', label: 'Review Inputs', type: 'section' },
      { id: 'energy_performance', label: 'Energy Performance Summary', type: 'textarea', required: true, placeholder: 'Summary of energy performance against objectives and EnPIs...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Review Inputs' },
      { id: 'audit_results', label: 'Audit Results Summary', type: 'textarea', placeholder: 'Key findings from internal/external audits...', validation: { maxLength: 2000 }, width: 'full', section: 'Review Inputs' },
      { id: 'nonconformities', label: 'Nonconformities & Corrective Actions', type: 'textarea', placeholder: 'Status of open nonconformities...', validation: { maxLength: 2000 }, width: 'full', section: 'Review Inputs' },
      { id: 'section_outputs', label: 'Review Outputs', type: 'section' },
      { id: 'decisions', label: 'Decisions & Actions', type: 'textarea', required: true, placeholder: 'Key decisions and action items from the review...', validation: { minLength: 10, maxLength: 3000 }, width: 'full', section: 'Review Outputs' },
      { id: 'objectives_update', label: 'Updated Objectives & Targets', type: 'textarea', placeholder: 'Any changes to energy objectives or targets...', validation: { maxLength: 2000 }, width: 'full', section: 'Review Outputs' },
      { id: 'next_review', label: 'Next Review Date', type: 'date', required: true, width: 'half', section: 'Review Outputs' },
      { id: 'chair_signature', label: 'Chair Signature', type: 'signature', required: true, section: 'Review Outputs' },
    ],
  },
];
