import type { TemplateDefinition } from '../types';

export const energyTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-ENR-001',
    name: 'Energy Audit Report',
    description:
      'Comprehensive energy audit report covering energy consumption analysis, efficiency opportunities, and recommended improvements. Aligned with ISO 50001.',
    module: 'ENERGY',
    category: 'AUDIT',
    tags: ['energy-audit', 'iso-50001', 'efficiency', 'consumption'],
    isoClause: '6.3',
    fields: [
      { id: 'section_header', label: 'Audit Details', type: 'section' },
      { id: 'facility', label: 'Facility', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'auditor', label: 'Auditor', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'audit_date', label: 'Audit Date', type: 'date', required: true, width: 'half', section: 'Audit Details' },
      { id: 'period_covered', label: 'Period Covered', type: 'text', required: true, placeholder: 'e.g. Jan–Dec 2025', width: 'half', section: 'Audit Details' },
      { id: 'section_consumption', label: 'Energy Consumption', type: 'section' },
      {
        id: 'consumption',
        label: 'Consumption by Source',
        type: 'table',
        required: true,
        columns: [
          { id: 'source', label: 'Energy Source', type: 'select', required: true, options: [{ label: 'Electricity', value: 'electricity' }, { label: 'Natural Gas', value: 'natural_gas' }, { label: 'Diesel', value: 'diesel' }, { label: 'Solar', value: 'solar' }, { label: 'Other', value: 'other' }] },
          { id: 'consumption_kwh', label: 'Consumption (kWh)', type: 'number', required: true, validation: { min: 0 } },
          { id: 'cost', label: 'Cost', type: 'number', required: true, validation: { min: 0 } },
          { id: 'percentage', label: '% of Total', type: 'number', validation: { min: 0, max: 100 } },
        ],
        section: 'Energy Consumption',
      },
      { id: 'total_consumption', label: 'Total Consumption (kWh)', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Energy Consumption' },
      { id: 'section_opportunities', label: 'Improvement Opportunities', type: 'section' },
      {
        id: 'opportunities',
        label: 'Opportunities',
        type: 'table',
        required: true,
        columns: [
          { id: 'opportunity', label: 'Opportunity', type: 'text', required: true },
          { id: 'estimated_savings_kwh', label: 'Est. Savings (kWh/yr)', type: 'number', validation: { min: 0 } },
          { id: 'estimated_cost_saving', label: 'Est. Cost Saving/yr', type: 'number', validation: { min: 0 } },
          { id: 'investment', label: 'Investment Required', type: 'number', validation: { min: 0 } },
          { id: 'payback', label: 'Payback (months)', type: 'number', validation: { min: 0 } },
          { id: 'priority', label: 'Priority', type: 'select', required: true, options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
        ],
        section: 'Improvement Opportunities',
      },
      { id: 'summary', label: 'Audit Summary', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Improvement Opportunities' },
    ],
  },
  {
    code: 'TPL-ENR-002',
    name: 'Energy Savings Action Plan',
    description:
      'Action plan for implementing energy efficiency improvements with timeline, responsibilities, and expected savings.',
    module: 'ENERGY',
    category: 'PLANNING',
    tags: ['energy-savings', 'action-plan', 'efficiency', 'improvement'],
    fields: [
      { id: 'section_header', label: 'Plan Details', type: 'section' },
      { id: 'plan_title', label: 'Plan Title', type: 'text', required: true, width: 'full', section: 'Plan Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'Plan Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Plan Details' },
      { id: 'target_reduction', label: 'Target Reduction (%)', type: 'number', required: true, validation: { min: 0, max: 100 }, width: 'half', section: 'Plan Details' },
      { id: 'section_actions', label: 'Actions', type: 'section' },
      {
        id: 'actions',
        label: 'Action Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'start_date', label: 'Start Date', type: 'date', required: true },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          { id: 'expected_saving', label: 'Expected Saving (kWh/yr)', type: 'number', validation: { min: 0 } },
          { id: 'budget', label: 'Budget', type: 'number', validation: { min: 0 } },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Not Started', value: 'not_started' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }, { label: 'On Hold', value: 'on_hold' }] },
        ],
        section: 'Actions',
      },
    ],
  },
  {
    code: 'TPL-ENR-003',
    name: 'ISO 50001 Management Review',
    description:
      'Management review template for the energy management system per ISO 50001. Covers energy performance, objectives, audit results, and improvement opportunities.',
    module: 'ENERGY',
    category: 'MANAGEMENT_REVIEW',
    tags: ['management-review', 'iso-50001', 'energy-performance', 'enms'],
    isoClause: '9.3',
    fields: [
      { id: 'section_header', label: 'Review Details', type: 'section' },
      { id: 'review_date', label: 'Review Date', type: 'date', required: true, width: 'half', section: 'Review Details' },
      { id: 'chair', label: 'Chaired By', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'attendees', label: 'Attendees', type: 'textarea', required: true, placeholder: 'List all attendees...', validation: { maxLength: 1000 }, width: 'full', section: 'Review Details' },
      { id: 'section_inputs', label: 'Review Inputs', type: 'section' },
      { id: 'energy_performance', label: 'Energy Performance Summary', type: 'textarea', required: true, placeholder: 'Summary of energy performance against objectives and EnPIs...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Review Inputs' },
      { id: 'audit_results', label: 'Audit Results Summary', type: 'textarea', placeholder: 'Key findings from internal/external audits...', validation: { maxLength: 2000 }, width: 'full', section: 'Review Inputs' },
      { id: 'nonconformities', label: 'Nonconformities & Corrective Actions', type: 'textarea', placeholder: 'Status of open nonconformities...', validation: { maxLength: 2000 }, width: 'full', section: 'Review Inputs' },
      { id: 'section_outputs', label: 'Review Outputs', type: 'section' },
      { id: 'decisions', label: 'Decisions & Actions', type: 'textarea', required: true, placeholder: 'Key decisions and action items from the review...', validation: { minLength: 10, maxLength: 3000 }, width: 'full', section: 'Review Outputs' },
      { id: 'objectives_update', label: 'Updated Objectives & Targets', type: 'textarea', placeholder: 'Any changes to energy objectives or targets...', validation: { maxLength: 2000 }, width: 'full', section: 'Review Outputs' },
      { id: 'next_review', label: 'Next Review Date', type: 'date', required: true, width: 'half', section: 'Review Outputs' },
      { id: 'chair_signature', label: 'Chair Signature', type: 'signature', required: true, section: 'Review Outputs' },
    ],
  },
  {
    code: 'TPL-ENR-004',
    name: 'Significant Energy Use (SEU) Register',
    description:
      'Register for identifying and documenting Significant Energy Uses, establishing baseline consumption data, and defining monitoring plans. Required by ISO 50001 clause 6.3 for energy planning.',
    module: 'ENERGY',
    category: 'PLANNING',
    tags: ['seu', 'significant-energy-use', 'energy-planning', 'iso-50001', 'baseline'],
    isoClause: '6.3',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      { id: 'facility', label: 'Facility / Site', type: 'text', required: true, width: 'half', section: 'Register Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'Register Details' },
      { id: 'register_date', label: 'Register Date', type: 'date', required: true, width: 'half', section: 'Register Details' },
      { id: 'baseline_period', label: 'Baseline Period', type: 'text', required: true, placeholder: 'e.g. Jan–Dec 2025', width: 'half', section: 'Register Details', helpText: 'The reference period used to establish baseline energy consumption' },
      { id: 'total_site_consumption', label: 'Total Site Consumption (kWh/yr)', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Register Details' },
      { id: 'seu_threshold', label: 'SEU Threshold (%)', type: 'number', required: true, validation: { min: 0, max: 100 }, width: 'half', section: 'Register Details', helpText: 'Percentage of total consumption above which an energy use is deemed significant (typically 5-10%)' },
      { id: 'section_seus', label: 'Significant Energy Uses', type: 'section' },
      {
        id: 'seus',
        label: 'SEU Register',
        type: 'table',
        required: true,
        columns: [
          { id: 'seu_ref', label: 'SEU Ref', type: 'text', required: true, placeholder: 'e.g. SEU-001' },
          { id: 'description', label: 'Energy Use Description', type: 'text', required: true, placeholder: 'e.g. HVAC System — Building A' },
          { id: 'energy_source', label: 'Energy Source', type: 'select', required: true, options: [{ label: 'Electricity', value: 'electricity' }, { label: 'Natural Gas', value: 'natural_gas' }, { label: 'Diesel / Fuel Oil', value: 'diesel' }, { label: 'LPG', value: 'lpg' }, { label: 'Steam', value: 'steam' }, { label: 'Compressed Air', value: 'compressed_air' }, { label: 'Other', value: 'other' }] },
          { id: 'baseline_consumption', label: 'Baseline Consumption (kWh/yr)', type: 'number', required: true, validation: { min: 0 } },
          { id: 'percentage_of_total', label: '% of Total', type: 'number', required: true, validation: { min: 0, max: 100 } },
          { id: 'relevant_variables', label: 'Relevant Variables', type: 'text', required: true, placeholder: 'e.g. Outdoor temp, production volume, occupancy' },
          { id: 'current_efficiency', label: 'Current Efficiency / COP', type: 'text', placeholder: 'e.g. COP 3.2, 85% thermal efficiency' },
          { id: 'improvement_potential', label: 'Improvement Potential', type: 'select', required: true, options: [{ label: 'High (>15% saving)', value: 'high' }, { label: 'Medium (5-15% saving)', value: 'medium' }, { label: 'Low (<5% saving)', value: 'low' }] },
        ],
        section: 'Significant Energy Uses',
      },
      { id: 'section_monitoring', label: 'Monitoring Plan', type: 'section' },
      {
        id: 'monitoring_plan',
        label: 'SEU Monitoring Plan',
        type: 'table',
        required: true,
        columns: [
          { id: 'seu_ref', label: 'SEU Ref', type: 'text', required: true },
          { id: 'measurement_method', label: 'Measurement Method', type: 'select', required: true, options: [{ label: 'Sub-meter', value: 'sub_meter' }, { label: 'Main meter', value: 'main_meter' }, { label: 'Portable meter', value: 'portable' }, { label: 'Calculation / Estimate', value: 'calculation' }, { label: 'Invoice data', value: 'invoice' }] },
          { id: 'meter_ref', label: 'Meter Reference', type: 'text', placeholder: 'e.g. M-HVAC-01' },
          { id: 'frequency', label: 'Monitoring Frequency', type: 'select', required: true, options: [{ label: 'Real-time / AMR', value: 'realtime' }, { label: 'Daily', value: 'daily' }, { label: 'Weekly', value: 'weekly' }, { label: 'Monthly', value: 'monthly' }, { label: 'Quarterly', value: 'quarterly' }] },
          { id: 'responsible_person', label: 'Responsible Person', type: 'text', required: true },
          { id: 'calibration_status', label: 'Calibration Status', type: 'select', required: true, options: [{ label: 'In calibration', value: 'in_calibration' }, { label: 'Due for calibration', value: 'due' }, { label: 'Overdue', value: 'overdue' }, { label: 'N/A', value: 'na' }] },
        ],
        section: 'Monitoring Plan',
      },
      { id: 'section_normalisation', label: 'Normalisation & Baseline Adjustments', type: 'section' },
      { id: 'normalisation_factors', label: 'Normalisation Factors', type: 'textarea', required: true, placeholder: 'Describe the factors used to normalise energy data (e.g. heating degree days, production output, occupancy hours)...', validation: { minLength: 10, maxLength: 2000 }, width: 'full', section: 'Normalisation & Baseline Adjustments' },
      { id: 'baseline_adjustments', label: 'Baseline Adjustment Criteria', type: 'textarea', placeholder: 'Define conditions under which the baseline will be adjusted (e.g. significant process change, facility expansion, new equipment)...', validation: { maxLength: 2000 }, width: 'full', section: 'Normalisation & Baseline Adjustments', helpText: 'ISO 50001 requires baseline adjustment when relevant variables change significantly or there are major changes to the static factors' },
      { id: 'section_summary', label: 'Summary & Approval', type: 'section' },
      { id: 'summary_notes', label: 'Summary Notes', type: 'textarea', required: true, placeholder: 'Key observations and recommended improvement priorities...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Summary & Approval' },
      { id: 'next_review_date', label: 'Next Review Date', type: 'date', required: true, width: 'half', section: 'Summary & Approval' },
      { id: 'energy_manager_signature', label: 'Energy Manager Signature', type: 'signature', required: true, section: 'Summary & Approval' },
      { id: 'management_rep_signature', label: 'Management Representative Signature', type: 'signature', required: true, section: 'Summary & Approval' },
    ],
  },
  {
    code: 'TPL-ENR-005',
    name: 'Energy Performance Indicator (EnPI) Tracking',
    description:
      'Monthly and quarterly tracking of Energy Performance Indicators with trending analysis and variance commentary. Supports ISO 50001 clause 6.4 requirement to establish EnPIs and energy baselines for measuring energy performance improvement.',
    module: 'ENERGY',
    category: 'REPORTING',
    tags: ['enpi', 'energy-performance', 'kpi-tracking', 'iso-50001', 'trending', 'monitoring'],
    isoClause: '6.4',
    fields: [
      { id: 'section_header', label: 'Tracking Period Details', type: 'section' },
      { id: 'facility', label: 'Facility / Site', type: 'text', required: true, width: 'half', section: 'Tracking Period Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'Tracking Period Details' },
      { id: 'reporting_period', label: 'Reporting Period', type: 'text', required: true, placeholder: 'e.g. Q1 2026 (Jan–Mar)', width: 'half', section: 'Tracking Period Details' },
      { id: 'report_date', label: 'Report Date', type: 'date', required: true, width: 'half', section: 'Tracking Period Details' },
      { id: 'section_enpi_definitions', label: 'EnPI Definitions', type: 'section' },
      {
        id: 'enpi_definitions',
        label: 'Defined EnPIs',
        type: 'table',
        required: true,
        columns: [
          { id: 'enpi_ref', label: 'EnPI Ref', type: 'text', required: true, placeholder: 'e.g. EnPI-001' },
          { id: 'enpi_name', label: 'EnPI Name', type: 'text', required: true, placeholder: 'e.g. kWh per unit produced' },
          { id: 'unit', label: 'Unit of Measure', type: 'text', required: true, placeholder: 'e.g. kWh/unit, kWh/m2, GJ/tonne' },
          { id: 'scope', label: 'Scope / SEU', type: 'text', required: true, placeholder: 'e.g. Whole site, HVAC, Compressed air' },
          { id: 'baseline_value', label: 'Baseline Value', type: 'number', required: true, validation: { min: 0 } },
          { id: 'target_value', label: 'Target Value', type: 'number', required: true, validation: { min: 0 } },
          { id: 'improvement_direction', label: 'Improvement Direction', type: 'select', required: true, options: [{ label: 'Lower is better', value: 'lower' }, { label: 'Higher is better', value: 'higher' }] },
        ],
        section: 'EnPI Definitions',
        helpText: 'Define each EnPI with its baseline and target. Baselines should align with the SEU Register.',
      },
      { id: 'section_monthly_data', label: 'Monthly Data Collection', type: 'section' },
      {
        id: 'monthly_data',
        label: 'Monthly EnPI Data',
        type: 'table',
        required: true,
        columns: [
          { id: 'month', label: 'Month', type: 'select', required: true, options: [{ label: 'January', value: '01' }, { label: 'February', value: '02' }, { label: 'March', value: '03' }, { label: 'April', value: '04' }, { label: 'May', value: '05' }, { label: 'June', value: '06' }, { label: 'July', value: '07' }, { label: 'August', value: '08' }, { label: 'September', value: '09' }, { label: 'October', value: '10' }, { label: 'November', value: '11' }, { label: 'December', value: '12' }] },
          { id: 'enpi_ref', label: 'EnPI Ref', type: 'text', required: true },
          { id: 'energy_consumed', label: 'Energy Consumed (kWh)', type: 'number', required: true, validation: { min: 0 } },
          { id: 'normalisation_value', label: 'Normalisation Value', type: 'number', required: true, validation: { min: 0 }, placeholder: 'e.g. units produced, HDD, m2' },
          { id: 'enpi_actual', label: 'EnPI Actual', type: 'number', required: true, validation: { min: 0 } },
          { id: 'enpi_target', label: 'EnPI Target', type: 'number', required: true, validation: { min: 0 } },
          { id: 'variance_pct', label: 'Variance (%)', type: 'number', placeholder: 'Positive = above target' },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'On Track', value: 'on_track' }, { label: 'Marginal', value: 'marginal' }, { label: 'Off Track', value: 'off_track' }] },
        ],
        section: 'Monthly Data Collection',
      },
      { id: 'section_analysis', label: 'Trend Analysis & Commentary', type: 'section' },
      { id: 'trend_summary', label: 'Trend Summary', type: 'textarea', required: true, placeholder: 'Describe the overall EnPI trend for this period (improving / stable / deteriorating). Include comparison to baseline and previous periods...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Trend Analysis & Commentary' },
      { id: 'variance_commentary', label: 'Variance Commentary', type: 'textarea', required: true, placeholder: 'Explain significant variances from target. Include root causes (e.g. weather, production changes, equipment issues)...', validation: { minLength: 10, maxLength: 3000 }, width: 'full', section: 'Trend Analysis & Commentary' },
      {
        id: 'corrective_actions',
        label: 'Corrective Actions for Off-Track EnPIs',
        type: 'table',
        columns: [
          { id: 'enpi_ref', label: 'EnPI Ref', type: 'text', required: true },
          { id: 'action', label: 'Corrective Action', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          { id: 'expected_impact', label: 'Expected Impact', type: 'text', placeholder: 'e.g. 5% improvement in kWh/unit' },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Open', value: 'open' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Complete', value: 'complete' }] },
        ],
        section: 'Trend Analysis & Commentary',
      },
      { id: 'section_approval', label: 'Sign-Off', type: 'section' },
      { id: 'next_reporting_date', label: 'Next Reporting Date', type: 'date', required: true, width: 'half', section: 'Sign-Off' },
      { id: 'energy_manager_signature', label: 'Energy Manager Signature', type: 'signature', required: true, section: 'Sign-Off' },
    ],
  },
];
