import type { TemplateDefinition } from '../types';

export const esgTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-ESG-001',
    name: 'ESG Materiality Assessment',
    description:
      'Double materiality assessment for identifying and prioritising ESG topics that are material to the organisation and its stakeholders.',
    module: 'ESG',
    category: 'RISK_ASSESSMENT',
    tags: ['materiality', 'double-materiality', 'esg-topics', 'stakeholder'],
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      {
        id: 'assessment_title',
        label: 'Assessment Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Assessment Details',
      },
      {
        id: 'assessor',
        label: 'Assessor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      { id: 'section_topics', label: 'Material Topics', type: 'section' },
      {
        id: 'topics',
        label: 'ESG Topics',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'topic',
            label: 'Topic',
            type: 'text',
            required: true,
            placeholder: 'e.g. Carbon Emissions',
          },
          {
            id: 'pillar',
            label: 'Pillar',
            type: 'select',
            required: true,
            options: [
              { label: 'Environmental', value: 'environmental' },
              { label: 'Social', value: 'social' },
              { label: 'Governance', value: 'governance' },
            ],
          },
          {
            id: 'financial_impact',
            label: 'Financial Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'stakeholder_impact',
            label: 'Stakeholder Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'material',
            label: 'Material?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
          {
            id: 'action',
            label: 'Action / Response',
            type: 'text',
            placeholder: 'How will this topic be addressed?',
          },
        ],
        section: 'Material Topics',
      },
      {
        id: 'summary',
        label: 'Summary',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Material Topics',
      },
    ],
  },
  {
    code: 'TPL-ESG-002',
    name: 'Carbon Footprint Report',
    description:
      'Organisational carbon footprint report covering Scope 1, 2, and 3 emissions with reduction targets and action plans.',
    module: 'ESG',
    category: 'REPORTING',
    tags: ['carbon-footprint', 'ghg', 'emissions', 'scope-1-2-3', 'climate'],
    fields: [
      { id: 'section_header', label: 'Report Details', type: 'section' },
      {
        id: 'reporting_period',
        label: 'Reporting Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. FY 2025/26',
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      { id: 'section_emissions', label: 'Emissions Data', type: 'section' },
      {
        id: 'emissions',
        label: 'Emissions by Scope',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'scope',
            label: 'Scope',
            type: 'select',
            required: true,
            options: [
              { label: 'Scope 1 — Direct', value: 'scope_1' },
              { label: 'Scope 2 — Indirect (Energy)', value: 'scope_2' },
              { label: 'Scope 3 — Value Chain', value: 'scope_3' },
            ],
          },
          {
            id: 'source',
            label: 'Source',
            type: 'text',
            required: true,
            placeholder: 'e.g. Fleet vehicles, electricity',
          },
          { id: 'tco2e', label: 'tCO2e', type: 'number', required: true, validation: { min: 0 } },
          {
            id: 'methodology',
            label: 'Methodology',
            type: 'text',
            placeholder: 'Calculation method used',
          },
        ],
        section: 'Emissions Data',
      },
      {
        id: 'total_emissions',
        label: 'Total Emissions (tCO2e)',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Emissions Data',
      },
      { id: 'section_targets', label: 'Reduction Targets', type: 'section' },
      {
        id: 'reduction_target',
        label: 'Reduction Target',
        type: 'textarea',
        required: true,
        placeholder: 'e.g. 30% reduction by 2030 from 2025 baseline...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Reduction Targets',
      },
      {
        id: 'action_plan',
        label: 'Action Plan',
        type: 'textarea',
        required: true,
        placeholder: 'Key actions to achieve the reduction target...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Reduction Targets',
      },
    ],
  },
  {
    code: 'TPL-ESG-003',
    name: 'Stakeholder Engagement Log',
    description:
      'Log for recording ESG-related stakeholder engagement activities, feedback received, and actions taken in response.',
    module: 'ESG',
    category: 'GENERAL',
    tags: ['stakeholder-engagement', 'feedback', 'community', 'esg-reporting'],
    fields: [
      { id: 'section_header', label: 'Engagement Log', type: 'section' },
      {
        id: 'period',
        label: 'Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. Q1 2026',
        width: 'half',
        section: 'Engagement Log',
      },
      {
        id: 'coordinator',
        label: 'Coordinator',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Engagement Log',
      },
      { id: 'section_entries', label: 'Engagement Activities', type: 'section' },
      {
        id: 'engagements',
        label: 'Activities',
        type: 'table',
        required: true,
        columns: [
          { id: 'date', label: 'Date', type: 'date', required: true },
          {
            id: 'stakeholder',
            label: 'Stakeholder Group',
            type: 'text',
            required: true,
            placeholder: 'e.g. Local community, investors',
          },
          {
            id: 'method',
            label: 'Method',
            type: 'select',
            required: true,
            options: [
              { label: 'Meeting', value: 'meeting' },
              { label: 'Survey', value: 'survey' },
              { label: 'Workshop', value: 'workshop' },
              { label: 'Public Consultation', value: 'consultation' },
              { label: 'Report/Disclosure', value: 'report' },
            ],
          },
          { id: 'topic', label: 'Topic', type: 'text', required: true },
          {
            id: 'feedback',
            label: 'Key Feedback',
            type: 'text',
            placeholder: 'Summary of feedback received',
          },
          {
            id: 'action',
            label: 'Action Taken',
            type: 'text',
            placeholder: 'Response or follow-up',
          },
        ],
        section: 'Engagement Activities',
      },
    ],
  },
  {
    code: 'TPL-ESG-004',
    name: 'Social Impact Assessment',
    description:
      "Social impact assessment for evaluating the organisation's impact on communities, labour practices, human rights, and diversity & inclusion. Supports GRI 400-series social disclosures and UN SDG alignment.",
    module: 'ESG',
    category: 'RISK_ASSESSMENT',
    tags: [
      'social-impact',
      'community',
      'labour-practices',
      'diversity',
      'human-rights',
      'gri-400',
    ],
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      {
        id: 'assessment_title',
        label: 'Assessment Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Assessment Details',
      },
      {
        id: 'assessor',
        label: 'Assessor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'reporting_period',
        label: 'Reporting Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. FY 2025/26',
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'scope',
        label: 'Scope / Operations Covered',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the operations, sites, and geographies included in this assessment...',
        validation: { minLength: 10, maxLength: 2000 },
        width: 'full',
        section: 'Assessment Details',
      },
      { id: 'section_community', label: 'Community Impact', type: 'section' },
      {
        id: 'community_impacts',
        label: 'Community Impact Register',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'impact_area',
            label: 'Impact Area',
            type: 'select',
            required: true,
            options: [
              { label: 'Local employment', value: 'employment' },
              { label: 'Local procurement', value: 'procurement' },
              { label: 'Community investment', value: 'investment' },
              { label: 'Noise / Disruption', value: 'disruption' },
              { label: 'Infrastructure', value: 'infrastructure' },
              { label: 'Health impacts', value: 'health' },
              { label: 'Cultural heritage', value: 'cultural' },
              { label: 'Displacement / Resettlement', value: 'displacement' },
            ],
          },
          {
            id: 'description',
            label: 'Description',
            type: 'text',
            required: true,
            placeholder: 'Describe the specific impact',
          },
          {
            id: 'affected_group',
            label: 'Affected Community / Group',
            type: 'text',
            required: true,
          },
          {
            id: 'impact_type',
            label: 'Impact Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Positive', value: 'positive' },
              { label: 'Negative', value: 'negative' },
              { label: 'Mixed', value: 'mixed' },
            ],
          },
          {
            id: 'significance',
            label: 'Significance (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'mitigation_action',
            label: 'Mitigation / Enhancement Action',
            type: 'text',
            placeholder: 'Actions to mitigate negative or enhance positive impacts',
          },
        ],
        section: 'Community Impact',
      },
      {
        id: 'community_investment_amount',
        label: 'Total Community Investment',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Community Impact',
        helpText: 'Total monetary value of community investment programmes in the reporting period',
      },
      {
        id: 'local_hiring_pct',
        label: 'Local Hiring Rate (%)',
        type: 'number',
        validation: { min: 0, max: 100 },
        width: 'half',
        section: 'Community Impact',
        helpText: 'Percentage of workforce from local communities',
      },
      { id: 'section_labour', label: 'Labour Practices', type: 'section' },
      {
        id: 'labour_practices',
        label: 'Labour Practice Assessment',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'practice_area',
            label: 'Practice Area',
            type: 'select',
            required: true,
            options: [
              { label: 'Working hours', value: 'working_hours' },
              { label: 'Fair wages', value: 'wages' },
              { label: 'Freedom of association', value: 'association' },
              { label: 'Health & safety', value: 'health_safety' },
              { label: 'Forced labour', value: 'forced_labour' },
              { label: 'Child labour', value: 'child_labour' },
              { label: 'Grievance mechanisms', value: 'grievance' },
              { label: 'Training & development', value: 'training' },
              { label: 'Benefits & social protection', value: 'benefits' },
            ],
          },
          {
            id: 'compliance_status',
            label: 'Compliance Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Fully Compliant', value: 'compliant' },
              { label: 'Partially Compliant', value: 'partial' },
              { label: 'Non-Compliant', value: 'non_compliant' },
              { label: 'Not Assessed', value: 'not_assessed' },
            ],
          },
          {
            id: 'evidence',
            label: 'Evidence / Data',
            type: 'text',
            required: true,
            placeholder: 'e.g. Average hours = 38/wk, living wage audit completed',
          },
          {
            id: 'gap_identified',
            label: 'Gap Identified',
            type: 'text',
            placeholder: 'Describe any gap or risk',
          },
          {
            id: 'improvement_action',
            label: 'Improvement Action',
            type: 'text',
            placeholder: 'Planned corrective or preventive action',
          },
          { id: 'due_date', label: 'Due Date', type: 'date' },
        ],
        section: 'Labour Practices',
      },
      {
        id: 'grievances_reported',
        label: 'Grievances Reported in Period',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Labour Practices',
      },
      {
        id: 'grievances_resolved',
        label: 'Grievances Resolved',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Labour Practices',
      },
      { id: 'section_diversity', label: 'Diversity, Equity & Inclusion', type: 'section' },
      {
        id: 'diversity_data',
        label: 'Workforce Diversity Data',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Gender — Board level', value: 'gender_board' },
              { label: 'Gender — Senior management', value: 'gender_senior' },
              { label: 'Gender — All employees', value: 'gender_all' },
              { label: 'Age — Under 30', value: 'age_under_30' },
              { label: 'Age — 30-50', value: 'age_30_50' },
              { label: 'Age — Over 50', value: 'age_over_50' },
              { label: 'Ethnicity', value: 'ethnicity' },
              { label: 'Disability', value: 'disability' },
            ],
          },
          {
            id: 'total_headcount',
            label: 'Total Headcount',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'representation_pct',
            label: 'Representation (%)',
            type: 'number',
            required: true,
            validation: { min: 0, max: 100 },
          },
          {
            id: 'target_pct',
            label: 'Target (%)',
            type: 'number',
            validation: { min: 0, max: 100 },
          },
          {
            id: 'year_on_year_change',
            label: 'Year-on-Year Change (pp)',
            type: 'number',
            placeholder: 'Percentage points change',
          },
        ],
        section: 'Diversity, Equity & Inclusion',
      },
      {
        id: 'gender_pay_gap',
        label: 'Gender Pay Gap (%)',
        type: 'number',
        width: 'half',
        section: 'Diversity, Equity & Inclusion',
        helpText: 'Mean or median gender pay gap as percentage',
      },
      {
        id: 'dei_initiatives',
        label: 'DE&I Initiatives',
        type: 'textarea',
        required: true,
        placeholder: 'Describe active DE&I programmes, training, and targets...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Diversity, Equity & Inclusion',
      },
      { id: 'section_summary', label: 'Summary & Approval', type: 'section' },
      {
        id: 'key_risks',
        label: 'Key Social Risks Identified',
        type: 'textarea',
        required: true,
        placeholder: 'Summarise the top social risks and their potential impact...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Summary & Approval',
      },
      {
        id: 'overall_assessment',
        label: 'Overall Social Performance Rating',
        type: 'select',
        required: true,
        options: [
          { label: 'Strong — Leading practices, minimal gaps', value: 'strong' },
          { label: 'Adequate — Generally compliant, some improvements needed', value: 'adequate' },
          { label: 'Weak — Significant gaps requiring urgent action', value: 'weak' },
        ],
        width: 'half',
        section: 'Summary & Approval',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Summary & Approval',
      },
      {
        id: 'esg_director_signature',
        label: 'ESG Director Signature',
        type: 'signature',
        required: true,
        section: 'Summary & Approval',
      },
    ],
  },
  {
    code: 'TPL-ESG-005',
    name: 'TCFD Climate Risk Disclosure',
    description:
      'Climate-related financial disclosure template aligned with the Task Force on Climate-related Financial Disclosures (TCFD) framework. Covers the four core pillars: Governance, Strategy, Risk Management, and Metrics & Targets.',
    module: 'ESG',
    category: 'REPORTING',
    tags: [
      'tcfd',
      'climate-risk',
      'climate-disclosure',
      'governance',
      'strategy',
      'risk-management',
      'metrics',
    ],
    fields: [
      { id: 'section_header', label: 'Disclosure Details', type: 'section' },
      {
        id: 'organisation_name',
        label: 'Organisation Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Disclosure Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Disclosure Details',
      },
      {
        id: 'reporting_period',
        label: 'Reporting Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. FY 2025/26',
        width: 'half',
        section: 'Disclosure Details',
      },
      {
        id: 'disclosure_date',
        label: 'Disclosure Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Disclosure Details',
      },
      { id: 'section_governance', label: 'Pillar 1: Governance', type: 'section' },
      {
        id: 'board_oversight',
        label: 'Board Oversight of Climate-Related Risks',
        type: 'textarea',
        required: true,
        placeholder:
          "Describe the board's oversight of climate-related risks and opportunities. Include: frequency of board discussion, committees involved, how climate risks are reported to the board...",
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Pillar 1: Governance',
        helpText:
          "TCFD Governance (a): Describe the board's oversight of climate-related risks and opportunities",
      },
      {
        id: 'management_role',
        label: "Management's Role in Climate Risk",
        type: 'textarea',
        required: true,
        placeholder:
          "Describe management's role in assessing and managing climate-related risks. Include: organisational structure, reporting lines, specific management positions responsible...",
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Pillar 1: Governance',
        helpText:
          "TCFD Governance (b): Describe management's role in assessing and managing climate-related risks and opportunities",
      },
      { id: 'section_strategy', label: 'Pillar 2: Strategy', type: 'section' },
      {
        id: 'climate_risks',
        label: 'Climate-Related Risks',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'risk_type',
            label: 'Risk Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Transition — Policy & Legal', value: 'transition_policy' },
              { label: 'Transition — Technology', value: 'transition_technology' },
              { label: 'Transition — Market', value: 'transition_market' },
              { label: 'Transition — Reputation', value: 'transition_reputation' },
              { label: 'Physical — Acute', value: 'physical_acute' },
              { label: 'Physical — Chronic', value: 'physical_chronic' },
            ],
          },
          { id: 'description', label: 'Risk Description', type: 'text', required: true },
          {
            id: 'time_horizon',
            label: 'Time Horizon',
            type: 'select',
            required: true,
            options: [
              { label: 'Short-term (0-2 years)', value: 'short' },
              { label: 'Medium-term (2-5 years)', value: 'medium' },
              { label: 'Long-term (5-30 years)', value: 'long' },
            ],
          },
          {
            id: 'likelihood',
            label: 'Likelihood (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'financial_impact',
            label: 'Potential Financial Impact',
            type: 'select',
            required: true,
            options: [
              { label: 'High (>5% revenue)', value: 'high' },
              { label: 'Medium (1-5% revenue)', value: 'medium' },
              { label: 'Low (<1% revenue)', value: 'low' },
            ],
          },
          { id: 'mitigation', label: 'Mitigation Strategy', type: 'text', required: true },
        ],
        section: 'Pillar 2: Strategy',
      },
      {
        id: 'climate_opportunities',
        label: 'Climate-Related Opportunities',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'opportunity_type',
            label: 'Opportunity Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Resource efficiency', value: 'resource_efficiency' },
              { label: 'Energy source', value: 'energy_source' },
              { label: 'Products & services', value: 'products_services' },
              { label: 'Markets', value: 'markets' },
              { label: 'Resilience', value: 'resilience' },
            ],
          },
          { id: 'description', label: 'Opportunity Description', type: 'text', required: true },
          {
            id: 'time_horizon',
            label: 'Time Horizon',
            type: 'select',
            required: true,
            options: [
              { label: 'Short-term (0-2 years)', value: 'short' },
              { label: 'Medium-term (2-5 years)', value: 'medium' },
              { label: 'Long-term (5-30 years)', value: 'long' },
            ],
          },
          {
            id: 'financial_impact',
            label: 'Potential Financial Impact',
            type: 'select',
            required: true,
            options: [
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          { id: 'action_plan', label: 'Action Plan', type: 'text', required: true },
        ],
        section: 'Pillar 2: Strategy',
      },
      {
        id: 'scenario_analysis',
        label: 'Scenario Analysis',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the climate scenarios used to assess strategic resilience (e.g. 1.5C, 2C, 4C pathways). Include: scenarios modelled, key assumptions, time horizons, impact on business strategy...',
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Pillar 2: Strategy',
        helpText:
          "TCFD Strategy (c): Describe the resilience of the organisation's strategy under different climate-related scenarios, including a 2C or lower scenario",
      },
      { id: 'section_risk_mgmt', label: 'Pillar 3: Risk Management', type: 'section' },
      {
        id: 'risk_identification_process',
        label: 'Risk Identification & Assessment Process',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the processes for identifying and assessing climate-related risks. Include: risk assessment methodology, frequency, data sources, materiality thresholds...',
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Pillar 3: Risk Management',
        helpText:
          "TCFD Risk Management (a): Describe the organisation's processes for identifying and assessing climate-related risks",
      },
      {
        id: 'risk_management_process',
        label: 'Risk Management & Mitigation Process',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe how climate-related risks are managed and mitigated. Include: risk response strategies, escalation procedures, monitoring mechanisms...',
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Pillar 3: Risk Management',
        helpText:
          "TCFD Risk Management (b): Describe the organisation's processes for managing climate-related risks",
      },
      {
        id: 'integration_with_erm',
        label: 'Integration with Enterprise Risk Management',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe how climate risk management is integrated into the overall enterprise risk management framework...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Pillar 3: Risk Management',
        helpText:
          'TCFD Risk Management (c): Describe how processes for identifying, assessing, and managing climate-related risks are integrated into overall risk management',
      },
      { id: 'section_metrics', label: 'Pillar 4: Metrics & Targets', type: 'section' },
      {
        id: 'metrics',
        label: 'Climate-Related Metrics',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'metric_name',
            label: 'Metric',
            type: 'text',
            required: true,
            placeholder: 'e.g. Scope 1 emissions, Energy intensity',
          },
          {
            id: 'unit',
            label: 'Unit',
            type: 'text',
            required: true,
            placeholder: 'e.g. tCO2e, kWh/revenue',
          },
          { id: 'baseline_year', label: 'Baseline Year', type: 'text', required: true },
          {
            id: 'baseline_value',
            label: 'Baseline Value',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'current_value',
            label: 'Current Period Value',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'change_pct',
            label: 'Change (%)',
            type: 'number',
            placeholder: 'Negative = reduction',
          },
          {
            id: 'methodology',
            label: 'Methodology',
            type: 'text',
            placeholder: 'e.g. GHG Protocol, location-based',
          },
        ],
        section: 'Pillar 4: Metrics & Targets',
      },
      {
        id: 'targets',
        label: 'Climate Targets',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'target_description',
            label: 'Target',
            type: 'text',
            required: true,
            placeholder: 'e.g. Net zero by 2050',
          },
          {
            id: 'target_type',
            label: 'Target Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Absolute reduction', value: 'absolute' },
              { label: 'Intensity reduction', value: 'intensity' },
              { label: 'Renewable energy', value: 'renewable' },
              { label: 'Net zero / Carbon neutral', value: 'net_zero' },
              { label: 'Science-based target', value: 'sbt' },
            ],
          },
          { id: 'target_year', label: 'Target Year', type: 'text', required: true },
          {
            id: 'target_value',
            label: 'Target Value',
            type: 'text',
            required: true,
            placeholder: 'e.g. 50% reduction, 100% renewable',
          },
          {
            id: 'progress_pct',
            label: 'Progress (%)',
            type: 'number',
            required: true,
            validation: { min: 0, max: 100 },
          },
          {
            id: 'on_track',
            label: 'On Track?',
            type: 'select',
            required: true,
            options: [
              { label: 'On Track', value: 'on_track' },
              { label: 'At Risk', value: 'at_risk' },
              { label: 'Off Track', value: 'off_track' },
            ],
          },
        ],
        section: 'Pillar 4: Metrics & Targets',
      },
      {
        id: 'scope3_commentary',
        label: 'Scope 3 Value Chain Emissions Commentary',
        type: 'textarea',
        placeholder:
          'Provide commentary on Scope 3 emission categories measured, methodology, and data quality. Identify the most material Scope 3 categories for your organisation...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Pillar 4: Metrics & Targets',
        helpText:
          'TCFD recommends disclosing Scope 1, Scope 2 and, if appropriate, Scope 3 GHG emissions and related risks',
      },
      { id: 'section_approval', label: 'Disclosure Approval', type: 'section' },
      {
        id: 'approval_notes',
        label: 'Approval Notes',
        type: 'textarea',
        placeholder: 'Any additional notes or caveats for this disclosure...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Disclosure Approval',
      },
      {
        id: 'prepared_by_signature',
        label: 'Prepared By Signature',
        type: 'signature',
        required: true,
        section: 'Disclosure Approval',
      },
      {
        id: 'cfo_signature',
        label: 'CFO / Finance Director Signature',
        type: 'signature',
        required: true,
        section: 'Disclosure Approval',
      },
      {
        id: 'board_approval_signature',
        label: 'Board Approval Signature',
        type: 'signature',
        required: true,
        section: 'Disclosure Approval',
      },
    ],
  },
];
