import type { TemplateDefinition } from '../types';

export const fieldServiceTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-FSV-001',
    name: 'Field Service Report',
    description:
      'On-site service report documenting work performed, equipment status, parts used, and customer acknowledgement.',
    module: 'FIELD_SERVICE',
    category: 'REPORTING',
    tags: ['field-service', 'service-report', 'on-site', 'customer'],
    fields: [
      { id: 'section_header', label: 'Service Details', type: 'section' },
      {
        id: 'service_order',
        label: 'Service Order #',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Details',
      },
      {
        id: 'customer_name',
        label: 'Customer Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Details',
      },
      {
        id: 'site_address',
        label: 'Site Address',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Service Details',
      },
      {
        id: 'technician',
        label: 'Technician',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Details',
      },
      {
        id: 'date',
        label: 'Service Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Service Details',
      },
      {
        id: 'arrival_time',
        label: 'Arrival Time',
        type: 'text',
        required: true,
        placeholder: 'e.g. 09:30',
        width: 'half',
        section: 'Service Details',
      },
      {
        id: 'departure_time',
        label: 'Departure Time',
        type: 'text',
        required: true,
        placeholder: 'e.g. 14:00',
        width: 'half',
        section: 'Service Details',
      },
      { id: 'section_work', label: 'Work Performed', type: 'section' },
      {
        id: 'problem_reported',
        label: 'Problem Reported',
        type: 'textarea',
        required: true,
        validation: { minLength: 10, maxLength: 2000 },
        width: 'full',
        section: 'Work Performed',
      },
      {
        id: 'work_performed',
        label: 'Work Performed',
        type: 'textarea',
        required: true,
        validation: { minLength: 10, maxLength: 3000 },
        width: 'full',
        section: 'Work Performed',
      },
      {
        id: 'parts_used',
        label: 'Parts Used',
        type: 'table',
        columns: [
          { id: 'part', label: 'Part', type: 'text', required: true },
          { id: 'quantity', label: 'Qty', type: 'number', required: true, validation: { min: 1 } },
          { id: 'serial', label: 'Serial #', type: 'text' },
        ],
        section: 'Work Performed',
      },
      {
        id: 'resolution',
        label: 'Resolution Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Resolved', value: 'resolved' },
          { label: 'Partial — Follow-Up Required', value: 'partial' },
          { label: 'Unresolved — Escalated', value: 'escalated' },
        ],
        width: 'half',
        section: 'Work Performed',
      },
      { id: 'section_signoff', label: 'Sign-Off', type: 'section' },
      {
        id: 'technician_signature',
        label: 'Technician Signature',
        type: 'signature',
        required: true,
        section: 'Sign-Off',
      },
      {
        id: 'customer_signature',
        label: 'Customer Signature',
        type: 'signature',
        required: true,
        section: 'Sign-Off',
      },
    ],
  },
  {
    code: 'TPL-FSV-002',
    name: 'Site Inspection Checklist',
    description:
      'Pre-service or periodic site inspection checklist for evaluating equipment condition, safety compliance, and environment at customer sites.',
    module: 'FIELD_SERVICE',
    category: 'INSPECTION',
    tags: ['site-inspection', 'checklist', 'field', 'safety'],
    fields: [
      { id: 'section_header', label: 'Inspection Details', type: 'section' },
      {
        id: 'site_name',
        label: 'Site Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Inspection Details',
      },
      {
        id: 'inspector',
        label: 'Inspector',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Inspection Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Inspection Details',
      },
      { id: 'section_checks', label: 'Inspection Items', type: 'section' },
      {
        id: 'checks',
        label: 'Checklist',
        type: 'table',
        required: true,
        columns: [
          { id: 'item', label: 'Item', type: 'text', required: true },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Equipment', value: 'equipment' },
              { label: 'Safety', value: 'safety' },
              { label: 'Environment', value: 'environment' },
              { label: 'Access', value: 'access' },
            ],
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
              { label: 'N/A', value: 'na' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Inspection Items',
      },
      {
        id: 'overall_status',
        label: 'Overall Site Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Acceptable', value: 'acceptable' },
          { label: 'Needs Attention', value: 'attention' },
          { label: 'Unacceptable', value: 'unacceptable' },
        ],
        width: 'half',
        section: 'Inspection Items',
      },
      {
        id: 'actions_required',
        label: 'Actions Required',
        type: 'textarea',
        placeholder: 'Describe any corrective actions needed...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Inspection Items',
      },
      {
        id: 'inspector_signature',
        label: 'Inspector Signature',
        type: 'signature',
        required: true,
        section: 'Inspection Items',
      },
    ],
  },
  {
    code: 'TPL-FSV-003',
    name: 'Customer Sign-Off Form',
    description:
      'Formal customer sign-off form for confirming service completion, satisfaction, and any outstanding items or follow-up requirements.',
    module: 'FIELD_SERVICE',
    category: 'GENERAL',
    tags: ['sign-off', 'customer-acceptance', 'completion', 'satisfaction'],
    fields: [
      { id: 'section_header', label: 'Service Completion', type: 'section' },
      {
        id: 'service_order',
        label: 'Service Order #',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Completion',
      },
      {
        id: 'customer_name',
        label: 'Customer Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Completion',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Service Completion',
      },
      {
        id: 'work_summary',
        label: 'Work Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Brief summary of work completed...',
        validation: { minLength: 10, maxLength: 2000 },
        width: 'full',
        section: 'Service Completion',
      },
      { id: 'section_acceptance', label: 'Customer Acceptance', type: 'section' },
      {
        id: 'work_completed',
        label: 'Work Completed to Satisfaction?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'Partially', value: 'partial' },
        ],
        width: 'half',
        section: 'Customer Acceptance',
      },
      {
        id: 'satisfaction_rating',
        label: 'Satisfaction Rating',
        type: 'rating',
        required: true,
        validation: { min: 1, max: 5 },
        section: 'Customer Acceptance',
      },
      {
        id: 'outstanding_items',
        label: 'Outstanding Items',
        type: 'textarea',
        placeholder: 'Any items remaining or follow-up required...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Customer Acceptance',
      },
      {
        id: 'customer_comments',
        label: 'Customer Comments',
        type: 'textarea',
        placeholder: 'Additional comments or feedback...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Customer Acceptance',
      },
      {
        id: 'customer_signature',
        label: 'Customer Signature',
        type: 'signature',
        required: true,
        section: 'Customer Acceptance',
      },
      {
        id: 'technician_signature',
        label: 'Technician Signature',
        type: 'signature',
        required: true,
        section: 'Customer Acceptance',
      },
    ],
  },
  {
    code: 'TPL-FSV-004',
    name: 'Equipment Commissioning Checklist',
    description:
      'Comprehensive commissioning checklist for verifying newly installed or overhauled equipment is fit for service. Covers pre-commissioning inspections, functional tests, safety verification, documentation review, and formal handover to operations.',
    module: 'FIELD_SERVICE',
    category: 'INSPECTION',
    tags: ['commissioning', 'equipment', 'verification', 'handover', 'testing'],
    fields: [
      { id: 'section_header', label: 'Commissioning Details', type: 'section' },
      {
        id: 'commission_ref',
        label: 'Commissioning Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. COM-2026-001',
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'equipment_name',
        label: 'Equipment Name / Model',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'serial_number',
        label: 'Serial Number',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'asset_tag',
        label: 'Asset Tag',
        type: 'text',
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'location',
        label: 'Installation Location',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Commissioning Details',
      },
      {
        id: 'manufacturer',
        label: 'Manufacturer',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'commissioning_date',
        label: 'Commissioning Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'lead_technician',
        label: 'Lead Technician',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'project_reference',
        label: 'Project / Work Order Reference',
        type: 'text',
        width: 'half',
        section: 'Commissioning Details',
      },
      {
        id: 'section_pre_checks',
        label: 'Pre-Commissioning Checks',
        type: 'section',
        helpText:
          'Verify physical installation, connections, and documentation before powering on.',
      },
      {
        id: 'pre_commission_checks',
        label: 'Pre-Commissioning Checks',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'check_item',
            label: 'Check Item',
            type: 'text',
            required: true,
            placeholder: 'e.g. Electrical connections verified',
          },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Mechanical', value: 'mechanical' },
              { label: 'Electrical', value: 'electrical' },
              { label: 'Hydraulic / Pneumatic', value: 'hydraulic_pneumatic' },
              { label: 'Controls / Software', value: 'controls' },
              { label: 'Safety Systems', value: 'safety' },
              { label: 'Documentation', value: 'documentation' },
            ],
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
              { label: 'N/A', value: 'na' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Pre-Commissioning Checks',
      },
      {
        id: 'section_functional',
        label: 'Functional Testing',
        type: 'section',
        helpText: 'Record results of each functional test performed during commissioning.',
      },
      {
        id: 'functional_tests',
        label: 'Functional Test Results',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'test_name',
            label: 'Test Name',
            type: 'text',
            required: true,
            placeholder: 'e.g. Full load test',
          },
          {
            id: 'test_procedure',
            label: 'Procedure Ref',
            type: 'text',
            placeholder: 'e.g. TP-001',
          },
          { id: 'expected_result', label: 'Expected Result', type: 'text', required: true },
          { id: 'actual_result', label: 'Actual Result', type: 'text', required: true },
          {
            id: 'pass_fail',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
              { label: 'Conditional Pass', value: 'conditional' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Functional Testing',
      },
      {
        id: 'section_safety',
        label: 'Safety Verification',
        type: 'section',
        helpText:
          'Confirm all safety systems, guards, and emergency stops are functioning correctly.',
      },
      {
        id: 'safety_checks',
        label: 'Safety Checks',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'safety_item',
            label: 'Safety Item',
            type: 'text',
            required: true,
            placeholder: 'e.g. Emergency stop button',
          },
          { id: 'test_method', label: 'Test Method', type: 'text', required: true },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Safety Verification',
      },
      {
        id: 'section_documentation',
        label: 'Documentation Review',
        type: 'section',
        helpText: 'Verify all required documentation has been provided and is complete.',
      },
      {
        id: 'documentation_checklist',
        label: 'Documentation Checklist',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'document',
            label: 'Document',
            type: 'select',
            required: true,
            options: [
              { label: 'O&M Manual', value: 'om_manual' },
              { label: 'Wiring Diagrams', value: 'wiring_diagrams' },
              { label: 'P&ID / Schematics', value: 'schematics' },
              { label: 'Calibration Certificates', value: 'calibration_certs' },
              { label: 'Test Certificates', value: 'test_certs' },
              { label: 'Warranty Documentation', value: 'warranty' },
              { label: 'Spare Parts List', value: 'spare_parts' },
              { label: 'Risk Assessment', value: 'risk_assessment' },
            ],
          },
          {
            id: 'provided',
            label: 'Provided',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No — Outstanding', value: 'no' },
              { label: 'N/A', value: 'na' },
            ],
          },
          {
            id: 'reference',
            label: 'Document Reference',
            type: 'text',
            placeholder: 'Document number or location',
          },
        ],
        section: 'Documentation Review',
      },
      {
        id: 'section_snagging',
        label: 'Snagging / Punch List',
        type: 'section',
        helpText:
          'Record any outstanding items or defects that must be resolved before or after handover.',
      },
      {
        id: 'snagging_items',
        label: 'Snagging Items',
        type: 'table',
        columns: [
          { id: 'item_description', label: 'Description', type: 'text', required: true },
          {
            id: 'severity',
            label: 'Severity',
            type: 'select',
            required: true,
            options: [
              { label: 'Critical — Blocks Handover', value: 'critical' },
              { label: 'Major — Must Fix Within 30 Days', value: 'major' },
              { label: 'Minor — Cosmetic / Low Impact', value: 'minor' },
            ],
          },
          { id: 'assigned_to', label: 'Assigned To', type: 'text', required: true },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Closed', value: 'closed' },
            ],
          },
        ],
        section: 'Snagging / Punch List',
      },
      { id: 'section_handover', label: 'Handover & Sign-Off', type: 'section' },
      {
        id: 'commissioning_outcome',
        label: 'Commissioning Outcome',
        type: 'select',
        required: true,
        options: [
          { label: 'Accepted — Fit for Service', value: 'accepted' },
          { label: 'Conditionally Accepted — Snagging Items Outstanding', value: 'conditional' },
          { label: 'Rejected — Critical Failures', value: 'rejected' },
        ],
        width: 'half',
        section: 'Handover & Sign-Off',
      },
      {
        id: 'handover_notes',
        label: 'Handover Notes',
        type: 'textarea',
        placeholder:
          'Special operating instructions, maintenance schedules, or training requirements...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Handover & Sign-Off',
      },
      {
        id: 'commissioning_engineer_signature',
        label: 'Commissioning Engineer Signature',
        type: 'signature',
        required: true,
        section: 'Handover & Sign-Off',
      },
      {
        id: 'operations_manager_signature',
        label: 'Operations Manager Signature',
        type: 'signature',
        required: true,
        section: 'Handover & Sign-Off',
      },
      {
        id: 'customer_representative_signature',
        label: 'Customer Representative Signature',
        type: 'signature',
        required: true,
        section: 'Handover & Sign-Off',
      },
    ],
  },
  {
    code: 'TPL-FSV-005',
    name: 'Customer Satisfaction Survey',
    description:
      'Post-service customer satisfaction survey capturing overall service quality, technician performance, response time, communication, and improvement suggestions. Used to monitor service standards and drive continuous improvement.',
    module: 'FIELD_SERVICE',
    category: 'GENERAL',
    tags: ['customer-satisfaction', 'survey', 'feedback', 'service-quality', 'NPS'],
    fields: [
      { id: 'section_header', label: 'Service Reference', type: 'section' },
      {
        id: 'service_order',
        label: 'Service Order #',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'customer_name',
        label: 'Customer Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'customer_contact',
        label: 'Contact Person',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'customer_email',
        label: 'Contact Email',
        type: 'text',
        placeholder: 'For follow-up if required',
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'service_date',
        label: 'Service Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'survey_date',
        label: 'Survey Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'technician_name',
        label: 'Technician Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'service_type',
        label: 'Service Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Installation', value: 'installation' },
          { label: 'Repair', value: 'repair' },
          { label: 'Preventive Maintenance', value: 'preventive_maintenance' },
          { label: 'Commissioning', value: 'commissioning' },
          { label: 'Inspection', value: 'inspection' },
          { label: 'Emergency Call-Out', value: 'emergency' },
        ],
        width: 'half',
        section: 'Service Reference',
      },
      {
        id: 'section_ratings',
        label: 'Service Quality Ratings',
        type: 'section',
        helpText: 'Rate each aspect of the service on a scale of 1 (Poor) to 5 (Excellent).',
      },
      {
        id: 'overall_satisfaction',
        label: 'Overall Satisfaction',
        type: 'rating',
        required: true,
        validation: { min: 1, max: 5 },
        section: 'Service Quality Ratings',
      },
      {
        id: 'response_time',
        label: 'Response Time',
        type: 'rating',
        required: true,
        validation: { min: 1, max: 5 },
        section: 'Service Quality Ratings',
        helpText: 'How quickly was the service scheduled and the technician on site?',
      },
      {
        id: 'work_quality',
        label: 'Quality of Work',
        type: 'rating',
        required: true,
        validation: { min: 1, max: 5 },
        section: 'Service Quality Ratings',
        helpText: 'Was the issue resolved effectively and to a high standard?',
      },
      {
        id: 'communication',
        label: 'Communication',
        type: 'rating',
        required: true,
        validation: { min: 1, max: 5 },
        section: 'Service Quality Ratings',
        helpText: 'Were you kept informed throughout the service process?',
      },
      {
        id: 'professionalism',
        label: 'Professionalism',
        type: 'rating',
        required: true,
        validation: { min: 1, max: 5 },
        section: 'Service Quality Ratings',
        helpText: 'Was the technician courteous, punctual, and professional?',
      },
      {
        id: 'site_cleanliness',
        label: 'Site Cleanliness',
        type: 'rating',
        required: true,
        validation: { min: 1, max: 5 },
        section: 'Service Quality Ratings',
        helpText: 'Was the work area left clean and tidy after service?',
      },
      { id: 'section_technician', label: 'Technician Assessment', type: 'section' },
      {
        id: 'technician_assessment',
        label: 'Technician Assessment',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'criteria',
            label: 'Criteria',
            type: 'select',
            required: true,
            options: [
              { label: 'Technical Knowledge', value: 'technical_knowledge' },
              { label: 'Problem Solving', value: 'problem_solving' },
              { label: 'Safety Awareness', value: 'safety_awareness' },
              { label: 'Explanation of Work', value: 'explanation' },
              { label: 'Time Management', value: 'time_management' },
            ],
          },
          {
            id: 'rating',
            label: 'Rating (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          { id: 'comments', label: 'Comments', type: 'text', placeholder: 'Specific feedback' },
        ],
        section: 'Technician Assessment',
      },
      { id: 'section_nps', label: 'Recommendation', type: 'section' },
      {
        id: 'nps_score',
        label: 'How likely are you to recommend our service? (0-10)',
        type: 'number',
        required: true,
        validation: { min: 0, max: 10 },
        width: 'half',
        section: 'Recommendation',
        helpText: '0 = Not at all likely, 10 = Extremely likely (Net Promoter Score)',
      },
      {
        id: 'would_use_again',
        label: 'Would you use our service again?',
        type: 'select',
        required: true,
        options: [
          { label: 'Definitely', value: 'definitely' },
          { label: 'Probably', value: 'probably' },
          { label: 'Not Sure', value: 'not_sure' },
          { label: 'Probably Not', value: 'probably_not' },
          { label: 'Definitely Not', value: 'definitely_not' },
        ],
        width: 'half',
        section: 'Recommendation',
      },
      { id: 'section_comments', label: 'Additional Feedback', type: 'section' },
      {
        id: 'positive_feedback',
        label: 'What did we do well?',
        type: 'textarea',
        placeholder: 'Tell us what you were pleased with...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Additional Feedback',
      },
      {
        id: 'improvement_areas',
        label: 'What could we improve?',
        type: 'textarea',
        placeholder: 'Suggestions for improvement...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Additional Feedback',
      },
      {
        id: 'additional_comments',
        label: 'Any other comments?',
        type: 'textarea',
        placeholder: 'Anything else you would like us to know...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Additional Feedback',
      },
      {
        id: 'follow_up_requested',
        label: 'Would you like a follow-up call?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ],
        width: 'half',
        section: 'Additional Feedback',
      },
      {
        id: 'customer_signature',
        label: 'Customer Signature',
        type: 'signature',
        required: true,
        section: 'Additional Feedback',
      },
    ],
  },
];
