import type { TemplateDefinition } from '../types';

export const fieldServiceTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-FSV-001',
    name: 'Field Service Report',
    description:
      'On-site service report documenting work performed, equipment status, parts used, and customer acknowledgement.',
    module: 'FIELD_SERVICE',
    category: 'REPORTING',
    tags: ['field-service', 'service-report', 'on-site', 'customer'],
    fields: [
      { id: 'section_header', label: 'Service Details', type: 'section' },
      { id: 'service_order', label: 'Service Order #', type: 'text', required: true, width: 'half', section: 'Service Details' },
      { id: 'customer_name', label: 'Customer Name', type: 'text', required: true, width: 'half', section: 'Service Details' },
      { id: 'site_address', label: 'Site Address', type: 'text', required: true, width: 'full', section: 'Service Details' },
      { id: 'technician', label: 'Technician', type: 'text', required: true, width: 'half', section: 'Service Details' },
      { id: 'date', label: 'Service Date', type: 'date', required: true, width: 'half', section: 'Service Details' },
      { id: 'arrival_time', label: 'Arrival Time', type: 'text', required: true, placeholder: 'e.g. 09:30', width: 'half', section: 'Service Details' },
      { id: 'departure_time', label: 'Departure Time', type: 'text', required: true, placeholder: 'e.g. 14:00', width: 'half', section: 'Service Details' },
      { id: 'section_work', label: 'Work Performed', type: 'section' },
      { id: 'problem_reported', label: 'Problem Reported', type: 'textarea', required: true, validation: { minLength: 10, maxLength: 2000 }, width: 'full', section: 'Work Performed' },
      { id: 'work_performed', label: 'Work Performed', type: 'textarea', required: true, validation: { minLength: 10, maxLength: 3000 }, width: 'full', section: 'Work Performed' },
      {
        id: 'parts_used',
        label: 'Parts Used',
        type: 'table',
        columns: [
          { id: 'part', label: 'Part', type: 'text', required: true },
          { id: 'quantity', label: 'Qty', type: 'number', required: true, validation: { min: 1 } },
          { id: 'serial', label: 'Serial #', type: 'text' },
        ],
        section: 'Work Performed',
      },
      { id: 'resolution', label: 'Resolution Status', type: 'select', required: true, options: [{ label: 'Resolved', value: 'resolved' }, { label: 'Partial — Follow-Up Required', value: 'partial' }, { label: 'Unresolved — Escalated', value: 'escalated' }], width: 'half', section: 'Work Performed' },
      { id: 'section_signoff', label: 'Sign-Off', type: 'section' },
      { id: 'technician_signature', label: 'Technician Signature', type: 'signature', required: true, section: 'Sign-Off' },
      { id: 'customer_signature', label: 'Customer Signature', type: 'signature', required: true, section: 'Sign-Off' },
    ],
  },
  {
    code: 'TPL-FSV-002',
    name: 'Site Inspection Checklist',
    description:
      'Pre-service or periodic site inspection checklist for evaluating equipment condition, safety compliance, and environment at customer sites.',
    module: 'FIELD_SERVICE',
    category: 'INSPECTION',
    tags: ['site-inspection', 'checklist', 'field', 'safety'],
    fields: [
      { id: 'section_header', label: 'Inspection Details', type: 'section' },
      { id: 'site_name', label: 'Site Name', type: 'text', required: true, width: 'half', section: 'Inspection Details' },
      { id: 'inspector', label: 'Inspector', type: 'text', required: true, width: 'half', section: 'Inspection Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Inspection Details' },
      { id: 'section_checks', label: 'Inspection Items', type: 'section' },
      {
        id: 'checks',
        label: 'Checklist',
        type: 'table',
        required: true,
        columns: [
          { id: 'item', label: 'Item', type: 'text', required: true },
          { id: 'category', label: 'Category', type: 'select', required: true, options: [{ label: 'Equipment', value: 'equipment' }, { label: 'Safety', value: 'safety' }, { label: 'Environment', value: 'environment' }, { label: 'Access', value: 'access' }] },
          { id: 'result', label: 'Result', type: 'select', required: true, options: [{ label: 'Pass', value: 'pass' }, { label: 'Fail', value: 'fail' }, { label: 'N/A', value: 'na' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Inspection Items',
      },
      { id: 'overall_status', label: 'Overall Site Status', type: 'select', required: true, options: [{ label: 'Acceptable', value: 'acceptable' }, { label: 'Needs Attention', value: 'attention' }, { label: 'Unacceptable', value: 'unacceptable' }], width: 'half', section: 'Inspection Items' },
      { id: 'actions_required', label: 'Actions Required', type: 'textarea', placeholder: 'Describe any corrective actions needed...', validation: { maxLength: 2000 }, width: 'full', section: 'Inspection Items' },
      { id: 'inspector_signature', label: 'Inspector Signature', type: 'signature', required: true, section: 'Inspection Items' },
    ],
  },
  {
    code: 'TPL-FSV-003',
    name: 'Customer Sign-Off Form',
    description:
      'Formal customer sign-off form for confirming service completion, satisfaction, and any outstanding items or follow-up requirements.',
    module: 'FIELD_SERVICE',
    category: 'GENERAL',
    tags: ['sign-off', 'customer-acceptance', 'completion', 'satisfaction'],
    fields: [
      { id: 'section_header', label: 'Service Completion', type: 'section' },
      { id: 'service_order', label: 'Service Order #', type: 'text', required: true, width: 'half', section: 'Service Completion' },
      { id: 'customer_name', label: 'Customer Name', type: 'text', required: true, width: 'half', section: 'Service Completion' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Service Completion' },
      { id: 'work_summary', label: 'Work Summary', type: 'textarea', required: true, placeholder: 'Brief summary of work completed...', validation: { minLength: 10, maxLength: 2000 }, width: 'full', section: 'Service Completion' },
      { id: 'section_acceptance', label: 'Customer Acceptance', type: 'section' },
      { id: 'work_completed', label: 'Work Completed to Satisfaction?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }, { label: 'Partially', value: 'partial' }], width: 'half', section: 'Customer Acceptance' },
      { id: 'satisfaction_rating', label: 'Satisfaction Rating', type: 'rating', required: true, validation: { min: 1, max: 5 }, section: 'Customer Acceptance' },
      { id: 'outstanding_items', label: 'Outstanding Items', type: 'textarea', placeholder: 'Any items remaining or follow-up required...', validation: { maxLength: 2000 }, width: 'full', section: 'Customer Acceptance' },
      { id: 'customer_comments', label: 'Customer Comments', type: 'textarea', placeholder: 'Additional comments or feedback...', validation: { maxLength: 2000 }, width: 'full', section: 'Customer Acceptance' },
      { id: 'customer_signature', label: 'Customer Signature', type: 'signature', required: true, section: 'Customer Acceptance' },
      { id: 'technician_signature', label: 'Technician Signature', type: 'signature', required: true, section: 'Customer Acceptance' },
    ],
  },
];
