// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.
import type { TemplateDefinition } from '../types';

export const financeTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-FIN-001',
    name: 'Budget Approval Form',
    description:
      'Formal budget request and approval form for new expenditure, projects, or cost centres. Includes justification, breakdown, and multi-level approval.',
    module: 'FINANCE',
    category: 'COMPLIANCE',
    tags: ['budget', 'approval', 'expenditure', 'cost-centre'],
    fields: [
      { id: 'section_request', label: 'Budget Request', type: 'section' },
      {
        id: 'request_title',
        label: 'Request Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Budget Request',
      },
      {
        id: 'requested_by',
        label: 'Requested By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Budget Request',
      },
      {
        id: 'department',
        label: 'Department',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Budget Request',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Budget Request',
      },
      {
        id: 'total_amount',
        label: 'Total Amount Requested',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Budget Request',
      },
      {
        id: 'justification',
        label: 'Business Justification',
        type: 'textarea',
        required: true,
        placeholder: 'Why is this expenditure needed?',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Budget Request',
      },
      { id: 'section_breakdown', label: 'Cost Breakdown', type: 'section' },
      {
        id: 'line_items',
        label: 'Line Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'item', label: 'Item', type: 'text', required: true },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Capital', value: 'capital' },
              { label: 'Operational', value: 'operational' },
              { label: 'Personnel', value: 'personnel' },
              { label: 'Software', value: 'software' },
              { label: 'Other', value: 'other' },
            ],
          },
          { id: 'amount', label: 'Amount', type: 'number', required: true, validation: { min: 0 } },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Cost Breakdown',
      },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      {
        id: 'decision',
        label: 'Decision',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Rejected', value: 'rejected' },
          { label: 'Approved with Conditions', value: 'conditional' },
        ],
        width: 'half',
        section: 'Approval',
      },
      {
        id: 'approver_signature',
        label: 'Approver Signature',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
    ],
  },
  {
    code: 'TPL-FIN-002',
    name: 'Expense Report',
    description:
      'Employee expense report for claiming business-related expenditure. Supports itemised entries with receipts and manager approval.',
    module: 'FINANCE',
    category: 'REPORTING',
    tags: ['expense', 'reimbursement', 'claims', 'receipts'],
    fields: [
      { id: 'section_header', label: 'Expense Report Details', type: 'section' },
      {
        id: 'employee_name',
        label: 'Employee Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Expense Report Details',
      },
      {
        id: 'department',
        label: 'Department',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Expense Report Details',
      },
      {
        id: 'period_from',
        label: 'Period From',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Expense Report Details',
      },
      {
        id: 'period_to',
        label: 'Period To',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Expense Report Details',
      },
      { id: 'section_items', label: 'Expense Items', type: 'section' },
      {
        id: 'expenses',
        label: 'Expense Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'date', label: 'Date', type: 'date', required: true },
          {
            id: 'description',
            label: 'Description',
            type: 'text',
            required: true,
            placeholder: 'e.g. Client dinner',
          },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Travel', value: 'travel' },
              { label: 'Meals', value: 'meals' },
              { label: 'Accommodation', value: 'accommodation' },
              { label: 'Transport', value: 'transport' },
              { label: 'Office Supplies', value: 'supplies' },
              { label: 'Other', value: 'other' },
            ],
          },
          { id: 'amount', label: 'Amount', type: 'number', required: true, validation: { min: 0 } },
          {
            id: 'receipt',
            label: 'Receipt Attached',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
        ],
        section: 'Expense Items',
      },
      {
        id: 'total',
        label: 'Total Claimed',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Expense Items',
      },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      {
        id: 'employee_signature',
        label: 'Employee Signature',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
      {
        id: 'manager_signature',
        label: 'Manager Signature',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
    ],
  },
  {
    code: 'TPL-FIN-003',
    name: 'Financial Audit Checklist',
    description:
      'Internal financial audit checklist covering accounts, controls, compliance, and documentation. Aligned with standard audit frameworks.',
    module: 'FINANCE',
    category: 'AUDIT',
    tags: ['financial-audit', 'internal-audit', 'controls', 'compliance'],
    fields: [
      { id: 'section_header', label: 'Audit Details', type: 'section' },
      {
        id: 'audit_title',
        label: 'Audit Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Audit Details',
      },
      {
        id: 'auditor',
        label: 'Auditor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'audit_date',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'period_under_review',
        label: 'Period Under Review',
        type: 'text',
        required: true,
        placeholder: 'e.g. FY 2025/26',
        width: 'half',
        section: 'Audit Details',
      },
      { id: 'section_checks', label: 'Audit Checks', type: 'section' },
      {
        id: 'checks',
        label: 'Audit Items',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'area',
            label: 'Area',
            type: 'select',
            required: true,
            options: [
              { label: 'Accounts Payable', value: 'ap' },
              { label: 'Accounts Receivable', value: 'ar' },
              { label: 'General Ledger', value: 'gl' },
              { label: 'Payroll', value: 'payroll' },
              { label: 'Fixed Assets', value: 'fixed_assets' },
              { label: 'Bank Reconciliation', value: 'bank_recon' },
              { label: 'Tax Compliance', value: 'tax' },
            ],
          },
          { id: 'check', label: 'Check Item', type: 'text', required: true },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Satisfactory', value: 'satisfactory' },
              { label: 'Observation', value: 'observation' },
              { label: 'Non-Conformance', value: 'non_conformance' },
            ],
          },
          {
            id: 'evidence',
            label: 'Evidence Ref',
            type: 'text',
            placeholder: 'Document reference',
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Audit Checks',
      },
      { id: 'section_summary', label: 'Audit Summary', type: 'section' },
      {
        id: 'findings',
        label: 'Key Findings',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Audit Summary',
      },
      {
        id: 'recommendations',
        label: 'Recommendations',
        type: 'textarea',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Audit Summary',
      },
      {
        id: 'auditor_signature',
        label: 'Auditor Signature',
        type: 'signature',
        required: true,
        section: 'Audit Summary',
      },
    ],
  },
  {
    code: 'TPL-FIN-004',
    name: 'Budget Variance Report',
    description:
      'Periodic budget variance report comparing budgeted amounts against actual expenditure. Highlights variances by cost centre, provides root cause explanations, and documents corrective actions to bring spending back on track.',
    module: 'FINANCE',
    category: 'REPORTING',
    tags: ['budget', 'variance', 'actual-vs-budget', 'cost-centre', 'corrective-action'],
    fields: [
      { id: 'section_header', label: 'Report Details', type: 'section' },
      {
        id: 'report_title',
        label: 'Report Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Report Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'report_date',
        label: 'Report Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'reporting_period',
        label: 'Reporting Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. Q3 FY 2025/26',
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'department',
        label: 'Department / Business Unit',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'section_summary',
        label: 'Period Summary',
        type: 'section',
        helpText: 'High-level budget vs actual figures for the reporting period.',
      },
      {
        id: 'total_budget',
        label: 'Total Budget',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Period Summary',
      },
      {
        id: 'total_actual',
        label: 'Total Actual',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Period Summary',
      },
      {
        id: 'total_variance',
        label: 'Total Variance',
        type: 'number',
        required: true,
        width: 'half',
        section: 'Period Summary',
        helpText: 'Positive = under budget, Negative = over budget',
      },
      {
        id: 'variance_pct',
        label: 'Variance %',
        type: 'number',
        required: true,
        width: 'half',
        section: 'Period Summary',
      },
      {
        id: 'section_breakdown',
        label: 'Variance Breakdown by Cost Centre',
        type: 'section',
        helpText:
          'Detail each cost centre with budget, actual, and variance. Flag items exceeding the materiality threshold.',
      },
      {
        id: 'cost_centre_variances',
        label: 'Cost Centre Variances',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'cost_centre',
            label: 'Cost Centre',
            type: 'text',
            required: true,
            placeholder: 'e.g. CC-4100 Marketing',
          },
          {
            id: 'budget_amount',
            label: 'Budget',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'actual_amount',
            label: 'Actual',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          { id: 'variance_amount', label: 'Variance', type: 'number', required: true },
          {
            id: 'variance_type',
            label: 'Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Favourable', value: 'favourable' },
              { label: 'Adverse', value: 'adverse' },
              { label: 'On Budget', value: 'on_budget' },
            ],
          },
          {
            id: 'explanation',
            label: 'Root Cause',
            type: 'text',
            required: true,
            placeholder: 'Reason for variance',
          },
        ],
        section: 'Variance Breakdown by Cost Centre',
      },
      {
        id: 'section_actions',
        label: 'Corrective Actions',
        type: 'section',
        helpText:
          'Document corrective actions for adverse variances exceeding the materiality threshold.',
      },
      {
        id: 'corrective_actions',
        label: 'Corrective Actions',
        type: 'table',
        columns: [
          { id: 'cost_centre_ref', label: 'Cost Centre', type: 'text', required: true },
          {
            id: 'action_description',
            label: 'Action',
            type: 'text',
            required: true,
            placeholder: 'Corrective action to address variance',
          },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            required: true,
            options: [
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Complete', value: 'complete' },
            ],
          },
        ],
        section: 'Corrective Actions',
      },
      { id: 'section_commentary', label: 'Management Commentary', type: 'section' },
      {
        id: 'executive_summary',
        label: 'Executive Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Summarise overall budget performance, key drivers, and outlook...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Management Commentary',
      },
      {
        id: 'forecast_adjustment',
        label: 'Forecast Adjustment Required?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Reforecast Needed', value: 'yes' },
          { label: 'No — Within Tolerance', value: 'no' },
        ],
        width: 'half',
        section: 'Management Commentary',
      },
      {
        id: 'forecast_notes',
        label: 'Forecast Notes',
        type: 'textarea',
        placeholder: 'If reforecast needed, describe proposed adjustments...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Management Commentary',
      },
      {
        id: 'finance_manager_signature',
        label: 'Finance Manager Signature',
        type: 'signature',
        required: true,
        section: 'Management Commentary',
      },
      {
        id: 'budget_holder_signature',
        label: 'Budget Holder Signature',
        type: 'signature',
        required: true,
        section: 'Management Commentary',
      },
    ],
  },
  {
    code: 'TPL-FIN-005',
    name: 'Procurement Authorisation Form',
    description:
      'Formal procurement authorisation request for goods or services. Includes purchase justification, supplier selection, budget verification, and multi-level approval chain aligned with delegated authority limits.',
    module: 'FINANCE',
    category: 'COMPLIANCE',
    tags: ['procurement', 'purchase-order', 'authorisation', 'approval', 'supplier'],
    fields: [
      { id: 'section_request', label: 'Purchase Request', type: 'section' },
      {
        id: 'request_number',
        label: 'Request Number',
        type: 'text',
        required: true,
        placeholder: 'Auto-generated or manual reference',
        width: 'half',
        section: 'Purchase Request',
      },
      {
        id: 'request_date',
        label: 'Request Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Purchase Request',
      },
      {
        id: 'requester_name',
        label: 'Requester Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Purchase Request',
      },
      {
        id: 'requester_department',
        label: 'Department',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Purchase Request',
      },
      {
        id: 'purchase_description',
        label: 'Description of Goods / Services',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of what is being procured...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Purchase Request',
      },
      {
        id: 'required_by_date',
        label: 'Required By Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Purchase Request',
      },
      {
        id: 'urgency',
        label: 'Urgency',
        type: 'select',
        required: true,
        options: [
          { label: 'Routine', value: 'routine' },
          { label: 'Urgent', value: 'urgent' },
          { label: 'Emergency', value: 'emergency' },
        ],
        width: 'half',
        section: 'Purchase Request',
      },
      {
        id: 'section_justification',
        label: 'Business Justification',
        type: 'section',
        helpText:
          'Provide clear justification for this purchase including business need and expected benefit.',
      },
      {
        id: 'business_need',
        label: 'Business Need',
        type: 'textarea',
        required: true,
        placeholder: 'Why is this purchase necessary? What problem does it solve?',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Business Justification',
      },
      {
        id: 'alternatives_considered',
        label: 'Alternatives Considered',
        type: 'textarea',
        placeholder: 'What alternatives were evaluated? Why was this option selected?',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Business Justification',
      },
      { id: 'section_supplier', label: 'Supplier Details', type: 'section' },
      {
        id: 'preferred_supplier',
        label: 'Preferred Supplier',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Supplier Details',
      },
      {
        id: 'supplier_reference',
        label: 'Supplier Reference / Quote #',
        type: 'text',
        width: 'half',
        section: 'Supplier Details',
      },
      {
        id: 'sole_source',
        label: 'Sole Source?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Sole Source', value: 'yes' },
          { label: 'No — Competitive Quotes Obtained', value: 'no' },
        ],
        width: 'half',
        section: 'Supplier Details',
      },
      {
        id: 'sole_source_justification',
        label: 'Sole Source Justification',
        type: 'textarea',
        placeholder: 'If sole source, explain why competitive bidding was not possible...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Supplier Details',
      },
      {
        id: 'quotes_comparison',
        label: 'Quotes Comparison',
        type: 'table',
        columns: [
          { id: 'supplier_name', label: 'Supplier', type: 'text', required: true },
          {
            id: 'quote_amount',
            label: 'Quote Amount',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          { id: 'delivery_time', label: 'Delivery (days)', type: 'number', validation: { min: 0 } },
          { id: 'payment_terms', label: 'Payment Terms', type: 'text', placeholder: 'e.g. Net 30' },
          {
            id: 'selected',
            label: 'Selected',
            type: 'select',
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
        ],
        section: 'Supplier Details',
      },
      {
        id: 'section_budget',
        label: 'Budget Verification',
        type: 'section',
        helpText: 'Confirm budget availability and correct cost allocation.',
      },
      {
        id: 'cost_centre',
        label: 'Cost Centre',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Budget Verification',
      },
      {
        id: 'gl_account',
        label: 'GL Account',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Budget Verification',
      },
      {
        id: 'total_amount',
        label: 'Total Purchase Amount',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Budget Verification',
      },
      {
        id: 'currency',
        label: 'Currency',
        type: 'select',
        required: true,
        options: [
          { label: 'GBP', value: 'GBP' },
          { label: 'USD', value: 'USD' },
          { label: 'EUR', value: 'EUR' },
          { label: 'AUD', value: 'AUD' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Budget Verification',
      },
      {
        id: 'budget_available',
        label: 'Budget Available',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Budget Verification',
      },
      {
        id: 'budget_remaining_after',
        label: 'Budget Remaining After Purchase',
        type: 'number',
        required: true,
        width: 'half',
        section: 'Budget Verification',
      },
      {
        id: 'within_budget',
        label: 'Within Approved Budget?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Additional Approval Required', value: 'no' },
        ],
        width: 'half',
        section: 'Budget Verification',
      },
      { id: 'section_items', label: 'Line Items', type: 'section' },
      {
        id: 'line_items',
        label: 'Purchase Line Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'item_description', label: 'Item Description', type: 'text', required: true },
          {
            id: 'quantity',
            label: 'Quantity',
            type: 'number',
            required: true,
            validation: { min: 1 },
          },
          {
            id: 'unit_price',
            label: 'Unit Price',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'total_price',
            label: 'Total Price',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Capital', value: 'capital' },
              { label: 'Operational', value: 'operational' },
              { label: 'Software', value: 'software' },
              { label: 'Consumables', value: 'consumables' },
              { label: 'Services', value: 'services' },
            ],
          },
        ],
        section: 'Line Items',
      },
      {
        id: 'section_approval',
        label: 'Approval Chain',
        type: 'section',
        helpText:
          'Approvals required based on delegated authority limits. All applicable levels must sign.',
      },
      {
        id: 'approval_level',
        label: 'Approval Level Required',
        type: 'select',
        required: true,
        options: [
          { label: 'Level 1 — Line Manager (up to 5,000)', value: 'level_1' },
          { label: 'Level 2 — Department Head (up to 25,000)', value: 'level_2' },
          { label: 'Level 3 — Finance Director (up to 100,000)', value: 'level_3' },
          { label: 'Level 4 — CEO / Board (over 100,000)', value: 'level_4' },
        ],
        width: 'half',
        section: 'Approval Chain',
      },
      {
        id: 'decision',
        label: 'Decision',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Rejected', value: 'rejected' },
          { label: 'Approved with Conditions', value: 'conditional' },
          { label: 'Deferred', value: 'deferred' },
        ],
        width: 'half',
        section: 'Approval Chain',
      },
      {
        id: 'conditions',
        label: 'Conditions / Comments',
        type: 'textarea',
        placeholder: 'If approved with conditions or deferred, specify details...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Approval Chain',
      },
      {
        id: 'requester_signature',
        label: 'Requester Signature',
        type: 'signature',
        required: true,
        section: 'Approval Chain',
      },
      {
        id: 'budget_holder_signature',
        label: 'Budget Holder Signature',
        type: 'signature',
        required: true,
        section: 'Approval Chain',
      },
      {
        id: 'finance_approver_signature',
        label: 'Finance Approver Signature',
        type: 'signature',
        required: true,
        section: 'Approval Chain',
      },
    ],
  },
];
