import type { TemplateDefinition } from '../types';

export const financeTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-FIN-001',
    name: 'Budget Approval Form',
    description:
      'Formal budget request and approval form for new expenditure, projects, or cost centres. Includes justification, breakdown, and multi-level approval.',
    module: 'FINANCE',
    category: 'COMPLIANCE',
    tags: ['budget', 'approval', 'expenditure', 'cost-centre'],
    fields: [
      { id: 'section_request', label: 'Budget Request', type: 'section' },
      { id: 'request_title', label: 'Request Title', type: 'text', required: true, width: 'full', section: 'Budget Request' },
      { id: 'requested_by', label: 'Requested By', type: 'text', required: true, width: 'half', section: 'Budget Request' },
      { id: 'department', label: 'Department', type: 'text', required: true, width: 'half', section: 'Budget Request' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Budget Request' },
      { id: 'total_amount', label: 'Total Amount Requested', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Budget Request' },
      { id: 'justification', label: 'Business Justification', type: 'textarea', required: true, placeholder: 'Why is this expenditure needed?', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Budget Request' },
      { id: 'section_breakdown', label: 'Cost Breakdown', type: 'section' },
      {
        id: 'line_items',
        label: 'Line Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'item', label: 'Item', type: 'text', required: true },
          { id: 'category', label: 'Category', type: 'select', required: true, options: [{ label: 'Capital', value: 'capital' }, { label: 'Operational', value: 'operational' }, { label: 'Personnel', value: 'personnel' }, { label: 'Software', value: 'software' }, { label: 'Other', value: 'other' }] },
          { id: 'amount', label: 'Amount', type: 'number', required: true, validation: { min: 0 } },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Cost Breakdown',
      },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      { id: 'decision', label: 'Decision', type: 'select', required: true, options: [{ label: 'Approved', value: 'approved' }, { label: 'Rejected', value: 'rejected' }, { label: 'Approved with Conditions', value: 'conditional' }], width: 'half', section: 'Approval' },
      { id: 'approver_signature', label: 'Approver Signature', type: 'signature', required: true, section: 'Approval' },
    ],
  },
  {
    code: 'TPL-FIN-002',
    name: 'Expense Report',
    description:
      'Employee expense report for claiming business-related expenditure. Supports itemised entries with receipts and manager approval.',
    module: 'FINANCE',
    category: 'REPORTING',
    tags: ['expense', 'reimbursement', 'claims', 'receipts'],
    fields: [
      { id: 'section_header', label: 'Expense Report Details', type: 'section' },
      { id: 'employee_name', label: 'Employee Name', type: 'text', required: true, width: 'half', section: 'Expense Report Details' },
      { id: 'department', label: 'Department', type: 'text', required: true, width: 'half', section: 'Expense Report Details' },
      { id: 'period_from', label: 'Period From', type: 'date', required: true, width: 'half', section: 'Expense Report Details' },
      { id: 'period_to', label: 'Period To', type: 'date', required: true, width: 'half', section: 'Expense Report Details' },
      { id: 'section_items', label: 'Expense Items', type: 'section' },
      {
        id: 'expenses',
        label: 'Expense Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'date', label: 'Date', type: 'date', required: true },
          { id: 'description', label: 'Description', type: 'text', required: true, placeholder: 'e.g. Client dinner' },
          { id: 'category', label: 'Category', type: 'select', required: true, options: [{ label: 'Travel', value: 'travel' }, { label: 'Meals', value: 'meals' }, { label: 'Accommodation', value: 'accommodation' }, { label: 'Transport', value: 'transport' }, { label: 'Office Supplies', value: 'supplies' }, { label: 'Other', value: 'other' }] },
          { id: 'amount', label: 'Amount', type: 'number', required: true, validation: { min: 0 } },
          { id: 'receipt', label: 'Receipt Attached', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }] },
        ],
        section: 'Expense Items',
      },
      { id: 'total', label: 'Total Claimed', type: 'number', required: true, validation: { min: 0 }, width: 'half', section: 'Expense Items' },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      { id: 'employee_signature', label: 'Employee Signature', type: 'signature', required: true, section: 'Approval' },
      { id: 'manager_signature', label: 'Manager Signature', type: 'signature', required: true, section: 'Approval' },
    ],
  },
  {
    code: 'TPL-FIN-003',
    name: 'Financial Audit Checklist',
    description:
      'Internal financial audit checklist covering accounts, controls, compliance, and documentation. Aligned with standard audit frameworks.',
    module: 'FINANCE',
    category: 'AUDIT',
    tags: ['financial-audit', 'internal-audit', 'controls', 'compliance'],
    fields: [
      { id: 'section_header', label: 'Audit Details', type: 'section' },
      { id: 'audit_title', label: 'Audit Title', type: 'text', required: true, width: 'full', section: 'Audit Details' },
      { id: 'auditor', label: 'Auditor', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'audit_date', label: 'Audit Date', type: 'date', required: true, width: 'half', section: 'Audit Details' },
      { id: 'period_under_review', label: 'Period Under Review', type: 'text', required: true, placeholder: 'e.g. FY 2025/26', width: 'half', section: 'Audit Details' },
      { id: 'section_checks', label: 'Audit Checks', type: 'section' },
      {
        id: 'checks',
        label: 'Audit Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'area', label: 'Area', type: 'select', required: true, options: [{ label: 'Accounts Payable', value: 'ap' }, { label: 'Accounts Receivable', value: 'ar' }, { label: 'General Ledger', value: 'gl' }, { label: 'Payroll', value: 'payroll' }, { label: 'Fixed Assets', value: 'fixed_assets' }, { label: 'Bank Reconciliation', value: 'bank_recon' }, { label: 'Tax Compliance', value: 'tax' }] },
          { id: 'check', label: 'Check Item', type: 'text', required: true },
          { id: 'result', label: 'Result', type: 'select', required: true, options: [{ label: 'Satisfactory', value: 'satisfactory' }, { label: 'Observation', value: 'observation' }, { label: 'Non-Conformance', value: 'non_conformance' }] },
          { id: 'evidence', label: 'Evidence Ref', type: 'text', placeholder: 'Document reference' },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Audit Checks',
      },
      { id: 'section_summary', label: 'Audit Summary', type: 'section' },
      { id: 'findings', label: 'Key Findings', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Audit Summary' },
      { id: 'recommendations', label: 'Recommendations', type: 'textarea', validation: { maxLength: 3000 }, width: 'full', section: 'Audit Summary' },
      { id: 'auditor_signature', label: 'Auditor Signature', type: 'signature', required: true, section: 'Audit Summary' },
    ],
  },
];
