import type { TemplateDefinition } from '../types';

export const foodSafetyTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-FS-001',
    name: 'HACCP Plan Template',
    description:
      'Hazard Analysis and Critical Control Points plan for identifying food safety hazards, establishing critical control points, and defining monitoring procedures.',
    module: 'FOOD_SAFETY',
    category: 'COMPLIANCE',
    tags: ['haccp', 'food-safety', 'critical-control-points', 'hazard-analysis'],
    isoClause: '8.5.2',
    fields: [
      { id: 'section_header', label: 'HACCP Plan Details', type: 'section' },
      { id: 'product_name', label: 'Product / Process', type: 'text', required: true, width: 'half', section: 'HACCP Plan Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'HACCP Plan Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'HACCP Plan Details' },
      { id: 'section_ccps', label: 'Critical Control Points', type: 'section' },
      {
        id: 'ccps',
        label: 'CCPs',
        type: 'table',
        required: true,
        columns: [
          { id: 'ccp_number', label: 'CCP #', type: 'text', required: true, placeholder: 'e.g. CCP-1' },
          { id: 'process_step', label: 'Process Step', type: 'text', required: true },
          { id: 'hazard', label: 'Hazard', type: 'text', required: true, placeholder: 'e.g. Pathogen survival' },
          { id: 'hazard_type', label: 'Hazard Type', type: 'select', required: true, options: [{ label: 'Biological', value: 'biological' }, { label: 'Chemical', value: 'chemical' }, { label: 'Physical', value: 'physical' }, { label: 'Allergen', value: 'allergen' }] },
          { id: 'critical_limit', label: 'Critical Limit', type: 'text', required: true, placeholder: 'e.g. Core temp ≥ 75°C' },
          { id: 'monitoring', label: 'Monitoring Procedure', type: 'text', required: true },
          { id: 'corrective_action', label: 'Corrective Action', type: 'text', required: true },
          { id: 'verification', label: 'Verification', type: 'text' },
        ],
        section: 'Critical Control Points',
      },
      { id: 'review_notes', label: 'Review Notes', type: 'textarea', placeholder: 'Notes from HACCP team review...', validation: { maxLength: 2000 }, width: 'full', section: 'Critical Control Points' },
    ],
  },
  {
    code: 'TPL-FS-002',
    name: 'Hygiene Inspection Checklist',
    description:
      'Facility hygiene inspection checklist covering cleanliness, sanitation, pest control, personal hygiene, and storage conditions.',
    module: 'FOOD_SAFETY',
    category: 'INSPECTION',
    tags: ['hygiene', 'inspection', 'sanitation', 'cleanliness', 'facility'],
    fields: [
      { id: 'section_header', label: 'Inspection Details', type: 'section' },
      { id: 'facility', label: 'Facility / Area', type: 'text', required: true, width: 'half', section: 'Inspection Details' },
      { id: 'inspector', label: 'Inspector', type: 'text', required: true, width: 'half', section: 'Inspection Details' },
      { id: 'date', label: 'Inspection Date', type: 'date', required: true, width: 'half', section: 'Inspection Details' },
      { id: 'section_checks', label: 'Inspection Items', type: 'section' },
      {
        id: 'checks',
        label: 'Checklist',
        type: 'table',
        required: true,
        columns: [
          { id: 'area', label: 'Area', type: 'select', required: true, options: [{ label: 'Production Floor', value: 'production' }, { label: 'Storage', value: 'storage' }, { label: 'Washrooms', value: 'washrooms' }, { label: 'Loading Bay', value: 'loading' }, { label: 'Staff Area', value: 'staff' }, { label: 'Waste Area', value: 'waste' }] },
          { id: 'item', label: 'Check Item', type: 'text', required: true },
          { id: 'result', label: 'Result', type: 'select', required: true, options: [{ label: 'Satisfactory', value: 'satisfactory' }, { label: 'Needs Improvement', value: 'improvement' }, { label: 'Non-Compliant', value: 'non_compliant' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Inspection Items',
      },
      { id: 'overall_rating', label: 'Overall Rating', type: 'select', required: true, options: [{ label: 'Excellent', value: 'excellent' }, { label: 'Good', value: 'good' }, { label: 'Needs Improvement', value: 'improvement' }, { label: 'Unacceptable', value: 'unacceptable' }], width: 'half', section: 'Inspection Items' },
      { id: 'corrective_actions', label: 'Corrective Actions Required', type: 'textarea', placeholder: 'List any corrective actions needed...', validation: { maxLength: 2000 }, width: 'full', section: 'Inspection Items' },
      { id: 'inspector_signature', label: 'Inspector Signature', type: 'signature', required: true, section: 'Inspection Items' },
    ],
  },
  {
    code: 'TPL-FS-003',
    name: 'Supplier Audit Report',
    description:
      'Food safety supplier audit report for evaluating supplier compliance with food safety standards, HACCP, and hygiene practices.',
    module: 'FOOD_SAFETY',
    category: 'AUDIT',
    tags: ['supplier-audit', 'food-safety', 'supply-chain', 'compliance'],
    fields: [
      { id: 'section_header', label: 'Audit Details', type: 'section' },
      { id: 'supplier_name', label: 'Supplier Name', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'auditor', label: 'Auditor', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'audit_date', label: 'Audit Date', type: 'date', required: true, width: 'half', section: 'Audit Details' },
      { id: 'site_location', label: 'Site Location', type: 'text', required: true, width: 'half', section: 'Audit Details' },
      { id: 'section_findings', label: 'Audit Findings', type: 'section' },
      {
        id: 'findings',
        label: 'Findings',
        type: 'table',
        required: true,
        columns: [
          { id: 'area', label: 'Area', type: 'text', required: true, placeholder: 'e.g. HACCP Plan, Traceability' },
          { id: 'finding', label: 'Finding', type: 'text', required: true },
          { id: 'severity', label: 'Severity', type: 'select', required: true, options: [{ label: 'Critical', value: 'critical' }, { label: 'Major', value: 'major' }, { label: 'Minor', value: 'minor' }, { label: 'Observation', value: 'observation' }] },
          { id: 'corrective_action', label: 'Corrective Action', type: 'text', placeholder: 'Required action' },
          { id: 'due_date', label: 'Due Date', type: 'date' },
        ],
        section: 'Audit Findings',
      },
      { id: 'overall_result', label: 'Overall Result', type: 'select', required: true, options: [{ label: 'Approved', value: 'approved' }, { label: 'Conditionally Approved', value: 'conditional' }, { label: 'Not Approved', value: 'not_approved' }], width: 'half', section: 'Audit Findings' },
      { id: 'summary', label: 'Audit Summary', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Audit Findings' },
      { id: 'auditor_signature', label: 'Auditor Signature', type: 'signature', required: true, section: 'Audit Findings' },
    ],
  },
];
