// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.
import type { TemplateDefinition } from '../types';

export const foodSafetyTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-FS-001',
    name: 'HACCP Plan Template',
    description:
      'Hazard Analysis and Critical Control Points plan for identifying food safety hazards, establishing critical control points, and defining monitoring procedures.',
    module: 'FOOD_SAFETY',
    category: 'COMPLIANCE',
    tags: ['haccp', 'food-safety', 'critical-control-points', 'hazard-analysis'],
    isoClause: '8.5.2',
    fields: [
      { id: 'section_header', label: 'HACCP Plan Details', type: 'section' },
      {
        id: 'product_name',
        label: 'Product / Process',
        type: 'text',
        required: true,
        width: 'half',
        section: 'HACCP Plan Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'HACCP Plan Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'HACCP Plan Details',
      },
      { id: 'section_ccps', label: 'Critical Control Points', type: 'section' },
      {
        id: 'ccps',
        label: 'CCPs',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'ccp_number',
            label: 'CCP #',
            type: 'text',
            required: true,
            placeholder: 'e.g. CCP-1',
          },
          { id: 'process_step', label: 'Process Step', type: 'text', required: true },
          {
            id: 'hazard',
            label: 'Hazard',
            type: 'text',
            required: true,
            placeholder: 'e.g. Pathogen survival',
          },
          {
            id: 'hazard_type',
            label: 'Hazard Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Biological', value: 'biological' },
              { label: 'Chemical', value: 'chemical' },
              { label: 'Physical', value: 'physical' },
              { label: 'Allergen', value: 'allergen' },
            ],
          },
          {
            id: 'critical_limit',
            label: 'Critical Limit',
            type: 'text',
            required: true,
            placeholder: 'e.g. Core temp ≥ 75°C',
          },
          { id: 'monitoring', label: 'Monitoring Procedure', type: 'text', required: true },
          { id: 'corrective_action', label: 'Corrective Action', type: 'text', required: true },
          { id: 'verification', label: 'Verification', type: 'text' },
        ],
        section: 'Critical Control Points',
      },
      {
        id: 'review_notes',
        label: 'Review Notes',
        type: 'textarea',
        placeholder: 'Notes from HACCP team review...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Critical Control Points',
      },
    ],
  },
  {
    code: 'TPL-FS-002',
    name: 'Hygiene Inspection Checklist',
    description:
      'Facility hygiene inspection checklist covering cleanliness, sanitation, pest control, personal hygiene, and storage conditions.',
    module: 'FOOD_SAFETY',
    category: 'INSPECTION',
    tags: ['hygiene', 'inspection', 'sanitation', 'cleanliness', 'facility'],
    fields: [
      { id: 'section_header', label: 'Inspection Details', type: 'section' },
      {
        id: 'facility',
        label: 'Facility / Area',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Inspection Details',
      },
      {
        id: 'inspector',
        label: 'Inspector',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Inspection Details',
      },
      {
        id: 'date',
        label: 'Inspection Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Inspection Details',
      },
      { id: 'section_checks', label: 'Inspection Items', type: 'section' },
      {
        id: 'checks',
        label: 'Checklist',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'area',
            label: 'Area',
            type: 'select',
            required: true,
            options: [
              { label: 'Production Floor', value: 'production' },
              { label: 'Storage', value: 'storage' },
              { label: 'Washrooms', value: 'washrooms' },
              { label: 'Loading Bay', value: 'loading' },
              { label: 'Staff Area', value: 'staff' },
              { label: 'Waste Area', value: 'waste' },
            ],
          },
          { id: 'item', label: 'Check Item', type: 'text', required: true },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Satisfactory', value: 'satisfactory' },
              { label: 'Needs Improvement', value: 'improvement' },
              { label: 'Non-Compliant', value: 'non_compliant' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Inspection Items',
      },
      {
        id: 'overall_rating',
        label: 'Overall Rating',
        type: 'select',
        required: true,
        options: [
          { label: 'Excellent', value: 'excellent' },
          { label: 'Good', value: 'good' },
          { label: 'Needs Improvement', value: 'improvement' },
          { label: 'Unacceptable', value: 'unacceptable' },
        ],
        width: 'half',
        section: 'Inspection Items',
      },
      {
        id: 'corrective_actions',
        label: 'Corrective Actions Required',
        type: 'textarea',
        placeholder: 'List any corrective actions needed...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Inspection Items',
      },
      {
        id: 'inspector_signature',
        label: 'Inspector Signature',
        type: 'signature',
        required: true,
        section: 'Inspection Items',
      },
    ],
  },
  {
    code: 'TPL-FS-003',
    name: 'Supplier Audit Report',
    description:
      'Food safety supplier audit report for evaluating supplier compliance with food safety standards, HACCP, and hygiene practices.',
    module: 'FOOD_SAFETY',
    category: 'AUDIT',
    tags: ['supplier-audit', 'food-safety', 'supply-chain', 'compliance'],
    fields: [
      { id: 'section_header', label: 'Audit Details', type: 'section' },
      {
        id: 'supplier_name',
        label: 'Supplier Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'auditor',
        label: 'Auditor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'audit_date',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'site_location',
        label: 'Site Location',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      { id: 'section_findings', label: 'Audit Findings', type: 'section' },
      {
        id: 'findings',
        label: 'Findings',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'area',
            label: 'Area',
            type: 'text',
            required: true,
            placeholder: 'e.g. HACCP Plan, Traceability',
          },
          { id: 'finding', label: 'Finding', type: 'text', required: true },
          {
            id: 'severity',
            label: 'Severity',
            type: 'select',
            required: true,
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'Major', value: 'major' },
              { label: 'Minor', value: 'minor' },
              { label: 'Observation', value: 'observation' },
            ],
          },
          {
            id: 'corrective_action',
            label: 'Corrective Action',
            type: 'text',
            placeholder: 'Required action',
          },
          { id: 'due_date', label: 'Due Date', type: 'date' },
        ],
        section: 'Audit Findings',
      },
      {
        id: 'overall_result',
        label: 'Overall Result',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Conditionally Approved', value: 'conditional' },
          { label: 'Not Approved', value: 'not_approved' },
        ],
        width: 'half',
        section: 'Audit Findings',
      },
      {
        id: 'summary',
        label: 'Audit Summary',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Audit Findings',
      },
      {
        id: 'auditor_signature',
        label: 'Auditor Signature',
        type: 'signature',
        required: true,
        section: 'Audit Findings',
      },
    ],
  },
  {
    code: 'TPL-FS-004',
    name: 'Allergen Risk Assessment',
    description:
      'Allergen risk assessment for identifying allergenic ingredients, evaluating cross-contamination risks, and verifying labelling accuracy. Aligned with ISO 22000 and Codex Alimentarius allergen management requirements.',
    module: 'FOOD_SAFETY',
    category: 'RISK_ASSESSMENT',
    tags: ['allergen', 'risk-assessment', 'cross-contamination', 'labelling', 'food-safety'],
    isoClause: '8.5.1',
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      {
        id: 'product_name',
        label: 'Product / Product Line',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'assessor',
        label: 'Assessor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'review_due_date',
        label: 'Review Due Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
        helpText: 'Maximum 12 months from assessment date',
      },
      {
        id: 'production_line',
        label: 'Production Line / Area',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      { id: 'section_allergen_id', label: 'Allergen Identification', type: 'section' },
      {
        id: 'allergens',
        label: 'Allergens Present in Product',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'allergen',
            label: 'Allergen',
            type: 'select',
            required: true,
            options: [
              { label: 'Cereals containing gluten', value: 'gluten' },
              { label: 'Crustaceans', value: 'crustaceans' },
              { label: 'Eggs', value: 'eggs' },
              { label: 'Fish', value: 'fish' },
              { label: 'Peanuts', value: 'peanuts' },
              { label: 'Soybeans', value: 'soybeans' },
              { label: 'Milk / Lactose', value: 'milk' },
              { label: 'Tree nuts', value: 'tree_nuts' },
              { label: 'Celery', value: 'celery' },
              { label: 'Mustard', value: 'mustard' },
              { label: 'Sesame', value: 'sesame' },
              { label: 'Sulphur dioxide / Sulphites', value: 'sulphites' },
              { label: 'Lupin', value: 'lupin' },
              { label: 'Molluscs', value: 'molluscs' },
            ],
          },
          {
            id: 'source_ingredient',
            label: 'Source Ingredient',
            type: 'text',
            required: true,
            placeholder: 'e.g. Wheat flour, Soy lecithin',
          },
          {
            id: 'intentional',
            label: 'Intentional Use?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes - Ingredient', value: 'yes' },
              { label: 'No - Potential cross-contact', value: 'no' },
            ],
          },
          {
            id: 'supplier',
            label: 'Supplier',
            type: 'text',
            placeholder: 'Ingredient supplier name',
          },
          {
            id: 'supplier_declaration',
            label: 'Supplier Declaration on File?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
              { label: 'Pending', value: 'pending' },
            ],
          },
        ],
        section: 'Allergen Identification',
      },
      { id: 'section_cross_contamination', label: 'Cross-Contamination Controls', type: 'section' },
      {
        id: 'cross_contamination_controls',
        label: 'Cross-Contamination Risk & Controls',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'risk_source',
            label: 'Risk Source',
            type: 'text',
            required: true,
            placeholder: 'e.g. Shared production line with nut products',
          },
          { id: 'allergen_involved', label: 'Allergen Involved', type: 'text', required: true },
          {
            id: 'likelihood',
            label: 'Likelihood (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'severity',
            label: 'Severity (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'risk_level',
            label: 'Risk Level',
            type: 'select',
            required: true,
            options: [
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          {
            id: 'control_measure',
            label: 'Control Measure',
            type: 'text',
            required: true,
            placeholder: 'e.g. Dedicated line, validated cleaning, scheduling',
          },
          {
            id: 'verification_method',
            label: 'Verification Method',
            type: 'text',
            placeholder: 'e.g. ATP swab, lateral flow test',
          },
        ],
        section: 'Cross-Contamination Controls',
      },
      {
        id: 'cleaning_validation',
        label: 'Cleaning Validation Method',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the validated cleaning procedure used between allergen changeovers (method, acceptance criteria, frequency of validation)...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Cross-Contamination Controls',
      },
      { id: 'section_labelling', label: 'Labelling Verification', type: 'section' },
      {
        id: 'labelling_checks',
        label: 'Label Verification Checks',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'check_item',
            label: 'Check Item',
            type: 'text',
            required: true,
            placeholder: 'e.g. Ingredient list accurate',
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Compliant', value: 'compliant' },
              { label: 'Non-Compliant', value: 'non_compliant' },
              { label: 'N/A', value: 'na' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Labelling Verification',
      },
      {
        id: 'precautionary_statement',
        label: 'Precautionary Allergen Labelling (PAL) Statement',
        type: 'textarea',
        placeholder:
          'e.g. "May contain traces of nuts" — justify the use or omission of PAL statements...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Labelling Verification',
        helpText:
          'PAL should only be used after a thorough risk assessment demonstrates a real cross-contamination risk that cannot be eliminated',
      },
      { id: 'section_summary', label: 'Assessment Summary', type: 'section' },
      {
        id: 'overall_risk',
        label: 'Overall Allergen Risk Rating',
        type: 'select',
        required: true,
        options: [
          { label: 'High — Immediate action required', value: 'high' },
          { label: 'Medium — Improvement actions needed', value: 'medium' },
          { label: 'Low — Adequate controls in place', value: 'low' },
        ],
        width: 'half',
        section: 'Assessment Summary',
      },
      {
        id: 'summary_notes',
        label: 'Summary & Recommendations',
        type: 'textarea',
        required: true,
        placeholder: 'Summarise key findings and recommended actions...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Assessment Summary',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Assessment Summary',
      },
      {
        id: 'approver_signature',
        label: 'Food Safety Manager Signature',
        type: 'signature',
        required: true,
        section: 'Assessment Summary',
      },
    ],
  },
  {
    code: 'TPL-FS-005',
    name: 'Traceability Test Record',
    description:
      'Mock recall and traceability exercise record for testing the ability to trace ingredients forward to finished goods and backward to suppliers within required timeframes. Aligned with ISO 22000 clause 8.3 and FSSC 22000 traceability requirements.',
    module: 'FOOD_SAFETY',
    category: 'COMPLIANCE',
    tags: ['traceability', 'mock-recall', 'batch-trace', 'recall-test', 'food-safety'],
    isoClause: '8.3',
    fields: [
      { id: 'section_header', label: 'Test Details', type: 'section' },
      {
        id: 'test_reference',
        label: 'Test Reference Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. TRACE-2026-001',
        width: 'half',
        section: 'Test Details',
      },
      {
        id: 'test_date',
        label: 'Test Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Test Details',
      },
      {
        id: 'test_coordinator',
        label: 'Test Coordinator',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Test Details',
      },
      {
        id: 'test_type',
        label: 'Test Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Forward Trace (ingredient to finished good)', value: 'forward' },
          { label: 'Backward Trace (finished good to ingredient)', value: 'backward' },
          { label: 'Full Trace (both directions)', value: 'full' },
        ],
        width: 'half',
        section: 'Test Details',
      },
      {
        id: 'trigger',
        label: 'Test Trigger',
        type: 'select',
        required: true,
        options: [
          { label: 'Scheduled exercise', value: 'scheduled' },
          { label: 'Customer request', value: 'customer' },
          { label: 'Regulatory requirement', value: 'regulatory' },
          { label: 'Certification body requirement', value: 'certification' },
          { label: 'Post-incident verification', value: 'post_incident' },
        ],
        width: 'half',
        section: 'Test Details',
      },
      {
        id: 'target_product',
        label: 'Target Product / Batch',
        type: 'text',
        required: true,
        placeholder: 'Product name and batch/lot number selected for trace',
        width: 'full',
        section: 'Test Details',
      },
      {
        id: 'section_backward',
        label: 'Backward Traceability (Ingredient to Supplier)',
        type: 'section',
      },
      {
        id: 'backward_trace',
        label: 'Backward Trace Results',
        type: 'table',
        required: true,
        columns: [
          { id: 'ingredient', label: 'Ingredient / Raw Material', type: 'text', required: true },
          { id: 'batch_lot', label: 'Batch / Lot Number', type: 'text', required: true },
          { id: 'supplier', label: 'Supplier', type: 'text', required: true },
          { id: 'delivery_date', label: 'Delivery Date', type: 'date', required: true },
          { id: 'delivery_ref', label: 'Delivery Note / GRN Ref', type: 'text' },
          {
            id: 'traced',
            label: 'Successfully Traced?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'Partial', value: 'partial' },
              { label: 'No', value: 'no' },
            ],
          },
        ],
        section: 'Backward Traceability (Ingredient to Supplier)',
      },
      {
        id: 'section_forward',
        label: 'Forward Traceability (Finished Good to Customer)',
        type: 'section',
      },
      {
        id: 'forward_trace',
        label: 'Forward Trace Results',
        type: 'table',
        required: true,
        columns: [
          { id: 'finished_product', label: 'Finished Product', type: 'text', required: true },
          { id: 'batch_lot', label: 'Batch / Lot Number', type: 'text', required: true },
          { id: 'quantity_produced', label: 'Quantity Produced', type: 'text', required: true },
          {
            id: 'customer_destination',
            label: 'Customer / Destination',
            type: 'text',
            required: true,
          },
          { id: 'dispatch_date', label: 'Dispatch Date', type: 'date', required: true },
          { id: 'dispatch_ref', label: 'Dispatch Note Ref', type: 'text' },
          { id: 'quantity_dispatched', label: 'Quantity Dispatched', type: 'text', required: true },
          {
            id: 'traced',
            label: 'Successfully Traced?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'Partial', value: 'partial' },
              { label: 'No', value: 'no' },
            ],
          },
        ],
        section: 'Forward Traceability (Finished Good to Customer)',
      },
      { id: 'section_timing', label: 'Timing & Effectiveness', type: 'section' },
      {
        id: 'time_started',
        label: 'Exercise Start Time',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Timing & Effectiveness',
      },
      {
        id: 'time_completed',
        label: 'Exercise End Time',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Timing & Effectiveness',
      },
      {
        id: 'total_duration_minutes',
        label: 'Total Duration (minutes)',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Timing & Effectiveness',
        helpText: 'Target: complete within 4 hours for most food safety schemes',
      },
      {
        id: 'target_met',
        label: 'Timeframe Target Met?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — within target', value: 'yes' },
          { label: 'No — exceeded target', value: 'no' },
        ],
        width: 'half',
        section: 'Timing & Effectiveness',
      },
      {
        id: 'mass_balance_check',
        label: 'Mass Balance Reconciliation',
        type: 'select',
        required: true,
        options: [
          { label: 'Accounted for (100%)', value: 'full' },
          { label: 'Minor discrepancy (<2%)', value: 'minor' },
          { label: 'Significant discrepancy (>2%)', value: 'significant' },
        ],
        width: 'half',
        section: 'Timing & Effectiveness',
        helpText: 'Can you account for all quantity received vs quantity dispatched + waste + WIP?',
      },
      { id: 'section_gaps', label: 'Gaps & Corrective Actions', type: 'section' },
      {
        id: 'gaps',
        label: 'Gaps Identified',
        type: 'table',
        columns: [
          { id: 'gap_description', label: 'Gap / Issue', type: 'text', required: true },
          {
            id: 'severity',
            label: 'Severity',
            type: 'select',
            required: true,
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'Major', value: 'major' },
              { label: 'Minor', value: 'minor' },
            ],
          },
          { id: 'corrective_action', label: 'Corrective Action', type: 'text', required: true },
          { id: 'responsible_person', label: 'Responsible Person', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Closed', value: 'closed' },
            ],
          },
        ],
        section: 'Gaps & Corrective Actions',
      },
      { id: 'section_conclusion', label: 'Conclusion', type: 'section' },
      {
        id: 'overall_result',
        label: 'Overall Test Result',
        type: 'select',
        required: true,
        options: [
          { label: 'Pass — Full traceability achieved within target time', value: 'pass' },
          { label: 'Conditional Pass — Minor gaps identified', value: 'conditional' },
          { label: 'Fail — Significant gaps or target time exceeded', value: 'fail' },
        ],
        width: 'half',
        section: 'Conclusion',
      },
      {
        id: 'conclusion_notes',
        label: 'Conclusions & Recommendations',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise the effectiveness of the traceability system and any improvements needed...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Conclusion',
      },
      {
        id: 'coordinator_signature',
        label: 'Test Coordinator Signature',
        type: 'signature',
        required: true,
        section: 'Conclusion',
      },
      {
        id: 'fsm_signature',
        label: 'Food Safety Manager Signature',
        type: 'signature',
        required: true,
        section: 'Conclusion',
      },
    ],
  },
];
