import type { TemplateDefinition } from '../types';

export const healthSafetyTemplates: TemplateDefinition[] = [
  // ─── TPL-HS-001  Generic Risk Assessment ────────────────────────────
  {
    code: 'TPL-HS-001',
    name: 'Generic Risk Assessment',
    description:
      'A comprehensive risk assessment form for identifying hazards, evaluating likelihood and severity, and documenting control measures. Suitable for any workplace activity or process.',
    module: 'HEALTH_SAFETY',
    category: 'RISK_ASSESSMENT',
    tags: ['risk', 'hazard', 'assessment', 'ISO 45001', 'controls'],
    isoClause: '6.1.2',
    fields: [
      // ── Section: Activity Details ──
      {
        id: 'section_activity',
        label: 'Activity Details',
        type: 'section',
        helpText: 'Describe the activity or process being assessed.',
      },
      {
        id: 'activity',
        label: 'Activity / Process',
        type: 'text',
        required: true,
        placeholder: 'e.g. Loading pallets onto delivery vehicle',
        helpText: 'Brief name of the activity or process under assessment.',
        width: 'full',
        section: 'section_activity',
      },
      {
        id: 'activity_description',
        label: 'Activity Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Provide a detailed description of the work activity, including location, equipment, and frequency.',
        helpText: 'Include enough detail so someone unfamiliar with the task can understand it.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_activity',
      },
      {
        id: 'department',
        label: 'Department',
        type: 'text',
        required: true,
        placeholder: 'e.g. Warehouse Operations',
        width: 'half',
        section: 'section_activity',
      },
      {
        id: 'location',
        label: 'Location',
        type: 'text',
        required: true,
        placeholder: 'e.g. Building B — Loading Bay 3',
        width: 'half',
        section: 'section_activity',
      },

      // ── Section: Hazard Identification ──
      {
        id: 'section_hazards',
        label: 'Hazard Identification',
        type: 'section',
        helpText: 'List all identified hazards associated with the activity.',
      },
      {
        id: 'hazards_table',
        label: 'Identified Hazards',
        type: 'table',
        required: true,
        helpText:
          'Add one row per hazard. Describe the hazard, its source, and the potential harm.',
        columns: [
          { id: 'hazard_ref', label: 'Ref #', type: 'text', placeholder: 'H1' },
          {
            id: 'hazard_description',
            label: 'Hazard',
            type: 'text',
            placeholder: 'e.g. Manual lifting of heavy loads',
          },
          {
            id: 'hazard_source',
            label: 'Source / Cause',
            type: 'text',
            placeholder: 'e.g. Pallets weighing >25 kg',
          },
          {
            id: 'potential_harm',
            label: 'Potential Harm',
            type: 'text',
            placeholder: 'e.g. Musculoskeletal injury',
          },
        ],
        section: 'section_hazards',
      },
      {
        id: 'persons_at_risk',
        label: 'Persons at Risk',
        type: 'multiselect',
        required: true,
        helpText: 'Select all groups of people who could be harmed.',
        options: [
          { label: 'Employees', value: 'employees' },
          { label: 'Contractors', value: 'contractors' },
          { label: 'Visitors', value: 'visitors' },
          { label: 'Members of the Public', value: 'public' },
          { label: 'Young Persons (< 18)', value: 'young_persons' },
          { label: 'New / Expectant Mothers', value: 'new_mothers' },
          { label: 'Disabled Workers', value: 'disabled' },
          { label: 'Lone Workers', value: 'lone_workers' },
        ],
        section: 'section_hazards',
      },

      // ── Section: Existing Controls ──
      {
        id: 'section_existing_controls',
        label: 'Existing Control Measures',
        type: 'section',
        helpText: 'Document the control measures already in place.',
      },
      {
        id: 'existing_controls',
        label: 'Existing Controls',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe existing engineering controls, safe systems of work, PPE, training, etc.',
        helpText: 'List all current measures that reduce the risk.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_existing_controls',
      },

      // ── Section: Initial Risk Rating ──
      {
        id: 'section_initial_risk',
        label: 'Initial Risk Rating (with existing controls)',
        type: 'section',
        helpText: 'Evaluate the risk level considering only the existing controls.',
      },
      {
        id: 'likelihood',
        label: 'Likelihood',
        type: 'select',
        required: true,
        helpText: 'How likely is the harm to occur with existing controls in place?',
        options: [
          { label: '1 — Very Unlikely (rare / almost impossible)', value: '1' },
          { label: '2 — Unlikely (could happen but not expected)', value: '2' },
          { label: '3 — Possible (may occur occasionally)', value: '3' },
          { label: '4 — Likely (will probably occur)', value: '4' },
          { label: '5 — Very Likely (almost certain / imminent)', value: '5' },
        ],
        width: 'half',
        section: 'section_initial_risk',
      },
      {
        id: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        helpText: 'What is the worst realistic outcome if the harm occurs?',
        options: [
          { label: '1 — Negligible (first aid only)', value: '1' },
          { label: '2 — Minor (minor injury, < 3 days off)', value: '2' },
          { label: '3 — Moderate (over 3 day injury / RIDDOR)', value: '3' },
          { label: '4 — Major (major injury / hospitalisation)', value: '4' },
          { label: '5 — Catastrophic (fatality / permanent disability)', value: '5' },
        ],
        width: 'half',
        section: 'section_initial_risk',
      },
      {
        id: 'risk_rating',
        label: 'Risk Rating (Likelihood x Severity)',
        type: 'number',
        required: true,
        helpText: 'Auto-calculated: Likelihood x Severity. 1-6 = Low, 8-12 = Medium, 15-25 = High.',
        validation: { min: 1, max: 25 },
        width: 'half',
        section: 'section_initial_risk',
      },
      {
        id: 'risk_level',
        label: 'Risk Level',
        type: 'select',
        required: true,
        options: [
          { label: 'Low (1-6)', value: 'low' },
          { label: 'Medium (8-12)', value: 'medium' },
          { label: 'High (15-25)', value: 'high' },
        ],
        width: 'half',
        section: 'section_initial_risk',
      },

      // ── Section: Additional Controls ──
      {
        id: 'section_additional_controls',
        label: 'Additional Control Measures',
        type: 'section',
        helpText: 'Specify further controls needed to reduce the risk to an acceptable level.',
      },
      {
        id: 'additional_controls',
        label: 'Additional Controls Required',
        type: 'textarea',
        required: false,
        placeholder:
          'Describe additional controls to be implemented, following the hierarchy of controls.',
        helpText: 'Elimination > Substitution > Engineering > Administrative > PPE.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_additional_controls',
      },

      // ── Section: Residual Risk ──
      {
        id: 'section_residual_risk',
        label: 'Residual Risk Rating (after additional controls)',
        type: 'section',
        helpText: 'Re-evaluate risk assuming additional controls are fully implemented.',
      },
      {
        id: 'residual_likelihood',
        label: 'Residual Likelihood',
        type: 'select',
        required: true,
        options: [
          { label: '1 — Very Unlikely', value: '1' },
          { label: '2 — Unlikely', value: '2' },
          { label: '3 — Possible', value: '3' },
          { label: '4 — Likely', value: '4' },
          { label: '5 — Very Likely', value: '5' },
        ],
        width: 'half',
        section: 'section_residual_risk',
      },
      {
        id: 'residual_severity',
        label: 'Residual Severity',
        type: 'select',
        required: true,
        options: [
          { label: '1 — Negligible', value: '1' },
          { label: '2 — Minor', value: '2' },
          { label: '3 — Moderate', value: '3' },
          { label: '4 — Major', value: '4' },
          { label: '5 — Catastrophic', value: '5' },
        ],
        width: 'half',
        section: 'section_residual_risk',
      },
      {
        id: 'residual_risk_rating',
        label: 'Residual Risk Rating',
        type: 'number',
        helpText: 'Auto-calculated: Residual Likelihood x Residual Severity.',
        validation: { min: 1, max: 25 },
        width: 'half',
        section: 'section_residual_risk',
      },

      // ── Section: Sign-off ──
      {
        id: 'section_signoff',
        label: 'Assessment Sign-Off',
        type: 'section',
      },
      {
        id: 'assessor_name',
        label: 'Assessor Name',
        type: 'text',
        required: true,
        placeholder: 'Full name of the risk assessor',
        width: 'third',
        section: 'section_signoff',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'third',
        section: 'section_signoff',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        helpText: 'Date by which this assessment must be reviewed (maximum 12 months).',
        width: 'third',
        section: 'section_signoff',
      },
    ],
    defaultContent: {
      risk_level: 'medium',
    },
  },

  // ─── TPL-HS-002  Manual Handling Assessment ─────────────────────────
  {
    code: 'TPL-HS-002',
    name: 'Manual Handling Assessment',
    description:
      'A structured assessment for manual handling operations, evaluating the task, the load, the working environment, and individual capability in line with the Manual Handling Operations Regulations.',
    module: 'HEALTH_SAFETY',
    category: 'RISK_ASSESSMENT',
    tags: ['manual handling', 'ergonomics', 'MSD', 'MHOR', 'risk assessment'],
    isoClause: '6.1.2',
    fields: [
      {
        id: 'section_task',
        label: 'Task Details',
        type: 'section',
        helpText: 'Describe the manual handling task being assessed.',
      },
      {
        id: 'task_description',
        label: 'Task Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the manual handling task including what is lifted/carried/pushed/pulled, start and end points, and frequency.',
        helpText:
          'Include enough detail for someone unfamiliar with the task to understand what is involved.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_task',
      },
      {
        id: 'department',
        label: 'Department',
        type: 'text',
        required: true,
        placeholder: 'e.g. Warehouse',
        width: 'half',
        section: 'section_task',
      },
      {
        id: 'location',
        label: 'Location',
        type: 'text',
        required: true,
        placeholder: 'e.g. Goods-in area',
        width: 'half',
        section: 'section_task',
      },

      // ── Section: Load ──
      {
        id: 'section_load',
        label: 'Load Characteristics',
        type: 'section',
        helpText: 'Describe the load being handled.',
      },
      {
        id: 'load_weight',
        label: 'Load Weight (kg)',
        type: 'number',
        required: true,
        placeholder: 'e.g. 25',
        helpText: 'Weight of the heaviest load handled in kilograms.',
        validation: { min: 0, max: 500 },
        width: 'third',
        section: 'section_load',
      },
      {
        id: 'load_dimensions',
        label: 'Load Dimensions / Shape',
        type: 'text',
        placeholder: 'e.g. 60 x 40 x 30 cm, rectangular box',
        width: 'third',
        section: 'section_load',
      },
      {
        id: 'load_characteristics',
        label: 'Load Characteristics',
        type: 'multiselect',
        helpText: 'Select all that apply.',
        options: [
          { label: 'Bulky / difficult to grip', value: 'bulky' },
          { label: 'Unstable / shifting contents', value: 'unstable' },
          { label: 'Sharp edges', value: 'sharp' },
          { label: 'Hot / cold', value: 'temperature' },
          { label: 'Contains hazardous substances', value: 'hazardous' },
          { label: 'Requires two-person lift', value: 'two_person' },
        ],
        width: 'third',
        section: 'section_load',
      },

      // ── Section: Frequency & Duration ──
      {
        id: 'section_frequency',
        label: 'Frequency & Duration',
        type: 'section',
      },
      {
        id: 'frequency',
        label: 'Handling Frequency',
        type: 'select',
        required: true,
        helpText: 'How often is this manual handling task performed?',
        options: [
          { label: 'Infrequent (less than once per day)', value: 'infrequent' },
          { label: 'Low (1-5 times per day)', value: 'low' },
          { label: 'Medium (6-20 times per day)', value: 'medium' },
          { label: 'High (21-50 times per day)', value: 'high' },
          { label: 'Very High (more than 50 times per day)', value: 'very_high' },
        ],
        width: 'half',
        section: 'section_frequency',
      },
      {
        id: 'duration_per_lift',
        label: 'Duration per Lift / Carry',
        type: 'select',
        options: [
          { label: 'Brief (< 10 seconds)', value: 'brief' },
          { label: 'Short (10-30 seconds)', value: 'short' },
          { label: 'Moderate (30 seconds - 2 minutes)', value: 'moderate' },
          { label: 'Extended (> 2 minutes)', value: 'extended' },
        ],
        width: 'half',
        section: 'section_frequency',
      },

      // ── Section: Environment ──
      {
        id: 'section_environment',
        label: 'Working Environment Conditions',
        type: 'section',
        helpText: 'Assess the environmental factors that affect the manual handling task.',
      },
      {
        id: 'environment_conditions',
        label: 'Environment Conditions',
        type: 'multiselect',
        required: true,
        helpText: 'Select any conditions present in the working environment.',
        options: [
          { label: 'Uneven or slippery floor surface', value: 'uneven_floor' },
          { label: 'Restricted space / confined area', value: 'restricted_space' },
          { label: 'Variation in floor levels (stairs, ramps)', value: 'level_changes' },
          { label: 'Poor lighting', value: 'poor_lighting' },
          { label: 'Extreme temperature (hot or cold)', value: 'extreme_temp' },
          { label: 'Strong air movement / wind', value: 'wind' },
          { label: 'Wet / outdoor conditions', value: 'wet_conditions' },
          { label: 'Obstructions in walkway', value: 'obstructions' },
        ],
        width: 'full',
        section: 'section_environment',
      },
      {
        id: 'environment_notes',
        label: 'Additional Environment Notes',
        type: 'textarea',
        placeholder: 'Any other environmental factors that may affect the task.',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'section_environment',
      },

      // ── Section: Posture Assessment ──
      {
        id: 'section_posture',
        label: 'Posture Assessment',
        type: 'section',
        helpText: 'Evaluate the postures adopted during the manual handling task.',
      },
      {
        id: 'posture_assessment_table',
        label: 'Posture Assessment',
        type: 'table',
        required: true,
        helpText: 'Assess each body region for risk during the handling task.',
        columns: [
          {
            id: 'body_region',
            label: 'Body Region',
            type: 'select',
            options: [
              { label: 'Lower Back', value: 'lower_back' },
              { label: 'Upper Back / Shoulders', value: 'upper_back' },
              { label: 'Neck', value: 'neck' },
              { label: 'Arms / Wrists', value: 'arms_wrists' },
              { label: 'Knees / Legs', value: 'knees_legs' },
            ],
          },
          {
            id: 'posture_observed',
            label: 'Posture Observed',
            type: 'text',
            placeholder: 'e.g. Twisting, stooping, reaching above shoulder',
          },
          {
            id: 'risk_factor',
            label: 'Risk Factor',
            type: 'select',
            options: [
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
            ],
          },
          {
            id: 'comments',
            label: 'Comments',
            type: 'text',
            placeholder: 'Specific observations',
          },
        ],
        section: 'section_posture',
      },

      // ── Section: Risk Level ──
      {
        id: 'section_risk',
        label: 'Overall Risk Level',
        type: 'section',
      },
      {
        id: 'overall_risk_level',
        label: 'Overall Risk Level',
        type: 'select',
        required: true,
        helpText: 'Based on the combined assessment of load, posture, frequency, and environment.',
        options: [
          { label: 'Low — Acceptable, no further action required', value: 'low' },
          { label: 'Medium — Reduce risk where reasonably practicable', value: 'medium' },
          { label: 'High — Immediate action required', value: 'high' },
        ],
        width: 'full',
        section: 'section_risk',
      },

      // ── Section: Controls ──
      {
        id: 'section_controls',
        label: 'Control Measures',
        type: 'section',
        helpText: 'Document the measures to eliminate or reduce the manual handling risk.',
      },
      {
        id: 'controls',
        label: 'Control Measures',
        type: 'textarea',
        required: true,
        placeholder:
          'e.g. Introduce mechanical aids (pallet truck), reduce load weight, provide manual handling training.',
        helpText:
          'Apply the hierarchy: Eliminate > Automate > Mechanical aids > Reduce load > Improve environment > Training.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_controls',
      },

      // ── Section: Sign-off ──
      {
        id: 'section_signoff',
        label: 'Assessment Sign-Off',
        type: 'section',
      },
      {
        id: 'assessor_name',
        label: 'Assessor Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        helpText: 'Sign to confirm this assessment has been completed accurately.',
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        helpText: 'Maximum 12 months from assessment date.',
        width: 'half',
        section: 'section_signoff',
      },
    ],
  },

  // ─── TPL-HS-003  COSHH Assessment ──────────────────────────────────
  {
    code: 'TPL-HS-003',
    name: 'COSHH Assessment',
    description:
      'Control of Substances Hazardous to Health assessment form. Documents the substance, hazard classification, exposure routes, control measures, and emergency procedures in compliance with COSHH Regulations.',
    module: 'HEALTH_SAFETY',
    category: 'RISK_ASSESSMENT',
    tags: ['COSHH', 'chemical', 'hazardous substance', 'exposure', 'PPE', 'SDS'],
    isoClause: '8.1.2',
    fields: [
      // ── Section: Substance Details ──
      {
        id: 'section_substance',
        label: 'Substance Information',
        type: 'section',
        helpText: 'Record details of the hazardous substance from the Safety Data Sheet (SDS).',
      },
      {
        id: 'substance_name',
        label: 'Substance / Product Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Isopropyl Alcohol 70%',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'supplier',
        label: 'Supplier / Manufacturer',
        type: 'text',
        required: true,
        placeholder: 'e.g. ChemCorp Ltd.',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'sds_reference',
        label: 'SDS Reference / Version',
        type: 'text',
        placeholder: 'e.g. SDS-2024-IPA-003 Rev 2',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'cas_number',
        label: 'CAS Number',
        type: 'text',
        placeholder: 'e.g. 67-63-0',
        helpText: 'Chemical Abstracts Service registry number from the SDS.',
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'physical_form',
        label: 'Physical Form',
        type: 'select',
        required: true,
        options: [
          { label: 'Solid (powder / granules)', value: 'solid' },
          { label: 'Liquid', value: 'liquid' },
          { label: 'Gas', value: 'gas' },
          { label: 'Vapour', value: 'vapour' },
          { label: 'Mist / Aerosol', value: 'mist' },
          { label: 'Fume', value: 'fume' },
          { label: 'Dust / Fibre', value: 'dust' },
        ],
        width: 'half',
        section: 'section_substance',
      },
      {
        id: 'quantity_used',
        label: 'Quantity Used / Stored',
        type: 'text',
        placeholder: 'e.g. 5 litres per week, 20L drum in store',
        width: 'half',
        section: 'section_substance',
      },

      // ── Section: Hazard Classification ──
      {
        id: 'section_hazards',
        label: 'Hazard Classification',
        type: 'section',
        helpText: 'Record the GHS/CLP hazard classification from the SDS.',
      },
      {
        id: 'hazard_classification',
        label: 'Hazard Statements (H-codes)',
        type: 'multiselect',
        required: true,
        helpText: 'Select all applicable hazard classifications from the SDS.',
        options: [
          { label: 'H225 — Highly flammable liquid and vapour', value: 'H225' },
          { label: 'H226 — Flammable liquid and vapour', value: 'H226' },
          { label: 'H301 — Toxic if swallowed', value: 'H301' },
          { label: 'H302 — Harmful if swallowed', value: 'H302' },
          { label: 'H311 — Toxic in contact with skin', value: 'H311' },
          { label: 'H312 — Harmful in contact with skin', value: 'H312' },
          { label: 'H314 — Causes severe skin burns and eye damage', value: 'H314' },
          { label: 'H315 — Causes skin irritation', value: 'H315' },
          { label: 'H317 — May cause an allergic skin reaction', value: 'H317' },
          { label: 'H318 — Causes serious eye damage', value: 'H318' },
          { label: 'H319 — Causes serious eye irritation', value: 'H319' },
          { label: 'H331 — Toxic if inhaled', value: 'H331' },
          { label: 'H332 — Harmful if inhaled', value: 'H332' },
          { label: 'H334 — May cause allergy or asthma symptoms if inhaled', value: 'H334' },
          { label: 'H335 — May cause respiratory irritation', value: 'H335' },
          { label: 'H340 — May cause genetic defects', value: 'H340' },
          { label: 'H350 — May cause cancer', value: 'H350' },
          { label: 'H360 — May damage fertility or the unborn child', value: 'H360' },
          { label: 'H370 — Causes damage to organs', value: 'H370' },
          { label: 'H372 — Causes damage to organs through prolonged exposure', value: 'H372' },
          { label: 'H400 — Very toxic to aquatic life', value: 'H400' },
          { label: 'H410 — Very toxic to aquatic life with long lasting effects', value: 'H410' },
        ],
        section: 'section_hazards',
      },

      // ── Section: Exposure ──
      {
        id: 'section_exposure',
        label: 'Exposure Assessment',
        type: 'section',
      },
      {
        id: 'exposure_route',
        label: 'Route(s) of Exposure',
        type: 'multiselect',
        required: true,
        helpText: 'How could workers be exposed to this substance?',
        options: [
          { label: 'Inhalation (breathing in vapours, dust, fumes)', value: 'inhalation' },
          { label: 'Skin contact (direct or splash)', value: 'skin_contact' },
          { label: 'Skin absorption', value: 'skin_absorption' },
          { label: 'Eye contact', value: 'eye_contact' },
          { label: 'Ingestion (swallowing)', value: 'ingestion' },
          { label: 'Injection (needlestick, sharp contamination)', value: 'injection' },
        ],
        width: 'half',
        section: 'section_exposure',
      },
      {
        id: 'exposure_duration',
        label: 'Typical Exposure Duration',
        type: 'select',
        required: true,
        options: [
          { label: 'Brief (< 15 minutes per shift)', value: 'brief' },
          { label: 'Short (15 min - 1 hour per shift)', value: 'short' },
          { label: 'Medium (1-4 hours per shift)', value: 'medium' },
          { label: 'Long (4-8 hours per shift)', value: 'long' },
          { label: 'Continuous (full shift exposure)', value: 'continuous' },
        ],
        width: 'half',
        section: 'section_exposure',
      },
      {
        id: 'oel_value',
        label: 'Occupational Exposure Limit (OEL)',
        type: 'text',
        placeholder: 'e.g. WEL 8-hr TWA: 400 ppm (999 mg/m3)',
        helpText: 'Workplace Exposure Limit from EH40 or equivalent standard.',
        width: 'half',
        section: 'section_exposure',
      },
      {
        id: 'exposure_frequency',
        label: 'Exposure Frequency',
        type: 'select',
        options: [
          { label: 'Daily', value: 'daily' },
          { label: 'Weekly', value: 'weekly' },
          { label: 'Monthly', value: 'monthly' },
          { label: 'Occasional / Ad-hoc', value: 'occasional' },
        ],
        width: 'half',
        section: 'section_exposure',
      },

      // ── Section: Controls Hierarchy ──
      {
        id: 'section_controls',
        label: 'Control Measures (Hierarchy of Controls)',
        type: 'section',
        helpText: 'Document controls in order of the COSHH hierarchy.',
      },
      {
        id: 'controls_hierarchy_table',
        label: 'Controls Hierarchy',
        type: 'table',
        required: true,
        helpText:
          'For each level of the hierarchy, record the control measures in place or planned.',
        columns: [
          {
            id: 'hierarchy_level',
            label: 'Hierarchy Level',
            type: 'select',
            options: [
              { label: '1 — Elimination', value: 'elimination' },
              { label: '2 — Substitution', value: 'substitution' },
              { label: '3 — Enclosed / Isolation', value: 'enclosure' },
              { label: '4 — Local Exhaust Ventilation', value: 'lev' },
              { label: '5 — General Ventilation', value: 'general_vent' },
              { label: '6 — Safe Systems of Work', value: 'ssow' },
              { label: '7 — PPE (last resort)', value: 'ppe' },
            ],
          },
          {
            id: 'control_measure',
            label: 'Control Measure',
            type: 'text',
            placeholder: 'Describe the control',
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'In Place', value: 'in_place' },
              { label: 'Planned', value: 'planned' },
              { label: 'Not Applicable', value: 'na' },
            ],
          },
        ],
        section: 'section_controls',
      },

      // ── Section: PPE ──
      {
        id: 'section_ppe',
        label: 'Personal Protective Equipment',
        type: 'section',
      },
      {
        id: 'ppe_required',
        label: 'PPE Required',
        type: 'multiselect',
        required: true,
        helpText: 'Select all PPE required when handling this substance.',
        options: [
          { label: 'Safety goggles / splash-proof', value: 'goggles' },
          { label: 'Face shield', value: 'face_shield' },
          { label: 'Chemical-resistant gloves (nitrile)', value: 'gloves_nitrile' },
          { label: 'Chemical-resistant gloves (neoprene)', value: 'gloves_neoprene' },
          { label: 'Chemical-resistant gloves (PVC)', value: 'gloves_pvc' },
          { label: 'Respiratory protection — FFP2 / FFP3 mask', value: 'resp_ffp' },
          {
            label: 'Respiratory protection — half-face respirator with cartridge',
            value: 'resp_half',
          },
          { label: 'Respiratory protection — full-face respirator', value: 'resp_full' },
          { label: 'Chemical-resistant apron', value: 'apron' },
          { label: 'Chemical-resistant suit', value: 'suit' },
          { label: 'Safety boots (chemical resistant)', value: 'boots' },
        ],
        section: 'section_ppe',
      },

      // ── Section: Emergency ──
      {
        id: 'section_emergency',
        label: 'Emergency Procedures',
        type: 'section',
      },
      {
        id: 'emergency_procedures',
        label: 'Emergency & First Aid Procedures',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe spill response, first aid measures (inhalation, skin, eye, ingestion), and fire-fighting measures.',
        helpText:
          'Reference the SDS sections 4 (First Aid), 5 (Fire-fighting), and 6 (Accidental Release).',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_emergency',
      },
      {
        id: 'spill_kit_location',
        label: 'Spill Kit Location',
        type: 'text',
        placeholder: 'e.g. Adjacent to chemical store, Bay C',
        width: 'half',
        section: 'section_emergency',
      },
      {
        id: 'eyewash_location',
        label: 'Eye Wash Station Location',
        type: 'text',
        placeholder: 'e.g. West wall of lab',
        width: 'half',
        section: 'section_emergency',
      },

      // ── Section: Sign-off ──
      {
        id: 'section_signoff',
        label: 'Assessment Sign-Off',
        type: 'section',
      },
      {
        id: 'assessor_name',
        label: 'Assessor Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        helpText:
          'COSHH assessments must be reviewed at least annually or when circumstances change.',
        width: 'half',
        section: 'section_signoff',
      },
    ],
  },

  // ─── TPL-HS-004  Incident Investigation Report ─────────────────────
  {
    code: 'TPL-HS-004',
    name: 'Incident Investigation Report',
    description:
      'Structured form for investigating workplace incidents, recording details of injured persons, identifying root causes, documenting witness statements, and assigning corrective actions.',
    module: 'HEALTH_SAFETY',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['incident', 'investigation', 'root cause', 'corrective action', 'RIDDOR'],
    isoClause: '10.2',
    fields: [
      // ── Section: Incident Details ──
      {
        id: 'section_incident',
        label: 'Incident Details',
        type: 'section',
      },
      {
        id: 'incident_ref',
        label: 'Incident Reference Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. INC-2026-0042',
        helpText: 'Unique incident tracking reference.',
        width: 'third',
        section: 'section_incident',
      },
      {
        id: 'incident_date',
        label: 'Date of Incident',
        type: 'date',
        required: true,
        width: 'third',
        section: 'section_incident',
      },
      {
        id: 'incident_time',
        label: 'Time of Incident',
        type: 'text',
        required: true,
        placeholder: 'HH:MM (24-hour)',
        helpText: 'Use 24-hour format.',
        validation: { pattern: '^([01]\\d|2[0-3]):[0-5]\\d$' },
        width: 'third',
        section: 'section_incident',
      },
      {
        id: 'incident_location',
        label: 'Location of Incident',
        type: 'text',
        required: true,
        placeholder: 'e.g. Workshop A, Machine Bay 7',
        width: 'half',
        section: 'section_incident',
      },
      {
        id: 'incident_type',
        label: 'Incident Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Injury / Ill Health', value: 'injury' },
          { label: 'Dangerous Occurrence', value: 'dangerous_occurrence' },
          { label: 'Property Damage', value: 'property_damage' },
          { label: 'Environmental Release', value: 'environmental' },
          { label: 'Fire / Explosion', value: 'fire' },
          { label: 'Security Breach', value: 'security' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'section_incident',
      },
      {
        id: 'incident_description',
        label: 'Description of Incident',
        type: 'textarea',
        required: true,
        placeholder: 'Provide a factual, chronological account of what happened.',
        helpText:
          'Include what happened, in what order, what equipment was involved, and what the outcome was.',
        validation: { maxLength: 5000 },
        width: 'full',
        section: 'section_incident',
      },
      {
        id: 'riddor_reportable',
        label: 'RIDDOR Reportable?',
        type: 'radio',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'Under investigation', value: 'tbc' },
        ],
        helpText: 'Reporting of Injuries, Diseases and Dangerous Occurrences Regulations.',
        width: 'half',
        section: 'section_incident',
      },

      // ── Section: Injured Persons ──
      {
        id: 'section_injured',
        label: 'Injured / Affected Persons',
        type: 'section',
        helpText: 'Record details of anyone injured or affected.',
      },
      {
        id: 'injured_persons_table',
        label: 'Injured Persons',
        type: 'table',
        helpText: 'Add one row per injured or affected person.',
        columns: [
          { id: 'name', label: 'Full Name', type: 'text' },
          { id: 'role', label: 'Role / Job Title', type: 'text' },
          {
            id: 'employment_status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Employee', value: 'employee' },
              { label: 'Contractor', value: 'contractor' },
              { label: 'Visitor', value: 'visitor' },
              { label: 'Member of Public', value: 'public' },
            ],
          },
          {
            id: 'injury_type',
            label: 'Injury / Condition',
            type: 'text',
            placeholder: 'e.g. Laceration to right hand',
          },
          { id: 'body_part', label: 'Body Part', type: 'text', placeholder: 'e.g. Right hand' },
          {
            id: 'treatment',
            label: 'Treatment',
            type: 'select',
            options: [
              { label: 'First aid on site', value: 'first_aid' },
              { label: 'Hospital (outpatient)', value: 'hospital_out' },
              { label: 'Hospital (admitted)', value: 'hospital_in' },
              { label: 'No treatment required', value: 'none' },
            ],
          },
          { id: 'days_lost', label: 'Days Lost', type: 'number' },
        ],
        section: 'section_injured',
      },

      // ── Section: Cause Analysis ──
      {
        id: 'section_causes',
        label: 'Cause Analysis',
        type: 'section',
        helpText: 'Identify the immediate, root, and contributing causes.',
      },
      {
        id: 'immediate_causes',
        label: 'Immediate Cause(s)',
        type: 'textarea',
        required: true,
        placeholder: 'What unsafe acts or conditions directly led to the incident?',
        helpText: 'The direct cause that immediately preceded the event.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_causes',
      },
      {
        id: 'root_causes',
        label: 'Root Cause(s)',
        type: 'textarea',
        required: true,
        placeholder:
          'Use 5-Why or fishbone analysis. What underlying system failures allowed this to happen?',
        helpText:
          'The fundamental organisational or system failures that allowed the immediate cause to exist.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_causes',
      },
      {
        id: 'contributing_factors',
        label: 'Contributing Factors',
        type: 'multiselect',
        helpText: 'Select any factors that contributed to the incident.',
        options: [
          { label: 'Inadequate training / competence', value: 'training' },
          { label: 'Inadequate supervision', value: 'supervision' },
          { label: 'Inadequate risk assessment', value: 'risk_assessment' },
          { label: 'Procedure not followed', value: 'procedure_breach' },
          { label: 'No procedure available', value: 'no_procedure' },
          { label: 'Equipment failure / defect', value: 'equipment' },
          { label: 'Workplace design / layout', value: 'design' },
          { label: 'Environmental conditions', value: 'environment' },
          { label: 'Fatigue / stress / human factors', value: 'human_factors' },
          { label: 'Communication failure', value: 'communication' },
          { label: 'PPE not worn / inadequate', value: 'ppe' },
          { label: 'Maintenance failure', value: 'maintenance' },
        ],
        width: 'full',
        section: 'section_causes',
      },

      // ── Section: Witness Statements ──
      {
        id: 'section_witnesses',
        label: 'Witness Statements',
        type: 'section',
      },
      {
        id: 'witness_statements_table',
        label: 'Witness Statements',
        type: 'table',
        helpText: 'Record statements from each witness.',
        columns: [
          { id: 'witness_name', label: 'Witness Name', type: 'text' },
          { id: 'witness_role', label: 'Role / Job Title', type: 'text' },
          {
            id: 'statement',
            label: 'Statement Summary',
            type: 'text',
            placeholder: 'Key points from the witness account',
          },
          { id: 'statement_date', label: 'Date Taken', type: 'date' },
        ],
        section: 'section_witnesses',
      },

      // ── Section: Corrective Actions ──
      {
        id: 'section_actions',
        label: 'Corrective Actions',
        type: 'section',
        helpText: 'Actions to prevent recurrence.',
      },
      {
        id: 'corrective_actions_table',
        label: 'Corrective Actions',
        type: 'table',
        required: true,
        helpText: 'List all corrective actions with responsible persons and due dates.',
        columns: [
          { id: 'action_ref', label: 'Action #', type: 'text', placeholder: 'CA-01' },
          { id: 'description', label: 'Action Description', type: 'text' },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            options: [
              { label: 'Immediate', value: 'immediate' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          { id: 'responsible', label: 'Responsible Person', type: 'text' },
          { id: 'due_date', label: 'Due Date', type: 'date' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Complete', value: 'complete' },
              { label: 'Overdue', value: 'overdue' },
            ],
          },
        ],
        section: 'section_actions',
      },

      // ── Section: Sign-off ──
      {
        id: 'section_signoff',
        label: 'Investigation Sign-Off',
        type: 'section',
      },
      {
        id: 'investigation_lead',
        label: 'Investigation Lead',
        type: 'text',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'investigation_lead_signature',
        label: 'Investigation Lead Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
      {
        id: 'signoff_date',
        label: 'Sign-Off Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_signoff',
      },
    ],
  },

  // ─── TPL-HS-005  Near Miss Report ──────────────────────────────────
  {
    code: 'TPL-HS-005',
    name: 'Near Miss Report',
    description:
      'A quick and accessible form for reporting near miss events. Encourages a positive reporting culture by capturing near misses before they result in actual harm.',
    module: 'HEALTH_SAFETY',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['near miss', 'hazard', 'reporting', 'proactive', 'safety culture'],
    isoClause: '10.2',
    fields: [
      {
        id: 'section_event',
        label: 'Near Miss Event Details',
        type: 'section',
      },
      {
        id: 'event_date',
        label: 'Date of Near Miss',
        type: 'date',
        required: true,
        width: 'third',
        section: 'section_event',
      },
      {
        id: 'event_time',
        label: 'Time of Near Miss',
        type: 'text',
        required: true,
        placeholder: 'HH:MM (24-hour)',
        validation: { pattern: '^([01]\\d|2[0-3]):[0-5]\\d$' },
        width: 'third',
        section: 'section_event',
      },
      {
        id: 'event_location',
        label: 'Location',
        type: 'text',
        required: true,
        placeholder: 'e.g. Car park entrance, Building A corridor',
        width: 'third',
        section: 'section_event',
      },
      {
        id: 'reporter_name',
        label: 'Reporter Name',
        type: 'text',
        required: true,
        placeholder: 'Your full name',
        helpText: 'Reports can also be submitted anonymously via your safety rep.',
        width: 'half',
        section: 'section_event',
      },
      {
        id: 'reporter_department',
        label: 'Department',
        type: 'text',
        placeholder: 'e.g. Production',
        width: 'half',
        section: 'section_event',
      },
      {
        id: 'description',
        label: 'What happened?',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the near miss event. What were you doing? What went wrong? Who or what could have been harmed?',
        helpText: 'Be as specific as possible — include equipment, materials, and conditions.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_event',
      },

      // ── Section: Risk Assessment ──
      {
        id: 'section_risk',
        label: 'Potential Risk Assessment',
        type: 'section',
        helpText:
          'Evaluate what could have happened if the near miss had resulted in an actual incident.',
      },
      {
        id: 'potential_consequence',
        label: 'Potential Consequence',
        type: 'select',
        required: true,
        helpText: 'What was the most likely outcome if this had resulted in an actual incident?',
        options: [
          { label: 'First aid injury', value: 'first_aid' },
          { label: 'Lost time injury (< 7 days)', value: 'lost_time_minor' },
          { label: 'Major injury / hospitalisation', value: 'major_injury' },
          { label: 'Permanent disability', value: 'disability' },
          { label: 'Fatality', value: 'fatality' },
          { label: 'Property / equipment damage', value: 'property_damage' },
          { label: 'Environmental release', value: 'environmental' },
        ],
        width: 'half',
        section: 'section_risk',
      },
      {
        id: 'potential_severity',
        label: 'Potential Severity',
        type: 'select',
        required: true,
        options: [
          { label: '1 — Negligible', value: '1' },
          { label: '2 — Minor', value: '2' },
          { label: '3 — Moderate', value: '3' },
          { label: '4 — Major', value: '4' },
          { label: '5 — Catastrophic', value: '5' },
        ],
        width: 'half',
        section: 'section_risk',
      },
      {
        id: 'category',
        label: 'Category',
        type: 'select',
        required: true,
        helpText: 'Select the category that best describes the near miss.',
        options: [
          { label: 'Slip / Trip / Fall', value: 'slip_trip_fall' },
          { label: 'Struck by object', value: 'struck_by' },
          { label: 'Caught in / between', value: 'caught_in' },
          { label: 'Electrical', value: 'electrical' },
          { label: 'Fire / Explosion', value: 'fire' },
          { label: 'Chemical / Hazardous substance', value: 'chemical' },
          { label: 'Moving vehicle / plant', value: 'vehicle' },
          { label: 'Working at height', value: 'height' },
          { label: 'Manual handling', value: 'manual_handling' },
          { label: 'Machinery / equipment', value: 'machinery' },
          { label: 'Housekeeping', value: 'housekeeping' },
          { label: 'Environmental', value: 'environmental' },
          { label: 'Other', value: 'other' },
        ],
        width: 'full',
        section: 'section_risk',
      },

      // ── Section: Actions ──
      {
        id: 'section_actions',
        label: 'Actions Taken / Suggested',
        type: 'section',
      },
      {
        id: 'immediate_action',
        label: 'Immediate Action Taken',
        type: 'textarea',
        placeholder:
          'Describe any immediate steps taken to make the area safe (e.g. isolated equipment, cleaned spill, cordoned area).',
        helpText: 'What did you or others do immediately to prevent harm?',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_actions',
      },
      {
        id: 'suggested_actions',
        label: 'Suggested Preventive Actions',
        type: 'textarea',
        placeholder: 'What changes would prevent this from happening again?',
        helpText: 'Your suggestions help us improve safety. All ideas are welcome.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_actions',
      },
      {
        id: 'photos_attached',
        label: 'Photos / Evidence Attached',
        type: 'file',
        helpText: 'Attach any photos of the hazard or conditions.',
        section: 'section_actions',
      },
    ],
  },

  // ─── TPL-HS-006  ISO 45001 Internal Audit Checklist ────────────────
  {
    code: 'TPL-HS-006',
    name: 'ISO 45001 Internal Audit Checklist',
    description:
      'Comprehensive internal audit checklist aligned with ISO 45001:2018 clauses 4-10. Records conformity status, objective evidence, and audit findings for each requirement.',
    module: 'HEALTH_SAFETY',
    category: 'AUDIT',
    tags: ['ISO 45001', 'audit', 'internal audit', 'OHS', 'conformity', 'certification'],
    isoClause: '9.2.2',
    fields: [
      // ── Section: Audit Header ──
      {
        id: 'section_header',
        label: 'Audit Information',
        type: 'section',
      },
      {
        id: 'audit_number',
        label: 'Audit Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. IA-OHS-2026-003',
        helpText: 'Unique audit identifier from the audit programme.',
        width: 'third',
        section: 'section_header',
      },
      {
        id: 'audit_scope',
        label: 'Audit Scope',
        type: 'textarea',
        required: true,
        placeholder: 'e.g. ISO 45001 Clauses 6-8 covering Warehouse Operations',
        helpText: 'Define the scope including clauses, processes, departments, and sites covered.',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'section_header',
      },
      {
        id: 'audit_criteria',
        label: 'Audit Criteria',
        type: 'text',
        required: true,
        placeholder: 'ISO 45001:2018, internal procedures, legal requirements',
        defaultValue: 'ISO 45001:2018',
        width: 'half',
        section: 'section_header',
      },
      {
        id: 'lead_auditor',
        label: 'Lead Auditor',
        type: 'text',
        required: true,
        placeholder: 'Full name of lead auditor',
        width: 'half',
        section: 'section_header',
      },
      {
        id: 'audit_team',
        label: 'Audit Team Members',
        type: 'text',
        placeholder: 'Names of additional audit team members',
        width: 'half',
        section: 'section_header',
      },
      {
        id: 'audit_date',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'third',
        section: 'section_header',
      },
      {
        id: 'auditee_department',
        label: 'Auditee Department / Process',
        type: 'text',
        required: true,
        placeholder: 'e.g. Warehouse Operations',
        width: 'third',
        section: 'section_header',
      },

      // ── Section: Clause Audit ──
      {
        id: 'section_clauses',
        label: 'Clause-by-Clause Audit',
        type: 'section',
        helpText: 'Assess conformity against each ISO 45001 requirement in scope.',
      },
      {
        id: 'clauses_table',
        label: 'Audit Findings by Clause',
        type: 'table',
        required: true,
        helpText: 'One row per clause or sub-clause assessed.',
        columns: [
          { id: 'clause_ref', label: 'Clause', type: 'text', placeholder: 'e.g. 6.1.2.1' },
          {
            id: 'requirement',
            label: 'Requirement Summary',
            type: 'text',
            placeholder: 'e.g. Hazard identification',
          },
          {
            id: 'conformity',
            label: 'Conformity',
            type: 'select',
            options: [
              { label: 'Conforming', value: 'conforming' },
              { label: 'Minor Non-Conformity', value: 'minor_nc' },
              { label: 'Major Non-Conformity', value: 'major_nc' },
              { label: 'Observation', value: 'observation' },
              { label: 'Not Assessed', value: 'not_assessed' },
              { label: 'Not Applicable', value: 'na' },
            ],
          },
          {
            id: 'evidence',
            label: 'Objective Evidence',
            type: 'text',
            placeholder: 'Records, interviews, observations',
          },
          {
            id: 'finding',
            label: 'Finding / Notes',
            type: 'text',
            placeholder: 'Details of conformity or non-conformity',
          },
        ],
        section: 'section_clauses',
      },

      // ── Section: Non-Conformities ──
      {
        id: 'section_ncrs',
        label: 'Non-Conformity Reports',
        type: 'section',
        helpText: 'Detail any non-conformities identified during the audit.',
      },
      {
        id: 'ncrs_table',
        label: 'NCR Register',
        type: 'table',
        helpText: 'Raise a formal NCR for each non-conformity.',
        columns: [
          { id: 'ncr_ref', label: 'NCR Ref', type: 'text', placeholder: 'NCR-001' },
          {
            id: 'ncr_type',
            label: 'Type',
            type: 'select',
            options: [
              { label: 'Minor', value: 'minor' },
              { label: 'Major', value: 'major' },
            ],
          },
          { id: 'clause_ref', label: 'Clause', type: 'text', placeholder: '6.1.2' },
          { id: 'ncr_description', label: 'Description of Non-Conformity', type: 'text' },
          { id: 'corrective_action', label: 'Corrective Action Required', type: 'text' },
          { id: 'responsible', label: 'Responsible Person', type: 'text' },
          { id: 'due_date', label: 'Due Date', type: 'date' },
        ],
        section: 'section_ncrs',
      },

      // ── Section: Opportunities ──
      {
        id: 'section_ofi',
        label: 'Opportunities for Improvement',
        type: 'section',
      },
      {
        id: 'opportunities',
        label: 'Opportunities for Improvement (OFI)',
        type: 'textarea',
        placeholder:
          'List any opportunities to improve the OHS management system, even where requirements are being met.',
        helpText:
          'OFIs are not non-conformities but represent areas where performance could be enhanced.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_ofi',
      },

      // ── Section: Conclusion ──
      {
        id: 'section_conclusion',
        label: 'Audit Conclusion',
        type: 'section',
      },
      {
        id: 'audit_conclusion',
        label: 'Audit Conclusion',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise the overall audit findings, number of NCs raised, and overall opinion on OHS management system effectiveness.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_conclusion',
      },
      {
        id: 'auditor_signature',
        label: 'Lead Auditor Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_conclusion',
      },
      {
        id: 'audit_close_date',
        label: 'Audit Close Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'section_conclusion',
      },
    ],
  },

  // ─── TPL-HS-007  Safety Walkthrough Checklist ──────────────────────
  {
    code: 'TPL-HS-007',
    name: 'Safety Walkthrough Checklist',
    description:
      'A practical checklist for conducting safety walkthrough inspections of workplace areas. Covers housekeeping, fire safety, electrical safety, PPE compliance, and machinery guarding with checkbox-based assessments.',
    module: 'HEALTH_SAFETY',
    category: 'INSPECTION',
    tags: ['inspection', 'walkthrough', 'checklist', 'housekeeping', 'fire safety', 'PPE'],
    isoClause: '9.1.1',
    fields: [
      // ── Section: Header ──
      {
        id: 'section_header',
        label: 'Inspection Details',
        type: 'section',
      },
      {
        id: 'area_inspected',
        label: 'Area / Zone Inspected',
        type: 'text',
        required: true,
        placeholder: 'e.g. Production Hall B, Floor 2',
        width: 'half',
        section: 'section_header',
      },
      {
        id: 'inspection_date',
        label: 'Inspection Date',
        type: 'date',
        required: true,
        width: 'third',
        section: 'section_header',
      },
      {
        id: 'inspector_name',
        label: 'Inspector Name',
        type: 'text',
        required: true,
        width: 'third',
        section: 'section_header',
      },
      {
        id: 'accompanied_by',
        label: 'Accompanied By',
        type: 'text',
        placeholder: 'Area supervisor or safety rep',
        width: 'third',
        section: 'section_header',
      },

      // ── Section: Housekeeping ──
      {
        id: 'section_housekeeping',
        label: 'Housekeeping',
        type: 'section',
        helpText: 'Assess general cleanliness and order in the area.',
      },
      {
        id: 'hk_floors_clean',
        label: 'Floors clean, dry, and free from trip hazards',
        type: 'checkbox',
        section: 'section_housekeeping',
      },
      {
        id: 'hk_walkways_clear',
        label: 'Walkways and emergency routes unobstructed',
        type: 'checkbox',
        section: 'section_housekeeping',
      },
      {
        id: 'hk_waste_disposed',
        label: 'Waste disposed of correctly (bins not overflowing)',
        type: 'checkbox',
        section: 'section_housekeeping',
      },
      {
        id: 'hk_storage_tidy',
        label: 'Materials and equipment stored safely and tidily',
        type: 'checkbox',
        section: 'section_housekeeping',
      },
      {
        id: 'hk_signage',
        label: 'Safety signage visible and in good condition',
        type: 'checkbox',
        section: 'section_housekeeping',
      },
      {
        id: 'hk_spills',
        label: 'No spills or leaks on floor surfaces',
        type: 'checkbox',
        section: 'section_housekeeping',
      },

      // ── Section: Fire Safety ──
      {
        id: 'section_fire',
        label: 'Fire Safety',
        type: 'section',
      },
      {
        id: 'fire_extinguishers',
        label: 'Fire extinguishers accessible and in-date',
        type: 'checkbox',
        section: 'section_fire',
      },
      {
        id: 'fire_exits_clear',
        label: 'Fire exits unobstructed and clearly marked',
        type: 'checkbox',
        section: 'section_fire',
      },
      {
        id: 'fire_doors',
        label: 'Fire doors in good condition and self-closing',
        type: 'checkbox',
        section: 'section_fire',
      },
      {
        id: 'fire_alarm_points',
        label: 'Fire alarm call points accessible and unobstructed',
        type: 'checkbox',
        section: 'section_fire',
      },
      {
        id: 'fire_assembly',
        label: 'Assembly point signage visible and correct',
        type: 'checkbox',
        section: 'section_fire',
      },
      {
        id: 'fire_flammable_storage',
        label: 'Flammable materials stored correctly (COSHH cabinet)',
        type: 'checkbox',
        section: 'section_fire',
      },

      // ── Section: Electrical Safety ──
      {
        id: 'section_electrical',
        label: 'Electrical Safety',
        type: 'section',
      },
      {
        id: 'elec_leads_condition',
        label: 'Electrical leads and cables in good condition (no damage)',
        type: 'checkbox',
        section: 'section_electrical',
      },
      {
        id: 'elec_no_overload',
        label: 'No overloaded sockets or daisy-chained extension leads',
        type: 'checkbox',
        section: 'section_electrical',
      },
      {
        id: 'elec_pat_testing',
        label: 'Portable appliances PAT tested (labels current)',
        type: 'checkbox',
        section: 'section_electrical',
      },
      {
        id: 'elec_panels_access',
        label: 'Electrical panels accessible and labelled',
        type: 'checkbox',
        section: 'section_electrical',
      },
      {
        id: 'elec_isolators',
        label: 'Isolator switches identified and accessible',
        type: 'checkbox',
        section: 'section_electrical',
      },

      // ── Section: PPE ──
      {
        id: 'section_ppe',
        label: 'PPE Compliance',
        type: 'section',
      },
      {
        id: 'ppe_correct_type',
        label: 'Correct PPE worn for tasks observed',
        type: 'checkbox',
        section: 'section_ppe',
      },
      {
        id: 'ppe_good_condition',
        label: 'PPE in good condition (not damaged or expired)',
        type: 'checkbox',
        section: 'section_ppe',
      },
      {
        id: 'ppe_available',
        label: 'PPE readily available and accessible',
        type: 'checkbox',
        section: 'section_ppe',
      },
      {
        id: 'ppe_signage',
        label: 'PPE requirement signs displayed at entry points',
        type: 'checkbox',
        section: 'section_ppe',
      },
      {
        id: 'ppe_storage',
        label: 'PPE stored correctly when not in use',
        type: 'checkbox',
        section: 'section_ppe',
      },

      // ── Section: Machinery ──
      {
        id: 'section_machinery',
        label: 'Machinery & Equipment Safety',
        type: 'section',
      },
      {
        id: 'mach_guarding',
        label: 'Machine guards in place and functioning',
        type: 'checkbox',
        section: 'section_machinery',
      },
      {
        id: 'mach_emergency_stops',
        label: 'Emergency stop buttons accessible and tested',
        type: 'checkbox',
        section: 'section_machinery',
      },
      {
        id: 'mach_lockout_tagout',
        label: 'Lockout/tagout procedures followed for maintenance',
        type: 'checkbox',
        section: 'section_machinery',
      },
      {
        id: 'mach_safe_operation',
        label: 'Operators following safe operating procedures',
        type: 'checkbox',
        section: 'section_machinery',
      },
      {
        id: 'mach_maintenance',
        label: 'Maintenance records up to date',
        type: 'checkbox',
        section: 'section_machinery',
      },

      // ── Section: Observations ──
      {
        id: 'section_observations',
        label: 'Observations',
        type: 'section',
        helpText: 'Record any observations, positive or negative, during the walkthrough.',
      },
      {
        id: 'observations_table',
        label: 'Observations',
        type: 'table',
        helpText: 'Document each observation with location and recommended action.',
        columns: [
          { id: 'observation_ref', label: 'Ref', type: 'text', placeholder: 'OBS-01' },
          { id: 'location', label: 'Location', type: 'text', placeholder: 'Specific area' },
          {
            id: 'observation',
            label: 'Observation',
            type: 'text',
            placeholder: 'What was observed',
          },
          {
            id: 'type',
            label: 'Type',
            type: 'select',
            options: [
              { label: 'Positive', value: 'positive' },
              { label: 'Concern', value: 'concern' },
              { label: 'Unsafe act', value: 'unsafe_act' },
              { label: 'Unsafe condition', value: 'unsafe_condition' },
            ],
          },
          { id: 'photo_ref', label: 'Photo Ref', type: 'text', placeholder: 'Photo filename' },
        ],
        section: 'section_observations',
      },

      // ── Section: Action Items ──
      {
        id: 'section_action_items',
        label: 'Action Items',
        type: 'section',
      },
      {
        id: 'action_items_table',
        label: 'Action Items',
        type: 'table',
        helpText: 'Actions arising from the inspection.',
        columns: [
          { id: 'action_ref', label: 'Action #', type: 'text', placeholder: 'ACT-01' },
          { id: 'description', label: 'Action Required', type: 'text' },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            options: [
              { label: 'Immediate', value: 'immediate' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          { id: 'responsible', label: 'Assigned To', type: 'text' },
          { id: 'due_date', label: 'Due Date', type: 'date' },
        ],
        section: 'section_action_items',
      },

      // ── Section: Overall Rating ──
      {
        id: 'section_rating',
        label: 'Overall Assessment',
        type: 'section',
      },
      {
        id: 'overall_rating',
        label: 'Overall Safety Rating',
        type: 'rating',
        required: true,
        helpText: '1 = Poor (immediate action required), 5 = Excellent (exemplary standards).',
        section: 'section_rating',
      },
      {
        id: 'overall_comments',
        label: 'Overall Comments',
        type: 'textarea',
        placeholder: 'Summarise the general state of safety in the area inspected.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_rating',
      },
      {
        id: 'inspector_signature',
        label: 'Inspector Signature',
        type: 'signature',
        required: true,
        width: 'half',
        section: 'section_rating',
      },
    ],
  },

  // ─── TPL-HS-008  OH&S Management Review ───────────────────────────
  {
    code: 'TPL-HS-008',
    name: 'OH&S Management Review',
    description:
      'Structured management review agenda and minutes template for the OH&S management system, aligned with ISO 45001 Clause 9.3. Covers all required inputs, outputs, decisions, and action items.',
    module: 'HEALTH_SAFETY',
    category: 'MANAGEMENT_REVIEW',
    tags: [
      'management review',
      'ISO 45001',
      'clause 9.3',
      'continual improvement',
      'top management',
    ],
    isoClause: '9.3',
    fields: [
      // ── Section: Meeting Details ──
      {
        id: 'section_meeting',
        label: 'Meeting Details',
        type: 'section',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'third',
        section: 'section_meeting',
      },
      {
        id: 'review_number',
        label: 'Review Number',
        type: 'text',
        placeholder: 'e.g. MR-OHS-2026-Q1',
        width: 'third',
        section: 'section_meeting',
      },
      {
        id: 'chair',
        label: 'Chair / Top Management Representative',
        type: 'text',
        required: true,
        placeholder: 'Name and title',
        width: 'third',
        section: 'section_meeting',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'textarea',
        required: true,
        placeholder:
          'List all attendees with their roles (e.g. John Smith — Operations Director, Jane Doe — H&S Manager).',
        helpText: 'Top management must be represented to satisfy ISO 45001 Clause 9.3.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_meeting',
      },

      // ── Section: Input — Audit Results ──
      {
        id: 'section_input_audit',
        label: 'Input: Internal Audit Results',
        type: 'section',
        helpText: 'ISO 45001 Clause 9.3 (a) — Status of actions from previous management reviews.',
      },
      {
        id: 'previous_actions_status',
        label: 'Status of Actions from Previous Review',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise the status of actions raised in the previous management review. How many are complete, in progress, or overdue?',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_input_audit',
      },
      {
        id: 'audit_results',
        label: 'Internal Audit Results Summary',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise key findings from internal audits conducted since the last review. Include number of NCs raised, trends, and areas of concern.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_input_audit',
      },

      // ── Section: Input — Incident Statistics ──
      {
        id: 'section_input_incidents',
        label: 'Input: Incident & Near Miss Statistics',
        type: 'section',
        helpText: 'ISO 45001 Clause 9.3 (b) — OHS performance including trends.',
      },
      {
        id: 'incident_stats',
        label: 'Incident Statistics',
        type: 'textarea',
        required: true,
        placeholder:
          'Provide incident metrics: total incidents, RIDDOR reports, lost time injuries, LTI frequency rate, severity rate, near miss reports, and trends compared to previous period.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_input_incidents',
      },

      // ── Section: Input — Compliance ──
      {
        id: 'section_input_compliance',
        label: 'Input: Compliance Obligations',
        type: 'section',
        helpText: 'ISO 45001 Clause 9.3 (c) — Fulfilment of compliance obligations.',
      },
      {
        id: 'compliance_status',
        label: 'Compliance Status',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise compliance evaluation results, any regulatory changes, enforcement actions, or compliance gaps identified.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_input_compliance',
      },

      // ── Section: Input — Objectives Progress ──
      {
        id: 'section_input_objectives',
        label: 'Input: OH&S Objectives Progress',
        type: 'section',
        helpText: 'ISO 45001 Clause 9.3 (d) — Extent to which objectives have been achieved.',
      },
      {
        id: 'objectives_progress',
        label: 'Objectives Progress',
        type: 'textarea',
        required: true,
        placeholder:
          'Review progress against each OH&S objective set for this period. Include KPI data and any objectives not on track.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'section_input_objectives',
      },

      // ── Section: Input — Consultation & Worker Participation ──
      {
        id: 'section_input_consultation',
        label: 'Input: Worker Consultation & Participation',
        type: 'section',
        helpText:
          'ISO 45001 Clause 9.3 (e) — Relevant information on worker consultation and participation.',
      },
      {
        id: 'consultation_summary',
        label: 'Worker Consultation & Participation Summary',
        type: 'textarea',
        placeholder:
          'Summarise worker consultation activities, safety committee outcomes, feedback from safety representatives, and worker participation in risk assessments.',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'section_input_consultation',
      },

      // ── Section: Output — Decisions ──
      {
        id: 'section_output_decisions',
        label: 'Output: Decisions',
        type: 'section',
        helpText: 'ISO 45001 Clause 9.3 — Decisions and conclusions of the review.',
      },
      {
        id: 'decisions_table',
        label: 'Decisions Made',
        type: 'table',
        required: true,
        helpText: 'Record all decisions, resource allocations, and strategic directions agreed.',
        columns: [
          { id: 'decision_ref', label: 'Ref', type: 'text', placeholder: 'D-01' },
          { id: 'decision', label: 'Decision / Direction', type: 'text' },
          { id: 'rationale', label: 'Rationale', type: 'text' },
          {
            id: 'resources',
            label: 'Resources Required',
            type: 'text',
            placeholder: 'Budget, personnel, equipment',
          },
          { id: 'owner', label: 'Owner', type: 'text' },
        ],
        section: 'section_output_decisions',
      },

      // ── Section: Output — Action Items ──
      {
        id: 'section_output_actions',
        label: 'Output: Action Items',
        type: 'section',
      },
      {
        id: 'action_items_table',
        label: 'Action Items',
        type: 'table',
        required: true,
        helpText: 'All actions arising from the management review with owners and deadlines.',
        columns: [
          { id: 'action_ref', label: 'Action #', type: 'text', placeholder: 'MR-ACT-01' },
          { id: 'action_description', label: 'Action', type: 'text' },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            options: [
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          { id: 'responsible', label: 'Responsible Person', type: 'text' },
          { id: 'due_date', label: 'Due Date', type: 'date' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Complete', value: 'complete' },
            ],
          },
        ],
        section: 'section_output_actions',
      },

      // ── Section: Next Review ──
      {
        id: 'section_next_review',
        label: 'Next Review',
        type: 'section',
      },
      {
        id: 'next_review_date',
        label: 'Next Management Review Date',
        type: 'date',
        required: true,
        helpText:
          'Management reviews must be conducted at planned intervals (typically quarterly or semi-annually).',
        width: 'half',
        section: 'section_next_review',
      },
      {
        id: 'chair_signature',
        label: 'Chair Signature',
        type: 'signature',
        required: true,
        helpText: 'Signature of the management representative who chaired the review.',
        width: 'half',
        section: 'section_next_review',
      },
    ],
  },
];
