// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.
import type { TemplateDefinition } from '../types';

export const incidentsTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-INC-001',
    name: 'Incident Report Form',
    description:
      'Comprehensive incident report form for recording workplace incidents, near misses, and dangerous occurrences. Covers details, immediate actions, root cause analysis, and corrective actions.',
    module: 'INCIDENTS',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['incident-report', 'workplace-incident', 'near-miss', 'riddor'],
    isoClause: '10.2',
    fields: [
      { id: 'section_incident', label: 'Incident Details', type: 'section' },
      {
        id: 'incident_ref',
        label: 'Incident Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. INC-2026-001',
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'incident_type',
        label: 'Incident Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Injury', value: 'injury' },
          { label: 'Near Miss', value: 'near_miss' },
          { label: 'Dangerous Occurrence', value: 'dangerous_occurrence' },
          { label: 'Environmental Release', value: 'environmental' },
          { label: 'Property Damage', value: 'property_damage' },
          { label: 'Security Breach', value: 'security' },
          { label: 'Process Deviation', value: 'process_deviation' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'date_occurred',
        label: 'Date / Time of Incident',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'date_reported',
        label: 'Date Reported',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'location',
        label: 'Location',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'reported_by',
        label: 'Reported By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Critical', value: 'critical' },
          { label: 'Major', value: 'major' },
          { label: 'Moderate', value: 'moderate' },
          { label: 'Minor', value: 'minor' },
          { label: 'Negligible', value: 'negligible' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'riddor_reportable',
        label: 'RIDDOR Reportable?',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'Under Investigation', value: 'investigating' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'description',
        label: 'Incident Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe what happened, sequence of events, and immediate consequences...',
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Incident Details',
      },
      { id: 'section_persons', label: 'Persons Involved', type: 'section' },
      {
        id: 'persons',
        label: 'Affected Persons',
        type: 'table',
        columns: [
          { id: 'name', label: 'Name', type: 'text', required: true },
          {
            id: 'role',
            label: 'Role / Status',
            type: 'select',
            options: [
              { label: 'Employee', value: 'employee' },
              { label: 'Contractor', value: 'contractor' },
              { label: 'Visitor', value: 'visitor' },
              { label: 'Member of Public', value: 'public' },
            ],
          },
          { id: 'injury_type', label: 'Injury / Impact', type: 'text' },
          { id: 'treatment', label: 'Treatment Given', type: 'text' },
        ],
        section: 'Persons Involved',
      },
      { id: 'section_immediate', label: 'Immediate Actions', type: 'section' },
      {
        id: 'immediate_actions',
        label: 'Immediate Actions Taken',
        type: 'textarea',
        required: true,
        placeholder: 'Containment, first aid, area cordoned off, notifications made...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Immediate Actions',
      },
      { id: 'section_investigation', label: 'Investigation', type: 'section' },
      {
        id: 'investigator',
        label: 'Investigator',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Investigation',
      },
      {
        id: 'investigation_date',
        label: 'Investigation Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Investigation',
      },
      {
        id: 'root_cause',
        label: 'Root Cause Analysis',
        type: 'textarea',
        required: true,
        placeholder: 'Use 5-Why or other root cause analysis method...',
        validation: { minLength: 30, maxLength: 5000 },
        width: 'full',
        section: 'Investigation',
      },
      {
        id: 'contributing_factors',
        label: 'Contributing Factors',
        type: 'textarea',
        placeholder:
          'Environmental conditions, training gaps, equipment condition, procedural issues...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Investigation',
      },
      { id: 'section_corrective', label: 'Corrective Actions', type: 'section' },
      {
        id: 'corrective_actions',
        label: 'Corrective Actions',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Completed', value: 'completed' },
              { label: 'Verified', value: 'verified' },
            ],
          },
        ],
        section: 'Corrective Actions',
      },
      {
        id: 'investigator_signature',
        label: 'Investigator Signature',
        type: 'signature',
        required: true,
        section: 'Corrective Actions',
      },
      {
        id: 'manager_signature',
        label: 'Manager Approval',
        type: 'signature',
        required: true,
        section: 'Corrective Actions',
      },
    ],
  },
  {
    code: 'TPL-INC-002',
    name: 'Incident Trend Analysis Report',
    description:
      'Periodic report for analysing incident trends, identifying patterns, and tracking effectiveness of corrective measures.',
    module: 'INCIDENTS',
    category: 'REPORTING',
    tags: ['incident-trends', 'analysis', 'statistics', 'prevention'],
    isoClause: '9.1.3',
    fields: [
      { id: 'section_header', label: 'Report Details', type: 'section' },
      {
        id: 'period',
        label: 'Report Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. Q1 2026',
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      { id: 'section_stats', label: 'Summary Statistics', type: 'section' },
      {
        id: 'total_incidents',
        label: 'Total Incidents',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'third',
        section: 'Summary Statistics',
      },
      {
        id: 'near_misses',
        label: 'Near Misses',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'third',
        section: 'Summary Statistics',
      },
      {
        id: 'lost_time_injuries',
        label: 'Lost Time Injuries',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'third',
        section: 'Summary Statistics',
      },
      {
        id: 'ltifr',
        label: 'LTIFR',
        type: 'number',
        helpText: 'Lost Time Injury Frequency Rate per million hours',
        validation: { min: 0 },
        width: 'third',
        section: 'Summary Statistics',
      },
      {
        id: 'trifr',
        label: 'TRIFR',
        type: 'number',
        helpText: 'Total Recordable Injury Frequency Rate',
        validation: { min: 0 },
        width: 'third',
        section: 'Summary Statistics',
      },
      {
        id: 'riddor_count',
        label: 'RIDDOR Reports',
        type: 'number',
        validation: { min: 0 },
        width: 'third',
        section: 'Summary Statistics',
      },
      { id: 'section_analysis', label: 'Trend Analysis', type: 'section' },
      {
        id: 'by_type',
        label: 'Incidents by Type',
        type: 'table',
        columns: [
          { id: 'type', label: 'Type', type: 'text', required: true },
          { id: 'count', label: 'Count', type: 'number', required: true },
          { id: 'previous', label: 'Previous Period', type: 'number' },
          {
            id: 'trend',
            label: 'Trend',
            type: 'select',
            options: [
              { label: 'Increasing', value: 'increasing' },
              { label: 'Stable', value: 'stable' },
              { label: 'Decreasing', value: 'decreasing' },
            ],
          },
        ],
        section: 'Trend Analysis',
      },
      {
        id: 'key_findings',
        label: 'Key Findings',
        type: 'textarea',
        required: true,
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Trend Analysis',
      },
      {
        id: 'recommendations',
        label: 'Recommendations',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Trend Analysis',
      },
      {
        id: 'manager_signature',
        label: 'H&S Manager Signature',
        type: 'signature',
        required: true,
        section: 'Trend Analysis',
      },
    ],
  },
  {
    code: 'TPL-INC-003',
    name: 'Near Miss Report',
    description:
      'Quick near miss / hazard observation report form for capturing potential incident events and proactive safety improvements.',
    module: 'INCIDENTS',
    category: 'RISK_ASSESSMENT',
    tags: ['near-miss', 'hazard-observation', 'proactive-safety', 'prevention'],
    isoClause: '6.1.2',
    fields: [
      { id: 'section_report', label: 'Report Details', type: 'section' },
      {
        id: 'report_ref',
        label: 'Report Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. NM-2026-001',
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'date',
        label: 'Date / Time Observed',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'reporter',
        label: 'Reporter Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'department',
        label: 'Department / Area',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'location',
        label: 'Exact Location',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Report Details',
      },
      {
        id: 'category',
        label: 'Category',
        type: 'select',
        required: true,
        options: [
          { label: 'Unsafe Act', value: 'unsafe_act' },
          { label: 'Unsafe Condition', value: 'unsafe_condition' },
          { label: 'Equipment Failure', value: 'equipment' },
          { label: 'Environmental Hazard', value: 'environmental' },
          { label: 'Process Issue', value: 'process' },
        ],
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'potential_severity',
        label: 'Potential Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Fatality / Life-Altering', value: 'fatality' },
          { label: 'Major Injury', value: 'major' },
          { label: 'Minor Injury', value: 'minor' },
          { label: 'First Aid', value: 'first_aid' },
          { label: 'No Injury', value: 'no_injury' },
        ],
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'description',
        label: 'Description of Near Miss',
        type: 'textarea',
        required: true,
        placeholder: 'What happened? What could have happened? Who was at risk?',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Report Details',
      },
      { id: 'section_action', label: 'Action Taken', type: 'section' },
      {
        id: 'immediate_action',
        label: 'Immediate Action Taken',
        type: 'textarea',
        placeholder: 'What was done immediately to eliminate the hazard?',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Action Taken',
      },
      {
        id: 'suggested_improvement',
        label: 'Suggested Improvement',
        type: 'textarea',
        placeholder: 'What should be done to prevent recurrence?',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Action Taken',
      },
      {
        id: 'reporter_signature',
        label: 'Reporter Signature',
        type: 'signature',
        section: 'Action Taken',
      },
    ],
  },
  {
    code: 'TPL-INC-004',
    name: 'RIDDOR / Statutory Incident Notification',
    description:
      'Statutory notification form for reportable incidents under RIDDOR or equivalent regulations, capturing all required fields for regulatory submission.',
    module: 'INCIDENTS',
    category: 'REGULATORY',
    tags: ['riddor', 'statutory-reporting', 'hse-notification', 'regulatory'],
    isoClause: '10.2',
    fields: [
      { id: 'section_report', label: 'Notification Details', type: 'section' },
      {
        id: 'riddor_ref',
        label: 'Notification Reference',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Notification Details',
      },
      {
        id: 'incident_ref',
        label: 'Internal Incident Ref',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Notification Details',
      },
      {
        id: 'date_occurred',
        label: 'Date of Incident',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Notification Details',
      },
      {
        id: 'date_reported',
        label: 'Date Reported to Authority',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Notification Details',
      },
      {
        id: 'report_type',
        label: 'Report Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Death', value: 'death' },
          { label: 'Specified Injury', value: 'specified_injury' },
          { label: 'Over-7-Day Incapacitation', value: 'over_7_day' },
          { label: 'Non-Fatal Injury (Non-Worker)', value: 'non_worker' },
          { label: 'Occupational Disease', value: 'disease' },
          { label: 'Dangerous Occurrence', value: 'dangerous_occurrence' },
        ],
        width: 'half',
        section: 'Notification Details',
      },
      { id: 'section_person', label: 'Injured Person', type: 'section' },
      {
        id: 'ip_name',
        label: 'Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Injured Person',
      },
      {
        id: 'ip_occupation',
        label: 'Occupation',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Injured Person',
      },
      {
        id: 'ip_status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Employee', value: 'employee' },
          { label: 'Self-Employed', value: 'self_employed' },
          { label: 'Contractor', value: 'contractor' },
          { label: 'Member of Public', value: 'public' },
        ],
        width: 'half',
        section: 'Injured Person',
      },
      {
        id: 'injury_nature',
        label: 'Nature of Injury / Disease',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Injured Person',
      },
      { id: 'section_circumstances', label: 'Circumstances', type: 'section' },
      {
        id: 'location',
        label: 'Location',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Circumstances',
      },
      {
        id: 'activity',
        label: 'Activity at Time',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Circumstances',
      },
      {
        id: 'description',
        label: 'How the Incident Occurred',
        type: 'textarea',
        required: true,
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Circumstances',
      },
      {
        id: 'notifier_name',
        label: 'Notifier Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Circumstances',
      },
      {
        id: 'notifier_signature',
        label: 'Notifier Signature',
        type: 'signature',
        required: true,
        section: 'Circumstances',
      },
    ],
  },
  {
    code: 'TPL-INC-005',
    name: 'Incident Investigation Report',
    description:
      'Detailed investigation report for root cause analysis, contributing factors, corrective actions, and lessons learned following an incident.',
    module: 'INCIDENTS',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['investigation', 'root-cause', '5-whys', 'corrective-action'],
    isoClause: '10.2',
    fields: [
      { id: 'section_ref', label: 'Investigation Details', type: 'section' },
      {
        id: 'investigation_ref',
        label: 'Investigation Reference',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Investigation Details',
      },
      {
        id: 'incident_ref',
        label: 'Related Incident Ref',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Investigation Details',
      },
      {
        id: 'investigator',
        label: 'Lead Investigator',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Investigation Details',
      },
      {
        id: 'investigation_date',
        label: 'Investigation Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Investigation Details',
      },
      {
        id: 'team_members',
        label: 'Investigation Team',
        type: 'textarea',
        placeholder: 'Name, role — one per line',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Investigation Details',
      },
      { id: 'section_analysis', label: 'Root Cause Analysis', type: 'section' },
      {
        id: 'method',
        label: 'Analysis Method',
        type: 'select',
        required: true,
        options: [
          { label: '5 Whys', value: '5whys' },
          { label: 'Fishbone / Ishikawa', value: 'fishbone' },
          { label: 'Fault Tree', value: 'fault_tree' },
          { label: 'Bow-Tie', value: 'bowtie' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Root Cause Analysis',
      },
      {
        id: 'immediate_cause',
        label: 'Immediate Cause',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Root Cause Analysis',
      },
      {
        id: 'contributing_factors',
        label: 'Contributing Factors',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Root Cause Analysis',
      },
      {
        id: 'root_cause',
        label: 'Root Cause(s)',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Root Cause Analysis',
      },
      { id: 'section_actions', label: 'Corrective Actions', type: 'section' },
      {
        id: 'actions',
        label: 'Corrective & Preventive Actions',
        type: 'table',
        required: true,
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          {
            id: 'type',
            label: 'Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Corrective', value: 'corrective' },
              { label: 'Preventive', value: 'preventive' },
            ],
          },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Completed', value: 'completed' },
              { label: 'Verified', value: 'verified' },
            ],
          },
        ],
        section: 'Corrective Actions',
      },
      {
        id: 'lessons_learned',
        label: 'Lessons Learned',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Corrective Actions',
      },
      {
        id: 'investigator_signature',
        label: 'Lead Investigator Signature',
        type: 'signature',
        required: true,
        section: 'Corrective Actions',
      },
      {
        id: 'manager_signature',
        label: 'Manager Approval',
        type: 'signature',
        required: true,
        section: 'Corrective Actions',
      },
    ],
  },
];
