import type { TemplateDefinition } from '../types';

export const infosecTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-SEC-001',
    name: 'Security Incident Report',
    description:
      'Information security incident report for documenting security events, impact assessment, containment actions, and lessons learned. Aligned with ISO 27001.',
    module: 'INFOSEC',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['security-incident', 'breach', 'containment', 'iso-27001'],
    isoClause: 'A.16.1',
    fields: [
      { id: 'section_incident', label: 'Incident Details', type: 'section' },
      {
        id: 'incident_id',
        label: 'Incident ID',
        type: 'text',
        required: true,
        placeholder: 'e.g. SEC-INC-001',
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'date_detected',
        label: 'Date Detected',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'reported_by',
        label: 'Reported By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Critical', value: 'critical' },
          { label: 'High', value: 'high' },
          { label: 'Medium', value: 'medium' },
          { label: 'Low', value: 'low' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'incident_type',
        label: 'Incident Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Data Breach', value: 'data_breach' },
          { label: 'Malware', value: 'malware' },
          { label: 'Phishing', value: 'phishing' },
          { label: 'Unauthorised Access', value: 'unauthorised_access' },
          { label: 'Denial of Service', value: 'dos' },
          { label: 'Social Engineering', value: 'social_engineering' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'description',
        label: 'Incident Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe what happened, how it was detected, and affected systems...',
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Incident Details',
      },
      { id: 'section_impact', label: 'Impact Assessment', type: 'section' },
      {
        id: 'systems_affected',
        label: 'Systems Affected',
        type: 'textarea',
        required: true,
        placeholder: 'List affected systems, services, and data...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Impact Assessment',
      },
      {
        id: 'data_compromised',
        label: 'Data Compromised',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Personal Data', value: 'personal' },
          { label: 'Yes — Business Data', value: 'business' },
          { label: 'Yes — Both', value: 'both' },
          { label: 'No', value: 'none' },
          { label: 'Unknown', value: 'unknown' },
        ],
        width: 'half',
        section: 'Impact Assessment',
      },
      { id: 'section_response', label: 'Response & Containment', type: 'section' },
      {
        id: 'containment_actions',
        label: 'Containment Actions Taken',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Response & Containment',
      },
      {
        id: 'root_cause',
        label: 'Root Cause',
        type: 'textarea',
        placeholder: 'Identified root cause (if known)...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Response & Containment',
      },
      {
        id: 'lessons_learned',
        label: 'Lessons Learned',
        type: 'textarea',
        placeholder: 'What should be improved to prevent recurrence?',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Response & Containment',
      },
      {
        id: 'investigator_signature',
        label: 'Investigator Signature',
        type: 'signature',
        required: true,
        section: 'Response & Containment',
      },
    ],
  },
  {
    code: 'TPL-SEC-002',
    name: 'Information Security Risk Assessment',
    description:
      'Risk assessment template for identifying, evaluating, and treating information security risks. Aligned with ISO 27001:2022 clause 6.1.2.',
    module: 'INFOSEC',
    category: 'RISK_ASSESSMENT',
    tags: ['risk-assessment', 'iso-27001', 'threats', 'vulnerabilities', 'risk-treatment'],
    isoClause: '6.1.2',
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      {
        id: 'assessment_title',
        label: 'Assessment Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Assessment Details',
      },
      {
        id: 'assessor',
        label: 'Assessor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'scope',
        label: 'Scope',
        type: 'textarea',
        required: true,
        placeholder: 'Define the scope of this risk assessment...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Assessment Details',
      },
      { id: 'section_risks', label: 'Risk Register', type: 'section' },
      {
        id: 'risks',
        label: 'Risks',
        type: 'table',
        required: true,
        columns: [
          { id: 'asset', label: 'Asset / Process', type: 'text', required: true },
          { id: 'threat', label: 'Threat', type: 'text', required: true },
          { id: 'vulnerability', label: 'Vulnerability', type: 'text', required: true },
          {
            id: 'likelihood',
            label: 'Likelihood (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'impact',
            label: 'Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'risk_level',
            label: 'Risk Level',
            type: 'select',
            required: true,
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          {
            id: 'treatment',
            label: 'Treatment',
            type: 'select',
            required: true,
            options: [
              { label: 'Mitigate', value: 'mitigate' },
              { label: 'Accept', value: 'accept' },
              { label: 'Transfer', value: 'transfer' },
              { label: 'Avoid', value: 'avoid' },
            ],
          },
          {
            id: 'controls',
            label: 'Controls',
            type: 'text',
            placeholder: 'Existing or planned controls',
          },
        ],
        section: 'Risk Register',
      },
      {
        id: 'summary',
        label: 'Assessment Summary',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Risk Register',
      },
    ],
  },
  {
    code: 'TPL-SEC-003',
    name: 'Access Review Checklist',
    description:
      'Periodic access review checklist for verifying user access rights, privileged accounts, and system permissions are appropriate and up to date.',
    module: 'INFOSEC',
    category: 'COMPLIANCE',
    tags: ['access-review', 'user-access', 'privileged-accounts', 'permissions'],
    isoClause: 'A.9.2',
    fields: [
      { id: 'section_header', label: 'Review Details', type: 'section' },
      {
        id: 'review_title',
        label: 'Review Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Review Details',
      },
      {
        id: 'reviewer',
        label: 'Reviewer',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Review Details',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Review Details',
      },
      {
        id: 'system',
        label: 'System / Application',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Review Details',
      },
      { id: 'section_accounts', label: 'Account Review', type: 'section' },
      {
        id: 'accounts',
        label: 'User Accounts',
        type: 'table',
        required: true,
        columns: [
          { id: 'username', label: 'Username', type: 'text', required: true },
          { id: 'role', label: 'Role / Group', type: 'text', required: true },
          {
            id: 'privileged',
            label: 'Privileged?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
          { id: 'last_login', label: 'Last Login', type: 'date' },
          {
            id: 'appropriate',
            label: 'Access Appropriate?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No — Revoke', value: 'revoke' },
              { label: 'No — Modify', value: 'modify' },
            ],
          },
          {
            id: 'action',
            label: 'Action Required',
            type: 'text',
            placeholder: 'Describe action if not appropriate',
          },
        ],
        section: 'Account Review',
      },
      {
        id: 'findings',
        label: 'Review Findings',
        type: 'textarea',
        required: true,
        validation: { minLength: 10, maxLength: 3000 },
        width: 'full',
        section: 'Account Review',
      },
      {
        id: 'reviewer_signature',
        label: 'Reviewer Signature',
        type: 'signature',
        required: true,
        section: 'Account Review',
      },
    ],
  },
  {
    code: 'TPL-SEC-004',
    name: 'Business Impact Analysis (BIA) Worksheet',
    description:
      'Business impact analysis worksheet for identifying critical business processes, recovery time objectives (RTO), recovery point objectives (RPO), dependencies, and impact levels. Supports ISO 27001 business continuity planning.',
    module: 'INFOSEC',
    category: 'RISK_ASSESSMENT',
    tags: ['bia', 'business-impact', 'continuity', 'rto', 'rpo', 'iso-27001', 'disaster-recovery'],
    isoClause: 'A.17.1',
    fields: [
      { id: 'section_header', label: 'BIA Details', type: 'section' },
      {
        id: 'bia_title',
        label: 'BIA Title',
        type: 'text',
        required: true,
        placeholder: 'e.g. Annual BIA — Finance Department',
        width: 'full',
        section: 'BIA Details',
      },
      {
        id: 'analyst',
        label: 'Analyst',
        type: 'text',
        required: true,
        width: 'half',
        section: 'BIA Details',
      },
      {
        id: 'department',
        label: 'Department / Business Unit',
        type: 'text',
        required: true,
        width: 'half',
        section: 'BIA Details',
      },
      {
        id: 'date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'BIA Details',
      },
      {
        id: 'review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'BIA Details',
      },
      {
        id: 'scope',
        label: 'Scope of Analysis',
        type: 'textarea',
        required: true,
        placeholder:
          'Define the scope of this BIA including departments, systems, and processes covered...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'BIA Details',
      },
      {
        id: 'section_processes',
        label: 'Critical Business Processes',
        type: 'section',
        helpText: 'Identify each critical business process and assess its recovery requirements.',
      },
      {
        id: 'processes',
        label: 'Critical Processes',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'process_name',
            label: 'Process Name',
            type: 'text',
            required: true,
            placeholder: 'e.g. Payroll Processing',
          },
          { id: 'process_owner', label: 'Process Owner', type: 'text', required: true },
          {
            id: 'criticality',
            label: 'Criticality',
            type: 'select',
            required: true,
            options: [
              { label: 'Mission Critical', value: 'mission_critical' },
              { label: 'Business Critical', value: 'business_critical' },
              { label: 'Important', value: 'important' },
              { label: 'Non-Critical', value: 'non_critical' },
            ],
          },
          {
            id: 'rto',
            label: 'RTO',
            type: 'select',
            required: true,
            options: [
              { label: '< 1 hour', value: '1h' },
              { label: '< 4 hours', value: '4h' },
              { label: '< 8 hours', value: '8h' },
              { label: '< 24 hours', value: '24h' },
              { label: '< 72 hours', value: '72h' },
              { label: '> 72 hours', value: '72h_plus' },
            ],
          },
          {
            id: 'rpo',
            label: 'RPO',
            type: 'select',
            required: true,
            options: [
              { label: 'Zero (no data loss)', value: 'zero' },
              { label: '< 1 hour', value: '1h' },
              { label: '< 4 hours', value: '4h' },
              { label: '< 24 hours', value: '24h' },
              { label: '< 7 days', value: '7d' },
            ],
          },
          {
            id: 'mtpd',
            label: 'Max Tolerable Downtime',
            type: 'text',
            required: true,
            placeholder: 'e.g. 48 hours',
          },
          {
            id: 'peak_periods',
            label: 'Peak Periods',
            type: 'text',
            placeholder: 'e.g. Month-end, Year-end',
          },
        ],
        section: 'Critical Business Processes',
      },
      {
        id: 'section_impact',
        label: 'Impact Assessment',
        type: 'section',
        helpText: 'Assess impact of disruption at key time intervals.',
      },
      {
        id: 'impact_assessment',
        label: 'Impact by Time Interval',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'process_ref',
            label: 'Process',
            type: 'text',
            required: true,
            placeholder: 'Reference from above',
          },
          {
            id: 'impact_1h',
            label: 'Impact at 1 Hour',
            type: 'select',
            required: true,
            options: [
              { label: 'None', value: 'none' },
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Critical', value: 'critical' },
            ],
          },
          {
            id: 'impact_8h',
            label: 'Impact at 8 Hours',
            type: 'select',
            required: true,
            options: [
              { label: 'None', value: 'none' },
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Critical', value: 'critical' },
            ],
          },
          {
            id: 'impact_24h',
            label: 'Impact at 24 Hours',
            type: 'select',
            required: true,
            options: [
              { label: 'None', value: 'none' },
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Critical', value: 'critical' },
            ],
          },
          {
            id: 'impact_72h',
            label: 'Impact at 72 Hours',
            type: 'select',
            required: true,
            options: [
              { label: 'None', value: 'none' },
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Critical', value: 'critical' },
            ],
          },
          {
            id: 'financial_impact',
            label: 'Estimated Financial Impact',
            type: 'text',
            placeholder: 'e.g. $50,000/day',
          },
          {
            id: 'reputational_impact',
            label: 'Reputational Impact',
            type: 'select',
            required: true,
            options: [
              { label: 'None', value: 'none' },
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Severe', value: 'severe' },
            ],
          },
        ],
        section: 'Impact Assessment',
      },
      {
        id: 'section_dependencies',
        label: 'Dependencies & Resources',
        type: 'section',
        helpText: 'Identify dependencies required for each critical process to operate.',
      },
      {
        id: 'dependencies',
        label: 'Dependencies',
        type: 'table',
        required: true,
        columns: [
          { id: 'process_ref', label: 'Process', type: 'text', required: true },
          {
            id: 'dependency_type',
            label: 'Dependency Type',
            type: 'select',
            required: true,
            options: [
              { label: 'IT System', value: 'it_system' },
              { label: 'Application', value: 'application' },
              { label: 'Third-Party Service', value: 'third_party' },
              { label: 'Personnel', value: 'personnel' },
              { label: 'Facility', value: 'facility' },
              { label: 'Equipment', value: 'equipment' },
              { label: 'Data / Records', value: 'data' },
            ],
          },
          {
            id: 'dependency_name',
            label: 'Dependency Name',
            type: 'text',
            required: true,
            placeholder: 'e.g. SAP ERP, AWS eu-west-1',
          },
          {
            id: 'single_point_of_failure',
            label: 'Single Point of Failure?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
          {
            id: 'alternative',
            label: 'Alternative / Workaround',
            type: 'text',
            placeholder: 'Manual process or backup system',
          },
        ],
        section: 'Dependencies & Resources',
      },
      { id: 'section_summary', label: 'Summary & Recommendations', type: 'section' },
      {
        id: 'key_findings',
        label: 'Key Findings',
        type: 'textarea',
        required: true,
        placeholder: 'Summarise the most critical findings from this BIA...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Summary & Recommendations',
      },
      {
        id: 'recommendations',
        label: 'Recommendations',
        type: 'textarea',
        required: true,
        placeholder: 'List recommended actions to improve business continuity posture...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Summary & Recommendations',
      },
      {
        id: 'analyst_signature',
        label: 'Analyst Signature',
        type: 'signature',
        required: true,
        section: 'Summary & Recommendations',
      },
      {
        id: 'management_approval',
        label: 'Management Approval Signature',
        type: 'signature',
        required: true,
        section: 'Summary & Recommendations',
      },
    ],
  },
  {
    code: 'TPL-SEC-005',
    name: 'Supplier Security Assessment',
    description:
      'Third-party supplier security assessment questionnaire for evaluating information security controls, data handling practices, certifications, and compliance posture before and during supplier engagements. Aligned with ISO 27001 Annex A.15.',
    module: 'INFOSEC',
    category: 'COMPLIANCE',
    tags: [
      'supplier-security',
      'third-party',
      'vendor-assessment',
      'data-handling',
      'iso-27001',
      'supply-chain',
    ],
    isoClause: 'A.15.1',
    fields: [
      { id: 'section_supplier', label: 'Supplier Information', type: 'section' },
      {
        id: 'supplier_name',
        label: 'Supplier Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'supplier_contact',
        label: 'Primary Contact',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'supplier_email',
        label: 'Contact Email',
        type: 'email',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'supplier_website',
        label: 'Supplier Website',
        type: 'url',
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'service_description',
        label: 'Service / Product Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the services or products the supplier will provide...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Supplier Information',
      },
      {
        id: 'data_access_level',
        label: 'Data Access Level',
        type: 'select',
        required: true,
        options: [
          { label: 'No Data Access', value: 'none' },
          { label: 'Non-Sensitive Data Only', value: 'non_sensitive' },
          { label: 'Personal Data (PII)', value: 'pii' },
          { label: 'Sensitive / Confidential Data', value: 'sensitive' },
          { label: 'Highly Restricted Data', value: 'highly_restricted' },
        ],
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'contract_value',
        label: 'Annual Contract Value',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'assessor',
        label: 'Assessed By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'assessment_date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'section_certifications',
        label: 'Certifications & Compliance',
        type: 'section',
        helpText: "Record the supplier's current security certifications and compliance status.",
      },
      {
        id: 'certifications',
        label: 'Certifications Held',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'certification',
            label: 'Certification / Standard',
            type: 'select',
            required: true,
            options: [
              { label: 'ISO 27001', value: 'iso27001' },
              { label: 'SOC 2 Type II', value: 'soc2' },
              { label: 'SOC 1 Type II', value: 'soc1' },
              { label: 'PCI DSS', value: 'pci_dss' },
              { label: 'GDPR Compliant', value: 'gdpr' },
              { label: 'Cyber Essentials Plus', value: 'ce_plus' },
              { label: 'NIST CSF', value: 'nist_csf' },
              { label: 'Other', value: 'other' },
            ],
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Certified / Active', value: 'certified' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Expired', value: 'expired' },
              { label: 'Not Applicable', value: 'na' },
            ],
          },
          { id: 'expiry_date', label: 'Expiry Date', type: 'date' },
          {
            id: 'evidence',
            label: 'Evidence Provided',
            type: 'select',
            required: true,
            options: [
              { label: 'Certificate Provided', value: 'certificate' },
              { label: 'Self-Attestation', value: 'self_attest' },
              { label: 'Audit Report Provided', value: 'audit_report' },
              { label: 'Not Provided', value: 'not_provided' },
            ],
          },
        ],
        section: 'Certifications & Compliance',
      },
      {
        id: 'section_security_controls',
        label: 'Security Controls Assessment',
        type: 'section',
        helpText: "Evaluate the supplier's security controls across key domains.",
      },
      {
        id: 'controls_assessment',
        label: 'Controls Assessment',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'domain',
            label: 'Control Domain',
            type: 'select',
            required: true,
            options: [
              { label: 'Access Control', value: 'access_control' },
              { label: 'Encryption', value: 'encryption' },
              { label: 'Network Security', value: 'network' },
              { label: 'Endpoint Protection', value: 'endpoint' },
              { label: 'Patch Management', value: 'patching' },
              { label: 'Logging & Monitoring', value: 'logging' },
              { label: 'Incident Response', value: 'incident_response' },
              { label: 'Business Continuity', value: 'bc' },
              { label: 'Physical Security', value: 'physical' },
              { label: 'HR Security', value: 'hr_security' },
            ],
          },
          {
            id: 'question',
            label: 'Assessment Question',
            type: 'text',
            required: true,
            placeholder: 'e.g. Is MFA enforced for all privileged access?',
          },
          {
            id: 'response',
            label: 'Supplier Response',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes — Fully Implemented', value: 'yes' },
              { label: 'Partially Implemented', value: 'partial' },
              { label: 'Not Implemented', value: 'no' },
              { label: 'Not Applicable', value: 'na' },
            ],
          },
          {
            id: 'risk_rating',
            label: 'Risk Rating',
            type: 'select',
            required: true,
            options: [
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Critical', value: 'critical' },
            ],
          },
          {
            id: 'notes',
            label: 'Notes / Evidence',
            type: 'text',
            placeholder: 'Additional detail or evidence reference',
          },
        ],
        section: 'Security Controls Assessment',
      },
      {
        id: 'section_data_handling',
        label: 'Data Handling & Privacy',
        type: 'section',
        helpText:
          "Assess how the supplier handles, stores, and processes your organisation's data.",
      },
      {
        id: 'data_location',
        label: 'Data Storage Location(s)',
        type: 'textarea',
        required: true,
        placeholder:
          'List all locations where data will be stored or processed (countries, data centres)...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Data Handling & Privacy',
      },
      {
        id: 'encryption_at_rest',
        label: 'Encryption at Rest',
        type: 'select',
        required: true,
        options: [
          { label: 'AES-256', value: 'aes256' },
          { label: 'AES-128', value: 'aes128' },
          { label: 'Other Encryption', value: 'other' },
          { label: 'Not Encrypted', value: 'none' },
          { label: 'Unknown', value: 'unknown' },
        ],
        width: 'half',
        section: 'Data Handling & Privacy',
      },
      {
        id: 'encryption_in_transit',
        label: 'Encryption in Transit',
        type: 'select',
        required: true,
        options: [
          { label: 'TLS 1.3', value: 'tls13' },
          { label: 'TLS 1.2', value: 'tls12' },
          { label: 'Other', value: 'other' },
          { label: 'Not Encrypted', value: 'none' },
          { label: 'Unknown', value: 'unknown' },
        ],
        width: 'half',
        section: 'Data Handling & Privacy',
      },
      {
        id: 'data_retention_policy',
        label: 'Data Retention Policy',
        type: 'textarea',
        placeholder: "Describe the supplier's data retention and deletion policy...",
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Data Handling & Privacy',
      },
      {
        id: 'subprocessors',
        label: 'Sub-Processors Used',
        type: 'textarea',
        placeholder: 'List any sub-processors or fourth parties who will access the data...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Data Handling & Privacy',
      },
      { id: 'section_incident', label: 'Incident Response & Breach Notification', type: 'section' },
      {
        id: 'has_incident_plan',
        label: 'Documented Incident Response Plan?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'In Development', value: 'in_dev' },
        ],
        width: 'half',
        section: 'Incident Response & Breach Notification',
      },
      {
        id: 'breach_notification_sla',
        label: 'Breach Notification SLA',
        type: 'select',
        required: true,
        options: [
          { label: '< 24 hours', value: '24h' },
          { label: '< 48 hours', value: '48h' },
          { label: '< 72 hours', value: '72h' },
          { label: 'No Defined SLA', value: 'none' },
        ],
        width: 'half',
        section: 'Incident Response & Breach Notification',
      },
      {
        id: 'last_incident',
        label: 'Last Security Incident',
        type: 'textarea',
        placeholder: 'Describe the most recent security incident (if any) and remediation taken...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Incident Response & Breach Notification',
      },
      { id: 'section_outcome', label: 'Assessment Outcome', type: 'section' },
      {
        id: 'overall_risk',
        label: 'Overall Supplier Risk Rating',
        type: 'select',
        required: true,
        options: [
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
          { label: 'Critical', value: 'critical' },
        ],
        width: 'half',
        section: 'Assessment Outcome',
      },
      {
        id: 'recommendation',
        label: 'Recommendation',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Approved with Conditions', value: 'conditional' },
          { label: 'Rejected', value: 'rejected' },
          { label: 'Requires Further Assessment', value: 'further' },
        ],
        width: 'half',
        section: 'Assessment Outcome',
      },
      {
        id: 'conditions',
        label: 'Conditions / Required Improvements',
        type: 'textarea',
        placeholder: 'List any conditions that must be met before or during the engagement...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Assessment Outcome',
      },
      {
        id: 'reassessment_date',
        label: 'Reassessment Due Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Outcome',
      },
      {
        id: 'findings_summary',
        label: 'Findings Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Summarise the key findings from this assessment...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Assessment Outcome',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Assessment Outcome',
      },
      {
        id: 'iso_manager_signature',
        label: 'Information Security Manager Signature',
        type: 'signature',
        required: true,
        section: 'Assessment Outcome',
      },
    ],
  },
];
