import type { TemplateDefinition } from '../types';

export const infosecTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-SEC-001',
    name: 'Security Incident Report',
    description:
      'Information security incident report for documenting security events, impact assessment, containment actions, and lessons learned. Aligned with ISO 27001.',
    module: 'INFOSEC',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['security-incident', 'breach', 'containment', 'iso-27001'],
    isoClause: 'A.16.1',
    fields: [
      { id: 'section_incident', label: 'Incident Details', type: 'section' },
      { id: 'incident_id', label: 'Incident ID', type: 'text', required: true, placeholder: 'e.g. SEC-INC-001', width: 'half', section: 'Incident Details' },
      { id: 'date_detected', label: 'Date Detected', type: 'datetime', required: true, width: 'half', section: 'Incident Details' },
      { id: 'reported_by', label: 'Reported By', type: 'text', required: true, width: 'half', section: 'Incident Details' },
      { id: 'severity', label: 'Severity', type: 'select', required: true, options: [{ label: 'Critical', value: 'critical' }, { label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }], width: 'half', section: 'Incident Details' },
      { id: 'incident_type', label: 'Incident Type', type: 'select', required: true, options: [{ label: 'Data Breach', value: 'data_breach' }, { label: 'Malware', value: 'malware' }, { label: 'Phishing', value: 'phishing' }, { label: 'Unauthorised Access', value: 'unauthorised_access' }, { label: 'Denial of Service', value: 'dos' }, { label: 'Social Engineering', value: 'social_engineering' }, { label: 'Other', value: 'other' }], width: 'half', section: 'Incident Details' },
      { id: 'description', label: 'Incident Description', type: 'textarea', required: true, placeholder: 'Describe what happened, how it was detected, and affected systems...', validation: { minLength: 50, maxLength: 5000 }, width: 'full', section: 'Incident Details' },
      { id: 'section_impact', label: 'Impact Assessment', type: 'section' },
      { id: 'systems_affected', label: 'Systems Affected', type: 'textarea', required: true, placeholder: 'List affected systems, services, and data...', validation: { maxLength: 2000 }, width: 'full', section: 'Impact Assessment' },
      { id: 'data_compromised', label: 'Data Compromised', type: 'select', required: true, options: [{ label: 'Yes — Personal Data', value: 'personal' }, { label: 'Yes — Business Data', value: 'business' }, { label: 'Yes — Both', value: 'both' }, { label: 'No', value: 'none' }, { label: 'Unknown', value: 'unknown' }], width: 'half', section: 'Impact Assessment' },
      { id: 'section_response', label: 'Response & Containment', type: 'section' },
      { id: 'containment_actions', label: 'Containment Actions Taken', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Response & Containment' },
      { id: 'root_cause', label: 'Root Cause', type: 'textarea', placeholder: 'Identified root cause (if known)...', validation: { maxLength: 2000 }, width: 'full', section: 'Response & Containment' },
      { id: 'lessons_learned', label: 'Lessons Learned', type: 'textarea', placeholder: 'What should be improved to prevent recurrence?', validation: { maxLength: 2000 }, width: 'full', section: 'Response & Containment' },
      { id: 'investigator_signature', label: 'Investigator Signature', type: 'signature', required: true, section: 'Response & Containment' },
    ],
  },
  {
    code: 'TPL-SEC-002',
    name: 'Information Security Risk Assessment',
    description:
      'Risk assessment template for identifying, evaluating, and treating information security risks. Aligned with ISO 27001:2022 clause 6.1.2.',
    module: 'INFOSEC',
    category: 'RISK_ASSESSMENT',
    tags: ['risk-assessment', 'iso-27001', 'threats', 'vulnerabilities', 'risk-treatment'],
    isoClause: '6.1.2',
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      { id: 'assessment_title', label: 'Assessment Title', type: 'text', required: true, width: 'full', section: 'Assessment Details' },
      { id: 'assessor', label: 'Assessor', type: 'text', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'date', label: 'Assessment Date', type: 'date', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'scope', label: 'Scope', type: 'textarea', required: true, placeholder: 'Define the scope of this risk assessment...', validation: { maxLength: 2000 }, width: 'full', section: 'Assessment Details' },
      { id: 'section_risks', label: 'Risk Register', type: 'section' },
      {
        id: 'risks',
        label: 'Risks',
        type: 'table',
        required: true,
        columns: [
          { id: 'asset', label: 'Asset / Process', type: 'text', required: true },
          { id: 'threat', label: 'Threat', type: 'text', required: true },
          { id: 'vulnerability', label: 'Vulnerability', type: 'text', required: true },
          { id: 'likelihood', label: 'Likelihood (1-5)', type: 'rating', required: true, validation: { min: 1, max: 5 } },
          { id: 'impact', label: 'Impact (1-5)', type: 'rating', required: true, validation: { min: 1, max: 5 } },
          { id: 'risk_level', label: 'Risk Level', type: 'select', required: true, options: [{ label: 'Critical', value: 'critical' }, { label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
          { id: 'treatment', label: 'Treatment', type: 'select', required: true, options: [{ label: 'Mitigate', value: 'mitigate' }, { label: 'Accept', value: 'accept' }, { label: 'Transfer', value: 'transfer' }, { label: 'Avoid', value: 'avoid' }] },
          { id: 'controls', label: 'Controls', type: 'text', placeholder: 'Existing or planned controls' },
        ],
        section: 'Risk Register',
      },
      { id: 'summary', label: 'Assessment Summary', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Risk Register' },
    ],
  },
  {
    code: 'TPL-SEC-003',
    name: 'Access Review Checklist',
    description:
      'Periodic access review checklist for verifying user access rights, privileged accounts, and system permissions are appropriate and up to date.',
    module: 'INFOSEC',
    category: 'COMPLIANCE',
    tags: ['access-review', 'user-access', 'privileged-accounts', 'permissions'],
    isoClause: 'A.9.2',
    fields: [
      { id: 'section_header', label: 'Review Details', type: 'section' },
      { id: 'review_title', label: 'Review Title', type: 'text', required: true, width: 'full', section: 'Review Details' },
      { id: 'reviewer', label: 'Reviewer', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'review_date', label: 'Review Date', type: 'date', required: true, width: 'half', section: 'Review Details' },
      { id: 'system', label: 'System / Application', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'section_accounts', label: 'Account Review', type: 'section' },
      {
        id: 'accounts',
        label: 'User Accounts',
        type: 'table',
        required: true,
        columns: [
          { id: 'username', label: 'Username', type: 'text', required: true },
          { id: 'role', label: 'Role / Group', type: 'text', required: true },
          { id: 'privileged', label: 'Privileged?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }] },
          { id: 'last_login', label: 'Last Login', type: 'date' },
          { id: 'appropriate', label: 'Access Appropriate?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No — Revoke', value: 'revoke' }, { label: 'No — Modify', value: 'modify' }] },
          { id: 'action', label: 'Action Required', type: 'text', placeholder: 'Describe action if not appropriate' },
        ],
        section: 'Account Review',
      },
      { id: 'findings', label: 'Review Findings', type: 'textarea', required: true, validation: { minLength: 10, maxLength: 3000 }, width: 'full', section: 'Account Review' },
      { id: 'reviewer_signature', label: 'Reviewer Signature', type: 'signature', required: true, section: 'Account Review' },
    ],
  },
];
