// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.
import type { TemplateDefinition } from '../types';

export const inventoryTemplates: TemplateDefinition[] = [
  // ───────────────────────────────────────────────
  // TPL-INV-001  Goods Receipt Note
  // ───────────────────────────────────────────────
  {
    code: 'TPL-INV-001',
    name: 'Goods Receipt Note',
    description:
      'Standard goods receipt note (GRN) for recording the receipt and inspection of materials, parts, or equipment delivered by suppliers against a purchase order.',
    module: 'INVENTORY',
    category: 'INSPECTION',
    tags: ['goods-receipt', 'GRN', 'receiving', 'inspection', 'supplier', 'purchase-order'],
    fields: [
      // ── Section: Receipt Details ──
      {
        id: 'section_receipt',
        label: 'Receipt Details',
        type: 'section',
        helpText: 'Basic identification of the goods receipt.',
      },
      {
        id: 'grn_number',
        label: 'GRN Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. GRN-2026-0153',
        helpText: 'Unique goods receipt note reference number.',
        width: 'third',
        section: 'Receipt Details',
      },
      {
        id: 'date',
        label: 'Receipt Date',
        type: 'date',
        required: true,
        width: 'third',
        section: 'Receipt Details',
      },
      {
        id: 'supplier',
        label: 'Supplier',
        type: 'text',
        required: true,
        placeholder: 'e.g. Acme Components Ltd',
        helpText: 'Name of the supplier who delivered the goods.',
        width: 'third',
        section: 'Receipt Details',
      },
      {
        id: 'po_reference',
        label: 'Purchase Order Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. PO-2026-0087',
        helpText: 'The purchase order number this delivery relates to.',
        width: 'half',
        section: 'Receipt Details',
      },
      {
        id: 'delivery_note_ref',
        label: 'Delivery Note Reference',
        type: 'text',
        placeholder: 'Supplier delivery note number if available',
        width: 'half',
        section: 'Receipt Details',
      },

      // ── Section: Line Items ──
      {
        id: 'section_items',
        label: 'Received Items',
        type: 'section',
        helpText: 'Record each item received, comparing against the PO quantity.',
      },
      {
        id: 'items',
        label: 'Items Received',
        type: 'table',
        required: true,
        helpText:
          'Enter each line item with quantities ordered, received, and rejected. Flag any condition issues.',
        columns: [
          {
            id: 'item_code',
            label: 'Item Code',
            type: 'text',
            required: true,
            placeholder: 'e.g. COMP-A1234',
          },
          {
            id: 'description',
            label: 'Description',
            type: 'text',
            required: true,
            placeholder: 'e.g. M8 hex bolt, stainless steel',
          },
          {
            id: 'quantity_ordered',
            label: 'Qty Ordered',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'quantity_received',
            label: 'Qty Received',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'quantity_rejected',
            label: 'Qty Rejected',
            type: 'number',
            required: true,
            validation: { min: 0 },
            defaultValue: 0,
          },
          {
            id: 'unit',
            label: 'Unit',
            type: 'text',
            required: true,
            placeholder: 'e.g. pcs, kg, m',
          },
          {
            id: 'condition',
            label: 'Condition',
            type: 'select',
            required: true,
            options: [
              { label: 'Good', value: 'good' },
              { label: 'Damaged', value: 'damaged' },
              { label: 'Short', value: 'short' },
            ],
          },
        ],
        section: 'Received Items',
      },

      // ── Section: Inspection ──
      {
        id: 'section_inspection',
        label: 'Inspection',
        type: 'section',
        helpText: 'Incoming inspection result and disposition.',
      },
      {
        id: 'inspection_result',
        label: 'Inspection Result',
        type: 'select',
        required: true,
        helpText: 'Overall inspection disposition for this delivery.',
        options: [
          { label: 'Accepted', value: 'accepted' },
          { label: 'Rejected', value: 'rejected' },
          { label: 'Partial Accept (see rejected quantities)', value: 'partial' },
        ],
        width: 'half',
        section: 'Inspection',
      },
      {
        id: 'inspection_notes',
        label: 'Inspection Notes',
        type: 'textarea',
        placeholder:
          'Record any non-conformances, damage details, certificate discrepancies, or other inspection findings...',
        helpText:
          'Include lot/batch numbers, certificate of conformance checks, and any deviations.',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Inspection',
      },

      // ── Section: Sign-Off ──
      {
        id: 'section_signoff',
        label: 'Sign-Off',
        type: 'section',
        helpText: 'Confirmation of receipt and inspection by authorised personnel.',
      },
      {
        id: 'receiver_signature',
        label: 'Receiver Signature',
        type: 'signature',
        required: true,
        helpText: 'The person who physically received the goods at the loading dock or stores.',
        section: 'Sign-Off',
      },
      {
        id: 'inspector_signature',
        label: 'Inspector Signature',
        type: 'signature',
        required: true,
        helpText: 'The quality or stores inspector who checked the goods.',
        section: 'Sign-Off',
      },
      {
        id: 'notes',
        label: 'Additional Notes',
        type: 'textarea',
        placeholder: 'Any other notes, follow-up actions, or NCR references...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Sign-Off',
      },
    ],
  },

  // ───────────────────────────────────────────────
  // TPL-INV-002  Stock Count Sheet
  // ───────────────────────────────────────────────
  {
    code: 'TPL-INV-002',
    name: 'Stock Count Sheet',
    description:
      'Physical stock count sheet for verifying actual inventory against system records, identifying variances, and recording reconciliation actions.',
    module: 'INVENTORY',
    category: 'INSPECTION',
    tags: ['stock-count', 'stocktake', 'inventory-check', 'physical-count', 'reconciliation'],
    fields: [
      // ── Section: Count Details ──
      {
        id: 'section_count',
        label: 'Count Details',
        type: 'section',
        helpText: 'Identify the scope and participants of this stock count.',
      },
      {
        id: 'count_date',
        label: 'Count Date',
        type: 'date',
        required: true,
        width: 'third',
        section: 'Count Details',
      },
      {
        id: 'location',
        label: 'Location / Warehouse',
        type: 'text',
        required: true,
        placeholder: 'e.g. Warehouse A, Zone 3',
        helpText: 'The physical location or warehouse area being counted.',
        width: 'third',
        section: 'Count Details',
      },
      {
        id: 'counter_name',
        label: 'Counter Name',
        type: 'text',
        required: true,
        placeholder: 'Name of the person performing the count',
        width: 'third',
        section: 'Count Details',
      },
      {
        id: 'supervisor',
        label: 'Supervisor',
        type: 'text',
        required: true,
        placeholder: 'Name of the supervising manager',
        helpText: 'The person responsible for overseeing and verifying the count.',
        width: 'half',
        section: 'Count Details',
      },
      {
        id: 'count_type',
        label: 'Count Type',
        type: 'select',
        helpText: 'Select the type of stock count being performed.',
        options: [
          { label: 'Full Stock Take', value: 'full' },
          { label: 'Cycle Count', value: 'cycle' },
          { label: 'Spot Check', value: 'spot' },
          { label: 'Year-End Count', value: 'year_end' },
        ],
        width: 'half',
        section: 'Count Details',
      },

      // ── Section: Count Items ──
      {
        id: 'section_items',
        label: 'Count Items',
        type: 'section',
        helpText: 'Record each item counted with system quantity and actual quantity.',
      },
      {
        id: 'items',
        label: 'Stock Count Items',
        type: 'table',
        required: true,
        helpText:
          'For each item, record the system (expected) quantity and the physically counted quantity. Variance is the difference.',
        columns: [
          {
            id: 'item_code',
            label: 'Item Code',
            type: 'text',
            required: true,
            placeholder: 'e.g. COMP-A1234',
          },
          {
            id: 'description',
            label: 'Description',
            type: 'text',
            required: true,
            placeholder: 'e.g. M8 hex bolt, stainless steel',
          },
          {
            id: 'bin_location',
            label: 'Bin Location',
            type: 'text',
            required: true,
            placeholder: 'e.g. A-03-12',
          },
          {
            id: 'system_quantity',
            label: 'System Qty',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'counted_quantity',
            label: 'Counted Qty',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'variance',
            label: 'Variance',
            type: 'number',
            helpText: 'Counted minus System quantity. Auto-calculated where possible.',
          },
          {
            id: 'unit',
            label: 'Unit',
            type: 'text',
            required: true,
            placeholder: 'e.g. pcs, kg, m',
          },
          {
            id: 'notes',
            label: 'Notes',
            type: 'text',
            placeholder: 'e.g. damaged items, wrong location',
          },
        ],
        section: 'Count Items',
      },

      // ── Section: Summary ──
      {
        id: 'section_summary',
        label: 'Count Summary',
        type: 'section',
        helpText: 'Overall results of the stock count.',
      },
      {
        id: 'total_items_counted',
        label: 'Total Items Counted',
        type: 'number',
        required: true,
        placeholder: 'e.g. 342',
        helpText: 'Total number of unique item lines counted.',
        validation: { min: 0 },
        width: 'half',
        section: 'Count Summary',
      },
      {
        id: 'discrepancies_found',
        label: 'Discrepancies Found',
        type: 'number',
        required: true,
        placeholder: 'e.g. 12',
        helpText: 'Number of item lines with a non-zero variance.',
        validation: { min: 0 },
        width: 'half',
        section: 'Count Summary',
      },
      {
        id: 'accuracy_rate',
        label: 'Accuracy Rate (%)',
        type: 'number',
        placeholder: 'e.g. 96.5',
        helpText: 'Percentage of items where system quantity matched counted quantity.',
        validation: { min: 0, max: 100 },
        width: 'half',
        section: 'Count Summary',
      },

      // ── Section: Reconciliation ──
      {
        id: 'section_reconciliation',
        label: 'Reconciliation',
        type: 'section',
        helpText: 'Actions taken to investigate and resolve discrepancies.',
      },
      {
        id: 'reconciliation_notes',
        label: 'Reconciliation Notes',
        type: 'textarea',
        required: true,
        placeholder:
          'Document investigations into variances, root causes identified, and corrective actions taken...',
        helpText: 'Include transaction reviews, recount results, and any system adjustments made.',
        validation: { minLength: 10, maxLength: 5000 },
        width: 'full',
        section: 'Reconciliation',
      },
      {
        id: 'adjustment_reference',
        label: 'System Adjustment Reference',
        type: 'text',
        placeholder: 'e.g. ADJ-2026-0042',
        helpText: 'Reference number for any inventory adjustment transactions posted.',
        width: 'half',
        section: 'Reconciliation',
      },

      // ── Section: Sign-Off ──
      {
        id: 'section_signoff',
        label: 'Sign-Off',
        type: 'section',
        helpText: 'Counter and supervisor confirm the count results are accurate.',
      },
      {
        id: 'counter_signature',
        label: 'Counter Signature',
        type: 'signature',
        required: true,
        helpText: 'The person who performed the physical count confirms accuracy.',
        section: 'Sign-Off',
      },
      {
        id: 'supervisor_signature',
        label: 'Supervisor Signature',
        type: 'signature',
        required: true,
        helpText:
          'The supervisor confirms the count was performed correctly and results are verified.',
        section: 'Sign-Off',
      },
    ],
  },
  {
    code: 'TPL-INV-003',
    name: 'Stock Transfer Note',
    description:
      'Form for recording the transfer of stock between locations, warehouses, or departments with authorisation and receipt confirmation.',
    module: 'INVENTORY',
    category: 'PROCESS_CONTROL',
    tags: ['stock-transfer', 'inter-warehouse', 'movement', 'logistics'],
    fields: [
      { id: 'section_transfer', label: 'Transfer Details', type: 'section' },
      {
        id: 'transfer_ref',
        label: 'Transfer Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. TRF-2026-001',
        width: 'half',
        section: 'Transfer Details',
      },
      {
        id: 'date',
        label: 'Transfer Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Transfer Details',
      },
      {
        id: 'from_location',
        label: 'From Location',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Transfer Details',
      },
      {
        id: 'to_location',
        label: 'To Location',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Transfer Details',
      },
      {
        id: 'reason',
        label: 'Reason for Transfer',
        type: 'select',
        required: true,
        options: [
          { label: 'Production Requirement', value: 'production' },
          { label: 'Rebalancing Stock', value: 'rebalance' },
          { label: 'Customer Order', value: 'customer' },
          { label: 'Maintenance', value: 'maintenance' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Transfer Details',
      },
      {
        id: 'requested_by',
        label: 'Requested By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Transfer Details',
      },
      { id: 'section_items', label: 'Items', type: 'section' },
      {
        id: 'items',
        label: 'Transfer Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'item_code', label: 'Item Code', type: 'text', required: true },
          { id: 'description', label: 'Description', type: 'text', required: true },
          {
            id: 'quantity',
            label: 'Quantity',
            type: 'number',
            required: true,
            validation: { min: 1 },
          },
          { id: 'unit', label: 'Unit', type: 'text', required: true },
          { id: 'batch_lot', label: 'Batch / Lot No.', type: 'text' },
        ],
        section: 'Items',
      },
      { id: 'section_signoff', label: 'Sign-Off', type: 'section' },
      {
        id: 'sender_signature',
        label: 'Sender Signature',
        type: 'signature',
        required: true,
        section: 'Sign-Off',
      },
      {
        id: 'receiver_signature',
        label: 'Receiver Signature',
        type: 'signature',
        required: true,
        section: 'Sign-Off',
      },
    ],
  },
  {
    code: 'TPL-INV-004',
    name: 'Inventory Adjustment Form',
    description:
      'Form for documenting inventory adjustments with justification, approval, and audit trail for write-offs, corrections, and reclassifications.',
    module: 'INVENTORY',
    category: 'COMPLIANCE',
    tags: ['adjustment', 'write-off', 'correction', 'inventory-control'],
    fields: [
      { id: 'section_adj', label: 'Adjustment Details', type: 'section' },
      {
        id: 'adj_ref',
        label: 'Adjustment Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. ADJ-2026-001',
        width: 'half',
        section: 'Adjustment Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Adjustment Details',
      },
      {
        id: 'requested_by',
        label: 'Requested By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Adjustment Details',
      },
      {
        id: 'adj_type',
        label: 'Adjustment Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Write-Off', value: 'write_off' },
          { label: 'Write-On', value: 'write_on' },
          { label: 'Quantity Correction', value: 'correction' },
          { label: 'Reclassification', value: 'reclassification' },
          { label: 'Scrap', value: 'scrap' },
          { label: 'Damage', value: 'damage' },
        ],
        width: 'half',
        section: 'Adjustment Details',
      },
      { id: 'section_items', label: 'Items', type: 'section' },
      {
        id: 'items',
        label: 'Adjustment Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'item_code', label: 'Item Code', type: 'text', required: true },
          { id: 'description', label: 'Description', type: 'text', required: true },
          { id: 'current_qty', label: 'Current Qty', type: 'number', required: true },
          { id: 'adjusted_qty', label: 'Adjusted Qty', type: 'number', required: true },
          { id: 'variance', label: 'Variance', type: 'number' },
          { id: 'value_impact', label: 'Value Impact (GBP)', type: 'number' },
          { id: 'reason', label: 'Reason', type: 'text', required: true },
        ],
        section: 'Items',
      },
      {
        id: 'justification',
        label: 'Justification',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Items',
      },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      {
        id: 'stores_signature',
        label: 'Stores Manager Signature',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
      {
        id: 'finance_signature',
        label: 'Finance Approval',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
    ],
  },
];
