import type { TemplateDefinition } from '../types';

export const iso37001Templates: TemplateDefinition[] = [
  {
    code: 'TPL-AB-001',
    name: 'Bribery Risk Assessment',
    description:
      'Anti-bribery risk assessment for evaluating bribery risks across business activities, geographies, and third-party relationships. Aligned with ISO 37001.',
    module: 'ISO37001',
    category: 'RISK_ASSESSMENT',
    tags: ['bribery-risk', 'anti-bribery', 'iso-37001', 'corruption'],
    isoClause: '4.5',
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      {
        id: 'assessment_title',
        label: 'Assessment Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Assessment Details',
      },
      {
        id: 'assessor',
        label: 'Assessor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Details',
      },
      {
        id: 'section_risks',
        label: 'Bribery Risks',
        type: 'section',
        helpText: 'Identify and assess bribery risks across all business activities.',
      },
      {
        id: 'risks',
        label: 'Risk Items',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'activity',
            label: 'Business Activity',
            type: 'text',
            required: true,
            placeholder: 'e.g. Government contract procurement',
          },
          {
            id: 'geography',
            label: 'Geography',
            type: 'text',
            required: true,
            placeholder: 'Country or region',
          },
          {
            id: 'risk_type',
            label: 'Risk Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Active Bribery', value: 'active' },
              { label: 'Passive Bribery', value: 'passive' },
              { label: 'Facilitation Payment', value: 'facilitation' },
              { label: 'Gifts & Hospitality', value: 'gifts' },
              { label: 'Political Contribution', value: 'political' },
            ],
          },
          {
            id: 'likelihood',
            label: 'Likelihood (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'impact',
            label: 'Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'controls',
            label: 'Existing Controls',
            type: 'text',
            placeholder: 'Current mitigations',
          },
          {
            id: 'residual_risk',
            label: 'Residual Risk',
            type: 'select',
            required: true,
            options: [
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          {
            id: 'action',
            label: 'Additional Action',
            type: 'text',
            placeholder: 'Further actions needed',
          },
        ],
        section: 'Bribery Risks',
      },
      {
        id: 'summary',
        label: 'Assessment Summary',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Bribery Risks',
      },
    ],
  },
  {
    code: 'TPL-AB-002',
    name: 'Due Diligence Report',
    description:
      'Anti-bribery due diligence report for evaluating third parties, business associates, and partners before entering into commercial relationships.',
    module: 'ISO37001',
    category: 'COMPLIANCE',
    tags: ['due-diligence', 'third-party', 'anti-bribery', 'screening'],
    isoClause: '8.2',
    fields: [
      { id: 'section_header', label: 'Due Diligence Details', type: 'section' },
      {
        id: 'subject_name',
        label: 'Subject Name (Company/Person)',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Due Diligence Details',
      },
      {
        id: 'relationship_type',
        label: 'Relationship Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Supplier', value: 'supplier' },
          { label: 'Agent', value: 'agent' },
          { label: 'Joint Venture Partner', value: 'jv_partner' },
          { label: 'Consultant', value: 'consultant' },
          { label: 'Customer', value: 'customer' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Due Diligence Details',
      },
      {
        id: 'country',
        label: 'Country of Operation',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Due Diligence Details',
      },
      {
        id: 'assessed_by',
        label: 'Assessed By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Due Diligence Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Due Diligence Details',
      },
      { id: 'section_checks', label: 'Due Diligence Checks', type: 'section' },
      {
        id: 'checks',
        label: 'Checks Performed',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'check',
            label: 'Check',
            type: 'text',
            required: true,
            placeholder: 'e.g. Sanctions screening',
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Clear', value: 'clear' },
              { label: 'Flag', value: 'flag' },
              { label: 'Fail', value: 'fail' },
              { label: 'Pending', value: 'pending' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Due Diligence Checks',
      },
      {
        id: 'risk_rating',
        label: 'Overall Risk Rating',
        type: 'select',
        required: true,
        options: [
          { label: 'Low Risk', value: 'low' },
          { label: 'Medium Risk', value: 'medium' },
          { label: 'High Risk', value: 'high' },
        ],
        width: 'half',
        section: 'Due Diligence Checks',
      },
      {
        id: 'recommendation',
        label: 'Recommendation',
        type: 'select',
        required: true,
        options: [
          { label: 'Proceed', value: 'proceed' },
          { label: 'Proceed with Conditions', value: 'conditional' },
          { label: 'Do Not Proceed', value: 'reject' },
        ],
        width: 'half',
        section: 'Due Diligence Checks',
      },
      {
        id: 'findings',
        label: 'Findings & Notes',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Due Diligence Checks',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Due Diligence Checks',
      },
    ],
  },
  {
    code: 'TPL-AB-003',
    name: 'Gift & Hospitality Register',
    description:
      'Register for recording all gifts and hospitality given or received. Ensures transparency and compliance with anti-bribery policies.',
    module: 'ISO37001',
    category: 'COMPLIANCE',
    tags: ['gifts', 'hospitality', 'register', 'transparency', 'anti-bribery'],
    isoClause: '8.7',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      {
        id: 'department',
        label: 'Department',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Register Details',
      },
      {
        id: 'period',
        label: 'Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. Q1 2026',
        width: 'half',
        section: 'Register Details',
      },
      { id: 'section_entries', label: 'Gift & Hospitality Entries', type: 'section' },
      {
        id: 'entries',
        label: 'Entries',
        type: 'table',
        required: true,
        columns: [
          { id: 'date', label: 'Date', type: 'date', required: true },
          {
            id: 'direction',
            label: 'Given / Received',
            type: 'select',
            required: true,
            options: [
              { label: 'Given', value: 'given' },
              { label: 'Received', value: 'received' },
            ],
          },
          {
            id: 'description',
            label: 'Description',
            type: 'text',
            required: true,
            placeholder: 'e.g. Dinner at restaurant',
          },
          {
            id: 'value',
            label: 'Estimated Value',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
          {
            id: 'counterparty',
            label: 'Counterparty',
            type: 'text',
            required: true,
            placeholder: 'Name and organisation',
          },
          { id: 'reason', label: 'Business Reason', type: 'text', required: true },
          { id: 'approved_by', label: 'Approved By', type: 'text' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Approved', value: 'approved' },
              { label: 'Pending', value: 'pending' },
              { label: 'Declined', value: 'declined' },
            ],
          },
        ],
        section: 'Gift & Hospitality Entries',
      },
    ],
  },
  {
    code: 'TPL-AB-004',
    name: 'Third-Party Due Diligence Form',
    description:
      'Comprehensive third-party due diligence form for assessing counterparty bribery and corruption risk. Covers entity identification, beneficial ownership, PEP screening, sanctions checks, red flag analysis, and risk categorisation. Aligned with ISO 37001 clause 8.2.',
    module: 'ISO37001',
    category: 'COMPLIANCE',
    tags: [
      'due-diligence',
      'third-party',
      'pep-screening',
      'sanctions',
      'red-flags',
      'counterparty-risk',
      'iso-37001',
    ],
    isoClause: '8.2',
    fields: [
      { id: 'section_entity', label: 'Counterparty Identification', type: 'section' },
      {
        id: 'entity_name',
        label: 'Entity / Individual Name',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Counterparty Identification',
      },
      {
        id: 'entity_type',
        label: 'Entity Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Corporation', value: 'corporation' },
          { label: 'Partnership', value: 'partnership' },
          { label: 'Sole Trader', value: 'sole_trader' },
          { label: 'Government Entity', value: 'government' },
          { label: 'Non-Profit / NGO', value: 'ngo' },
          { label: 'Individual', value: 'individual' },
          { label: 'Joint Venture', value: 'jv' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Counterparty Identification',
      },
      {
        id: 'relationship_type',
        label: 'Proposed Relationship',
        type: 'select',
        required: true,
        options: [
          { label: 'Supplier', value: 'supplier' },
          { label: 'Agent / Intermediary', value: 'agent' },
          { label: 'Consultant', value: 'consultant' },
          { label: 'Joint Venture Partner', value: 'jv_partner' },
          { label: 'Distributor', value: 'distributor' },
          { label: 'Customer', value: 'customer' },
          { label: 'Sub-Contractor', value: 'subcontractor' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Counterparty Identification',
      },
      {
        id: 'country_incorporation',
        label: 'Country of Incorporation',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Counterparty Identification',
      },
      {
        id: 'country_operations',
        label: 'Country/Countries of Operations',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Counterparty Identification',
      },
      {
        id: 'registration_number',
        label: 'Registration / Company Number',
        type: 'text',
        width: 'half',
        section: 'Counterparty Identification',
      },
      {
        id: 'estimated_contract_value',
        label: 'Estimated Contract Value',
        type: 'number',
        validation: { min: 0 },
        width: 'half',
        section: 'Counterparty Identification',
      },
      {
        id: 'business_rationale',
        label: 'Business Rationale for Engagement',
        type: 'textarea',
        required: true,
        placeholder: 'Explain the business need for engaging this third party...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Counterparty Identification',
      },
      {
        id: 'section_ownership',
        label: 'Beneficial Ownership & Key Personnel',
        type: 'section',
        helpText: 'Identify all individuals with 25%+ ownership or significant control.',
      },
      {
        id: 'beneficial_owners',
        label: 'Beneficial Owners',
        type: 'table',
        required: true,
        columns: [
          { id: 'name', label: 'Full Name', type: 'text', required: true },
          { id: 'nationality', label: 'Nationality', type: 'text', required: true },
          {
            id: 'ownership_pct',
            label: 'Ownership %',
            type: 'number',
            required: true,
            validation: { min: 0, max: 100 },
          },
          { id: 'role', label: 'Role / Position', type: 'text', required: true },
          {
            id: 'is_pep',
            label: 'PEP Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Confirmed PEP', value: 'confirmed_pep' },
              { label: 'PEP Associate', value: 'pep_associate' },
              { label: 'Former PEP', value: 'former_pep' },
              { label: 'Not a PEP', value: 'not_pep' },
              { label: 'Unknown — Requires Screening', value: 'unknown' },
            ],
          },
          {
            id: 'pep_details',
            label: 'PEP Details (if applicable)',
            type: 'text',
            placeholder: 'Government role, relationship to PEP, etc.',
          },
        ],
        section: 'Beneficial Ownership & Key Personnel',
      },
      {
        id: 'section_screening',
        label: 'Screening Results',
        type: 'section',
        helpText: 'Record the results of all screening checks performed.',
      },
      {
        id: 'screening_checks',
        label: 'Screening Checks',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'check_type',
            label: 'Check Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Sanctions Screening (OFAC/EU/UN)', value: 'sanctions' },
              { label: 'PEP Screening', value: 'pep' },
              { label: 'Adverse Media Search', value: 'adverse_media' },
              { label: 'Criminal Record Check', value: 'criminal' },
              { label: 'Court / Litigation Search', value: 'litigation' },
              { label: 'Regulatory Enforcement Check', value: 'regulatory' },
              { label: 'CPI / TI Index Check', value: 'cpi' },
              { label: 'Company Registry Search', value: 'registry' },
            ],
          },
          {
            id: 'source',
            label: 'Source / Provider',
            type: 'text',
            required: true,
            placeholder: 'e.g. World-Check, Dow Jones, manual search',
          },
          { id: 'date_performed', label: 'Date Performed', type: 'date', required: true },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Clear', value: 'clear' },
              { label: 'Match Found — Reviewed', value: 'match_reviewed' },
              { label: 'Match Found — Escalated', value: 'match_escalated' },
              { label: 'Pending', value: 'pending' },
            ],
          },
          { id: 'details', label: 'Details / Comments', type: 'text' },
        ],
        section: 'Screening Results',
      },
      {
        id: 'section_red_flags',
        label: 'Red Flag Analysis',
        type: 'section',
        helpText: 'Assess whether any bribery and corruption red flags are present.',
      },
      {
        id: 'red_flags',
        label: 'Red Flags',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'red_flag',
            label: 'Red Flag Indicator',
            type: 'select',
            required: true,
            options: [
              { label: 'High-risk country of operations', value: 'high_risk_country' },
              { label: 'Government interaction or public contract', value: 'gov_interaction' },
              { label: 'Unusual payment terms or structure', value: 'unusual_payments' },
              { label: 'Reluctance to provide information', value: 'reluctance' },
              { label: 'Undisclosed agents or intermediaries', value: 'undisclosed_agents' },
              { label: 'Reputation concerns or adverse media', value: 'reputation' },
              { label: 'Complex or opaque ownership structure', value: 'opaque_structure' },
              { label: 'Requests for cash or off-books payments', value: 'cash_requests' },
              { label: 'Excessive commissions or fees', value: 'excessive_fees' },
              { label: 'No legitimate business premises', value: 'no_premises' },
            ],
          },
          {
            id: 'present',
            label: 'Present?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
              { label: 'Partially / Unclear', value: 'partial' },
            ],
          },
          {
            id: 'explanation',
            label: 'Explanation / Mitigant',
            type: 'text',
            placeholder: 'Details and any mitigating factors',
          },
        ],
        section: 'Red Flag Analysis',
      },
      { id: 'section_outcome', label: 'Risk Assessment & Outcome', type: 'section' },
      {
        id: 'overall_risk',
        label: 'Overall Risk Rating',
        type: 'select',
        required: true,
        options: [
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
          { label: 'Unacceptable', value: 'unacceptable' },
        ],
        width: 'half',
        section: 'Risk Assessment & Outcome',
      },
      {
        id: 'recommendation',
        label: 'Recommendation',
        type: 'select',
        required: true,
        options: [
          { label: 'Approve — Standard Terms', value: 'approve' },
          { label: 'Approve — Enhanced Monitoring', value: 'approve_enhanced' },
          { label: 'Approve — With Conditions', value: 'approve_conditional' },
          { label: 'Reject', value: 'reject' },
          { label: 'Escalate to Compliance Committee', value: 'escalate' },
        ],
        width: 'half',
        section: 'Risk Assessment & Outcome',
      },
      {
        id: 'conditions',
        label: 'Conditions / Enhanced Controls',
        type: 'textarea',
        placeholder: 'List any conditions or enhanced controls required if approved...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Risk Assessment & Outcome',
      },
      {
        id: 'due_diligence_summary',
        label: 'Due Diligence Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Summarise the findings and basis for the recommendation...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Risk Assessment & Outcome',
      },
      {
        id: 'next_review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Risk Assessment & Outcome',
      },
      {
        id: 'assessor',
        label: 'Assessed By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Risk Assessment & Outcome',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Risk Assessment & Outcome',
      },
      {
        id: 'compliance_officer_signature',
        label: 'Compliance Officer Approval',
        type: 'signature',
        required: true,
        section: 'Risk Assessment & Outcome',
      },
    ],
  },
  {
    code: 'TPL-AB-005',
    name: 'Anti-Bribery Training Record',
    description:
      'Training record for anti-bribery and corruption awareness training. Captures training details, attendance, comprehension assessment, and employee acknowledgement of the anti-bribery policy. Aligned with ISO 37001 clause 7.2.',
    module: 'ISO37001',
    category: 'COMPLIANCE',
    tags: ['training', 'anti-bribery', 'awareness', 'competence', 'acknowledgement', 'iso-37001'],
    isoClause: '7.2',
    fields: [
      { id: 'section_training', label: 'Training Details', type: 'section' },
      {
        id: 'training_title',
        label: 'Training Title',
        type: 'text',
        required: true,
        placeholder: 'e.g. Annual Anti-Bribery Awareness Training 2026',
        width: 'full',
        section: 'Training Details',
      },
      {
        id: 'training_type',
        label: 'Training Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Initial / Induction', value: 'initial' },
          { label: 'Annual Refresher', value: 'annual' },
          { label: 'Role-Specific', value: 'role_specific' },
          { label: 'Incident-Triggered', value: 'incident_triggered' },
          { label: 'Regulatory Update', value: 'regulatory_update' },
        ],
        width: 'half',
        section: 'Training Details',
      },
      {
        id: 'delivery_method',
        label: 'Delivery Method',
        type: 'select',
        required: true,
        options: [
          { label: 'In-Person Classroom', value: 'classroom' },
          { label: 'Virtual / Webinar', value: 'virtual' },
          { label: 'E-Learning Module', value: 'elearning' },
          { label: 'Blended (In-Person + Online)', value: 'blended' },
          { label: 'Self-Study / Reading', value: 'self_study' },
        ],
        width: 'half',
        section: 'Training Details',
      },
      {
        id: 'training_date',
        label: 'Training Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Training Details',
      },
      {
        id: 'duration_hours',
        label: 'Duration (Hours)',
        type: 'number',
        required: true,
        validation: { min: 0.25, max: 40 },
        width: 'half',
        section: 'Training Details',
      },
      {
        id: 'trainer_name',
        label: 'Trainer / Facilitator',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Training Details',
      },
      {
        id: 'trainer_organisation',
        label: 'Trainer Organisation',
        type: 'text',
        placeholder: 'e.g. Internal Compliance Team, External Law Firm',
        width: 'half',
        section: 'Training Details',
      },
      {
        id: 'section_content',
        label: 'Training Content',
        type: 'section',
        helpText: 'Record the topics covered during the training session.',
      },
      {
        id: 'topics_covered',
        label: 'Topics Covered',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'topic',
            label: 'Topic',
            type: 'select',
            required: true,
            options: [
              { label: 'Anti-Bribery Policy Overview', value: 'policy_overview' },
              { label: 'ISO 37001 Requirements', value: 'iso37001' },
              { label: 'Bribery Act / FCPA / Local Legislation', value: 'legislation' },
              { label: 'Red Flags & Warning Signs', value: 'red_flags' },
              { label: 'Gifts, Hospitality & Entertainment', value: 'gifts' },
              { label: 'Due Diligence on Third Parties', value: 'due_diligence' },
              { label: 'Reporting Procedures & Whistleblowing', value: 'reporting' },
              { label: 'Facilitation Payments', value: 'facilitation' },
              { label: 'Political & Charitable Contributions', value: 'political' },
              { label: 'Consequences of Non-Compliance', value: 'consequences' },
              { label: 'Case Studies & Scenarios', value: 'case_studies' },
            ],
          },
          {
            id: 'covered',
            label: 'Covered?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'Partially', value: 'partial' },
              { label: 'No', value: 'no' },
            ],
          },
          {
            id: 'notes',
            label: 'Notes',
            type: 'text',
            placeholder: 'Key points or materials used',
          },
        ],
        section: 'Training Content',
      },
      {
        id: 'materials_provided',
        label: 'Materials Provided',
        type: 'textarea',
        placeholder:
          'List training materials distributed (slides, handouts, policy documents, e-learning links)...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Training Content',
      },
      {
        id: 'section_assessment',
        label: 'Comprehension Assessment',
        type: 'section',
        helpText: 'Record results of any knowledge assessment or quiz administered after training.',
      },
      {
        id: 'assessment_administered',
        label: 'Assessment Administered?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Written Quiz', value: 'written_quiz' },
          { label: 'Yes — Online Quiz', value: 'online_quiz' },
          { label: 'Yes — Verbal Q&A', value: 'verbal' },
          { label: 'Yes — Scenario-Based Exercise', value: 'scenario' },
          { label: 'No Assessment', value: 'none' },
        ],
        width: 'half',
        section: 'Comprehension Assessment',
      },
      {
        id: 'pass_threshold',
        label: 'Pass Threshold (%)',
        type: 'number',
        validation: { min: 0, max: 100 },
        placeholder: 'e.g. 80',
        width: 'half',
        section: 'Comprehension Assessment',
      },
      {
        id: 'section_attendees',
        label: 'Attendance & Results',
        type: 'section',
        helpText: 'Record each attendee, their assessment result, and acknowledgement status.',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'table',
        required: true,
        columns: [
          { id: 'employee_name', label: 'Employee Name', type: 'text', required: true },
          { id: 'employee_id', label: 'Employee ID', type: 'text', required: true },
          { id: 'department', label: 'Department', type: 'text', required: true },
          { id: 'role', label: 'Job Title / Role', type: 'text', required: true },
          {
            id: 'attendance',
            label: 'Attendance',
            type: 'select',
            required: true,
            options: [
              { label: 'Attended — Full', value: 'attended_full' },
              { label: 'Attended — Partial', value: 'attended_partial' },
              { label: 'Absent — Excused', value: 'absent_excused' },
              { label: 'Absent — No Reason', value: 'absent' },
            ],
          },
          {
            id: 'assessment_score',
            label: 'Assessment Score (%)',
            type: 'number',
            validation: { min: 0, max: 100 },
          },
          {
            id: 'pass_fail',
            label: 'Pass / Fail',
            type: 'select',
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail — Retake Required', value: 'fail' },
              { label: 'N/A', value: 'na' },
            ],
          },
          {
            id: 'policy_acknowledged',
            label: 'Policy Acknowledged?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
        ],
        section: 'Attendance & Results',
      },
      { id: 'section_followup', label: 'Follow-Up Actions', type: 'section' },
      {
        id: 'failed_attendees_action',
        label: 'Action for Failed / Absent Attendees',
        type: 'textarea',
        placeholder: 'Describe the plan for attendees who failed the assessment or were absent...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Follow-Up Actions',
      },
      {
        id: 'next_training_date',
        label: 'Next Training Due Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Follow-Up Actions',
      },
      {
        id: 'improvement_notes',
        label: 'Training Improvement Notes',
        type: 'textarea',
        placeholder: 'Feedback or suggestions to improve future training sessions...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Follow-Up Actions',
      },
      {
        id: 'overall_summary',
        label: 'Training Summary',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise the training session including attendance rate, pass rate, and key takeaways...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Follow-Up Actions',
      },
      {
        id: 'trainer_signature',
        label: 'Trainer Signature',
        type: 'signature',
        required: true,
        section: 'Follow-Up Actions',
      },
      {
        id: 'compliance_officer_signature',
        label: 'Compliance Officer Signature',
        type: 'signature',
        required: true,
        section: 'Follow-Up Actions',
      },
    ],
  },
];
