import type { TemplateDefinition } from '../types';

export const iso37001Templates: TemplateDefinition[] = [
  {
    code: 'TPL-AB-001',
    name: 'Bribery Risk Assessment',
    description:
      'Anti-bribery risk assessment for evaluating bribery risks across business activities, geographies, and third-party relationships. Aligned with ISO 37001.',
    module: 'ISO37001',
    category: 'RISK_ASSESSMENT',
    tags: ['bribery-risk', 'anti-bribery', 'iso-37001', 'corruption'],
    isoClause: '4.5',
    fields: [
      { id: 'section_header', label: 'Assessment Details', type: 'section' },
      { id: 'assessment_title', label: 'Assessment Title', type: 'text', required: true, width: 'full', section: 'Assessment Details' },
      { id: 'assessor', label: 'Assessor', type: 'text', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Assessment Details' },
      { id: 'section_risks', label: 'Bribery Risks', type: 'section', helpText: 'Identify and assess bribery risks across all business activities.' },
      {
        id: 'risks',
        label: 'Risk Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'activity', label: 'Business Activity', type: 'text', required: true, placeholder: 'e.g. Government contract procurement' },
          { id: 'geography', label: 'Geography', type: 'text', required: true, placeholder: 'Country or region' },
          { id: 'risk_type', label: 'Risk Type', type: 'select', required: true, options: [{ label: 'Active Bribery', value: 'active' }, { label: 'Passive Bribery', value: 'passive' }, { label: 'Facilitation Payment', value: 'facilitation' }, { label: 'Gifts & Hospitality', value: 'gifts' }, { label: 'Political Contribution', value: 'political' }] },
          { id: 'likelihood', label: 'Likelihood (1-5)', type: 'rating', required: true, validation: { min: 1, max: 5 } },
          { id: 'impact', label: 'Impact (1-5)', type: 'rating', required: true, validation: { min: 1, max: 5 } },
          { id: 'controls', label: 'Existing Controls', type: 'text', placeholder: 'Current mitigations' },
          { id: 'residual_risk', label: 'Residual Risk', type: 'select', required: true, options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
          { id: 'action', label: 'Additional Action', type: 'text', placeholder: 'Further actions needed' },
        ],
        section: 'Bribery Risks',
      },
      { id: 'summary', label: 'Assessment Summary', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Bribery Risks' },
    ],
  },
  {
    code: 'TPL-AB-002',
    name: 'Due Diligence Report',
    description:
      'Anti-bribery due diligence report for evaluating third parties, business associates, and partners before entering into commercial relationships.',
    module: 'ISO37001',
    category: 'COMPLIANCE',
    tags: ['due-diligence', 'third-party', 'anti-bribery', 'screening'],
    isoClause: '8.2',
    fields: [
      { id: 'section_header', label: 'Due Diligence Details', type: 'section' },
      { id: 'subject_name', label: 'Subject Name (Company/Person)', type: 'text', required: true, width: 'full', section: 'Due Diligence Details' },
      { id: 'relationship_type', label: 'Relationship Type', type: 'select', required: true, options: [{ label: 'Supplier', value: 'supplier' }, { label: 'Agent', value: 'agent' }, { label: 'Joint Venture Partner', value: 'jv_partner' }, { label: 'Consultant', value: 'consultant' }, { label: 'Customer', value: 'customer' }, { label: 'Other', value: 'other' }], width: 'half', section: 'Due Diligence Details' },
      { id: 'country', label: 'Country of Operation', type: 'text', required: true, width: 'half', section: 'Due Diligence Details' },
      { id: 'assessed_by', label: 'Assessed By', type: 'text', required: true, width: 'half', section: 'Due Diligence Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Due Diligence Details' },
      { id: 'section_checks', label: 'Due Diligence Checks', type: 'section' },
      {
        id: 'checks',
        label: 'Checks Performed',
        type: 'table',
        required: true,
        columns: [
          { id: 'check', label: 'Check', type: 'text', required: true, placeholder: 'e.g. Sanctions screening' },
          { id: 'result', label: 'Result', type: 'select', required: true, options: [{ label: 'Clear', value: 'clear' }, { label: 'Flag', value: 'flag' }, { label: 'Fail', value: 'fail' }, { label: 'Pending', value: 'pending' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Due Diligence Checks',
      },
      { id: 'risk_rating', label: 'Overall Risk Rating', type: 'select', required: true, options: [{ label: 'Low Risk', value: 'low' }, { label: 'Medium Risk', value: 'medium' }, { label: 'High Risk', value: 'high' }], width: 'half', section: 'Due Diligence Checks' },
      { id: 'recommendation', label: 'Recommendation', type: 'select', required: true, options: [{ label: 'Proceed', value: 'proceed' }, { label: 'Proceed with Conditions', value: 'conditional' }, { label: 'Do Not Proceed', value: 'reject' }], width: 'half', section: 'Due Diligence Checks' },
      { id: 'findings', label: 'Findings & Notes', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Due Diligence Checks' },
      { id: 'assessor_signature', label: 'Assessor Signature', type: 'signature', required: true, section: 'Due Diligence Checks' },
    ],
  },
  {
    code: 'TPL-AB-003',
    name: 'Gift & Hospitality Register',
    description:
      'Register for recording all gifts and hospitality given or received. Ensures transparency and compliance with anti-bribery policies.',
    module: 'ISO37001',
    category: 'COMPLIANCE',
    tags: ['gifts', 'hospitality', 'register', 'transparency', 'anti-bribery'],
    isoClause: '8.7',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      { id: 'department', label: 'Department', type: 'text', required: true, width: 'half', section: 'Register Details' },
      { id: 'period', label: 'Period', type: 'text', required: true, placeholder: 'e.g. Q1 2026', width: 'half', section: 'Register Details' },
      { id: 'section_entries', label: 'Gift & Hospitality Entries', type: 'section' },
      {
        id: 'entries',
        label: 'Entries',
        type: 'table',
        required: true,
        columns: [
          { id: 'date', label: 'Date', type: 'date', required: true },
          { id: 'direction', label: 'Given / Received', type: 'select', required: true, options: [{ label: 'Given', value: 'given' }, { label: 'Received', value: 'received' }] },
          { id: 'description', label: 'Description', type: 'text', required: true, placeholder: 'e.g. Dinner at restaurant' },
          { id: 'value', label: 'Estimated Value', type: 'number', required: true, validation: { min: 0 } },
          { id: 'counterparty', label: 'Counterparty', type: 'text', required: true, placeholder: 'Name and organisation' },
          { id: 'reason', label: 'Business Reason', type: 'text', required: true },
          { id: 'approved_by', label: 'Approved By', type: 'text' },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Approved', value: 'approved' }, { label: 'Pending', value: 'pending' }, { label: 'Declined', value: 'declined' }] },
        ],
        section: 'Gift & Hospitality Entries',
      },
    ],
  },
];
