import type { TemplateDefinition } from '../types';

export const iso42001Templates: TemplateDefinition[] = [
  {
    code: 'TPL-AI-001',
    name: 'AI System Impact Assessment',
    description:
      'Impact assessment for AI systems covering ethical, social, privacy, and safety considerations. Aligned with ISO 42001 requirements for responsible AI management.',
    module: 'ISO42001',
    category: 'RISK_ASSESSMENT',
    tags: ['ai-impact', 'ethical-ai', 'iso-42001', 'responsible-ai'],
    isoClause: '6.1.2',
    fields: [
      { id: 'section_system', label: 'AI System Details', type: 'section' },
      {
        id: 'system_name',
        label: 'AI System Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'AI System Details',
      },
      {
        id: 'system_owner',
        label: 'System Owner',
        type: 'text',
        required: true,
        width: 'half',
        section: 'AI System Details',
      },
      {
        id: 'date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'AI System Details',
      },
      {
        id: 'purpose',
        label: 'System Purpose',
        type: 'textarea',
        required: true,
        placeholder: 'Describe what the AI system does and its intended use...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'AI System Details',
      },
      {
        id: 'ai_type',
        label: 'AI Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Machine Learning', value: 'ml' },
          { label: 'Deep Learning', value: 'dl' },
          { label: 'NLP', value: 'nlp' },
          { label: 'Computer Vision', value: 'cv' },
          { label: 'Generative AI', value: 'gen_ai' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'AI System Details',
      },
      {
        id: 'risk_level',
        label: 'Risk Level',
        type: 'select',
        required: true,
        options: [
          { label: 'High', value: 'high' },
          { label: 'Medium', value: 'medium' },
          { label: 'Low', value: 'low' },
        ],
        width: 'half',
        section: 'AI System Details',
      },
      {
        id: 'section_impacts',
        label: 'Impact Areas',
        type: 'section',
        helpText: 'Assess the impact of the AI system across key dimensions.',
      },
      {
        id: 'impacts',
        label: 'Impact Assessment',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'area',
            label: 'Impact Area',
            type: 'select',
            required: true,
            options: [
              { label: 'Privacy', value: 'privacy' },
              { label: 'Bias & Fairness', value: 'bias' },
              { label: 'Transparency', value: 'transparency' },
              { label: 'Safety', value: 'safety' },
              { label: 'Human Autonomy', value: 'autonomy' },
              { label: 'Environmental', value: 'environmental' },
              { label: 'Economic', value: 'economic' },
            ],
          },
          {
            id: 'description',
            label: 'Description',
            type: 'textarea',
            required: true,
            validation: { maxLength: 1000 },
          },
          {
            id: 'severity',
            label: 'Severity',
            type: 'select',
            required: true,
            options: [
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
              { label: 'None', value: 'none' },
            ],
          },
          {
            id: 'mitigation',
            label: 'Mitigation',
            type: 'textarea',
            placeholder: 'How will this impact be mitigated?',
            validation: { maxLength: 1000 },
          },
        ],
        section: 'Impact Areas',
      },
      {
        id: 'overall_assessment',
        label: 'Overall Assessment',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Impact Areas',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Impact Areas',
      },
    ],
  },
  {
    code: 'TPL-AI-002',
    name: 'AI Risk Register',
    description:
      'Risk register for AI-specific risks including model drift, bias, security vulnerabilities, and regulatory non-compliance. Supports ongoing AI governance.',
    module: 'ISO42001',
    category: 'RISK_ASSESSMENT',
    tags: ['ai-risk', 'model-drift', 'bias', 'ai-governance', 'risk-register'],
    isoClause: '6.1',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      {
        id: 'system_name',
        label: 'AI System Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Register Details',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Register Details',
      },
      { id: 'section_risks', label: 'AI Risks', type: 'section' },
      {
        id: 'risks',
        label: 'Risk Items',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'risk_id',
            label: 'Risk ID',
            type: 'text',
            required: true,
            placeholder: 'e.g. AI-R-001',
          },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Model Performance', value: 'performance' },
              { label: 'Bias & Fairness', value: 'bias' },
              { label: 'Data Quality', value: 'data_quality' },
              { label: 'Security', value: 'security' },
              { label: 'Regulatory', value: 'regulatory' },
              { label: 'Ethical', value: 'ethical' },
              { label: 'Operational', value: 'operational' },
            ],
          },
          {
            id: 'description',
            label: 'Risk Description',
            type: 'textarea',
            required: true,
            validation: { maxLength: 500 },
          },
          {
            id: 'likelihood',
            label: 'Likelihood (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'impact',
            label: 'Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          {
            id: 'mitigation',
            label: 'Mitigation',
            type: 'textarea',
            required: true,
            validation: { maxLength: 500 },
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Open', value: 'open' },
              { label: 'Mitigating', value: 'mitigating' },
              { label: 'Closed', value: 'closed' },
              { label: 'Accepted', value: 'accepted' },
            ],
          },
        ],
        section: 'AI Risks',
      },
      {
        id: 'review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'AI Risks',
      },
    ],
  },
  {
    code: 'TPL-AI-003',
    name: 'Model Performance Review',
    description:
      'Periodic review of AI model performance metrics including accuracy, drift, fairness, and operational health. Supports model lifecycle management.',
    module: 'ISO42001',
    category: 'REPORTING',
    tags: ['model-performance', 'metrics', 'drift', 'monitoring', 'lifecycle'],
    isoClause: '9.1',
    fields: [
      { id: 'section_header', label: 'Review Details', type: 'section' },
      {
        id: 'model_name',
        label: 'Model Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Review Details',
      },
      {
        id: 'version',
        label: 'Model Version',
        type: 'text',
        required: true,
        placeholder: 'e.g. v2.3.1',
        width: 'half',
        section: 'Review Details',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Review Details',
      },
      {
        id: 'reviewer',
        label: 'Reviewer',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Review Details',
      },
      { id: 'section_metrics', label: 'Performance Metrics', type: 'section' },
      {
        id: 'metrics',
        label: 'Metrics',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'metric',
            label: 'Metric',
            type: 'text',
            required: true,
            placeholder: 'e.g. Accuracy, F1 Score',
          },
          {
            id: 'target',
            label: 'Target',
            type: 'text',
            required: true,
            placeholder: 'e.g. >= 95%',
          },
          { id: 'actual', label: 'Actual', type: 'text', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Met', value: 'met' },
              { label: 'Below Target', value: 'below' },
              { label: 'Critical', value: 'critical' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Performance Metrics',
      },
      { id: 'section_drift', label: 'Drift Analysis', type: 'section' },
      {
        id: 'data_drift',
        label: 'Data Drift Detected?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'Under Investigation', value: 'investigating' },
        ],
        width: 'half',
        section: 'Drift Analysis',
      },
      {
        id: 'concept_drift',
        label: 'Concept Drift Detected?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'Under Investigation', value: 'investigating' },
        ],
        width: 'half',
        section: 'Drift Analysis',
      },
      {
        id: 'drift_notes',
        label: 'Drift Analysis Notes',
        type: 'textarea',
        placeholder: 'Details on drift analysis and recommended actions...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Drift Analysis',
      },
      {
        id: 'recommendation',
        label: 'Recommendation',
        type: 'select',
        required: true,
        options: [
          { label: 'Continue Monitoring', value: 'monitor' },
          { label: 'Retrain Model', value: 'retrain' },
          { label: 'Retire Model', value: 'retire' },
          { label: 'Escalate', value: 'escalate' },
        ],
        width: 'half',
        section: 'Drift Analysis',
      },
      {
        id: 'summary',
        label: 'Overall Summary',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Drift Analysis',
      },
    ],
  },
  {
    code: 'TPL-AI-004',
    name: 'AI Model Card Template',
    description:
      'Standardised model card for documenting AI model purpose, training data, performance metrics, known limitations, bias assessment, and ethical considerations. Supports transparency and accountability requirements of ISO 42001.',
    module: 'ISO42001',
    category: 'REPORTING',
    tags: [
      'model-card',
      'transparency',
      'documentation',
      'bias-assessment',
      'ai-governance',
      'iso-42001',
    ],
    isoClause: '8.4',
    fields: [
      { id: 'section_overview', label: 'Model Overview', type: 'section' },
      {
        id: 'model_name',
        label: 'Model Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Model Overview',
      },
      {
        id: 'model_version',
        label: 'Model Version',
        type: 'text',
        required: true,
        placeholder: 'e.g. v3.1.0',
        width: 'half',
        section: 'Model Overview',
      },
      {
        id: 'model_owner',
        label: 'Model Owner',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Model Overview',
      },
      {
        id: 'date_created',
        label: 'Date Created',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Model Overview',
      },
      {
        id: 'model_type',
        label: 'Model Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Classification', value: 'classification' },
          { label: 'Regression', value: 'regression' },
          { label: 'Clustering', value: 'clustering' },
          { label: 'Generative', value: 'generative' },
          { label: 'Reinforcement Learning', value: 'rl' },
          { label: 'Recommender System', value: 'recommender' },
          { label: 'NLP / Language Model', value: 'nlp' },
          { label: 'Computer Vision', value: 'cv' },
          { label: 'Multi-Modal', value: 'multimodal' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Model Overview',
      },
      {
        id: 'deployment_status',
        label: 'Deployment Status',
        type: 'select',
        required: true,
        options: [
          { label: 'In Development', value: 'development' },
          { label: 'Staging / Testing', value: 'staging' },
          { label: 'Production', value: 'production' },
          { label: 'Deprecated', value: 'deprecated' },
          { label: 'Retired', value: 'retired' },
        ],
        width: 'half',
        section: 'Model Overview',
      },
      {
        id: 'intended_purpose',
        label: 'Intended Purpose',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the primary purpose and intended use cases for this model...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Model Overview',
      },
      {
        id: 'out_of_scope_uses',
        label: 'Out-of-Scope Uses',
        type: 'textarea',
        required: true,
        placeholder: 'Describe use cases this model is NOT designed or appropriate for...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Model Overview',
      },
      {
        id: 'intended_users',
        label: 'Intended Users',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the intended user groups (e.g. internal analysts, customer-facing system, automated pipeline)...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Model Overview',
      },
      {
        id: 'section_training',
        label: 'Training Data & Methodology',
        type: 'section',
        helpText: 'Document the data used to train the model and the methodology employed.',
      },
      {
        id: 'training_datasets',
        label: 'Training Datasets',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'dataset_name',
            label: 'Dataset Name',
            type: 'text',
            required: true,
            placeholder: 'e.g. Customer Transactions Q1-Q4 2025',
          },
          {
            id: 'source',
            label: 'Data Source',
            type: 'text',
            required: true,
            placeholder: 'e.g. Internal CRM, Public Dataset, Synthetic',
          },
          {
            id: 'size',
            label: 'Size (Records)',
            type: 'text',
            required: true,
            placeholder: 'e.g. 2.4M records',
          },
          {
            id: 'date_range',
            label: 'Date Range',
            type: 'text',
            placeholder: 'e.g. Jan 2023 — Dec 2025',
          },
          {
            id: 'pii_present',
            label: 'Contains PII?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes — Anonymised', value: 'yes_anon' },
              { label: 'Yes — Pseudonymised', value: 'yes_pseudo' },
              { label: 'Yes — Raw', value: 'yes_raw' },
              { label: 'No', value: 'no' },
            ],
          },
          {
            id: 'consent_basis',
            label: 'Legal Basis / Consent',
            type: 'text',
            placeholder: 'e.g. Legitimate interest, Consent, Synthetic',
          },
        ],
        section: 'Training Data & Methodology',
      },
      {
        id: 'preprocessing',
        label: 'Data Preprocessing Steps',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe feature engineering, normalisation, augmentation, and cleaning steps applied...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Training Data & Methodology',
      },
      {
        id: 'architecture',
        label: 'Model Architecture',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the model architecture (e.g. transformer, CNN, XGBoost), key hyperparameters, and training framework...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Training Data & Methodology',
      },
      {
        id: 'training_compute',
        label: 'Training Compute Resources',
        type: 'textarea',
        placeholder:
          'Describe compute used (GPU type, hours, cloud provider, estimated energy consumption)...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Training Data & Methodology',
      },
      {
        id: 'section_performance',
        label: 'Performance Metrics',
        type: 'section',
        helpText: 'Document measured performance across key metrics and evaluation datasets.',
      },
      {
        id: 'performance_metrics',
        label: 'Performance Metrics',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'metric_name',
            label: 'Metric',
            type: 'text',
            required: true,
            placeholder: 'e.g. Accuracy, F1, AUC-ROC, BLEU',
          },
          {
            id: 'eval_dataset',
            label: 'Evaluation Dataset',
            type: 'text',
            required: true,
            placeholder: 'e.g. Hold-out test set, Benchmark X',
          },
          {
            id: 'value',
            label: 'Value',
            type: 'text',
            required: true,
            placeholder: 'e.g. 0.94, 92.3%',
          },
          {
            id: 'baseline',
            label: 'Baseline / Previous Version',
            type: 'text',
            placeholder: 'e.g. v2.0: 0.89',
          },
          {
            id: 'confidence_interval',
            label: 'Confidence Interval',
            type: 'text',
            placeholder: 'e.g. 95% CI: [0.92, 0.96]',
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Performance Metrics',
      },
      {
        id: 'section_bias',
        label: 'Bias & Fairness Assessment',
        type: 'section',
        helpText:
          'Document bias testing methodology, results, and any disparities found across protected groups.',
      },
      {
        id: 'bias_evaluation',
        label: 'Bias Evaluation',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'protected_attribute',
            label: 'Protected Attribute',
            type: 'select',
            required: true,
            options: [
              { label: 'Gender', value: 'gender' },
              { label: 'Race / Ethnicity', value: 'race' },
              { label: 'Age', value: 'age' },
              { label: 'Disability', value: 'disability' },
              { label: 'Geographic Region', value: 'geography' },
              { label: 'Socioeconomic Status', value: 'socioeconomic' },
              { label: 'Language', value: 'language' },
              { label: 'Other', value: 'other' },
            ],
          },
          {
            id: 'metric',
            label: 'Fairness Metric',
            type: 'select',
            required: true,
            options: [
              { label: 'Demographic Parity', value: 'demographic_parity' },
              { label: 'Equalised Odds', value: 'equalised_odds' },
              { label: 'Predictive Parity', value: 'predictive_parity' },
              { label: 'Disparate Impact Ratio', value: 'disparate_impact' },
              { label: 'False Positive Rate Parity', value: 'fpr_parity' },
              { label: 'Other', value: 'other' },
            ],
          },
          {
            id: 'result',
            label: 'Result',
            type: 'text',
            required: true,
            placeholder: 'e.g. 0.87 (threshold: >0.80)',
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Within Threshold', value: 'pass' },
              { label: 'Below Threshold — Mitigated', value: 'mitigated' },
              { label: 'Below Threshold — Open', value: 'open' },
              { label: 'Not Tested', value: 'not_tested' },
            ],
          },
          {
            id: 'mitigation',
            label: 'Mitigation Applied',
            type: 'text',
            placeholder: 'e.g. Re-sampling, threshold adjustment',
          },
        ],
        section: 'Bias & Fairness Assessment',
      },
      {
        id: 'bias_summary',
        label: 'Bias Assessment Summary',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise the overall bias assessment findings, methodology, and any remaining concerns...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Bias & Fairness Assessment',
      },
      { id: 'section_limitations', label: 'Known Limitations & Risks', type: 'section' },
      {
        id: 'technical_limitations',
        label: 'Technical Limitations',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe known technical limitations (e.g. performance degrades on rare classes, latency constraints)...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Known Limitations & Risks',
      },
      {
        id: 'ethical_considerations',
        label: 'Ethical Considerations',
        type: 'textarea',
        required: true,
        placeholder:
          'Document ethical risks and considerations (e.g. potential for misuse, dual-use concerns, societal impact)...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Known Limitations & Risks',
      },
      {
        id: 'failure_modes',
        label: 'Known Failure Modes',
        type: 'textarea',
        placeholder:
          'Describe known failure modes and edge cases where the model may produce unreliable outputs...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Known Limitations & Risks',
      },
      {
        id: 'human_oversight',
        label: 'Human Oversight Requirements',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe required human-in-the-loop controls, override mechanisms, and escalation procedures...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Known Limitations & Risks',
      },
      { id: 'section_approval', label: 'Review & Approval', type: 'section' },
      {
        id: 'review_summary',
        label: 'Review Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Overall assessment of model readiness for its intended purpose...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Review & Approval',
      },
      {
        id: 'next_review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Review & Approval',
      },
      {
        id: 'model_owner_signature',
        label: 'Model Owner Signature',
        type: 'signature',
        required: true,
        section: 'Review & Approval',
      },
      {
        id: 'ai_governance_signature',
        label: 'AI Governance Lead Signature',
        type: 'signature',
        required: true,
        section: 'Review & Approval',
      },
    ],
  },
  {
    code: 'TPL-AI-005',
    name: 'AI Incident & Bias Report',
    description:
      'Report template for recording AI system incidents including unexpected behaviour, bias detection events, safety failures, and harmful outputs. Includes root cause analysis, impact assessment, and remediation planning. Aligned with ISO 42001 clause 10.2.',
    module: 'ISO42001',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['ai-incident', 'bias-report', 'ai-safety', 'remediation', 'harm', 'iso-42001'],
    isoClause: '10.2',
    fields: [
      { id: 'section_incident', label: 'Incident Details', type: 'section' },
      {
        id: 'incident_id',
        label: 'Incident ID',
        type: 'text',
        required: true,
        placeholder: 'e.g. AI-INC-2026-001',
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'date_detected',
        label: 'Date Detected',
        type: 'datetime',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'reported_by',
        label: 'Reported By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'ai_system_name',
        label: 'AI System Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'model_version',
        label: 'Model Version',
        type: 'text',
        required: true,
        placeholder: 'e.g. v3.1.0',
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'environment',
        label: 'Environment',
        type: 'select',
        required: true,
        options: [
          { label: 'Production', value: 'production' },
          { label: 'Staging', value: 'staging' },
          { label: 'Development', value: 'development' },
          { label: 'Testing', value: 'testing' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'incident_category',
        label: 'Incident Category',
        type: 'select',
        required: true,
        options: [
          { label: 'Bias / Discrimination', value: 'bias' },
          { label: 'Harmful / Toxic Output', value: 'harmful_output' },
          { label: 'Privacy Violation', value: 'privacy' },
          { label: 'Safety Failure', value: 'safety' },
          { label: 'Model Hallucination / Fabrication', value: 'hallucination' },
          { label: 'Performance Degradation', value: 'performance' },
          { label: 'Security Vulnerability', value: 'security' },
          { label: 'Unexpected Behaviour', value: 'unexpected' },
          { label: 'Regulatory Non-Compliance', value: 'regulatory' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Critical — Immediate Harm or Regulatory Breach', value: 'critical' },
          { label: 'High — Significant Impact, Containment Needed', value: 'high' },
          { label: 'Medium — Moderate Impact, Workaround Available', value: 'medium' },
          { label: 'Low — Minor Issue, No Immediate Harm', value: 'low' },
        ],
        width: 'half',
        section: 'Incident Details',
      },
      {
        id: 'description',
        label: 'Incident Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe what happened, how it was detected, specific inputs/outputs involved, and the context in which the incident occurred...',
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
        section: 'Incident Details',
      },
      {
        id: 'section_impact',
        label: 'Impact Assessment',
        type: 'section',
        helpText: 'Assess the impact of the AI incident across relevant dimensions.',
      },
      {
        id: 'affected_parties',
        label: 'Affected Parties',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'party',
            label: 'Affected Party',
            type: 'select',
            required: true,
            options: [
              { label: 'End Users / Customers', value: 'customers' },
              { label: 'Employees', value: 'employees' },
              { label: 'Specific Demographic Group', value: 'demographic' },
              { label: 'Business Operations', value: 'operations' },
              { label: 'Partners / Third Parties', value: 'partners' },
              { label: 'Public / Society', value: 'public' },
            ],
          },
          {
            id: 'description',
            label: 'How Affected',
            type: 'text',
            required: true,
            placeholder: 'Describe the specific impact on this party',
          },
          {
            id: 'estimated_count',
            label: 'Estimated Number Affected',
            type: 'text',
            placeholder: 'e.g. ~500 users, Unknown',
          },
          {
            id: 'harm_type',
            label: 'Type of Harm',
            type: 'select',
            required: true,
            options: [
              { label: 'Financial', value: 'financial' },
              { label: 'Reputational', value: 'reputational' },
              { label: 'Discriminatory', value: 'discriminatory' },
              { label: 'Physical Safety', value: 'physical' },
              { label: 'Psychological', value: 'psychological' },
              { label: 'Privacy', value: 'privacy' },
              { label: 'Operational', value: 'operational' },
              { label: 'No Direct Harm', value: 'none' },
            ],
          },
        ],
        section: 'Impact Assessment',
      },
      {
        id: 'regulatory_notification',
        label: 'Regulatory Notification Required?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Notified', value: 'yes_notified' },
          { label: 'Yes — Pending Notification', value: 'yes_pending' },
          { label: 'No', value: 'no' },
          { label: 'Under Assessment', value: 'assessing' },
        ],
        width: 'half',
        section: 'Impact Assessment',
      },
      {
        id: 'data_breach',
        label: 'Involves Data Breach?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Personal Data', value: 'personal' },
          { label: 'Yes — Business Data', value: 'business' },
          { label: 'No', value: 'no' },
          { label: 'Under Investigation', value: 'investigating' },
        ],
        width: 'half',
        section: 'Impact Assessment',
      },
      {
        id: 'section_bias',
        label: 'Bias Detection Details',
        type: 'section',
        helpText: 'Complete this section if the incident involves bias or discriminatory outputs.',
      },
      {
        id: 'bias_type',
        label: 'Type of Bias Detected',
        type: 'multiselect',
        options: [
          { label: 'Selection / Sampling Bias', value: 'selection' },
          { label: 'Measurement Bias', value: 'measurement' },
          { label: 'Algorithmic Bias', value: 'algorithmic' },
          { label: 'Historical / Societal Bias', value: 'historical' },
          { label: 'Representation Bias', value: 'representation' },
          { label: 'Automation Bias', value: 'automation' },
          { label: 'Confirmation Bias in Labelling', value: 'labelling' },
          { label: 'Not Applicable', value: 'na' },
        ],
        width: 'full',
        section: 'Bias Detection Details',
      },
      {
        id: 'affected_demographics',
        label: 'Affected Demographics / Groups',
        type: 'textarea',
        placeholder: 'Identify which demographic groups were disproportionately affected...',
        validation: { maxLength: 1000 },
        width: 'full',
        section: 'Bias Detection Details',
      },
      {
        id: 'bias_evidence',
        label: 'Evidence of Bias',
        type: 'textarea',
        placeholder:
          'Describe the evidence (statistical disparities, specific examples, user complaints)...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Bias Detection Details',
      },
      {
        id: 'fairness_metrics',
        label: 'Fairness Metrics (Post-Incident)',
        type: 'table',
        columns: [
          {
            id: 'metric',
            label: 'Fairness Metric',
            type: 'text',
            required: true,
            placeholder: 'e.g. Disparate Impact Ratio',
          },
          { id: 'group_a', label: 'Group A Result', type: 'text', required: true },
          { id: 'group_b', label: 'Group B Result', type: 'text', required: true },
          {
            id: 'threshold',
            label: 'Acceptable Threshold',
            type: 'text',
            placeholder: 'e.g. >0.80',
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
              { label: 'Inconclusive', value: 'inconclusive' },
            ],
          },
        ],
        section: 'Bias Detection Details',
      },
      { id: 'section_rca', label: 'Root Cause Analysis', type: 'section' },
      {
        id: 'root_cause_category',
        label: 'Root Cause Category',
        type: 'select',
        required: true,
        options: [
          { label: 'Training Data Issue', value: 'training_data' },
          { label: 'Model Architecture / Design', value: 'architecture' },
          { label: 'Feature Engineering Error', value: 'feature_eng' },
          { label: 'Labelling / Annotation Error', value: 'labelling' },
          { label: 'Data Pipeline Failure', value: 'data_pipeline' },
          { label: 'Deployment / Integration Error', value: 'deployment' },
          { label: 'Concept Drift', value: 'concept_drift' },
          { label: 'Data Drift', value: 'data_drift' },
          { label: 'Adversarial Input', value: 'adversarial' },
          { label: 'Human Error', value: 'human_error' },
          { label: 'Unknown', value: 'unknown' },
        ],
        width: 'half',
        section: 'Root Cause Analysis',
      },
      {
        id: 'root_cause_detail',
        label: 'Root Cause Analysis',
        type: 'textarea',
        required: true,
        placeholder:
          'Provide a detailed root cause analysis including timeline, contributing factors, and chain of events...',
        validation: { minLength: 30, maxLength: 5000 },
        width: 'full',
        section: 'Root Cause Analysis',
      },
      { id: 'section_containment', label: 'Containment & Immediate Actions', type: 'section' },
      {
        id: 'containment_actions',
        label: 'Containment Actions',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'action',
            label: 'Action Taken',
            type: 'text',
            required: true,
            placeholder: 'e.g. Model rolled back to v2.9.0',
          },
          {
            id: 'action_type',
            label: 'Action Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Model Rollback', value: 'rollback' },
              { label: 'Model Disabled / Offline', value: 'disabled' },
              { label: 'Output Filtering Added', value: 'filtering' },
              { label: 'Human Review Enforced', value: 'human_review' },
              { label: 'User Notification', value: 'user_notification' },
              { label: 'Access Restriction', value: 'access_restriction' },
              { label: 'Other', value: 'other' },
            ],
          },
          { id: 'date_implemented', label: 'Date Implemented', type: 'datetime', required: true },
          { id: 'implemented_by', label: 'Implemented By', type: 'text', required: true },
          {
            id: 'effective',
            label: 'Effective?',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'Partially', value: 'partial' },
              { label: 'No', value: 'no' },
              { label: 'Pending Verification', value: 'pending' },
            ],
          },
        ],
        section: 'Containment & Immediate Actions',
      },
      {
        id: 'section_remediation',
        label: 'Remediation Plan',
        type: 'section',
        helpText: 'Define the long-term remediation actions to prevent recurrence.',
      },
      {
        id: 'remediation_actions',
        label: 'Remediation Actions',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'action',
            label: 'Remediation Action',
            type: 'text',
            required: true,
            placeholder: 'e.g. Retrain model with balanced dataset',
          },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            required: true,
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'target_date', label: 'Target Date', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Not Started', value: 'not_started' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Complete', value: 'complete' },
              { label: 'Cancelled', value: 'cancelled' },
            ],
          },
          {
            id: 'verification',
            label: 'Verification Method',
            type: 'text',
            placeholder: 'How will completion be verified?',
          },
        ],
        section: 'Remediation Plan',
      },
      { id: 'section_lessons', label: 'Lessons Learned & Closure', type: 'section' },
      {
        id: 'lessons_learned',
        label: 'Lessons Learned',
        type: 'textarea',
        required: true,
        placeholder:
          'What should be changed in processes, monitoring, or governance to prevent similar incidents?',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Lessons Learned & Closure',
      },
      {
        id: 'monitoring_improvements',
        label: 'Monitoring Improvements',
        type: 'textarea',
        placeholder:
          'Describe any new monitoring, alerting, or testing that will be implemented...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Lessons Learned & Closure',
      },
      {
        id: 'incident_status',
        label: 'Incident Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Open — Under Investigation', value: 'open' },
          { label: 'Contained — Remediation In Progress', value: 'contained' },
          { label: 'Resolved — Monitoring', value: 'resolved' },
          { label: 'Closed', value: 'closed' },
        ],
        width: 'half',
        section: 'Lessons Learned & Closure',
      },
      {
        id: 'closure_date',
        label: 'Closure Date',
        type: 'date',
        width: 'half',
        section: 'Lessons Learned & Closure',
      },
      {
        id: 'investigator_signature',
        label: 'Investigator Signature',
        type: 'signature',
        required: true,
        section: 'Lessons Learned & Closure',
      },
      {
        id: 'ai_governance_signature',
        label: 'AI Governance Lead Signature',
        type: 'signature',
        required: true,
        section: 'Lessons Learned & Closure',
      },
    ],
  },
];
