import type { TemplateDefinition } from '../types';

export const iso42001Templates: TemplateDefinition[] = [
  {
    code: 'TPL-AI-001',
    name: 'AI System Impact Assessment',
    description:
      'Impact assessment for AI systems covering ethical, social, privacy, and safety considerations. Aligned with ISO 42001 requirements for responsible AI management.',
    module: 'ISO42001',
    category: 'RISK_ASSESSMENT',
    tags: ['ai-impact', 'ethical-ai', 'iso-42001', 'responsible-ai'],
    isoClause: '6.1.2',
    fields: [
      { id: 'section_system', label: 'AI System Details', type: 'section' },
      { id: 'system_name', label: 'AI System Name', type: 'text', required: true, width: 'half', section: 'AI System Details' },
      { id: 'system_owner', label: 'System Owner', type: 'text', required: true, width: 'half', section: 'AI System Details' },
      { id: 'date', label: 'Assessment Date', type: 'date', required: true, width: 'half', section: 'AI System Details' },
      { id: 'purpose', label: 'System Purpose', type: 'textarea', required: true, placeholder: 'Describe what the AI system does and its intended use...', validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'AI System Details' },
      { id: 'ai_type', label: 'AI Type', type: 'select', required: true, options: [{ label: 'Machine Learning', value: 'ml' }, { label: 'Deep Learning', value: 'dl' }, { label: 'NLP', value: 'nlp' }, { label: 'Computer Vision', value: 'cv' }, { label: 'Generative AI', value: 'gen_ai' }, { label: 'Other', value: 'other' }], width: 'half', section: 'AI System Details' },
      { id: 'risk_level', label: 'Risk Level', type: 'select', required: true, options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }], width: 'half', section: 'AI System Details' },
      { id: 'section_impacts', label: 'Impact Areas', type: 'section', helpText: 'Assess the impact of the AI system across key dimensions.' },
      {
        id: 'impacts',
        label: 'Impact Assessment',
        type: 'table',
        required: true,
        columns: [
          { id: 'area', label: 'Impact Area', type: 'select', required: true, options: [{ label: 'Privacy', value: 'privacy' }, { label: 'Bias & Fairness', value: 'bias' }, { label: 'Transparency', value: 'transparency' }, { label: 'Safety', value: 'safety' }, { label: 'Human Autonomy', value: 'autonomy' }, { label: 'Environmental', value: 'environmental' }, { label: 'Economic', value: 'economic' }] },
          { id: 'description', label: 'Description', type: 'textarea', required: true, validation: { maxLength: 1000 } },
          { id: 'severity', label: 'Severity', type: 'select', required: true, options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }, { label: 'None', value: 'none' }] },
          { id: 'mitigation', label: 'Mitigation', type: 'textarea', placeholder: 'How will this impact be mitigated?', validation: { maxLength: 1000 } },
        ],
        section: 'Impact Areas',
      },
      { id: 'overall_assessment', label: 'Overall Assessment', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Impact Areas' },
      { id: 'assessor_signature', label: 'Assessor Signature', type: 'signature', required: true, section: 'Impact Areas' },
    ],
  },
  {
    code: 'TPL-AI-002',
    name: 'AI Risk Register',
    description:
      'Risk register for AI-specific risks including model drift, bias, security vulnerabilities, and regulatory non-compliance. Supports ongoing AI governance.',
    module: 'ISO42001',
    category: 'RISK_ASSESSMENT',
    tags: ['ai-risk', 'model-drift', 'bias', 'ai-governance', 'risk-register'],
    isoClause: '6.1',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      { id: 'system_name', label: 'AI System Name', type: 'text', required: true, width: 'half', section: 'Register Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Register Details' },
      { id: 'section_risks', label: 'AI Risks', type: 'section' },
      {
        id: 'risks',
        label: 'Risk Items',
        type: 'table',
        required: true,
        columns: [
          { id: 'risk_id', label: 'Risk ID', type: 'text', required: true, placeholder: 'e.g. AI-R-001' },
          { id: 'category', label: 'Category', type: 'select', required: true, options: [{ label: 'Model Performance', value: 'performance' }, { label: 'Bias & Fairness', value: 'bias' }, { label: 'Data Quality', value: 'data_quality' }, { label: 'Security', value: 'security' }, { label: 'Regulatory', value: 'regulatory' }, { label: 'Ethical', value: 'ethical' }, { label: 'Operational', value: 'operational' }] },
          { id: 'description', label: 'Risk Description', type: 'textarea', required: true, validation: { maxLength: 500 } },
          { id: 'likelihood', label: 'Likelihood (1-5)', type: 'rating', required: true, validation: { min: 1, max: 5 } },
          { id: 'impact', label: 'Impact (1-5)', type: 'rating', required: true, validation: { min: 1, max: 5 } },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'mitigation', label: 'Mitigation', type: 'textarea', required: true, validation: { maxLength: 500 } },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Open', value: 'open' }, { label: 'Mitigating', value: 'mitigating' }, { label: 'Closed', value: 'closed' }, { label: 'Accepted', value: 'accepted' }] },
        ],
        section: 'AI Risks',
      },
      { id: 'review_date', label: 'Next Review Date', type: 'date', required: true, width: 'half', section: 'AI Risks' },
    ],
  },
  {
    code: 'TPL-AI-003',
    name: 'Model Performance Review',
    description:
      'Periodic review of AI model performance metrics including accuracy, drift, fairness, and operational health. Supports model lifecycle management.',
    module: 'ISO42001',
    category: 'REPORTING',
    tags: ['model-performance', 'metrics', 'drift', 'monitoring', 'lifecycle'],
    isoClause: '9.1',
    fields: [
      { id: 'section_header', label: 'Review Details', type: 'section' },
      { id: 'model_name', label: 'Model Name', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'version', label: 'Model Version', type: 'text', required: true, placeholder: 'e.g. v2.3.1', width: 'half', section: 'Review Details' },
      { id: 'review_date', label: 'Review Date', type: 'date', required: true, width: 'half', section: 'Review Details' },
      { id: 'reviewer', label: 'Reviewer', type: 'text', required: true, width: 'half', section: 'Review Details' },
      { id: 'section_metrics', label: 'Performance Metrics', type: 'section' },
      {
        id: 'metrics',
        label: 'Metrics',
        type: 'table',
        required: true,
        columns: [
          { id: 'metric', label: 'Metric', type: 'text', required: true, placeholder: 'e.g. Accuracy, F1 Score' },
          { id: 'target', label: 'Target', type: 'text', required: true, placeholder: 'e.g. >= 95%' },
          { id: 'actual', label: 'Actual', type: 'text', required: true },
          { id: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Met', value: 'met' }, { label: 'Below Target', value: 'below' }, { label: 'Critical', value: 'critical' }] },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Performance Metrics',
      },
      { id: 'section_drift', label: 'Drift Analysis', type: 'section' },
      { id: 'data_drift', label: 'Data Drift Detected?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }, { label: 'Under Investigation', value: 'investigating' }], width: 'half', section: 'Drift Analysis' },
      { id: 'concept_drift', label: 'Concept Drift Detected?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }, { label: 'Under Investigation', value: 'investigating' }], width: 'half', section: 'Drift Analysis' },
      { id: 'drift_notes', label: 'Drift Analysis Notes', type: 'textarea', placeholder: 'Details on drift analysis and recommended actions...', validation: { maxLength: 2000 }, width: 'full', section: 'Drift Analysis' },
      { id: 'recommendation', label: 'Recommendation', type: 'select', required: true, options: [{ label: 'Continue Monitoring', value: 'monitor' }, { label: 'Retrain Model', value: 'retrain' }, { label: 'Retire Model', value: 'retire' }, { label: 'Escalate', value: 'escalate' }], width: 'half', section: 'Drift Analysis' },
      { id: 'summary', label: 'Overall Summary', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Drift Analysis' },
    ],
  },
];
