// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.
import type { TemplateDefinition } from '../types';

export const medicalTemplates: TemplateDefinition[] = [
  // ─── TPL-MED-001  Design & Development Plan ───────────────────────────
  {
    code: 'TPL-MED-001',
    name: 'Design & Development Plan',
    description:
      'Comprehensive design and development planning document for medical devices per ISO 13485:2016 clause 7.3.2. Captures device classification, intended use, design phases, applicable standards, risk management references, and review schedule.',
    module: 'MEDICAL',
    category: 'DESIGN_DEVELOPMENT',
    tags: ['design-control', 'iso-13485', 'development-plan', 'device-classification'],
    isoClause: '7.3.2',
    fields: [
      {
        id: 'section_general',
        label: 'General Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'project_name',
        label: 'Project Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. CardioSense Implantable Monitor v2',
        helpText: 'Formal project or device programme name.',
        width: 'half',
      },
      {
        id: 'project_number',
        label: 'Project Number',
        type: 'text',
        required: true,
        placeholder: 'PRJ-2026-001',
        width: 'half',
      },
      {
        id: 'device_class',
        label: 'Device Classification',
        type: 'select',
        required: true,
        helpText: 'EU MDR / FDA classification of the device.',
        options: [
          { label: 'Class I', value: 'I' },
          { label: 'Class IIa', value: 'IIa' },
          { label: 'Class IIb', value: 'IIb' },
          { label: 'Class III', value: 'III' },
        ],
        width: 'half',
      },
      {
        id: 'regulatory_pathway',
        label: 'Regulatory Pathway',
        type: 'select',
        options: [
          { label: '510(k)', value: '510k' },
          { label: 'PMA', value: 'PMA' },
          { label: 'De Novo', value: 'de_novo' },
          { label: 'CE Marking (MDR)', value: 'CE_MDR' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
      },
      {
        id: 'intended_use',
        label: 'Intended Use / Intended Purpose',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the medical purpose, target patient population, and clinical context of use.',
        helpText:
          'Per IEC 62366-1 and ISO 14971 — state the intended medical indication, patient population, user profile, and use environment.',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'section_phases',
        label: 'Design Phases',
        type: 'section',
        width: 'full',
      },
      {
        id: 'design_phases',
        label: 'Design Phases',
        type: 'table',
        required: true,
        helpText: 'Define each phase of the design and development lifecycle.',
        columns: [
          {
            id: 'phase',
            label: 'Phase',
            type: 'select',
            required: true,
            options: [
              { label: 'Concept / Feasibility', value: 'concept' },
              { label: 'Design Input', value: 'design_input' },
              { label: 'Design Output', value: 'design_output' },
              { label: 'Verification', value: 'verification' },
              { label: 'Validation', value: 'validation' },
              { label: 'Design Transfer', value: 'design_transfer' },
              { label: 'Design Changes', value: 'design_changes' },
            ],
          },
          {
            id: 'deliverables',
            label: 'Key Deliverables',
            type: 'textarea',
            required: true,
            placeholder: 'List the deliverables for this phase',
          },
          {
            id: 'timeline',
            label: 'Target Completion',
            type: 'date',
            required: true,
          },
          {
            id: 'responsibility',
            label: 'Responsible Person / Team',
            type: 'text',
            required: true,
            placeholder: 'e.g. R&D Lead, Regulatory Affairs',
          },
        ],
        width: 'full',
      },
      {
        id: 'section_standards',
        label: 'Applicable Standards & References',
        type: 'section',
        width: 'full',
      },
      {
        id: 'standards_applicable',
        label: 'Applicable Standards',
        type: 'multiselect',
        required: true,
        helpText: 'Select all harmonized and consensus standards applicable to this device.',
        options: [
          { label: 'ISO 13485:2016 — QMS for Medical Devices', value: 'ISO_13485' },
          { label: 'ISO 14971:2019 — Risk Management', value: 'ISO_14971' },
          { label: 'IEC 62304 — Medical Device Software Lifecycle', value: 'IEC_62304' },
          { label: 'IEC 60601-1 — Electrical Safety', value: 'IEC_60601_1' },
          { label: 'IEC 62366-1 — Usability Engineering', value: 'IEC_62366_1' },
          { label: 'ISO 10993 — Biocompatibility', value: 'ISO_10993' },
          { label: 'ISO 11607 — Packaging for Terminally Sterilized Devices', value: 'ISO_11607' },
          { label: 'ISO 11135 — EO Sterilization', value: 'ISO_11135' },
          { label: 'ISO 11137 — Radiation Sterilization', value: 'ISO_11137' },
          { label: 'IEC 60601-1-2 — EMC', value: 'IEC_60601_1_2' },
          { label: 'FDA 21 CFR Part 820', value: 'FDA_820' },
          { label: 'EU MDR 2017/745', value: 'EU_MDR' },
        ],
        width: 'full',
      },
      {
        id: 'risk_management_plan_ref',
        label: 'Risk Management Plan Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. RMP-2026-001 Rev A',
        helpText: 'Document number of the ISO 14971 risk management plan for this project.',
        width: 'half',
      },
      {
        id: 'clinical_evaluation_ref',
        label: 'Clinical Evaluation Plan Reference',
        type: 'text',
        placeholder: 'e.g. CEP-2026-001',
        helpText: 'Document number of the clinical evaluation plan, if applicable.',
        width: 'half',
      },
      {
        id: 'section_review',
        label: 'Review Schedule',
        type: 'section',
        width: 'full',
      },
      {
        id: 'review_schedule',
        label: 'Design Review Schedule',
        type: 'table',
        required: true,
        helpText: 'Plan formal design reviews at each phase gate per ISO 13485 clause 7.3.5.',
        columns: [
          {
            id: 'review_name',
            label: 'Review Name',
            type: 'text',
            required: true,
            placeholder: 'e.g. Concept Design Review',
          },
          {
            id: 'planned_date',
            label: 'Planned Date',
            type: 'date',
            required: true,
          },
          {
            id: 'participants',
            label: 'Required Participants',
            type: 'text',
            placeholder: 'e.g. R&D, QA, Regulatory, Clinical',
          },
          {
            id: 'criteria',
            label: 'Review Criteria / Gate Requirements',
            type: 'textarea',
            placeholder: 'Criteria that must be met to pass this gate',
          },
        ],
        width: 'full',
      },
      {
        id: 'plan_approver',
        label: 'Plan Approved By',
        type: 'signature',
        required: true,
        helpText: 'Signature of the Design & Development Plan owner.',
        width: 'half',
      },
      {
        id: 'plan_approval_date',
        label: 'Approval Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-MED-002  Design Input Requirements ──────────────────────────
  {
    code: 'TPL-MED-002',
    name: 'Design Input Requirements',
    description:
      'Captures and categorizes design input requirements per ISO 13485:2016 clause 7.3.3. Ensures requirements are complete, unambiguous, verifiable, and traceable.',
    module: 'MEDICAL',
    category: 'DESIGN_DEVELOPMENT',
    tags: ['design-input', 'requirements', 'traceability', 'iso-13485'],
    isoClause: '7.3.3',
    fields: [
      {
        id: 'section_header',
        label: 'Project Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'project_name',
        label: 'Project Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. CardioSense Implantable Monitor v2',
        width: 'half',
      },
      {
        id: 'document_number',
        label: 'Document Number',
        type: 'text',
        required: true,
        placeholder: 'DI-2026-001',
        width: 'half',
      },
      {
        id: 'revision',
        label: 'Revision',
        type: 'text',
        required: true,
        defaultValue: 'A',
        width: 'third',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'third',
      },
      {
        id: 'author',
        label: 'Author',
        type: 'text',
        required: true,
        width: 'third',
      },
      {
        id: 'requirement_category',
        label: 'Primary Requirement Category',
        type: 'select',
        required: true,
        helpText:
          'Select the primary category for this requirement set. Individual requirements are categorized in the table below.',
        options: [
          { label: 'Performance Requirements', value: 'performance' },
          { label: 'Safety Requirements', value: 'safety' },
          { label: 'Regulatory Requirements', value: 'regulatory' },
          { label: 'User / Usability Requirements', value: 'user' },
          { label: 'Environmental / Durability Requirements', value: 'environmental' },
        ],
        width: 'half',
      },
      {
        id: 'section_requirements',
        label: 'Design Input Requirements',
        type: 'section',
        width: 'full',
      },
      {
        id: 'requirements_table',
        label: 'Requirements',
        type: 'table',
        required: true,
        helpText:
          'Each requirement must be verifiable and traceable to a source. Use unique IDs (e.g. REQ-001).',
        columns: [
          {
            id: 'req_id',
            label: 'Requirement ID',
            type: 'text',
            required: true,
            placeholder: 'REQ-001',
          },
          {
            id: 'description',
            label: 'Requirement Description',
            type: 'textarea',
            required: true,
            placeholder: 'The device shall ...',
          },
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Performance', value: 'performance' },
              { label: 'Safety', value: 'safety' },
              { label: 'Regulatory', value: 'regulatory' },
              { label: 'User', value: 'user' },
              { label: 'Environmental', value: 'environmental' },
            ],
          },
          {
            id: 'source',
            label: 'Source',
            type: 'text',
            required: true,
            placeholder: 'e.g. ISO 14971, User Needs Spec, Clinical feedback',
          },
          {
            id: 'verification_method',
            label: 'Verification Method',
            type: 'select',
            required: true,
            options: [
              { label: 'Test', value: 'test' },
              { label: 'Inspection', value: 'inspection' },
              { label: 'Analysis', value: 'analysis' },
              { label: 'Demonstration', value: 'demonstration' },
            ],
          },
          {
            id: 'acceptance_criteria',
            label: 'Acceptance Criteria',
            type: 'textarea',
            required: true,
            placeholder: 'Measurable pass/fail criteria',
          },
        ],
        width: 'full',
      },
      {
        id: 'section_traceability',
        label: 'Traceability & Approvals',
        type: 'section',
        width: 'full',
      },
      {
        id: 'traceability_matrix_ref',
        label: 'Traceability Matrix Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. TM-2026-001',
        helpText:
          'Document number of the design traceability matrix that links inputs to outputs, V&V, and risk controls.',
        width: 'half',
      },
      {
        id: 'predecessor_docs',
        label: 'Predecessor / Source Documents',
        type: 'textarea',
        placeholder:
          'List user needs documents, clinical investigation reports, predicate device analysis, etc.',
        width: 'full',
      },
      {
        id: 'reviewed_by',
        label: 'Reviewed By',
        type: 'signature',
        required: true,
        helpText: 'Independent reviewer (must not be the author).',
        width: 'half',
      },
      {
        id: 'approved_by',
        label: 'Approved By',
        type: 'signature',
        required: true,
        helpText: 'Design authority or project lead approval.',
        width: 'half',
      },
      {
        id: 'approval_date',
        label: 'Approval Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-MED-003  Design Verification Protocol ───────────────────────
  {
    code: 'TPL-MED-003',
    name: 'Design Verification Protocol',
    description:
      'Protocol for design verification testing per ISO 13485:2016 clause 7.3.5. Documents test methods, equipment, acceptance criteria, sample sizes, procedures, and approval signatures.',
    module: 'MEDICAL',
    category: 'INSPECTION',
    tags: ['verification', 'testing', 'design-control', 'protocol', 'iso-13485'],
    isoClause: '7.3.5',
    fields: [
      {
        id: 'section_protocol_info',
        label: 'Protocol Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'protocol_number',
        label: 'Protocol Number',
        type: 'text',
        required: true,
        placeholder: 'VP-2026-001',
        width: 'third',
      },
      {
        id: 'revision',
        label: 'Revision',
        type: 'text',
        required: true,
        defaultValue: 'A',
        width: 'third',
      },
      {
        id: 'date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'third',
      },
      {
        id: 'device_name',
        label: 'Device Under Test',
        type: 'text',
        required: true,
        placeholder: 'Full device name and model number',
        width: 'half',
      },
      {
        id: 'device_revision',
        label: 'Device Revision / Lot',
        type: 'text',
        placeholder: 'e.g. Rev C, Lot 2026-03',
        width: 'half',
      },
      {
        id: 'test_method',
        label: 'Test Method / Standard',
        type: 'text',
        required: true,
        placeholder: 'e.g. IEC 60601-1 clause 8.7, ASTM F2129',
        helpText: 'Reference the specific standard, clause, or internal test method.',
        width: 'full',
      },
      {
        id: 'section_equipment',
        label: 'Test Equipment',
        type: 'section',
        width: 'full',
      },
      {
        id: 'equipment_table',
        label: 'Equipment List',
        type: 'table',
        required: true,
        helpText: 'All equipment must have current calibration.',
        columns: [
          {
            id: 'equipment_name',
            label: 'Equipment Name',
            type: 'text',
            required: true,
          },
          {
            id: 'model',
            label: 'Model / ID',
            type: 'text',
            required: true,
          },
          {
            id: 'serial_number',
            label: 'Serial Number',
            type: 'text',
          },
          {
            id: 'calibration_due',
            label: 'Calibration Due Date',
            type: 'date',
            required: true,
          },
          {
            id: 'calibration_cert',
            label: 'Calibration Certificate',
            type: 'text',
            placeholder: 'Cert number or reference',
          },
        ],
        width: 'full',
      },
      {
        id: 'section_acceptance',
        label: 'Acceptance Criteria',
        type: 'section',
        width: 'full',
      },
      {
        id: 'acceptance_criteria_table',
        label: 'Acceptance Criteria',
        type: 'table',
        required: true,
        helpText: 'Define each measurable parameter and its pass/fail criteria.',
        columns: [
          {
            id: 'parameter',
            label: 'Parameter',
            type: 'text',
            required: true,
            placeholder: 'e.g. Tensile strength',
          },
          {
            id: 'specification',
            label: 'Specification / Limit',
            type: 'text',
            required: true,
            placeholder: 'e.g. >= 50 N, 37 +/- 2 degC',
          },
          {
            id: 'method',
            label: 'Test Method',
            type: 'text',
            required: true,
            placeholder: 'e.g. Pull test per ASTM D638',
          },
        ],
        width: 'full',
      },
      {
        id: 'section_procedure',
        label: 'Test Procedure',
        type: 'section',
        width: 'full',
      },
      {
        id: 'sample_size',
        label: 'Sample Size',
        type: 'text',
        required: true,
        placeholder: 'e.g. n=30 per ANSI/ASQ Z1.4 Level II',
        helpText: 'Provide statistical rationale for sample size selection.',
        width: 'half',
      },
      {
        id: 'sampling_plan',
        label: 'Sampling Plan Reference',
        type: 'text',
        placeholder: 'e.g. ANSI/ASQ Z1.4, ISO 2859-1',
        width: 'half',
      },
      {
        id: 'test_procedure',
        label: 'Test Procedure',
        type: 'textarea',
        required: true,
        placeholder:
          'Step-by-step test instructions. Include environment conditions, setup, and measurement steps.',
        helpText:
          'Provide sufficient detail for a qualified technician to reproduce the test independently.',
        validation: { minLength: 50, maxLength: 10000 },
        width: 'full',
      },
      {
        id: 'expected_results',
        label: 'Expected Results',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the expected outcome when the device meets all specifications.',
        width: 'full',
      },
      {
        id: 'section_deviations',
        label: 'Deviations & Approvals',
        type: 'section',
        width: 'full',
      },
      {
        id: 'deviation_handling',
        label: 'Deviation Handling Procedure',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe how deviations from the protocol will be documented, assessed, and dispositioned.',
        helpText:
          'Include criteria for when a deviation requires protocol amendment vs. documentation only.',
        width: 'full',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'reviewed_by',
        label: 'Reviewed By (QA)',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'approved_by',
        label: 'Approved By',
        type: 'signature',
        required: true,
        width: 'third',
      },
    ],
  },

  // ─── TPL-MED-004  Usability Engineering Report ───────────────────────
  {
    code: 'TPL-MED-004',
    name: 'Usability Engineering Report',
    description:
      'Summative usability evaluation report per IEC 62366-1:2015. Documents user profiles, use scenarios, task analysis, test results, residual risk assessment, and conclusions on the user interface.',
    module: 'MEDICAL',
    category: 'DESIGN_DEVELOPMENT',
    tags: ['usability', 'human-factors', 'iec-62366', 'user-interface', 'validation'],
    isoClause: '7.3.7',
    fields: [
      {
        id: 'section_device',
        label: 'Device & User Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'device_name',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. CardioSense Implantable Monitor v2',
        width: 'half',
      },
      {
        id: 'report_number',
        label: 'Report Number',
        type: 'text',
        required: true,
        placeholder: 'UER-2026-001',
        width: 'half',
      },
      {
        id: 'intended_users',
        label: 'Intended User Groups',
        type: 'multiselect',
        required: true,
        helpText: 'Select all user groups identified in the use specification.',
        options: [
          { label: 'Physician / Surgeon', value: 'physician' },
          { label: 'Nurse / Clinical Staff', value: 'nurse' },
          { label: 'Biomedical Technician', value: 'biomed_tech' },
          { label: 'Patient (Self-Use)', value: 'patient' },
          { label: 'Caregiver (Lay User)', value: 'caregiver' },
          { label: 'Emergency Responder', value: 'emergency' },
          { label: 'Laboratory Technician', value: 'lab_tech' },
          { label: 'Pharmacist', value: 'pharmacist' },
          { label: 'IT / System Administrator', value: 'it_admin' },
        ],
        width: 'full',
      },
      {
        id: 'use_environment',
        label: 'Use Environment',
        type: 'textarea',
        placeholder:
          'Describe the physical and social environment where the device will be used (e.g. ICU, home, ambulance).',
        width: 'full',
      },
      {
        id: 'section_scenarios',
        label: 'Use Scenarios',
        type: 'section',
        width: 'full',
      },
      {
        id: 'use_scenarios',
        label: 'Use Scenarios',
        type: 'table',
        required: true,
        helpText: 'Document all critical use scenarios derived from the use specification.',
        columns: [
          {
            id: 'scenario_id',
            label: 'Scenario ID',
            type: 'text',
            required: true,
            placeholder: 'US-001',
          },
          {
            id: 'scenario_description',
            label: 'Description',
            type: 'textarea',
            required: true,
          },
          {
            id: 'user_group',
            label: 'User Group',
            type: 'text',
            required: true,
          },
          {
            id: 'criticality',
            label: 'Criticality',
            type: 'select',
            required: true,
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'section_task_analysis',
        label: 'Task Analysis',
        type: 'section',
        width: 'full',
      },
      {
        id: 'task_analysis',
        label: 'Task Analysis',
        type: 'table',
        required: true,
        helpText:
          'Hierarchical task analysis identifying potential use errors and their risk mitigation.',
        columns: [
          {
            id: 'task',
            label: 'Task',
            type: 'text',
            required: true,
            placeholder: 'e.g. Insert catheter',
          },
          {
            id: 'steps',
            label: 'Sub-Steps',
            type: 'textarea',
            required: true,
            placeholder: '1. Open package\n2. Inspect tip\n3. ...',
          },
          {
            id: 'potential_errors',
            label: 'Potential Use Errors',
            type: 'textarea',
            required: true,
            placeholder: 'e.g. Incorrect insertion depth, contamination',
          },
          {
            id: 'severity',
            label: 'Severity of Harm',
            type: 'select',
            required: true,
            options: [
              { label: 'Negligible', value: 'negligible' },
              { label: 'Minor', value: 'minor' },
              { label: 'Serious', value: 'serious' },
              { label: 'Critical', value: 'critical' },
              { label: 'Catastrophic', value: 'catastrophic' },
            ],
          },
          {
            id: 'mitigation',
            label: 'Risk Mitigation',
            type: 'textarea',
            required: true,
            placeholder: 'Design controls, labelling, training, IFU',
          },
        ],
        width: 'full',
      },
      {
        id: 'section_results',
        label: 'Test Results & Conclusions',
        type: 'section',
        width: 'full',
      },
      {
        id: 'usability_test_results',
        label: 'Usability Test Results Summary',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarize participant performance, task completion rates, use errors observed, close calls, and use difficulties.',
        helpText: 'Reference the detailed summative evaluation report if applicable.',
        validation: { minLength: 50, maxLength: 10000 },
        width: 'full',
      },
      {
        id: 'participants_count',
        label: 'Number of Participants',
        type: 'number',
        required: true,
        helpText: 'IEC 62366-1 recommends minimum 15 participants per user group.',
        validation: { min: 1, max: 500 },
        width: 'third',
      },
      {
        id: 'task_success_rate',
        label: 'Overall Task Success Rate (%)',
        type: 'number',
        validation: { min: 0, max: 100 },
        width: 'third',
      },
      {
        id: 'critical_errors',
        label: 'Critical Use Errors Observed',
        type: 'number',
        validation: { min: 0 },
        width: 'third',
      },
      {
        id: 'residual_risk_assessment',
        label: 'Residual Risk Assessment',
        type: 'textarea',
        required: true,
        placeholder:
          'Assess residual use-related risks after all mitigations. State whether residual risks are acceptable.',
        width: 'full',
      },
      {
        id: 'conclusions',
        label: 'Conclusions',
        type: 'textarea',
        required: true,
        placeholder:
          'State whether the user interface is acceptable for the intended use and user groups, and list any outstanding actions.',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'author_signature',
        label: 'Report Author',
        type: 'signature',
        required: true,
        width: 'half',
      },
      {
        id: 'approval_date',
        label: 'Report Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-MED-005  Device Master Record Index ─────────────────────────
  {
    code: 'TPL-MED-005',
    name: 'Device Master Record Index',
    description:
      'Index of all documents comprising the Device Master Record (DMR) per FDA 21 CFR 820.181 and ISO 13485:2016 clause 4.2.3. Provides controlled listing of specifications, drawings, procedures, forms, and labels.',
    module: 'MEDICAL',
    category: 'COMPLIANCE',
    tags: ['DMR', 'device-master-record', 'document-control', 'fda-820', 'iso-13485'],
    isoClause: '4.2.3',
    fields: [
      {
        id: 'section_dmr_info',
        label: 'DMR Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'dmr_number',
        label: 'DMR Number',
        type: 'text',
        required: true,
        placeholder: 'DMR-2026-001',
        width: 'third',
      },
      {
        id: 'device_name',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'Full commercial device name',
        width: 'third',
      },
      {
        id: 'device_identifier',
        label: 'Device Identifier (UDI-DI)',
        type: 'text',
        required: true,
        placeholder: 'e.g. (01)00844588012345',
        helpText: 'Unique Device Identifier — Device Identifier per UDI rule.',
        width: 'third',
      },
      {
        id: 'device_family',
        label: 'Device Family / Product Line',
        type: 'text',
        placeholder: 'e.g. CardioSense Platform',
        width: 'half',
      },
      {
        id: 'dmr_owner',
        label: 'DMR Owner',
        type: 'text',
        required: true,
        placeholder: 'Name and title of the DMR custodian',
        width: 'half',
      },
      {
        id: 'section_documents',
        label: 'Document Listing',
        type: 'section',
        width: 'full',
      },
      {
        id: 'document_list',
        label: 'DMR Document List',
        type: 'table',
        required: true,
        helpText: 'List every document that forms part of this Device Master Record.',
        columns: [
          {
            id: 'doc_number',
            label: 'Document Number',
            type: 'text',
            required: true,
            placeholder: 'e.g. SPC-001',
          },
          {
            id: 'title',
            label: 'Document Title',
            type: 'text',
            required: true,
          },
          {
            id: 'revision',
            label: 'Current Revision',
            type: 'text',
            required: true,
            placeholder: 'e.g. Rev C',
          },
          {
            id: 'doc_type',
            label: 'Document Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Specification', value: 'specification' },
              { label: 'Drawing', value: 'drawing' },
              { label: 'Procedure / SOP', value: 'procedure' },
              { label: 'Form / Template', value: 'form' },
              { label: 'Label / Artwork', value: 'label' },
              { label: 'Test Protocol', value: 'test_protocol' },
              { label: 'Bill of Materials', value: 'bom' },
              { label: 'Software Documentation', value: 'software' },
              { label: 'Risk Management', value: 'risk' },
            ],
          },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Current / Approved', value: 'current' },
              { label: 'Draft', value: 'draft' },
              { label: 'Under Review', value: 'under_review' },
              { label: 'Obsolete', value: 'obsolete' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'section_revision_history',
        label: 'DMR Revision History',
        type: 'section',
        width: 'full',
      },
      {
        id: 'revision_history',
        label: 'Revision History',
        type: 'table',
        helpText: 'Track changes to the DMR index itself.',
        columns: [
          {
            id: 'rev',
            label: 'Revision',
            type: 'text',
            required: true,
          },
          {
            id: 'date',
            label: 'Date',
            type: 'date',
            required: true,
          },
          {
            id: 'description',
            label: 'Description of Change',
            type: 'textarea',
            required: true,
          },
          {
            id: 'author',
            label: 'Changed By',
            type: 'text',
            required: true,
          },
        ],
        width: 'full',
      },
      {
        id: 'section_approval',
        label: 'Approval',
        type: 'section',
        width: 'full',
      },
      {
        id: 'approved_by',
        label: 'Approved By',
        type: 'signature',
        required: true,
        helpText: 'Quality Assurance or Regulatory Affairs approval.',
        width: 'half',
      },
      {
        id: 'approval_date',
        label: 'Approval Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },

  // ─── TPL-MED-006  ISO 14971 Risk Management File ─────────────────────
  {
    code: 'TPL-MED-006',
    name: 'ISO 14971 Risk Management File',
    description:
      'Comprehensive risk management file per ISO 14971:2019. Consolidates hazard identification, risk estimation, risk evaluation, risk control, benefit-risk analysis, and overall residual risk acceptability.',
    module: 'MEDICAL',
    category: 'RISK_ASSESSMENT',
    tags: ['risk-management', 'iso-14971', 'hazard-analysis', 'benefit-risk', 'residual-risk'],
    isoClause: '4.5',
    fields: [
      {
        id: 'section_device_info',
        label: 'Device Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'device_name',
        label: 'Device Name',
        type: 'text',
        required: true,
        width: 'half',
      },
      {
        id: 'device_model',
        label: 'Model / Part Number',
        type: 'text',
        width: 'half',
      },
      {
        id: 'rmp_version',
        label: 'Risk Management Plan Version',
        type: 'text',
        required: true,
        placeholder: 'e.g. RMP-2026-001 Rev B',
        helpText: 'Reference to the current approved risk management plan.',
        width: 'half',
      },
      {
        id: 'rmf_date',
        label: 'File Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'section_hazard_id',
        label: 'Hazard Identification',
        type: 'section',
        width: 'full',
      },
      {
        id: 'hazard_identification',
        label: 'Hazard Identification Table',
        type: 'table',
        required: true,
        helpText:
          'Systematic identification of hazards, hazardous situations, and potential harms per ISO 14971 clause 5.4.',
        columns: [
          {
            id: 'hazard',
            label: 'Hazard',
            type: 'text',
            required: true,
            placeholder: 'e.g. Electrical energy',
          },
          {
            id: 'hazardous_situation',
            label: 'Hazardous Situation',
            type: 'textarea',
            required: true,
            placeholder: 'e.g. Patient connected during fault condition',
          },
          {
            id: 'harm',
            label: 'Potential Harm',
            type: 'text',
            required: true,
            placeholder: 'e.g. Electric shock, burns',
          },
          {
            id: 'severity',
            label: 'Severity (S)',
            type: 'select',
            required: true,
            options: [
              { label: 'S1 — Negligible', value: 'S1' },
              { label: 'S2 — Minor', value: 'S2' },
              { label: 'S3 — Serious', value: 'S3' },
              { label: 'S4 — Critical', value: 'S4' },
              { label: 'S5 — Catastrophic', value: 'S5' },
            ],
          },
          {
            id: 'probability',
            label: 'Probability (P)',
            type: 'select',
            required: true,
            options: [
              { label: 'P1 — Incredible', value: 'P1' },
              { label: 'P2 — Improbable', value: 'P2' },
              { label: 'P3 — Remote', value: 'P3' },
              { label: 'P4 — Occasional', value: 'P4' },
              { label: 'P5 — Frequent', value: 'P5' },
            ],
          },
          {
            id: 'risk_level',
            label: 'Initial Risk Level',
            type: 'select',
            required: true,
            options: [
              { label: 'Acceptable', value: 'acceptable' },
              { label: 'ALARP', value: 'alarp' },
              { label: 'Unacceptable', value: 'unacceptable' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'section_risk_controls',
        label: 'Risk Control Measures',
        type: 'section',
        width: 'full',
      },
      {
        id: 'risk_control_measures',
        label: 'Risk Control Measures',
        type: 'table',
        required: true,
        helpText:
          'Document risk controls in priority order: inherent safety by design, protective measures, information for safety.',
        columns: [
          {
            id: 'hazard_ref',
            label: 'Hazard Reference',
            type: 'text',
            required: true,
            placeholder: 'e.g. H-001',
          },
          {
            id: 'control_type',
            label: 'Control Type',
            type: 'select',
            required: true,
            options: [
              { label: 'Inherent Safety by Design', value: 'inherent_safety' },
              { label: 'Protective Measure', value: 'protective_measure' },
              { label: 'Information for Safety', value: 'information' },
            ],
          },
          {
            id: 'control_description',
            label: 'Control Description',
            type: 'textarea',
            required: true,
          },
          {
            id: 'verification_ref',
            label: 'Verification Reference',
            type: 'text',
            placeholder: 'e.g. VP-2026-003',
          },
          {
            id: 'residual_severity',
            label: 'Residual Severity',
            type: 'select',
            options: [
              { label: 'S1', value: 'S1' },
              { label: 'S2', value: 'S2' },
              { label: 'S3', value: 'S3' },
              { label: 'S4', value: 'S4' },
              { label: 'S5', value: 'S5' },
            ],
          },
          {
            id: 'residual_probability',
            label: 'Residual Probability',
            type: 'select',
            options: [
              { label: 'P1', value: 'P1' },
              { label: 'P2', value: 'P2' },
              { label: 'P3', value: 'P3' },
              { label: 'P4', value: 'P4' },
              { label: 'P5', value: 'P5' },
            ],
          },
          {
            id: 'residual_risk_level',
            label: 'Residual Risk Level',
            type: 'select',
            options: [
              { label: 'Acceptable', value: 'acceptable' },
              { label: 'ALARP', value: 'alarp' },
              { label: 'Unacceptable', value: 'unacceptable' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'section_benefit_risk',
        label: 'Benefit-Risk Analysis & Overall Residual Risk',
        type: 'section',
        width: 'full',
      },
      {
        id: 'benefit_risk_analysis',
        label: 'Benefit-Risk Analysis',
        type: 'textarea',
        required: true,
        placeholder:
          'For each residual risk judged individually unacceptable, weigh the medical benefits against the residual risk per ISO 14971 clause 6.5.',
        helpText:
          'Document the rationale for accepting residual risks where benefits outweigh risks.',
        validation: { minLength: 50, maxLength: 10000 },
        width: 'full',
      },
      {
        id: 'residual_risk_evaluation',
        label: 'Residual Risk Evaluation',
        type: 'textarea',
        required: true,
        placeholder:
          'Evaluate the overall residual risk considering all identified hazards and risk controls.',
        width: 'full',
      },
      {
        id: 'overall_residual_risk_acceptability',
        label: 'Overall Residual Risk Acceptability',
        type: 'select',
        required: true,
        helpText:
          'Per ISO 14971 clause 8 — determination that the overall residual risk is acceptable.',
        options: [
          { label: 'Acceptable — all risks within acceptable region', value: 'acceptable' },
          {
            label: 'Acceptable — benefits outweigh residual risks (ALARP)',
            value: 'acceptable_alarp',
          },
          { label: 'Not Acceptable — further risk control required', value: 'not_acceptable' },
        ],
        width: 'full',
      },
      {
        id: 'section_rmf_approval',
        label: 'Approval',
        type: 'section',
        width: 'full',
      },
      {
        id: 'risk_manager',
        label: 'Risk Manager Approval',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'qa_approval',
        label: 'Quality Assurance Approval',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'management_approval',
        label: 'Top Management Approval',
        type: 'signature',
        required: true,
        width: 'third',
      },
    ],
  },

  // ─── TPL-MED-007  Hazard Analysis Worksheet ──────────────────────────
  {
    code: 'TPL-MED-007',
    name: 'Hazard Analysis Worksheet',
    description:
      'Detailed hazard analysis worksheet using severity, probability, and detectability scoring to calculate Risk Priority Numbers (RPN). Supports FMEA-style analysis for medical devices per ISO 14971.',
    module: 'MEDICAL',
    category: 'RISK_ASSESSMENT',
    tags: ['hazard-analysis', 'FMEA', 'RPN', 'iso-14971', 'risk-scoring'],
    isoClause: '5.4',
    fields: [
      {
        id: 'section_context',
        label: 'Analysis Context',
        type: 'section',
        width: 'full',
      },
      {
        id: 'device_name',
        label: 'Device / System Name',
        type: 'text',
        required: true,
        width: 'half',
      },
      {
        id: 'analysis_date',
        label: 'Analysis Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'process_step',
        label: 'Process Step / Use Phase',
        type: 'text',
        required: true,
        placeholder:
          'e.g. Manufacturing — Soldering, Clinical Use — Insertion, Maintenance — Battery Replacement',
        helpText: 'Identify the specific process step, use phase, or component being analyzed.',
        width: 'full',
      },
      {
        id: 'analysis_scope',
        label: 'Analysis Scope',
        type: 'textarea',
        placeholder: 'Boundaries and assumptions for this analysis.',
        width: 'full',
      },
      {
        id: 'section_hazards',
        label: 'Hazard Analysis',
        type: 'section',
        width: 'full',
      },
      {
        id: 'hazards_table',
        label: 'Hazards',
        type: 'table',
        required: true,
        helpText:
          'Score severity (S), probability (P), and detectability (D) from 1 to 5. RPN = S x P x D. Risk Level: Low (1-20), Medium (21-50), High (51-80), Very High (81-125).',
        columns: [
          {
            id: 'hazard',
            label: 'Hazard',
            type: 'text',
            required: true,
            placeholder: 'e.g. Sharp edge on housing',
          },
          {
            id: 'cause',
            label: 'Cause',
            type: 'text',
            required: true,
            placeholder: 'e.g. Moulding defect',
          },
          {
            id: 'effect',
            label: 'Effect / Harm',
            type: 'text',
            required: true,
            placeholder: 'e.g. Laceration to user',
          },
          {
            id: 'severity',
            label: 'Severity (1-5)',
            type: 'number',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'probability',
            label: 'Probability (1-5)',
            type: 'number',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'detectability',
            label: 'Detectability (1-5)',
            type: 'number',
            required: true,
            helpText: '1=easily detected, 5=undetectable',
            validation: { min: 1, max: 5 },
          },
          {
            id: 'rpn',
            label: 'RPN',
            type: 'number',
            helpText: 'Calculated: S x P x D',
            validation: { min: 1, max: 125 },
          },
          {
            id: 'risk_level',
            label: 'Risk Level',
            type: 'select',
            required: true,
            options: [
              { label: 'Low (1-20)', value: 'low' },
              { label: 'Medium (21-50)', value: 'medium' },
              { label: 'High (51-80)', value: 'high' },
              { label: 'Very High (81-125)', value: 'very_high' },
            ],
          },
          {
            id: 'controls',
            label: 'Risk Controls',
            type: 'textarea',
            required: true,
            placeholder: 'Describe design or process controls',
          },
          {
            id: 'residual_rpn',
            label: 'Residual RPN',
            type: 'number',
            helpText: 'RPN after controls are implemented',
            validation: { min: 1, max: 125 },
          },
        ],
        width: 'full',
      },
      {
        id: 'section_references',
        label: 'References & Sign-off',
        type: 'section',
        width: 'full',
      },
      {
        id: 'risk_acceptability_matrix_ref',
        label: 'Risk Acceptability Matrix Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. RMP-2026-001 Appendix A',
        helpText: 'Reference to the risk acceptability matrix defined in the risk management plan.',
        width: 'half',
      },
      {
        id: 'related_fmea_ref',
        label: 'Related FMEA / pFMEA Reference',
        type: 'text',
        placeholder: 'e.g. FMEA-2026-002',
        width: 'half',
      },
      {
        id: 'analyst',
        label: 'Analyst',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'reviewer',
        label: 'Reviewer',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'sign_off_date',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'third',
      },
    ],
  },

  // ─── TPL-MED-008  Medical Device Complaint Investigation ─────────────
  {
    code: 'TPL-MED-008',
    name: 'Medical Device Complaint Investigation',
    description:
      'Complaint handling and investigation form per FDA 21 CFR 820.198 and ISO 13485:2016 clause 8.2.2. Covers complaint receipt, investigation, root cause, CAPA, and regulatory reportability assessment.',
    module: 'MEDICAL',
    category: 'INCIDENT_INVESTIGATION',
    tags: ['complaint', 'investigation', 'MDR', 'vigilance', 'post-market', 'fda-820'],
    isoClause: '8.2.2',
    fields: [
      {
        id: 'section_complaint_details',
        label: 'Complaint Details',
        type: 'section',
        width: 'full',
      },
      {
        id: 'complaint_ref',
        label: 'Complaint Reference Number',
        type: 'text',
        required: true,
        placeholder: 'COMP-2026-0001',
        width: 'third',
      },
      {
        id: 'date_received',
        label: 'Date Received',
        type: 'date',
        required: true,
        width: 'third',
      },
      {
        id: 'date_of_event',
        label: 'Date of Event',
        type: 'date',
        width: 'third',
      },
      {
        id: 'device_name',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'Full commercial device name',
        width: 'half',
      },
      {
        id: 'lot_number',
        label: 'Lot / Serial Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. LOT-2026-03-A',
        helpText: 'Lot, batch, or serial number for traceability.',
        width: 'half',
      },
      {
        id: 'udi',
        label: 'UDI (if available)',
        type: 'text',
        placeholder: 'Full UDI string',
        width: 'half',
      },
      {
        id: 'complaint_source',
        label: 'Complaint Source',
        type: 'select',
        options: [
          { label: 'Healthcare Professional', value: 'hcp' },
          { label: 'Patient / User', value: 'patient' },
          { label: 'Distributor', value: 'distributor' },
          { label: 'Internal (Quality)', value: 'internal' },
          { label: 'Regulatory Authority', value: 'regulatory' },
          { label: 'Literature / Media', value: 'literature' },
        ],
        width: 'half',
      },
      {
        id: 'complaint_description',
        label: 'Complaint Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Detailed description of the complaint, including what happened, the circumstances, and any patient injury or adverse event.',
        validation: { minLength: 20, maxLength: 10000 },
        width: 'full',
      },
      {
        id: 'patient_injury',
        label: 'Patient Injury / Adverse Event',
        type: 'select',
        required: true,
        options: [
          { label: 'No injury or adverse event', value: 'none' },
          { label: 'Minor injury — no intervention required', value: 'minor' },
          { label: 'Moderate injury — intervention required', value: 'moderate' },
          { label: 'Serious injury', value: 'serious' },
          { label: 'Death', value: 'death' },
        ],
        width: 'half',
      },
      {
        id: 'section_investigation',
        label: 'Investigation',
        type: 'section',
        width: 'full',
      },
      {
        id: 'investigation_findings',
        label: 'Investigation Findings',
        type: 'textarea',
        required: true,
        placeholder:
          'Document the investigation process, tests performed, evidence collected, and findings.',
        helpText:
          'Include references to any returned device evaluations, manufacturing records reviewed, and testing performed.',
        validation: { minLength: 50, maxLength: 20000 },
        width: 'full',
      },
      {
        id: 'root_cause',
        label: 'Root Cause',
        type: 'textarea',
        required: true,
        placeholder:
          'Identified root cause(s) of the complaint. If no root cause identified, explain why.',
        width: 'full',
      },
      {
        id: 'risk_assessment',
        label: 'Risk Assessment',
        type: 'textarea',
        required: true,
        placeholder:
          'Assess the risk to patients/users considering severity and probability. Reference the risk management file.',
        width: 'full',
      },
      {
        id: 'capa_reference',
        label: 'CAPA Reference',
        type: 'text',
        placeholder: 'e.g. CAPA-2026-005',
        helpText:
          'If a CAPA was initiated, provide the reference number. If no CAPA, document justification below.',
        width: 'half',
      },
      {
        id: 'capa_justification',
        label: 'CAPA Decision Justification',
        type: 'textarea',
        placeholder: 'If no CAPA initiated, explain the rationale.',
        width: 'half',
      },
      {
        id: 'section_regulatory',
        label: 'Regulatory Reporting Assessment',
        type: 'section',
        width: 'full',
      },
      {
        id: 'reportability_assessment',
        label: 'Meets MDR / Adverse Event Reporting Criteria',
        type: 'checkbox',
        helpText:
          'Check if this event meets the criteria for mandatory adverse event reporting under FDA MDR (21 CFR 803) or EU Vigilance (MDR Article 87).',
        width: 'half',
      },
      {
        id: 'regulatory_notification_needed',
        label: 'Regulatory Notification Required',
        type: 'checkbox',
        helpText:
          'Check if a regulatory authority notification (e.g. MedWatch, FSCA) must be submitted.',
        width: 'half',
      },
      {
        id: 'mdr_report_type',
        label: 'MDR / MEDDEV Report Type',
        type: 'select',
        helpText: 'If reportable, select the type of regulatory report.',
        options: [
          { label: 'Not Reportable', value: 'not_reportable' },
          { label: 'FDA MDR — 30-Day Report', value: 'fda_mdr_30' },
          { label: 'FDA MDR — 5-Day Report', value: 'fda_mdr_5' },
          { label: 'EU Serious Incident Report — Initial', value: 'eu_sir_initial' },
          { label: 'EU Serious Incident Report — Follow-Up', value: 'eu_sir_followup' },
          { label: 'EU Trend Report', value: 'eu_trend' },
          { label: 'Field Safety Corrective Action (FSCA)', value: 'fsca' },
        ],
        width: 'half',
      },
      {
        id: 'regulatory_report_ref',
        label: 'Regulatory Report Reference',
        type: 'text',
        placeholder: 'e.g. MedWatch number or EU SIR reference',
        width: 'half',
      },
      {
        id: 'section_closure',
        label: 'Closure',
        type: 'section',
        width: 'full',
      },
      {
        id: 'closure_summary',
        label: 'Closure Summary',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarize the outcome, actions taken, and rationale for closing the complaint.',
        width: 'full',
      },
      {
        id: 'investigator_signature',
        label: 'Investigator',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'qa_signature',
        label: 'QA Review',
        type: 'signature',
        required: true,
        width: 'third',
      },
      {
        id: 'closure_date',
        label: 'Closure Date',
        type: 'date',
        required: true,
        width: 'third',
      },
    ],
  },

  // ─── TPL-MED-009  ISO 13485 Management Review ────────────────────────
  {
    code: 'TPL-MED-009',
    name: 'ISO 13485 Management Review',
    description:
      'Management review meeting template per ISO 13485:2016 clause 5.6. Covers mandatory review inputs (audit results, customer feedback, CAPA, product conformity, regulatory changes, process performance) and outputs (improvement actions, resource decisions, system changes).',
    module: 'MEDICAL',
    category: 'MANAGEMENT_REVIEW',
    tags: ['management-review', 'iso-13485', 'clause-5.6', 'QMS', 'continual-improvement'],
    isoClause: '5.6',
    fields: [
      {
        id: 'section_meeting_info',
        label: 'Meeting Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'review_period',
        label: 'Review Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. Q1 2026 (Jan-Mar 2026)',
        helpText: 'The period covered by this management review.',
        width: 'half',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'textarea',
        required: true,
        placeholder:
          'Name — Title\ne.g. Jane Smith — Quality Director\nJohn Doe — VP Regulatory Affairs',
        helpText:
          'Top management with executive responsibility must participate (ISO 13485 clause 5.1).',
        width: 'full',
      },
      {
        id: 'section_inputs',
        label: 'Review Inputs (ISO 13485 clause 5.6.2)',
        type: 'section',
        width: 'full',
      },
      {
        id: 'audit_results',
        label: 'Audit Results',
        type: 'textarea',
        required: true,
        placeholder:
          'Summary of internal and external audit findings, open nonconformities, and trends.',
        helpText:
          'Include both internal QMS audits and any regulatory or notified body audit findings.',
        width: 'full',
      },
      {
        id: 'customer_feedback',
        label: 'Customer Feedback (Including Complaints)',
        type: 'textarea',
        required: true,
        placeholder:
          'Summary of customer complaints, satisfaction surveys, field performance data, and feedback trends.',
        helpText:
          'Per clause 8.2.1 — feedback as input to risk management and product realization.',
        width: 'full',
      },
      {
        id: 'capa_status',
        label: 'CAPA Status',
        type: 'textarea',
        required: true,
        placeholder: 'Summary of open CAPAs, overdue CAPAs, effectiveness checks, and CAPA trends.',
        width: 'full',
      },
      {
        id: 'product_conformity',
        label: 'Product Conformity',
        type: 'textarea',
        required: true,
        placeholder:
          'Product quality metrics: reject rates, NCRs, field failures, recalls, advisory notices.',
        width: 'full',
      },
      {
        id: 'regulatory_changes',
        label: 'Regulatory Changes',
        type: 'textarea',
        required: true,
        placeholder:
          'New or changed regulations, standards, or guidance affecting the QMS (e.g. MDR updates, FDA guidances).',
        helpText: 'Per clause 5.6.2(e) — new or revised regulatory requirements.',
        width: 'full',
      },
      {
        id: 'process_performance',
        label: 'Process Performance & Monitoring',
        type: 'textarea',
        required: true,
        placeholder:
          'Key process metrics: on-time delivery, supplier quality, production yields, process validation status.',
        width: 'full',
      },
      {
        id: 'previous_actions_status',
        label: 'Status of Actions from Previous Reviews',
        type: 'textarea',
        required: true,
        placeholder:
          'Review and update status of actions assigned in the previous management review.',
        width: 'full',
      },
      {
        id: 'section_outputs',
        label: 'Review Outputs (ISO 13485 clause 5.6.3)',
        type: 'section',
        width: 'full',
      },
      {
        id: 'improvement_actions',
        label: 'Improvement Actions',
        type: 'table',
        required: true,
        helpText: 'Record all decisions and actions arising from the review.',
        columns: [
          {
            id: 'action_id',
            label: 'Action ID',
            type: 'text',
            required: true,
            placeholder: 'MR-ACT-001',
          },
          {
            id: 'description',
            label: 'Action Description',
            type: 'textarea',
            required: true,
          },
          {
            id: 'owner',
            label: 'Owner',
            type: 'text',
            required: true,
          },
          {
            id: 'due_date',
            label: 'Due Date',
            type: 'date',
            required: true,
          },
          {
            id: 'priority',
            label: 'Priority',
            type: 'select',
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
        ],
        width: 'full',
      },
      {
        id: 'resource_decisions',
        label: 'Resource Decisions',
        type: 'textarea',
        required: true,
        placeholder:
          'Decisions on resource allocation: personnel, equipment, training, infrastructure, budget.',
        helpText: 'Per clause 5.6.3(b) — resources needed to maintain the QMS.',
        width: 'full',
      },
      {
        id: 'system_changes',
        label: 'QMS Changes Required',
        type: 'textarea',
        placeholder:
          'Any changes to the quality management system, quality policy, or quality objectives.',
        width: 'full',
      },
      {
        id: 'section_next_review',
        label: 'Next Review & Approval',
        type: 'section',
        width: 'full',
      },
      {
        id: 'next_review_date',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        helpText:
          'ISO 13485 requires management reviews at planned intervals (typically quarterly or semi-annually).',
        width: 'half',
      },
      {
        id: 'chair_signature',
        label: 'Meeting Chair / Top Management',
        type: 'signature',
        required: true,
        helpText: 'Signature of the management representative or top management chair.',
        width: 'half',
      },
      {
        id: 'minutes_date',
        label: 'Minutes Approved Date',
        type: 'date',
        required: true,
        width: 'half',
      },
    ],
  },
];
