import type { TemplateDefinition } from '../types';

export const payrollTemplates: TemplateDefinition[] = [
  // ───────────────────────────────────────────────
  // TPL-PAY-001  Payroll Run Checklist
  // ───────────────────────────────────────────────
  {
    code: 'TPL-PAY-001',
    name: 'Payroll Run Checklist',
    description:
      'Pre-run and post-run checklist for payroll processing. Ensures all inputs are verified, calculations validated, and approvals obtained before disbursement.',
    module: 'PAYROLL',
    category: 'COMPLIANCE',
    tags: ['payroll-run', 'checklist', 'processing', 'verification'],
    fields: [
      {
        id: 'section_header',
        label: 'Payroll Run Details',
        type: 'section',
      },
      {
        id: 'pay_period',
        label: 'Pay Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. March 2026',
        width: 'half',
        section: 'Payroll Run Details',
      },
      {
        id: 'run_date',
        label: 'Run Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Payroll Run Details',
      },
      {
        id: 'processed_by',
        label: 'Processed By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Payroll Run Details',
      },
      {
        id: 'section_pre_run',
        label: 'Pre-Run Checks',
        type: 'section',
        helpText: 'Verify all inputs before running payroll.',
      },
      {
        id: 'pre_run_checks',
        label: 'Pre-Run Checks',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'check',
            label: 'Check Item',
            type: 'text',
            required: true,
            placeholder: 'e.g. New starters added',
          },
          {
            id: 'completed',
            label: 'Completed',
            type: 'select',
            required: true,
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
              { label: 'N/A', value: 'na' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text', placeholder: 'Any issues or comments' },
        ],
        section: 'Pre-Run Checks',
      },
      {
        id: 'section_post_run',
        label: 'Post-Run Verification',
        type: 'section',
        helpText: 'Validate outputs after payroll processing.',
      },
      {
        id: 'total_gross',
        label: 'Total Gross Pay',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Post-Run Verification',
      },
      {
        id: 'total_net',
        label: 'Total Net Pay',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Post-Run Verification',
      },
      {
        id: 'headcount',
        label: 'Employee Headcount',
        type: 'number',
        required: true,
        validation: { min: 1 },
        width: 'half',
        section: 'Post-Run Verification',
      },
      {
        id: 'variance_notes',
        label: 'Variance Notes',
        type: 'textarea',
        placeholder: 'Note any significant variances from prior period...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Post-Run Verification',
      },
      {
        id: 'approver_signature',
        label: 'Approver Signature',
        type: 'signature',
        required: true,
        section: 'Post-Run Verification',
      },
    ],
  },

  // ───────────────────────────────────────────────
  // TPL-PAY-002  Pay Variance Report
  // ───────────────────────────────────────────────
  {
    code: 'TPL-PAY-002',
    name: 'Pay Variance Report',
    description:
      'Period-over-period payroll variance analysis report. Highlights significant changes in gross pay, deductions, and headcount with explanations.',
    module: 'PAYROLL',
    category: 'REPORTING',
    tags: ['variance', 'analysis', 'period-comparison', 'payroll-report'],
    fields: [
      {
        id: 'section_header',
        label: 'Report Details',
        type: 'section',
      },
      {
        id: 'current_period',
        label: 'Current Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. March 2026',
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'comparison_period',
        label: 'Comparison Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. February 2026',
        width: 'half',
        section: 'Report Details',
      },
      {
        id: 'section_variances',
        label: 'Variance Items',
        type: 'section',
        helpText: 'Document each significant variance.',
      },
      {
        id: 'variances',
        label: 'Variances',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Gross Pay', value: 'gross_pay' },
              { label: 'Overtime', value: 'overtime' },
              { label: 'Deductions', value: 'deductions' },
              { label: 'Tax', value: 'tax' },
              { label: 'Benefits', value: 'benefits' },
              { label: 'Headcount', value: 'headcount' },
            ],
          },
          { id: 'prior_amount', label: 'Prior Period', type: 'number', required: true },
          { id: 'current_amount', label: 'Current Period', type: 'number', required: true },
          { id: 'variance', label: 'Variance', type: 'number' },
          {
            id: 'explanation',
            label: 'Explanation',
            type: 'text',
            required: true,
            placeholder: 'Reason for variance',
          },
        ],
        section: 'Variance Items',
      },
      {
        id: 'summary',
        label: 'Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Overall summary of payroll variances and recommended actions...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Variance Items',
      },
    ],
  },

  // ───────────────────────────────────────────────
  // TPL-PAY-003  Year-End Tax Summary
  // ───────────────────────────────────────────────
  {
    code: 'TPL-PAY-003',
    name: 'Year-End Tax Summary',
    description:
      'Annual tax summary report for payroll year-end processing. Covers total earnings, tax deducted, pension contributions, and statutory filings.',
    module: 'PAYROLL',
    category: 'REPORTING',
    tags: ['year-end', 'tax-summary', 'annual', 'statutory-filing'],
    fields: [
      {
        id: 'section_header',
        label: 'Year-End Details',
        type: 'section',
      },
      {
        id: 'tax_year',
        label: 'Tax Year',
        type: 'text',
        required: true,
        placeholder: 'e.g. 2025/26',
        width: 'half',
        section: 'Year-End Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Year-End Details',
      },
      {
        id: 'section_totals',
        label: 'Annual Totals',
        type: 'section',
      },
      {
        id: 'total_gross',
        label: 'Total Gross Pay',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Annual Totals',
      },
      {
        id: 'total_tax',
        label: 'Total Tax Deducted',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Annual Totals',
      },
      {
        id: 'total_ni',
        label: 'Total National Insurance / Social Security',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Annual Totals',
      },
      {
        id: 'total_pension',
        label: 'Total Pension Contributions',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Annual Totals',
      },
      {
        id: 'section_filings',
        label: 'Statutory Filings',
        type: 'section',
      },
      {
        id: 'filings',
        label: 'Filing Checklist',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'filing',
            label: 'Filing',
            type: 'text',
            required: true,
            placeholder: 'e.g. P60 Distribution',
          },
          { id: 'deadline', label: 'Deadline', type: 'date', required: true },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Not Started', value: 'not_started' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Complete', value: 'complete' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Statutory Filings',
      },
      {
        id: 'sign_off',
        label: 'Sign-Off',
        type: 'signature',
        required: true,
        section: 'Statutory Filings',
      },
    ],
  },

  // ───────────────────────────────────────────────
  // TPL-PAY-004  Payroll Reconciliation Report
  // ───────────────────────────────────────────────
  {
    code: 'TPL-PAY-004',
    name: 'Payroll Reconciliation Report',
    description:
      'Period-end payroll reconciliation report comparing payroll system outputs against general ledger entries. Covers gross pay, income tax, national insurance / social security, pension contributions, net pay, and third-party deductions with variance checks and sign-off.',
    module: 'PAYROLL',
    category: 'REPORTING',
    tags: ['reconciliation', 'payroll-audit', 'gross-net', 'tax', 'national-insurance'],
    fields: [
      {
        id: 'section_header',
        label: 'Reconciliation Details',
        type: 'section',
      },
      {
        id: 'pay_period',
        label: 'Pay Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. March 2026',
        width: 'half',
        section: 'Reconciliation Details',
      },
      {
        id: 'reconciliation_date',
        label: 'Reconciliation Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Reconciliation Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Reconciliation Details',
      },
      {
        id: 'payroll_system',
        label: 'Payroll System / Source',
        type: 'text',
        required: true,
        placeholder: 'e.g. IMS Payroll Module',
        width: 'half',
        section: 'Reconciliation Details',
      },
      {
        id: 'headcount',
        label: 'Employee Headcount',
        type: 'number',
        required: true,
        validation: { min: 1 },
        width: 'half',
        section: 'Reconciliation Details',
      },
      {
        id: 'section_figures',
        label: 'Payroll Figures',
        type: 'section',
        helpText:
          'Enter the payroll system totals and corresponding general ledger balances for each category.',
      },
      {
        id: 'payroll_figures',
        label: 'Payroll vs GL Reconciliation',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Gross Pay', value: 'gross_pay' },
              { label: 'Income Tax (PAYE)', value: 'income_tax' },
              { label: 'Employee NI / Social Security', value: 'employee_ni' },
              { label: 'Employer NI / Social Security', value: 'employer_ni' },
              { label: 'Employee Pension', value: 'employee_pension' },
              { label: 'Employer Pension', value: 'employer_pension' },
              { label: 'Student Loan Deductions', value: 'student_loan' },
              { label: 'Court Orders / Garnishments', value: 'court_orders' },
              { label: 'Voluntary Deductions', value: 'voluntary' },
              { label: 'Net Pay', value: 'net_pay' },
            ],
          },
          { id: 'payroll_amount', label: 'Payroll System', type: 'number', required: true },
          { id: 'gl_amount', label: 'General Ledger', type: 'number', required: true },
          { id: 'variance', label: 'Variance', type: 'number' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { label: 'Reconciled', value: 'reconciled' },
              { label: 'Variance — Explained', value: 'variance_explained' },
              { label: 'Variance — Unresolved', value: 'variance_unresolved' },
            ],
          },
          {
            id: 'explanation',
            label: 'Explanation',
            type: 'text',
            placeholder: 'Reason for variance if applicable',
          },
        ],
        section: 'Payroll Figures',
      },
      {
        id: 'section_control',
        label: 'Control Checks',
        type: 'section',
        helpText: 'Verify standard payroll controls have been completed.',
      },
      {
        id: 'control_checks',
        label: 'Control Checks',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'check_item',
            label: 'Control Check',
            type: 'text',
            required: true,
            placeholder: 'e.g. Bank file total matches net pay',
          },
          {
            id: 'result',
            label: 'Result',
            type: 'select',
            required: true,
            options: [
              { label: 'Pass', value: 'pass' },
              { label: 'Fail', value: 'fail' },
              { label: 'N/A', value: 'na' },
            ],
          },
          { id: 'notes', label: 'Notes', type: 'text' },
        ],
        section: 'Control Checks',
      },
      {
        id: 'section_summary',
        label: 'Reconciliation Summary',
        type: 'section',
      },
      {
        id: 'overall_status',
        label: 'Overall Reconciliation Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Fully Reconciled', value: 'fully_reconciled' },
          { label: 'Reconciled with Explained Variances', value: 'reconciled_with_variances' },
          { label: 'Unresolved Variances — Escalated', value: 'unresolved' },
        ],
        width: 'half',
        section: 'Reconciliation Summary',
      },
      {
        id: 'summary_notes',
        label: 'Summary Notes',
        type: 'textarea',
        required: true,
        placeholder:
          'Summarise reconciliation outcome, any outstanding items, and actions taken...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Reconciliation Summary',
      },
      {
        id: 'payroll_officer_signature',
        label: 'Payroll Officer Signature',
        type: 'signature',
        required: true,
        section: 'Reconciliation Summary',
      },
      {
        id: 'finance_reviewer_signature',
        label: 'Finance Reviewer Signature',
        type: 'signature',
        required: true,
        section: 'Reconciliation Summary',
      },
    ],
  },

  // ───────────────────────────────────────────────
  // TPL-PAY-005  Overtime Authorisation Form
  // ───────────────────────────────────────────────
  {
    code: 'TPL-PAY-005',
    name: 'Overtime Authorisation Form',
    description:
      'Pre-approval form for overtime hours. Captures business justification, estimated hours and cost, budget impact assessment, and manager authorisation. Must be completed before overtime is worked.',
    module: 'PAYROLL',
    category: 'COMPLIANCE',
    tags: ['overtime', 'authorisation', 'pre-approval', 'working-hours', 'budget-impact'],
    fields: [
      {
        id: 'section_header',
        label: 'Request Details',
        type: 'section',
      },
      {
        id: 'request_date',
        label: 'Request Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Request Details',
      },
      {
        id: 'requester_name',
        label: 'Requesting Manager',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Request Details',
      },
      {
        id: 'department',
        label: 'Department',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Request Details',
      },
      {
        id: 'overtime_type',
        label: 'Overtime Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Planned — Project Deadline', value: 'planned_project' },
          { label: 'Planned — Seasonal Demand', value: 'planned_seasonal' },
          { label: 'Unplanned — Emergency / Breakdown', value: 'unplanned_emergency' },
          { label: 'Unplanned — Staff Shortage', value: 'unplanned_shortage' },
          { label: 'Mandatory — Regulatory Deadline', value: 'mandatory_regulatory' },
        ],
        width: 'half',
        section: 'Request Details',
      },
      {
        id: 'section_justification',
        label: 'Business Justification',
        type: 'section',
        helpText: 'Provide a clear business case for the overtime request.',
      },
      {
        id: 'justification',
        label: 'Justification',
        type: 'textarea',
        required: true,
        placeholder:
          'Explain why overtime is necessary, what alternatives were considered, and the consequence of not approving...',
        validation: { minLength: 20, maxLength: 2000 },
        width: 'full',
        section: 'Business Justification',
      },
      {
        id: 'alternatives_considered',
        label: 'Alternatives Considered',
        type: 'select',
        required: true,
        options: [
          { label: 'Temporary Staff', value: 'temp_staff' },
          { label: 'Reprioritisation', value: 'reprioritise' },
          { label: 'Deadline Extension', value: 'deadline_extension' },
          { label: 'None Available', value: 'none' },
        ],
        width: 'half',
        section: 'Business Justification',
      },
      {
        id: 'section_employees',
        label: 'Employee Overtime Schedule',
        type: 'section',
        helpText:
          'List each employee and their planned overtime hours. Ensure compliance with Working Time Regulations.',
      },
      {
        id: 'overtime_schedule',
        label: 'Overtime Schedule',
        type: 'table',
        required: true,
        columns: [
          { id: 'employee_name', label: 'Employee Name', type: 'text', required: true },
          { id: 'employee_id', label: 'Employee ID', type: 'text', required: true },
          { id: 'role', label: 'Role', type: 'text', required: true },
          { id: 'date_from', label: 'From Date', type: 'date', required: true },
          { id: 'date_to', label: 'To Date', type: 'date', required: true },
          {
            id: 'estimated_hours',
            label: 'Est. Hours',
            type: 'number',
            required: true,
            validation: { min: 0.5 },
          },
          {
            id: 'rate_multiplier',
            label: 'Rate Multiplier',
            type: 'select',
            required: true,
            options: [
              { label: '1.0x (Standard)', value: '1.0' },
              { label: '1.5x (Time and a Half)', value: '1.5' },
              { label: '2.0x (Double Time)', value: '2.0' },
            ],
          },
          {
            id: 'estimated_cost',
            label: 'Est. Cost',
            type: 'number',
            required: true,
            validation: { min: 0 },
          },
        ],
        section: 'Employee Overtime Schedule',
      },
      {
        id: 'section_wtr',
        label: 'Working Time Compliance',
        type: 'section',
        helpText:
          'Confirm that overtime will not breach Working Time Regulations or contractual limits.',
      },
      {
        id: 'max_weekly_hours_check',
        label: 'All employees will remain under 48 hours/week (or have opted out)?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Confirmed', value: 'yes' },
          { label: 'No — Opt-Out Required', value: 'no' },
        ],
        width: 'half',
        section: 'Working Time Compliance',
      },
      {
        id: 'rest_period_check',
        label: 'Minimum rest periods (11 hours daily, 24 hours weekly) maintained?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes — Confirmed', value: 'yes' },
          { label: 'No — Exception Documented', value: 'no' },
        ],
        width: 'half',
        section: 'Working Time Compliance',
      },
      {
        id: 'wtr_notes',
        label: 'Compliance Notes',
        type: 'textarea',
        placeholder: 'Document any opt-out forms, exceptions, or special arrangements...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Working Time Compliance',
      },
      {
        id: 'section_budget',
        label: 'Budget Impact',
        type: 'section',
        helpText:
          'Assess the financial impact of the overtime request against departmental budget.',
      },
      {
        id: 'total_estimated_cost',
        label: 'Total Estimated Cost',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Budget Impact',
      },
      {
        id: 'overtime_budget_remaining',
        label: 'Overtime Budget Remaining',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'half',
        section: 'Budget Impact',
      },
      {
        id: 'within_budget',
        label: 'Within Overtime Budget?',
        type: 'select',
        required: true,
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Budget Overspend', value: 'no' },
        ],
        width: 'half',
        section: 'Budget Impact',
      },
      {
        id: 'budget_notes',
        label: 'Budget Notes',
        type: 'textarea',
        placeholder: 'If exceeding budget, explain how overspend will be managed...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Budget Impact',
      },
      {
        id: 'section_approval',
        label: 'Authorisation',
        type: 'section',
      },
      {
        id: 'decision',
        label: 'Decision',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Approved with Conditions', value: 'conditional' },
          { label: 'Rejected', value: 'rejected' },
        ],
        width: 'half',
        section: 'Authorisation',
      },
      {
        id: 'conditions',
        label: 'Conditions / Comments',
        type: 'textarea',
        placeholder: 'If approved with conditions, specify requirements...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Authorisation',
      },
      {
        id: 'requesting_manager_signature',
        label: 'Requesting Manager Signature',
        type: 'signature',
        required: true,
        section: 'Authorisation',
      },
      {
        id: 'approver_signature',
        label: 'Approver Signature',
        type: 'signature',
        required: true,
        section: 'Authorisation',
      },
    ],
  },
];
