import type { TemplateDefinition } from '../types';

export const qualityTemplates: TemplateDefinition[] = [
  // ─── TPL-QMS-001  Non-Conformance Report ─────────────────────────────
  {
    code: 'TPL-QMS-001',
    name: 'Non-Conformance Report',
    description:
      'Standard non-conformance report for documenting product or process deviations, root cause analysis, and corrective actions per ISO 9001:2015 clause 10.2.',
    module: 'QUALITY',
    category: 'CAPA',
    tags: ['ncr', 'non-conformance', 'deviation', 'corrective-action', 'iso-9001'],
    isoClause: '10.2',
    fields: [
      {
        id: 'ncr-header',
        label: 'NCR Details',
        type: 'section',
        width: 'full',
      },
      {
        id: 'ncrRef',
        label: 'NCR Reference Number',
        type: 'text',
        required: true,
        placeholder: 'NCR-2026-001',
        helpText: 'Auto-generated reference number for this non-conformance report.',
        width: 'half',
      },
      {
        id: 'ncrDate',
        label: 'Date Raised',
        type: 'date',
        required: true,
        helpText: 'Date the non-conformance was identified.',
        width: 'half',
      },
      {
        id: 'source',
        label: 'Source of Non-Conformance',
        type: 'select',
        required: true,
        helpText: 'Where the non-conformance was detected.',
        options: [
          { label: 'Incoming Inspection', value: 'incoming_inspection' },
          { label: 'In-Process Inspection', value: 'in_process_inspection' },
          { label: 'Final Inspection', value: 'final_inspection' },
          { label: 'Customer Complaint', value: 'customer_complaint' },
          { label: 'Internal Audit', value: 'internal_audit' },
          { label: 'Supplier Audit', value: 'supplier_audit' },
          { label: 'Management Review', value: 'management_review' },
          { label: 'Field Return', value: 'field_return' },
        ],
        width: 'half',
      },
      {
        id: 'productProcess',
        label: 'Product / Process Affected',
        type: 'text',
        required: true,
        placeholder: 'Enter product name, part number, or process identifier',
        helpText: 'Identify the specific product, component, or process where the NC occurred.',
        width: 'half',
      },
      {
        id: 'ncDescription',
        label: 'Non-Conformance Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the non-conformance in detail including what was found, expected vs actual...',
        helpText: 'Provide a clear, factual description of the deviation from requirements.',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
      },
      {
        id: 'disposition',
        label: 'Disposition',
        type: 'select',
        required: true,
        helpText: 'Decision on how the non-conforming item will be handled.',
        options: [
          { label: 'Use As Is', value: 'use_as_is' },
          { label: 'Rework', value: 'rework' },
          { label: 'Scrap', value: 'scrap' },
          { label: 'Return to Supplier', value: 'return_to_supplier' },
          { label: 'Concession', value: 'concession' },
        ],
        width: 'half',
      },
      {
        id: 'rootCause',
        label: 'Root Cause Analysis',
        type: 'textarea',
        required: true,
        placeholder: 'Detail the root cause analysis performed (5-Why, fishbone, etc.)',
        helpText: 'Document the analysis method used and the identified root cause(s).',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
      },
      {
        id: 'containmentActions',
        label: 'Containment Actions',
        type: 'textarea',
        placeholder: 'Describe immediate actions taken to contain the non-conformance...',
        helpText:
          'Actions taken to prevent further non-conforming product from being produced or shipped.',
        width: 'full',
      },
      {
        id: 'correctiveActions',
        label: 'Corrective Actions',
        type: 'table',
        required: true,
        helpText: 'List all corrective actions to eliminate the root cause.',
        columns: [
          { id: 'caNumber', label: '#', type: 'number', width: 'third' },
          {
            id: 'caDescription',
            label: 'Action Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          {
            id: 'caResponsible',
            label: 'Responsible Person',
            type: 'text',
            required: true,
            width: 'half',
          },
          { id: 'caTargetDate', label: 'Target Date', type: 'date', required: true, width: 'half' },
          {
            id: 'caStatus',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Completed', value: 'completed' },
              { label: 'Verified', value: 'verified' },
            ],
            width: 'half',
          },
        ],
        width: 'full',
      },
      {
        id: 'costImpact',
        label: 'Cost of Non-Conformance',
        type: 'number',
        placeholder: '0.00',
        helpText: 'Estimated total cost including scrap, rework, inspection, and customer impact.',
        validation: { min: 0 },
        width: 'half',
      },
      {
        id: 'verificationDetails',
        label: 'Verification of Effectiveness',
        type: 'textarea',
        placeholder:
          'Describe how effectiveness of corrective actions will be or has been verified...',
        helpText:
          'Evidence that corrective actions have eliminated the root cause and prevented recurrence.',
        width: 'full',
      },
      {
        id: 'signOff',
        label: 'Sign-Off',
        type: 'signature',
        required: true,
        helpText: 'Quality Manager approval and closure signature.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-002  Customer Complaint Form ─────────────────────────────
  {
    code: 'TPL-QMS-002',
    name: 'Customer Complaint Form',
    description:
      'Formal customer complaint registration and resolution form per ISO 9001:2015 clause 9.1.2 for monitoring customer satisfaction.',
    module: 'QUALITY',
    category: 'CUSTOMER',
    tags: ['customer', 'complaint', 'satisfaction', 'resolution', 'iso-9001'],
    isoClause: '9.1.2',
    fields: [
      {
        id: 'complaint-header',
        label: 'Complaint Registration',
        type: 'section',
        width: 'full',
      },
      {
        id: 'complaintRef',
        label: 'Complaint Reference',
        type: 'text',
        required: true,
        placeholder: 'CC-2026-001',
        helpText: 'Unique reference number for tracking.',
        width: 'half',
      },
      {
        id: 'customerName',
        label: 'Customer Name',
        type: 'text',
        required: true,
        placeholder: 'Full company or customer name',
        width: 'half',
      },
      {
        id: 'dateReceived',
        label: 'Date Received',
        type: 'date',
        required: true,
        helpText: 'Date the complaint was received from the customer.',
        width: 'half',
      },
      {
        id: 'product',
        label: 'Product / Service',
        type: 'text',
        required: true,
        placeholder: 'Product name, part number, or service description',
        helpText: 'The product or service the complaint relates to.',
        width: 'half',
      },
      {
        id: 'complaintDescription',
        label: 'Complaint Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the customer complaint in detail...',
        helpText: 'Record the complaint exactly as communicated by the customer.',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        helpText: 'Assessed severity of the complaint impact.',
        options: [
          { label: 'Low - Minor inconvenience', value: 'low' },
          { label: 'Medium - Functional impact', value: 'medium' },
          { label: 'High - Significant impact', value: 'high' },
          { label: 'Critical - Safety or regulatory', value: 'critical' },
        ],
        width: 'half',
      },
      {
        id: 'investigation-section',
        label: 'Investigation & Resolution',
        type: 'section',
        width: 'full',
      },
      {
        id: 'immediateAction',
        label: 'Immediate Action Taken',
        type: 'textarea',
        placeholder: 'Describe any immediate containment or response actions...',
        helpText: 'Actions taken immediately upon receiving the complaint.',
        width: 'full',
      },
      {
        id: 'investigationFindings',
        label: 'Investigation Findings',
        type: 'textarea',
        required: true,
        placeholder: 'Document the investigation process and findings...',
        helpText: 'Results of the investigation into the complaint cause.',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'rootCause',
        label: 'Root Cause',
        type: 'textarea',
        required: true,
        placeholder: 'Identified root cause of the customer complaint...',
        helpText: 'The underlying root cause determined through investigation.',
        width: 'full',
      },
      {
        id: 'correctiveActions',
        label: 'Corrective Actions',
        type: 'table',
        required: true,
        helpText: 'Actions to prevent recurrence.',
        columns: [
          { id: 'caNumber', label: '#', type: 'number', width: 'third' },
          { id: 'caDescription', label: 'Action', type: 'textarea', required: true, width: 'full' },
          { id: 'caOwner', label: 'Owner', type: 'text', required: true, width: 'half' },
          { id: 'caDeadline', label: 'Deadline', type: 'date', required: true, width: 'half' },
          {
            id: 'caStatus',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Pending', value: 'pending' },
              { label: 'In Progress', value: 'in_progress' },
              { label: 'Completed', value: 'completed' },
            ],
            width: 'half',
          },
        ],
        width: 'full',
      },
      {
        id: 'customerResponse',
        label: 'Customer Response / Feedback',
        type: 'textarea',
        placeholder: 'Record customer response to the proposed resolution...',
        helpText: 'Customer acknowledgement and satisfaction with the resolution.',
        width: 'full',
      },
      {
        id: 'closeDate',
        label: 'Close Date',
        type: 'date',
        helpText: 'Date the complaint was formally closed.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-003  8D Problem Solving Report ──────────────────────────
  {
    code: 'TPL-QMS-003',
    name: '8D Problem Solving Report',
    description:
      'Structured 8-discipline problem solving methodology report. Guides teams through identification, containment, root cause analysis, and permanent corrective action.',
    module: 'QUALITY',
    category: 'CAPA',
    tags: ['8d', 'problem-solving', 'root-cause', 'corrective-action', 'team-based'],
    isoClause: '10.2',
    fields: [
      {
        id: '8d-header',
        label: '8D Report Header',
        type: 'section',
        width: 'full',
      },
      {
        id: 'eightDNumber',
        label: '8D Report Number',
        type: 'text',
        required: true,
        placeholder: '8D-2026-001',
        helpText: 'Unique identifier for this 8D report.',
        width: 'half',
      },
      {
        id: 'reportDate',
        label: 'Date Initiated',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'd1-section',
        label: 'D1 - Establish the Team',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd1TeamMembers',
        label: 'Team Members',
        type: 'table',
        required: true,
        helpText:
          'Select a cross-functional team with the process/product knowledge to solve the problem.',
        columns: [
          { id: 'memberName', label: 'Name', type: 'text', required: true, width: 'half' },
          {
            id: 'memberRole',
            label: 'Role / Function',
            type: 'text',
            required: true,
            width: 'half',
          },
          { id: 'memberDept', label: 'Department', type: 'text', width: 'half' },
        ],
        width: 'full',
      },
      {
        id: 'd1Champion',
        label: 'Team Champion / Sponsor',
        type: 'text',
        required: true,
        placeholder: 'Name of management sponsor',
        helpText: 'Management representative who can allocate resources and remove roadblocks.',
        width: 'half',
      },
      {
        id: 'd2-section',
        label: 'D2 - Describe the Problem',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd2ProblemDescription',
        label: 'Problem Description',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe the problem using 5W2H: Who, What, When, Where, Why, How, How many...',
        helpText: 'Quantify the problem using measurable terms. Use IS / IS NOT analysis.',
        validation: { minLength: 50, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'd3-section',
        label: 'D3 - Develop Interim Containment Actions',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd3Containment',
        label: 'Interim Containment Actions',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe actions to protect the customer from the problem until permanent fix...',
        helpText:
          'Actions to isolate the effect of the problem from the customer. Verify effectiveness of containment.',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
      },
      {
        id: 'd4-section',
        label: 'D4 - Identify and Verify Root Cause',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd4RootCause',
        label: 'Root Cause Analysis',
        type: 'textarea',
        required: true,
        placeholder: 'Document the root cause analysis findings...',
        helpText:
          'Identify all potential causes. Test each against the problem description. Verify the true root cause.',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
      },
      {
        id: 'd4FiveWhy',
        label: '5-Why Analysis',
        type: 'textarea',
        placeholder: 'Why 1: ...\nWhy 2: ...\nWhy 3: ...\nWhy 4: ...\nWhy 5: ...',
        helpText: 'Apply the 5-Why technique to drill down to the root cause.',
        width: 'full',
      },
      {
        id: 'd5-section',
        label: 'D5 - Choose and Verify Permanent Corrective Actions',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd5CorrectiveActions',
        label: 'Permanent Corrective Actions',
        type: 'textarea',
        required: true,
        placeholder: 'Describe permanent corrective actions that address the root cause...',
        helpText:
          'Select the best permanent corrective action(s). Verify they resolve the problem without undesirable side effects.',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
      },
      {
        id: 'd6-section',
        label: 'D6 - Implement and Validate Permanent Corrective Actions',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd6Implementation',
        label: 'Implementation Plan',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the implementation steps, timeline, and monitoring plan...',
        helpText:
          'Define implementation plan, remove containment actions, and monitor long-term effectiveness.',
        width: 'full',
      },
      {
        id: 'd7-section',
        label: 'D7 - Prevent Recurrence',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd7PreventiveActions',
        label: 'Preventive Actions',
        type: 'textarea',
        required: true,
        placeholder:
          'Describe systemic changes to prevent recurrence across similar products/processes...',
        helpText:
          'Modify systems, procedures, standards, and training to prevent this and similar problems.',
        width: 'full',
      },
      {
        id: 'd8-section',
        label: 'D8 - Congratulate the Team',
        type: 'section',
        width: 'full',
      },
      {
        id: 'd8Recognition',
        label: 'Team Recognition',
        type: 'textarea',
        placeholder: 'Acknowledge team effort, key learnings, and contributions...',
        helpText: 'Recognize the collective effort of the team. Document lessons learned.',
        width: 'full',
      },
      {
        id: 'verificationDate',
        label: 'Verification Date',
        type: 'date',
        helpText: 'Date when effectiveness of corrective actions was verified.',
        width: 'half',
      },
      {
        id: 'signOff',
        label: 'Quality Manager Sign-Off',
        type: 'signature',
        required: true,
        helpText: 'Final approval to close the 8D report.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-004  CAPA Request ────────────────────────────────────────
  {
    code: 'TPL-QMS-004',
    name: 'CAPA Request',
    description:
      'Corrective and Preventive Action (CAPA) request form for initiating, tracking, and verifying CAPAs per ISO 9001:2015 clause 10.2 and 10.3.',
    module: 'QUALITY',
    category: 'CAPA',
    tags: ['capa', 'corrective', 'preventive', 'root-cause', 'iso-9001'],
    isoClause: '10.2',
    fields: [
      {
        id: 'capa-header',
        label: 'CAPA Details',
        type: 'section',
        width: 'full',
      },
      {
        id: 'capaNumber',
        label: 'CAPA Number',
        type: 'text',
        required: true,
        placeholder: 'CAPA-2026-001',
        helpText: 'Unique CAPA tracking number.',
        width: 'half',
      },
      {
        id: 'capaType',
        label: 'CAPA Type',
        type: 'select',
        required: true,
        helpText: 'Whether this is a corrective or preventive action.',
        options: [
          { label: 'Corrective Action', value: 'corrective' },
          { label: 'Preventive Action', value: 'preventive' },
        ],
        width: 'half',
      },
      {
        id: 'capaSource',
        label: 'Source',
        type: 'select',
        required: true,
        helpText: 'Origin of the CAPA request.',
        options: [
          { label: 'Internal Audit', value: 'internal_audit' },
          { label: 'External Audit', value: 'external_audit' },
          { label: 'Customer Complaint', value: 'customer_complaint' },
          { label: 'Non-Conformance Report', value: 'ncr' },
          { label: 'Management Review', value: 'management_review' },
          { label: 'Process Monitoring', value: 'process_monitoring' },
          { label: 'Trend Analysis', value: 'trend_analysis' },
          { label: 'Risk Assessment', value: 'risk_assessment' },
        ],
        width: 'half',
      },
      {
        id: 'capaDescription',
        label: 'Description of Issue',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the issue, non-conformance, or risk that requires CAPA...',
        helpText: 'Detailed description of the problem or potential problem.',
        validation: { minLength: 20, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'riskAssessment',
        label: 'Risk Assessment',
        type: 'textarea',
        required: true,
        placeholder: 'Assess the risk: likelihood, severity, and potential impact...',
        helpText:
          'Evaluate the risk to product quality, customer satisfaction, and regulatory compliance.',
        width: 'full',
      },
      {
        id: 'analysis-section',
        label: 'Root Cause Analysis',
        type: 'section',
        width: 'full',
      },
      {
        id: 'rootCauseAnalysis',
        label: 'Root Cause Analysis',
        type: 'textarea',
        required: true,
        placeholder: 'Document the root cause analysis method and findings...',
        helpText:
          'Use appropriate analysis tools (5-Why, fishbone, fault tree, etc.) to determine root cause.',
        validation: { minLength: 30, maxLength: 5000 },
        width: 'full',
      },
      {
        id: 'actions-section',
        label: 'Proposed Actions & Implementation',
        type: 'section',
        width: 'full',
      },
      {
        id: 'proposedActions',
        label: 'Proposed Actions',
        type: 'table',
        required: true,
        helpText: 'Define specific, measurable actions to address the root cause.',
        columns: [
          { id: 'actionNumber', label: '#', type: 'number', width: 'third' },
          {
            id: 'actionDescription',
            label: 'Action Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          { id: 'actionOwner', label: 'Owner', type: 'text', required: true, width: 'half' },
          {
            id: 'actionPriority',
            label: 'Priority',
            type: 'select',
            options: [
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
            width: 'third',
          },
          {
            id: 'actionTargetDate',
            label: 'Target Date',
            type: 'date',
            required: true,
            width: 'half',
          },
        ],
        width: 'full',
      },
      {
        id: 'implementationTimeline',
        label: 'Implementation Timeline',
        type: 'textarea',
        placeholder: 'Define the overall timeline including key milestones...',
        helpText: 'Overview of the implementation schedule.',
        width: 'full',
      },
      {
        id: 'verification-section',
        label: 'Verification & Closure',
        type: 'section',
        width: 'full',
      },
      {
        id: 'effectivenessCriteria',
        label: 'Effectiveness Criteria',
        type: 'textarea',
        required: true,
        placeholder: 'Define measurable criteria for determining CAPA effectiveness...',
        helpText:
          'How will you know the CAPA was effective? Define measurable acceptance criteria.',
        width: 'full',
      },
      {
        id: 'verificationMethod',
        label: 'Verification Method',
        type: 'select',
        required: true,
        helpText: 'Method used to verify CAPA effectiveness.',
        options: [
          { label: 'Audit', value: 'audit' },
          { label: 'Inspection / Test', value: 'inspection_test' },
          { label: 'Data Analysis / Trend Review', value: 'data_analysis' },
          { label: 'Process Monitoring', value: 'process_monitoring' },
          { label: 'Customer Feedback', value: 'customer_feedback' },
        ],
        width: 'half',
      },
      {
        id: 'signOff',
        label: 'Approval Sign-Off',
        type: 'signature',
        required: true,
        helpText: 'Quality Manager approval for the CAPA plan.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-005  ISO 9001 Internal Audit Checklist ───────────────────
  {
    code: 'TPL-QMS-005',
    name: 'ISO 9001 Internal Audit Checklist',
    description:
      'Comprehensive internal audit checklist covering all clauses of ISO 9001:2015. Used by internal auditors to assess QMS conformity and effectiveness.',
    module: 'QUALITY',
    category: 'AUDIT',
    tags: ['audit', 'internal-audit', 'iso-9001', 'checklist', 'conformity'],
    isoClause: '9.2',
    fields: [
      {
        id: 'audit-header',
        label: 'Audit Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'auditNumber',
        label: 'Audit Number',
        type: 'text',
        required: true,
        placeholder: 'IA-2026-001',
        helpText: 'Unique internal audit reference number.',
        width: 'third',
      },
      {
        id: 'auditScope',
        label: 'Audit Scope',
        type: 'textarea',
        required: true,
        placeholder: 'Define the processes, departments, and clauses to be audited...',
        helpText: 'Boundaries and extent of the audit.',
        validation: { minLength: 10, maxLength: 2000 },
        width: 'full',
      },
      {
        id: 'leadAuditor',
        label: 'Lead Auditor',
        type: 'text',
        required: true,
        placeholder: 'Name of lead auditor',
        width: 'half',
      },
      {
        id: 'auditDate',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'clauses-section',
        label: 'ISO 9001:2015 Clause Assessment',
        type: 'section',
        width: 'full',
      },
      {
        id: 'clauseAssessment',
        label: 'Clause Assessment',
        type: 'table',
        required: true,
        helpText: 'Evaluate each applicable ISO 9001:2015 clause.',
        columns: [
          {
            id: 'clauseNumber',
            label: 'Clause',
            type: 'text',
            required: true,
            placeholder: 'e.g. 4.1',
            width: 'third',
          },
          {
            id: 'requirement',
            label: 'Requirement',
            type: 'text',
            required: true,
            placeholder: 'e.g. Understanding the organization and its context',
            width: 'full',
          },
          {
            id: 'conformity',
            label: 'Conformity',
            type: 'select',
            required: true,
            options: [
              { label: 'Conforming', value: 'conforming' },
              { label: 'Minor NC', value: 'minor_nc' },
              { label: 'Major NC', value: 'major_nc' },
              { label: 'Observation', value: 'observation' },
              { label: 'Not Applicable', value: 'na' },
            ],
            width: 'half',
          },
          {
            id: 'evidence',
            label: 'Objective Evidence',
            type: 'textarea',
            placeholder: 'Document, record, or observation reference...',
            width: 'full',
          },
          {
            id: 'finding',
            label: 'Finding / Notes',
            type: 'textarea',
            placeholder: 'Details of any non-conformity or observation...',
            width: 'full',
          },
        ],
        width: 'full',
      },
      {
        id: 'findings-section',
        label: 'Findings Summary',
        type: 'section',
        width: 'full',
      },
      {
        id: 'ncrs',
        label: 'Non-Conformance Reports Raised',
        type: 'table',
        helpText: 'List all NCRs raised during this audit.',
        columns: [
          { id: 'ncrRef', label: 'NCR Reference', type: 'text', required: true, width: 'half' },
          { id: 'ncrClause', label: 'Clause', type: 'text', required: true, width: 'third' },
          {
            id: 'ncrGrade',
            label: 'Grade',
            type: 'select',
            options: [
              { label: 'Minor', value: 'minor' },
              { label: 'Major', value: 'major' },
            ],
            required: true,
            width: 'third',
          },
          {
            id: 'ncrDescription',
            label: 'Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
        ],
        width: 'full',
      },
      {
        id: 'ofis',
        label: 'Opportunities for Improvement (OFIs)',
        type: 'textarea',
        placeholder: 'List any opportunities for improvement identified during the audit...',
        helpText: 'Observations that are not non-conformities but could improve the QMS.',
        width: 'full',
      },
      {
        id: 'auditorSignature',
        label: 'Auditor Signature',
        type: 'signature',
        required: true,
        helpText: 'Lead auditor confirmation of audit findings.',
        width: 'half',
      },
      {
        id: 'auditeeSignature',
        label: 'Auditee Signature',
        type: 'signature',
        required: true,
        helpText: 'Auditee acknowledgement of audit findings.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-006  Supplier Audit Report ───────────────────────────────
  {
    code: 'TPL-QMS-006',
    name: 'Supplier Audit Report',
    description:
      'Supplier quality audit report for evaluating supplier QMS capability and compliance. Supports approved supplier list management per ISO 9001:2015 clause 8.4.',
    module: 'QUALITY',
    category: 'SUPPLIER',
    tags: ['supplier', 'audit', 'evaluation', 'approved-supplier', 'iso-9001'],
    isoClause: '8.4',
    fields: [
      {
        id: 'supplier-header',
        label: 'Supplier Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'supplierName',
        label: 'Supplier Name',
        type: 'text',
        required: true,
        placeholder: 'Full registered company name',
        width: 'half',
      },
      {
        id: 'auditDate',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'auditor',
        label: 'Lead Auditor',
        type: 'text',
        required: true,
        placeholder: 'Name of lead auditor',
        width: 'half',
      },
      {
        id: 'auditScope',
        label: 'Audit Scope',
        type: 'textarea',
        required: true,
        placeholder: 'Products/services supplied, processes audited, standards referenced...',
        helpText: 'Define the scope including products, processes, and applicable standards.',
        width: 'full',
      },
      {
        id: 'assessment-section',
        label: 'Quality System Assessment',
        type: 'section',
        width: 'full',
      },
      {
        id: 'clauseAssessment',
        label: 'Clause Assessment',
        type: 'table',
        required: true,
        helpText: 'Assess supplier quality system against applicable requirements.',
        columns: [
          { id: 'area', label: 'Assessment Area', type: 'text', required: true, width: 'half' },
          {
            id: 'rating',
            label: 'Rating',
            type: 'select',
            required: true,
            options: [
              { label: 'Fully Conforming', value: 'full' },
              { label: 'Partially Conforming', value: 'partial' },
              { label: 'Non-Conforming', value: 'non_conforming' },
              { label: 'Not Applicable', value: 'na' },
            ],
            width: 'half',
          },
          { id: 'evidence', label: 'Evidence / Notes', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'qualitySystemRating',
        label: 'Overall Quality System Rating',
        type: 'rating',
        required: true,
        helpText: 'Rate the overall quality system maturity from 1 (poor) to 5 (excellent).',
        width: 'half',
      },
      {
        id: 'strengths',
        label: 'Strengths',
        type: 'textarea',
        placeholder: 'Key strengths identified during the audit...',
        helpText: 'Notable areas where the supplier excels.',
        width: 'full',
      },
      {
        id: 'weaknesses',
        label: 'Weaknesses',
        type: 'textarea',
        placeholder: 'Key weaknesses and areas for improvement...',
        helpText: 'Areas requiring improvement or development.',
        width: 'full',
      },
      {
        id: 'ncrs',
        label: 'Non-Conformance Reports',
        type: 'table',
        helpText: 'List all NCRs raised during the supplier audit.',
        columns: [
          { id: 'ncrRef', label: 'NCR #', type: 'text', required: true, width: 'third' },
          { id: 'ncrArea', label: 'Area', type: 'text', required: true, width: 'half' },
          {
            id: 'ncrGrade',
            label: 'Grade',
            type: 'select',
            options: [
              { label: 'Minor', value: 'minor' },
              { label: 'Major', value: 'major' },
            ],
            required: true,
            width: 'third',
          },
          {
            id: 'ncrDescription',
            label: 'Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          {
            id: 'ncrCorrective',
            label: 'Required Corrective Action',
            type: 'textarea',
            width: 'full',
          },
        ],
        width: 'full',
      },
      {
        id: 'overallScore',
        label: 'Overall Audit Score (%)',
        type: 'number',
        helpText: 'Calculated overall score as a percentage.',
        validation: { min: 0, max: 100 },
        width: 'half',
      },
      {
        id: 'recommendation',
        label: 'Recommendation',
        type: 'select',
        required: true,
        helpText: 'Final recommendation based on audit findings.',
        options: [
          { label: 'Approved', value: 'approved' },
          { label: 'Conditionally Approved', value: 'conditional' },
          { label: 'Not Approved', value: 'not_approved' },
        ],
        width: 'half',
      },
      {
        id: 'followUpDate',
        label: 'Follow-Up Audit Date',
        type: 'date',
        helpText: 'Scheduled date for follow-up audit (if conditionally approved or not approved).',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-007  Process Audit Checklist ─────────────────────────────
  {
    code: 'TPL-QMS-007',
    name: 'Process Audit Checklist',
    description:
      'Process-based audit checklist for evaluating process effectiveness, controls, and compliance. Focuses on inputs, outputs, and control points per ISO 9001:2015 clause 4.4.',
    module: 'QUALITY',
    category: 'AUDIT',
    tags: ['process-audit', 'audit', 'checklist', 'process-control', 'effectiveness'],
    isoClause: '4.4',
    fields: [
      {
        id: 'process-header',
        label: 'Process Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'processName',
        label: 'Process Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Machining, Assembly, Welding',
        width: 'half',
      },
      {
        id: 'processOwner',
        label: 'Process Owner',
        type: 'text',
        required: true,
        placeholder: 'Name of process owner',
        width: 'half',
      },
      {
        id: 'auditDate',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'auditor',
        label: 'Auditor',
        type: 'text',
        required: true,
        placeholder: 'Name of auditor',
        width: 'half',
      },
      {
        id: 'processInputs',
        label: 'Process Inputs',
        type: 'textarea',
        required: true,
        placeholder: 'List all process inputs (materials, information, resources, criteria)...',
        helpText:
          'Identify what enters the process including raw materials, work instructions, specifications.',
        width: 'half',
      },
      {
        id: 'processOutputs',
        label: 'Process Outputs',
        type: 'textarea',
        required: true,
        placeholder: 'List all process outputs (products, records, data)...',
        helpText: 'Identify what the process produces or delivers.',
        width: 'half',
      },
      {
        id: 'controls-section',
        label: 'Control Points Assessment',
        type: 'section',
        width: 'full',
      },
      {
        id: 'controlPoints',
        label: 'Control Points',
        type: 'table',
        required: true,
        helpText: 'Evaluate each control point in the process.',
        columns: [
          { id: 'controlStep', label: 'Process Step', type: 'text', required: true, width: 'half' },
          {
            id: 'controlParam',
            label: 'Control Parameter',
            type: 'text',
            required: true,
            width: 'half',
          },
          { id: 'controlMethod', label: 'Control Method', type: 'text', width: 'half' },
          { id: 'controlSpec', label: 'Specification / Limit', type: 'text', width: 'half' },
          {
            id: 'controlConformity',
            label: 'Conformity',
            type: 'select',
            options: [
              { label: 'Conforming', value: 'conforming' },
              { label: 'Non-Conforming', value: 'non_conforming' },
              { label: 'Observation', value: 'observation' },
            ],
            required: true,
            width: 'half',
          },
          { id: 'controlNotes', label: 'Notes', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'measurementCriteria',
        label: 'Measurement Criteria',
        type: 'textarea',
        placeholder: 'KPIs, acceptance criteria, and measurement methods used...',
        helpText: 'How process performance is measured and monitored.',
        width: 'full',
      },
      {
        id: 'findings-section',
        label: 'Findings',
        type: 'section',
        width: 'full',
      },
      {
        id: 'findings',
        label: 'Audit Findings',
        type: 'table',
        helpText: 'Document all findings from the process audit.',
        columns: [
          { id: 'findingRef', label: 'Finding #', type: 'text', required: true, width: 'third' },
          {
            id: 'findingType',
            label: 'Type',
            type: 'select',
            options: [
              { label: 'Major NC', value: 'major_nc' },
              { label: 'Minor NC', value: 'minor_nc' },
              { label: 'Observation', value: 'observation' },
              { label: 'OFI', value: 'ofi' },
            ],
            required: true,
            width: 'half',
          },
          {
            id: 'findingDescription',
            label: 'Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          { id: 'findingAction', label: 'Required Action', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'effectivenessRating',
        label: 'Process Effectiveness Rating',
        type: 'rating',
        required: true,
        helpText:
          'Rate overall process effectiveness from 1 (ineffective) to 5 (highly effective).',
        width: 'half',
      },
      {
        id: 'improvementOpportunities',
        label: 'Improvement Opportunities',
        type: 'textarea',
        placeholder: 'Identify opportunities for process improvement...',
        helpText: 'Suggestions for enhancing process efficiency, effectiveness, or capability.',
        width: 'full',
      },
    ],
  },

  // ─── TPL-QMS-008  QMS Management Review ───────────────────────────────
  {
    code: 'TPL-QMS-008',
    name: 'QMS Management Review',
    description:
      'Management review meeting record covering all required inputs and outputs per ISO 9001:2015 clause 9.3. Ensures top management reviews the QMS at planned intervals.',
    module: 'QUALITY',
    category: 'MANAGEMENT_REVIEW',
    tags: ['management-review', 'iso-9001', 'continual-improvement', 'qms'],
    isoClause: '9.3',
    fields: [
      {
        id: 'review-header',
        label: 'Meeting Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'reviewDate',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'textarea',
        required: true,
        placeholder: 'List all attendees with their titles/roles...',
        helpText: 'Top management and other key personnel present.',
        width: 'full',
      },
      {
        id: 'input-audit-section',
        label: 'Input: Audit Results',
        type: 'section',
        width: 'full',
      },
      {
        id: 'auditResults',
        label: 'Audit Results Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Summarize internal and external audit results since last review...',
        helpText: 'Status of internal/external audits, NCRs raised, and CAPA effectiveness.',
        width: 'full',
      },
      {
        id: 'input-customer-section',
        label: 'Input: Customer Feedback',
        type: 'section',
        width: 'full',
      },
      {
        id: 'customerFeedback',
        label: 'Customer Feedback & Satisfaction',
        type: 'textarea',
        required: true,
        placeholder: 'Customer satisfaction scores, complaints, returns, positive feedback...',
        helpText: 'Analysis of customer satisfaction data and trends.',
        width: 'full',
      },
      {
        id: 'input-process-section',
        label: 'Input: Process Performance',
        type: 'section',
        width: 'full',
      },
      {
        id: 'processPerformance',
        label: 'Process Performance & Product Conformity',
        type: 'textarea',
        required: true,
        placeholder: 'KPI results, yield rates, defect rates, on-time delivery...',
        helpText: 'Review of key process performance indicators and product conformity data.',
        width: 'full',
      },
      {
        id: 'input-ncr-section',
        label: 'Input: Non-Conformance Trends',
        type: 'section',
        width: 'full',
      },
      {
        id: 'ncrTrends',
        label: 'NCR Trends & Analysis',
        type: 'textarea',
        required: true,
        placeholder: 'NCR statistics, Pareto analysis, recurring issues...',
        helpText: 'Trends in non-conformances including repeat NCRs and systemic issues.',
        width: 'full',
      },
      {
        id: 'input-capa-section',
        label: 'Input: CAPA Status',
        type: 'section',
        width: 'full',
      },
      {
        id: 'capaStatus',
        label: 'CAPA Status Review',
        type: 'textarea',
        required: true,
        placeholder: 'Open CAPAs, overdue actions, effectiveness verification results...',
        helpText: 'Status of all open corrective and preventive actions.',
        width: 'full',
      },
      {
        id: 'output-section',
        label: 'Management Review Outputs',
        type: 'section',
        width: 'full',
      },
      {
        id: 'improvementDecisions',
        label: 'Improvement Decisions',
        type: 'table',
        required: true,
        helpText: 'Decisions and actions for QMS improvement.',
        columns: [
          { id: 'decisionNumber', label: '#', type: 'number', width: 'third' },
          {
            id: 'decisionDescription',
            label: 'Decision / Action',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          { id: 'decisionOwner', label: 'Owner', type: 'text', required: true, width: 'half' },
          {
            id: 'decisionDeadline',
            label: 'Deadline',
            type: 'date',
            required: true,
            width: 'half',
          },
        ],
        width: 'full',
      },
      {
        id: 'resourceNeeds',
        label: 'Resource Needs',
        type: 'textarea',
        placeholder: 'Identify resource requirements (personnel, equipment, training, budget)...',
        helpText: 'Resources needed to support QMS improvements and objectives.',
        width: 'full',
      },
      {
        id: 'objectivesUpdate',
        label: 'Quality Objectives Update',
        type: 'textarea',
        placeholder: 'Review and update quality objectives as needed...',
        helpText: 'Status of current objectives and any changes or new objectives.',
        width: 'full',
      },
      {
        id: 'nextReview',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        helpText: 'Scheduled date for the next management review.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-009  Design Review Record ────────────────────────────────
  {
    code: 'TPL-QMS-009',
    name: 'Design Review Record',
    description:
      'Design and development review record for systematic evaluation of design outputs against requirements at each design phase per ISO 9001:2015 clause 8.3.4.',
    module: 'QUALITY',
    category: 'DESIGN_DEVELOPMENT',
    tags: ['design-review', 'design-development', 'verification', 'validation', 'iso-9001'],
    isoClause: '8.3.4',
    fields: [
      {
        id: 'design-header',
        label: 'Design Review Information',
        type: 'section',
        width: 'full',
      },
      {
        id: 'project',
        label: 'Project / Product Name',
        type: 'text',
        required: true,
        placeholder: 'Project or product name',
        width: 'half',
      },
      {
        id: 'designPhase',
        label: 'Design Phase',
        type: 'select',
        required: true,
        helpText: 'Current phase of the design and development process.',
        options: [
          { label: 'Concept Review', value: 'concept' },
          { label: 'Preliminary Design Review', value: 'preliminary' },
          { label: 'Detailed Design Review', value: 'detailed' },
          { label: 'Design Validation Review', value: 'validation' },
        ],
        width: 'half',
      },
      {
        id: 'reviewDate',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'reviewers',
        label: 'Review Participants',
        type: 'table',
        required: true,
        helpText: 'List all review participants and their functions.',
        columns: [
          { id: 'reviewerName', label: 'Name', type: 'text', required: true, width: 'half' },
          {
            id: 'reviewerRole',
            label: 'Role / Function',
            type: 'text',
            required: true,
            width: 'half',
          },
          { id: 'reviewerDept', label: 'Department', type: 'text', width: 'half' },
        ],
        width: 'full',
      },
      {
        id: 'inputs-section',
        label: 'Design Inputs Review',
        type: 'section',
        width: 'full',
      },
      {
        id: 'designInputsChecklist',
        label: 'Design Inputs Checklist',
        type: 'table',
        required: true,
        helpText: 'Verify all required design inputs have been defined.',
        columns: [
          { id: 'inputItem', label: 'Input Item', type: 'text', required: true, width: 'half' },
          { id: 'inputDefined', label: 'Defined?', type: 'checkbox', width: 'third' },
          { id: 'inputAdequate', label: 'Adequate?', type: 'checkbox', width: 'third' },
          { id: 'inputNotes', label: 'Notes', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'outputs-section',
        label: 'Design Outputs Review',
        type: 'section',
        width: 'full',
      },
      {
        id: 'designOutputsChecklist',
        label: 'Design Outputs Checklist',
        type: 'table',
        required: true,
        helpText: 'Verify design outputs meet input requirements.',
        columns: [
          { id: 'outputItem', label: 'Output Item', type: 'text', required: true, width: 'half' },
          { id: 'outputComplete', label: 'Complete?', type: 'checkbox', width: 'third' },
          { id: 'outputMeetsReq', label: 'Meets Requirements?', type: 'checkbox', width: 'third' },
          { id: 'outputNotes', label: 'Notes', type: 'textarea', width: 'full' },
        ],
        width: 'full',
      },
      {
        id: 'issues-section',
        label: 'Issues & Actions',
        type: 'section',
        width: 'full',
      },
      {
        id: 'issues',
        label: 'Issues Identified',
        type: 'table',
        helpText: 'Document any issues, concerns, or risks identified during the review.',
        columns: [
          { id: 'issueRef', label: 'Issue #', type: 'text', required: true, width: 'third' },
          {
            id: 'issueDescription',
            label: 'Description',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          {
            id: 'issueSeverity',
            label: 'Severity',
            type: 'select',
            options: [
              { label: 'Low', value: 'low' },
              { label: 'Medium', value: 'medium' },
              { label: 'High', value: 'high' },
              { label: 'Critical', value: 'critical' },
            ],
            required: true,
            width: 'third',
          },
        ],
        width: 'full',
      },
      {
        id: 'actionItems',
        label: 'Action Items',
        type: 'table',
        helpText: 'Actions required to resolve issues and progress the design.',
        columns: [
          { id: 'actionRef', label: 'Action #', type: 'text', required: true, width: 'third' },
          {
            id: 'actionDescription',
            label: 'Action',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          { id: 'actionOwner', label: 'Owner', type: 'text', required: true, width: 'half' },
          { id: 'actionDueDate', label: 'Due Date', type: 'date', required: true, width: 'half' },
        ],
        width: 'full',
      },
      {
        id: 'decision',
        label: 'Review Decision',
        type: 'select',
        required: true,
        helpText: 'Outcome decision of this design review gate.',
        options: [
          { label: 'Approved - Proceed to Next Phase', value: 'approved' },
          { label: 'Approved with Conditions', value: 'approved_conditional' },
          { label: 'Not Approved - Rework Required', value: 'not_approved' },
          { label: 'Deferred - Additional Information Needed', value: 'deferred' },
        ],
        width: 'half',
      },
      {
        id: 'approvalSignature',
        label: 'Approval Signature',
        type: 'signature',
        required: true,
        helpText: 'Design authority approval.',
        width: 'half',
      },
    ],
  },

  // ─── TPL-QMS-010  FMEA Worksheet ──────────────────────────────────────
  {
    code: 'TPL-QMS-010',
    name: 'FMEA Worksheet',
    description:
      'Failure Mode and Effects Analysis worksheet for systematically identifying potential failures, assessing risk, and prioritizing corrective actions. Supports both Design and Process FMEA.',
    module: 'QUALITY',
    category: 'RISK_ASSESSMENT',
    tags: ['fmea', 'failure-mode', 'risk', 'rpn', 'design', 'process'],
    isoClause: '6.1',
    fields: [
      {
        id: 'fmea-header',
        label: 'FMEA Header',
        type: 'section',
        width: 'full',
      },
      {
        id: 'fmeaNumber',
        label: 'FMEA Number',
        type: 'text',
        required: true,
        placeholder: 'FMEA-2026-001',
        helpText: 'Unique FMEA document number.',
        width: 'third',
      },
      {
        id: 'fmeaType',
        label: 'FMEA Type',
        type: 'select',
        required: true,
        helpText: 'Whether this is a Design FMEA or Process FMEA.',
        options: [
          { label: 'Design FMEA (DFMEA)', value: 'design' },
          { label: 'Process FMEA (PFMEA)', value: 'process' },
        ],
        width: 'third',
      },
      {
        id: 'itemProcess',
        label: 'Item / Process Name',
        type: 'text',
        required: true,
        placeholder: 'Name of the item, subsystem, or process being analyzed',
        helpText: 'Identify the specific design element or process step being analyzed.',
        width: 'third',
      },
      {
        id: 'team',
        label: 'FMEA Team',
        type: 'textarea',
        required: true,
        placeholder: 'List team members and their roles/expertise...',
        helpText: 'Cross-functional team responsible for performing the analysis.',
        width: 'half',
      },
      {
        id: 'fmeaDate',
        label: 'Date',
        type: 'date',
        required: true,
        width: 'half',
      },
      {
        id: 'analysis-section',
        label: 'Failure Mode Analysis',
        type: 'section',
        width: 'full',
      },
      {
        id: 'fmeaAnalysis',
        label: 'FMEA Analysis Table',
        type: 'table',
        required: true,
        helpText:
          'Systematically analyze each function/process step for potential failure modes. RPN = Severity x Occurrence x Detection.',
        columns: [
          {
            id: 'function',
            label: 'Function / Process Step',
            type: 'text',
            required: true,
            width: 'full',
          },
          {
            id: 'failureMode',
            label: 'Potential Failure Mode',
            type: 'text',
            required: true,
            width: 'full',
          },
          {
            id: 'effect',
            label: 'Potential Effect(s) of Failure',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          {
            id: 'severity',
            label: 'Severity (1-10)',
            type: 'number',
            required: true,
            validation: { min: 1, max: 10 },
            helpText: '1=No effect, 10=Hazardous without warning',
            width: 'third',
          },
          {
            id: 'cause',
            label: 'Potential Cause(s)',
            type: 'textarea',
            required: true,
            width: 'full',
          },
          {
            id: 'occurrence',
            label: 'Occurrence (1-10)',
            type: 'number',
            required: true,
            validation: { min: 1, max: 10 },
            helpText: '1=Remote, 10=Very high (inevitable)',
            width: 'third',
          },
          {
            id: 'controls',
            label: 'Current Controls',
            type: 'textarea',
            width: 'full',
          },
          {
            id: 'detection',
            label: 'Detection (1-10)',
            type: 'number',
            required: true,
            validation: { min: 1, max: 10 },
            helpText: '1=Almost certain detection, 10=No detection',
            width: 'third',
          },
          {
            id: 'rpn',
            label: 'RPN',
            type: 'number',
            helpText: 'Risk Priority Number = S x O x D. Auto-calculated.',
            width: 'third',
          },
          {
            id: 'recommendedActions',
            label: 'Recommended Actions',
            type: 'textarea',
            width: 'full',
          },
          {
            id: 'responsible',
            label: 'Responsible',
            type: 'text',
            width: 'half',
          },
          {
            id: 'targetDate',
            label: 'Target Date',
            type: 'date',
            width: 'half',
          },
        ],
        width: 'full',
      },
    ],
  },
];
