// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// This file is part of the Nexara IMS Platform. CONFIDENTIAL — TRADE SECRET.
// Unauthorised copying, modification, or distribution is strictly prohibited.
import type { TemplateDefinition } from '../types';

export const riskTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-RISK-001',
    name: 'Enterprise Risk Register',
    description:
      'Comprehensive enterprise risk register for identifying, assessing, and tracking organisational risks with likelihood/impact scoring, risk owners, and treatment plans. Aligned with ISO 31000.',
    module: 'RISK',
    category: 'RISK_ASSESSMENT',
    tags: ['enterprise-risk', 'risk-register', 'iso-31000', 'risk-matrix'],
    isoClause: '6.1',
    fields: [
      { id: 'section_header', label: 'Register Details', type: 'section' },
      {
        id: 'register_title',
        label: 'Register Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Register Details',
      },
      {
        id: 'prepared_by',
        label: 'Prepared By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Register Details',
      },
      {
        id: 'review_date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Register Details',
      },
      {
        id: 'scope',
        label: 'Scope / Business Unit',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Register Details',
      },
      { id: 'section_risks', label: 'Risk Entries', type: 'section' },
      {
        id: 'risks',
        label: 'Risk Register',
        type: 'table',
        required: true,
        columns: [
          { id: 'risk_id', label: 'Risk ID', type: 'text', required: true },
          {
            id: 'risk_category',
            label: 'Category',
            type: 'select',
            required: true,
            options: [
              { label: 'Strategic', value: 'strategic' },
              { label: 'Operational', value: 'operational' },
              { label: 'Financial', value: 'financial' },
              { label: 'Compliance', value: 'compliance' },
              { label: 'Reputational', value: 'reputational' },
              { label: 'Technology', value: 'technology' },
            ],
          },
          { id: 'description', label: 'Risk Description', type: 'text', required: true },
          { id: 'cause', label: 'Root Cause', type: 'text', required: true },
          { id: 'consequence', label: 'Consequence', type: 'text', required: true },
          {
            id: 'likelihood',
            label: 'Likelihood (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'impact',
            label: 'Impact (1-5)',
            type: 'rating',
            required: true,
            validation: { min: 1, max: 5 },
          },
          {
            id: 'inherent_score',
            label: 'Inherent Risk Score',
            type: 'number',
            helpText: 'Likelihood × Impact',
          },
          { id: 'controls', label: 'Existing Controls', type: 'text' },
          {
            id: 'residual_likelihood',
            label: 'Residual Likelihood',
            type: 'rating',
            validation: { min: 1, max: 5 },
          },
          {
            id: 'residual_impact',
            label: 'Residual Impact',
            type: 'rating',
            validation: { min: 1, max: 5 },
          },
          {
            id: 'treatment',
            label: 'Treatment',
            type: 'select',
            required: true,
            options: [
              { label: 'Mitigate', value: 'mitigate' },
              { label: 'Accept', value: 'accept' },
              { label: 'Transfer', value: 'transfer' },
              { label: 'Avoid', value: 'avoid' },
            ],
          },
          { id: 'owner', label: 'Risk Owner', type: 'text', required: true },
          { id: 'target_date', label: 'Target Date', type: 'date' },
          {
            id: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { label: 'Open', value: 'open' },
              { label: 'In Treatment', value: 'in_treatment' },
              { label: 'Closed', value: 'closed' },
              { label: 'Accepted', value: 'accepted' },
            ],
          },
        ],
        section: 'Risk Entries',
      },
      { id: 'section_approval', label: 'Approval', type: 'section' },
      {
        id: 'reviewer_comments',
        label: 'Review Comments',
        type: 'textarea',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Approval',
      },
      {
        id: 'approved_by',
        label: 'Approved By',
        type: 'signature',
        required: true,
        section: 'Approval',
      },
    ],
  },
  {
    code: 'TPL-RISK-002',
    name: 'Risk Assessment Form',
    description:
      'Individual risk assessment form for detailed analysis of a specific risk event, including bow-tie analysis, controls assessment, and action plan.',
    module: 'RISK',
    category: 'RISK_ASSESSMENT',
    tags: ['risk-assessment', 'bow-tie', 'controls', 'action-plan'],
    isoClause: '6.1.2',
    fields: [
      { id: 'section_info', label: 'Assessment Information', type: 'section' },
      {
        id: 'assessment_ref',
        label: 'Assessment Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. RA-2026-001',
        width: 'half',
        section: 'Assessment Information',
      },
      {
        id: 'date',
        label: 'Assessment Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Assessment Information',
      },
      {
        id: 'assessor',
        label: 'Assessor Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Information',
      },
      {
        id: 'department',
        label: 'Department / Area',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Assessment Information',
      },
      {
        id: 'risk_title',
        label: 'Risk Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Assessment Information',
      },
      {
        id: 'risk_description',
        label: 'Risk Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the risk event in detail...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Assessment Information',
      },
      { id: 'section_analysis', label: 'Risk Analysis', type: 'section' },
      {
        id: 'causes',
        label: 'Causes / Threats',
        type: 'textarea',
        required: true,
        placeholder: 'List all potential causes leading to this risk...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Risk Analysis',
      },
      {
        id: 'consequences',
        label: 'Consequences / Impacts',
        type: 'textarea',
        required: true,
        placeholder: 'List all potential consequences if the risk materialises...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Risk Analysis',
      },
      {
        id: 'likelihood',
        label: 'Likelihood',
        type: 'select',
        required: true,
        options: [
          { label: '1 — Rare', value: '1' },
          { label: '2 — Unlikely', value: '2' },
          { label: '3 — Possible', value: '3' },
          { label: '4 — Likely', value: '4' },
          { label: '5 — Almost Certain', value: '5' },
        ],
        width: 'half',
        section: 'Risk Analysis',
      },
      {
        id: 'impact',
        label: 'Impact',
        type: 'select',
        required: true,
        options: [
          { label: '1 — Insignificant', value: '1' },
          { label: '2 — Minor', value: '2' },
          { label: '3 — Moderate', value: '3' },
          { label: '4 — Major', value: '4' },
          { label: '5 — Catastrophic', value: '5' },
        ],
        width: 'half',
        section: 'Risk Analysis',
      },
      { id: 'section_controls', label: 'Controls & Treatment', type: 'section' },
      {
        id: 'existing_controls',
        label: 'Existing Controls',
        type: 'textarea',
        required: true,
        placeholder: 'List current controls in place...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Controls & Treatment',
      },
      {
        id: 'control_effectiveness',
        label: 'Control Effectiveness',
        type: 'select',
        required: true,
        options: [
          { label: 'Effective', value: 'effective' },
          { label: 'Partially Effective', value: 'partial' },
          { label: 'Ineffective', value: 'ineffective' },
        ],
        width: 'half',
        section: 'Controls & Treatment',
      },
      {
        id: 'treatment_plan',
        label: 'Treatment Plan',
        type: 'textarea',
        required: true,
        placeholder: 'Describe additional controls or actions to reduce risk...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Controls & Treatment',
      },
      {
        id: 'treatment_owner',
        label: 'Treatment Owner',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Controls & Treatment',
      },
      {
        id: 'target_date',
        label: 'Target Completion Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Controls & Treatment',
      },
      {
        id: 'assessor_signature',
        label: 'Assessor Signature',
        type: 'signature',
        required: true,
        section: 'Controls & Treatment',
      },
    ],
  },
  {
    code: 'TPL-RISK-003',
    name: 'Risk Review Meeting Minutes',
    description:
      'Structured minutes template for periodic risk review meetings, capturing risk status updates, new/emerging risks, escalations, and agreed actions.',
    module: 'RISK',
    category: 'MANAGEMENT_REVIEW',
    tags: ['risk-review', 'meeting-minutes', 'governance', 'escalation'],
    isoClause: '9.3',
    fields: [
      { id: 'section_meeting', label: 'Meeting Details', type: 'section' },
      {
        id: 'meeting_date',
        label: 'Meeting Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Meeting Details',
      },
      {
        id: 'chair',
        label: 'Chair',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Meeting Details',
      },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'textarea',
        required: true,
        placeholder: 'Name, Role — one per line',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Meeting Details',
      },
      { id: 'section_review', label: 'Risk Review', type: 'section' },
      {
        id: 'risk_updates',
        label: 'Risk Status Updates',
        type: 'table',
        required: true,
        columns: [
          { id: 'risk_id', label: 'Risk ID', type: 'text', required: true },
          { id: 'risk_title', label: 'Risk Title', type: 'text', required: true },
          {
            id: 'current_rating',
            label: 'Current Rating',
            type: 'select',
            options: [
              { label: 'Critical', value: 'critical' },
              { label: 'High', value: 'high' },
              { label: 'Medium', value: 'medium' },
              { label: 'Low', value: 'low' },
            ],
          },
          {
            id: 'trend',
            label: 'Trend',
            type: 'select',
            options: [
              { label: 'Increasing', value: 'increasing' },
              { label: 'Stable', value: 'stable' },
              { label: 'Decreasing', value: 'decreasing' },
            ],
          },
          { id: 'update', label: 'Status Update', type: 'text', required: true },
          { id: 'action_required', label: 'Action Required', type: 'text' },
        ],
        section: 'Risk Review',
      },
      {
        id: 'new_risks',
        label: 'New / Emerging Risks Identified',
        type: 'textarea',
        placeholder: 'Describe any new or emerging risks discussed...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Risk Review',
      },
      {
        id: 'escalations',
        label: 'Escalations',
        type: 'textarea',
        placeholder: 'Risks escalated to senior management / board...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Risk Review',
      },
      { id: 'section_actions', label: 'Actions & Decisions', type: 'section' },
      {
        id: 'actions',
        label: 'Agreed Actions',
        type: 'table',
        columns: [
          { id: 'action', label: 'Action', type: 'text', required: true },
          { id: 'owner', label: 'Owner', type: 'text', required: true },
          { id: 'due_date', label: 'Due Date', type: 'date', required: true },
        ],
        section: 'Actions & Decisions',
      },
      {
        id: 'next_review',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Actions & Decisions',
      },
      {
        id: 'chair_signature',
        label: 'Chair Signature',
        type: 'signature',
        required: true,
        section: 'Actions & Decisions',
      },
    ],
  },
  {
    code: 'TPL-RISK-004',
    name: 'Opportunity Assessment',
    description:
      'Template for identifying and evaluating positive risks (opportunities), including benefit analysis and exploitation strategies per ISO 31000 / clause 6.1.',
    module: 'RISK',
    category: 'PLANNING',
    tags: ['opportunity', 'positive-risk', 'benefit-analysis', 'iso-31000'],
    isoClause: '6.1',
    fields: [
      { id: 'section_info', label: 'Opportunity Details', type: 'section' },
      {
        id: 'opp_ref',
        label: 'Opportunity Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. OPP-2026-001',
        width: 'half',
        section: 'Opportunity Details',
      },
      {
        id: 'date',
        label: 'Date Identified',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Opportunity Details',
      },
      {
        id: 'identified_by',
        label: 'Identified By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Opportunity Details',
      },
      {
        id: 'department',
        label: 'Department',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Opportunity Details',
      },
      {
        id: 'title',
        label: 'Opportunity Title',
        type: 'text',
        required: true,
        width: 'full',
        section: 'Opportunity Details',
      },
      {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the opportunity in detail...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'Opportunity Details',
      },
      { id: 'section_analysis', label: 'Analysis', type: 'section' },
      {
        id: 'potential_benefits',
        label: 'Potential Benefits',
        type: 'textarea',
        required: true,
        placeholder: 'Quantify benefits where possible (cost savings, revenue, efficiency)...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Analysis',
      },
      {
        id: 'probability',
        label: 'Probability of Realisation',
        type: 'select',
        required: true,
        options: [
          { label: 'High', value: 'high' },
          { label: 'Medium', value: 'medium' },
          { label: 'Low', value: 'low' },
        ],
        width: 'half',
        section: 'Analysis',
      },
      {
        id: 'impact_level',
        label: 'Benefit Impact',
        type: 'select',
        required: true,
        options: [
          { label: 'Major', value: 'major' },
          { label: 'Moderate', value: 'moderate' },
          { label: 'Minor', value: 'minor' },
        ],
        width: 'half',
        section: 'Analysis',
      },
      {
        id: 'resources_needed',
        label: 'Resources Required',
        type: 'textarea',
        placeholder: 'Budget, people, time, technology needed...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Analysis',
      },
      {
        id: 'strategy',
        label: 'Exploitation Strategy',
        type: 'select',
        required: true,
        options: [
          { label: 'Exploit', value: 'exploit' },
          { label: 'Share', value: 'share' },
          { label: 'Enhance', value: 'enhance' },
          { label: 'Accept', value: 'accept' },
        ],
        width: 'half',
        section: 'Analysis',
      },
      {
        id: 'action_plan',
        label: 'Action Plan',
        type: 'textarea',
        required: true,
        placeholder: 'Steps to pursue this opportunity...',
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Analysis',
      },
      {
        id: 'owner',
        label: 'Opportunity Owner',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Analysis',
      },
      {
        id: 'target_date',
        label: 'Target Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Analysis',
      },
      {
        id: 'approver_signature',
        label: 'Approver Signature',
        type: 'signature',
        required: true,
        section: 'Analysis',
      },
    ],
  },
];
