import type { TemplateDefinition } from '../types';

export const suppliersTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-SUP-001',
    name: 'Supplier Evaluation Form',
    description:
      'Comprehensive supplier evaluation form for assessing new and existing suppliers against quality, delivery, cost, and compliance criteria. Aligned with ISO 9001 clause 8.4.',
    module: 'SUPPLIERS',
    category: 'SUPPLIER',
    tags: ['supplier-evaluation', 'vendor-assessment', 'qualification', 'iso-9001'],
    isoClause: '8.4.1',
    fields: [
      { id: 'section_supplier', label: 'Supplier Information', type: 'section' },
      {
        id: 'supplier_name',
        label: 'Supplier Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'supplier_ref',
        label: 'Supplier Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. SUP-001',
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'contact_name',
        label: 'Primary Contact',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'contact_email',
        label: 'Contact Email',
        type: 'email',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'products_services',
        label: 'Products / Services Supplied',
        type: 'textarea',
        required: true,
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Supplier Information',
      },
      {
        id: 'evaluation_date',
        label: 'Evaluation Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      {
        id: 'evaluator',
        label: 'Evaluator',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Supplier Information',
      },
      { id: 'section_criteria', label: 'Evaluation Criteria', type: 'section' },
      {
        id: 'quality_score',
        label: 'Quality (1-5)',
        type: 'rating',
        required: true,
        helpText: 'Product/service quality consistency',
        section: 'Evaluation Criteria',
      },
      {
        id: 'delivery_score',
        label: 'Delivery (1-5)',
        type: 'rating',
        required: true,
        helpText: 'On-time delivery performance',
        section: 'Evaluation Criteria',
      },
      {
        id: 'cost_score',
        label: 'Cost Competitiveness (1-5)',
        type: 'rating',
        required: true,
        helpText: 'Value for money and pricing',
        section: 'Evaluation Criteria',
      },
      {
        id: 'responsiveness_score',
        label: 'Responsiveness (1-5)',
        type: 'rating',
        required: true,
        helpText: 'Communication and issue resolution',
        section: 'Evaluation Criteria',
      },
      {
        id: 'compliance_score',
        label: 'Compliance (1-5)',
        type: 'rating',
        required: true,
        helpText: 'Regulatory and contractual compliance',
        section: 'Evaluation Criteria',
      },
      {
        id: 'certifications',
        label: 'Certifications Held',
        type: 'multiselect',
        options: [
          { label: 'ISO 9001', value: 'iso9001' },
          { label: 'ISO 14001', value: 'iso14001' },
          { label: 'ISO 45001', value: 'iso45001' },
          { label: 'ISO 27001', value: 'iso27001' },
          { label: 'IATF 16949', value: 'iatf16949' },
          { label: 'AS9100', value: 'as9100' },
          { label: 'ISO 13485', value: 'iso13485' },
          { label: 'None', value: 'none' },
        ],
        width: 'full',
        section: 'Evaluation Criteria',
      },
      { id: 'section_decision', label: 'Decision', type: 'section' },
      {
        id: 'overall_rating',
        label: 'Overall Rating',
        type: 'select',
        required: true,
        options: [
          { label: 'Approved — Preferred', value: 'preferred' },
          { label: 'Approved', value: 'approved' },
          { label: 'Conditionally Approved', value: 'conditional' },
          { label: 'Not Approved', value: 'not_approved' },
        ],
        width: 'half',
        section: 'Decision',
      },
      {
        id: 'conditions',
        label: 'Conditions / Improvement Actions',
        type: 'textarea',
        placeholder: 'Any conditions for approval or required improvements...',
        validation: { maxLength: 2000 },
        width: 'full',
        section: 'Decision',
      },
      {
        id: 'next_review',
        label: 'Next Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Decision',
      },
      {
        id: 'approver_signature',
        label: 'Approver Signature',
        type: 'signature',
        required: true,
        section: 'Decision',
      },
    ],
  },
  {
    code: 'TPL-SUP-002',
    name: 'Supplier Audit Checklist',
    description:
      'On-site or remote supplier audit checklist covering quality management, production processes, documentation, and corrective actions.',
    module: 'SUPPLIERS',
    category: 'AUDIT',
    tags: ['supplier-audit', 'vendor-audit', 'second-party-audit', 'quality'],
    isoClause: '8.4.2',
    fields: [
      { id: 'section_header', label: 'Audit Details', type: 'section' },
      {
        id: 'supplier_name',
        label: 'Supplier Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'audit_date',
        label: 'Audit Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'auditor',
        label: 'Lead Auditor',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Audit Details',
      },
      {
        id: 'audit_type',
        label: 'Audit Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Initial Qualification', value: 'initial' },
          { label: 'Periodic Review', value: 'periodic' },
          { label: 'For Cause', value: 'for_cause' },
          { label: 'Re-qualification', value: 'requalification' },
        ],
        width: 'half',
        section: 'Audit Details',
      },
      { id: 'section_checklist', label: 'Audit Checklist', type: 'section' },
      {
        id: 'checklist',
        label: 'Audit Items',
        type: 'table',
        required: true,
        columns: [
          {
            id: 'area',
            label: 'Area',
            type: 'select',
            required: true,
            options: [
              { label: 'QMS Documentation', value: 'qms' },
              { label: 'Production Process', value: 'production' },
              { label: 'Inspection & Test', value: 'inspection' },
              { label: 'Purchasing & Suppliers', value: 'purchasing' },
              { label: 'Storage & Handling', value: 'storage' },
              { label: 'Training & Competency', value: 'training' },
              { label: 'CAPA', value: 'capa' },
              { label: 'Calibration', value: 'calibration' },
            ],
          },
          { id: 'question', label: 'Audit Question', type: 'text', required: true },
          {
            id: 'finding',
            label: 'Finding',
            type: 'select',
            required: true,
            options: [
              { label: 'Conforming', value: 'conforming' },
              { label: 'Observation', value: 'observation' },
              { label: 'Minor NC', value: 'minor_nc' },
              { label: 'Major NC', value: 'major_nc' },
              { label: 'N/A', value: 'na' },
            ],
          },
          { id: 'evidence', label: 'Evidence / Notes', type: 'text' },
        ],
        section: 'Audit Checklist',
      },
      { id: 'section_summary', label: 'Audit Summary', type: 'section' },
      {
        id: 'summary',
        label: 'Audit Summary',
        type: 'textarea',
        required: true,
        validation: { minLength: 20, maxLength: 3000 },
        width: 'full',
        section: 'Audit Summary',
      },
      {
        id: 'recommendation',
        label: 'Recommendation',
        type: 'select',
        required: true,
        options: [
          { label: 'Approve', value: 'approve' },
          { label: 'Approve with Conditions', value: 'conditional' },
          { label: 'Re-audit Required', value: 're_audit' },
          { label: 'Reject', value: 'reject' },
        ],
        width: 'half',
        section: 'Audit Summary',
      },
      {
        id: 'auditor_signature',
        label: 'Auditor Signature',
        type: 'signature',
        required: true,
        section: 'Audit Summary',
      },
    ],
  },
  {
    code: 'TPL-SUP-003',
    name: 'Supplier Performance Scorecard',
    description:
      'Quarterly or annual supplier performance scorecard for tracking KPIs, trends, and improvement actions.',
    module: 'SUPPLIERS',
    category: 'REPORTING',
    tags: ['supplier-performance', 'scorecard', 'kpi', 'vendor-management'],
    isoClause: '8.4.1',
    fields: [
      { id: 'section_header', label: 'Scorecard Details', type: 'section' },
      {
        id: 'supplier_name',
        label: 'Supplier Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Scorecard Details',
      },
      {
        id: 'period',
        label: 'Review Period',
        type: 'text',
        required: true,
        placeholder: 'e.g. Q1 2026',
        width: 'half',
        section: 'Scorecard Details',
      },
      {
        id: 'reviewer',
        label: 'Reviewed By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'Scorecard Details',
      },
      {
        id: 'date',
        label: 'Review Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Scorecard Details',
      },
      { id: 'section_kpis', label: 'Performance KPIs', type: 'section' },
      {
        id: 'otd',
        label: 'On-Time Delivery %',
        type: 'number',
        required: true,
        validation: { min: 0, max: 100 },
        width: 'third',
        section: 'Performance KPIs',
      },
      {
        id: 'quality_reject_rate',
        label: 'Quality Reject Rate %',
        type: 'number',
        required: true,
        validation: { min: 0, max: 100 },
        width: 'third',
        section: 'Performance KPIs',
      },
      {
        id: 'responsiveness_days',
        label: 'Avg. Response Time (days)',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'third',
        section: 'Performance KPIs',
      },
      {
        id: 'ncr_count',
        label: 'NCRs Raised',
        type: 'number',
        required: true,
        validation: { min: 0 },
        width: 'third',
        section: 'Performance KPIs',
      },
      {
        id: 'capa_closure_rate',
        label: 'CAPA Closure Rate %',
        type: 'number',
        validation: { min: 0, max: 100 },
        width: 'third',
        section: 'Performance KPIs',
      },
      {
        id: 'overall_score',
        label: 'Overall Score (1-5)',
        type: 'rating',
        required: true,
        section: 'Performance KPIs',
      },
      { id: 'section_actions', label: 'Actions & Decisions', type: 'section' },
      {
        id: 'trend',
        label: 'Performance Trend',
        type: 'select',
        required: true,
        options: [
          { label: 'Improving', value: 'improving' },
          { label: 'Stable', value: 'stable' },
          { label: 'Declining', value: 'declining' },
        ],
        width: 'half',
        section: 'Actions & Decisions',
      },
      {
        id: 'actions',
        label: 'Improvement Actions',
        type: 'textarea',
        placeholder: 'Required improvement actions and follow-up...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Actions & Decisions',
      },
      {
        id: 'status_decision',
        label: 'Status Decision',
        type: 'select',
        required: true,
        options: [
          { label: 'Retain — Preferred', value: 'preferred' },
          { label: 'Retain', value: 'retain' },
          { label: 'Under Review', value: 'under_review' },
          { label: 'Phase Out', value: 'phase_out' },
        ],
        width: 'half',
        section: 'Actions & Decisions',
      },
      {
        id: 'reviewer_signature',
        label: 'Reviewer Signature',
        type: 'signature',
        required: true,
        section: 'Actions & Decisions',
      },
    ],
  },
  {
    code: 'TPL-SUP-004',
    name: 'Supplier Corrective Action Request (SCAR)',
    description:
      'Formal SCAR for requesting corrective action from a supplier following a quality issue, nonconformance, or delivery failure.',
    module: 'SUPPLIERS',
    category: 'CAPA',
    tags: ['scar', 'supplier-corrective-action', 'nonconformance', 'quality'],
    isoClause: '8.4.2',
    fields: [
      { id: 'section_scar', label: 'SCAR Details', type: 'section' },
      {
        id: 'scar_ref',
        label: 'SCAR Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. SCAR-2026-001',
        width: 'half',
        section: 'SCAR Details',
      },
      {
        id: 'date_issued',
        label: 'Date Issued',
        type: 'date',
        required: true,
        width: 'half',
        section: 'SCAR Details',
      },
      {
        id: 'supplier_name',
        label: 'Supplier Name',
        type: 'text',
        required: true,
        width: 'half',
        section: 'SCAR Details',
      },
      {
        id: 'issued_by',
        label: 'Issued By',
        type: 'text',
        required: true,
        width: 'half',
        section: 'SCAR Details',
      },
      {
        id: 'issue_type',
        label: 'Issue Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Quality Defect', value: 'quality' },
          { label: 'Late Delivery', value: 'delivery' },
          { label: 'Documentation Error', value: 'documentation' },
          { label: 'Packaging / Damage', value: 'packaging' },
          { label: 'Specification Non-Compliance', value: 'spec' },
          { label: 'Other', value: 'other' },
        ],
        width: 'half',
        section: 'SCAR Details',
      },
      {
        id: 'ncr_ref',
        label: 'Related NCR / Complaint Ref',
        type: 'text',
        width: 'half',
        section: 'SCAR Details',
      },
      {
        id: 'description',
        label: 'Issue Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the nonconformance or issue in detail...',
        validation: { minLength: 30, maxLength: 3000 },
        width: 'full',
        section: 'SCAR Details',
      },
      { id: 'section_supplier_response', label: 'Supplier Response', type: 'section' },
      {
        id: 'response_due',
        label: 'Response Due Date',
        type: 'date',
        required: true,
        width: 'half',
        section: 'Supplier Response',
      },
      {
        id: 'root_cause',
        label: 'Root Cause (Supplier to Complete)',
        type: 'textarea',
        placeholder: 'Supplier identifies the root cause...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Supplier Response',
      },
      {
        id: 'corrective_action',
        label: 'Corrective Action Plan (Supplier)',
        type: 'textarea',
        placeholder: 'Supplier describes corrective and preventive actions...',
        validation: { maxLength: 3000 },
        width: 'full',
        section: 'Supplier Response',
      },
      {
        id: 'implementation_date',
        label: 'Implementation Date',
        type: 'date',
        width: 'half',
        section: 'Supplier Response',
      },
      { id: 'section_verification', label: 'Verification', type: 'section' },
      {
        id: 'response_accepted',
        label: 'Response Accepted?',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No — Resubmit', value: 'no' },
        ],
        width: 'half',
        section: 'Verification',
      },
      {
        id: 'verified_effective',
        label: 'Action Verified Effective?',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'Pending', value: 'pending' },
        ],
        width: 'half',
        section: 'Verification',
      },
      {
        id: 'verifier_signature',
        label: 'Verifier Signature',
        type: 'signature',
        section: 'Verification',
      },
    ],
  },
];
