import type { TemplateDefinition } from '../types';

export const trainingTemplates: TemplateDefinition[] = [
  {
    code: 'TPL-TRN-001',
    name: 'Training Needs Analysis',
    description:
      'Systematic training needs analysis for identifying competency gaps, prioritising training requirements, and planning development activities. Aligned with ISO clause 7.2.',
    module: 'TRAINING',
    category: 'PLANNING',
    tags: ['training-needs', 'competency-gap', 'skills-assessment', 'development'],
    isoClause: '7.2',
    fields: [
      { id: 'section_header', label: 'Analysis Details', type: 'section' },
      { id: 'department', label: 'Department / Team', type: 'text', required: true, width: 'half', section: 'Analysis Details' },
      { id: 'analysis_date', label: 'Analysis Date', type: 'date', required: true, width: 'half', section: 'Analysis Details' },
      { id: 'conducted_by', label: 'Conducted By', type: 'text', required: true, width: 'half', section: 'Analysis Details' },
      { id: 'review_period', label: 'Review Period', type: 'text', required: true, placeholder: 'e.g. Q1 2026', width: 'half', section: 'Analysis Details' },
      { id: 'section_gaps', label: 'Competency Gaps', type: 'section' },
      {
        id: 'gaps',
        label: 'Identified Gaps',
        type: 'table',
        required: true,
        columns: [
          { id: 'role', label: 'Role / Position', type: 'text', required: true },
          { id: 'competency', label: 'Competency Required', type: 'text', required: true },
          { id: 'current_level', label: 'Current Level', type: 'select', required: true, options: [{ label: 'None', value: 'none' }, { label: 'Basic', value: 'basic' }, { label: 'Intermediate', value: 'intermediate' }, { label: 'Advanced', value: 'advanced' }] },
          { id: 'required_level', label: 'Required Level', type: 'select', required: true, options: [{ label: 'Basic', value: 'basic' }, { label: 'Intermediate', value: 'intermediate' }, { label: 'Advanced', value: 'advanced' }, { label: 'Expert', value: 'expert' }] },
          { id: 'priority', label: 'Priority', type: 'select', required: true, options: [{ label: 'Critical', value: 'critical' }, { label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
          { id: 'training_method', label: 'Training Method', type: 'select', options: [{ label: 'Classroom', value: 'classroom' }, { label: 'E-Learning', value: 'elearning' }, { label: 'On-the-Job', value: 'otj' }, { label: 'External Course', value: 'external' }, { label: 'Mentoring', value: 'mentoring' }] },
          { id: 'target_date', label: 'Target Date', type: 'date' },
        ],
        section: 'Competency Gaps',
      },
      { id: 'section_plan', label: 'Training Plan Summary', type: 'section' },
      { id: 'budget_estimate', label: 'Estimated Budget', type: 'number', placeholder: 'GBP', width: 'half', section: 'Training Plan Summary' },
      { id: 'total_hours', label: 'Estimated Total Hours', type: 'number', width: 'half', section: 'Training Plan Summary' },
      { id: 'recommendations', label: 'Recommendations', type: 'textarea', required: true, validation: { minLength: 20, maxLength: 3000 }, width: 'full', section: 'Training Plan Summary' },
      { id: 'manager_signature', label: 'Manager Approval', type: 'signature', required: true, section: 'Training Plan Summary' },
    ],
  },
  {
    code: 'TPL-TRN-002',
    name: 'Competency Matrix',
    description:
      'Competency matrix for mapping required competencies against team members, tracking skill levels, and identifying development priorities.',
    module: 'TRAINING',
    category: 'COMPLIANCE',
    tags: ['competency-matrix', 'skills-matrix', 'capability', 'team-skills'],
    isoClause: '7.2',
    fields: [
      { id: 'section_header', label: 'Matrix Details', type: 'section' },
      { id: 'department', label: 'Department', type: 'text', required: true, width: 'half', section: 'Matrix Details' },
      { id: 'date', label: 'Date', type: 'date', required: true, width: 'half', section: 'Matrix Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'Matrix Details' },
      { id: 'section_competencies', label: 'Competency Definitions', type: 'section' },
      {
        id: 'competencies',
        label: 'Competencies',
        type: 'table',
        required: true,
        columns: [
          { id: 'comp_id', label: 'Comp. ID', type: 'text', required: true },
          { id: 'competency', label: 'Competency', type: 'text', required: true },
          { id: 'category', label: 'Category', type: 'select', options: [{ label: 'Technical', value: 'technical' }, { label: 'Regulatory', value: 'regulatory' }, { label: 'Safety', value: 'safety' }, { label: 'Management', value: 'management' }, { label: 'Quality', value: 'quality' }] },
          { id: 'standard', label: 'ISO Standard', type: 'text', placeholder: 'e.g. ISO 9001 7.2' },
          { id: 'mandatory', label: 'Mandatory?', type: 'select', options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }] },
        ],
        section: 'Competency Definitions',
      },
      { id: 'section_people', label: 'Team Assessment', type: 'section' },
      {
        id: 'team',
        label: 'Team Members',
        type: 'table',
        required: true,
        columns: [
          { id: 'name', label: 'Name', type: 'text', required: true },
          { id: 'role', label: 'Role', type: 'text', required: true },
          { id: 'comp_levels', label: 'Competency Levels (Comp ID: Level)', type: 'text', required: true, placeholder: 'e.g. C1:3, C2:2, C3:4' },
          { id: 'gaps', label: 'Key Gaps', type: 'text' },
          { id: 'dev_plan', label: 'Development Plan', type: 'text' },
        ],
        section: 'Team Assessment',
      },
      { id: 'summary', label: 'Summary & Next Steps', type: 'textarea', required: true, validation: { maxLength: 3000 }, width: 'full', section: 'Team Assessment' },
    ],
  },
  {
    code: 'TPL-TRN-003',
    name: 'Training Record',
    description:
      'Individual training attendance and evaluation record for documenting training delivery, participant assessment, and effectiveness evaluation.',
    module: 'TRAINING',
    category: 'TRAINING',
    tags: ['training-record', 'attendance', 'evaluation', 'effectiveness'],
    isoClause: '7.2',
    fields: [
      { id: 'section_course', label: 'Course Details', type: 'section' },
      { id: 'course_title', label: 'Course Title', type: 'text', required: true, width: 'full', section: 'Course Details' },
      { id: 'course_code', label: 'Course Code', type: 'text', width: 'half', section: 'Course Details' },
      { id: 'trainer', label: 'Trainer / Provider', type: 'text', required: true, width: 'half', section: 'Course Details' },
      { id: 'date', label: 'Training Date', type: 'date', required: true, width: 'half', section: 'Course Details' },
      { id: 'duration', label: 'Duration (hours)', type: 'number', required: true, validation: { min: 0.5, max: 100 }, width: 'half', section: 'Course Details' },
      { id: 'location', label: 'Location', type: 'text', required: true, width: 'half', section: 'Course Details' },
      { id: 'training_type', label: 'Training Type', type: 'select', required: true, options: [{ label: 'Classroom', value: 'classroom' }, { label: 'E-Learning', value: 'elearning' }, { label: 'On-the-Job', value: 'otj' }, { label: 'Workshop', value: 'workshop' }, { label: 'External Seminar', value: 'external' }], width: 'half', section: 'Course Details' },
      { id: 'objectives', label: 'Learning Objectives', type: 'textarea', required: true, placeholder: 'List the learning objectives for this training...', validation: { maxLength: 2000 }, width: 'full', section: 'Course Details' },
      { id: 'section_attendees', label: 'Attendance', type: 'section' },
      {
        id: 'attendees',
        label: 'Attendees',
        type: 'table',
        required: true,
        columns: [
          { id: 'name', label: 'Name', type: 'text', required: true },
          { id: 'employee_id', label: 'Employee ID', type: 'text' },
          { id: 'department', label: 'Department', type: 'text' },
          { id: 'attended', label: 'Attended?', type: 'select', required: true, options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }, { label: 'Partial', value: 'partial' }] },
          { id: 'assessment', label: 'Assessment Result', type: 'select', options: [{ label: 'Competent', value: 'competent' }, { label: 'Not Yet Competent', value: 'not_yet' }, { label: 'N/A', value: 'na' }] },
        ],
        section: 'Attendance',
      },
      { id: 'section_eval', label: 'Effectiveness Evaluation', type: 'section' },
      { id: 'effectiveness_rating', label: 'Overall Effectiveness', type: 'rating', required: true, section: 'Effectiveness Evaluation' },
      { id: 'feedback', label: 'Feedback / Comments', type: 'textarea', placeholder: 'General feedback on the training effectiveness...', validation: { maxLength: 2000 }, width: 'full', section: 'Effectiveness Evaluation' },
      { id: 'trainer_signature', label: 'Trainer Signature', type: 'signature', required: true, section: 'Effectiveness Evaluation' },
    ],
  },
  {
    code: 'TPL-TRN-004',
    name: 'Training Programme Schedule',
    description:
      'Annual or periodic training programme schedule for planning and tracking all training activities across the organisation.',
    module: 'TRAINING',
    category: 'PLANNING',
    tags: ['training-programme', 'schedule', 'annual-plan', 'calendar'],
    isoClause: '7.2',
    fields: [
      { id: 'section_header', label: 'Programme Details', type: 'section' },
      { id: 'programme_title', label: 'Programme Title', type: 'text', required: true, placeholder: 'e.g. 2026 Annual Training Programme', width: 'full', section: 'Programme Details' },
      { id: 'period', label: 'Period', type: 'text', required: true, placeholder: 'e.g. January — December 2026', width: 'half', section: 'Programme Details' },
      { id: 'prepared_by', label: 'Prepared By', type: 'text', required: true, width: 'half', section: 'Programme Details' },
      { id: 'budget', label: 'Total Budget (GBP)', type: 'number', width: 'half', section: 'Programme Details' },
      { id: 'section_schedule', label: 'Training Schedule', type: 'section' },
      {
        id: 'schedule',
        label: 'Scheduled Training',
        type: 'table',
        required: true,
        columns: [
          { id: 'course', label: 'Course / Topic', type: 'text', required: true },
          { id: 'target_audience', label: 'Target Audience', type: 'text', required: true },
          { id: 'type', label: 'Type', type: 'select', options: [{ label: 'Mandatory', value: 'mandatory' }, { label: 'Recommended', value: 'recommended' }, { label: 'Optional', value: 'optional' }] },
          { id: 'frequency', label: 'Frequency', type: 'select', options: [{ label: 'One-off', value: 'oneoff' }, { label: 'Annual', value: 'annual' }, { label: 'Biannual', value: 'biannual' }, { label: 'Quarterly', value: 'quarterly' }, { label: 'Monthly', value: 'monthly' }] },
          { id: 'planned_date', label: 'Planned Date', type: 'date', required: true },
          { id: 'provider', label: 'Provider', type: 'text' },
          { id: 'est_cost', label: 'Est. Cost (GBP)', type: 'number' },
          { id: 'status', label: 'Status', type: 'select', options: [{ label: 'Planned', value: 'planned' }, { label: 'Confirmed', value: 'confirmed' }, { label: 'Completed', value: 'completed' }, { label: 'Cancelled', value: 'cancelled' }, { label: 'Deferred', value: 'deferred' }] },
        ],
        section: 'Training Schedule',
      },
      { id: 'notes', label: 'Notes', type: 'textarea', validation: { maxLength: 2000 }, width: 'full', section: 'Training Schedule' },
      { id: 'approved_by', label: 'Approved By', type: 'signature', required: true, section: 'Training Schedule' },
    ],
  },
];
