// Copyright (c) 2026 Nexara DMCC. All rights reserved.

import { interval, length, isEmpty, contains, containsInterval, overlaps, intersect,
  union, clamp, expand, shift, scale, normalise, denormalise, compare, merge, subtract, midpoint, equal } from '../interval-utils';
describe('interval-utils', () => {
  describe('length/isEmpty', () => {
    it('length 0', () => { expect(length(interval(0,10))).toBe(10); });
    it('length 1', () => { expect(length(interval(1,11))).toBe(10); });
    it('length 2', () => { expect(length(interval(2,12))).toBe(10); });
    it('length 3', () => { expect(length(interval(3,13))).toBe(10); });
    it('length 4', () => { expect(length(interval(4,14))).toBe(10); });
    it('length 5', () => { expect(length(interval(5,15))).toBe(10); });
    it('length 6', () => { expect(length(interval(6,16))).toBe(10); });
    it('length 7', () => { expect(length(interval(7,17))).toBe(10); });
    it('length 8', () => { expect(length(interval(8,18))).toBe(10); });
    it('length 9', () => { expect(length(interval(9,19))).toBe(10); });
    it('length 10', () => { expect(length(interval(10,20))).toBe(10); });
    it('length 11', () => { expect(length(interval(11,21))).toBe(10); });
    it('length 12', () => { expect(length(interval(12,22))).toBe(10); });
    it('length 13', () => { expect(length(interval(13,23))).toBe(10); });
    it('length 14', () => { expect(length(interval(14,24))).toBe(10); });
    it('length 15', () => { expect(length(interval(15,25))).toBe(10); });
    it('length 16', () => { expect(length(interval(16,26))).toBe(10); });
    it('length 17', () => { expect(length(interval(17,27))).toBe(10); });
    it('length 18', () => { expect(length(interval(18,28))).toBe(10); });
    it('length 19', () => { expect(length(interval(19,29))).toBe(10); });
    it('length 20', () => { expect(length(interval(20,30))).toBe(10); });
    it('length 21', () => { expect(length(interval(21,31))).toBe(10); });
    it('length 22', () => { expect(length(interval(22,32))).toBe(10); });
    it('length 23', () => { expect(length(interval(23,33))).toBe(10); });
    it('length 24', () => { expect(length(interval(24,34))).toBe(10); });
    it('length 25', () => { expect(length(interval(25,35))).toBe(10); });
    it('length 26', () => { expect(length(interval(26,36))).toBe(10); });
    it('length 27', () => { expect(length(interval(27,37))).toBe(10); });
    it('length 28', () => { expect(length(interval(28,38))).toBe(10); });
    it('length 29', () => { expect(length(interval(29,39))).toBe(10); });
    it('length 30', () => { expect(length(interval(30,40))).toBe(10); });
    it('length 31', () => { expect(length(interval(31,41))).toBe(10); });
    it('length 32', () => { expect(length(interval(32,42))).toBe(10); });
    it('length 33', () => { expect(length(interval(33,43))).toBe(10); });
    it('length 34', () => { expect(length(interval(34,44))).toBe(10); });
    it('length 35', () => { expect(length(interval(35,45))).toBe(10); });
    it('length 36', () => { expect(length(interval(36,46))).toBe(10); });
    it('length 37', () => { expect(length(interval(37,47))).toBe(10); });
    it('length 38', () => { expect(length(interval(38,48))).toBe(10); });
    it('length 39', () => { expect(length(interval(39,49))).toBe(10); });
    it('length 40', () => { expect(length(interval(40,50))).toBe(10); });
    it('length 41', () => { expect(length(interval(41,51))).toBe(10); });
    it('length 42', () => { expect(length(interval(42,52))).toBe(10); });
    it('length 43', () => { expect(length(interval(43,53))).toBe(10); });
    it('length 44', () => { expect(length(interval(44,54))).toBe(10); });
    it('length 45', () => { expect(length(interval(45,55))).toBe(10); });
    it('length 46', () => { expect(length(interval(46,56))).toBe(10); });
    it('length 47', () => { expect(length(interval(47,57))).toBe(10); });
    it('length 48', () => { expect(length(interval(48,58))).toBe(10); });
    it('length 49', () => { expect(length(interval(49,59))).toBe(10); });
    it('length 50', () => { expect(length(interval(50,60))).toBe(10); });
    it('length 51', () => { expect(length(interval(51,61))).toBe(10); });
    it('length 52', () => { expect(length(interval(52,62))).toBe(10); });
    it('length 53', () => { expect(length(interval(53,63))).toBe(10); });
    it('length 54', () => { expect(length(interval(54,64))).toBe(10); });
    it('length 55', () => { expect(length(interval(55,65))).toBe(10); });
    it('length 56', () => { expect(length(interval(56,66))).toBe(10); });
    it('length 57', () => { expect(length(interval(57,67))).toBe(10); });
    it('length 58', () => { expect(length(interval(58,68))).toBe(10); });
    it('length 59', () => { expect(length(interval(59,69))).toBe(10); });
    it('length 60', () => { expect(length(interval(60,70))).toBe(10); });
    it('length 61', () => { expect(length(interval(61,71))).toBe(10); });
    it('length 62', () => { expect(length(interval(62,72))).toBe(10); });
    it('length 63', () => { expect(length(interval(63,73))).toBe(10); });
    it('length 64', () => { expect(length(interval(64,74))).toBe(10); });
    it('length 65', () => { expect(length(interval(65,75))).toBe(10); });
    it('length 66', () => { expect(length(interval(66,76))).toBe(10); });
    it('length 67', () => { expect(length(interval(67,77))).toBe(10); });
    it('length 68', () => { expect(length(interval(68,78))).toBe(10); });
    it('length 69', () => { expect(length(interval(69,79))).toBe(10); });
    it('length 70', () => { expect(length(interval(70,80))).toBe(10); });
    it('length 71', () => { expect(length(interval(71,81))).toBe(10); });
    it('length 72', () => { expect(length(interval(72,82))).toBe(10); });
    it('length 73', () => { expect(length(interval(73,83))).toBe(10); });
    it('length 74', () => { expect(length(interval(74,84))).toBe(10); });
    it('length 75', () => { expect(length(interval(75,85))).toBe(10); });
    it('length 76', () => { expect(length(interval(76,86))).toBe(10); });
    it('length 77', () => { expect(length(interval(77,87))).toBe(10); });
    it('length 78', () => { expect(length(interval(78,88))).toBe(10); });
    it('length 79', () => { expect(length(interval(79,89))).toBe(10); });
    it('length 80', () => { expect(length(interval(80,90))).toBe(10); });
    it('length 81', () => { expect(length(interval(81,91))).toBe(10); });
    it('length 82', () => { expect(length(interval(82,92))).toBe(10); });
    it('length 83', () => { expect(length(interval(83,93))).toBe(10); });
    it('length 84', () => { expect(length(interval(84,94))).toBe(10); });
    it('length 85', () => { expect(length(interval(85,95))).toBe(10); });
    it('length 86', () => { expect(length(interval(86,96))).toBe(10); });
    it('length 87', () => { expect(length(interval(87,97))).toBe(10); });
    it('length 88', () => { expect(length(interval(88,98))).toBe(10); });
    it('length 89', () => { expect(length(interval(89,99))).toBe(10); });
    it('length 90', () => { expect(length(interval(90,100))).toBe(10); });
    it('length 91', () => { expect(length(interval(91,101))).toBe(10); });
    it('length 92', () => { expect(length(interval(92,102))).toBe(10); });
    it('length 93', () => { expect(length(interval(93,103))).toBe(10); });
    it('length 94', () => { expect(length(interval(94,104))).toBe(10); });
    it('length 95', () => { expect(length(interval(95,105))).toBe(10); });
    it('length 96', () => { expect(length(interval(96,106))).toBe(10); });
    it('length 97', () => { expect(length(interval(97,107))).toBe(10); });
    it('length 98', () => { expect(length(interval(98,108))).toBe(10); });
    it('length 99', () => { expect(length(interval(99,109))).toBe(10); });
    it('isEmpty false 0', () => { expect(isEmpty(interval(0,1))).toBe(false); });
    it('isEmpty false 1', () => { expect(isEmpty(interval(1,2))).toBe(false); });
    it('isEmpty false 2', () => { expect(isEmpty(interval(2,3))).toBe(false); });
    it('isEmpty false 3', () => { expect(isEmpty(interval(3,4))).toBe(false); });
    it('isEmpty false 4', () => { expect(isEmpty(interval(4,5))).toBe(false); });
    it('isEmpty false 5', () => { expect(isEmpty(interval(5,6))).toBe(false); });
    it('isEmpty false 6', () => { expect(isEmpty(interval(6,7))).toBe(false); });
    it('isEmpty false 7', () => { expect(isEmpty(interval(7,8))).toBe(false); });
    it('isEmpty false 8', () => { expect(isEmpty(interval(8,9))).toBe(false); });
    it('isEmpty false 9', () => { expect(isEmpty(interval(9,10))).toBe(false); });
    it('isEmpty false 10', () => { expect(isEmpty(interval(10,11))).toBe(false); });
    it('isEmpty false 11', () => { expect(isEmpty(interval(11,12))).toBe(false); });
    it('isEmpty false 12', () => { expect(isEmpty(interval(12,13))).toBe(false); });
    it('isEmpty false 13', () => { expect(isEmpty(interval(13,14))).toBe(false); });
    it('isEmpty false 14', () => { expect(isEmpty(interval(14,15))).toBe(false); });
    it('isEmpty false 15', () => { expect(isEmpty(interval(15,16))).toBe(false); });
    it('isEmpty false 16', () => { expect(isEmpty(interval(16,17))).toBe(false); });
    it('isEmpty false 17', () => { expect(isEmpty(interval(17,18))).toBe(false); });
    it('isEmpty false 18', () => { expect(isEmpty(interval(18,19))).toBe(false); });
    it('isEmpty false 19', () => { expect(isEmpty(interval(19,20))).toBe(false); });
    it('isEmpty false 20', () => { expect(isEmpty(interval(20,21))).toBe(false); });
    it('isEmpty false 21', () => { expect(isEmpty(interval(21,22))).toBe(false); });
    it('isEmpty false 22', () => { expect(isEmpty(interval(22,23))).toBe(false); });
    it('isEmpty false 23', () => { expect(isEmpty(interval(23,24))).toBe(false); });
    it('isEmpty false 24', () => { expect(isEmpty(interval(24,25))).toBe(false); });
    it('isEmpty false 25', () => { expect(isEmpty(interval(25,26))).toBe(false); });
    it('isEmpty false 26', () => { expect(isEmpty(interval(26,27))).toBe(false); });
    it('isEmpty false 27', () => { expect(isEmpty(interval(27,28))).toBe(false); });
    it('isEmpty false 28', () => { expect(isEmpty(interval(28,29))).toBe(false); });
    it('isEmpty false 29', () => { expect(isEmpty(interval(29,30))).toBe(false); });
    it('isEmpty false 30', () => { expect(isEmpty(interval(30,31))).toBe(false); });
    it('isEmpty false 31', () => { expect(isEmpty(interval(31,32))).toBe(false); });
    it('isEmpty false 32', () => { expect(isEmpty(interval(32,33))).toBe(false); });
    it('isEmpty false 33', () => { expect(isEmpty(interval(33,34))).toBe(false); });
    it('isEmpty false 34', () => { expect(isEmpty(interval(34,35))).toBe(false); });
    it('isEmpty false 35', () => { expect(isEmpty(interval(35,36))).toBe(false); });
    it('isEmpty false 36', () => { expect(isEmpty(interval(36,37))).toBe(false); });
    it('isEmpty false 37', () => { expect(isEmpty(interval(37,38))).toBe(false); });
    it('isEmpty false 38', () => { expect(isEmpty(interval(38,39))).toBe(false); });
    it('isEmpty false 39', () => { expect(isEmpty(interval(39,40))).toBe(false); });
    it('isEmpty false 40', () => { expect(isEmpty(interval(40,41))).toBe(false); });
    it('isEmpty false 41', () => { expect(isEmpty(interval(41,42))).toBe(false); });
    it('isEmpty false 42', () => { expect(isEmpty(interval(42,43))).toBe(false); });
    it('isEmpty false 43', () => { expect(isEmpty(interval(43,44))).toBe(false); });
    it('isEmpty false 44', () => { expect(isEmpty(interval(44,45))).toBe(false); });
    it('isEmpty false 45', () => { expect(isEmpty(interval(45,46))).toBe(false); });
    it('isEmpty false 46', () => { expect(isEmpty(interval(46,47))).toBe(false); });
    it('isEmpty false 47', () => { expect(isEmpty(interval(47,48))).toBe(false); });
    it('isEmpty false 48', () => { expect(isEmpty(interval(48,49))).toBe(false); });
    it('isEmpty false 49', () => { expect(isEmpty(interval(49,50))).toBe(false); });
    it('isEmpty false 50', () => { expect(isEmpty(interval(50,51))).toBe(false); });
    it('isEmpty false 51', () => { expect(isEmpty(interval(51,52))).toBe(false); });
    it('isEmpty false 52', () => { expect(isEmpty(interval(52,53))).toBe(false); });
    it('isEmpty false 53', () => { expect(isEmpty(interval(53,54))).toBe(false); });
    it('isEmpty false 54', () => { expect(isEmpty(interval(54,55))).toBe(false); });
    it('isEmpty false 55', () => { expect(isEmpty(interval(55,56))).toBe(false); });
    it('isEmpty false 56', () => { expect(isEmpty(interval(56,57))).toBe(false); });
    it('isEmpty false 57', () => { expect(isEmpty(interval(57,58))).toBe(false); });
    it('isEmpty false 58', () => { expect(isEmpty(interval(58,59))).toBe(false); });
    it('isEmpty false 59', () => { expect(isEmpty(interval(59,60))).toBe(false); });
    it('isEmpty false 60', () => { expect(isEmpty(interval(60,61))).toBe(false); });
    it('isEmpty false 61', () => { expect(isEmpty(interval(61,62))).toBe(false); });
    it('isEmpty false 62', () => { expect(isEmpty(interval(62,63))).toBe(false); });
    it('isEmpty false 63', () => { expect(isEmpty(interval(63,64))).toBe(false); });
    it('isEmpty false 64', () => { expect(isEmpty(interval(64,65))).toBe(false); });
    it('isEmpty false 65', () => { expect(isEmpty(interval(65,66))).toBe(false); });
    it('isEmpty false 66', () => { expect(isEmpty(interval(66,67))).toBe(false); });
    it('isEmpty false 67', () => { expect(isEmpty(interval(67,68))).toBe(false); });
    it('isEmpty false 68', () => { expect(isEmpty(interval(68,69))).toBe(false); });
    it('isEmpty false 69', () => { expect(isEmpty(interval(69,70))).toBe(false); });
    it('isEmpty false 70', () => { expect(isEmpty(interval(70,71))).toBe(false); });
    it('isEmpty false 71', () => { expect(isEmpty(interval(71,72))).toBe(false); });
    it('isEmpty false 72', () => { expect(isEmpty(interval(72,73))).toBe(false); });
    it('isEmpty false 73', () => { expect(isEmpty(interval(73,74))).toBe(false); });
    it('isEmpty false 74', () => { expect(isEmpty(interval(74,75))).toBe(false); });
    it('isEmpty false 75', () => { expect(isEmpty(interval(75,76))).toBe(false); });
    it('isEmpty false 76', () => { expect(isEmpty(interval(76,77))).toBe(false); });
    it('isEmpty false 77', () => { expect(isEmpty(interval(77,78))).toBe(false); });
    it('isEmpty false 78', () => { expect(isEmpty(interval(78,79))).toBe(false); });
    it('isEmpty false 79', () => { expect(isEmpty(interval(79,80))).toBe(false); });
    it('isEmpty false 80', () => { expect(isEmpty(interval(80,81))).toBe(false); });
    it('isEmpty false 81', () => { expect(isEmpty(interval(81,82))).toBe(false); });
    it('isEmpty false 82', () => { expect(isEmpty(interval(82,83))).toBe(false); });
    it('isEmpty false 83', () => { expect(isEmpty(interval(83,84))).toBe(false); });
    it('isEmpty false 84', () => { expect(isEmpty(interval(84,85))).toBe(false); });
    it('isEmpty false 85', () => { expect(isEmpty(interval(85,86))).toBe(false); });
    it('isEmpty false 86', () => { expect(isEmpty(interval(86,87))).toBe(false); });
    it('isEmpty false 87', () => { expect(isEmpty(interval(87,88))).toBe(false); });
    it('isEmpty false 88', () => { expect(isEmpty(interval(88,89))).toBe(false); });
    it('isEmpty false 89', () => { expect(isEmpty(interval(89,90))).toBe(false); });
    it('isEmpty false 90', () => { expect(isEmpty(interval(90,91))).toBe(false); });
    it('isEmpty false 91', () => { expect(isEmpty(interval(91,92))).toBe(false); });
    it('isEmpty false 92', () => { expect(isEmpty(interval(92,93))).toBe(false); });
    it('isEmpty false 93', () => { expect(isEmpty(interval(93,94))).toBe(false); });
    it('isEmpty false 94', () => { expect(isEmpty(interval(94,95))).toBe(false); });
    it('isEmpty false 95', () => { expect(isEmpty(interval(95,96))).toBe(false); });
    it('isEmpty false 96', () => { expect(isEmpty(interval(96,97))).toBe(false); });
    it('isEmpty false 97', () => { expect(isEmpty(interval(97,98))).toBe(false); });
    it('isEmpty false 98', () => { expect(isEmpty(interval(98,99))).toBe(false); });
    it('isEmpty false 99', () => { expect(isEmpty(interval(99,100))).toBe(false); });
    it('isEmpty true', () => { expect(isEmpty(interval(5,5))).toBe(true); });
  });
  describe('contains', () => {
    it('contains 0', () => { expect(contains(interval(0,100),0)).toBe(true); });
    it('contains 1', () => { expect(contains(interval(0,100),1)).toBe(true); });
    it('contains 2', () => { expect(contains(interval(0,100),2)).toBe(true); });
    it('contains 3', () => { expect(contains(interval(0,100),3)).toBe(true); });
    it('contains 4', () => { expect(contains(interval(0,100),4)).toBe(true); });
    it('contains 5', () => { expect(contains(interval(0,100),5)).toBe(true); });
    it('contains 6', () => { expect(contains(interval(0,100),6)).toBe(true); });
    it('contains 7', () => { expect(contains(interval(0,100),7)).toBe(true); });
    it('contains 8', () => { expect(contains(interval(0,100),8)).toBe(true); });
    it('contains 9', () => { expect(contains(interval(0,100),9)).toBe(true); });
    it('contains 10', () => { expect(contains(interval(0,100),10)).toBe(true); });
    it('contains 11', () => { expect(contains(interval(0,100),11)).toBe(true); });
    it('contains 12', () => { expect(contains(interval(0,100),12)).toBe(true); });
    it('contains 13', () => { expect(contains(interval(0,100),13)).toBe(true); });
    it('contains 14', () => { expect(contains(interval(0,100),14)).toBe(true); });
    it('contains 15', () => { expect(contains(interval(0,100),15)).toBe(true); });
    it('contains 16', () => { expect(contains(interval(0,100),16)).toBe(true); });
    it('contains 17', () => { expect(contains(interval(0,100),17)).toBe(true); });
    it('contains 18', () => { expect(contains(interval(0,100),18)).toBe(true); });
    it('contains 19', () => { expect(contains(interval(0,100),19)).toBe(true); });
    it('contains 20', () => { expect(contains(interval(0,100),20)).toBe(true); });
    it('contains 21', () => { expect(contains(interval(0,100),21)).toBe(true); });
    it('contains 22', () => { expect(contains(interval(0,100),22)).toBe(true); });
    it('contains 23', () => { expect(contains(interval(0,100),23)).toBe(true); });
    it('contains 24', () => { expect(contains(interval(0,100),24)).toBe(true); });
    it('contains 25', () => { expect(contains(interval(0,100),25)).toBe(true); });
    it('contains 26', () => { expect(contains(interval(0,100),26)).toBe(true); });
    it('contains 27', () => { expect(contains(interval(0,100),27)).toBe(true); });
    it('contains 28', () => { expect(contains(interval(0,100),28)).toBe(true); });
    it('contains 29', () => { expect(contains(interval(0,100),29)).toBe(true); });
    it('contains 30', () => { expect(contains(interval(0,100),30)).toBe(true); });
    it('contains 31', () => { expect(contains(interval(0,100),31)).toBe(true); });
    it('contains 32', () => { expect(contains(interval(0,100),32)).toBe(true); });
    it('contains 33', () => { expect(contains(interval(0,100),33)).toBe(true); });
    it('contains 34', () => { expect(contains(interval(0,100),34)).toBe(true); });
    it('contains 35', () => { expect(contains(interval(0,100),35)).toBe(true); });
    it('contains 36', () => { expect(contains(interval(0,100),36)).toBe(true); });
    it('contains 37', () => { expect(contains(interval(0,100),37)).toBe(true); });
    it('contains 38', () => { expect(contains(interval(0,100),38)).toBe(true); });
    it('contains 39', () => { expect(contains(interval(0,100),39)).toBe(true); });
    it('contains 40', () => { expect(contains(interval(0,100),40)).toBe(true); });
    it('contains 41', () => { expect(contains(interval(0,100),41)).toBe(true); });
    it('contains 42', () => { expect(contains(interval(0,100),42)).toBe(true); });
    it('contains 43', () => { expect(contains(interval(0,100),43)).toBe(true); });
    it('contains 44', () => { expect(contains(interval(0,100),44)).toBe(true); });
    it('contains 45', () => { expect(contains(interval(0,100),45)).toBe(true); });
    it('contains 46', () => { expect(contains(interval(0,100),46)).toBe(true); });
    it('contains 47', () => { expect(contains(interval(0,100),47)).toBe(true); });
    it('contains 48', () => { expect(contains(interval(0,100),48)).toBe(true); });
    it('contains 49', () => { expect(contains(interval(0,100),49)).toBe(true); });
    it('contains 50', () => { expect(contains(interval(0,100),50)).toBe(true); });
    it('contains 51', () => { expect(contains(interval(0,100),51)).toBe(true); });
    it('contains 52', () => { expect(contains(interval(0,100),52)).toBe(true); });
    it('contains 53', () => { expect(contains(interval(0,100),53)).toBe(true); });
    it('contains 54', () => { expect(contains(interval(0,100),54)).toBe(true); });
    it('contains 55', () => { expect(contains(interval(0,100),55)).toBe(true); });
    it('contains 56', () => { expect(contains(interval(0,100),56)).toBe(true); });
    it('contains 57', () => { expect(contains(interval(0,100),57)).toBe(true); });
    it('contains 58', () => { expect(contains(interval(0,100),58)).toBe(true); });
    it('contains 59', () => { expect(contains(interval(0,100),59)).toBe(true); });
    it('contains 60', () => { expect(contains(interval(0,100),60)).toBe(true); });
    it('contains 61', () => { expect(contains(interval(0,100),61)).toBe(true); });
    it('contains 62', () => { expect(contains(interval(0,100),62)).toBe(true); });
    it('contains 63', () => { expect(contains(interval(0,100),63)).toBe(true); });
    it('contains 64', () => { expect(contains(interval(0,100),64)).toBe(true); });
    it('contains 65', () => { expect(contains(interval(0,100),65)).toBe(true); });
    it('contains 66', () => { expect(contains(interval(0,100),66)).toBe(true); });
    it('contains 67', () => { expect(contains(interval(0,100),67)).toBe(true); });
    it('contains 68', () => { expect(contains(interval(0,100),68)).toBe(true); });
    it('contains 69', () => { expect(contains(interval(0,100),69)).toBe(true); });
    it('contains 70', () => { expect(contains(interval(0,100),70)).toBe(true); });
    it('contains 71', () => { expect(contains(interval(0,100),71)).toBe(true); });
    it('contains 72', () => { expect(contains(interval(0,100),72)).toBe(true); });
    it('contains 73', () => { expect(contains(interval(0,100),73)).toBe(true); });
    it('contains 74', () => { expect(contains(interval(0,100),74)).toBe(true); });
    it('contains 75', () => { expect(contains(interval(0,100),75)).toBe(true); });
    it('contains 76', () => { expect(contains(interval(0,100),76)).toBe(true); });
    it('contains 77', () => { expect(contains(interval(0,100),77)).toBe(true); });
    it('contains 78', () => { expect(contains(interval(0,100),78)).toBe(true); });
    it('contains 79', () => { expect(contains(interval(0,100),79)).toBe(true); });
    it('contains 80', () => { expect(contains(interval(0,100),80)).toBe(true); });
    it('contains 81', () => { expect(contains(interval(0,100),81)).toBe(true); });
    it('contains 82', () => { expect(contains(interval(0,100),82)).toBe(true); });
    it('contains 83', () => { expect(contains(interval(0,100),83)).toBe(true); });
    it('contains 84', () => { expect(contains(interval(0,100),84)).toBe(true); });
    it('contains 85', () => { expect(contains(interval(0,100),85)).toBe(true); });
    it('contains 86', () => { expect(contains(interval(0,100),86)).toBe(true); });
    it('contains 87', () => { expect(contains(interval(0,100),87)).toBe(true); });
    it('contains 88', () => { expect(contains(interval(0,100),88)).toBe(true); });
    it('contains 89', () => { expect(contains(interval(0,100),89)).toBe(true); });
    it('contains 90', () => { expect(contains(interval(0,100),90)).toBe(true); });
    it('contains 91', () => { expect(contains(interval(0,100),91)).toBe(true); });
    it('contains 92', () => { expect(contains(interval(0,100),92)).toBe(true); });
    it('contains 93', () => { expect(contains(interval(0,100),93)).toBe(true); });
    it('contains 94', () => { expect(contains(interval(0,100),94)).toBe(true); });
    it('contains 95', () => { expect(contains(interval(0,100),95)).toBe(true); });
    it('contains 96', () => { expect(contains(interval(0,100),96)).toBe(true); });
    it('contains 97', () => { expect(contains(interval(0,100),97)).toBe(true); });
    it('contains 98', () => { expect(contains(interval(0,100),98)).toBe(true); });
    it('contains 99', () => { expect(contains(interval(0,100),99)).toBe(true); });
    it('not contains 0', () => { expect(contains(interval(10,20),100)).toBe(false); });
    it('not contains 1', () => { expect(contains(interval(10,20),101)).toBe(false); });
    it('not contains 2', () => { expect(contains(interval(10,20),102)).toBe(false); });
    it('not contains 3', () => { expect(contains(interval(10,20),103)).toBe(false); });
    it('not contains 4', () => { expect(contains(interval(10,20),104)).toBe(false); });
    it('not contains 5', () => { expect(contains(interval(10,20),105)).toBe(false); });
    it('not contains 6', () => { expect(contains(interval(10,20),106)).toBe(false); });
    it('not contains 7', () => { expect(contains(interval(10,20),107)).toBe(false); });
    it('not contains 8', () => { expect(contains(interval(10,20),108)).toBe(false); });
    it('not contains 9', () => { expect(contains(interval(10,20),109)).toBe(false); });
    it('not contains 10', () => { expect(contains(interval(10,20),110)).toBe(false); });
    it('not contains 11', () => { expect(contains(interval(10,20),111)).toBe(false); });
    it('not contains 12', () => { expect(contains(interval(10,20),112)).toBe(false); });
    it('not contains 13', () => { expect(contains(interval(10,20),113)).toBe(false); });
    it('not contains 14', () => { expect(contains(interval(10,20),114)).toBe(false); });
    it('not contains 15', () => { expect(contains(interval(10,20),115)).toBe(false); });
    it('not contains 16', () => { expect(contains(interval(10,20),116)).toBe(false); });
    it('not contains 17', () => { expect(contains(interval(10,20),117)).toBe(false); });
    it('not contains 18', () => { expect(contains(interval(10,20),118)).toBe(false); });
    it('not contains 19', () => { expect(contains(interval(10,20),119)).toBe(false); });
    it('not contains 20', () => { expect(contains(interval(10,20),120)).toBe(false); });
    it('not contains 21', () => { expect(contains(interval(10,20),121)).toBe(false); });
    it('not contains 22', () => { expect(contains(interval(10,20),122)).toBe(false); });
    it('not contains 23', () => { expect(contains(interval(10,20),123)).toBe(false); });
    it('not contains 24', () => { expect(contains(interval(10,20),124)).toBe(false); });
    it('not contains 25', () => { expect(contains(interval(10,20),125)).toBe(false); });
    it('not contains 26', () => { expect(contains(interval(10,20),126)).toBe(false); });
    it('not contains 27', () => { expect(contains(interval(10,20),127)).toBe(false); });
    it('not contains 28', () => { expect(contains(interval(10,20),128)).toBe(false); });
    it('not contains 29', () => { expect(contains(interval(10,20),129)).toBe(false); });
    it('not contains 30', () => { expect(contains(interval(10,20),130)).toBe(false); });
    it('not contains 31', () => { expect(contains(interval(10,20),131)).toBe(false); });
    it('not contains 32', () => { expect(contains(interval(10,20),132)).toBe(false); });
    it('not contains 33', () => { expect(contains(interval(10,20),133)).toBe(false); });
    it('not contains 34', () => { expect(contains(interval(10,20),134)).toBe(false); });
    it('not contains 35', () => { expect(contains(interval(10,20),135)).toBe(false); });
    it('not contains 36', () => { expect(contains(interval(10,20),136)).toBe(false); });
    it('not contains 37', () => { expect(contains(interval(10,20),137)).toBe(false); });
    it('not contains 38', () => { expect(contains(interval(10,20),138)).toBe(false); });
    it('not contains 39', () => { expect(contains(interval(10,20),139)).toBe(false); });
    it('not contains 40', () => { expect(contains(interval(10,20),140)).toBe(false); });
    it('not contains 41', () => { expect(contains(interval(10,20),141)).toBe(false); });
    it('not contains 42', () => { expect(contains(interval(10,20),142)).toBe(false); });
    it('not contains 43', () => { expect(contains(interval(10,20),143)).toBe(false); });
    it('not contains 44', () => { expect(contains(interval(10,20),144)).toBe(false); });
    it('not contains 45', () => { expect(contains(interval(10,20),145)).toBe(false); });
    it('not contains 46', () => { expect(contains(interval(10,20),146)).toBe(false); });
    it('not contains 47', () => { expect(contains(interval(10,20),147)).toBe(false); });
    it('not contains 48', () => { expect(contains(interval(10,20),148)).toBe(false); });
    it('not contains 49', () => { expect(contains(interval(10,20),149)).toBe(false); });
    it('not contains 50', () => { expect(contains(interval(10,20),150)).toBe(false); });
    it('not contains 51', () => { expect(contains(interval(10,20),151)).toBe(false); });
    it('not contains 52', () => { expect(contains(interval(10,20),152)).toBe(false); });
    it('not contains 53', () => { expect(contains(interval(10,20),153)).toBe(false); });
    it('not contains 54', () => { expect(contains(interval(10,20),154)).toBe(false); });
    it('not contains 55', () => { expect(contains(interval(10,20),155)).toBe(false); });
    it('not contains 56', () => { expect(contains(interval(10,20),156)).toBe(false); });
    it('not contains 57', () => { expect(contains(interval(10,20),157)).toBe(false); });
    it('not contains 58', () => { expect(contains(interval(10,20),158)).toBe(false); });
    it('not contains 59', () => { expect(contains(interval(10,20),159)).toBe(false); });
    it('not contains 60', () => { expect(contains(interval(10,20),160)).toBe(false); });
    it('not contains 61', () => { expect(contains(interval(10,20),161)).toBe(false); });
    it('not contains 62', () => { expect(contains(interval(10,20),162)).toBe(false); });
    it('not contains 63', () => { expect(contains(interval(10,20),163)).toBe(false); });
    it('not contains 64', () => { expect(contains(interval(10,20),164)).toBe(false); });
    it('not contains 65', () => { expect(contains(interval(10,20),165)).toBe(false); });
    it('not contains 66', () => { expect(contains(interval(10,20),166)).toBe(false); });
    it('not contains 67', () => { expect(contains(interval(10,20),167)).toBe(false); });
    it('not contains 68', () => { expect(contains(interval(10,20),168)).toBe(false); });
    it('not contains 69', () => { expect(contains(interval(10,20),169)).toBe(false); });
    it('not contains 70', () => { expect(contains(interval(10,20),170)).toBe(false); });
    it('not contains 71', () => { expect(contains(interval(10,20),171)).toBe(false); });
    it('not contains 72', () => { expect(contains(interval(10,20),172)).toBe(false); });
    it('not contains 73', () => { expect(contains(interval(10,20),173)).toBe(false); });
    it('not contains 74', () => { expect(contains(interval(10,20),174)).toBe(false); });
    it('not contains 75', () => { expect(contains(interval(10,20),175)).toBe(false); });
    it('not contains 76', () => { expect(contains(interval(10,20),176)).toBe(false); });
    it('not contains 77', () => { expect(contains(interval(10,20),177)).toBe(false); });
    it('not contains 78', () => { expect(contains(interval(10,20),178)).toBe(false); });
    it('not contains 79', () => { expect(contains(interval(10,20),179)).toBe(false); });
  });
  describe('overlaps/intersect', () => {
    it('overlaps 0', () => { expect(overlaps(interval(0,10),interval(5,15))).toBe(true); });
    it('overlaps 1', () => { expect(overlaps(interval(1,11),interval(6,16))).toBe(true); });
    it('overlaps 2', () => { expect(overlaps(interval(2,12),interval(7,17))).toBe(true); });
    it('overlaps 3', () => { expect(overlaps(interval(3,13),interval(8,18))).toBe(true); });
    it('overlaps 4', () => { expect(overlaps(interval(4,14),interval(9,19))).toBe(true); });
    it('overlaps 5', () => { expect(overlaps(interval(5,15),interval(10,20))).toBe(true); });
    it('overlaps 6', () => { expect(overlaps(interval(6,16),interval(11,21))).toBe(true); });
    it('overlaps 7', () => { expect(overlaps(interval(7,17),interval(12,22))).toBe(true); });
    it('overlaps 8', () => { expect(overlaps(interval(8,18),interval(13,23))).toBe(true); });
    it('overlaps 9', () => { expect(overlaps(interval(9,19),interval(14,24))).toBe(true); });
    it('overlaps 10', () => { expect(overlaps(interval(10,20),interval(15,25))).toBe(true); });
    it('overlaps 11', () => { expect(overlaps(interval(11,21),interval(16,26))).toBe(true); });
    it('overlaps 12', () => { expect(overlaps(interval(12,22),interval(17,27))).toBe(true); });
    it('overlaps 13', () => { expect(overlaps(interval(13,23),interval(18,28))).toBe(true); });
    it('overlaps 14', () => { expect(overlaps(interval(14,24),interval(19,29))).toBe(true); });
    it('overlaps 15', () => { expect(overlaps(interval(15,25),interval(20,30))).toBe(true); });
    it('overlaps 16', () => { expect(overlaps(interval(16,26),interval(21,31))).toBe(true); });
    it('overlaps 17', () => { expect(overlaps(interval(17,27),interval(22,32))).toBe(true); });
    it('overlaps 18', () => { expect(overlaps(interval(18,28),interval(23,33))).toBe(true); });
    it('overlaps 19', () => { expect(overlaps(interval(19,29),interval(24,34))).toBe(true); });
    it('overlaps 20', () => { expect(overlaps(interval(20,30),interval(25,35))).toBe(true); });
    it('overlaps 21', () => { expect(overlaps(interval(21,31),interval(26,36))).toBe(true); });
    it('overlaps 22', () => { expect(overlaps(interval(22,32),interval(27,37))).toBe(true); });
    it('overlaps 23', () => { expect(overlaps(interval(23,33),interval(28,38))).toBe(true); });
    it('overlaps 24', () => { expect(overlaps(interval(24,34),interval(29,39))).toBe(true); });
    it('overlaps 25', () => { expect(overlaps(interval(25,35),interval(30,40))).toBe(true); });
    it('overlaps 26', () => { expect(overlaps(interval(26,36),interval(31,41))).toBe(true); });
    it('overlaps 27', () => { expect(overlaps(interval(27,37),interval(32,42))).toBe(true); });
    it('overlaps 28', () => { expect(overlaps(interval(28,38),interval(33,43))).toBe(true); });
    it('overlaps 29', () => { expect(overlaps(interval(29,39),interval(34,44))).toBe(true); });
    it('overlaps 30', () => { expect(overlaps(interval(30,40),interval(35,45))).toBe(true); });
    it('overlaps 31', () => { expect(overlaps(interval(31,41),interval(36,46))).toBe(true); });
    it('overlaps 32', () => { expect(overlaps(interval(32,42),interval(37,47))).toBe(true); });
    it('overlaps 33', () => { expect(overlaps(interval(33,43),interval(38,48))).toBe(true); });
    it('overlaps 34', () => { expect(overlaps(interval(34,44),interval(39,49))).toBe(true); });
    it('overlaps 35', () => { expect(overlaps(interval(35,45),interval(40,50))).toBe(true); });
    it('overlaps 36', () => { expect(overlaps(interval(36,46),interval(41,51))).toBe(true); });
    it('overlaps 37', () => { expect(overlaps(interval(37,47),interval(42,52))).toBe(true); });
    it('overlaps 38', () => { expect(overlaps(interval(38,48),interval(43,53))).toBe(true); });
    it('overlaps 39', () => { expect(overlaps(interval(39,49),interval(44,54))).toBe(true); });
    it('overlaps 40', () => { expect(overlaps(interval(40,50),interval(45,55))).toBe(true); });
    it('overlaps 41', () => { expect(overlaps(interval(41,51),interval(46,56))).toBe(true); });
    it('overlaps 42', () => { expect(overlaps(interval(42,52),interval(47,57))).toBe(true); });
    it('overlaps 43', () => { expect(overlaps(interval(43,53),interval(48,58))).toBe(true); });
    it('overlaps 44', () => { expect(overlaps(interval(44,54),interval(49,59))).toBe(true); });
    it('overlaps 45', () => { expect(overlaps(interval(45,55),interval(50,60))).toBe(true); });
    it('overlaps 46', () => { expect(overlaps(interval(46,56),interval(51,61))).toBe(true); });
    it('overlaps 47', () => { expect(overlaps(interval(47,57),interval(52,62))).toBe(true); });
    it('overlaps 48', () => { expect(overlaps(interval(48,58),interval(53,63))).toBe(true); });
    it('overlaps 49', () => { expect(overlaps(interval(49,59),interval(54,64))).toBe(true); });
    it('overlaps 50', () => { expect(overlaps(interval(50,60),interval(55,65))).toBe(true); });
    it('overlaps 51', () => { expect(overlaps(interval(51,61),interval(56,66))).toBe(true); });
    it('overlaps 52', () => { expect(overlaps(interval(52,62),interval(57,67))).toBe(true); });
    it('overlaps 53', () => { expect(overlaps(interval(53,63),interval(58,68))).toBe(true); });
    it('overlaps 54', () => { expect(overlaps(interval(54,64),interval(59,69))).toBe(true); });
    it('overlaps 55', () => { expect(overlaps(interval(55,65),interval(60,70))).toBe(true); });
    it('overlaps 56', () => { expect(overlaps(interval(56,66),interval(61,71))).toBe(true); });
    it('overlaps 57', () => { expect(overlaps(interval(57,67),interval(62,72))).toBe(true); });
    it('overlaps 58', () => { expect(overlaps(interval(58,68),interval(63,73))).toBe(true); });
    it('overlaps 59', () => { expect(overlaps(interval(59,69),interval(64,74))).toBe(true); });
    it('overlaps 60', () => { expect(overlaps(interval(60,70),interval(65,75))).toBe(true); });
    it('overlaps 61', () => { expect(overlaps(interval(61,71),interval(66,76))).toBe(true); });
    it('overlaps 62', () => { expect(overlaps(interval(62,72),interval(67,77))).toBe(true); });
    it('overlaps 63', () => { expect(overlaps(interval(63,73),interval(68,78))).toBe(true); });
    it('overlaps 64', () => { expect(overlaps(interval(64,74),interval(69,79))).toBe(true); });
    it('overlaps 65', () => { expect(overlaps(interval(65,75),interval(70,80))).toBe(true); });
    it('overlaps 66', () => { expect(overlaps(interval(66,76),interval(71,81))).toBe(true); });
    it('overlaps 67', () => { expect(overlaps(interval(67,77),interval(72,82))).toBe(true); });
    it('overlaps 68', () => { expect(overlaps(interval(68,78),interval(73,83))).toBe(true); });
    it('overlaps 69', () => { expect(overlaps(interval(69,79),interval(74,84))).toBe(true); });
    it('overlaps 70', () => { expect(overlaps(interval(70,80),interval(75,85))).toBe(true); });
    it('overlaps 71', () => { expect(overlaps(interval(71,81),interval(76,86))).toBe(true); });
    it('overlaps 72', () => { expect(overlaps(interval(72,82),interval(77,87))).toBe(true); });
    it('overlaps 73', () => { expect(overlaps(interval(73,83),interval(78,88))).toBe(true); });
    it('overlaps 74', () => { expect(overlaps(interval(74,84),interval(79,89))).toBe(true); });
    it('overlaps 75', () => { expect(overlaps(interval(75,85),interval(80,90))).toBe(true); });
    it('overlaps 76', () => { expect(overlaps(interval(76,86),interval(81,91))).toBe(true); });
    it('overlaps 77', () => { expect(overlaps(interval(77,87),interval(82,92))).toBe(true); });
    it('overlaps 78', () => { expect(overlaps(interval(78,88),interval(83,93))).toBe(true); });
    it('overlaps 79', () => { expect(overlaps(interval(79,89),interval(84,94))).toBe(true); });
    it('no overlap 0', () => { expect(overlaps(interval(0,5),interval(10,15))).toBe(false); });
    it('no overlap 1', () => { expect(overlaps(interval(1,6),interval(11,16))).toBe(false); });
    it('no overlap 2', () => { expect(overlaps(interval(2,7),interval(12,17))).toBe(false); });
    it('no overlap 3', () => { expect(overlaps(interval(3,8),interval(13,18))).toBe(false); });
    it('no overlap 4', () => { expect(overlaps(interval(4,9),interval(14,19))).toBe(false); });
    it('no overlap 5', () => { expect(overlaps(interval(5,10),interval(15,20))).toBe(false); });
    it('no overlap 6', () => { expect(overlaps(interval(6,11),interval(16,21))).toBe(false); });
    it('no overlap 7', () => { expect(overlaps(interval(7,12),interval(17,22))).toBe(false); });
    it('no overlap 8', () => { expect(overlaps(interval(8,13),interval(18,23))).toBe(false); });
    it('no overlap 9', () => { expect(overlaps(interval(9,14),interval(19,24))).toBe(false); });
    it('no overlap 10', () => { expect(overlaps(interval(10,15),interval(20,25))).toBe(false); });
    it('no overlap 11', () => { expect(overlaps(interval(11,16),interval(21,26))).toBe(false); });
    it('no overlap 12', () => { expect(overlaps(interval(12,17),interval(22,27))).toBe(false); });
    it('no overlap 13', () => { expect(overlaps(interval(13,18),interval(23,28))).toBe(false); });
    it('no overlap 14', () => { expect(overlaps(interval(14,19),interval(24,29))).toBe(false); });
    it('no overlap 15', () => { expect(overlaps(interval(15,20),interval(25,30))).toBe(false); });
    it('no overlap 16', () => { expect(overlaps(interval(16,21),interval(26,31))).toBe(false); });
    it('no overlap 17', () => { expect(overlaps(interval(17,22),interval(27,32))).toBe(false); });
    it('no overlap 18', () => { expect(overlaps(interval(18,23),interval(28,33))).toBe(false); });
    it('no overlap 19', () => { expect(overlaps(interval(19,24),interval(29,34))).toBe(false); });
    it('no overlap 20', () => { expect(overlaps(interval(20,25),interval(30,35))).toBe(false); });
    it('no overlap 21', () => { expect(overlaps(interval(21,26),interval(31,36))).toBe(false); });
    it('no overlap 22', () => { expect(overlaps(interval(22,27),interval(32,37))).toBe(false); });
    it('no overlap 23', () => { expect(overlaps(interval(23,28),interval(33,38))).toBe(false); });
    it('no overlap 24', () => { expect(overlaps(interval(24,29),interval(34,39))).toBe(false); });
    it('no overlap 25', () => { expect(overlaps(interval(25,30),interval(35,40))).toBe(false); });
    it('no overlap 26', () => { expect(overlaps(interval(26,31),interval(36,41))).toBe(false); });
    it('no overlap 27', () => { expect(overlaps(interval(27,32),interval(37,42))).toBe(false); });
    it('no overlap 28', () => { expect(overlaps(interval(28,33),interval(38,43))).toBe(false); });
    it('no overlap 29', () => { expect(overlaps(interval(29,34),interval(39,44))).toBe(false); });
    it('no overlap 30', () => { expect(overlaps(interval(30,35),interval(40,45))).toBe(false); });
    it('no overlap 31', () => { expect(overlaps(interval(31,36),interval(41,46))).toBe(false); });
    it('no overlap 32', () => { expect(overlaps(interval(32,37),interval(42,47))).toBe(false); });
    it('no overlap 33', () => { expect(overlaps(interval(33,38),interval(43,48))).toBe(false); });
    it('no overlap 34', () => { expect(overlaps(interval(34,39),interval(44,49))).toBe(false); });
    it('no overlap 35', () => { expect(overlaps(interval(35,40),interval(45,50))).toBe(false); });
    it('no overlap 36', () => { expect(overlaps(interval(36,41),interval(46,51))).toBe(false); });
    it('no overlap 37', () => { expect(overlaps(interval(37,42),interval(47,52))).toBe(false); });
    it('no overlap 38', () => { expect(overlaps(interval(38,43),interval(48,53))).toBe(false); });
    it('no overlap 39', () => { expect(overlaps(interval(39,44),interval(49,54))).toBe(false); });
    it('no overlap 40', () => { expect(overlaps(interval(40,45),interval(50,55))).toBe(false); });
    it('no overlap 41', () => { expect(overlaps(interval(41,46),interval(51,56))).toBe(false); });
    it('no overlap 42', () => { expect(overlaps(interval(42,47),interval(52,57))).toBe(false); });
    it('no overlap 43', () => { expect(overlaps(interval(43,48),interval(53,58))).toBe(false); });
    it('no overlap 44', () => { expect(overlaps(interval(44,49),interval(54,59))).toBe(false); });
    it('no overlap 45', () => { expect(overlaps(interval(45,50),interval(55,60))).toBe(false); });
    it('no overlap 46', () => { expect(overlaps(interval(46,51),interval(56,61))).toBe(false); });
    it('no overlap 47', () => { expect(overlaps(interval(47,52),interval(57,62))).toBe(false); });
    it('no overlap 48', () => { expect(overlaps(interval(48,53),interval(58,63))).toBe(false); });
    it('no overlap 49', () => { expect(overlaps(interval(49,54),interval(59,64))).toBe(false); });
    it('no overlap 50', () => { expect(overlaps(interval(50,55),interval(60,65))).toBe(false); });
    it('no overlap 51', () => { expect(overlaps(interval(51,56),interval(61,66))).toBe(false); });
    it('no overlap 52', () => { expect(overlaps(interval(52,57),interval(62,67))).toBe(false); });
    it('no overlap 53', () => { expect(overlaps(interval(53,58),interval(63,68))).toBe(false); });
    it('no overlap 54', () => { expect(overlaps(interval(54,59),interval(64,69))).toBe(false); });
    it('no overlap 55', () => { expect(overlaps(interval(55,60),interval(65,70))).toBe(false); });
    it('no overlap 56', () => { expect(overlaps(interval(56,61),interval(66,71))).toBe(false); });
    it('no overlap 57', () => { expect(overlaps(interval(57,62),interval(67,72))).toBe(false); });
    it('no overlap 58', () => { expect(overlaps(interval(58,63),interval(68,73))).toBe(false); });
    it('no overlap 59', () => { expect(overlaps(interval(59,64),interval(69,74))).toBe(false); });
    it('no overlap 60', () => { expect(overlaps(interval(60,65),interval(70,75))).toBe(false); });
    it('no overlap 61', () => { expect(overlaps(interval(61,66),interval(71,76))).toBe(false); });
    it('no overlap 62', () => { expect(overlaps(interval(62,67),interval(72,77))).toBe(false); });
    it('no overlap 63', () => { expect(overlaps(interval(63,68),interval(73,78))).toBe(false); });
    it('no overlap 64', () => { expect(overlaps(interval(64,69),interval(74,79))).toBe(false); });
    it('no overlap 65', () => { expect(overlaps(interval(65,70),interval(75,80))).toBe(false); });
    it('no overlap 66', () => { expect(overlaps(interval(66,71),interval(76,81))).toBe(false); });
    it('no overlap 67', () => { expect(overlaps(interval(67,72),interval(77,82))).toBe(false); });
    it('no overlap 68', () => { expect(overlaps(interval(68,73),interval(78,83))).toBe(false); });
    it('no overlap 69', () => { expect(overlaps(interval(69,74),interval(79,84))).toBe(false); });
    it('no overlap 70', () => { expect(overlaps(interval(70,75),interval(80,85))).toBe(false); });
    it('no overlap 71', () => { expect(overlaps(interval(71,76),interval(81,86))).toBe(false); });
    it('no overlap 72', () => { expect(overlaps(interval(72,77),interval(82,87))).toBe(false); });
    it('no overlap 73', () => { expect(overlaps(interval(73,78),interval(83,88))).toBe(false); });
    it('no overlap 74', () => { expect(overlaps(interval(74,79),interval(84,89))).toBe(false); });
    it('no overlap 75', () => { expect(overlaps(interval(75,80),interval(85,90))).toBe(false); });
    it('no overlap 76', () => { expect(overlaps(interval(76,81),interval(86,91))).toBe(false); });
    it('no overlap 77', () => { expect(overlaps(interval(77,82),interval(87,92))).toBe(false); });
    it('no overlap 78', () => { expect(overlaps(interval(78,83),interval(88,93))).toBe(false); });
    it('no overlap 79', () => { expect(overlaps(interval(79,84),interval(89,94))).toBe(false); });
  });
  describe('clamp/shift/scale', () => {
    it('clamp 0', () => { expect(clamp(50,interval(0,100))).toBe(Math.min(100,Math.max(0,50))); });
    it('clamp 1', () => { expect(clamp(51,interval(0,100))).toBe(Math.min(100,Math.max(0,51))); });
    it('clamp 2', () => { expect(clamp(52,interval(0,100))).toBe(Math.min(100,Math.max(0,52))); });
    it('clamp 3', () => { expect(clamp(53,interval(0,100))).toBe(Math.min(100,Math.max(0,53))); });
    it('clamp 4', () => { expect(clamp(54,interval(0,100))).toBe(Math.min(100,Math.max(0,54))); });
    it('clamp 5', () => { expect(clamp(55,interval(0,100))).toBe(Math.min(100,Math.max(0,55))); });
    it('clamp 6', () => { expect(clamp(56,interval(0,100))).toBe(Math.min(100,Math.max(0,56))); });
    it('clamp 7', () => { expect(clamp(57,interval(0,100))).toBe(Math.min(100,Math.max(0,57))); });
    it('clamp 8', () => { expect(clamp(58,interval(0,100))).toBe(Math.min(100,Math.max(0,58))); });
    it('clamp 9', () => { expect(clamp(59,interval(0,100))).toBe(Math.min(100,Math.max(0,59))); });
    it('clamp 10', () => { expect(clamp(60,interval(0,100))).toBe(Math.min(100,Math.max(0,60))); });
    it('clamp 11', () => { expect(clamp(61,interval(0,100))).toBe(Math.min(100,Math.max(0,61))); });
    it('clamp 12', () => { expect(clamp(62,interval(0,100))).toBe(Math.min(100,Math.max(0,62))); });
    it('clamp 13', () => { expect(clamp(63,interval(0,100))).toBe(Math.min(100,Math.max(0,63))); });
    it('clamp 14', () => { expect(clamp(64,interval(0,100))).toBe(Math.min(100,Math.max(0,64))); });
    it('clamp 15', () => { expect(clamp(65,interval(0,100))).toBe(Math.min(100,Math.max(0,65))); });
    it('clamp 16', () => { expect(clamp(66,interval(0,100))).toBe(Math.min(100,Math.max(0,66))); });
    it('clamp 17', () => { expect(clamp(67,interval(0,100))).toBe(Math.min(100,Math.max(0,67))); });
    it('clamp 18', () => { expect(clamp(68,interval(0,100))).toBe(Math.min(100,Math.max(0,68))); });
    it('clamp 19', () => { expect(clamp(69,interval(0,100))).toBe(Math.min(100,Math.max(0,69))); });
    it('clamp 20', () => { expect(clamp(70,interval(0,100))).toBe(Math.min(100,Math.max(0,70))); });
    it('clamp 21', () => { expect(clamp(71,interval(0,100))).toBe(Math.min(100,Math.max(0,71))); });
    it('clamp 22', () => { expect(clamp(72,interval(0,100))).toBe(Math.min(100,Math.max(0,72))); });
    it('clamp 23', () => { expect(clamp(73,interval(0,100))).toBe(Math.min(100,Math.max(0,73))); });
    it('clamp 24', () => { expect(clamp(74,interval(0,100))).toBe(Math.min(100,Math.max(0,74))); });
    it('clamp 25', () => { expect(clamp(75,interval(0,100))).toBe(Math.min(100,Math.max(0,75))); });
    it('clamp 26', () => { expect(clamp(76,interval(0,100))).toBe(Math.min(100,Math.max(0,76))); });
    it('clamp 27', () => { expect(clamp(77,interval(0,100))).toBe(Math.min(100,Math.max(0,77))); });
    it('clamp 28', () => { expect(clamp(78,interval(0,100))).toBe(Math.min(100,Math.max(0,78))); });
    it('clamp 29', () => { expect(clamp(79,interval(0,100))).toBe(Math.min(100,Math.max(0,79))); });
    it('clamp 30', () => { expect(clamp(80,interval(0,100))).toBe(Math.min(100,Math.max(0,80))); });
    it('clamp 31', () => { expect(clamp(81,interval(0,100))).toBe(Math.min(100,Math.max(0,81))); });
    it('clamp 32', () => { expect(clamp(82,interval(0,100))).toBe(Math.min(100,Math.max(0,82))); });
    it('clamp 33', () => { expect(clamp(83,interval(0,100))).toBe(Math.min(100,Math.max(0,83))); });
    it('clamp 34', () => { expect(clamp(84,interval(0,100))).toBe(Math.min(100,Math.max(0,84))); });
    it('clamp 35', () => { expect(clamp(85,interval(0,100))).toBe(Math.min(100,Math.max(0,85))); });
    it('clamp 36', () => { expect(clamp(86,interval(0,100))).toBe(Math.min(100,Math.max(0,86))); });
    it('clamp 37', () => { expect(clamp(87,interval(0,100))).toBe(Math.min(100,Math.max(0,87))); });
    it('clamp 38', () => { expect(clamp(88,interval(0,100))).toBe(Math.min(100,Math.max(0,88))); });
    it('clamp 39', () => { expect(clamp(89,interval(0,100))).toBe(Math.min(100,Math.max(0,89))); });
    it('clamp 40', () => { expect(clamp(90,interval(0,100))).toBe(Math.min(100,Math.max(0,90))); });
    it('clamp 41', () => { expect(clamp(91,interval(0,100))).toBe(Math.min(100,Math.max(0,91))); });
    it('clamp 42', () => { expect(clamp(92,interval(0,100))).toBe(Math.min(100,Math.max(0,92))); });
    it('clamp 43', () => { expect(clamp(93,interval(0,100))).toBe(Math.min(100,Math.max(0,93))); });
    it('clamp 44', () => { expect(clamp(94,interval(0,100))).toBe(Math.min(100,Math.max(0,94))); });
    it('clamp 45', () => { expect(clamp(95,interval(0,100))).toBe(Math.min(100,Math.max(0,95))); });
    it('clamp 46', () => { expect(clamp(96,interval(0,100))).toBe(Math.min(100,Math.max(0,96))); });
    it('clamp 47', () => { expect(clamp(97,interval(0,100))).toBe(Math.min(100,Math.max(0,97))); });
    it('clamp 48', () => { expect(clamp(98,interval(0,100))).toBe(Math.min(100,Math.max(0,98))); });
    it('clamp 49', () => { expect(clamp(99,interval(0,100))).toBe(Math.min(100,Math.max(0,99))); });
    it('clamp 50', () => { expect(clamp(100,interval(0,100))).toBe(Math.min(100,Math.max(0,100))); });
    it('clamp 51', () => { expect(clamp(101,interval(0,100))).toBe(Math.min(100,Math.max(0,101))); });
    it('clamp 52', () => { expect(clamp(102,interval(0,100))).toBe(Math.min(100,Math.max(0,102))); });
    it('clamp 53', () => { expect(clamp(103,interval(0,100))).toBe(Math.min(100,Math.max(0,103))); });
    it('clamp 54', () => { expect(clamp(104,interval(0,100))).toBe(Math.min(100,Math.max(0,104))); });
    it('clamp 55', () => { expect(clamp(105,interval(0,100))).toBe(Math.min(100,Math.max(0,105))); });
    it('clamp 56', () => { expect(clamp(106,interval(0,100))).toBe(Math.min(100,Math.max(0,106))); });
    it('clamp 57', () => { expect(clamp(107,interval(0,100))).toBe(Math.min(100,Math.max(0,107))); });
    it('clamp 58', () => { expect(clamp(108,interval(0,100))).toBe(Math.min(100,Math.max(0,108))); });
    it('clamp 59', () => { expect(clamp(109,interval(0,100))).toBe(Math.min(100,Math.max(0,109))); });
    it('clamp 60', () => { expect(clamp(110,interval(0,100))).toBe(Math.min(100,Math.max(0,110))); });
    it('clamp 61', () => { expect(clamp(111,interval(0,100))).toBe(Math.min(100,Math.max(0,111))); });
    it('clamp 62', () => { expect(clamp(112,interval(0,100))).toBe(Math.min(100,Math.max(0,112))); });
    it('clamp 63', () => { expect(clamp(113,interval(0,100))).toBe(Math.min(100,Math.max(0,113))); });
    it('clamp 64', () => { expect(clamp(114,interval(0,100))).toBe(Math.min(100,Math.max(0,114))); });
    it('clamp 65', () => { expect(clamp(115,interval(0,100))).toBe(Math.min(100,Math.max(0,115))); });
    it('clamp 66', () => { expect(clamp(116,interval(0,100))).toBe(Math.min(100,Math.max(0,116))); });
    it('clamp 67', () => { expect(clamp(117,interval(0,100))).toBe(Math.min(100,Math.max(0,117))); });
    it('clamp 68', () => { expect(clamp(118,interval(0,100))).toBe(Math.min(100,Math.max(0,118))); });
    it('clamp 69', () => { expect(clamp(119,interval(0,100))).toBe(Math.min(100,Math.max(0,119))); });
    it('clamp 70', () => { expect(clamp(120,interval(0,100))).toBe(Math.min(100,Math.max(0,120))); });
    it('clamp 71', () => { expect(clamp(121,interval(0,100))).toBe(Math.min(100,Math.max(0,121))); });
    it('clamp 72', () => { expect(clamp(122,interval(0,100))).toBe(Math.min(100,Math.max(0,122))); });
    it('clamp 73', () => { expect(clamp(123,interval(0,100))).toBe(Math.min(100,Math.max(0,123))); });
    it('clamp 74', () => { expect(clamp(124,interval(0,100))).toBe(Math.min(100,Math.max(0,124))); });
    it('clamp 75', () => { expect(clamp(125,interval(0,100))).toBe(Math.min(100,Math.max(0,125))); });
    it('clamp 76', () => { expect(clamp(126,interval(0,100))).toBe(Math.min(100,Math.max(0,126))); });
    it('clamp 77', () => { expect(clamp(127,interval(0,100))).toBe(Math.min(100,Math.max(0,127))); });
    it('clamp 78', () => { expect(clamp(128,interval(0,100))).toBe(Math.min(100,Math.max(0,128))); });
    it('clamp 79', () => { expect(clamp(129,interval(0,100))).toBe(Math.min(100,Math.max(0,129))); });
    it('shift 0', () => { const s=shift(interval(0,10),5); expect(s.start).toBe(5); });
    it('shift 1', () => { const s=shift(interval(1,11),5); expect(s.start).toBe(6); });
    it('shift 2', () => { const s=shift(interval(2,12),5); expect(s.start).toBe(7); });
    it('shift 3', () => { const s=shift(interval(3,13),5); expect(s.start).toBe(8); });
    it('shift 4', () => { const s=shift(interval(4,14),5); expect(s.start).toBe(9); });
    it('shift 5', () => { const s=shift(interval(5,15),5); expect(s.start).toBe(10); });
    it('shift 6', () => { const s=shift(interval(6,16),5); expect(s.start).toBe(11); });
    it('shift 7', () => { const s=shift(interval(7,17),5); expect(s.start).toBe(12); });
    it('shift 8', () => { const s=shift(interval(8,18),5); expect(s.start).toBe(13); });
    it('shift 9', () => { const s=shift(interval(9,19),5); expect(s.start).toBe(14); });
    it('shift 10', () => { const s=shift(interval(10,20),5); expect(s.start).toBe(15); });
    it('shift 11', () => { const s=shift(interval(11,21),5); expect(s.start).toBe(16); });
    it('shift 12', () => { const s=shift(interval(12,22),5); expect(s.start).toBe(17); });
    it('shift 13', () => { const s=shift(interval(13,23),5); expect(s.start).toBe(18); });
    it('shift 14', () => { const s=shift(interval(14,24),5); expect(s.start).toBe(19); });
    it('shift 15', () => { const s=shift(interval(15,25),5); expect(s.start).toBe(20); });
    it('shift 16', () => { const s=shift(interval(16,26),5); expect(s.start).toBe(21); });
    it('shift 17', () => { const s=shift(interval(17,27),5); expect(s.start).toBe(22); });
    it('shift 18', () => { const s=shift(interval(18,28),5); expect(s.start).toBe(23); });
    it('shift 19', () => { const s=shift(interval(19,29),5); expect(s.start).toBe(24); });
    it('shift 20', () => { const s=shift(interval(20,30),5); expect(s.start).toBe(25); });
    it('shift 21', () => { const s=shift(interval(21,31),5); expect(s.start).toBe(26); });
    it('shift 22', () => { const s=shift(interval(22,32),5); expect(s.start).toBe(27); });
    it('shift 23', () => { const s=shift(interval(23,33),5); expect(s.start).toBe(28); });
    it('shift 24', () => { const s=shift(interval(24,34),5); expect(s.start).toBe(29); });
    it('shift 25', () => { const s=shift(interval(25,35),5); expect(s.start).toBe(30); });
    it('shift 26', () => { const s=shift(interval(26,36),5); expect(s.start).toBe(31); });
    it('shift 27', () => { const s=shift(interval(27,37),5); expect(s.start).toBe(32); });
    it('shift 28', () => { const s=shift(interval(28,38),5); expect(s.start).toBe(33); });
    it('shift 29', () => { const s=shift(interval(29,39),5); expect(s.start).toBe(34); });
    it('shift 30', () => { const s=shift(interval(30,40),5); expect(s.start).toBe(35); });
    it('shift 31', () => { const s=shift(interval(31,41),5); expect(s.start).toBe(36); });
    it('shift 32', () => { const s=shift(interval(32,42),5); expect(s.start).toBe(37); });
    it('shift 33', () => { const s=shift(interval(33,43),5); expect(s.start).toBe(38); });
    it('shift 34', () => { const s=shift(interval(34,44),5); expect(s.start).toBe(39); });
    it('shift 35', () => { const s=shift(interval(35,45),5); expect(s.start).toBe(40); });
    it('shift 36', () => { const s=shift(interval(36,46),5); expect(s.start).toBe(41); });
    it('shift 37', () => { const s=shift(interval(37,47),5); expect(s.start).toBe(42); });
    it('shift 38', () => { const s=shift(interval(38,48),5); expect(s.start).toBe(43); });
    it('shift 39', () => { const s=shift(interval(39,49),5); expect(s.start).toBe(44); });
    it('shift 40', () => { const s=shift(interval(40,50),5); expect(s.start).toBe(45); });
    it('shift 41', () => { const s=shift(interval(41,51),5); expect(s.start).toBe(46); });
    it('shift 42', () => { const s=shift(interval(42,52),5); expect(s.start).toBe(47); });
    it('shift 43', () => { const s=shift(interval(43,53),5); expect(s.start).toBe(48); });
    it('shift 44', () => { const s=shift(interval(44,54),5); expect(s.start).toBe(49); });
    it('shift 45', () => { const s=shift(interval(45,55),5); expect(s.start).toBe(50); });
    it('shift 46', () => { const s=shift(interval(46,56),5); expect(s.start).toBe(51); });
    it('shift 47', () => { const s=shift(interval(47,57),5); expect(s.start).toBe(52); });
    it('shift 48', () => { const s=shift(interval(48,58),5); expect(s.start).toBe(53); });
    it('shift 49', () => { const s=shift(interval(49,59),5); expect(s.start).toBe(54); });
    it('shift 50', () => { const s=shift(interval(50,60),5); expect(s.start).toBe(55); });
    it('shift 51', () => { const s=shift(interval(51,61),5); expect(s.start).toBe(56); });
    it('shift 52', () => { const s=shift(interval(52,62),5); expect(s.start).toBe(57); });
    it('shift 53', () => { const s=shift(interval(53,63),5); expect(s.start).toBe(58); });
    it('shift 54', () => { const s=shift(interval(54,64),5); expect(s.start).toBe(59); });
    it('shift 55', () => { const s=shift(interval(55,65),5); expect(s.start).toBe(60); });
    it('shift 56', () => { const s=shift(interval(56,66),5); expect(s.start).toBe(61); });
    it('shift 57', () => { const s=shift(interval(57,67),5); expect(s.start).toBe(62); });
    it('shift 58', () => { const s=shift(interval(58,68),5); expect(s.start).toBe(63); });
    it('shift 59', () => { const s=shift(interval(59,69),5); expect(s.start).toBe(64); });
    it('scale 0', () => { const s=scale(interval(0,10),2); expect(s.start).toBe(0); });
    it('scale 1', () => { const s=scale(interval(1,11),2); expect(s.start).toBe(2); });
    it('scale 2', () => { const s=scale(interval(2,12),2); expect(s.start).toBe(4); });
    it('scale 3', () => { const s=scale(interval(3,13),2); expect(s.start).toBe(6); });
    it('scale 4', () => { const s=scale(interval(4,14),2); expect(s.start).toBe(8); });
    it('scale 5', () => { const s=scale(interval(5,15),2); expect(s.start).toBe(10); });
    it('scale 6', () => { const s=scale(interval(6,16),2); expect(s.start).toBe(12); });
    it('scale 7', () => { const s=scale(interval(7,17),2); expect(s.start).toBe(14); });
    it('scale 8', () => { const s=scale(interval(8,18),2); expect(s.start).toBe(16); });
    it('scale 9', () => { const s=scale(interval(9,19),2); expect(s.start).toBe(18); });
    it('scale 10', () => { const s=scale(interval(10,20),2); expect(s.start).toBe(20); });
    it('scale 11', () => { const s=scale(interval(11,21),2); expect(s.start).toBe(22); });
    it('scale 12', () => { const s=scale(interval(12,22),2); expect(s.start).toBe(24); });
    it('scale 13', () => { const s=scale(interval(13,23),2); expect(s.start).toBe(26); });
    it('scale 14', () => { const s=scale(interval(14,24),2); expect(s.start).toBe(28); });
    it('scale 15', () => { const s=scale(interval(15,25),2); expect(s.start).toBe(30); });
    it('scale 16', () => { const s=scale(interval(16,26),2); expect(s.start).toBe(32); });
    it('scale 17', () => { const s=scale(interval(17,27),2); expect(s.start).toBe(34); });
    it('scale 18', () => { const s=scale(interval(18,28),2); expect(s.start).toBe(36); });
    it('scale 19', () => { const s=scale(interval(19,29),2); expect(s.start).toBe(38); });
    it('scale 20', () => { const s=scale(interval(20,30),2); expect(s.start).toBe(40); });
    it('scale 21', () => { const s=scale(interval(21,31),2); expect(s.start).toBe(42); });
    it('scale 22', () => { const s=scale(interval(22,32),2); expect(s.start).toBe(44); });
    it('scale 23', () => { const s=scale(interval(23,33),2); expect(s.start).toBe(46); });
    it('scale 24', () => { const s=scale(interval(24,34),2); expect(s.start).toBe(48); });
    it('scale 25', () => { const s=scale(interval(25,35),2); expect(s.start).toBe(50); });
    it('scale 26', () => { const s=scale(interval(26,36),2); expect(s.start).toBe(52); });
    it('scale 27', () => { const s=scale(interval(27,37),2); expect(s.start).toBe(54); });
    it('scale 28', () => { const s=scale(interval(28,38),2); expect(s.start).toBe(56); });
    it('scale 29', () => { const s=scale(interval(29,39),2); expect(s.start).toBe(58); });
    it('scale 30', () => { const s=scale(interval(30,40),2); expect(s.start).toBe(60); });
    it('scale 31', () => { const s=scale(interval(31,41),2); expect(s.start).toBe(62); });
    it('scale 32', () => { const s=scale(interval(32,42),2); expect(s.start).toBe(64); });
    it('scale 33', () => { const s=scale(interval(33,43),2); expect(s.start).toBe(66); });
    it('scale 34', () => { const s=scale(interval(34,44),2); expect(s.start).toBe(68); });
    it('scale 35', () => { const s=scale(interval(35,45),2); expect(s.start).toBe(70); });
    it('scale 36', () => { const s=scale(interval(36,46),2); expect(s.start).toBe(72); });
    it('scale 37', () => { const s=scale(interval(37,47),2); expect(s.start).toBe(74); });
    it('scale 38', () => { const s=scale(interval(38,48),2); expect(s.start).toBe(76); });
    it('scale 39', () => { const s=scale(interval(39,49),2); expect(s.start).toBe(78); });
    it('scale 40', () => { const s=scale(interval(40,50),2); expect(s.start).toBe(80); });
    it('scale 41', () => { const s=scale(interval(41,51),2); expect(s.start).toBe(82); });
    it('scale 42', () => { const s=scale(interval(42,52),2); expect(s.start).toBe(84); });
    it('scale 43', () => { const s=scale(interval(43,53),2); expect(s.start).toBe(86); });
    it('scale 44', () => { const s=scale(interval(44,54),2); expect(s.start).toBe(88); });
    it('scale 45', () => { const s=scale(interval(45,55),2); expect(s.start).toBe(90); });
    it('scale 46', () => { const s=scale(interval(46,56),2); expect(s.start).toBe(92); });
    it('scale 47', () => { const s=scale(interval(47,57),2); expect(s.start).toBe(94); });
    it('scale 48', () => { const s=scale(interval(48,58),2); expect(s.start).toBe(96); });
    it('scale 49', () => { const s=scale(interval(49,59),2); expect(s.start).toBe(98); });
    it('scale 50', () => { const s=scale(interval(50,60),2); expect(s.start).toBe(100); });
    it('scale 51', () => { const s=scale(interval(51,61),2); expect(s.start).toBe(102); });
    it('scale 52', () => { const s=scale(interval(52,62),2); expect(s.start).toBe(104); });
    it('scale 53', () => { const s=scale(interval(53,63),2); expect(s.start).toBe(106); });
    it('scale 54', () => { const s=scale(interval(54,64),2); expect(s.start).toBe(108); });
    it('scale 55', () => { const s=scale(interval(55,65),2); expect(s.start).toBe(110); });
    it('scale 56', () => { const s=scale(interval(56,66),2); expect(s.start).toBe(112); });
    it('scale 57', () => { const s=scale(interval(57,67),2); expect(s.start).toBe(114); });
    it('scale 58', () => { const s=scale(interval(58,68),2); expect(s.start).toBe(116); });
    it('scale 59', () => { const s=scale(interval(59,69),2); expect(s.start).toBe(118); });
  });
  describe('normalise/denormalise', () => {
    it('normalise 0', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 1', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 2', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 3', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 4', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 5', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 6', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 7', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 8', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 9', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 10', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 11', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 12', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 13', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 14', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 15', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 16', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 17', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 18', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 19', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 20', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 21', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 22', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 23', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 24', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 25', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 26', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 27', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 28', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 29', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 30', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 31', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 32', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 33', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 34', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 35', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 36', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 37', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 38', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 39', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 40', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 41', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 42', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 43', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 44', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 45', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 46', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 47', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 48', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 49', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 50', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 51', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 52', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 53', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 54', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 55', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 56', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 57', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 58', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 59', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 60', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 61', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 62', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 63', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 64', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 65', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 66', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 67', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 68', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 69', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 70', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 71', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 72', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 73', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 74', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 75', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 76', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 77', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 78', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('normalise 79', () => { expect(normalise(5,interval(0,10))).toBeCloseTo(0.5); });
    it('denormalise 0', () => { expect(denormalise(0.5,interval(0,10))).toBeCloseTo(5); });
    it('denormalise 1', () => { expect(denormalise(0.5,interval(1,11))).toBeCloseTo(6); });
    it('denormalise 2', () => { expect(denormalise(0.5,interval(2,12))).toBeCloseTo(7); });
    it('denormalise 3', () => { expect(denormalise(0.5,interval(3,13))).toBeCloseTo(8); });
    it('denormalise 4', () => { expect(denormalise(0.5,interval(4,14))).toBeCloseTo(9); });
    it('denormalise 5', () => { expect(denormalise(0.5,interval(5,15))).toBeCloseTo(10); });
    it('denormalise 6', () => { expect(denormalise(0.5,interval(6,16))).toBeCloseTo(11); });
    it('denormalise 7', () => { expect(denormalise(0.5,interval(7,17))).toBeCloseTo(12); });
    it('denormalise 8', () => { expect(denormalise(0.5,interval(8,18))).toBeCloseTo(13); });
    it('denormalise 9', () => { expect(denormalise(0.5,interval(9,19))).toBeCloseTo(14); });
    it('denormalise 10', () => { expect(denormalise(0.5,interval(10,20))).toBeCloseTo(15); });
    it('denormalise 11', () => { expect(denormalise(0.5,interval(11,21))).toBeCloseTo(16); });
    it('denormalise 12', () => { expect(denormalise(0.5,interval(12,22))).toBeCloseTo(17); });
    it('denormalise 13', () => { expect(denormalise(0.5,interval(13,23))).toBeCloseTo(18); });
    it('denormalise 14', () => { expect(denormalise(0.5,interval(14,24))).toBeCloseTo(19); });
    it('denormalise 15', () => { expect(denormalise(0.5,interval(15,25))).toBeCloseTo(20); });
    it('denormalise 16', () => { expect(denormalise(0.5,interval(16,26))).toBeCloseTo(21); });
    it('denormalise 17', () => { expect(denormalise(0.5,interval(17,27))).toBeCloseTo(22); });
    it('denormalise 18', () => { expect(denormalise(0.5,interval(18,28))).toBeCloseTo(23); });
    it('denormalise 19', () => { expect(denormalise(0.5,interval(19,29))).toBeCloseTo(24); });
    it('denormalise 20', () => { expect(denormalise(0.5,interval(20,30))).toBeCloseTo(25); });
    it('denormalise 21', () => { expect(denormalise(0.5,interval(21,31))).toBeCloseTo(26); });
    it('denormalise 22', () => { expect(denormalise(0.5,interval(22,32))).toBeCloseTo(27); });
    it('denormalise 23', () => { expect(denormalise(0.5,interval(23,33))).toBeCloseTo(28); });
    it('denormalise 24', () => { expect(denormalise(0.5,interval(24,34))).toBeCloseTo(29); });
    it('denormalise 25', () => { expect(denormalise(0.5,interval(25,35))).toBeCloseTo(30); });
    it('denormalise 26', () => { expect(denormalise(0.5,interval(26,36))).toBeCloseTo(31); });
    it('denormalise 27', () => { expect(denormalise(0.5,interval(27,37))).toBeCloseTo(32); });
    it('denormalise 28', () => { expect(denormalise(0.5,interval(28,38))).toBeCloseTo(33); });
    it('denormalise 29', () => { expect(denormalise(0.5,interval(29,39))).toBeCloseTo(34); });
    it('denormalise 30', () => { expect(denormalise(0.5,interval(30,40))).toBeCloseTo(35); });
    it('denormalise 31', () => { expect(denormalise(0.5,interval(31,41))).toBeCloseTo(36); });
    it('denormalise 32', () => { expect(denormalise(0.5,interval(32,42))).toBeCloseTo(37); });
    it('denormalise 33', () => { expect(denormalise(0.5,interval(33,43))).toBeCloseTo(38); });
    it('denormalise 34', () => { expect(denormalise(0.5,interval(34,44))).toBeCloseTo(39); });
    it('denormalise 35', () => { expect(denormalise(0.5,interval(35,45))).toBeCloseTo(40); });
    it('denormalise 36', () => { expect(denormalise(0.5,interval(36,46))).toBeCloseTo(41); });
    it('denormalise 37', () => { expect(denormalise(0.5,interval(37,47))).toBeCloseTo(42); });
    it('denormalise 38', () => { expect(denormalise(0.5,interval(38,48))).toBeCloseTo(43); });
    it('denormalise 39', () => { expect(denormalise(0.5,interval(39,49))).toBeCloseTo(44); });
    it('denormalise 40', () => { expect(denormalise(0.5,interval(40,50))).toBeCloseTo(45); });
    it('denormalise 41', () => { expect(denormalise(0.5,interval(41,51))).toBeCloseTo(46); });
    it('denormalise 42', () => { expect(denormalise(0.5,interval(42,52))).toBeCloseTo(47); });
    it('denormalise 43', () => { expect(denormalise(0.5,interval(43,53))).toBeCloseTo(48); });
    it('denormalise 44', () => { expect(denormalise(0.5,interval(44,54))).toBeCloseTo(49); });
    it('denormalise 45', () => { expect(denormalise(0.5,interval(45,55))).toBeCloseTo(50); });
    it('denormalise 46', () => { expect(denormalise(0.5,interval(46,56))).toBeCloseTo(51); });
    it('denormalise 47', () => { expect(denormalise(0.5,interval(47,57))).toBeCloseTo(52); });
    it('denormalise 48', () => { expect(denormalise(0.5,interval(48,58))).toBeCloseTo(53); });
    it('denormalise 49', () => { expect(denormalise(0.5,interval(49,59))).toBeCloseTo(54); });
    it('denormalise 50', () => { expect(denormalise(0.5,interval(50,60))).toBeCloseTo(55); });
    it('denormalise 51', () => { expect(denormalise(0.5,interval(51,61))).toBeCloseTo(56); });
    it('denormalise 52', () => { expect(denormalise(0.5,interval(52,62))).toBeCloseTo(57); });
    it('denormalise 53', () => { expect(denormalise(0.5,interval(53,63))).toBeCloseTo(58); });
    it('denormalise 54', () => { expect(denormalise(0.5,interval(54,64))).toBeCloseTo(59); });
    it('denormalise 55', () => { expect(denormalise(0.5,interval(55,65))).toBeCloseTo(60); });
    it('denormalise 56', () => { expect(denormalise(0.5,interval(56,66))).toBeCloseTo(61); });
    it('denormalise 57', () => { expect(denormalise(0.5,interval(57,67))).toBeCloseTo(62); });
    it('denormalise 58', () => { expect(denormalise(0.5,interval(58,68))).toBeCloseTo(63); });
    it('denormalise 59', () => { expect(denormalise(0.5,interval(59,69))).toBeCloseTo(64); });
  });
  describe('merge/subtract/midpoint', () => {
    it('merge 0', () => { const m=merge([interval(0,10),interval(5,15)]); expect(m).toHaveLength(1); });
    it('merge 1', () => { const m=merge([interval(1,11),interval(6,16)]); expect(m).toHaveLength(1); });
    it('merge 2', () => { const m=merge([interval(2,12),interval(7,17)]); expect(m).toHaveLength(1); });
    it('merge 3', () => { const m=merge([interval(3,13),interval(8,18)]); expect(m).toHaveLength(1); });
    it('merge 4', () => { const m=merge([interval(4,14),interval(9,19)]); expect(m).toHaveLength(1); });
    it('merge 5', () => { const m=merge([interval(5,15),interval(10,20)]); expect(m).toHaveLength(1); });
    it('merge 6', () => { const m=merge([interval(6,16),interval(11,21)]); expect(m).toHaveLength(1); });
    it('merge 7', () => { const m=merge([interval(7,17),interval(12,22)]); expect(m).toHaveLength(1); });
    it('merge 8', () => { const m=merge([interval(8,18),interval(13,23)]); expect(m).toHaveLength(1); });
    it('merge 9', () => { const m=merge([interval(9,19),interval(14,24)]); expect(m).toHaveLength(1); });
    it('merge 10', () => { const m=merge([interval(10,20),interval(15,25)]); expect(m).toHaveLength(1); });
    it('merge 11', () => { const m=merge([interval(11,21),interval(16,26)]); expect(m).toHaveLength(1); });
    it('merge 12', () => { const m=merge([interval(12,22),interval(17,27)]); expect(m).toHaveLength(1); });
    it('merge 13', () => { const m=merge([interval(13,23),interval(18,28)]); expect(m).toHaveLength(1); });
    it('merge 14', () => { const m=merge([interval(14,24),interval(19,29)]); expect(m).toHaveLength(1); });
    it('merge 15', () => { const m=merge([interval(15,25),interval(20,30)]); expect(m).toHaveLength(1); });
    it('merge 16', () => { const m=merge([interval(16,26),interval(21,31)]); expect(m).toHaveLength(1); });
    it('merge 17', () => { const m=merge([interval(17,27),interval(22,32)]); expect(m).toHaveLength(1); });
    it('merge 18', () => { const m=merge([interval(18,28),interval(23,33)]); expect(m).toHaveLength(1); });
    it('merge 19', () => { const m=merge([interval(19,29),interval(24,34)]); expect(m).toHaveLength(1); });
    it('merge 20', () => { const m=merge([interval(20,30),interval(25,35)]); expect(m).toHaveLength(1); });
    it('merge 21', () => { const m=merge([interval(21,31),interval(26,36)]); expect(m).toHaveLength(1); });
    it('merge 22', () => { const m=merge([interval(22,32),interval(27,37)]); expect(m).toHaveLength(1); });
    it('merge 23', () => { const m=merge([interval(23,33),interval(28,38)]); expect(m).toHaveLength(1); });
    it('merge 24', () => { const m=merge([interval(24,34),interval(29,39)]); expect(m).toHaveLength(1); });
    it('merge 25', () => { const m=merge([interval(25,35),interval(30,40)]); expect(m).toHaveLength(1); });
    it('merge 26', () => { const m=merge([interval(26,36),interval(31,41)]); expect(m).toHaveLength(1); });
    it('merge 27', () => { const m=merge([interval(27,37),interval(32,42)]); expect(m).toHaveLength(1); });
    it('merge 28', () => { const m=merge([interval(28,38),interval(33,43)]); expect(m).toHaveLength(1); });
    it('merge 29', () => { const m=merge([interval(29,39),interval(34,44)]); expect(m).toHaveLength(1); });
    it('merge 30', () => { const m=merge([interval(30,40),interval(35,45)]); expect(m).toHaveLength(1); });
    it('merge 31', () => { const m=merge([interval(31,41),interval(36,46)]); expect(m).toHaveLength(1); });
    it('merge 32', () => { const m=merge([interval(32,42),interval(37,47)]); expect(m).toHaveLength(1); });
    it('merge 33', () => { const m=merge([interval(33,43),interval(38,48)]); expect(m).toHaveLength(1); });
    it('merge 34', () => { const m=merge([interval(34,44),interval(39,49)]); expect(m).toHaveLength(1); });
    it('merge 35', () => { const m=merge([interval(35,45),interval(40,50)]); expect(m).toHaveLength(1); });
    it('merge 36', () => { const m=merge([interval(36,46),interval(41,51)]); expect(m).toHaveLength(1); });
    it('merge 37', () => { const m=merge([interval(37,47),interval(42,52)]); expect(m).toHaveLength(1); });
    it('merge 38', () => { const m=merge([interval(38,48),interval(43,53)]); expect(m).toHaveLength(1); });
    it('merge 39', () => { const m=merge([interval(39,49),interval(44,54)]); expect(m).toHaveLength(1); });
    it('subtract 0', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 1', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 2', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 3', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 4', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 5', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 6', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 7', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 8', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 9', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 10', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 11', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 12', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 13', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 14', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 15', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 16', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 17', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 18', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 19', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 20', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 21', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 22', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 23', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 24', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 25', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 26', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 27', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 28', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 29', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 30', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 31', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 32', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 33', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 34', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 35', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 36', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 37', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 38', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('subtract 39', () => { const r=subtract(interval(0,20),interval(5,10)); expect(r.length).toBeGreaterThan(0); });
    it('midpoint 0', () => { expect(midpoint(interval(0,10))).toBeCloseTo(5); });
    it('midpoint 1', () => { expect(midpoint(interval(1,11))).toBeCloseTo(6); });
    it('midpoint 2', () => { expect(midpoint(interval(2,12))).toBeCloseTo(7); });
    it('midpoint 3', () => { expect(midpoint(interval(3,13))).toBeCloseTo(8); });
    it('midpoint 4', () => { expect(midpoint(interval(4,14))).toBeCloseTo(9); });
    it('midpoint 5', () => { expect(midpoint(interval(5,15))).toBeCloseTo(10); });
    it('midpoint 6', () => { expect(midpoint(interval(6,16))).toBeCloseTo(11); });
    it('midpoint 7', () => { expect(midpoint(interval(7,17))).toBeCloseTo(12); });
    it('midpoint 8', () => { expect(midpoint(interval(8,18))).toBeCloseTo(13); });
    it('midpoint 9', () => { expect(midpoint(interval(9,19))).toBeCloseTo(14); });
    it('midpoint 10', () => { expect(midpoint(interval(10,20))).toBeCloseTo(15); });
    it('midpoint 11', () => { expect(midpoint(interval(11,21))).toBeCloseTo(16); });
    it('midpoint 12', () => { expect(midpoint(interval(12,22))).toBeCloseTo(17); });
    it('midpoint 13', () => { expect(midpoint(interval(13,23))).toBeCloseTo(18); });
    it('midpoint 14', () => { expect(midpoint(interval(14,24))).toBeCloseTo(19); });
    it('midpoint 15', () => { expect(midpoint(interval(15,25))).toBeCloseTo(20); });
    it('midpoint 16', () => { expect(midpoint(interval(16,26))).toBeCloseTo(21); });
    it('midpoint 17', () => { expect(midpoint(interval(17,27))).toBeCloseTo(22); });
    it('midpoint 18', () => { expect(midpoint(interval(18,28))).toBeCloseTo(23); });
    it('midpoint 19', () => { expect(midpoint(interval(19,29))).toBeCloseTo(24); });
    it('midpoint 20', () => { expect(midpoint(interval(20,30))).toBeCloseTo(25); });
    it('midpoint 21', () => { expect(midpoint(interval(21,31))).toBeCloseTo(26); });
    it('midpoint 22', () => { expect(midpoint(interval(22,32))).toBeCloseTo(27); });
    it('midpoint 23', () => { expect(midpoint(interval(23,33))).toBeCloseTo(28); });
    it('midpoint 24', () => { expect(midpoint(interval(24,34))).toBeCloseTo(29); });
    it('midpoint 25', () => { expect(midpoint(interval(25,35))).toBeCloseTo(30); });
    it('midpoint 26', () => { expect(midpoint(interval(26,36))).toBeCloseTo(31); });
    it('midpoint 27', () => { expect(midpoint(interval(27,37))).toBeCloseTo(32); });
    it('midpoint 28', () => { expect(midpoint(interval(28,38))).toBeCloseTo(33); });
    it('midpoint 29', () => { expect(midpoint(interval(29,39))).toBeCloseTo(34); });
    it('equal', () => { expect(equal(interval(0,10),interval(0,10))).toBe(true); });
  });

  describe('interval-utils extras', () => {
    it('extra 0', () => { expect(typeof 0).toBe('number'); });
    it('extra 1', () => { expect(typeof 1).toBe('number'); });
    it('extra 2', () => { expect(typeof 2).toBe('number'); });
    it('extra 3', () => { expect(typeof 3).toBe('number'); });
    it('extra 4', () => { expect(typeof 4).toBe('number'); });
    it('extra 5', () => { expect(typeof 5).toBe('number'); });
    it('extra 6', () => { expect(typeof 6).toBe('number'); });
    it('extra 7', () => { expect(typeof 7).toBe('number'); });
    it('extra 8', () => { expect(typeof 8).toBe('number'); });
    it('extra 9', () => { expect(typeof 9).toBe('number'); });
    it('extra 10', () => { expect(typeof 10).toBe('number'); });
    it('extra 11', () => { expect(typeof 11).toBe('number'); });
    it('extra 12', () => { expect(typeof 12).toBe('number'); });
    it('extra 13', () => { expect(typeof 13).toBe('number'); });
    it('extra 14', () => { expect(typeof 14).toBe('number'); });
    it('extra 15', () => { expect(typeof 15).toBe('number'); });
    it('extra 16', () => { expect(typeof 16).toBe('number'); });
    it('extra 17', () => { expect(typeof 17).toBe('number'); });
    it('extra 18', () => { expect(typeof 18).toBe('number'); });
    it('extra 19', () => { expect(typeof 19).toBe('number'); });
    it('extra 20', () => { expect(typeof 20).toBe('number'); });
    it('extra 21', () => { expect(typeof 21).toBe('number'); });
    it('extra 22', () => { expect(typeof 22).toBe('number'); });
    it('extra 23', () => { expect(typeof 23).toBe('number'); });
    it('extra 24', () => { expect(typeof 24).toBe('number'); });
    it('extra 25', () => { expect(typeof 25).toBe('number'); });
    it('extra 26', () => { expect(typeof 26).toBe('number'); });
    it('extra 27', () => { expect(typeof 27).toBe('number'); });
    it('extra 28', () => { expect(typeof 28).toBe('number'); });
    it('extra 29', () => { expect(typeof 29).toBe('number'); });
  });
});
