// Copyright (c) 2026 Nexara DMCC. All rights reserved.
// CONFIDENTIAL — TRADE SECRET.

import type { KeyboardShortcut } from './types';

export const DEFAULT_SHORTCUTS: KeyboardShortcut[] = [
  // ── Global ───────────────────────────────────────────────────────
  {
    id: 'global.command-palette',
    keys: 'Cmd+K',
    description: 'Open command palette',
    category: 'global',
    modifiers: ['meta'],
    key: 'k',
    enabled: true,
  },
  {
    id: 'global.help',
    keys: 'Cmd+/',
    description: 'Open help panel',
    category: 'global',
    modifiers: ['meta'],
    key: '/',
    enabled: true,
  },
  {
    id: 'global.search',
    keys: '/',
    description: 'Focus global search',
    category: 'global',
    key: '/',
    modifiers: [],
    enabled: true,
  },
  {
    id: 'global.shortcuts-help',
    keys: '?',
    description: 'Show keyboard shortcuts help',
    category: 'global',
    key: '?',
    modifiers: [],
    enabled: true,
  },

  // ── Navigation (chord: G then X) ─────────────────────────────────
  {
    id: 'nav.dashboard',
    keys: 'G then D',
    description: 'Go to dashboard',
    category: 'navigation',
    chord: ['g', 'd'],
    enabled: true,
  },
  {
    id: 'nav.quality',
    keys: 'G then Q',
    description: 'Go to quality module',
    category: 'navigation',
    chord: ['g', 'q'],
    enabled: true,
  },
  {
    id: 'nav.health-safety',
    keys: 'G then H',
    description: 'Go to health & safety module',
    category: 'navigation',
    chord: ['g', 'h'],
    enabled: true,
  },
  {
    id: 'nav.environment',
    keys: 'G then E',
    description: 'Go to environment module',
    category: 'navigation',
    chord: ['g', 'e'],
    enabled: true,
  },
  {
    id: 'nav.risk',
    keys: 'G then R',
    description: 'Go to risk module',
    category: 'navigation',
    chord: ['g', 'r'],
    enabled: true,
  },
  {
    id: 'nav.analytics',
    keys: 'G then A',
    description: 'Go to analytics module',
    category: 'navigation',
    chord: ['g', 'a'],
    enabled: true,
  },
  {
    id: 'nav.incidents',
    keys: 'G then I',
    description: 'Go to incidents module',
    category: 'navigation',
    chord: ['g', 'i'],
    enabled: true,
  },
  {
    id: 'nav.documents',
    keys: 'G then O',
    description: 'Go to documents module',
    category: 'navigation',
    chord: ['g', 'o'],
    enabled: true,
  },

  // ── Actions (chord: C then X) ─────────────────────────────────────
  {
    id: 'action.new-ncr',
    keys: 'C then N',
    description: 'Create new NCR',
    category: 'actions',
    chord: ['c', 'n'],
    enabled: true,
  },
  {
    id: 'action.new-capa',
    keys: 'C then C',
    description: 'Create new CAPA',
    category: 'actions',
    chord: ['c', 'c'],
    enabled: true,
  },
  {
    id: 'action.new-incident',
    keys: 'C then I',
    description: 'Create new incident',
    category: 'actions',
    chord: ['c', 'i'],
    enabled: true,
  },
  {
    id: 'action.new-risk',
    keys: 'C then R',
    description: 'Create new risk',
    category: 'actions',
    chord: ['c', 'r'],
    enabled: true,
  },
  {
    id: 'action.new-audit',
    keys: 'C then A',
    description: 'Create new audit',
    category: 'actions',
    chord: ['c', 'a'],
    enabled: true,
  },
  {
    id: 'action.new-document',
    keys: 'C then D',
    description: 'Create new document',
    category: 'actions',
    chord: ['c', 'd'],
    enabled: true,
  },

  // ── UI ────────────────────────────────────────────────────────────
  {
    id: 'ui.toggle-sidebar',
    keys: 'Cmd+B',
    description: 'Toggle sidebar',
    category: 'ui',
    modifiers: ['meta'],
    key: 'b',
    enabled: true,
  },
  {
    id: 'ui.close-modal',
    keys: 'Escape',
    description: 'Close modal / dismiss overlay',
    category: 'ui',
    key: 'Escape',
    modifiers: [],
    enabled: true,
  },
  {
    id: 'ui.save',
    keys: 'Cmd+S',
    description: 'Save current form',
    category: 'ui',
    modifiers: ['meta'],
    key: 's',
    enabled: true,
  },
  {
    id: 'ui.new-item',
    keys: 'Cmd+N',
    description: 'Create new item in current context',
    category: 'ui',
    modifiers: ['meta'],
    key: 'n',
    enabled: true,
  },
];
